### ISSUE TITLE
Add Multiple Lines to Plot Simultaneously

### ISSUE THREAD

**Issue by MarkTurney** [emilk/egui#1007]
Problem: I would like to add multiple lines to a Plot simultaneously.

Solution: The addition of a new Plot method:

fn lines(mut self, mut lines: Vec<Line>) -> Self

**Comment by emilk** [comment]
Why not just call `.line` multiple times?

**Comment by MarkTurney** [comment]
If you are worried that it would clutter the API, please close this issue.  I will simply add a convenience method to my application.  Thank you!
