### ISSUE TITLE
Context menu on hover / clickable tooltips

### ISSUE THREAD

**Issue by emilk** [emilk/egui#1010]
It would be great to be able to bring up a context menu just by hovering an element. It would act similar to a tooltip, but a tooltip you can interact with (it won't go away when you move the mouse).

**Comment by mankinskin** [comment]
For anyone looking into implementing this, this would probably be an abstraction over the trigger mechanism for bringing up a stationary menu, i.e. a menu created at some other element (represented by `response`):

https://github.com/emilk/egui/blob/2d2022fb7290bf4fcca373ad3a0dc98b680a9203/egui/src/menu.rs#L284-L308

the menu doesn't really have a mechanism for configuring it yet, but I suppose this could be easily added with some enums and a `MenuConfig` struct or something like that.

**Comment by apexys** [comment]
It would also be interesting to be able to open a context menu with a left click or through some other action programmatically.

**Comment by emilk** [comment]
This could also be implemented as "Tooltips stay put when you move the mouse onto them"

**Comment by YgorSouza** [comment]
This could also be seen as a `Window` that is anchored to a `Response` and closes when you click outside it, like the solution proposed for #4463. This is called a `Popup` in other UI libraries, but egui already uses popup to refer to the ComboBox drawer.
