### ISSUE TITLE
egui_glium: Input::key_released never returns true

### ISSUE THREAD

**Issue by tangmi** [emilk/egui#102]
Hi, I noticed that under `egui_glium`, the `Event::Key` doesn't get a chance to fire with `pressed: false`.

I believe the relevant code is around here where the `Event::Key` instances are created:

https://github.com/emilk/egui/blob/e105719d3436b0419733f6a2657d06df4cc1507c/egui_glium/src/lib.rs#L127-L131

Note the conditional in the surrounding block above: https://github.com/emilk/egui/blob/e105719d3436b0419733f6a2657d06df4cc1507c/egui_glium/src/lib.rs#L101

As an a (related) aside, would you be receptive to letting `egui` track the keyboard state across frames, to enable helper methods for `Input::key_down`?

Thanks for your time!

**Comment by emilk** [comment]
Thanks - good catch!

Yeah, I'd be open to have `egui::InputState` track which keys are currently down. It is a very simple change.
