### ISSUE TITLE
ScrollArea show_rows doesn't work

### ISSUE THREAD

**Issue by mjhouse** [emilk/egui#1021]
(*could not find an existing issue and bug is still present in master*)

**Describe the bug**
ScrollArea::show_rows doesn't work with any variation of arguments that I've tried. The range is `0..n` as messages are added to a chat history until `n=row_count`, then it stops extending the range without displaying a scroll bar. 

**To Reproduce**

1. Use the following code (where history is a `Vec<String>`):

```
      let text_style = egui::TextStyle::Body;
      let row_height = ui.fonts()[text_style].row_height();
      let row_count  = 10; // for any n. tested with n=1000 and history.len()=10000

      egui::ScrollArea::vertical()
          .show_rows(ui, row_height, row_count, |ui, range| {
              for row in range {
                  if let Some(message) = history.get(row) {
                      ui.label(format!("{}",message));
                  }
              }
          });
```
2. Add messages to history.

**Expected behavior**
The scroll area should be able to scroll through the full history, but only draw the number of lines specified by `row_count`- centered on the currently visible area. 

**Screenshots**
![scroll_area_show_rows_bug](https://user-images.githubusercontent.com/4141157/147821613-d3f79e72-81aa-4357-ba9f-272be67d9f0f.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: N/A (see additional context)
 - Version: v0.15.0 (egui version)

**Additional context**
I'm using egui through the bevy_egui integration, but I don't believe that should affect this. I'm not using any sort of shortcut functions that could alter behavior.

**Comment by emilk** [comment]
Have you compared your code to the working example in `egui_demo_lib/src/apps/demo/scrolling.rs`?

**Comment by mjhouse** [comment]
I haven't. I'll take a look at it.

**Comment by mjhouse** [comment]
@emilk It looks like I was misunderstanding the purpose of [ScrollArea::show_rows](https://docs.rs/egui/latest/egui/containers/struct.ScrollArea.html#method.show_rows). I thought it was the number of rows to draw, but it's the *total* number of rows. Thanks for the help.
