### ISSUE TITLE
std::time::Instant not supported by WebAssembly

### ISSUE THREAD

**Issue by niklaskorz** [emilk/egui#1022]
The `std::time::Instant` type used in the egui-winit crate is not supported when running through WebAssembly:

```
panicked at 'time not implemented on this platform', library/std/src/sys/wasm/../unsupported/time.rs:13:9
```

WebAssembly could potentially be supported in egui-winit by using a crate such as https://github.com/sebcrozet/instant instead, which only re-exports the `std::time::Instant` type on native but implements a polyfill for WebAssembly targets.

**Comment by niklaskorz** [comment]
The same crate is already used by winit when the wasm-bindgen feature is enabled: https://github.com/rust-windowing/winit/blob/master/Cargo.toml#L26

**Comment by emilk** [comment]
Thanks for the PR!

I have never tried `winit` on the web, so I'm curious how well `egui-winit` work for you, and how it compares to [`egui_web`](https://github.com/emilk/egui/tree/master/egui_web). Do you have a [link](url) to your project? What are you using to render `egui`?

**Comment by niklaskorz** [comment]
I'm using wgpu for rendering, Unfortunatly, my project requires compute shaders, so it won't work with wgpu's WebGL 2 backend and requires real WebGPU support by the browser. Note that due to some recent changes in WGSL, the application partially works in the latest Firefox Nightly right now but not in Chrome Canary. Hopefully, it will fully work again in a month or two when the browsers are updated. But on latest Firefox Nightly, you should see egui working using the commits from the pull request and the demo link below.

- Repository: https://github.com/niklaskorz/linon/
- Web demo: https://niklaskorz.github.io/linon/

**Comment by niklaskorz** [comment]
![grafik](https://user-images.githubusercontent.com/590517/147981283-b8b9ecd9-e820-436d-b489-3cbf1a018ba0.png)

**Comment by niklaskorz** [comment]
egui itself is rendered by https://github.com/hasenbanck/egui_wgpu_backend which I used in combination with https://github.com/hasenbanck/egui_winit_platform before but now migrated to egui-winit.

**Comment by emilk** [comment]
Very cool, thanks for sharing!

There seems to be some problems with input though, e.g. holding down modifiers and moving the cursor in the text edit field doesn't work as expected. Perhaps a limitation of running winit on the web?

**Comment by niklaskorz** [comment]
Hm which modifiers and OS? I can hold down alt, ctrl or shift on Windows and move the cursor using arrow keys just fine. Note that leaving the text field (losing focus) currently freezes the application because of said shader that uses the new `else if` syntax. The same applies to most other control elements and will be fixed automatically when the wgpu version in Firefox Nightly is updated.

**Comment by emilk** [comment]
I'm running firefox nightly on my macbook, and holding down alt,shift or cmd and pressing the arrow keys still only moves the cursor by a single character. Holding down `ctrl` makes the cursor not move at all. cmd-A does not select the text. In short, it seems like all modifier keys are non-working.

**Comment by niklaskorz** [comment]
Ah I misread the "doesn't work as expected" as just "doesn't work". :) Yeah I can reproduce that. 🤔

**Comment by niklaskorz** [comment]
Related issue: https://github.com/rust-windowing/winit/issues/2092
