### ISSUE TITLE
input: add InputState::key_down method

### ISSUE THREAD

**Issue by tangmi** [emilk/egui#105]
Hi, this issue was opened to track adding a `InputState::key_down` that will return if a key is currently being held down. This would be useful for e.g. folks making games using pure `egui`.

This issue was created based on a comment from a previous issue:

> Yeah, I'd be open to have `egui::InputState` track which keys are currently down. It is a very simple change. Feel free to open a separate issue on that (or a PR! a simple `HashSet` should do fine)

_Originally posted by @emilk in https://github.com/emilk/egui/issues/102#issuecomment-758091620_

**Comment by tangmi** [comment]
It looks like `InputState` lives only as long as the current frame. Is the intention for `RawInput` to live longer than that? It looks like the glium backend has a persistent `RawInput` while the web backend creates one per frame

**Comment by emilk** [comment]
`InputState` persists, or rather the one from the previous frame is updated to create the one for the next frame with `InputState::begin_frame` at https://github.com/emilk/egui/blob/master/egui/src/input.rs#L332
