### ISSUE TITLE
Native rendering closures

### ISSUE THREAD

**Issue by LordMZTE** [emilk/egui#1085]
**Is your feature request related to a problem? Please describe.**
With egui, I currently have the problem that rendering inside it is somewhat limited (primitives, text and textures).

**Describe the solution you'd like**
It would be great, if native rendering were possible inside egui (not just over or under egui).

This would be possible to implement, by adding a function to `Ui` which takes a closure, which is then called by the rendering backend in between rendering the `ClippedMesh`es. This closure would then be able to use a captured native rendering context (such as opengl) in order to render whatever it wants to inside the egui UI.

**Comment by t18b219k** [comment]
If you want to render to Image rectangle please consider using NativeTexture trait for rendering .
glow painter implement that trait.
If lmplement it to Ui struct heavry tied to backend and Rust's orphen rule

**Comment by LordMZTE** [comment]
That is actually really cool! I didn't know that was possible!
