### ISSUE TITLE
Allow opting out of the dedicated GPU on macOS

### ISSUE THREAD

**Issue by terhechte** [emilk/egui#1095]
**Is your feature request related to a problem? Please describe.**

There's an issue on [Postsack](https://github.com/terhechte/postsack/issues/32) about high battery consumption of the app when run on MacBook Pros that contain a dedicated GPU. Basically by default any `egui` app switches macOS to the more powerful dedicated GPU. In most cases, though, the internal GPU (of the Intel chipset) would be enough for rendering the app.

Glium supports this via the `with_hardware_acceleration` call. However, `egui_glium` [currently doesn't expose this](https://github.com/emilk/egui/blob/master/egui_glium/src/epi_backend.rs#L17).

**Describe the solution you'd like**

My proposal would be to add an additional `requires_dedicated_gpu` field to [`epi::NativeOptions`](https://docs.rs/epi/0.16.0/epi/struct.NativeOptions.html) and then use that in the `epi_backend`. The default value could be `true` but it would be nice to be able to opt out. The whole thing could also be limited to macOS via `target_os = "macos"`. I'd be willing to implement this in a PR if this solution is approved.

**Describe alternatives you've considered**

Not implementing it would make any egui app on most of the older MacBook Pros out there consume their battery faster (also, heat up and turn on the fans I guess). 

**Additional context**

https://github.com/rust-windowing/glutin/issues/980

**Comment by emilk** [comment]
The new default native backend for `eframe` is [`glow`](https://github.com/grovesNL/glow), so we need to look at how that could be accomplished there.

**Comment by hacknus** [comment]
is there an update to this? I am also interested in a solution for that, but I have no idea where the problematic line is in the glow backend...

**Comment by coderedart** [comment]
it seems glow has nothing to do with this. this seems to be a opengl context creation / loading thing. glow just wraps around the already loaded functions with more rusty types. 

glium uses glutin. egui also uses glutin https://github.com/emilk/egui/blob/master/eframe/src/native/run.rs#L19 . 
just need to add the option and pass it to the glutin builder ^^ and this should work.

**Comment by terhechte** [comment]
Thanks @coderedart I hadn't seen this earlier, I've created a PR to add the functionality to run.rs :)

https://github.com/emilk/egui/pull/1681
