### ISSUE TITLE
Allow passing boolean argument to `ScrollArea::stick_to_right()` and `ScrollArea::stick_to_bottom()`

### ISSUE THREAD

**Issue by mushogenshin** [emilk/egui#1099]
**Is your feature request related to a problem? Please describe.**
For horizontal layouts in my app, instead of deciding whether the newest thing should be at the leftmost or at the rightmost, I want to allow users to choose, therefore I need to add the `ScrollArea::stick_to_right()` dynamically, but I cannot since the function consumes the `ScrollArea`, e.g. I cannot do this:

```rust
let scroll_area = ScrollArea::horizontal();

if newest_at_rightmost {
    scroll_area.stick_to_right();
}

// then same UI code for both layouts here -- newest at leftmost or newest at rightmost.
// this won't compile since `scroll_area` is moved in function call above.
scroll_area.show(ui, |ui| {
    // iterate through items queried from database
});
```

**Describe the solution you'd like**
I'd like that we could pass a `boolean` argument to `ScrollArea::stick_to_right()` and `ScrollArea::stick_to_bottom()`

**Describe alternatives you've considered**
I can use `if..else` blocks but that would lead to a lot of of duplicated code, e.g.

```rust
if newest_at_leftmost {
    ScrollArea::horizontal().show(ui, |ui| {
        // iterate through items queried from database
    });
} else {
    // newest at rightmost
    ScrollArea::horizontal()
        .stick_to_right()
        .show(ui, |ui| {
        // duplicated code to iterate through items queried from database
    });
};
```

Thanks!

**Comment by yusdacra** [comment]
You can do:

```rust
let mut scroll_area = ScrollArea::horizontal();

if bool {
    scroll_area = scroll_area.stick_to_right();
}

scroll_area.show(...);
```

**Comment by mushogenshin** [comment]
Thanks for your suggestion, I did try something similar, but the compiler is not happy:
> 
> ```rust
> let mut scroll_area = ScrollArea::horizontal();
> 
> if bool {
> // scroll_area is moved in this function call
>     scroll_area = scroll_area.stick_to_right();
> }
> // so using scroll_area again here is not allowed
> scroll_area.show(...);
> ```
Not sure if I missed something 🤔

**Comment by mushogenshin** [comment]
Oh sorry, my bad, it works! Thank you so much <3
