### ISSUE TITLE
Feature request: Expose the containers::area::State struct and a method to get the current one on all containers

### ISSUE THREAD

**Issue by ckaran** [emilk/egui#112]
I want to implement a new borderless window-like object that acts like a filter.  As an example, consider a magnifying glass being dragged over a picture; it needs to synchronize its view with the thing it's currently floating over.  I can see that the current location of the window is known and stored in the [`State`](https://docs.rs/egui/0.7.0/src/egui/containers/area.rs.html#12-22) struct, but I don't see how I get access to this from within my own code, which means I don't know where the magnifier is in relation to other objects when I go to do an update.

In my ideal world, I would always have a `Vec` that kept the `State`s in their current Z order, front to back (with non-overlapping objects in an arbitrary order relative to one another).  That way if I have multiple filters (e.g., one that is a magnifier, one that is an X-ray, one that is IR) that are partially overlapping, I could make sensible decisions on what to display based on the order that they are currently in.

**Comment by emilk** [comment]
Sorry for the slow response - I completely missed this one!

---

You can always ask the `ui` directly for it's location (`ui.min_rect()` for the current size). In other words, as you fill in the content of your window you know where that content is. If the x-ray effect is painted using egui methods, this should be enough. If not: store the rectangle somewhere and use later in your renderer.

The window also returns a `Response` with its location after the fact:

``` rust
let response = egui::Window::new(…)…show(…);
let window_rect = response.rect;
```

Again, store that and use in your rendering.

---

Note that egui doesn't store any window titles, so even if egui returned a list of the window rectangles, how would you know which is which window? You can match the `egui::Id`, but then it would be just as easy to just store the window positions as suggested above?

(I guess you could also reconstruct the same `Id` with the same title, but that also feels ugly and error prone)

---

What do you think?

**Comment by ckaran** [comment]
I just tested it, and it's perfect!  Thank you!

BTW, I noticed that [`egui::Id`](https://github.com/emilk/egui/blob/master/egui/src/id.rs) is just a wrapper around a `u64`, but that you can only create them objects that implement `Hash`.  The issue with hashes is that a) they are slow to compute and b) there is no guarantee that there won't be a hash collision in the future.  [`lazy_static`](https://crates.io/crates/lazy_static) and [`AtomicU64`](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicU64.html) might be a better choice for generating unique identifiers:

```rust
use std::sync::atomic::{AtomicU64, Ordering};

lazy_static! {
    // I like to leave the first few values of global identifiers unused
    // as reserved for future internal use.
    static ref EGUI_IDENTIFIERS: AtomicU64 = AtomicU64::new(256);
}

#[derive(Clone, Copy, Hash, Eq, PartialEq)]
#[cfg_attr(feature = "persistence", derive(serde::Deserialize, serde::Serialize))]
pub struct Id(u64);

impl Id {
    pub fn background() -> Self {
        Self(0)
    }

    pub fn tooltip() -> Self {
        Self(1)
    }

    pub fn new() -> Id {
        Self(EGUI_IDENTIFIERS.fetch_add(1, Ordering::SeqCst))
    }

    pub(crate) fn short_debug_format(&self) -> String {
        format!("{:04X}", self.0 as u16)
    }

    pub(crate) fn value(&self) -> u64 {
        self.0
    }
}

impl std::fmt::Debug for Id {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:X}", self.0)
    }
}
```

There's some more work that would be done to implement persistence on top of it, but it shouldn't be too hard to do if you need it.
