### ISSUE TITLE
Bézier Curve Support as a new Plot item

### ISSUE THREAD

**Issue by xudesheng** [emilk/egui#1120]
**Is your feature request related to a problem? Please describe.**
I'm trying to build an editor where all shapes can be simplified into two basic types: Line and Bezier Curve. I couldn't find any item that can work as `Bezier Curve`.

**Describe the solution you'd like**
Better to add `Bezier Curve` as a new `PlotItem` in egui::widgets::plot::items, or add a new type in `enum Shape`
```
#[must_use = "Add a Shape to a Painter"]
#[derive(Clone, Debug, PartialEq)]
pub enum Shape {
    /// Paint nothing. This can be useful as a placeholder.
    Noop,
    /// Recursively nest more shapes - sometimes a convenience to be able to do.
    /// For performance reasons it is better to avoid it.
    Vec(Vec<Shape>),
    Circle(CircleShape),
    LineSegment {
        points: [Pos2; 2],
        stroke: Stroke,
    },
    Path(PathShape),
    Rect(RectShape),
    Text(TextShape),
    Mesh(Mesh),
    C {
       points: [Pos2; 4],
       closed: bool,
       stroke: Stroke,
   }
}
```

**Additional context**
SVG standard supports two types of Bezier Curve. Only to support cubic Bezier Curve should be sufficient enough. It needs 4 points (begin, end, and two control points). This would be equivalent to the `C` command in SVG standard.

**Comment by emilk** [comment]
Supporting cubic Bezier curves in epaint and plot would be nice.

A good first step would be adding `Shape::CubizBezier` and implementing it in the tessellator by transforming it to a Path at some intelligently selected resolution, and then tessellating that.

Would you like to work on that?

**Comment by xudesheng** [comment]
> 

Yes, I will be happy to do so. But I'm a newbie in Rust. I'm sure it will function as expected but it needs intensive review/refinement from the coding style perspective.

**Comment by lampsitter** [comment]
[`lyon_geom`](https://docs.rs/lyon_geom/latest/lyon_geom/) could be used, but it is most likely overkill for egui. Though it might be worth taking a look at how it does flattening.

**Comment by xudesheng** [comment]
> [`lyon_geom`](https://docs.rs/lyon_geom/latest/lyon_geom/) could be used, but it is most likely overkill for egui. Though it might be worth taking a look at how it does flattening.
Thank you, @lampsitter !
The implementation in lyon_geom is great. It not only implemented the almost latest algorithm (from a paper published in 2020) but also built some magic numbers which made the computing faster! I can't build a better one. So, in the end, I copied the major algorithm from it.

@emilk I just submitted https://github.com/emilk/egui/pull/1155 . Kindly please review it. I also build a demo app as part of the egui_demo_app. The current demo only supports the `Cubic` and `Quadratic` bezier curves. 
I need your help for 3 questions:

1.  I modified the `TessellationOptions` and give a default value 0.1 to `bezier_flattern_tolerence`. I'm not sure what's the best way to use it or where you can use it. 
2. I'm not sure what's the best way to handle the PaintStates::add for `Cubic Shape` and `Quadratic Shape`.
3. Since both `Cubic` and `Quadratic` curves will be flattened anyway into `Ploygon`, is it better to cache it as part of both Shape structures during construction?

**Comment by emilk** [comment]
Thanks @xudesheng - I did a first pass on the PR, and answered questions 1 and 2 there.

As for question 3: If I understand you correctly, you are asking if it is better to flatten the splines into a path (`Vec<Pos2>`) right away, or wait until the `Tessellator`. Here the PR does the right thing: it postpones the flattening until we know we need to paint the shapes (i.e. until after culling). This is also better for [`eterm`](https://github.com/emilk/eterm), which sends shapes over TCP, so they need to be as small as possible.

egui optimizes for changing things (i.e. bezier splines that change each frame). If there is a lot of static curves and performance is suffering, then a user can manually flatten them into a `PathShape`. Perhaps the bezier shapes could even have a helper-function for doing so (`pub fn to_path(&self, tolerance: f32) -> PathShape`).

**Comment by xudesheng** [comment]
> Thanks @xudesheng - I did a first pass on the PR, and answered questions 1 and 2 there.
> 
> As for question 3: If I understand you correctly, you are asking if it is better to flatten the splines into a path (`Vec<Pos2>`) right away, or wait until the `Tessellator`. Here the PR does the right thing: it postpones the flattening until we know we need to paint the shapes (i.e. until after culling). This is also better for [`eterm`](https://github.com/emilk/eterm), which sends shapes over TCP, so they need to be as small as possible.
> 
> egui optimizes for changing things (i.e. bezier splines that change each frame). If there is a lot of static curves and performance is suffering, then a user can manually flatten them into a `PathShape`. Perhaps the bezier shapes could even have a helper-function for doing so (`pub fn to_path(&self, tolerance: f32) -> PathShape`).

1. Thank you, yes, the 3rd question has been cleared.
2. The helper function was there in my original code. I will add it back.
3. I will resolve all the questions you mentioned this week sometime.

**Comment by emilk** [comment]
Thanks! 👍

**Comment by xudesheng** [comment]
![image](https://user-images.githubusercontent.com/8742037/151306054-9a501724-56b9-423d-9cfd-81e5ac06d2f2.png)
It seems like this is a special case to handle when closed=true and fill != Color32::TRANSPARENT
Probably it's faster to handle it after flattening. Let me try.

**Comment by xudesheng** [comment]
![image](https://user-images.githubusercontent.com/8742037/151489678-0ebc87c2-c15a-4ec2-b378-a355d29a249e.png)
@emilk  I have two commits and fixed all the issues you mentioned. Kindly please review it.
