### ISSUE TITLE
Shift + scroll does not pan plot horizontally

### ISSUE THREAD

**Issue by jbuckmccready** [emilk/egui#1135]
**Describe the bug**
Shift + scroll wheel does not pan plot horizontally (as described by the plot demo instructions).
![image](https://user-images.githubusercontent.com/7730301/149987291-4dbaf988-404c-48a7-a086-51b5f1c75368.png)

I tested it does not work on Windows 10 (or Firefox on the hosted web demo here: https://emilk.github.io/egui/index.html).

I dug around in the plot code but could not find where the scroll wheel is handled for panning - I only found the other handling for zooming, dragging, etc.

**Comment by emilk** [comment]
On my mac, shift-scrolling will make the OS report horizontal scroll events, both in the browser and on native. For some reason I thought this was standard across operating systems.

Maybe we should add explicit code for this then in egui-winit and egui-web.
