### ISSUE TITLE
Bug: Window grows in size when clicking on menu bar.

### ISSUE THREAD

**Issue by ckaran** [emilk/egui#114]
I'm testing egui by cloning [`egui_template`](https://github.com/emilk/egui_template/), and simply running `cargo run --release`.  The window pops up, and everything within the window works as expected.  However, when I try to drag the window around by the menu bar, the window grows downwards until I let go of the menu bar.  I made a [video](https://github.com/ckaran/egui_test/blob/6d1d2986f4a2540c80e6593b713aab3ada1f90f5/bug_reports/Growing_Window_bug.mp4) of what I'm seeing, but the drag & drop feature of GitHub isn't working correctly for me for some reason, so you'll need to download the file and watch it.  I don't know if this is a bug in the template, or a bug in egui itself.

## Meta 

```bash
lsb_release -a:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

uname -a:
Linux Hammer 5.4.0-62-generic #70~18.04.1-Ubuntu SMP Tue Jan 12 17:18:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

rustc -vV:
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.49.0

cargo -vV:
cargo 1.49.0 (d00d64df9 2020-12-05)
release: 1.49.0
commit-hash: d00d64df9f803bf5bba8714ca498d8f9159d07f6
commit-date: 2020-12-05

rustc +beta -vV:
rustc 1.50.0-beta.6 (ea20aa255 2021-01-14)
binary: rustc
commit-hash: ea20aa255b54708fb6a86f3146244eb20d079513
commit-date: 2021-01-14
host: x86_64-unknown-linux-gnu
release: 1.50.0-beta.6

cargo +beta -vV:
cargo 1.50.0-beta (1a8df6a51 2021-01-12)
release: 1.50.0
commit-hash: 1a8df6a5196e4cad9a3956867e7e928f2bfaaba4
commit-date: 2021-01-12

rustc +nightly -vV:
rustc 1.51.0-nightly (e38fb306b 2021-01-14)
binary: rustc
commit-hash: e38fb306b7f5e65cca34df2dab1f0db15e1defb4
commit-date: 2021-01-14
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0

cargo +nightly -vV:
cargo 1.51.0-nightly (329895f5b 2021-01-06)
release: 1.51.0
commit-hash: 329895f5b52a358e5d9ecb26215708b5cb31d906
commit-date: 2021-01-06
```

**Comment by emilk** [comment]
Interesting!

Does it work if you remove the call to `frame.set_window_size(ctx.used_size())` at the end of `egui_template/src/app.rs` ?

(it's been causing other problems too, so I think I'll remove that call in the next version of `egui_template` anyway).

**Comment by ckaran** [comment]
Yup, that worked!  Thank you for solving this so quickly!

I forgot to add one other thing to the original bug report, just in case you're having trouble replicating the bug; I have a multi-monitor setup, and each monitor is a different size and none of them are properly aligned with one another (e.g, the edges of the frames don't line up horizontally or vertically).  The main monitor is not the laptop screen, but the monitor in the middle.  I'm not sure if the weird configuration is causing headaches, but its the only thing I could think of that might be different from what others do.
