### ISSUE TITLE
Allow users to set their own handlers for hyperlinks

### ISSUE THREAD

**Issue by yusdacra** [emilk/egui#1152]
**Is your feature request related to a problem? Please describe.**
I want to be able to handle link opening myself, such that I can use different code for different protocols, and other stuff like being able to open the link in a seperate tab on web, rather than the current tab.

**Describe the solution you'd like**
This could easily be implemented via just passing a closure to the hyperlink widget.

**Describe alternatives you've considered**
None?

**Additional context**
Nothing.

**Comment by emilk** [comment]
I think this could be implemented in another way:

If we add a new widget `LinkButton` that just takes a label (no URL) and does nothing on click, then you could do it yourself:

``` rust
if ui.add(LinKButton::new("Documentation")).clicked() {
    …
}
```

It would look the same as `HyperLink` but have no click response, no url, and now hover text. `Hyperlink` could use `LinkButton` internally.

**Comment by yusdacra** [comment]
> I think this could be implemented in another way:
> 
> If we add a new widget `LinkButton` that just takes a label (no URL) and does nothing on click, then you could do it yourself:
> 
> ```rust
> if ui.add(LinKButton::new("Documentation")).clicked() {
>     …
> }
> ```
> 
> It would look the same as `HyperLink` but have no click response, no url, and now hover text. `Hyperlink` could use `LinkButton` internally.

Yeah that would work better, more composition :sweat_smile:
