### ISSUE TITLE
egui_glium flashes white and zooms out on Windows 10

### ISSUE THREAD

**Issue by junknet** [emilk/egui#117]
And when the software starts up, it flashes, then goes white, then zooms out.

**Comment by emilk** [comment]
Which software are you referring to? Are you talking about `egui_demo_app`? If so, web or native? On which platform?

**Comment by junknet** [comment]
> h
egui_demo_app，win10 native.

I really like this project！

**Comment by emilk** [comment]
That sounds like a windows-specific glium and/or winit problem. Do you get the same problems with the examples at https://github.com/glium/glium ?

**Comment by junknet** [comment]
> 
> 
> That sounds like a windows-specific glium and/or winit problem. Do you get the same problems with the examples at https://github.com/glium/glium ?



> 
> 
> That sounds like a windows-specific glium and/or winit problem. Do you get the same problems with the examples at https://github.com/glium/glium ?

I tested every example of glium.The same problem occurred! 
But other GUI frameworks don't have this problem,such as druid iced.

**Comment by emilk** [comment]
I'm gonna close this as it is a `glium` bug and I plan to move away from glium: https://github.com/emilk/egui/issues/93
