### ISSUE TITLE
Inconsistent resize behavior for plots

### ISSUE THREAD

**Issue by Bromeon** [emilk/egui#1174]
The resize behavior is different when a plot is "centered" (after double-click) vs. when the position is moved:

https://user-images.githubusercontent.com/708488/151665505-135fe3cb-aaa4-40cd-80f4-d4e112d7f22c.mp4

**To Reproduce**
1. Open plot demo example
2. Resize horizontally or vertically -- the zoom doesn't change
3. Move plot slightly with left click
4. Resize again horizontally or vertically -- when reducing size, plot shrinks

**Desktop**
 - OS: Windows 10
 - egui `master` version, commit 3333d63b913e4d09b5b291469dbeb3d6fd191bbf

**Comment by Saecki** [comment]
Also related to this. Changing the `data_aspect` when the `Plot` isn't centered will always zooms out.
The problem in both cases is that egui always tries to keep everything that was previously visble also visible after resizing/changing the aspect ratio, thus always expanding one axis.

I think it would be a better user experience to make sure that the same amount of data on one axis will be kept visible.
So when rapidly resizing like in the video, or trying to find the right `data_aspect` using a slider the plot wont zoom out further and further.

Either way I think it's more important that this is consistent across resize/aspect-ratio.
So when the behavior will be changed both should be changed.

The code regarding changing the aspect ratio is here
https://github.com/emilk/egui/blob/4db6984e7406540b6845bb82374dd041ffadfd28/egui/src/widgets/plot/transform.rs#L279-L285
Changing this would be trivial, and would simplify the code a bit by always expanding/shrinking one axis.

The code regarding resizing is a bit more complex:
https://github.com/emilk/egui/blob/4db6984e7406540b6845bb82374dd041ffadfd28/egui/src/widgets/plot/mod.rs#L308-L330
But about the same would apply here.

**Comment by s-nie** [comment]
Just stumbled upon this issue. I think https://github.com/emilk/egui/pull/1184 should fix it.

**Comment by Saecki** [comment]
Yes that is pretty much exactly what I had in mind, and more.
