### ISSUE TITLE
CanvasRenderingContext2D based renderer

### ISSUE THREAD

**Issue by t18b219k** [emilk/egui#1185]
**Is your feature request related to a problem? Please describe.**

I tested glow and webgl1 painter on Epiphany and Midori browsers . now they don't support both browsers.  WebkitGTK's webgl  implementation is bag of bugs.
Also may better support for non sRGB browsers .
**Describe the solution you'd like**

eliminate webgl related error from browsers.
**Describe alternatives you've considered**

Do not support WebkitGTK browsers
**Additional context**

I'm implementing mobile text edit and IME support for winit on web .
I'm using egui to demonstrate or debugging  with modified egui_winit_platform with addtional winit IME support.
I tested it on Chrome,Firefox,MS Edge browsers . but I tested on WebkitGTK browsers then i faced alot of errors.

**Comment by emilk** [comment]
The very first egui renderer was using `CanvasRenderingContext2D`! I think drawing most shapes should be pretty straight-forward, and perhaps text can be rendered from the texture atlas using https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

I’m curious what the performance will be though. I’m not very optimistic

**Comment by t18b219k** [comment]
I made this renderer called [egui_canvas](https://github.com/t18b219k/egui_canvas)
