### ISSUE TITLE
Unsound `Result::ok` method usage

### ISSUE THREAD

**Issue by ZetaNumbers** [emilk/egui#1201]
**Describe the bug**

Implementation of `epi::backend::RepaintSignal` for glow, gluim relies upon unsound use of a `Result::ok` method (to ignore the error i think).

**To Reproduce**

N/A

**Expected behavior**

To be determined below

**Additional context**

https://github.com/emilk/egui/blob/c3be5665740fb0100ee7d6d74282e933110a7141/egui_glium/src/epi_backend.rs#L11-L15
https://github.com/emilk/egui/blob/c3be5665740fb0100ee7d6d74282e933110a7141/egui_glow/src/epi_backend.rs#L8-L12

**Comment by ZetaNumbers** [comment]
To ignore errors people usually use:
`drop(result);` or `let _ = result;`

However, i think it would be better to propagate the error to the caller, which would decide to ignore the error or not.

**Comment by emilk** [comment]
The error can only occur if the backend has already shut down (there is no receiver), and in that case there is no longer need for any repaints.

**Comment by ZetaNumbers** [comment]
But `Result::ok` is not meant to ignore the error.

> The error can only occur if the backend has already shut down (there is no receiver), and in that case there is no longer need for any repaints.

What if we have a background thread, which owns this `RepaintSignal`? We should be able to know if runtime is finished.
