### ISSUE TITLE
`epaint::Mesh` inaccessible from `eframe`

### ISSUE THREAD

**Issue by goertzenator** [emilk/egui#1208]
I am working on my first egui app and I have been able to access everything until now by adding just `eframe` as a dependency in my `Cargo.toml`.  However I currently have no path to `epaint::Mesh`.

I see that `egui` re-exports a number of `epaint` items including the `Shape` enum...
https://github.com/emilk/egui/blob/master/egui/src/lib.rs#L386-L392
... shouldn't the constituents of `Shape` also be re-exported? (`CircleShape, PathShape, RectShape, TextShape, Mesh`)

**Comment by emilk** [comment]
easy: `eframe::epaint::Mesh`
