### ISSUE TITLE
Template does not specify rendering libraries required to run

### ISSUE THREAD

**Issue by SeanMcLoughlin** [emilk/egui#121]
I'm running Ubuntu 20.04. When trying to run the provided template, I keep running into this `ld` error:

```
error: linking with `cc` failed: exit code: 1
  |
  = note: <All the flags passed to ld were here but it's several hundred lines and not important>
  = note: /usr/bin/ld: cannot find -lxcb-render
          /usr/bin/ld: cannot find -lxcb-shape
          /usr/bin/ld: cannot find -lxcb-xfixes
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `egui_template`
```
After installing the following libraries like so:

```
sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
```

This issue went away. These libraries should be specified as required in the template so others don't run into this issue.

**Comment by emilk** [comment]
Thank you for this! I've added a note both in this repository and to https://github.com/emilk/egui_template

**Comment by JerryLiew** [comment]
> I'm running Ubuntu 20.04. When trying to run the provided template, I keep running into this `ld` error:
> 
> ```
> error: linking with `cc` failed: exit code: 1
>   |
>   = note: <All the flags passed to ld were here but it's several hundred lines and not important>
>   = note: /usr/bin/ld: cannot find -lxcb-render
>           /usr/bin/ld: cannot find -lxcb-shape
>           /usr/bin/ld: cannot find -lxcb-xfixes
>           collect2: error: ld returned 1 exit status
>           
> 
> error: aborting due to previous error
> 
> error: could not compile `egui_template`
> ```
> 
> After installing the following libraries like so:
> 
> ```
> sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
> ```
> 
> This issue went away. These libraries should be specified as required in the template so others don't run into this issue.

really appreciate.i have wasted so much time on this issue

**Comment by toger5** [comment]
On fedora i also needed to install `dnf install libxcb-devel` in addition to the listed packages.
