### ISSUE TITLE
TopBottomPanel and CentralPanel could not be sensed to dragging, clicking

### ISSUE THREAD

**Issue by feelingnothing** [emilk/egui#1213]
**Describe the bug**
TopBottomPanel and CentralPanel could not be sensed to dragging, clicking

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1

**Additional context**
![result](https://user-images.githubusercontent.com/47575622/152661575-39749691-e9fa-45c6-a921-e89b63733665.gif)

**Comment by emilk** [comment]
Did you read the docs for `clicked()`? https://docs.rs/egui/latest/egui/struct.Response.html#method.clicked

You need to use https://docs.rs/egui/latest/egui/struct.Response.html#method.interact
