### ISSUE TITLE
Autocomplete / suggestions popup for TextEdit

### ISSUE THREAD

**Issue by Weasy666** [emilk/egui#122]
Hello! Is it possible to something like this
![grafik](https://user-images.githubusercontent.com/11967542/104949247-f12f4f80-59be-11eb-8d0e-2b08f2c1bd07.png)
with `TextEdit`?

I would like to show some matching suggestions when a user enters text into the `TextEdit`.

**Comment by emilk** [comment]
There is nothing like this for `TextEdit` in particular, but I've added a helper function for you: `egui::popup::popup_below_widget`. Good luck!

**Comment by Weasy666** [comment]
Oh! That is really nice of you. Thank you very much!

**Comment by crumblingstatue** [comment]
I think it would be worth revisiting this. The current support for autocompletion is very crude.
For example, you can't override the behavior of TextEdit to ignore up/down key when the user is navigating your list.
You also can't set the cursor position after the autocomplete succeeds.
This basically means there is no way to make a good working autocompletable text buffer with TextEdit to my knowledge.

**Comment by gabrieldechichi** [comment]
Seconding @crumblingstatue  comments, I'm trying to implement a game console lib, and feeling blocked by not being able to set the cursor position.
