### ISSUE TITLE
Custom formatters for Slider/DragValue etc

### ISSUE THREAD

**Issue by AlexApps99** [emilk/egui#1221]
**Is your feature request related to a problem? Please describe.**

I'm making a debugger GUI for a project I'm working on, and I'd like to select an address from a `DragValue`.
However, it's conventional to notate addresses in zero-padded hexadecimal, rather than decimal.

**Describe the solution you'd like**
There should be some way to specify custom formatting on a number. Ideally this should be flexible so users can do whatever they want, like using Chinese numerals, base 12, or whatever.
This could be implemented with a function that takes a closure to format it, or it could be done by having a custom implementation of `Display` on `Numeric`.

**Describe alternatives you've considered**

We could also just have a flag for hexadecimal/pad length etc but that's probably not worth the complexity

**Additional context**

**Comment by emilk** [comment]
I think adding a custom formatting closure makes sense (similar to recent PR:s on `Plot`: https://github.com/emilk/egui/pull/1130 and https://github.com/emilk/egui/pull/934)
