### ISSUE TITLE
Scrollable Window Contents Overflow.

### ISSUE THREAD

**Issue by robertsonb** [emilk/egui#123]
Hello.

I was hacking around and put a bunch of widgets in a `container::Window`, mostly in vertical arrangement. 

The content is overflowing the Window, where the Window frame itself is correct, but some of the context is still visible (separators, images). Other content, like text is clipped properly.

I checked the EGUI demo and the Window's and scrollable content was clipped well enough, so this could very well be pilot error on my part but I'm not 100% sure.

![window_scroll](https://user-images.githubusercontent.com/3724436/104965490-d522b280-59ac-11eb-9a08-f5e19c4e792b.png)

**Comment by emilk** [comment]
What integration are you using? It seems likely that the bug is there, as this works in the egui online demo, as you mentioned.

**Comment by robertsonb** [comment]
I'm using the WGPU integration (egui @ v0.8.0, wgpu @ v0.6.0).

**Comment by robertsonb** [comment]
Found issue in backend as suspected (scissor rect not quite right).

Closing.
