### ISSUE TITLE
Is there a plan to support webp?

### ISSUE THREAD

**Issue by songlinshu** [emilk/egui#1231]
hi,Is there a plan to support webp? It is recommended to integrate webp. See https://github.com/jaredforth/webp

**Comment by emilk** [comment]
Parsing image files is outside the scope of `egui` - the idea is that you can load your favorite image format with your favorite crate, and then show it in egui using `Context::load_texture`. Like this: https://github.com/emilk/egui/blob/master/eframe/examples/image.rs

So in that regard, `egui` already supports `webp`.

Perhaps there is a room for a helper crate (`egui_extras`) for helpers around image loading and the like, but I haven't made that decision yet (nor it is clear if it should be in this repo)

**Comment by songlinshu** [comment]
Thank you !

**Comment by songlinshu** [comment]
As egui is powerful and used by more and more people, it is suggested that there should be egui_ Extras, I hope you make up your mind! thank you!
