### ISSUE TITLE
Can't switch to another app (@demo app)

### ISSUE THREAD

**Issue by yumesmile** [emilk/egui#1232]
**Describe the bug**

When I access the demo app from [this link](https://www.egui.rs/#demo) (with anchor)
I can't switch to another app for example ("Demos" -> "EasyMark editor").

But I can switch to another app,  when I access the demo app from [this link](https://www.egui.rs/) (no anchor)

**To Reproduce**
1. [problem link](https://www.egui.rs/#demo)
2. try to switch to another app.

[no problem link](https://www.egui.rs/)

**Expected behavior**

to switch to another app

**Screenshots**

-

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge (chrome base)
 - Version 98.0.1108.43 (Official build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: HUAWEI EML-L29
 - OS: Android 10
 - Browser Chrome
 - Version 98.0.4758.87

**Additional context**

-

**Comment by emilk** [comment]
This has been fixed in `master`. I will update the web demo on the next release.
