### ISSUE TITLE
Tooltips flicker when they can't fit on the screen

### ISSUE THREAD

**Issue by juancampa** [emilk/egui#1239]
**Describe the bug**

Tooltips flicker when they can't fit on the screen

**To Reproduce**
1. Resize screen to make it small-ish
2. Hover on a tooltip that's large enough to not fit vertically
3. observe the flickering

**Expected behavior**
The tooltip should not flicker

**Screenshots**

https://user-images.githubusercontent.com/1410520/153644827-71046616-ff87-4724-96fa-f104e9de4d72.mp4

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**

**Comment by juancampa** [comment]
I investigated this a little bit, the label stops being hovered every other frame because the tooltip prevents it from staying hovered. A possible solution would be to make tooltips "transparent" to hovering. But that wouldn't work for other `Area`-based things, like menus.

Perhaps a better solution is to just let it overflow the screen when it can't fully fit

**Comment by emilk** [comment]
This regressed, but was fixed again:
* https://github.com/emilk/egui/issues/4616
* https://github.com/emilk/egui/pull/4623
