### ISSUE TITLE
Additional painter functions

### ISSUE THREAD

**Issue by avmartugin** [emilk/egui#124]
Hello! I need some functions for my app:
1. Image as background for painter.
2. Zoom in/out for painter (without increase painter size, painter show some zoomed rect).
3. Move up/down/right/left for painter zoomed rect.

Can I do it now or its impossible?

**Comment by emilk** [comment]
1: You can just add an image that covers the background (see https://github.com/emilk/egui/blob/master/egui/src/widgets/image.rs#L67:L69)

2 & 3: There is no transform (zoom/pan/rotate/...) in the painter, so you'd have to do that yourself before adding your `Shape`s to the painter.
