### ISSUE TITLE
egui::frame:panel is private

### ISSUE THREAD

**Issue by PauloMelo** [emilk/egui#125]
Hello emilk,

I'm new to this product and I like it. I do not know if this is a decision or if my approach is wrong, but why is the egui::frame::panel private? I get associated function `panel` is private when I try to use it.

I would like to create a "container" that has the same content let's say a label, a text_edit_singleline and a possible error message. Several of these containers would be used. Am I doing it right trying to use the egui::frame::panel or should I use another approach?

**Comment by emilk** [comment]
`egui::Frame` is exactly the right choice, but `panel` here refers to `egui::SidePanel` etc. But I added a `Frame::group` for you:

``` rust
egui::Frame::group(ui.style()).show(ui, |ui| {
    ui.label("…");
    ui.text_edit_singleline(…)
});
```

This will put a nice frame around those widgets.

**Comment by PauloMelo** [comment]
Thank you very much Emil.

Best Regards,
Paulo Melo

On 20 Jan 2021, at 22:27, Emil Ernerfeldt <notifications@github.com> wrote:

﻿
egui::Frame is exactly the right choice, but panel here refers to egui::SidePanel etc. But I added a Frame::group for you:

egui::Frame::group(ui.style()).show(ui, |ui| {
    ui.label("…");
    ui.text_edit_singleline(…)
});
This will put a nice frame around those widgets.
