### ISSUE TITLE
Copied text is lost after window application quits

### ISSUE THREAD

**Issue by 55nknown** [emilk/egui#1253]
**Describe the bug**
I created an application that copies text to the clipboard. After closing the window, the content of the clipboard (so the previously copied text) is lost.

**To Reproduce**
1.
```rs
ui.output().copied_text = "something";
```
2.
```rs
frame.quit();
```

**Expected behavior**
The clipboard should retain it's content after the window is closed and the application is terminated.

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by Mingun** [comment]
This is the Linux behavior -- unlike Windows, clipboard content is owned by the application and lost when application is closed.

**Comment by 55nknown** [comment]
That's weird, I never knew about it. Thank you for the clarification!
