### ISSUE TITLE
Pango font rendering

### ISSUE THREAD

**Issue by mahkoh** [emilk/egui#1259]
**Is your feature request related to a problem? Please describe.**

I'm working on a GUI application and I would like to respect the users font configuration. That includes fontconfig settings, e.g. default fonts, font fallback, hinting, etc. and freetype rendering settings.

**Describe the solution you'd like**

I would like egui to optionally use pango (or if this is too high level fontconfig, freetype, and harfbuzz) for text rendering.

**Describe alternatives you've considered**

None that I could come up with.

**Comment by coderedart** [comment]
related links to previous discussion of font rendering libs.
https://github.com/emilk/egui/issues/1016
https://github.com/emilk/egui/issues/56

**Comment by emilk** [comment]
We've decided to switch to Cosmic Text:
* https://github.com/emilk/egui/issues/3378
