### ISSUE TITLE
Lottie files widget

### ISSUE THREAD

**Issue by optimisme** [emilk/egui#1264]
**Is your feature request related to a problem? Please describe.**
Yes, there is no easy (and standard) way to include animations into egui applications (also for game development)

**Describe the solution you'd like**
Add a module to load and display "Lottie" files
https://lottiefiles.com/what-is-lottie
https://github.com/LottieFiles/awesome-lottie
https://codingwithmitch.com/blog/understanding-the-internals-of-lottie-rendering-the-animation-file/

**Describe alternatives you've considered**
No, any alternative won't be the industry' standard way of doing it

**Additional context**
There is a lottie player for every 'major' multiplatform development tool (web, ios, android, flutter, xamarin, ...), and the libraries are available in different languages except rust (saddly)

I don't have enough Rust knowledge to do it by myself, this is the 'simplest' implementation I have found, and it is MIT licensed:
https://github.com/Samsung/rlottie

**Comment by emilk** [comment]
This is outside the scope of egui. If someone writes a library to load lottie files in rust, then it should be possible to paint those files with `epaint`.
