### ISSUE TITLE
Demo app on web won't switch to other tests on Mac OS X

### ISSUE THREAD

**Issue by basusamit** [emilk/egui#1265]
**Describe the bug**

On both Chrome 98.0 and Safari 15.3, the current egui demo at egui.rs behaves oddly.  You cannot reliably switch the top "tab" between different options.  For example, if it is on `Fractal Clock`, then you cannot switch it to `Demos`.  The screen simply flashes the `Demos` window and then returns to `Fractal Clock`.  

**To Reproduce**
1. Go to `egui.rs` on a Mac (I do not see the same problem on my Linux WS)
2. Click on `Fractal Clock`
3. Click on `Demos`
4. At least on my machine, it does not switch to `Demos`.

**Expected behavior**
Should be able to switch it.  Prior versions certainly worked.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser Chrome 98 and Safari 15.3
 - Version 11.6.2

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

Here, I am trying to switch to the `Fractal Clock` when the `Color Test` is selected.
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/47843102/154773872-0b1b0a4b-8b73-4fb7-8179-e09f35b7539d.png">

**Comment by basusamit** [comment]
Some additional testing resulted in the following observations:

- The same problem occurs on iOS
- It appears related to the URL.  If you navigate to `egui.rs`, things work as expected.  However, if you navigate to `egui.rs/#demo`, things break.  Note that in the screen cap below, the URL points at `egui.rs/#clock`, but the screen is displaying the color test.


<img width="769" alt="image" src="https://user-images.githubusercontent.com/47843102/154774651-17d45a3b-92bb-47d2-ad72-6ed6004f8ca3.png">

**Comment by t18b219k** [comment]
same Issue #1139 and fixed in #1140.

**Comment by t18b219k** [comment]
wasm in egui.rs is not updated after fix.
when egui 0.17.0 released this issue will be fixed in egui.rs .
