### ISSUE TITLE
egui.rs seems down

### ISSUE THREAD

**Issue by samoylovfp** [emilk/egui#1280]
https://downforeveryoneorjustme.com/egui.rs

![image](https://user-images.githubusercontent.com/17025459/154906210-3b08ee00-bac2-43d2-bc0c-3d9d078fd142.png)

**Comment by emilk** [comment]
Working on it!

**Comment by emilk** [comment]
It should be fixed within a few hours.

**Comment by Friz64** [comment]
It's back for me.

**Comment by emilk** [comment]
It is indeed!
