### ISSUE TITLE
Awkward API for TexturesDelta in integrations

### ISSUE THREAD

**Issue by derivator** [emilk/egui#1281]
The API for integrations around `TexturesDelta` introduced in #1110 seems a bit awkward to me:  
`egui_winit::State::handle_output` [takes ownership of `egui::Output` and returns `egui::TexturesDelta`](https://github.com/emilk/egui/blob/713917e4819d9c26068aec286ee675f7e3bff907/egui-winit/src/lib.rs#L517), suggesting that egui_winit is somehow involved or needed to get the `TexturesDelta`, when that's not actually the case.  
Perhaps `TexturesDelta` could be moved out of `Output` and into a new struct containing exactly everything needed to render the gui (i.e. the `Vec<ClippedShape>` that egui returns at the moment).  
As an alternative, egui_winit could just not take ownership of `Output` and return nothing.

**Comment by derivator** [comment]
`BackendOutput` sounds ambiguous to me. Isn't rendering also part of the backend? It could also be misunderstood to be output *from* the backend. I can't really think of a better name right now though, but here's some words that might do the trick in the right combination: OS, platform, integration, window manager.  

Maybe something like this?:

```rust
pub struct Output {
    pub for_platform: PlatformOutput, // current `Output`
    pub for_rendering: RenderingOutput, // shapes, texture delta
    pub needs_repaint: bool, // ambiguous items that could go into either category go in top level struct
}
```

**Comment by emilk** [comment]
Take a look: https://github.com/emilk/egui/pull/1292
