### ISSUE TITLE
Font Book demo displays wrong glyph for some characters

### ISSUE THREAD

**Issue by derivator** [emilk/egui#1284]
**Describe the bug**
The "Font Book" demo on [egui.rs](https://www.egui.rs/) displays the wrong glyph for some characters. Clicking them copies the correct character (matching the hover text) to the clipboard.

**To Reproduce**
1. Go to egui.rs
2. Click on Font Book
3. Type "fullwidth latin capital" into the filter box
4. The letter "Ｓ" shows an incorrect glyph
5. All following letters except Z are shifted back by one space in the alphabet, e.g. T shows S instead

**Screenshots**
![Screenshot from 2022-02-21 21-26-20](https://user-images.githubusercontent.com/2171264/155022286-1e084893-148f-470f-84eb-e9afc8501e6b.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox, Chromium, standalone application
 - Version: latest

**Comment by emilk** [comment]
I can confirm this still happens on latest `master`. This is very strange!

**Comment by emilk** [comment]
![Screen Shot 2022-02-21 at 22 16 04](https://user-images.githubusercontent.com/1148717/155027189-5b9787dd-fca1-4d71-9850-fb90d7ab40c3.png)

It gets weirder. Hovering the large `Ｓ` here shows the text for [Fullwidth Latin Capital Letter T](https://unicode-table.com/en/FF34/). Clicking it and pasting here, we get: `Ｔ`. Pasting that `Ｔ` into egui will make it sometimes show up as `Ｓ`, and sometimes as `ｔ` (lowercase!) depending on where in `egui` you paste it into.

**Comment by derivator** [comment]
>Hovering the large `Ｓ` here shows the text for [Fullwidth Latin Capital Letter T](https://unicode-table.com/en/FF34/). Clicking it and pasting here, we get: `Ｔ`. 

Yes, that's what I meant by point 5. It seems like the appearance of that one wrong glyph for the S has been wedged in there, shifting the ones after it back. Y is shown as X, the Y glyph is nowhere to be seen, only Z is correct again. 

The lowercase "t" was also a genuine WTF for me, but it's easily explained: the filter box (intentionally?) does not display capital letters at all, so pasting the uppercase Ｔ (that incorrectly shows as Ｓ) there *correctly* displays the corresponding lowercase ｔ.

**Comment by emilk** [comment]
>  but it's easily explained: the filter box (intentionally?) does not display capital letters at all

Oh yeah, of course 🤦  - one less mystery to solve at least!

**Comment by emilk** [comment]
I found the problem - it is in `emoji-icon-font.ttf`:
* https://github.com/jslegers/emoji-icon-font/issues/18

**Comment by Jhynjhiruu** [comment]
Despite being marked as closed, this error is back - it appears that the commit intending to properly fix the issue by updating the font file and removing the hack actually broke it. The updated font file is at [epaint_default_fonts/emoji-icon-font.ttf](https://github.com/emilk/egui/blob/main/crates/epaint_default_fonts/emoji-icon-font.ttf), but [the code](https://github.com/emilk/egui/blob/main/crates/epaint_default_fonts/src/lib.rs#L47) refers to [epaint_default_fonts/**fonts**/emoji-icon-font.ttf](https://github.com/emilk/egui/blob/main/crates/epaint_default_fonts/fonts/emoji-icon-font.ttf), which is still the old version.
