### ISSUE TITLE
Window continuously expands with scrollarea and autoshrink false

### ISSUE THREAD

**Issue by tqwewe** [emilk/egui#1297]
https://user-images.githubusercontent.com/16362377/155397800-197e65c8-0148-4808-afa1-de4061358c23.mov

Given the following code, the window continously expands every update.

```rust
Window::new("Console")
    .default_pos([LEFT_POS, TOP_POS])
    .default_size([WIDTH, HEIGHT])
    .show(ctx, |ui| {
        // Scroll area
        ScrollArea::vertical()
            .auto_shrink([false, false])
            .stick_to_bottom()
            .show(ui, |ui| {});

        // Input
        ui.add(
            TextEdit::singleline(&mut String::new())
                .desired_width(f32::INFINITY)
                .font(egui::TextStyle::Monospace),
        );
    });
```

My goal is to make the window resizable, and the scrollarea to expand to fill the remaining size. The problem is that the scrollarea continously grows infinitely.

Is there a way I can keep the window resizable while having the scroll area expand to fill the available space (without the issue of it growing forever)?

**Comment by mccolljr** [comment]
For of how you might accomplish what you want: You can use [Ui::available_size](https://docs.rs/egui/latest/egui/struct.Ui.html#method.available_size) to query the space left in the parent area, and could use that to explicitly size the scroll area. If you want additional content below the scroll area, You could try [Ui::vertical](https://docs.rs/egui/latest/egui/struct.Ui.html#method.vertical) or [Ui::with_layout](https://docs.rs/egui/latest/egui/struct.Ui.html#method.with_layout) to lay out the content with the scroll area in the top portion and the additional content below.

**Comment by tqwewe** [comment]
@mccolljr Thanks for the tips

I tried available_size outsize the scroll area (as shown below), and `ui.set_height(ui.available_height() - 30.0)`, but the window still grows:
```rust
// Window::new()...
    .show(ctx, |ui| {
      let scroll_height = ui.available_height() - 30.0;
      
      // Scroll area
      ScrollArea::vertical()
        .auto_shrink([false, false])
        .stick_to_bottom()
        .show(ui, |ui| ui.set_height(scroll_height));
    });
```

Also trying the following didn't work:
```rust
window.show(ctx, |ui| {
    ui.vertical(|ui| {
        // Scroll area
        ScrollArea::vertical()
            .auto_shrink([false, false])
            .stick_to_bottom()
            .show(ui, |ui| {});

        // Input
        ui.add(
            TextEdit::singleline(&mut String::new())
                .desired_width(f32::INFINITY)
                .font(egui::TextStyle::Monospace),
        );
    });
    // let scroll_height = ui.available_height() - 30.0;
});
```

Both code snippets result in the window still growing every update.

**Comment by tqwewe** [comment]
Here's a repo showing the issue if you'd like to take a look.
https://github.com/tqwewe/egui-expanding-window-issue

Just `git clone git@github.com:tqwewe/egui-expanding-window-issue.git && cd egui-expanding-window-issue && cargo run`

**Comment by mccolljr** [comment]
Try changing your `update` function to the following:
```rust
fn update(&mut self, ctx: &egui::Context, _frame: &epi::Frame) {
        Window::new("Console")
            .default_pos([LEFT_POS, TOP_POS])
            .default_size([WIDTH, HEIGHT])
            .show(ctx, |ui| {
                ui.vertical(|ui| {
                    // Scroll area
                    let scroll_height = ui.available_height() - 30.0;
                    ScrollArea::vertical()
                        .auto_shrink([false, false])
                        .max_height(scroll_height)
                        .stick_to_bottom()
                        .show(ui, |ui| {
                            for linenum in 0..100 {
                                ui.label(format!("Blah blah I am line number {}", linenum));
                            }
                        });

                    // Input
                    ui.add(
                        TextEdit::singleline(&mut String::new())
                            .desired_width(f32::INFINITY)
                            .font(egui::TextStyle::Monospace),
                    );
                });
            });
    }
```

I have not investigated what is causing the infinite growth, but specifying `max_height` for the scroll area will prevent it from growing infinitely. The above code seems to be behaving how you want

**Comment by tqwewe** [comment]
That worked perfectly, thank you so much for taking the time to help me (:

**Comment by blueforesticarus** [comment]
I get an infinitely growing panel even if I don't put anything in the ui.

```
ui.with_layout(egui::Layout::bottom_up(egui::Align::Min), |ui| {}
```
