### ISSUE TITLE
Programmatically place TextEdit cursor to end of text

### ISSUE THREAD

**Issue by tqwewe** [emilk/egui#1302]
Is it possible to place the text cursor in a TextEdit to the end after it's already created?

In my case I am updating the value of the text field, and want to move the curor to the end of the text upon update.

**Comment by emilk** [comment]
It can be done, using `TextEdit::load_state` + `TextEditState::set_ccursor_range` + `TextEditState::store`. Check out `egui_demo_lib/src/easy_mark/easy_mark_editor.rs`. Something like this:

``` rust
let text_edit_id = response.id;
if let Some(mut state) = egui::TextEdit::load_state(ui.ctx(), text_edit_id) {
    let ccursor = egui::text::CCursor::new(text.chars().count());
    state.set_ccursor_range(Some(egui::text::CCursorRange::one(ccursor)));
    state.store(ui.ctx(), text_edit_id);
    ui.ctx().memory().request_focus(text_edit_id); // give focus back to the `TextEdit`.
}
```

PS: Issues are NOT for asking questions. Use https://github.com/emilk/egui/discussions for that.
