### ISSUE TITLE
Using eframe >= 1.17.0 in a workspace requires cargo resolver v2

### ISSUE THREAD

**Issue by DusterTheFirst** [emilk/egui#1307]
When using eframe (especially compiling for `wasm32-unknown-unknown`) version 1.17, the code will fail to compile when using cargo resolver v1. For most recent crates (edition 2021) this should not be a problem, but when using multiple edition 2021 crates in a workspace with a virtual manifest, the resolver v1 will be used. This is marked as working as intended [see here](https://github.com/rust-lang/cargo/issues/9996#issuecomment-949193342), but can be confusing when expecting to be using the resolver v2 in your workspace.

It would be useful to inform consumers of eframe (especially wasm32) that resolver v2 is required.

Resolver v1 failing is caused by these dependencies on eframe:

https://github.com/emilk/egui/blob/master/eframe/Cargo.toml#L55-L63

Intuitively this looks correct, and with resolver v2 is is correct. But in resolver v1, the features for `target.'cfg(not(target_arch = "wasm32"))'.dependencies` and `target.'cfg(target_arch = "wasm32")'.dependencies` are merged, meaning that the `egui_glow/winit` feature is enabled on wasm32, but the egui-winit dependency is not specified. This leads to a weird error in eframe of the external crate egui-winit not being found when compiling to wasm32.

**Comment by DusterTheFirst** [comment]
This may be the same issue as is being fixed in #1303

**Comment by emilk** [comment]
Closed by https://github.com/emilk/egui/pull/1303 (if not, please tell me and I'll reopen this)
