### ISSUE TITLE
Support other user texture types besides SrgbTexture2d in egui_glium

### ISSUE THREAD

**Issue by HactarCE** [emilk/egui#1314]
**Is your feature request related to a problem? Please describe.**
I'm currently doing some custom rendering to a texture using glium and then displaying that texture using egui. I'd like to enable MSAA for that texture, but I can't because `<egui_glium::Painter as NativeTexture>::Texture` is only `Rc<SrgbTexture2d>`; to render with MSAA, I'd have to pass an `SrgbTexture2dMultisample`.

**Describe the solution you'd like**
I'm not sure of a good way to do this. Ideally, all `T where Sampler<T>: AsUniformValue` would be valid textures. The only (somewhat cumbersome) option I can think of is to make `Painter::Texture` an enum of the various 2D texture types that could reasonably be supported:
- `Rc<Texture2d>`
- `Rc<SrgbTexture2d>`
- `Rc<CompressedTexture2d>`
- `Rc<CompressedSrgbTexture2d>`
- `Rc<Texture2dMultisample>`
- `Rc<SrgbTexture2dMultisample>`

This would be a breaking change.

**Comment by emilk** [comment]
`egui_glium` will no longer be an backend to `eframe` (it has been replaced by `egui_glow`), which means two things:

A) I won't be as active in maintaining it
B) it can evolve more freely

Perhaps we could/should move it to a separate repository and share maintainship of it?

**Comment by HactarCE** [comment]
I'm switching my projects to use `egui_wgpu` and/or `eframe`, so I have no interest in helping to maintain `egui_glium`. I appreciate the offer though!

Should this issue be closed as "won't fix"?

**Comment by emilk** [comment]
Yup :)
