### ISSUE TITLE
There is a bug when running under win8.1

### ISSUE THREAD

**Issue by noxue** [emilk/egui#1315]
eframe verson 0.15.0

Repositorie  https://github.com/noxue/ticom

https://user-images.githubusercontent.com/8570817/156185129-5510fd12-4d1c-44f2-8dde-d7fd9766db08.mp4

**Comment by hamamo** [comment]
This has apparently been fixed in 0.17.0 - can you try switching to that version? It may require some adaption, as the code isn't fully stable yet.

**Comment by emilk** [comment]
Duplicate of https://github.com/emilk/egui/issues/838
