### ISSUE TITLE
Can't make a line segment one pixel in width

### ISSUE THREAD

**Issue by ascclemens** [emilk/egui#1322]
**Describe the bug**
Trying to paint a line segment with a width of `1.0` (on a system where one point is one pixel) results in a line segment two pixels wide. Using a stroke of `0.5` just makes the line slightly transparent, not thinner, as well.

Hopefully I'm just missing something obvious!

**To Reproduce**
```rs
let painter = ui.painter();
let ppp = ui.ctx().pixels_per_point();
let unit = 1.0 / ppp;
println!("unit: {}, ppp: {}", unit, ppp);
// ...
let rounded = painter.round_to_pixel(pos.x);
painter.line_segment(
    dbg!([egui::Pos2::new(rounded, 0.0), egui::Pos2::new(rounded, avail.y)]),
    dbg!((unit, egui::Color32::RED)),
);
```

```
unit: 1, ppp: 1
[src\app.rs:67] [egui::Pos2::new(rounded, 0.0), egui::Pos2::new(rounded, avail.y)] = [
    [434.0 0.0],
    [434.0 100.0],
]
[src\app.rs:68] (unit, egui::Color32::RED) = (
    1.0,
    Color32(
        [
            255,
            0,
            0,
            255,
        ],
    ),
)
```

**Expected behavior**
The line segment is one pixel in width.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by emilk** [comment]
You probably need to offset it by half a pixel (`Pos2::new(rounded + 0.5 * unit, …`)

**Comment by ascclemens** [comment]
That does work, but it's very unintuitive. I would expect that drawing a line on a pixel would draw a one-pixel line, not a two-pixel line. Very strange to have to draw a line on a half-pixel! Either way, it does work, so thank you for the help!

**Comment by emilk** [comment]
It's because of feathering - i.e. how epaint does anti-aliasing. If you turn off the anti-aliasing in the `TessellationOptions` you should get a one pixel wide line always, but all lines will look jagged.

**Comment by rmccrystal** [comment]
> It's because of feathering - i.e. how epaint does anti-aliasing. If you turn off the anti-aliasing in the `TessellationOptions` you should get a one pixel wide line always, but all lines will look jagged.

Is it possible to do this automatically? It's possible to make most lines one pixel wide by setting the expansion to 0.5 but there is no option for this for windows and sometimes the UI gets misaligned by a fraction of a pixel causing two pixel wide lines where there should be only one pixel wide lines

**Comment by TheZoq2** [comment]
I'd also like to see this. Borders in my application which are set to width 1 are rendered as 2 pixels with dimmed colors which doesn't seem ideal
