### ISSUE TITLE
Add support for function keys

### ISSUE THREAD

**Issue by ambihelical** [emilk/egui#1336]
**Is your feature request related to a problem? Please describe.**

It would be very useful if egui had support for function keys F1, F2, etc as they are great to bind for special purposes. 

**Describe the solution you'd like**

Support for Fn keys in Key enum and handling on at least desktop platforms.  Compile time feature if necessary. 

**Describe alternatives you've considered**

I don't know of any alternative solutions other than choosing other key bindings.  However a user may expect F1 to bring up help, and might appreciate function keys for other application functions. 

**Additional context**

**Comment by emilk** [comment]
Just go ahead and add them if you want them! Just make sure to test them on web too!

**Comment by ambihelical** [comment]
Looks like this was implemented in PR #1665, so closing.
