### ISSUE TITLE
Bg_fill does not render correctly on WASM

### ISSUE THREAD

**Issue by soundprojects** [emilk/egui#1347]
### Discussed in https://github.com/emilk/egui/discussions/1333

<div type='discussions-op-text'>

<sup>Originally posted by **soundprojects** March  5, 2022</sup>
I have an Eframe template project where I want to change the background of a TextEdit

I use the following code using a utility method for converting the hex string to the proper RGB values:

```
        //Change button colors and text colors in fg_stroke
        style.visuals.widgets.inactive.bg_fill = Color32::from_hex("#4e505c").unwrap();
```

This makes the TextEdit render properly on desktop but sometimes on WASM, the background is still white

Is this a bug or am I missing something specific for WASM?

Thanks</div>

**Comment by emilk** [comment]
This sounds very strange - native and web should work the same here.

> but sometimes on WASM, the background is still white

What do you mean by "sometimes" here?

**Comment by soundprojects** [comment]
Sometimes as in, when I recompile it will be correct on MacOS but always wrong on windows browsers (chrome and edge)

I tried a portable version of Opera at work and then the TextEdit shows the proper dark background color.

You can see the project live at 

https://soundprojects.github.io/treinlengtes/

https://github.com/soundprojects/treinlengtes

Currently it is also white when viewing on IOS.
There seems to be a similar issue when using the RetainedImage in a horizontal way

https://github.com/emilk/egui/discussions/1331

This is also ‘sometimes’. Please let me know if I can change anything to make the issue more specific :-)

**Comment by emilk** [comment]
Well, `extreme_bg_color` is the background color of `TextEdit`, so that is not very surprising.

**Comment by soundprojects** [comment]
Thanks, it took some searching but it makes total sense now

**Comment by soundprojects** [comment]
Sometimes as in, when I recompile it will be correct on MacOS but always wrong on windows browsers (chrome and edge)

I tried a portable version of Opera at work and then the TextEdit shows the proper dark background color.

You can see the project live at 

https://soundprojects.github.io/treinlengtes/

https://github.com/soundprojects/treinlengtes

Currently it is also white when viewing on IOS.
There seems to be a similar issue when using the RetainedImage in a horizontal way

https://github.com/emilk/egui/discussions/1331

This is also ‘sometimes’
