### ISSUE TITLE
code write

### ISSUE THREAD

**Issue by exten** [emilk/egui#1350]
```rust
impl Default for BackendPanel {
    fn default() -> Self {
        Self {
            open: false,
            run_mode: Default::default(),
            pixels_per_point: Default::default(),
            max_size_points_ui: egui::Vec2::new(1024.0, 2048.0),
            max_size_points_active: egui::Vec2::new(1024.0, 2048.0),
            frame_history: Default::default(),
            egui_windows: Default::default(),
        }
    }
}
```

why the code `egui_windows: Default::default()` can't write `egui_windows: EguiWindows::default()`,The meaning is more straightforward and there is no need to look up through the IDE。Thank you

**Comment by emilk** [comment]
Opinions differ, but I prefer `Default::default()` because it leads to less code changes when e.g. renaming a type.
