### ISSUE TITLE
There is no POST for http_fetch

### ISSUE THREAD

**Issue by PauloMelo** [emilk/egui#137]
Hi emilk,

There is no POST method implemented. Only the GET. I have created a simple one on my machine, would you like me to create a pull request with it? 

as a nutshell I've just extended the Request with a body, and extended a post like the get function and intercepted the fetch request adding the body if it was a POST instead of a GET.

**Comment by emilk** [comment]
Yes, a PR would be much appreciated!

Have you come up with a good design for posting both binary and text data? And for passing on a `Content-Type`?

**Comment by PauloMelo** [comment]
Not yet, I've started with the simplest solution. 
I will PR it and if you like it I can try to design more solutions.
