### ISSUE TITLE
[egui_glow] Reject images that are too big

### ISSUE THREAD

**Issue by DusterTheFirst** [emilk/egui#1370]
**Is your feature request related to a problem? Please describe.**

Attempting to load a &mdash; admittedly absurdly &mdash; large image into `egui_glow` with `ctx.load_texture` this, unhelpful message is printed out by tracing:
```
ERROR egui_glow::misc_util: GL error, at: 'tex_image_2d', code: 1281 (0x501)
```

**Describe the solution you'd like**

Tracking down the GL error code and the rust code that produced this message I found it to be coming from here:

https://github.com/emilk/egui/blob/c8f6cae3624e2c1303f7d7ca0158ae3b07b8ac15/egui_glow/src/painter.rs#L542-L553

I am unfamiliar with any OpenGL so I wouldn't know specifically how this would be implemented. It would be useful to check the size of the provided texture and ensure it is within the limits that OpenGL/glow/whatever has on the size of a texture before attempting to send it to the GPU? (I think that's what is happening at least). It would make sense to just make this a panic so that the public facing API of `Context::load_texture` does not change. But if the API could change, `load_texture` could return a `Result` with a `TextureTooLarge` error or something or even just an `Option` so that applications could somehow recover from it.

It may also be advantageous to expose the maximum texture size to the application code so it could seperate textures if they would be too large.

**Comment by coderedart** [comment]
we can just get GL_MAX_TEXTURE_SIZE at startup and everytime a texture is created, we check that the dimensions are within that limit, and if not we can do a `panic!  in egui_glow. better our own friendly panic than an external gl error which is confusing for users.

we can also put the following lines in documentation of textures to point them to safer limits.
for mobiles, usually, its 8k, but some older mobiles are still on 4k https://opengles.gpuinfo.org/displaycapability.php?name=GL_MAX_TEXTURE_SIZE&esversion=2 

for webgl, https://webgl2fundamentals.org/webgl/lessons/webgl-cross-platform-issues.html
4k covers most devices.
