### ISSUE TITLE
Use full browser width by default

### ISSUE THREAD

**Issue by rukai** [emilk/egui#1377]
At first I assumed that egui was limited to a hardcoded width in browsers (why else wouldnt it use all the available space?)
After noticing the max width slider in the demo I followed the code to find where this was set: https://github.com/emilk/egui/blob/c69f39e8697c56d50b1f53199abea9122573353b/epi/src/lib.rs#L184
There I found that the reason for setting the max width is to work around this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1010527#c0 
The bug was closed 5 months ago so does that mean egui should be changed to use the full browser width by default?

Edit: this should probably be a feature request...

**Comment by emilk** [comment]
Oh wow, you are right - it has been fixed! The perf in firefox is now great on my Mac 😃 

I'll change this ASAP!
