### ISSUE TITLE
Feature request: Window pivots

### ISSUE THREAD

**Issue by mystal** [emilk/egui#138]
Dear Imgui allows a windows position to be relative to a `position_pivot`. For example, using `imgui-rs`:
```rust
Window::new(im_str!("Debug Stats"))
    .position([0.0, screen_height], Condition::Always)
    .position_pivot([0.0, 1.0])
```

Which positions the bottom left corner of the `imgui-rs` window on the bottom left corner of my game's screen. It looks like this in-game:
![image](https://user-images.githubusercontent.com/74258/105643914-962aac00-5e47-11eb-8cc8-2b854302baad.png)

It would be great to have this in `egui`!

**Comment by emilk** [comment]
The most important use case for this will be, I assume to position the window at the four corners of the screen, as well maybe the center. So call it the cartesian product of `left center right` x `top x bottom`, i.e. what is expressed by [`Align2`](https://docs.rs/emath/0.8.0/emath/align/struct.Align2.html).

So I think a good API for this would be to *either* specify a position for a window in points, or to express it with an `Align2`. So for instance:

`Window::new(…).anchor(Align2::LEFT_BOTTOM)` for the use case in the image.

It should also be noted that there will be a frame-delay for the position, as egui needs to know the size before knowing where to position it.

**Comment by emilk** [comment]
This is now implemented in https://github.com/emilk/egui/pull/310 - please test if you have the time!

**Comment by mystal** [comment]
Just wanted to report back that this feature works perfectly for my needs! Thanks so much :)
