### ISSUE TITLE
Firefox panic with parking_lot (Parking not supported on this platform)

### ISSUE THREAD

**Issue by Titaniumtown** [emilk/egui#1401]
**Describe the bug**
With the latest egui commit, egui randomly fails with the error "Parking not supported on this platform" in relation to `parking_lot`.

**To Reproduce**
1. Browse to egui site using latest commit of egui with Firefox browser
2. Interact with site for a bit
3. Observe panic in browser console

**Expected behavior**
The site should run fine on Firefox

**Screenshots**
![image](https://user-images.githubusercontent.com/11786225/159482979-0b7c315a-c243-4869-bf71-f8f379b9ce91.png)

**Desktop (please complete the following information):**
 - OS: `Arch Linux`
 - Browser: Firefox
 - Version: 100 (nightly)

**Comment by Titaniumtown** [comment]
This is on firefox though.

**Comment by emilk** [comment]
It's a bit dissapointing (and surprising) that you don't get a proper Rust callstack in the console - or did you accidentally crop that from the image?

**Comment by emilk** [comment]
Please try out https://github.com/emilk/egui/pull/1404 @Titaniumtown

**Comment by imxood** [comment]
Using latest code, and this is Ok,
OS: Deepin Linux
Browser: Firefox
![image](https://user-images.githubusercontent.com/14890680/159506190-10f7c142-af06-4b7a-a5d2-a0a753b6a123.png)
