### ISSUE TITLE
Wasm text handling panic

### ISSUE THREAD

**Issue by Titaniumtown** [emilk/egui#1402]
**Describe the bug**
This bug is VERY random, but still occurs. Egui in the browser can randomly panic in relation to `passStringToWasm0` or `passStringFromWasm0` and failing to decode/encode text, and freeze the entire application, requiring a refresh of the page to work again.

**To Reproduce**
1. Sit on a page for an extended period of time
2. Randomly a panic in relation to `passStringToWasm0` or `passStringFromWasm0` will occur and application will freeze

**Screenshots**
Firefox:
![image](https://user-images.githubusercontent.com/11786225/159488521-fdd27b5a-5275-48e7-8f64-c6f054c9d830.png)
Firefox:
![image](https://user-images.githubusercontent.com/11786225/159489115-f4a7556a-d3fb-4ea9-9247-33e189fd98b3.png)
Chromium:
![image](https://user-images.githubusercontent.com/11786225/159677425-1dd5c137-7118-4faf-9de7-1505b0b850ca.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox and Chromium
 - Version: 100 and 99

**Comment by emilk** [comment]
Is this on `egui.rs` (0.17) or latest `master`?

**Comment by Titaniumtown** [comment]
> Is this on `egui.rs` (0.17) or latest `master`?

Both

**Comment by Titaniumtown** [comment]
Discovered that this issue is not related to `text_edit_singleline` and can occur when simply having the page open for an extended period of time. I edited this issue to reflect that

**Comment by emilk** [comment]
So just visiting egui.rs and leaving it open for a few minutes(?) will get you a `passStringToWasm0/passStringFromWasm0` error?

**Comment by Titaniumtown** [comment]
It's EXTREMELY random. I cannot find a reliable way of reproducing it. Sometimes it happens within a minute or so of being on the page, sometimes it never occurs. I've been trying for ages to find a reliable way to reproduce it to see if I could fix it myself, but I couldn't, so I created this issue here.

**Comment by Titaniumtown** [comment]
I did some more digging. Seems it's actually a failure to parse an error in relation to the inability to borrow something mutably. I'm doing further digging.

**Comment by Titaniumtown** [comment]
Found the issue:
![image](https://user-images.githubusercontent.com/11786225/164270583-73f15766-0a5e-4c8c-bf7b-7d1f2e53437a.png)
![image](https://user-images.githubusercontent.com/11786225/164270720-1af1dbda-cdb7-4c23-95dc-86d36c4d2a9e.png)

**Comment by Titaniumtown** [comment]
@juancampa said this on the discord server:
> FWIW, I've seen panics like these because the `.js` file doesn't match the `.wasm`. When it happened (months ago) I discovered that the reason was the service worker that comes with `eframe_template` was caching one (or both?) files
I would disable that if you have it, just in case. Again, might be totally unrelated

That actually seems to be the issue, I implemented a system in which md5sums are appended to the end of file names, and it seems to work! This is my (probably poorly implemented) method of doing it here: https://github.com/Titaniumtown/YTBN-Graphing-Software/commit/aad08d06ab286c87d45827f790d0bb80ebf92630

I'll close this issue for now, if the issue persists I'll reopen it!

**Comment by emilk** [comment]
Oof 😞 

I wonder if we can do anything in the default setup to help prevent this. This is not a great developer experience, to say the least!

**Comment by juancampa** [comment]
Hashing like @Titaniumtown did is the way to go IMO

**Comment by emilk** [comment]
Changing the file name on each build sounds like a pretty robust way to always defeat the cache. Perhaps a bit hacky, but if it works it works.

Anyone feel like making a PR out of https://github.com/Titaniumtown/YTBN-Graphing-Software/commit/aad08d06ab286c87d45827f790d0bb80ebf92630 to `egui` and `eframe_template`?
