### ISSUE TITLE
Main window background

### ISSUE THREAD

**Issue by PauloMelo** [emilk/egui#141]
Hi Emilk is there a way to set the background color of the main window (the first one)?

Regards,
Paulo

**Comment by emilk** [comment]
You mean the glium window? Use https://docs.rs/epi/0.8.0/epi/trait.App.html#method.clear_color

**Comment by PauloMelo** [comment]
No I meant the egui_web. I have tried it, but it does no change it.

Regards,
Paulo

On 26 Jan 2021, at 17:58, Emil Ernerfeldt <notifications@github.com> wrote:

﻿
You mean the glium window? Use https://docs.rs/epi/0.8.0/epi/trait.App.html#method.clear_color

**Comment by emilk** [comment]
You mean the HTML background? https://github.com/emilk/egui/blob/master/docs/index.html#L17-L19

**Comment by PauloMelo** [comment]
No I mean the canvas. I’ve tried setting the background on the html css for the canvas, where the app runs. I could not set the style of the CtxRef before adding the Central Panel. 

In the central Panel I have several groups where I could change the background.

As I said before these are my first days with Rust, and I try to read the code before asking for some help.

Regards,
Paulo Melo

On 26 Jan 2021, at 20:08, Emil Ernerfeldt <notifications@github.com> wrote:

﻿
You mean the HTML background? https://github.com/emilk/egui/blob/master/docs/index.html#L17-L19

**Comment by emilk** [comment]
So is the question how to change the background of the `CentralPanel`? Then the answer is https://docs.rs/egui/0.8.0/egui/containers/struct.CentralPanel.html#method.frame

If that is now the question: please show a screenshot and show what you mean

**Comment by PauloMelo** [comment]
Hi Emil,

Yes I believe that it should be the frame I’d the CentralPanel. But that is a private field só I cannot change the fill color. And I do not have access to ui.style before adding the CentralPanel. 

Here is a sample screenshot:


The grey should be blue as set in the clear_color.

Regards,
Paulo

On 26 Jan 2021, at 20:55, Emil Ernerfeldt <notifications@github.com> wrote:

﻿
So is the question how to change the background of the CentralPanel? Then the answer is https://docs.rs/egui/0.8.0/egui/containers/struct.CentralPanel.html#method.frame

If that is now the question: please show a screenshot and show what you mean

**Comment by emilk** [comment]
I don't see your screenshot on https://github.com/emilk/egui/issues/141 - I think it's easier if you log in to GitHub than use email :)

Anyway, the linked docs is a functions, you do this:

``` rust
let my_frame = egui::Frame {
    fill: egui::Color32::LIGHT_BLUE,
    ..Default::default()
};
CentralPanel::default().frame(my_frame).show(…);
```
