### ISSUE TITLE
Safari renders RetainedImages the wrong way

### ISSUE THREAD

**Issue by soundprojects** [emilk/egui#1415]
### Discussed in https://github.com/emilk/egui/discussions/1331

<div type='discussions-op-text'>

<sup>Originally posted by **soundprojects** March  5, 2022</sup>
Hi

I have an Egui project (0.17.0) that compiles to both a desktop and a WASM app using the Eframe Template

I use` RetainedImage` from the egui_extras to show some images. I use the following code to place the images from a Vector next to each other in a horizontal UI:

```
        ui.horizontal(|ui| {
            for part in &train.parts {
                let image_ratio = part.image.size_vec2().y / 20.0;

                part.image.show_scaled(ui, 1.0 / image_ratio);
            }
        });
```

The desktop app places the images neatly next to each other like this:
<img width="746" alt="Schermafbeelding 2022-03-05 om 16 52 06" src="https://user-images.githubusercontent.com/10196339/156890646-39d52f03-fc58-4e44-8785-0d34b2ba9222.png">

But when I run my WASM build in Safari (same on IOS) specifically, it renders all the images on top of each other like this:

<img width="1138" alt="Schermafbeelding 2022-03-05 om 16 51 42" src="https://user-images.githubusercontent.com/10196339/156890672-b04003df-f3ce-43fb-b33d-839bbf216ea5.png">

Is this a bug or am I missing something?

Thanks
</div>

**Comment by emilk** [comment]
Is your web view wide enough? https://docs.rs/epi/latest/epi/trait.App.html#method.max_size_points

**Comment by soundprojects** [comment]
Yes I set the max size points to be the proper width. It is only in safari that these images are stacked like this

**Comment by emilk** [comment]
That's very weird O.o
