### ISSUE TITLE
Color picker closes immediately on click

### ISSUE THREAD

**Issue by EmbersArc** [emilk/egui#143]
**Describe the bug**
When picking a color, I'd expect to be able to click and drag within the color picker and select a color. It works that way in the online demo. In my native build however, the popup closes immediately when clicking anywhere in the color picker area.
This works fine in the web demo (online, I wasn't able to compile it myself). Dragging the rest of the popup works fine.

**To Reproduce**
1. Build the demo
2. Open any color picker
3. Click in the colored region but don't release the mouse
4. The popup closes

**Expected behavior**
 I'd expect to be able to click and drag within the color picker and select a color.

**Screenshots**
![test](https://user-images.githubusercontent.com/1352472/105896749-7f3ab400-6017-11eb-993a-0af67af58d6e.gif)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux KDE Plasma

**Comment by emilk** [comment]
This seems to have come with https://github.com/emilk/egui/pull/135 - thanks for the report!

**Comment by aakamenov** [comment]
Hello @emilk and EmbersArc ,

I've submitted a PR for this - #144

**Comment by emilk** [comment]
Fixed by https://github.com/emilk/egui/pull/144
