### ISSUE TITLE
Grid item uses wrong variable after add_visible

### ISSUE THREAD

**Issue by aalhitennf** [emilk/egui#1436]
**Describe the bug**
Grid item created with `ui.add_enabled`_ui after `ui.add_visible`, uses wrong variable somehow.

**To Reproduce**
Clone eframe_template and modify update fn to:

```
impl epi::App for TemplateApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut epi::Frame) {

        let column2_visible = false;
        let column3_enabled = true;

        egui::CentralPanel::default().show(ctx, |ui| {
            // For some reason, value from column2_visible is used in add_enabled_ui
            egui::Grid::new("grid").num_columns(3).show(ui, |ui| {
                ui.label("First column");
                ui.add_visible(column2_visible, egui::Label::new("Second column"));
                ui.add_enabled_ui(column3_enabled, |ui| ui.button("This should be enabled"));
                ui.end_row();
            });

            // But if we use add_visible_ui first, problem goes away
            egui::Grid::new("grid2").num_columns(3).show(ui, |ui| {
                ui.label("First column");
                ui.add_visible_ui(column2_visible, |ui| ui.label("Second column"));
                ui.add_enabled_ui(column3_enabled, |ui| ui.button("This is enabled"));
                ui.end_row();
            });
        });
    }
}
```

**Expected behavior**
There should be two buttons, both enabled.

**Screenshots**
https://i.imgur.com/myix3uu.png

**Desktop (please complete the following information):**
 - OS: Arch Linux, Windows 10
 - Browser: Not tested in browser

**Additional context**
This happens with both 0.17.0 and git master.

**Comment by emilk** [comment]
You need to use unique id:s for your `Grid`:s if they have the same parent. `Grid::new("grid1")` … `Grid::new("grid2")`

**Comment by aalhitennf** [comment]
Copy pasted and forgot to change the id, problem still exists even with unique id:s.

**Comment by emilk** [comment]
Thanks for the report!

**Comment by emilk** [comment]
I now added warnings about `Id` clashes for `Grid`:s https://github.com/emilk/egui/pull/1451 (even though this issue was not at all about that)
