### ISSUE TITLE
Font rendering with gray Rgba color is ugly

### ISSUE THREAD

**Issue by flosse** [emilk/egui#1455]
This is how it looks:

![Bildschirmfoto_2022-04-05_04-48-30](https://user-images.githubusercontent.com/276043/161669250-e7356c11-09eb-49f0-a2eb-edd86cf25086.png)

And this is how it is created:
```rust
let label_color = Rgba::from_gray(if path.is_some() { 1.0 } else { 0.5 });
ui.label("directory:");
ui.colored_label(label_color, path.unwrap_or(&"- none selected -".to_string()));
```
It is rendered on a Linux system and the master branch (10f30a0c5222726c3a31550773503ee063c65472).

**Comment by emilk** [comment]
Simpler reproduce:

``` rust
ui.colored_label(egui::Rgba::from_gray(1.0), "white");
ui.colored_label(egui::Rgba::from_gray(0.5), "gray");
```

Probably related to https://github.com/emilk/egui/pull/1412

**Comment by flosse** [comment]
To make it even simpler to reproduce, here is a repo:

https://github.com/flosse/egui-font-rendering-bug

**Comment by flosse** [comment]
> Probably related to #1412

yes it is!
You can reproduce this by using a commit before 8272b08 as shown in the [`before-8272b08`](https://github.com/flosse/egui-font-rendering-bug/tree/before-8272b08) branch.

**Comment by emilk** [comment]
I added a test suite to the color test panel: https://github.com/emilk/egui/commit/68d5806b41725fb8f8a5e62d7acd94b5ac9140f0

White-on-white also looks bad:

![Screen Shot 2022-04-05 at 14 39 00](https://user-images.githubusercontent.com/1148717/161755361-fbd879bb-dbe0-40fc-84ee-5f59fab501e9.png)
