### ISSUE TITLE
`Grid` gives different column widths in release  and debug builds

### ISSUE THREAD

**Issue by kud1ing** [emilk/egui#1462]
The code is just 
```
Grid::new("some_unique_id")
    .striped(true)
    .show(ui, |ui| {

[...]

}
```

Release build gives a compact grid:

<img width="486" alt="Bildschirmfoto 2022-04-06 um 13 29 06" src="https://user-images.githubusercontent.com/391975/161965392-cb94f169-b94a-4842-a9d3-9b7489a58df2.png">

Debug build:

<img width="717" alt="Bildschirmfoto 2022-04-06 um 13 29 25" src="https://user-images.githubusercontent.com/391975/161965422-defe20b4-68ea-4dfe-a82f-663c15616a4a.png">

and without the debug output:

<img width="717" alt="Bildschirmfoto 2022-04-06 um 13 29 51" src="https://user-images.githubusercontent.com/391975/161965458-0ba6fc19-7024-4d4e-88f9-23065b701ab1.png">

**Comment by emilk** [comment]
Is the problem still there if you turn off persistence? Can you make a minimal reproduce?

**Comment by kud1ing** [comment]
Hm, strange. I've duplicated the source tree with the intent to reduce the test case. But the problem is gone in the duplicate. So maybe this is indeed related to persistence.
Where is the persistence data stored? Does it include more than the model data?

**Comment by emilk** [comment]
The paths are documented https://docs.rs/epi/latest/epi/trait.App.html#method.save
By default: both the App state, egui state and window state is persisted. In this case it is likely the egui state that remembers the grid widths that is creating spookyness. You can always reset the egui state with `*egui_ctx.memory() = Default::default();`

**Comment by kud1ing** [comment]
On macOS there is nothing from 2022 in `~/Library/Application Support`.
Also i wouldn't understand why the data would be different between release and debug mode.
Mysterious. Since i can't reproduce it anymore, i'll close the issue.

Thank you for your support.
