### ISSUE TITLE
Persistence of window position is not working correctly on Windows and Linux

### ISSUE THREAD

**Issue by sourcebox** [emilk/egui#1469]
While it works for me as expected on macOS, the native window is moving on the screen across subsequent application launches on Windows and Linux when using the persistence feature.

- On Windows, it moves in both X and Y direction. Sometimes by an offset, sometimes it jumps a longer distance. I can't figure out any any regularity here.
- On Linux, it always moves some pixels down between launches. The amount of pixels seem to be equivalent to the height of the title bar. I did some tests with `winit` directly by using `window.set_outer_position()` and reading back via `window,outer_position()` and the results were correct. It seems that `egui` uses inner position internally, maybe this is the cause of that behaviour.

**Comment by sourcebox** [comment]
After upgrading to 0.19, the issue is now fixed on Linux but Windows still restores the window at the wrong position when launching the app several times.

**Comment by Shel-M** [comment]
Ran into this problem as well, so I looked at making a pull request when I found that this is deliberately disabled in egui-winit::initialize_window with the following. 

`
        // If the app last ran on two monitors and only one is now connected, then
        // the given position is invalid.
        // If this happens on Mac, the window is clamped into valid area.
        // If this happens on Windows, the window is hidden and very difficult to find.
        // So we don't restore window positions on Windows.
        let try_restore_position = !cfg!(target_os = "windows");
        if try_restore_position {
            if let Some(pos) = self.position {
                window = window.with_position(winit::dpi::PhysicalPosition {
                    x: pos.x as f64,
                    y: pos.y as f64,
                });
            }
        }
`

If the try_restore_position is set to true, then it works fine up until reproducing the problem outlined in the comment.
