### ISSUE TITLE
firefox on android 9 startup almost impossible.

### ISSUE THREAD

**Issue by t18b219k** [emilk/egui#1470]
**Describe the bug**

failed to run egui.rs on firefox.

**To Reproduce**
1.  open https://egui.rs/ by firefox

**Expected behavior**

should reach demo.

**Screenshots**

![スクリーンショット 2022-04-09 214703](https://user-images.githubusercontent.com/48007646/162574734-9553524b-4d72-49ae-91f0-8d045b4d1d9a.png)

**Smartphone (please complete the following information):**
 - Device:  Xperia XZ1 compact
 - OS:  Android 9
 - Browser  Firefox
 - Version  99 and 101 Nightly

**Additional context**

sometimes we can reach demo but chrome works well.

**Comment by t18b219k** [comment]
there are some problem in gl.bind_frame_buffer()

![スクリーンショット 2022-04-10 121539](https://user-images.githubusercontent.com/48007646/162599838-1c831256-6bb7-449a-a32c-fc843594d155.png)

**Comment by emilk** [comment]
![Screen Shot 2022-04-10 at 08 53 46](https://user-images.githubusercontent.com/1148717/162606281-1a056b4b-c2f1-4996-b248-d21a8d4afa55.png)

I'm pretty sure this is the problem causing all the subsequent problems. Does other WebGL sites work well for you? e.g. https://webglsamples.org/aquarium/aquarium.html

**Comment by t18b219k** [comment]
works very well.

**Comment by t18b219k** [comment]
Now run very well it seems to be fixed.
