### ISSUE TITLE
using epaint::text::Fonts::layout_job + FontDefinitions::default() to generate Galley results in gibberish

### ISSUE THREAD

**Issue by waynr** [emilk/egui#1472]
**Describe the bug**

When I generate a `Galley` using a custom `LayoutJob` and `Fonts` built using `FontsDefinition::default()`, I get some kind of weird rendering of whatever text I put in the `LayoutJob` sections.

The reason I want to use a `Galley` instead of a `LayoutJob` is because the `Galley` comes with information about the height of the text after wrapping occurs for the sake of reporting those heights to [`TableRow::heterogeneous_rows`](https://github.com/emilk/egui/blob/c2ab0404b7d8e2266934385798b0447145d0357b/egui_extras/src/table.rs#L397)

**To Reproduce**

1. fetch my [`demonstrate-apparent-galley-bug` branch](https://github.com/waynr/egui/tree/demonstrate-apparent-galley-bug)
2. `cd egui_glow`
3. `cargo run --example pure_glow`

**Expected behavior**
A giant red MEOW appears in the left side bar.

You can see how it _should_ look if you change [this line](https://github.com/waynr/egui/commit/4847640da6a7ec8c17158744a29fc9bd6ad89aaf#diff-16d9c6294ea6844fce4192fbfa934ddf515ac0a8a7c9adfefbd4afead37e1e42R43) to something like `ui.layout(job)` instead of `ui.layout(galley)`.

**Screenshots**

* When using a `Galley`: ![When using a `Galley`](https://user-images.githubusercontent.com/1441126/162599921-45fd0892-5019-44a5-9818-e4c7eb94ec54.png)
* When using a `LayoutJob`: ![When using a `LayoutJob`](https://user-images.githubusercontent.com/1441126/162599923-5eb1345e-a979-4855-9eb0-e6c63e7d27fa.png)

**Desktop (please complete the following information):**
 - OS: `Linux thing3 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux`

**Additional context**

I suspect this has something to do with some kind of setup on the `Ui`'s `fonts` field that I didn't do when initializing my `Fonts`. I am reporting this as a bug because it seems like the intuitive way to use these types according to the docs (though maybe i missed something) is borked.

**Comment by emilk** [comment]
You should instead be using `egui::Context::set_fonts` and `egui::Context::fonts`.

Each `Fonts` comes with a font texture atlas, and the tessellator expects there to be only one font texture.
