### ISSUE TITLE
Unable to stretch lines on edges using SidePanel

### ISSUE THREAD

**Issue by imxood** [emilk/egui#1473]
using ``` ui.vertical_centered ``` in ``` SidePanel ```， it can stretch lines on edges using SidePanel, it is ok
hovever, use ``` ui.horizontal ``` in ``` SidePanel ```， it cann't stretch lines on edges using SidePanel, it isn't ok

it show:

https://user-images.githubusercontent.com/14890680/162611479-d98b1be3-c8ec-4add-a5ac-209b23d78d0e.mp4

the code is in https://github.com/imxood/egui-examples/blob/master/test-egui/examples/test_panel1.rs

```rust
#![feature(let_chains)]

use eframe::{egui, epaint::Color32, epi, Frame};

#[derive(Default)]
pub struct MyApp {}

impl MyApp {
    fn new(_cc: &eframe::CreationContext) -> Self {
        Self::default()
    }
}

impl epi::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, frame: &mut Frame) {
        egui::SidePanel::left("left-panel").show(ctx, |ui| {
            ui.painter()
                .rect_stroke(ui.available_rect_before_wrap(), 0.0, (1.0, Color32::RED));

            ui.horizontal(|ui| if ui.button("left side").clicked() {});
        });
        egui::SidePanel::right("right-panel").show(ctx, |ui| {
            ui.painter()
                .rect_stroke(ui.available_rect_before_wrap(), 0.0, (1.0, Color32::RED));

            ui.vertical_centered(|ui| if ui.button("right side").clicked() {});
        });
    }
}

fn main() {
    eframe::run_native(
        "hello",
        eframe::NativeOptions::default(),
        Box::new(|cc| Box::new(MyApp::new(cc))),
    );
}
```

**Comment by emilk** [comment]
I think https://docs.rs/egui/latest/egui/#auto-sizing-panels-and-windows should explain it. I'll see if I can make that documentation more visible as this is a common point of confusion

**Comment by imxood** [comment]
thanks~ it works well~
