### ISSUE TITLE
Clipboard dependency unmaintained

### ISSUE THREAD

**Issue by Shatur** [emilk/egui#1474]
This crate depends on https://github.com/alacritty/copypasta which depends on unmaintained https://github.com/quininer/x11-clipboard/issues/19. Which also depends on xkb which is [unsound and also unmaintained](https://github.com/RustSec/advisory-db/issues/653) :rofl:
I would suggest to switch to https://github.com/1Password/arboard

**Comment by emilk** [comment]
I didn't know about `arboard` - good find!
