### ISSUE TITLE
Plot `Line::fill` does not fill last segment correctly

### ISSUE THREAD

**Issue by Hunter522** [emilk/egui#1477]
**Describe the bug**

Using `Line::fill` seems to work except for the very last segment of the line. See below screeshot:

![image](https://user-images.githubusercontent.com/9222431/162776535-1bb5c498-f801-4967-8f45-d30017acf8b4.png)

**To Reproduce**
Code to reproduce the behavior:

```rust
    let mut plot = Plot::new("lines")
        .include_x(0.0)
        .include_y(0.0)
        .legend(Legend::default());
    plot.show(ui, |plot_ui| {
        let series = [
            Value::new(0.0, 1.0),
            Value::new(1.0, 2.0),
            Value::new(2.0, 5.0),
            Value::new(3.0, 4.0),
            Value::new(4.0, 1.0),
            Value::new(5.0, 1.0),
            // Value::new(5.0, 1.0), // duplicate last point as workaround
        ];
        let planned_line = Line::new(Values::from_values_iter(series.into_iter()))
            .fill(0.0);
        plot_ui.line(planned_line);
    });
```

**Expected behavior**

Polygon fill should look correct for last segment of line, like so:

![image](https://user-images.githubusercontent.com/9222431/162777307-cf736eac-87e1-4a59-8c8c-a02c538cb499.png)

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Version 0.17.0

**Workaround**

As seen in the code comment above, duplicating the last point will "fix" this. But may be confusing for users.

**Comment by emilk** [comment]
The code is here: https://github.com/emilk/egui/blob/master/egui/src/widgets/plot/items/mod.rs#L430-L451 if you want to take a stab at fixing it - it is probably not much work.

**Comment by WesleyCh3n** [comment]
I think it miss the second to last vertex to draw the triangle.
https://github.com/emilk/egui/blob/af63101fdcbbba6e5b6b763598ba17eb76cff712/crates/egui/src/widgets/plot/items/mod.rs#L450
I can make a pr to fix this!
