### ISSUE TITLE
Color32 from hex value

### ISSUE THREAD

**Issue by tami5** [emilk/egui#1492]
**Is your feature request related to a problem? Please describe.**

Most of the time when implementing a UI design, colors comes in hex values. Having to manually convert hex to RGBA is kind tedious and time consuming.

**Describe the solution you'd like**

new method in Color32

```rust
Color32::from_hex("#0d1117")
```

**Comment by emilk** [comment]
This would be nice - especially if it could be a `const fn` or macro, so any typos could be caught at compile time.

I think what we would want to support is only the `#rrggbb` and `#rrggbbaa` formats, not the other weird CSS formats
