### ISSUE TITLE
Japanese word wrapping is weird

### ISSUE THREAD

**Issue by bigfarts** [emilk/egui#1497]
**Describe the bug**
Japanese text wraps at weird points of sentences.

<img width="832" alt="image" src="https://user-images.githubusercontent.com/90592158/163508589-5b0afc76-95b3-476a-b86c-4a6d66dc8ffd.png">

**To Reproduce**
Display the following text in egui:

> ゲームを下記より選択してください。
>
> リストが空の場合は、「roms」ディレクトリにROMファイルを、「saves」ディレクトリにセーブファイルを配置してください。

**Expected behavior**
Wrapping that looks more like this:

> ゲームを下記より選択してください。
>
> リストが空の場合は、「roms」ディレクトリにROMファイル
> を、「saves」ディレクトリにセーブファイルを配置してくだ
> さい。

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser N/A
 - Version 0.17.0

**Comment by emilk** [comment]
If you want to make a PR to fix this, take a look at https://github.com/emilk/egui/blob/master/epaint/src/text/text_layout.rs#L710-L768

**Comment by bigfarts** [comment]
Thanks! Is there a way to do lookahead? There are some characters that are only allowed to have a line break after them depending on the subsequent character e.g. it's permissible to break between しろ but not between しゅ

**Comment by emilk** [comment]
Of course there is a way; it will just require more code :)
