### ISSUE TITLE
version on github is different from the version on crates.io

### ISSUE THREAD

**Issue by CharlieBarbe** [emilk/egui#1514]
on github

#[cfg(not(target_arch = "wasm32"))]
#[allow(clippy::needless_pass_by_value)]
pub fn run_native(app_name: &str, native_options: NativeOptions, app_creator: AppCreator) -> ! {
    egui_glow::run(app_name, &native_options, app_creator)
}

from crates.io via depenties in cargo.toml

#[cfg(not(target_arch = "wasm32"))]
#[cfg(not(feature = "egui_glium"))] // make sure we still compile with `--all-features`
#[cfg(feature = "egui_glow")]
pub fn run_native(app: Box<dyn epi::App>, native_options: epi::NativeOptions) -> ! {
    egui_glow::run(app, &native_options)
}

the first needs 3 parameters the seconde needs 2

**Comment by Titaniumtown** [comment]
This is due to refactoring that hasn't been pushed to an official release.
