### ISSUE TITLE
Example custom_window_frame close button doesn't work on gnome and when I click on X button it drags the window

### ISSUE THREAD

**Issue by NiiightmareXD** [emilk/egui#1518]
Video of the bug:

https://user-images.githubusercontent.com/90005793/164396930-0b76827e-5a88-4816-9f0e-d61b510759a9.mp4

**To Reproduce**
1. run cargo run -p custom_window_frame
2. click on X button (close button)

**Expected behavior**
Close the window

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Version 36

**Comment by Titaniumtown** [comment]
Could you maybe provide more info? There's a bug template 😕

**Comment by NiiightmareXD** [comment]
> Could you maybe provide more info? There's a bug template confused

Ok edited it, I Also added a vidoe.

**Comment by emilk** [comment]
Anyone feel like digging into this? Perhaps see if https://github.com/rust-windowing/winit/blob/master/examples/drag_window.rs works  for you

**Comment by PikminGuts92** [comment]
> Anyone feel like digging into this? Perhaps see if https://github.com/rust-windowing/winit/blob/master/examples/drag_window.rs works for you

Yes, that example does seem to work fine for me without any noticeable issues.

Additional info is I'm on a 4K display with 150% scaling but switching to 100% didn't change anything.

**Comment by NiiightmareXD** [comment]
> > Anyone feel like digging into this? Perhaps see if https://github.com/rust-windowing/winit/blob/master/examples/drag_window.rs works for you
> 
> Yes, that example does seem to work fine for me without any noticeable issues.
> 
> Additional info is I'm on a 4K display with 150% scaling but switching to 100% didn't change anything.

Are you using windows or linux? What distribution?

**Comment by PikminGuts92** [comment]
> Are you using windows or linux? What distribution?

Windows 10 21H2 19044.1645

It seems that the 'X' button click event is caught somehow and prevents me from using the dark/light theme toggle buttons anymore. Force restarting the application is the only way to restore interaction.

https://user-images.githubusercontent.com/15707039/166829967-49b2a347-7ea6-42b3-a125-655b48b0df0c.mp4

**Comment by NiiightmareXD** [comment]
> > Are you using windows or linux? What distribution?
> 
> Windows 10 21H2 19044.1645
> 
> It seems that the 'X' button click event is caught somehow and prevents me from using the dark/light theme toggle buttons anymore. Force restarting the application is the only way to restore interaction.
> 
>  Code_d4z00bR4B0.mp4

Buttons work for me but close button doesn't in both fedora and windows 11

**Comment by PikminGuts92** [comment]
To be clear, theme toggle buttons work until after I click the 'X' button. After which they behave as disabled.

**Comment by alexniver** [comment]
Same issue on me. 

I'm using Win10

after adding some debug code

```
            let title_bar_response =
                ui.interact(title_bar_rect, Id::new("title_bar"), Sense::drag());
            if title_bar_response.drag_started() {
                println!("drag started");
                frame.drag_window();
            }
            println!("draged : {}", title_bar_response.dragged());
            if title_bar_response.drag_released() {
                println!("drag release");
            }
```
I find that drag release event doesn't depend on mouse release, It depends on if the mouse leave the current panel. 

If the mouse stay in panel(full panel, not just title panel), it will keeping "draged"

when mouse go out panel, "draged" change to false.

and may be 

```
 frame.drag_window();
```
need an other function to release frame.drag? like:
```
 frame.drag_window_end();
```

**Comment by lorrenbiffin** [comment]
Hey all! I think this problem is actually pretty simple. See #1750 for a detailed description of the problem and a proposed solution. Cheers! <3
