### ISSUE TITLE
Lack of support for MenuButton with image.

### ISSUE THREAD

**Issue by t18b219k** [emilk/egui#1526]
**Is your feature request related to a problem? Please describe.**

I want to add a ImageButton with left click menu. by following code.
```rust 
  struct Tracker{
       image_button:Option<usize>,
  }
 {
   let image_button=ImageButton::new(texture_id,size);
   if ui.add(image_button).clicked(){
    *tracker.image_button=self.id;
   } 
  if  tracker.image_button = Some(self.id){
  // menu rendering codes.
  } 
}
```
 but this approach is not good by following reasons.
 * update tracker if other menu opend.
 * manually close menu if lost focus.
 * id managing.
**Describe the solution you'd like**

adding ImageButton functionality to MenuButton.

**Comment by Aworldc** [comment]
This would be good
