### ISSUE TITLE
Large corner radii cause tessellation error

### ISSUE THREAD

**Issue by aevyrie** [emilk/egui#1529]
**Describe the bug**
Setting the corner radii for a button very high will generate a bad mesh on the northeast corner
This was working in v16, and broke in v17.

**To Reproduce**
1. Set the rounding of widgets to a large number:
 ```rs
WidgetVisuals {
    rounding: Rounding::same(100.0),
    // ...
}
```

**Expected behavior**
The rendered element should have fully-round corners, meeting at a tangent on the shortest edge.

**Screenshots**
![image](https://user-images.githubusercontent.com/2632925/164782996-c4172e81-54f6-4004-b1ea-feb61b910c6e.png)

I was able to replicate this on the web demo by updating the style in the settings panel:
![image](https://user-images.githubusercontent.com/2632925/164783937-0c02cf48-8d43-43dc-818d-f992995d7acb.png)

In this case the way it breaks is a bit different, and seems to be related to the contained text.

It also manifests in the outline on hover, you can see the border is malformed as it reaches tangency:
![image](https://user-images.githubusercontent.com/2632925/164784103-7f4e827f-0e52-4b9e-9d1f-5236a4452695.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser N/A

**Additional context**
This is running in `bevy_egui`

**Comment by emilk** [comment]
I tried reproducing this in the demo app, and failed:

![Screen Shot 2022-04-26 at 05 06 06](https://user-images.githubusercontent.com/1148717/165211957-fa68545e-0df4-4189-b3ac-552bb8289d5e.png)

Please make a minimal reproduce

**Comment by aevyrie** [comment]
I am now unable to replicate on the most recent version
