### ISSUE TITLE
glClear not working in eframe web

### ISSUE THREAD

**Issue by emilk** [emilk/egui#1548]
For some reason the color buffer isn't cleared in eframe web. The easiest way to replicate is with and `App::update` that has no `CentralPanel` (so the egui doesn't fill the background) but has an `egui::Window`.

**Comment by arshiyasolei** [comment]
@emilk seems like the issue is from the post processing. I returned a temporary `(None, "")`  [here](https://github.com/emilk/egui/blob/3c685d7bf6a36bda9ffbee36ee822b4205b29b36/egui_glow/src/painter.rs#L111) and that solved the clearing issue, though it is a temporary solution.

**Comment by emilk** [comment]
Good catch @arshiyasolei - I made a PR with a fix
