### ISSUE TITLE
2D plotting functionality

### ISSUE THREAD

**Issue by EmbersArc** [emilk/egui#155]
Having a 2D plotting library inside egui would be highly beneficial. It already has most of the capabilities necessary for implementing one. Taking some inspiration from [implot](https://github.com/epezent/implot) for imgui, I put together a prototype of what this feature may look like.

Note that I only have a surface-level understanding of egui, so much of what I do here may not be "best practice" and there may be better ways to do things. I am willing to continue work on this, but would appreciate occasional reviews, advice or even collaboration from someone who is more proficient with the internal workings of egui. So let me know if you want to help.

https://github.com/EmbersArc/eplot
![simplescreenrecorder-2021-02-02_21 22 15](https://user-images.githubusercontent.com/1352472/106660902-de14a600-65a0-11eb-8c9b-347a05d497eb.gif)

**Comment by emilk** [comment]
Very cool and impressive!

I have a vague plan of adding an immediate mode plot library to egui. My initial inclination is to make something very simple: plotting colored lines without any mouse interaction except hover.

I think a more fully-featured plotting library like you are demoing would make sense as a separate crate (`eplot`).

Let me know how `eplot` progresses and how I can help! In particular if there are any features you miss in `egui`.

One thing I've been planning to add is a transform to `Painter` to make it easier to build things like this. The transform would be applied to each [`Shape`](https://docs.rs/epaint/0.8.0/epaint/enum.Shape.html) passed to the `Painter`. I think initially it would only support translation and non-uniform scaling (including mirroring).

**Comment by EmbersArc** [comment]
You're right that this should better be a separate crate since creating/maintaining it would be quite an endeavor. I don't yet know how far I'm going to take this but so far working with egui has been great.

As for missing features, the biggest ones are related to text rendering. I haven't been able to find a way to rotate text (note the missing y-axis label) and text positioning in the plot seems to be quite tricky as well but I probably didn't try hard enough there.

The transformation function you mention would indeed be helpful, especially with axis mirroring. I am currently doing this in my own function. But I'm afraid linear transformations won't be enough for things like plots with log-log scaling anyways, and there might not be a case to add those to egui itself.
I wouldn't recommend scaling whole shapes in this function, just coordinates. There are some cases where I want to transform the position of polygons, but not their individual vertices. But such a function might have other applications that I'm not thinking of right now.

**Comment by emilk** [comment]
There is no way to rotate text at the moment. I think adding `emath::Rot2` to `Shape::Text` should be pretty easy.

As for positioning text: use `Shape::text` which allows you to position text relative some anchor (e.g. `CENTER_BOTTOM`): https://docs.rs/epaint/0.8.0/epaint/enum.Shape.html#method.text

**Comment by mindv0rtex** [comment]
One missing feature that I came across in ImPlot, which targets Dear Imgui, is plotting dashed lines. Doing this by drawing a bunch of tiny line segments can become a performance issue. Dear Imgui itself does not provide a way to draw dashed line segments or polylines, so this could be something for you to consider.

**Comment by emilk** [comment]
I've pushed an immediate mode plotter to `master`, with basic support for grid lines and tick labels. There is some minor polishing left to do, but it will be included in egui 0.10.

![plot](https://user-images.githubusercontent.com/1148717/108323357-df5fe880-71c6-11eb-8010-9f1f64110108.gif)

**Comment by emilk** [comment]
Closed by a19140ec679b2de6d1cfc43604e868ec9847ba82

**Comment by JPGygax68** [comment]
I have implemented something that is somewhat tangential to plotting, a "Canvas" struct that supports rulers, panning and scaling. 
Because of panning and scaling, it is necessary to convert coordinates prior to issuing calls to the Painter, which is slightly annoying as it makes the user-facing interface more complex (conversions are made available via an extra struct called "Surface".

Hence the following question: would it be possible to add an optional  2D transformation matrix to the Painter struct? Combined with the already existing and excellent clipping support, this would make rendering in "content" spaces a breeze.
