### ISSUE TITLE
Consider making `epi` functionality implementation-agnostic

### ISSUE THREAD

**Issue by EmbersArc** [emilk/egui#1555]
**Is your feature request related to a problem? Please describe.**
So far I've been able to reuse most of `epi`'s functionality in my own WGPU integration, strongly reducing the need for code duplication as it also uses winit. However, with the 0.18 release, `epi` was moved into `eframe` and made dependent on a GL context.

**Describe the solution you'd like**
If possible, epi should be separate and implementation-agnostic. This could significantly reduce the need for code duplication and would make egui's behavior between integrations more consistent.

**Describe alternatives you've considered**
Copying the epi code, removing all GL-related fields and functionality and keeping it in sync with future changes to `eframe::epi`.

I see that this request is a bit inconvenient right now as this change has just been made and there might be good reasons for the tighter GL dependency. But I still wanted to bring it up for discussion as `epi` by itself has been very useful without being dependent on GL.

**Comment by emilk** [comment]
I had no idea anyone was using `epi` outside of `eframe`. This was indeed bad timing 😓
