### ISSUE TITLE
Rust Cargo failing to fetch version 1.18 from crates.io index

### ISSUE THREAD

**Issue by Magnetuz** [emilk/egui#1567]
### Description
The Rust Cargo is failing to fetch the version 1.18 from crates.io index. The following message is displayed:

> Updating crates.io index
error: failed to select a version for the requirement `egui = "^0.18"`
candidate versions found which didn't match: 0.17.0, 0.16.1, 0.16.0, ...
location searched: crates.io index

After removing the registry at `.cargo` folder, Cargo will fetch all project crates again but the error remains.

According to the crates.io, the version 1.18 is already available.

The same issue happens for eframe and egui_extras 1.18.

### To Reproduce
Steps to reproduce the behaviour:
1. Create a new cargo project (with --bin)
2. Add the egui = "0.18" dependency
3. Build the project

**Expected behaviour**
The project builds

### Desktop
 - OS: Ubuntu 
 - Cargo version: 1.59.0

**Comment by Mingun** [comment]
Probably you have unsupported rustc version. Version 0.18 required Rust >=1.60

**Comment by emilk** [comment]
Also, you write "1.18" many times, but the latest release is "0.18". I think you have some local issues, because this is working for me and everyone else.

**Comment by Magnetuz** [comment]
> Probably you have unsupported rustc version. Version 0.18 requires Rust >=1.60.
> 
> Yes, that is definitely this. Failed on Rust 1.59 and works fine on 1.60

That solved the issue. Thanks

**Comment by Magnetuz** [comment]
> Also, you write "1.18" many times, but the latest release is "0.18".

Sorry about that. It was a typo. 

Thank you
