### ISSUE TITLE
Add `primary_clicked` & `secondary_clicked` for `PointerState`.

### ISSUE THREAD

**Issue by aleokdev** [emilk/egui#1580]
**Is your feature request related to a problem? Please describe.**
I'd like to detect if the user clicked something with the primary button somewhere in order to cancel their selection.
While we have `.any_click()` and `.primary_down()`, we don't have `.primary_clicked()`!

**Describe the solution you'd like**
I'd like a way to know if one button was clicked on this frame.

**Describe alternatives you've considered**
Using `.any_click() && .primary_down()`, but this is faulty: The user could be holding down the primary button and then have clicked with another button.

**Comment by emilk** [comment]
Sounds good, please make a PR adding the missing methods!
