### ISSUE TITLE
eframe transparent window not fully transparent 

### ISSUE THREAD

**Issue by kurtn3x** [emilk/egui#1581]
_On Windows_
Creating a simple transparent Window with eframe only makes it semi transparent. 
Tried to look into it, the window looks exactly like this, already mentioned in winit : https://github.com/rust-windowing/winit/issues/1859. In winit its fixed though.

The Window: 
```
    let native_options = eframe::NativeOptions{
        decorated: false,
        transparent: true,
        ..eframe::NativeOptions::default()};

```

**Comment by emilk** [comment]
@kurtn3x did you set `App::clear_color` as mentioned in the docs https://docs.rs/eframe/latest/eframe/struct.NativeOptions.html#structfield.transparent ?

**Comment by kurtn3x** [comment]
Oh, yeah sorry i'm blind, that fixed it. Thank you.
