### ISSUE TITLE
Freeze when a tooltip be created but the mouse moved outside of windows

### ISSUE THREAD

**Issue by willser** [emilk/egui#1609]
Hello,there is a bug.I am not sure it there someone report.I tried search but got nothing,so I open a new issue.

**To Reproduce**
1. Add a `tooltip` in a frame
2. Hoverdthe frame so `tooltip` be created
3. Use `alt + tab` or drag mouse moved outside of windows(Make sure `tooltip` is alive before mouse move out )
4. Window be freeze and dead soon

**Expected behavior**

*Desktop*
 - OS: windows
 - Version 10
 
And I test this case in https://www.egui.rs/#demo.There is no such problem.

**Comment by emilk** [comment]
Are you saying the whole app freezes and dies if you alt-tab while a tooltip is showing? Can you create a very simple example app and perhaps a video of the reproduce?

**Comment by willser** [comment]
````rust
fn main() {
    let native_options = eframe::NativeOptions::default();
    eframe::run_native(
        "test",
        native_options,
        Box::new(|creation_context| Box::new(Test {})),
    );
}

struct Test {}

impl App for Test {
    fn update(&mut self, ctx: &Context, frame: &mut Frame) {
        CentralPanel::default().show(ctx, |ui| {
            let response = ui.label("test");

            if response.hovered() {
                egui::show_tooltip_text(ui.ctx(), Id::new("name_tip"), "test tooltip");
            }
            response
        });
    }
}
````

<details> <summary>screen record</summary>


https://user-images.githubusercontent.com/64425242/167865438-8b87be5a-57d4-4f01-b2d0-acffe1e62402.mp4


https://user-images.githubusercontent.com/64425242/167865968-12eec735-af28-4af1-9431-d61ac565839e.mp4


</details>

**Comment by coderedart** [comment]
can confirm. when hovering and alt-tabbing out of window, the `update` function is not called. checked by continuously printing `ctx.input().time`

**Comment by emilk** [comment]
I can confirm it happens on Mac too!
