### ISSUE TITLE
Clipboard support is broken on Wayland

### ISSUE THREAD

**Issue by Detegr** [emilk/egui#1612]
**Describe the bug**

The clipboard is not working on Wayland. `arboard` supports only Wayland terminal applications, not graphical applications.

**To Reproduce**
```
use eframe::egui;

fn main() {
    let options = eframe::NativeOptions::default();
    eframe::run_native(
        "My egui App",
        options,
        Box::new(|_cc| Box::new(MyApp::default())),
    );
}

struct MyApp {
    s: String,
}

impl Default for MyApp {
    fn default() -> Self {
        Self { s: String::new() }
    }
}

impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {
            if ui.button("copy test string to clipboard").clicked() {
                ctx.output().copied_text = "hello, world!".into();
            }
            ui.text_edit_multiline(&mut self.s);
        });
    }
}
```
1. Run the demo on Wayland.
2. Try clicking the button, or copying from the text box.
3. Nothing happens.

**Expected behavior**
Clipboard should work as expected.

**Desktop (please complete the following information):**
 - OS: Linux, Wayland

**Comment by quietvoid** [comment]
The current clipboard was super inconsistent or not working at all for me in Wayland, using `eframe`.
Fix in #1613 works consistently now.

Thanks!
