### ISSUE TITLE
Support chinese characters

### ISSUE THREAD

**Issue by qqke** [emilk/egui#162]
when I input "多少有" in text field,
it show 
![image](https://user-images.githubusercontent.com/23273672/107141815-9c07ad80-696e-11eb-8605-067105929a69.png)

**Comment by emilk** [comment]
The default font does not support Chinese characters scripts. You will need to set up your own font with Chinese character support.
Use [`Context::set_fonts`](https://docs.rs/egui/0.8.0/egui/struct.Context.html#method.set_fonts) to install your own font.

The reason the default font doesn't support all the characters is that it is bundled with `egui`, and I don't want `egui` to be unnecessary large. If you find a good font (with a liberal license) with Chinese character support I could add it as an opt-in behind a feature flag.

**Comment by qqke** [comment]
Thanks
