### ISSUE TITLE
Conflicts with web-sys when trying to use egui-wgpu with wgpu 0.12

### ISSUE THREAD

**Issue by Rob1B** [emilk/egui#1629]
Hi ! 
I'm trying to add egui to my renderer and I'm having a conflict of the version of web-sys. 

Apparently, wgpu 0.12 asks for ^0.3.53 while egui-wgpu asks 0.3.50 because of having wpu 0.9 dependency. I'm not sure but it looks like the crate of egui-wgpu has not been updated on crates.io ? 

**To Reproduce**
1. Create a crate
2. Specify : `egui-wgpu = "0.0.1-alpha.1` and `wgpu = "0.12.0"`
3. Try to compile

**Expected behavior**
Compilation should finished well

**Screenshots**
![image](https://user-images.githubusercontent.com/30219092/168473516-7931ba96-16bb-4cd1-bf56-9155ab12754b.png)

**Comment by emilk** [comment]
I just published `egui-wgpu` 0.18.0, so this should be fixed now!
