### ISSUE TITLE
Rotate and Flip PlotImage.

### ISSUE THREAD

**Issue by kkngsm** [emilk/egui#1646]
Hi, I would like the ability to rotate and flip `PlotImage`.

Usually using `Vec<_>.push()`, if I want to append to the image data, it will be  append to bottom.
However, in some cases (such as drawing a spectrogram) I may want to append to the left or right.
Therefore, we need the ability to rotate or flip the image to make it appear as if it is being added to the left or right.

The function is like `widget::Image`
```rust
PlotImage::new(/*inline*/)
    .rotate(angle, origin)
    .flip([true, false])
```

With the current functionality, the only way to do this is to `Vec<Vec<u8>>`, but this is inefficient.

**Comment by ThundR67** [comment]
How do i rotate plot images for the time being?
