### ISSUE TITLE
Let scrolling follow the text cursor in a multiline text edit widget

### ISSUE THREAD

**Issue by the-drunk-coder** [emilk/egui#165]
**Is your feature request related to a problem? Please describe.**
Problem: When editing longer text snippets in a multi-line text edit widget, the cursor just leaves the scroll area, and you have to follow it manually with the mouse.

**Describe the solution you'd like**
Have the scrolling follow the cursor automatically, without having to switch to the mouse.

I've made some experiments with the customized text edit widget I keep in a fork, but when trying to scroll to a certain position the results are somewhat unpredictable ...

**Comment by emilk** [comment]
This might be pretty easy to implement by following the bread-crumbs of the implementation of https://docs.rs/egui/0.9.0/egui/struct.Response.html#method.scroll_to_me and https://docs.rs/egui/0.9.0/egui/struct.Ui.html#method.scroll_to_cursor

**Comment by the-drunk-coder** [comment]
Hmm I tried several variants of that but the results were a little unpredictable ... like, scrolling to a certain y-position never really scrolled to where I needed it ...

But I guess I should give it another look ...

**Comment by UE2020** [comment]
Is there a solution for this yet?

**Comment by the-drunk-coder** [comment]
Haven't worked on this either for a while ...

One problem I've frequently run into is that it seems hard to apply the abovementioned `scroll_to_cursor` and `scroll_to_me` methods selectively when the cursor leaves the visible part of the text field.

I think one thing that would be helpful is to have some method to detect whether the cursor moved out of the visible part of the text field, and in which direction ...

**Comment by robo-corg** [comment]
Is there a way to use to use this with `ScrollArea::show_rows`? Trying to get this working with that but I am not certain what a rect for this would be if the location is not on screen.

Looking at things in the debugger and it seems the clip area never really changes and seems to be the screen coordinates of the `ScrollArea`.

**Comment by robo-corg** [comment]
Ahh I think I figured it out. You need to calculate the position relative to row_range passed in.
