### ISSUE TITLE
Feature Request: table columns added with variable widths, a one liner

### ISSUE THREAD

**Issue by ray-5050** [emilk/egui#1652]
I'm using a table with about 9 columns and each has its own relative width so that seems to leave out using the columns method.  Currently I do the following
.column(Size::relative(self.col_widths[0]))
.column(Size::relative(self.col_widths[1]))
....
.column(Size::relative(self.col_widths[8]))
As you can see, this is a bit tedious.

Proposal

I added a method in the TableBuilder of the following

/// Allocate space for several columns at once with varying sizes.
    pub fn columns_with_sizes(mut self, size: Vec<Size>, count: usize) -> Self {
        if size.len() != count {
            panic!("The size vec must equal the count")
        }
        for i in 0..count {
            self.sizing.add(size[i]);
        }
        self
    }

This seems to work well and fills my needs, I just pass a vec containing the sizes and the Size enum I want
i.e. 
col_widths = vec![Size::relative(0.05), Size::relative(0.2), Size::relative(0.2), .....]
then
.columns_with_sizes(self.col_widths.clone(), 9)

Thanks for your consideration.

**Comment by emilk** [comment]
I don't see the need for the `count: usize` parameter, but sure, add such a method if you like
