### ISSUE TITLE
Unable to get precise or correct coords for mouse position over Image

### ISSUE THREAD

**Issue by junglie85** [emilk/egui#1654]
**Describe the bug**

Unable to get correct world coordinates from mouse position of image produced from texture of prior render pass.

In the image below, assume my mouse cursor is on the bottom-left corner of the blue square. I'm expecting the world coords position to be (0, 0), not (2.78, -8.59).

**To Reproduce**
Code below shows example of relevant part of my UI layout code.

```
egui::CentralPanel::default().show(&egui_ctx, |ui| {
    egui::TopBottomPanel::bottom("Scene Info Bar").show_inside(ui, |ui| {
        egui::menu::bar(ui, |ui| {
            egui::SidePanel::right("").show_inside(ui, |ui| {
                ui.horizontal(|ui| {
                    if let Some(_) = input.mouse() { // Input is WinitInputHelper
                        ui.label(format!(
                            "Window: ({:.2}, {:.2}),",
                            state.mouse_window_pos.x, state.mouse_window_pos.y
                        ));
                        ui.label(format!(
                            "Viewport: ({:.2}, {:.2}),",
                            state.mouse_viewport_pos.x, state.mouse_viewport_pos.y
                        ));
                        ui.label(format!(
                            "World: ({:.2}, {:.2})",
                            state.mouse_world_pos.x, state.mouse_world_pos.y
                        ));
                    }
                });
            });
        });
    });

    let available_rect = ui.available_rect_before_wrap();
    let size = ui.available_size_before_wrap();
    let img = ui.image(game_scene_texture_id, size);

    if let Some(Pos2 {
        x: mouse_x,
        y: mouse_y,
    }) = i.hover_pos()
    {
        state.mouse_window_pos.x = mouse_x * window.scale_factor() as f32;
        state.mouse_window_pos.y = mouse_y * window.scale_factor() as f32;

        let egui::Pos2 {
            x: viewport_x,
            y: viewport_y,
        } = img.rect.min;

        state.mouse_viewport_pos.x =
            state.mouse_window_pos.x - available_rect.min.x * window.scale_factor() as f32;
        state.mouse_viewport_pos.y =
            state.mouse_window_pos.y - available_rect.min.y * window.scale_factor() as f32;

        let viewport_width = img.rect.width() * window.scale_factor() as f32;
        let viewport_height = img.rect.height() * window.scale_factor() as f32;
        let viewport_dims = Vec2::new(viewport_width, viewport_height);
        let mut ndc = ((state.mouse_viewport_pos / viewport_dims) * 2.0) - 1.0;
        ndc.y *= -1.0; // Why is this necessary? Not impacting the bug in question.
        let ndc = Vec4::from((ndc, 1.0, 1.0));

        let inverse_projection = game.camera.get_projection().inverse();
        let inverse_view = game.camera.get_view().inverse();

        let world = inverse_projection * inverse_view * ndc;
        state.mouse_world_pos.x = world.x;
        state.mouse_world_pos.y = world.y;
    }
});
```

**Expected behavior**

I was expecting the bottom left of the image to be (0, 0).

**Screenshots**

<img width="1277" alt="Screenshot 2022-05-20 at 22 05 34" src="https://user-images.githubusercontent.com/17502031/169624876-5b9519fd-0986-4bf1-b301-0eead98d2486.png">

**Desktop (please complete the following information):**
```
egui = "0.16"
egui_wgpu_backend = "0.16"
egui_winit_platform = "0.13"
wgpu = "0.12"
winit = "0.26"
```

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

I don't know where the problem lies:
- I assume my maths is correct.
- It's possible the cause is due to floating point error.
- It could be that I'm using the wrong data from within egui to calculate the current screen, viewport and therefore world positions.
- It could be that I need to take some padding/style aspects of the central panel and image into account.
- It could be a bug in either the winit or wgpu backends.

I'm really at a loss and would appreciate some further pointers to help figure out if the bug is mine or in one of the consumed libraries.

**Comment by emilk** [comment]
This is not a bug report, but a "why isn't my code working?" question. The mouse cursor works great in egui, and the glow painter paints things where they should be painted, so if you can't figure out the correct transform matrix that's not a bug in egui.

Make sure you read up on the different coordinate systems and the differences between logical points and physical pixels. Perhaps take a look at the glow painter for more details.
