### ISSUE TITLE
Layout::bottom_up -> ui.horizontal -> ui.button with style.spacing.button_padding increases size downward

### ISSUE THREAD

**Issue by lunixbochs** [emilk/egui#1657]
(egui 0.18.1 on macOS 12.x with winit + wgpu backend)

When you nest these elements, then increase the vertical padding in `style.spacing.button_padding`, the button grows downward rather than upward, which causes a few problems.
```rust
ui.with_layout(egui::Layout::bottom_up(egui::Align::Center))
  ui.horizontal()
    ui.button()
```

I'm using a bottom-up layout because I'm trying to put multiple buttons horizontally at the bottom of a fixed size window below the content. The buttons do appear there, but if I add `button_padding`, the button expands downward to grow the window rather than upward with the layout.

I had to use `.fixed_size` for this demonstration, because if I use e.g. `.default_size`, the window becomes infinitely tall (presumably no matter how big the window is, the button grows it vertically every frame)

```rust
egui::Window::new("test")
    .fixed_size((160., 160.))
    .show(ctx, |ui| {
        ui.with_layout(egui::Layout::bottom_up(egui::Align::Center), |ui| {
            ui.horizontal(|ui| {
                ui.button("bottom button");
            }); 
        }); 
    }); 

egui::Window::new("test 2")
    .fixed_size((160., 160.))
    .show(ctx, |ui| {
        ui.style_mut().spacing.button_padding = (16.0, 64.0).into();
        ui.with_layout(egui::Layout::bottom_up(egui::Align::Center), |ui| {
            ui.horizontal(|ui| {
                ui.button("bottom button");
            }); 
        }); 
    }); 
```

<img width="279" alt="Screen Shot 2022-05-21 at 5 44 05 AM" src="https://user-images.githubusercontent.com/117642/169652015-bcd633c5-868e-4699-b8c0-0d56281e481a.png">

**Comment by lunixbochs** [comment]
Being more explicit about the layout seems to have helped:
```rust
egui::Window::new("test")
    .vscroll(false)
    .fixed_size((160., 160.))
    .show(ctx, |ui| {
        ui.with_layout(egui::Layout::bottom_up(egui::Align::Center), |ui| {
            ui.with_layout(egui::Layout::left_to_right().with_cross_align(egui::Align::Max), |ui| {
                ui.button("bottom button");
            }); 
        }); 
    }); 

egui::Window::new("test 2")
    .vscroll(false)
    .fixed_size((160., 160.))
    .show(ctx, |ui| {
        ui.style_mut().spacing.button_padding = (16.0, 20.0).into();
        ui.with_layout(egui::Layout::bottom_up(egui::Align::Center), |ui| {
            ui.with_layout(egui::Layout::left_to_right().with_cross_align(egui::Align::Max), |ui| {
                ui.button("bottom button");
            }); 
        }); 
    }); 
```

Is this due the the assumed initial_size in `ui.horizontal()`?

**Comment by emilk** [comment]
This is one of those "difficult to do in immediate mode" things. I think I'll close this in favor of [#pass](https://github.com/emilk/egui/issues/843)
