### ISSUE TITLE
egui-wgpu: Add a wgpu texture

### ISSUE THREAD

**Issue by parasyte** [emilk/egui#1662]
**Is your feature request related to a problem? Please describe.**

`egui-wgpu` has a method to upload raw image pixels and create an egui texture. It is missing a method to allocate an egui texture from a wgpu texture. This was available in `egui_wgpu_backend`: https://docs.rs/egui_wgpu_backend/0.17.0/egui_wgpu_backend/struct.RenderPass.html#method.egui_texture_from_wgpu_texture

**Describe the solution you'd like**

Add a similar method to `egui-wgpu` so that any texture usable by `wgpu` can also be used directly in `egui`.

**Describe alternatives you've considered**

- Stick with `egui_wgpu_backend` instead and update it to be compatible with `egui` 0.18. This was originally tracked in https://github.com/hasenbanck/egui_wgpu_backend/issues/60, but closed when `egui-wgpu` became a viable alternative.
- Animated textures can be updated every frame with the existing `update_texture` method, but this is unnecessary and probably a performance hit.

**Additional context**

This is an important feature for [`pixels`](https://crates.io/crates/pixels), which provides access to the wgpu texture view. And generally important for any application that renders to a texture.

**Comment by emilk** [comment]
closed in https://github.com/emilk/egui/pull/1660
