### ISSUE TITLE
Wrong transparency?!

### ISSUE THREAD

**Issue by lassade** [emilk/egui#1672]
**Describe the bug**

I'm loading a simple psd with the `psd` crate (see below) with a few transparent layers, the loaded layers are rendered using egui.

![stickman](https://user-images.githubusercontent.com/9643105/169919918-a66ae6f8-b769-49f2-9e67-220a5eab3641.png)

But as you see I'm getting a bunch of weird white stripes, the image is white in these areas but have alpha equal to 0.

![psd__load_glich](https://user-images.githubusercontent.com/9643105/169730100-6b6912e8-30ba-4e99-a92d-57ea589cc702.png)

I tested with miniquad (`egui-miniquad = "0.11.0"`) and winit/wgpu (`egui-winit = "0.18.0"` and `egui-wgpu = "0.18.0"`)  backends with the same result.

Inspecting the frame with RenderDoc shows the images here loaded correctly and have alpha == 0 in the white areas.
![render_doc](https://user-images.githubusercontent.com/9643105/169919936-d38f87dc-115f-4b2f-8653-57132512b2cb.png)

Why the alpha isn't working? Maybe I'm doing something wrong. I give a quick inspection in the shaders used in both miniquad and wgpu backends but didn't spot anything worng.

**Desktop**
 - OS: Windows 10
 - Version: egui 1.8.1

**Comment by lassade** [comment]
I kind fixed by adding `if (gl_FragColor.a == 0.0) discard;` at the end of the fragment function (in the miniquad backend)

**Comment by thomas992** [comment]
it looks like they are in multiple layers maybe something to refer to their [documentation](https://chinedufn.github.io/psd/user-guide/index.html) for?

**Comment by lassade** [comment]
It's because how egui does alpha blending, the images needs to be pre-multiplied, if the stickman above was white I would only see rectangles.

but pre-multiplying in shader will change the egui looks (especially the fonts)

**Comment by emilk** [comment]
You need to premultiply the alpha. Use https://docs.rs/epaint/latest/epaint/color/struct.Color32.html#method.from_rgba_unmultiplied if you are using `Color32`.

**Comment by JumpyLionnn** [comment]
I have the same issue. I use `egui_extras::RetainedImage`, how can I fix it?
`egui` version: 0.22.0
`egui_extras` version: 0.22.0
