### ISSUE TITLE
eframe freezes

### ISSUE THREAD

**Issue by MalekiRe** [emilk/egui#1673]
**Describe the bug**
Frozen crashing/crashy egui window

**To Reproduce**
``fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {
            ui.painter().galley(Pos2::new(10.0, 10.0), ctx.fonts().layout(String::from("hi"), FontId::monospace(10.0), Color32::BLACK, 0.0));
        });
    }``

**Expected behavior**
Paint my text at my position

**Screenshots**
![image](https://user-images.githubusercontent.com/50841145/169959274-10e3935d-f2b8-4d34-b69d-e6e46c308952.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by emilk** [comment]
What is the crash backtrace?

Can you also please read your own issue text and A) remove the text that isn't informative and B) format your code

**Comment by MalekiRe** [comment]
There is no crash backtrace, it does not crash it just freezes.

**Comment by emilk** [comment]
Can you make a minimal reproduce (based e.g. on examples/hello_world/src/main.rs)?

**Comment by emilk** [comment]
```rust
            let galley = ctx.fonts().layout(
                String::from("hi"),
                FontId::monospace(10.0),
                Color32::BLACK,
                0.0,
            );
            ui.painter().galley(Pos2::new(10.0, 10.0), galley);
```

This is a an unfortunate side-effect of resource locking in egui.
