### ISSUE TITLE
Add an option to allow input to pass through a window

### ISSUE THREAD

**Issue by popcar2** [emilk/egui#1677]
I'm trying to make an overlay for the entire screen that's always on top, and while almost everything works, it turns out egui doesn't support input to pass through its window. I removed window decorations, made the window transparent, and made it always on top, but it seems like you have to jump through many hoops to get input to pass through the window. 

Someone made [a good fork that allows input passthrough in egui](https://github.com/coderedart/egui_overlay) but I was hoping there would be a native option for it so I can stick with eframe and updated versions of egui rather than rely on a fork. I'm not sure if this is an issue with egui itself or windowing libraries, but hopefully someone can take a look. Thanks.

**Additional context**
![LBVAoljZWd](https://user-images.githubusercontent.com/16920817/169650767-37dc657d-ba24-4d02-b274-ea9bbfe44ab5.png)

I talked more about what I'm trying to achieve in [this discussion](https://github.com/emilk/egui/discussions/1656)

**Comment by coderedart** [comment]
this might soon be possible with https://github.com/rust-windowing/winit/pull/2232

**Comment by mgalos999** [comment]
It works if you add this line to `crates/eframe/src/native/run.rs` at line 386
`gl_window.window().set_cursor_hittest(false).unwrap();`

If you add that line then all mouse events will pass through the window for all examples.

To do a proper solution you'd obviously want a config item been passed through rather than globally forcing it.

**Comment by chastise** [comment]
> To do a proper solution you'd obviously want a config item been passed through rather than globally forcing it.

Can you expand on what you mean by this? It looks like your flag was part of egui's v0.20.1 release, but it seems to cause the window to render everything transparent and click-through-able.

I'm pretty new to rust / egui, but I'm not able to figure out how I could access the flag you're setting from within a running egui application, or how I might configure it to apply only partially.
