### ISSUE TITLE
Editor Hotkeys Conflict With Browser

### ISSUE THREAD

**Issue by thomas992** [emilk/egui#1683]
In the EasyMark text editor it tells you to use CTRL or CMD + R to raise text as opposed to CTRL+L to lower. This causes the web browser to refresh the page. I would recommend moving it over one to CTRL+Y

[website with common web browser hotkeys](https://www.howtogeek.com/114518/47-keyboard-shortcuts-that-work-in-all-web-browsers/#:~:text=Ctrl%2BW%2C%20Ctrl%2BF4,Open%20a%20new%20browser%20window.)

**Comment by thomas992** [comment]
CTRL+C for code needs to be changed as well

**Comment by emilk** [comment]
do you want to make a pr?
