### ISSUE TITLE
DatePickerButton displays calendar out of window when in table

### ISSUE THREAD

**Issue by ray-5050** [emilk/egui#1685]
If the DatePickerButton widget is included in a table and if the column width is less than 333.0 (hard coded size for calendar), then the left margin is not accounted for and the calendar is displayed out of the window.  See the attached files for both the issue and the fix screenshots.  

The fix is added to the button.rs in the datepicker folder.  The fix simply checks to see if pos.x is < the left margin and if so it's equated.  The code is added at line 98.  

`
if pos.x < ui.style().spacing.window_margin.left {
   pos.x = ui.style().spacing.window_margin.left;
}
`

**Button before table, no issue**
![datepickerbutton_before_table](https://user-images.githubusercontent.com/5865038/170613411-279b6ae6-da71-4a49-98e2-4eac1ae3d923.png)
**Button in Coumn 0, extends out of window**
![datepickerbutton_in_column0](https://user-images.githubusercontent.com/5865038/170613431-a78ddc4e-3a57-494f-b9bf-5f56c0a04fa1.png)
**Button in Coumn 1, extends out of window**
![datepickerbutton_in_column1](https://user-images.githubusercontent.com/5865038/170613446-e6bb8c4b-ad95-4820-bcab-32664124b7e2.png)
**After fix button before table, no change**
![after_fix_button_before_table](https://user-images.githubusercontent.com/5865038/170613341-ccb58c02-6d86-4e3b-b632-37bc8d549251.png)
**After fix button in column 0, issue fixed**
![after_fix_button_before_table](https://user-images.githubusercontent.com/5865038/170613341-ccb58c02-6d86-4e3b-b632-37bc8d549251.png)
**After fix button in column 1, issue fixed**
![after_fix_button_in column1_table](https://user-images.githubusercontent.com/5865038/170613670-cb5f4007-23d3-445b-8596-c28bc759a6aa.png)

**Comment by emilk** [comment]
do you want to make a PR?

**Comment by ray-5050** [comment]
Will do.
