### ISSUE TITLE
Autosave causes freeze every 30 seconds

### ISSUE THREAD

**Issue by TheCallSign** [emilk/egui#1686]
This behaviour has been around for a while. I think from 0.15 or 0.16.

On devices with slow storage devices (read older laptops), the auto-save function that runs every 30 seconds causes a noticeable freeze while it blocks the main thread. A fair amount of data is shown on screen and in Multiline text widgets displayed. 

I think egui should either offload the io call in the auto save function to a background thread or, at a minimum, allow the application developer to configure the auto save timing and toggle this functionality. I don't mind working on a PR for the latter. 

Perhaps we should add a method somewhere with a signature like `fn autosave_interval(interval: Option<Duration>) {..}`?
Setting to None would disable autosaving. 

env:
Linux signz 5.15.0-3-amd64 #1 SMP Debian 5.15.15-2 (2022-01-30) x86_64 GNU/Linux
rustc 1.62.0-nightly (52ca603da 2022-04-12)

**Comment by TheCallSign** [comment]
I realised that disabling persistence would disable autosaving. It is a workaround but I don't think losing persistence altogether is the best compromise.

**Comment by emilk** [comment]
Are you sure you are using 0.18.0?

App persistence was moved to a background thread in 0.18.0: https://github.com/emilk/egui/blob/master/eframe/CHANGELOG.md#0180---2022-04-30

**Comment by TheCallSign** [comment]
Thanks for pointing that out. My bad for not reading the change log properly. Cheers.
