### ISSUE TITLE
New 3rd party integration for winit, ash and vk_mem!

### ISSUE THREAD

**Issue by MatchaChoco010** [emilk/egui#169]
I publish a new integration, egui_winit_ash_vk_mem!
https://github.com/MatchaChoco010/egui_winit_ash_vk_mem
https://crates.io/crates/egui_winit_ash_vk_mem

I'll keep updating it, so I hope you'll add it to the Readme.

At the end, I would like to thank you for developing this wonderful library called egui.
Thank you.

**Comment by emilk** [comment]
Very cool, thank you! I added a link under https://github.com/emilk/egui#integrations
