### ISSUE TITLE
provide manual timeout to egui in reactive mode to force refresh even if there's no new input

### ISSUE THREAD

**Issue by coderedart** [emilk/egui#1691]
**Is your feature request related to a problem? Please describe.**
egui's reactive mode is really great for applications, but the UI not updating AT ALL is a pain point for many newbies. at present, they are usually told to call `request_repaint` from another thread. not really user friendly imo. 

**Describe the solution you'd like**
just let users set a optional timeout, and when there's no input for the duration of the timeout, egui does the request repaint thing itself.

**Describe alternatives you've considered**
I don't see any alternatives.

**Additional context**
all big three windowing libraries:  winit, GLFW and SDL2, have support for wait_event timeout function, where the event loop will yield control back to us when it fails to get any events for the specified timeout. so, it should be pretty clean to implement.

**Comment by emilk** [comment]
`eframe`:s web backend already repaints every second by default, and I agree this should be controllable and also implemented on native. Is it something you'd like to work on?
