### ISSUE TITLE
Create a type representing a range of ShapeIdx

### ISSUE THREAD

**Issue by AlphaModder** [emilk/egui#170]
**Is your feature request related to a problem? Please describe.**
I'm trying to make a timeline widget, which means drawing vertical rules behind content, as can be seen in something like [this](https://github.com/CedricGuillemet/ImGuizmo#imsequencer). In order to do that, I add the lines before drawing the content, then use `Painter::set` to update their length once the content height is known, as described in [this comment](https://github.com/emilk/egui/blob/b869db728b6bbefa098ac987a796b2b0b836c7cd/egui/src/layers.rs#L103). However, this is a suboptimal solution because I must store all the lines' `ShapeIdx`es in a `Vec`, incurring an allocation every frame. 

**Describe the solution you'd like**
It seems like the best way to solve this would be to alter the signatures of `Painter::extend` and `PaintList::extend` so that `shapes` is an `impl Iterator<Item=Shape>` (so that using them does not require an allocation) and then to make the return type a new struct `ShapeIdxRange` where `&ShapeIdxRange: IntoIterator<Item=ShapeIdx>`, enabling the user to iterate over the ids of the shapes added. (EDIT: It occurs to me changing the type of `shapes` would be a breaking change. We could add a new method `extend_iter` and leave `extend` a `Vec` if this is undesirable.)

If you agree with this design, the could should be simple enough that I'd be happy to implement it myself.

**Describe alternatives you've considered**
An alternative option would be to simply expose the inner `usize` of `ShapeIdx` and let the user handle keeping track of ranges. This is simpler, but makes accidentally creating an invalid `ShapeIdx` more likely.

**Comment by emilk** [comment]
Thanks for this issue!

An alternate (and maybe simpler) solution is to add a new `fn pre_allocate(&self, num_shapes; usize) -> std::ops::Range<ShapeIdx>` to `Painter` and `PaintList` that allocates the specified number of `Shape::Noop`. Example usage:

``` rust
let vertical_rule_indices = painter.pre_allocate(num_rules);
…
for (i, rule_idx) in vertical_rule_indices.enumerate() {
    let x = rect.left() + (i as f32) * rule_spacing;
    painter.set(rule_idx, Shape::line_segment(…));
}
```

**Comment by AlphaModder** [comment]
Ah, true, somehow I forgot `Range` existed. Probably would make the most sense to use it for the iterator type (though I seem to recall some discussion about whether making ranges `Iterator` as opposed to `IntoIterator` was a mistake.)

I didn't realize `Shape::Noop` was a thing either (only just started using `egui` recently), but seeing as it does, no reason not to go for the simpler solution there, especially since `PaintList::set` overwrites the data anyway.

**Comment by emilk** [comment]
There is another solution for this now, using `shape::Vec`
