### ISSUE TITLE
horizontal_wrapped doesn't work for elements inside add_enabled_ui

### ISSUE THREAD

**Issue by teochikhany** [emilk/egui#1702]
**Describe the bug**
The elements (buttons) inside the ui.horizontal_wrapped() do not wrap (move to the next row) if these elements are 
inside a ui.add_enabled_ui(). They wrap correctly if the ui.add_enabled_ui is removed.

```rust
                ui.horizontal_wrapped(|ui| { 
                    // more buttons
                    ui.add_enabled_ui(!self.images.is_empty(), |ui| {  
                        if ui.button("free images!").clicked() {  
                            self.images.clear();  
                        }   
                    });  
                    // bla bla
                 });
```
![image](https://user-images.githubusercontent.com/47039131/171180281-50bf43eb-3ed3-4020-9c37-90e8412d12f8.png)

<hr>

**Expected behavior**
The elements are suppoed to go to the next line/row.

```rust                    
                    ui.horizontal_wrapped(|ui| { 
                     // more buttons
                     // ui.add_enabled_ui(!self.images.is_empty(), |ui| {
                        if ui.button("free images!").clicked() {
                            self.images.clear();
                        } 
                    // });
                    // bla bla
                   });
```

![image](https://user-images.githubusercontent.com/47039131/171179915-07331f36-7d1c-477f-a180-c37f97743908.png)

Notice how the "free images" button move to the next line, instead of being squashed.
This was built both using eframe=0.18.0 and using the latest master branch with the same result.

**Desktop:**
 - OS: Windows 10 Pro
 - Version: 21H2
 - OS Build: 19044.1706

**Comment by emilk** [comment]
Yeah, this is just a limitation of immediate mode. Putting a `Ui` inside of a layout will never respect the parent layout (not fully). BUT `ui.add_enabled` should work!
