### ISSUE TITLE
simple switch interface primitive prorosal

### ISSUE THREAD

**Issue by adsick** [emilk/egui#171]
![image](https://user-images.githubusercontent.com/24528839/107686542-0b9ed500-6cae-11eb-8553-5ac208b1728d.png)

this thing would be  nice to have.

**Comment by emilk** [comment]
What would the switch look like? What would make it different from a checkbox? Should we perhaps have a style option for checkboxes instead?

**Comment by adsick** [comment]
oh, didn't knew there is checkbox) basically the same thing but checkbox is more general. my switch thing is for those who are lazy in terms of storing ```checked``` value somewhere.
low priority proposal, never mind.

**Comment by emilk** [comment]
One of the main ideas of an immediate mode gui like `egui` is that the gui libary is only there to show and change the state of the application, but without retaining any state itself. That is, the state lives in the app, and egui just shows it and lets you interact with it.

egui can't reliably store a value for the user unless you supply egui with a unique ID to associate with the value, and then it is probably just easier to store a `bool` anyway.
