### ISSUE TITLE
Create an Undoer Example in the egui Demo App

### ISSUE THREAD

**Issue by zicklag** [emilk/egui#1713]
**Is your feature request related to a problem? Please describe.**
I didn't know about the awesome undoer utility, and almost wrote my own before stumbling upon it by chance while looking for something else in the egui docs.

**Describe the solution you'd like**
We could have a new demo window in the egui Demo App that just has a text box, and maybe an extra text-box or radio button, that allows you to undo by clicking a button or using a keyboard shortcut.

**Describe alternatives you've considered**
Somehow making the utility more visible in the API docs might be a good idea in addition or alternatively to the demo window.

**Additional context**
I often use the egui demo app as kind of an examples index / "feature list" so I think having the undoer featured in a demo would help increase its visibility, and I've found the feature very useful for my app. It made implementing undo painless, when it could have been quite some trouble.

**Comment by emilk** [comment]
Good idea! Feel free to contribute a PR

**Comment by zicklag** [comment]
OK, cool, I'll do that. :+1:
