### ISSUE TITLE
Text justification within SelectableLabel

### ISSUE THREAD

**Issue by rob-mur** [emilk/egui#1724]
It would be useful to be able to change the text alignment of text within a selectable label. In particular, to get the effect as seen [here ](https://angular.io/tutorial/toh-pt2#style-the-selected-hero ) in the Angular tour of heroes tutorial. 

This could be passed in as an align parameter to SelectableLabel, or perhaps there could be a builder method. For now I just wanted the left justify version so you can see a hacky version that does left justify in the code below:

```rust
 if ui.is_rect_visible(response.rect) {
            // let text_pos = ui
            //     .layout()
            //     .align_size_within_rect(text.size(), rect.shrink2(button_padding))
            //     .min;

            let text_pos = rect.min + button_padding;

            let visuals = ui.style().interact_selectable(&response, selected);

            if selected || response.hovered() || response.has_focus() {
                let rect = rect.expand(visuals.expansion);

                ui.painter()
                    .rect(rect, visuals.rounding, visuals.bg_fill, visuals.bg_stroke);
            }

            text.paint_with_visuals(ui.painter(), text_pos, &visuals);
        }
```

I'd be happy to implement this if I could get some guidance on the API design to keep in line with your preferences.

**Comment by emilk** [comment]
`SelectableLabel` takes a `egui::WidgetText`. You can customize the text a lot if you use https://docs.rs/egui/latest/egui/text/struct.LayoutJob.html
