### ISSUE TITLE
Multicolor TextEdit widgets (for Syntax Highlighting etc.)

### ISSUE THREAD

**Issue by the-drunk-coder** [emilk/egui#173]
**Is your feature request related to a problem? Please describe.**
I'm working on a little code editor with egui, and of course it'd be nice to have syntax highlighting ...

**Describe the solution you'd like**
A TextEdit widget that allows to pass a color map.

As a matter of fact I already implemented multicolor methods in `tesselator.rs` and `painter.rs` in my egui fork (which I otherwise keep aligned with the latest version): 

https://github.com/the-drunk-coder/egui/blob/master/epaint/src/tessellator.rs#L730
https://github.com/the-drunk-coder/egui/blob/master/egui/src/painter.rs#L324

Works fine, but I'm not sure if that's how you'd do it ...

**Comment by emilk** [comment]
Interesting! I think this could be a very useful feature with not much work. So do you envision something like `ui.add(TextEdit::multiline(my_text).colormap(my_highlighting));` then? If the user enters text then the colormap will be wrong that frame, but maybe having the colors be off by a few characters for a frame is fine.

I wonder if such a feature should be extended to also cover things like background color, underline, _italics_ and ~strikethrough~, though arguably that is a lot more work for something a lot less useful.

Buy the way, I have an opt-in feature in the demo app which applies syntax-highlighting to the results of HTTP requests using the [`syntect`](https://github.com/trishume/syntect) crate: <https://github.com/emilk/egui/blob/master/egui_demo_lib/src/apps/http_app.rs#L197-L251>. What are you using for syntax highlighting?

**Comment by the-drunk-coder** [comment]
Well the final color map is calculated every frame and maps character positions to text color changes. It's then passed to the painter method mentioned above. 

The color map on the higher level that is passed to the text edit widget are mappings from function names, keywords etc. to their respective colors.

To generate the final map so far i just look for the positions of the keywords etc, and calculate the color changes from that.

**Comment by emilk** [comment]
I think having the colormap as a `BTree<usize, Color32>` works, but and ordered `Vec<(usize, Color32)>` might be more efficient, but also harder to use. In any case a wrapper type is in order: `struct Colormap(…)` and pass that on to the tessellator and painter like in your fork. Feel free to open a PR!

**Comment by Pebaz** [comment]
I'd like to express my interest for a syntax highlighting widget also! I think the example in the demo is perfect, but I would prefer if it were standardized rather than having to custom make it. Either way thanks for the example it's really cool! :)

**Comment by kotx** [comment]
I'm also interested in this feature, has there been any progress recently?

**Comment by emilk** [comment]
This is being worked on in https://github.com/emilk/egui/pull/682

**Comment by emilk** [comment]
Closed by https://github.com/emilk/egui/pull/682
