### ISSUE TITLE
About CollapsingHeader's

### ISSUE THREAD

**Issue by outomla** [emilk/egui#174]
Quick question - is there a way for collapsing headers to be enabled quite like the bool on button? I am running into a problem where I would not like the content within a header rendered until, for lack of a better comparison, .clicked() is enabled. I quite like the implementation of buttons but am curious on how to not .show() a collapsing header until an action. With cascading tree structures of collapsing headers with a lot of information, implementations get slow quickly as the calls are recursively generating headers. Yes - this is more an implementation detail that is user error - BUT I think that having an action on headers would be a life saver for people. 

 Sorry for my bad question/comment - I am new to the library.

**Comment by emilk** [comment]
Just to make sure I understand the question: You'd like to control whether or not a `CollapsingHeader` is collapsed/expanded based on a `bool` you pass to `CollapsingHeader` and ignore any clicks on the `CollapsingHeader`?

If that is what you mean: that is not currently supported, but it is a good idea and something I can add pretty quickly.

**Comment by outomla** [comment]
Thanks for getting back so fast and for making an amazing library! 

So adding onto what you said - yes that would be an amazing addition. I was thinking more along the lines of unless header clicked, do not render ui elements ( .show() ). This could be a simple label or more complex structures. Hopefully that makes it a bit more clear.

**Comment by emilk** [comment]
Closed by https://github.com/emilk/egui/issues/174
