### ISSUE TITLE
Artifacts rendering on the web using three-d

### ISSUE THREAD

**Issue by Yeicor** [emilk/egui#1744]
**Describe the bug**
Using a custom glow context for web is buggy (see demo gif). This happens for both desktop and mobile browsers (see versions below), so I think it is a web backend + custom glow code bug.

![demo](https://user-images.githubusercontent.com/4929005/174131468-2bee6136-a3ae-4703-8d4f-fbb07f0f57d1.gif)

**To Reproduce**
1. Download the latest source code (7eeb292adfacd9311a420ac3ea225e2261a8f8d3).
2. Apply this patch to be able to run the example for web: [custom_3d_three_d_web.diff.txt](https://github.com/emilk/egui/files/8921112/custom_3d_three_d_web.diff.txt)
3. From `examples/custom_3d_three-d/`, execute `wasm-pack build --target web --out-dir ./target/pkg` and `cp index.html target/pkg` to prepare the static site.
4. Serve the files at `target/pkg`, for example with `python -m http.server`, and open the directory in any browser

**Expected behavior**
I expected the triangle to render exactly like the desktop version on the same machine:

![demo_14](https://user-images.githubusercontent.com/4929005/174131797-5ce97733-1699-4cca-8faa-21d6ca39fc74.gif)

**Desktop**
 - OS: Manjaro Linux
 - Browser: tested on Google Chrome 101.0.4951.54 (Official Build) (64-bit) and Firefox 101.0.1 (64-bit) with the same results.

**Mobile**
 - Device: Poco F3
 - OS: Android 12
 - Browser: tested on Google Chrome 102.0.5005.78 and Firefox 101.2.0 with the same results.

**Comment by Yeicor** [comment]
FWIW, custom glow code works on the web if instead of rendering to a widget I render directly to the initial glow context. [Demo](https://yeicor.github.io/sdf-viewer/) with [these](https://github.com/Yeicor/sdf-viewer/blob/v0.0.15/src/app/mod.rs#L61) [sources](https://github.com/Yeicor/sdf-viewer/blob/v0.0.15/src/app/scene/mod.rs#L136).

**Comment by Yeicor** [comment]
This bug seems partially related to rendering the background of Frame::canvas for web, as setting `Frame::canvas(ui.style()).fill(Color32::from_rgba_unmultiplied(0, 0, 0, 0))` almost solves it.

After this change, things like tooltips or other removed widgets that previously overlapped the canvas area are still visible over the content of the canvas, even if clear is called from the canvas rendering code. This happens only on the web, the desktop still renders as expected, cleaning up removed widgets.

**Comment by emilk** [comment]
The pure `glow` example at egui.rs works fine (at least for me), so this might be a bug related to how WebGL state is stored/restored in `egui_glow` vs `three-d`. Perhaps @asny has some idea?

**Comment by asny** [comment]
I've learned (the hard way) that you should never be too confident about what causes a bug, but I am fairly certain that this has something to do with blending. I've had several issues with that in the past since OpenGL default blend parameters does not work together with the transparent canvas background. Therefore the default blend parameters in `three-d` for transparency are different than default OpenGL (see [here](https://github.com/asny/three-d/blob/dee4ec6eb346cb1ab47a9ebdf8dd2808ed5e914f/src/core/render_states.rs#L178)). 

@Yeicor can I get you to test with a different blend setting, for example `Blend::STANDARD_TRANSPARENCY` instead of `Blend::TRANSPARENCY` in the materials `render_states`? It also depends on how the widget background is cleared (as you already figured out), but I guess clearing the widget to a transparent background (alpha = 0) is not really an option since you would be able to see the main window through the widget?

Another thought is z-fighting because it looks like z-fighting, but I can't see why that should happen on web widget only.

**Comment by Yeicor** [comment]
Thank you both for your help and projects :wink:. I tried mixing and matching your suggestions but, unfortunately, I cannot get the `three-d` demo working without setting the alpha of the background to 0. Here's what I've tested:

> The pure `glow` example at egui.rs works fine (at least for me)

Yes, I can also confirm that the `custom_3d_glow` example works, so the issue must be related to the `three-d` integration.

> @Yeicor can I get you to test with a different blend setting, for example `Blend::STANDARD_TRANSPARENCY` instead of `Blend::TRANSPARENCY` in the materials `render_states`?

I added the following line after the definition of the only model that is rendered, but I get the same results.
```rust
model.material.render_states.blend = Blend::STANDARD_TRANSPARENCY;
``` 

> I guess clearing the widget to a transparent background (alpha = 0) is not really an option since you would be able to see the main window through the widget?

It works for my project (except for the overlapping content bug mentioned [above](https://github.com/emilk/egui/issues/1744#issuecomment-1158576638)), but if the 3D scene is rendered in a window over other contents it probably breaks too (untested).

> Another thought is z-fighting because it looks like z-fighting, but I can't see why that should happen on web widget only.

To test this I moved the model towards the camera with the same results.
```diff
- model.set_transformation(Mat4::from_angle_y(radians(angle)));
+ model.set_transformation(Mat4::from_translation(Vector3::new(0.0, 0.0, 1.0)).mul(
+       Mat4::from_angle_y(radians(angle))));
``` 

> also try changing the alpha blend function of `egui_glow`

I applied this patch and tried combining it with the ones above but I always get the same results as the initial gifs.

**Comment by asny** [comment]
Thanks for testing 👍 It was worth a try! I will take a closer look soon, hope you're not blocked until then 🙂 

Also, really cool project you are working on, I also want to take a closer look at that 🤓

**Comment by Yeicor** [comment]
Sure, take your time. I am not blocked by this issue. 

Thanks for your interest in my project, it needs a little more work but it's working quite nicely thanks to your libraries 🤗.

**Comment by emilk** [comment]
`egui_glow` paints directly to the main framebuffer except when using WebGL1 or other places where sRGB framebuffer blending is not available (then we paint to https://github.com/emilk/egui/blob/master/egui_glow/src/post_process.rs)

**Comment by asny** [comment]
@emilk Any input on this? I'm not sure how important it is though 🙂

**Comment by emilk** [comment]
> The flow would look something like this:
> 
>  * Render egui stuff to the `PostProcess` frame buffer (without any depth buffer, only color)
>  * Copy/blit the `PostProcess` frame buffer to the screen frame buffer
>  * Call `PaintCallback`

The problem is compositing. Say you have a 3D scene and want a popup menu to cover it. At the moment that works as it should thanks to painters algorithm (painting back-to-front).

So the process would be a more complex and expensive:

```
post_process.bind();
clear(Color | Depth);
for primitive in primtivies {
    match primitive {
        Mesh(mesh) => mesh.paint();,
        Callback(callback) => {
            screen_frame_buffer.bind();
            post_process.paint(); // blit onto main framebuffer
            callback.paint();
            post_process.bind();
            clear(Color | Depth); // start over
        }
    }
}
```

…and then the blending would still not be correct between egui widgets.

---

How about we just tell `PaintCallback` what FBO to render to? Then `three-d` can do its own render-to-texture, and then restore the correct FBO target instead of assuming the screen framebuffer.

The only other solution I see is to stop using linear blending in egui. It causes a lot of other complexities so I'm not sure it worth it (and I've been experimenting with removing it in https://github.com/emilk/egui/pull/1411)

**Comment by asny** [comment]
Arh, yes that makes sense 😕  

Parsing the FBO in `PaintCallback` is definitely an option, though it's not super elegant (I imagine it is going to be ugly to go from a low-level FBO to a high level `RenderTarget` but might not be as bad as I imagine). Also, to make it consistent between for example native and web, you need to be able to set the properties of the `PostProcess` framebuffer (similar to the options passed into `eframe`, for example number of bits in depth buffer, multisampling etc.). If only `egui` was post processed, we could avoid this completely. 

What if we instead do it the other way around?
```
post_process.bind();
clear(Color);
for primitive in primitivies {
    match primitive {
        Mesh(mesh) => mesh.paint();,
        Callback(callback) => {}
    }
}

screen_frame_buffer.bind();
clear(Color | Depth);
for primitive in primitivies {
    match primitive {
        Mesh(_) => {},
        Callback(callback) => {
            callback.paint();
        }
    }
}
post_process.paint(); // blend onto main framebuffer with depth test disabled
```

Usually you want the GUI on top of everything else, or am I missing something (again)? AFAIK this would yield the exact same result for the GUI with regards to blending and pop-ups.

**Comment by emilk** [comment]
> Also, to make it consistent between for example native and web, you need to be able to set the properties of the `PostProcess` framebuffer (similar to the options passed into `eframe`, for example number of bits in depth buffer, multisampling etc.).

That's easy enough to fix in `eframe`.

> Usually you want the GUI on top of everything else, or am I missing something (again)? AFAIK this would yield the exact same result for the GUI with regards to blending and pop-ups.

There are cases when you want the 3D on top. For instance, you may want to show a 3D preview in a tooltip when hovering something.

**Comment by asny** [comment]
> That's easy enough to fix in eframe.

So you can use the same parameters as passed into `eframe` for the post processing?

> There are cases when you want the 3D on top. For instance, you may want to show a 3D preview in a tooltip when hovering something.

Oh God 😆 

I think passing the FBO sounds like the right solution then 🙂 I will update the `custom_3d_three-d` example to use this approach 💪
