### ISSUE TITLE
Selection Stroke Color is the same color for the cursor for the text box.

### ISSUE THREAD

**Issue by pepperoni42069** [emilk/egui#1749]
`ui.visuals_mut().selection.stroke.color ` is the same color for the text edit cursor, could you make it so we can change the color of the selection stroke color without changing the text edit cursor color. If you could just tell me where in the code the text edit cursor code is i might be able to do it myself, but im new to rust. So can you add this

**Comment by Eskerepvp** [comment]
![image](https://user-images.githubusercontent.com/75771072/174287683-4120067c-9ea0-4bdb-9882-49992f728be8.png)
![image](https://user-images.githubusercontent.com/75771072/174287695-284aa170-fa05-4529-9099-ad09394e8904.png)
Thats what im talking about

**Comment by emilk** [comment]
I think adding a separate `cursor: Stroke` to `struct Visuals` makes sense.

The code is in `paint_cursor_end` in `egui/src/widgets/text_edit/builder.rs`
