### ISSUE TITLE
Bottom Up Grid Incorrect Size

### ISSUE THREAD

**Issue by daaku** [emilk/egui#175]
Adding a `Grid` to a `bottom_up` layout doesn't render as expected. Here's a minimal sample:

```rust
use eframe::{egui, epi};

struct App;

impl epi::App for App {
    fn name(&self) -> &str {
        "Grid Bottom"
    }

    fn update(&mut self, ctx: &egui::CtxRef, _frame: &mut epi::Frame<'_>) {
        egui::CentralPanel::default().show(ctx, |ui| {
            ui.label("Top");
            ui.with_layout(egui::Layout::bottom_up(egui::Align::Center), |ui| {
                egui::Grid::new("meta").striped(true).show(ui, |ui| {
                    ui.label("Account");
                    ui.label("emilk");
                    ui.end_row();

                    ui.label("Repo");
                    ui.label("egui");
                    ui.end_row();
                });
            });
        });
    }
}

fn main() {
    eframe::run_native(Box::new(App {}));
}
```

I've tried this on Linux with Wayland with the master branch.

PS: I'd like to take this opportunity to understand what's going on and fix it myself, but I'm currently lost between the `Grid`, `Layout`, `Placer` and `Ui`. Any hints / implementation notes would be much appreciated!

**Comment by emilk** [comment]
Grids are allways top-down, left-to-right. If you want to change that order... I guess you'll have to change `Grid`. `Grid` is very separate from `Layout`. `Placer` is basically what switched between them (if there is a `Grid`, placer uses it to place the next widget. if not, it uses `Layout`).

Also: bottom-up and right-to-left layouts are not very well tested, so there be bugs and features missing. I think `Layout` needs a rewrite for it to work properly, with better cursor tracking.

**Comment by emilk** [comment]
Not a bug
