### ISSUE TITLE
Demo web app. 3D painting. button (source code) click not working

### ISSUE THREAD

**Issue by barrrettt** [emilk/egui#1761]
Url not exits when click on (souce code) 

![image](https://user-images.githubusercontent.com/47840319/175047339-8edaa54a-3a0b-4a28-9b76-2e7e69117b37.png)

> good work with this repo guys! 👏🏽

**Comment by barrrettt** [comment]
https://github.com/emilk/egui/blob/master/egui_demo_app/src/apps/custom3d.rs

**Comment by emilk** [comment]
It's been moved since the last release - it will be fixed when a new release is made.

here it is in the meantime: https://github.com/emilk/egui/blob/master/egui_demo_app/src/apps/custom3d_glow.rs
