### ISSUE TITLE
The image format Png is not supported

### ISSUE THREAD

**Issue by DLM8207** [emilk/egui#1767]
**When I runned the retained image example,I got a error:thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "The image format Png is not supported"'**

**To Reproduce**
1. impl Default for MyApp {
    fn default() -> Self {
        Self{
            image:RetainedImage::from_image_bytes(
                "rust-logo-256x256.png",
                include_bytes!("rust-logo-256x256.png"),
            ).unwrap(),
        }
    }
}

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11

**Comment by xTibor** [comment]
Do you have the `png` feature of the `image` crate enabled in your `Cargo.toml`? There's an [example here](https://github.com/emilk/egui/blob/eeae485629fca24a81a7251739460b671e1420f7/examples/retained_image/Cargo.toml#L14) how to enable it.
