### ISSUE TITLE
Text is blurry on NVIDIA cards

### ISSUE THREAD

**Issue by blueglyph** [emilk/egui#1768]
**Describe the bug**
The text is blurred on native examples. The work-around is to disable FXAA in the NVIDIA control panel for each executable that is produced (or globally at the expense of quality for all other software which don't suffer from this problem).

**To Reproduce**
- clone the master branch (I used rev eeae485629fca24a81a7251739460b671e1420f7)
- build the executable (release or debug doesn't matter)
- run the executable
=> text is blurred

**Screenshots**

Click on each of the screenshot to open them at 100% in seperate tabs, it's easier to compare.

- with FXAA
![image](https://user-images.githubusercontent.com/31706195/175526582-00e6ce2e-b8e1-4a4c-8f40-057e88cefca7.png)

- without FXAA
![image](https://user-images.githubusercontent.com/31706195/175526632-92aa2619-16b9-41f4-b32d-34ebc9573382.png)

**Desktop (please complete the following information):**
- OS: Windows 10 64-bit
- NVIDIA RTX 3070
- NVIDIA driver 497.09
- active toolchain:
   - stable-x86_64-pc-windows-msvc (default)
   - rustc 1.61.0 (fe5b13d68 2022-05-18)

**Comment by emilk** [comment]
So NVIDIA adds a FXAA pass on eframe apps, and the result is blur?

Well, that sucks. Tell NVIDIA to stop doing that!

I don't see how egui can fix this. This is similar problem to "my brother poured paint on my computer screen, and now all egui apps are red" :P

**Comment by blueglyph** [comment]
It's rather a case of egui not being able to use the API correctly, but up to you.

**Comment by emilk** [comment]
Maybe you are right! How is `egui_glow` using the API incorrectly? Is `egui-wgpu` using it correctly?

As far as I know, neither `egui_glow` nor `egui-wgpu` opts in to the drivers adding post-processing effects to the application. FXAA is made for video games, but as far as I know there isn't an OpenGL API for saying "This is not a video game!" but maybe I'm wrong?
