### ISSUE TITLE
Path routing like in React

### ISSUE THREAD

**Issue by erikpa1** [emilk/egui#1769]
Hi, in the React JS there is something called routing where I can render components based on browser path I'm currently on.

Its like:

```
function MyView() {

 return (
        <Router>
            <Route path={"/home"}>
                <MyGUi></MyGUi>
            </Route>
            <Route path={"/projects"}>
                <MyAnotherGUi></MyAnotherGUi>
            </Route>
        </Router>
)

}
 
```
(For those who don't know react, this is xmlike syntax inside javascript which is compiled to valina javascript - its not xml static code!)

It could be nice to have something like this in egui

this could be made by registering functions like:

```
eframeInstance.route("/home", |contex| {draw_home(context)}
eframeInstance.route("/projects/<projectid>", |contex| {draw_home(context)})
```

and the re-routing could be like this:

if ui.button("Home").clicked() {
    egui::route("/home")
}

I think this could be nice feature of UI framework with minimum work and maximum efficiency, which could also add possibility of easy back and forward button functionality, with maybe undo system when there will be link variables + could also integrate native browser routing.

**Comment by emilk** [comment]
You can find the current path with https://docs.rs/eframe/latest/eframe/struct.Frame.html#method.info and follow links with https://docs.rs/egui/latest/egui/struct.PlatformOutput.html#structfield.open_url
