### ISSUE TITLE
RetainedImage clicked not working

### ISSUE THREAD

**Issue by erikpa1** [emilk/egui#1770]
Hi, I'm using RetainedImage from egui_extras for rendering SVG image but it seems that .clicked() is not working

`icon_projects: RetainedImage::from_svg_bytes("project_icons", include_bytes!("projects.svg")).unwrap()`

then:

```
        let mapIcon = self.icons.icon_projects.show_size(ui, egui::Vec2 { x: imageSize, y: imageSize });
         println!("{}", mapIcon.hovered());
        println!("{}", mapIcon.clicked());
```

I'm using
```
eframe = "0.18.0"
egui_extras = { version = "0.18.0", features = ["svg"] }
```
Platform - Windows

![image](https://user-images.githubusercontent.com/19526670/175781609-86f5d3c6-0126-40cf-9f4f-21f52c68a3bb.png)

**Comment by emilk** [comment]
This is explained by https://docs.rs/egui/latest/egui/struct.Response.html#method.clicked
