### ISSUE TITLE
Metal validation error WGPU "Draw Indexed Primitives Validation indexCount(0) must be non-zero"

### ISSUE THREAD

**Issue by ScanMountGoat** [emilk/egui#1772]
**Describe the bug**
egui generates empty mesh primitives in some circumstances, which causes validation errors when using egui-wgpu with the Metal backend. This makes it harder to perform GPU debugging on Mac with validation enabled, since the debugger terminates the program after hitting this error. Running the application without validation enabled works without issues.

```
-[MTLDebugRenderCommandEncoder validateDrawIndexedPrimitives:indexCount:indexType:indexBuffer:indexBufferOffset:instanceCount:function:]:5605: failed assertion `Draw Indexed Primitives Validation
indexCount(0) must be non-zero.
'
```

**To Reproduce**
The easiest way I found to reproduce this behavior is to add too many items to fit on screen to a scroll area. 
Looking at the output of `ctx.tesselate(...)`, I noticed that some of the mesh primitives have empty vertex and index lists.

```rust
pub fn update(&mut self, ctx: &egui::Context) {
    egui::CentralPanel::default().show(ctx, |ui| {
        ScrollArea::vertical().show(ui, |ui| {
            // Some number large enough to fill past the window.
            for _ in 0..30 {
                ui.label("Test");
            }
        });
    });
}
```
Example of an empty primitive that gets generated:
```
Mesh {
    indices: [],
    vertices: [],
    texture_id: Managed(
        0,
    ),
}
```

**Expected behavior**

The wgpu backend shouldn't attempt to draw any primitives with no vertices. This could probably be incorporated as a check into `ctx.tesselate(...)`.

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**

**Comment by emilk** [comment]
I think this should be fixed in two places:

A) the `tessellator` should not generate empty meshes (instead, skip them).
B) the `wgpu` backend should handle empty meshes without crashing

Fixing this should be rather simple. Do you want to take a stab at it?

**Comment by coderedart** [comment]
wgpu backend already skips rendering if `clip_rect` is zero (wdith or height) which is also a validation check. https://github.com/emilk/egui/blob/master/egui-wgpu/src/renderer.rs#L371

i think adding another check for empty index count would be the same thing.
