### ISSUE TITLE
`add(label)` justifies the text left but `add_sized(ui.available_size(), label)` justifies the text center

### ISSUE THREAD

**Issue by cbeust** [emilk/egui#1773]
**Describe the bug**

    ui.add(Label::new("Disassembly"));

produces the following:

![unknown-1](https://user-images.githubusercontent.com/92322/176307024-0c3e18a7-5770-4608-93c9-7efef27e40d5.png)

but

    ui.add_sized(ui.available_size(), Label::new("Disassembly")); 

produces:

![unknown-2](https://user-images.githubusercontent.com/92322/176307110-ca8a03b3-fe7d-449f-bc5d-37142eb340b2.png)

**Expected behavior**

Specifying a size for the label should not alter the justification of its text.

**Desktop (please complete the following information):**

- Windows 11
- egui 0.18.1

**Comment by emilk** [comment]
This is not a bug. Use a `Button` instead and you'll see why!

In the first case, the label is small, and i put leftmost (because of the layout it is in).
In the second case, the label is big (taking up all the available size).

In both cases the text is centered _within_ the label.
