### ISSUE TITLE
Have an optional parameter for the Area container to constrain its dragging bounds

### ISSUE THREAD

**Issue by aakamenov** [emilk/egui#178]
**Is your feature request related to a problem? Please describe.**
This might be more of a rare use case (which I ran into), but it would be nice to have the option to constrain the dragging of an `Area` into a specified zone. The current implementation only allows these constraints to be the program window/web canvas.

_Example_: In my scenario I have two same size panels, side by side, each of which can contain a number of `Area` containers with some widgets inside of them that the user can freely move around. However, I don't want them to be able to move the areas outside of their panels. The current implementation doesn't allow me to achieve this (or at least not easily if at all).

**Describe the solution you'd like**
I've come up with an API like `Area::new("id").drag_bounds(bounds).show(...` where `bounds` is a `Rect`. Supposedly, this should be implemented for `Window` as well?

I have this working locally (implemented only for `Area` so far), so I can submit a PR if this is something that we should have.

Thoughts?

**Comment by emilk** [comment]
Yeah, sounds like a good idea!

**Comment by aakamenov** [comment]
Added with #201
