### ISSUE TITLE
thread 'main' panicked at 'Failed to find Name("Heading2") in Style::text_styles. Available styles:

### ISSUE THREAD

**Issue by DLM8207** [emilk/egui#1785]
**When I runned custom font style example,I got a error:thread 'main' panicked at 'Failed to find Name("Heading2") in Style::text_styles. Available styles:**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser 
 - Version 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by emilk** [comment]
Are you sure? `cargo r -p custom_font_style` works for me on `master`.
