### ISSUE TITLE
Layout::right_to_left() clips the group frame

### ISSUE THREAD

**Issue by cbeust** [emilk/egui#1786]
**Describe the bug**
The following code:

        egui::CentralPanel::default().show(ctx, |ui| {
            ui.group(|ui| {
                ui.with_layout(Layout::right_to_left(), |ui| {
                    ui.button("Right");
                });
                ui.label("Left");
            });
        });

produces this UI:

![Screenshot 2022-07-01 093541](https://user-images.githubusercontent.com/92322/176935240-24ddf963-2976-4af4-8b49-9374613e51b6.png)

Note that the Left label is not only at the bottom of the window but also clipped, and the frame of the group is clipped as well.

**Desktop (please complete the following information):**
- Windows 11
- egui 0.18.1

**Comment by emilk** [comment]
As documented, `with_layout` takes up all available space. So any call after that will have no space left.
