### ISSUE TITLE
TextEdit::code_editor not registering curly brackets on native macOS/eframe application

### ISSUE THREAD

**Issue by sonodima** [emilk/egui#1795]
**Describe the bug**
When run natively on macOS, the TextEdit::code_editor widget does not register any curly bracket input.

**To Reproduce**
1. Create a basic eframe project and add a code_editor widget.
2. Run it on a macOS machine
3. Select the code_editor
4. Try writing a curly bracket

**Expected behavior**
Curly braces are written correctly in the widget

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.4
 - Keyboard Layout: Italian [IT]
 - OS Language: English
 - Device: M1 Pro MacBook Pro

**Additional context**
The bug is still present in the latest master.

**Comment by emilk** [comment]
This broke in https://github.com/emilk/egui/pull/1697
