### ISSUE TITLE
Is it possible to make new release for egui_wgpu?

### ISSUE THREAD

**Issue by setzer22** [emilk/egui#1805]
Hi! I've been using egui for [my project](https://github.com/setzer22/blackjack) and I wanted to update it to use 0.18. However, I can't update because what used to be `egui_wgpu_backend` and `egui_winit_platform` are now bundled as part of egui (in `egui_winit` and `egui_wgpu`). When fixing the egui integration inside `rend3`'s integration, which is the one I'm using, I realized there was a function that got lost during the migration (details here: https://github.com/BVE-Reborn/rend3/pull/400).

This function was reintroduced in 5d15e3d367632289, but this was after the release of 0.18. I understand the current goal is to keep the version of egui_wgpu in lockstep with core egui, so releasing a 0.19 may not be possible at this point. But since egui 0.19 may still take a while, I wanted to ask: Would it be possible to release a new `egui_wgpu` version with the changes from the commit above? Since that only adds a new function and breaks no existing functionality, it could be sneaked in a potential 0.18.1, even though that is not strictly how SemVer works.

**Comment by emilk** [comment]
The problem is that `egui-wgpu` on `master` is incompatible with latest egui (`0.18`) (at least if I recall correctly), which means we also need to do a new egui release first.

**Comment by setzer22** [comment]
I see, that's unfortunate :/  But yes, there's not much that can be done until next release then.

FWIW, `egui_wgpu_backend` and `egui_winit_platform` have been updated to be compatible with egui 0.18, so projects relying on the old libraries may have an easier time migrating from that, at least for the time being (that's what rend3 ended up doing).

**Comment by emilk** [comment]
I'll try do do a 0.19 release next week!

**Comment by emilk** [comment]
0.19.0 has now been released!
