### ISSUE TITLE
Sidepanel expanding on reprint

### ISSUE THREAD

**Issue by zirconium-n** [emilk/egui#1813]
**Describe the bug**
Side panel with certain layout and separator results it expand on every reprint.

**To Reproduce**
Just run this code.
```
fn main() {
    eframe::run_native("bad", Default::default(), Box::new(|_| Box::new(Main)));
}

struct Main;

impl eframe::App for Main {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::SidePanel::right("").show(ctx, |ui| {
            ui.horizontal(|ui| {
                ui.vertical(|ui| {
                    ui.separator();
                });
                ui.vertical(|ui| {
                    ui.separator();
                });
            })
        });
    }
}
```

**Expected behavior**
Nothing resizes.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Native

Cargo.toml :
```
[dependencies]
eframe = "0.18.0"
egui = "0.18.1"
```

**Comment by zirconium-n** [comment]
The first `ui.separator();` call allocated all available horizontal space. Then any following call in `ui.horizontal(...)` would result requesting a larger space than the current. This loop indefinitely so the side panel keep expanding. Essentially, the code is equivalent to the following code
```rust
        egui::SidePanel::right("").show(ctx, |ui| {
            let mut s = ui.available_size();
            s.x += 8.;
            ui.allocate_space(s);
        });
```

You can replace the `separator` with a really long label, the result would be same (until the label is not long enough the fill the whole region ofc).

```rust
        // This keeps expanding the layout too!
        // Why is the layout expanding each frame until it's fit but not done in 1 frame directly?
        egui::SidePanel::right("").show(ctx, |ui| {
            ui.horizontal(|ui| {
                ui.vertical(|ui| {
                    ui.label("11111111111111111111111111111111111111111111111111");
                });
                ui.label("aaa");
            });
        });
```

The label case might be easier, but I wonder what could be done in the `separator` case.

**Comment by emilk** [comment]
Ah, I see. Well if you first use up all available space and then ask for _more_, well then the parent will _have_ to expand to satisfy your ask. I don't see what else you would expect to happen.

The solution is to only use the available space, and not more.

**Comment by zirconium-n** [comment]
> Ah, I see. Well if you first use up all available space and then ask for _more_, well then the parent will _have_ to expand to satisfy your ask. I don't see what else you would expect to happen.
> 
> The solution is to only use the available space, and not more.

I kind of expected the separator not asking for all space, since it's not the separator taking space, it's the other contents. To achieve this, I believe it needs to remember last frame's size and use that (and create a 1 frame lag), or use the 2-pass system.
