### ISSUE TITLE
Image nearest neighbour interpolation

### ISSUE THREAD

**Issue by samoylovfp** [emilk/egui#1819]
**Is your feature request related to a problem? Please describe.**

I use egui for numerical data visualization (see https://gitlab.com/samoylovfp/ncexplorer) and would like to be able to switch to a "nearest neighbor" interpolation for `PlotImage` to see boundaries in the values more clearly

**Describe the solution you'd like**

Add a `with_interpolation` function to `PlotImage` structure, allowing selecting the interpolation method

**Describe alternatives you've considered**

The interpolation might also be a parameter to `PlotUi::image`, but this feels less ergonomic, since it shouldn't matter for most users

**Additional context**

**Comment by emilk** [comment]
This is now possible on `master`: https://github.com/emilk/egui/pull/1636
