### ISSUE TITLE
wasm demo performance isn't as 60 as it claims

### ISSUE THREAD

**Issue by adsick** [emilk/egui#182]
Love egui, but https://emilk.github.io/egui/index.html actually runs with 40-50 fps when one window is opened, and it drops down to 25 fps when i open all the windows.

hardware: i5-3330 8g ram, amd Radeon R9-280x
software: Fedora 33 Firefox 85.

**Comment by emilk** [comment]
Yeah, Firefox does not implement WebGL very well. Out of my control unfortunately: https://twitter.com/fedor_games/status/1342838418343141381 https://t.co/UlnjSlw91Q?amp=1

**Comment by lancecarlson** [comment]
@emilk Sorry to bring this issue back from the grave, but I also noticed some performance issues on Chrome on my MacOS laptop (Firefox is worse). I compiled the demo on my local machine to see if there were improvements, and there were, but there is still a tiny noticeable lag (on the hover effect) and CPU bounces to 50% on a regular basis. If I unfocus the window and let it relax, the CPU goes all the way down to 0 again. I tried to compile in release mode to see if it helped. I think that dragged the CPU down to around 10%, but hover my mouse over things in the demo is still delayed.

Any idea what be the issue?

**Comment by emilk** [comment]
Try running the in-browser profiler and see if you can spot something. Certainly you should compile in release.

I know there is room for improvement in the painter - you can try using the glow painter instead, it is reportedly much faster than the WebGL based painter: https://github.com/emilk/egui/pull/868#issuecomment-957139142
