### ISSUE TITLE
Show/Hide main window

### ISSUE THREAD

**Issue by flukejones** [emilk/egui#1821]
I'm trying to rewrite an app from slint to egui, but one of the requirements for me is to allow the app to run as a background process without the GUI running.

From what I can see I need access to the Window Context to use [`set_visible`](https://docs.rs/glutin/latest/glutin/window/struct.Window.html#method.set_visible) in glutin.

I'm still new to egui, so perhaps there is another way?

**Comment by rdrpenguin04** [comment]
Duplicate of #1800
