### ISSUE TITLE
thread 'main' panicked at 'ERROR: 0:18: 'gl_VertexId' : undeclared identifier 

### ISSUE THREAD

**Issue by DLM8207** [emilk/egui#1823]
**when I runned custom 3d glow example,the program reported a error: thread 'main' panicked at 'ERROR: 0:18: 'gl_VertexId' : undeclared identifier **

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser 
 - Version

**Comment by emilk** [comment]
Try experimenting with the `shader_version`
