### ISSUE TITLE
Hanging application when opening some ewebsock connections

### ISSUE THREAD

**Issue by Kerollmops** [emilk/egui#1832]
Hi,

My egui application completly hang sometimes, it looks like it is related to _cloning/requesting a repaint_ from the `Context`.
My project can be found on [this repository at this exact commit](https://github.com/Kerollmops/riemann-egui-dash/tree/5b33b240923e1dc764584e4a0ac1f9bce05b37f1), it looks like it happens only when multiple ewebsock are opened at the same time.

Here is a backtrace of all threads and we can see that it hang when a `request_repaint` was called (`Context::write`).
[Hanging riemann-egui-dash.txt](https://github.com/emilk/egui/files/9124067/Hanging.riemann-egui-dash.txt)

**Comment by emilk** [comment]
Probably a double-locking of a mutex in `Context`. 

Try running in `debug` (it catches some problems), or use the new `deadlock_detection` feature (https://github.com/emilk/egui/pull/1619) or try https://github.com/emilk/egui/pull/1732
