### ISSUE TITLE
First element of the list of elements, takes up entire window height, when using RTL or LTR layout methods

### ISSUE THREAD

**Issue by gouravkhator** [emilk/egui#1836]
## Issue

I faced one layout issue while rendering the list of elements. 

### Issue Description with Code Snippet

I have created a dummy app [here](https://github.com/gouravkhator/rusty-users/blob/main/src/render_ui.rs), in which the hyperlink needs to be rendered with `right_to_left` layout. 

If I don't use the `with_cross_align()` method, then as checked in below screenshot, the first element in the list takes up entire window size.

**Code Snippet:**

```rust
ui.with_layout(
    Layout::right_to_left(),
    |ui| {
        ui.add(egui::Hyperlink::from_label_and_url(
            "See User's Profile",
            format!("http://example.com/u/{}", user.id),
        ));
    },
);
```

**Issue Screenshot**

![Issue_screenshot](https://user-images.githubusercontent.com/36273363/179375146-9c04f369-1667-418a-877d-0c9bd8157732.png)

### Workaround to be performed by every developers

We can fix the above using the `with_cross_align` method and passing the `Align::LEFT` in the params. But this is just a workaround, and not the actual fix.

The code snippet for that dummy app, along with the fix is also mentioned [here](https://github.com/gouravkhator/rusty-users/blob/1802ba52b724095edf4f82afd58630602d99ff51/src/render_ui.rs#L41).

**Code Snippet**:

```rust
ui.with_layout(
    Layout::right_to_left().with_cross_align(Align::LEFT),
    |ui| {
        ui.add(egui::Hyperlink::from_label_and_url(
            "See User's Profile",
            format!("http://example.com/u/{}", user.id),
        ));
    },
);
```

**Screenshot**

![Fixed_Issue_Screenshot](https://user-images.githubusercontent.com/36273363/179375154-3b796ac8-f006-407e-855c-711226bdbf61.png)

> Note: I have submitted PR [#1837](https://github.com/emilk/egui/pull/1837) for the actual fix. I would like the creator of this awesome library, to look into that and help merge the fix asap.

**Comment by emilk** [comment]
The reason for this behavior is twofold:

* [`with_layout` uses up all available space](https://docs.rs/egui/latest/egui/struct.Ui.html#method.with_layout)
* horizontal layouts centers vertically (as you noted)

Both these are the intended behavior. If you don't want to use up all the available space, use [`allocate_ui_with_layout`](https://docs.rs/egui/latest/egui/struct.Ui.html#method.allocate_ui_with_layout).
If you don't want vertical centering, use `.cross_align(Align::MIN)`.

The documentation for `Layout` is really bad though; I might take some time to improve that.

**Comment by gouravkhator** [comment]
Thank you @emilk for the update. I really faced issues with reading the documentation but a great work by the way.

Would follow your advice.. Amd would mostly refer the source code to get updated features, instead of relying on docs.

Even I am unable to update my projects' docs, due to time constraint..
