### ISSUE TITLE
expose force_set_min_rect to enable custom UI with expanding animation and smooth widget reveal

### ISSUE THREAD

**Issue by Madoshakalaka** [emilk/egui#1841]
**Is your feature request related to a problem? Please describe.**

I was designing a dual-purpose login-register form and found out there's no way to achieve a smooth animation. I looked into the code for collapsing headers, it turns out the only way is by `force_set_min_rect` in `ui.rs` which has `pub(crate)` visibility.

This is the wanted effect with a forked egui:

![feature-request](https://user-images.githubusercontent.com/44753941/180098556-dbe97265-5d57-4856-85c3-de40ff8f7bb8.gif)

**Describe the solution you'd like**

publicizing the `force_set_min_rect` methods both in  `painter.rs` and `ui.rs` by remove the `(crate)` visibility. It's the only thing that stops custom UIs with an expanding behavior and a smooth widget reveal.

**Describe alternatives you've considered**
I've tried rendering the widgets as long as there's space. But it looks very choppy as widgets appear abruptly.

**Comment by emilk** [comment]
Have you tried using https://docs.rs/egui/latest/egui/containers/collapsing_header/struct.CollapsingState.html#method.show_body_unindented for this?

**Comment by Madoshakalaka** [comment]
Thanks! Just tried playing with `CollapsingState`, and it works!

Updated the UI a bit, now it shrinks back too:
![smooth](https://user-images.githubusercontent.com/44753941/180286278-ceb7daf2-cfc1-452d-82cf-60e09691b123.gif)

It might be the best for this case though

1. The custom header (which in this case mutates itself from a row of buttons to a label row)
2. The closing button in this case sits inside the body, which makes it awkward to use the button to control the animation.

here's the code:

```rust
// the custom "header"
ui.horizontal(|ui| {
    if collapsing_state.is_open() {
        ui.label("confirm password");
    } else {
        ui.checkbox(&mut client_config.remember, "remember me");

        if ui.button("Create account").clicked() {
            collapsing_state.set_open(true);
        }

        ui.button("Login");
    }
});

if let Some(true) = collapsing_state
    .show_body_unindented(ui, |ui| {
        ui.text_edit_singleline(&mut String::from(""));
        ui.horizontal(|ui| ui.label("please fill all fields"));
        ui.horizontal(|ui| {
            let b = ui.button("back");
            ui.button("confirm");
            b
        })
        .inner
    })
    .map(|i| i.inner.clicked())
{
    collapsing_state.set_open(false);
    collapsing_state.store(ui.ctx());
};
```

**Comment by Madoshakalaka** [comment]
In the code above, I had to add the `collapsing_state.store()` for the `set_open(false)` otherwise the form won't close. But I don't have to add `.store` for the `set_open(true)` call. Do you know what's happening here? I'm using bevy_egui if that's relevant.
