### ISSUE TITLE
ComboBox layout issue

### ISSUE THREAD

**Issue by andreakarasho** [emilk/egui#1848]
ComboBox doesn't respect the parent layout:

```rust
ui.vertical_centered(|ui| {    
    egui::ComboBox::from_label("Take your pick")
        .selected_text(format!("{:?}", self.radio))
        .show_ui(ui, |ui| {
            ui.selectable_value(&mut self.radio, Enum::First, "First");
            ui.selectable_value(&mut self.radio, Enum::Second, "Second");
            ui.selectable_value(&mut self.radio, Enum::Third, "Third");
        });
});
```

![image](https://user-images.githubusercontent.com/20810422/180649710-37aac03c-0545-4d8e-8b97-2650fcc7a858.png)

**Comment by emilk** [comment]
This is intentional. You can always put your own label wherever you want it

**Comment by andreakarasho** [comment]
The problem is about the whole widget which i'd like to put in a specific layout. 
Am I missing anything?

**Comment by emilk** [comment]
Oh I see, my mistake.

Yeah, only atomic widgets can successfully be put into layouts. It's a similar problem for sliders. This cannot be solved until https://github.com/emilk/egui/issues/843
