### ISSUE TITLE
Can't resize a widget without changing the defaults (?)

### ISSUE THREAD

**Issue by Shika-B** [emilk/egui#1850]
**Is your feature request related to a problem? Please describe.**
I'm not sure if I just can't read the doc (spent 2 hours googling and reading the source code, so I hope it's not just that) but there seems to be no way to change a `Slider`'s width without changing the default size of all sliders. 

**Describe the solution you'd like**
I'm new to egui so I don't know if there is already existing structures to manage size of individual widgets. If it's the case, then implement a way to use them with the `Slider` widget. If not, then probably start by discussing how a solution should look like. In both cases, I'd be happy to implement one.

**Comment by emilk** [comment]
egui is a bit inconsistent here, unfortunately. A lot of widgets can be sized by using `ui.add_sized`, but that does not include sliders.

But changing the default doesn't necessarily mean changing it for everyone. You can scope all changes using [`ui.scope`](https://docs.rs/egui/latest/egui/struct.Ui.html#method.scope):

``` rust
ui.scope(|ui| {
    ui.spacing_mut().slider_width = 200.0; // Temporary change
    ui.add(Slider::new(…));
});
```

**Comment by Shika-B** [comment]
Alright thanks a lot !
