### ISSUE TITLE
Fuzzy (font) rendering on Firefox / X11

### ISSUE THREAD

**Issue by gcp** [emilk/egui#1863]
When browsing the demos on egui.rs, the font rendering is extremely fuzzy and text is hard to read.

**To Reproduce**
Browse to
https://www.egui.rs
using Firefox (Nightly) on Linux, using X11, Ubuntu 21.10

**Expected behavior**
Text should be readable. It's much better in Chromium.

**Screenshots**
![egui_fuzzy](https://user-images.githubusercontent.com/1104290/181571814-5b13d240-67d8-48ad-b5c9-2d0d84d6b0c9.png)

![Screenshot 2022-07-28 at 17-03-50 egui – An immediate mode GUI written in Rust](https://user-images.githubusercontent.com/1104290/181571866-069d1922-f170-4709-a3e4-e80bff1b076c.png)

**Comment by emilk** [comment]
This should be fixed now!
