### ISSUE TITLE
color_edit_button_rgb results are not correct

### ISSUE THREAD

**Issue by borgmanJeremy** [emilk/egui#1868]
- [x] I confirmed this issue is present on the master branch

**Describe the bug**
when using color_edit_button_rgb to select a color, the values that are reflected in the [f32;3] are not correct. See in the gif the values in the label do not match the rgb numbers in the widget. 

![rgb](https://user-images.githubusercontent.com/46930769/181790884-602025fe-8a49-4b01-ab34-20aafb9863fb.gif)

**To Reproduce**
Here is a minimal working example illustrating the bug
```
use eframe::egui;

pub struct MyApp{
    color: [f32;3],
}

impl Default for MyApp{
    fn default() -> Self{
        Self{
            color: [0.0,0.0,0.0],
        }
    }
}

impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, frame: &mut eframe::Frame) {
        ctx.request_repaint();

        egui::CentralPanel::default().show(ctx, |ui| {
            egui::widgets::color_picker::color_edit_button_rgb(ui, &mut self.color);
            ui.label(format!("Color: ({}, {}, {})", self.color[0], self.color[1], self.color[2]));
            ui.label(format!("Color: ({}, {}, {})", (self.color[0]*255.0) as u8, (self.color[1]*255.0) as u8, (self.color[2]*255.0) as u8));

        });

    }

}

fn main() {
    let mut app = MyApp::default();
    eframe::run_native("test", eframe::NativeOptions::default(), Box::new(|_cc| Box::new(app)));
}

```

**Expected behavior**
I would expect the u8 I calculate by multiplying the f32 by 255 to match the value in the color picker. 

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by emilk** [comment]
That's because the sRGBA gamma curve is non-linear. See the documentation for `Color32` and `Rgba`, or perhaps https://en.wikipedia.org/wiki/SRGB
