### ISSUE TITLE
egui_extras::Table causes frame lag when populating with large amounts of data

### ISSUE THREAD

**Issue by temportalflux** [emilk/egui#1874]
**Describe the bug**
When creating large amounts of rows with the `egui_extras::Table` API/widget, the application has a noticeable frame-delay. I suspect this is caused by [`egui_extras::Table::body()`](https://github.com/emilk/egui/blob/master/egui_extras/src/table.rs#L304) using `ScrollArea::show` (no access to swap behavior to `show_rows`).

**To Reproduce**
1. Create a table using the `egui_extras::TableBuilder` API, creating a header row, and calling the `egui_extras::Table::body()` function.
2. Populate table with a large number of rows (an amount akin to the examples in the egui demo when showing off `show_rows`).
4. Notice substantial frame lag when scrolling or using the application.

**Expected behavior**
Users are able to use the `Table` api with large amounts of data.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 0.18

**Comment by SteveCookTU** [comment]
Have also recently come across this issue. How many headers are you using as well?

The demo only uses 3 headers and is able to load fine with 10,000 rows. I have 16 headers and 10,000 rows is unable to run at a decent framerate.

**Comment by temportalflux** [comment]
The header row of the table that is causing frame lag is only 3 columns, but has a large number of rows. I haven't strictly profiled it, so it's possible some of the load is my code. Im certain that being able to fix this though will go a long way.

**Comment by SteveCookTU** [comment]
I refactored everything in mine to prevent any allocation during the rendering and was still getting the FPS issue.

Are you using `body.row` or `body.rows`? I think I just removed the issue by switching from `row` to `rows`. I now have 40,000 rows with no lag.

**Comment by SteveCookTU** [comment]
I have all my results stored in a `Vec` and instead of iterating through the vector and adding a single row per entry, I passed in the length as the row count and instead am retrieving from the vector based on the index.

My guess is that by using `rows`, it allocated all the rows and causes no issue. By adding a row for every result, it allocates a new row every time causing the framerate drop.

**Comment by temportalflux** [comment]
Ah I'm using the `table.body` + `table.row` API following examples in the docs. I'll look into what the `rows` function entails later and try that!

**Comment by temportalflux** [comment]
Closing this. I did some profiling today and the `rows` function definitely helped, it took me down from 9ms per table body to 1ms. It also revealed that the frame lag is being caused by wgpu functions taking 30+ms per frame, so not an issue of this library,
