### ISSUE TITLE
Widgets are not wrapped inside of egui_extras' Strips

### ISSUE THREAD

**Issue by Gohla** [emilk/egui#1875]
**Describe the bug**
Widgets (in my case, `CollapsingHeader`s) are not wrapped with layout `Layout::left_to_right().with_main_wrap(true)`. Instead, they are just layed out left-to-right, never wrap, and are clipped outside of their `Strip` (see screenshot below).

Code for the layout of the screenshot:
```Rust
CentralPanel::default()
  .show(ctx, |ui| {
    ui.add_enabled_ui(self.enable_gui, |ui| {
      let layout = Layout::left_to_right().with_main_wrap(true);
      StripBuilder::new(ui)
        .cell_layout(layout)
        .size(Size::remainder())
        .size(Size::exact(1.0))
        .size(Size::remainder())
        .horizontal(|mut strip| {
          strip.cell(|ui| {
            ScrollArea::vertical()
              .id_source("Calculator Scroll")
              .auto_shrink([false; 2])
              .show(ui, |ui| {
                if self.show_calculator(ui) {
                  self.calculate();
                }
              });
          });
          strip.cell(|ui| {
            ui.add(Separator::default().spacing(0.0).vertical());
          });
          strip.cell(|ui| {
            ScrollArea::vertical()
              .id_source("Result Scroll")
              .auto_shrink([false; 2])
              .show(ui, |ui| {
                self.show_results(ui, ctx);
              });
          });
        });
    });
  });
```

I've tried out several things such as compiling against the `master` branch of egui, removing the `ScrollArea`s and `ui.add_enabled_ui`, as well as applying the layout with `ui.with_layout` instead of passing it to `StripBuilder`.

**To Reproduce**
Full [source code can be found here](https://github.com/Gohla/space_engineers_calc/tree/left-to-right-wrap). Be sure to check out the `left-to-right-wrap` branch.

Run with `cargo run --bin secalc_gui_egui`.

Then observe that the widgets are not wrapped.

**Expected behavior**
The widgets to be layed out left-to-right as much as possible until they would overflow, and then to wrap to the next row. I think this should be possible (in immediate-mode GUI) because the `Strip` sizes its cells.

**Screenshots**
![Screenshot 2022-07-31 14 04 22](https://user-images.githubusercontent.com/368427/182025547-7be0553d-1319-46a1-a890-9ed04c903e0e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by emilk** [comment]
So it seems like `Layout` isn't respecting the `max_size` of the `Ui` made inside a `Strip` for whatever reason.

It would be useful with a minimal reproduce!

**Comment by Gohla** [comment]
It's not just limited to `Strip`s, I can also reproduce it with just a `CentralPanel`. I think it might have to do with `CollapsingHeader`, since I can't reproduce it with `Button` for example.

Here's a minimal reproduction with just `CentralPanel`:

```Rust
CentralPanel::default().show(ctx, |ui| {
  ui.with_layout(Layout::left_to_right().with_main_wrap(true), |ui| {
    CollapsingHeader::new("Test Test Test Test Test").default_open(true).show(ui, |ui| {
      for i in 0..3 { ui.label(format!("Test {}", i)); }
    });
    CollapsingHeader::new("Test Test Test Test Test Test Test Test Test Test").default_open(true).show(ui, |ui| {
      for i in 3..9 { ui.label(format!("Test {}", i)); }
    });
  });
});
```

And with `Strip`:
```Rust
CentralPanel::default().show(ctx, |ui| {
  StripBuilder::new(ui)
    .cell_layout(Layout::left_to_right().with_main_wrap(true))
    .size(Size::remainder())
    .horizontal(|mut strip| {
      strip.cell(|ui| {
        CollapsingHeader::new("Test Test Test Test Test").default_open(true).show(ui, |ui| {
          for i in 0..3 { ui.label(format!("Test {}", i)); }
        });
        CollapsingHeader::new("Test Test Test Test Test Test Test Test Test Test").default_open(true).show(ui, |ui| {
          for i in 3..9 { ui.label(format!("Test {}", i)); }
        });
      });
    });
});
```

But with `Button`, it works as expected:
```Rust
CentralPanel::default().show(ctx, |ui| {
  ui.with_layout(Layout::left_to_right().with_main_wrap(true).with_cross_align(Align::TOP), |ui| {
    for i in 0..50 { ui.button(format!("Test {}", i)); }
  });
});
```

Here's a repo with the code in an eframe app: https://github.com/Gohla/egui_strip_wrapping

**Comment by emilk** [comment]
Ah, I actually see the problem now - you need to put the layout _innermost_, for instance:

```
    CollapsingHeader::new("Test Test Test Test Test Test Test Test Test Test").default_open(true).show(ui, |ui| {
        ui.with_layout(Layout::left_to_right().with_main_wrap(true), |ui| {
            for i in 3..9 { ui.label(format!("Test {}", i)); }
        });
    });
```

**Comment by Gohla** [comment]
That doesn't achieve what I'd want, but my expectations are kind of vague so I will try to make them clearer with some screenshots.

I'd like to lay out multiple `CollapsingHeader`s from left-to-right, like so:

![Screenshot 2022-08-01 17 58 45](https://user-images.githubusercontent.com/368427/182190858-e2427fdf-7d60-440e-a197-1d87023f650e.png)

But when the window width is resized such that the two `CollapsingHeader`s don't fit any more width-wise, I'd like them to wrap to the next row like so:

![Screenshot 2022-08-01 17 59 10](https://user-images.githubusercontent.com/368427/182191002-1c9bbb21-1dbc-4ebb-9587-d4630abe8fcc.png)

However, what currently happens is that they get clipped:

![Screenshot 2022-08-01 17 58 53](https://user-images.githubusercontent.com/368427/182191055-7ea4eccd-3fc8-4190-ae15-19a4c0a1d21b.png)

My expectation is that `Layout::left_to_right().with_main_wrap(true)` should do this, but it only seems to do this with simpler widgets such as `Label` and `Button`, but not `CollapsingHeader`. Is that a bug or a limitation, or can this be achieved some other way?

Code for the screenshots above:

```Rust
CentralPanel::default().show(ctx, |ui| {
  ui.with_layout(Layout::left_to_right().with_main_wrap(true).with_cross_align(Align::TOP), |ui| {
    CollapsingHeader::new("Test Test Test Test Test").default_open(true).show(ui, |ui| {
      Grid::new("Grid 1").striped(true).show(ui, |ui| {
        for r in 0..3 {
          for c in 0..3 {
            ui.label(format!("Cell-{}-{}", r, c));
          }
          ui.end_row();
        }
      });
    });
    CollapsingHeader::new("Test Test Test Test Test Test Test Test Test Test").default_open(true).show(ui, |ui| {
      Grid::new("Grid 2").striped(true).show(ui, |ui| {
        for r in 0..5 {
          for c in 0..5 {
            ui.label(format!("Cell-{}-{}", r, c));
          }
          ui.end_row();
        }
      });
    });
  });
});
```

**Comment by emilk** [comment]
This is a limitation of immediate mode - only "atomic" widgets (buttons, labels, etc) can be part of advanced layouts such as this. The problem is that the layout cannot know how large a wrapped UI (e.g. a `CollapsingHeader`) is going to become.

Would be solved by https://github.com/emilk/egui/issues/843

**Comment by Gohla** [comment]
I see, that is unfortunate but makes sense, thanks for the help!
