### ISSUE TITLE
JSX (React like) syntax for building egui components/screen

### ISSUE THREAD

**Issue by akhilshastri** [emilk/egui#1879]
egui is awesome but the web-developer like me, rust it self a huge learning, if i get some familiar syntax like JSX ( React usages for building component tree)  would be huge win.
i found few initiative [jsx-rs](https://github.com/camjackson/jsx-rs) which tries to parse JSX to rust but seems limited.

**Comment by emilk** [comment]
I feel this is outside the scope of `egui`. It seems more suitable for a separate project that perhaps _uses_ egui.
