### ISSUE TITLE
DragValue: make from_get_set public

### ISSUE THREAD

**Issue by g-braeunlich** [emilk/egui#188]
Could you make `from_get_set public` (https://github.com/emilk/egui/blob/master/egui/src/widgets/drag_value.rs#L55)
public? I saw, that for Slider (https://github.com/emilk/egui/blob/master/egui/src/widgets/slider.rs#L76) it is already public.

**Comment by emilk** [comment]
Sure! I'm curious: what will you use it for?

**Comment by g-braeunlich** [comment]
I want to make a field for a `usize`.
In the meantime, I found that this also would be possible using something like:
```
let mut x = usize_var as f64;
ui.add(DragValue::f64(&mut x));
usize_var = x as usize;
```

**Comment by emilk** [comment]
Then this will make you even more happy: https://github.com/emilk/egui/commit/814f8c0dd8414ba7e1736430866c131e30256711

**Comment by g-braeunlich** [comment]
:tada: Even before this feature: a big :+1: for egui!!
