### ISSUE TITLE
`Response::context_menu()` and `Response::interact()` don't work with labels as documented

### ISSUE THREAD

**Issue by rib** [emilk/egui#1882]
**Describe the bug**

The egui docs [here](https://docs.rs/egui/latest/egui/struct.Response.html#method.context_menu) currently suggest that a context menu can be added to a label like this (quoted code from docs):
```rust
let response = ui.label("Right-click me!");
response.context_menu(|ui| {
    if ui.button("Close the menu").clicked() {
        ui.close_menu();
    }
});
```

but trying this I found I didn't get a pop-up menu when right clicking.

I guessed this might be related to the label not handling input by default and since I saw the [`Response::interact`](https://docs.rs/egui/latest/egui/struct.Response.html#method.interact) API could be used to explicitly enable input handling for a widget I gave that a try.

Notably, this is the example in the docs for the `interact` API, that shows how to use it with a label:
```rust
let response = ui.label("hello");
assert!(!response.clicked()); // labels don't sense clicks by default
let response = response.interact(egui::Sense::click());
if response.clicked() { /* … */ }
```

but following that also didn't get the context menu to work (clicking didn't work either).

Based on the suggestion in the `interact()` docs to use the widget's `sense()` API to get mouse-over highlighting I then tried:

```rust
let label = egui::Label::new("Right-click-me").sense(egui::Sense::click());
ui.add(label).context_menu(|ui| {
    ui.label("foo");
});
```

which did work.

**Expected behavior**

Either the two examples should probably be updated, or the two methods should be updated to match the documentation.

I'm not exactly sure whether this should be considered an issue with the docs or with the [`Response::context_menu`](https://docs.rs/egui/latest/egui/struct.Response.html#method.context_menu) and [`Response::interact`](https://docs.rs/egui/latest/egui/struct.Response.html#method.interact) APIs.

In the end (for my use case) I think I prefer having the highlighting behaviour from using the `Label::sense` API so I'm happy enough with the final solution but it took quite a bit of time to get to that when these two examples led me down the wrong path.

***Version***
This was tested with git master, on Windows 10, using `egui-winit` and `egui-wgpu`

**Comment by emilk** [comment]
Good catch - the docs are wrong here.
