### ISSUE TITLE
DragValue with hexadecimal values

### ISSUE THREAD

**Issue by damageboy** [emilk/egui#1888]
Currently, the `DragValue`  is mostly geared for decimal values, and provide a store of knobs and features around precision etc.

I'm personally interested in having a hexadecimal drag-value allowing, presentation dragging and editing in hex values.

Is this something you feel is reasonable for:
* egui?
* the current DragValue widget through adding formatting/validation capabilities
* A new HexDragValue widget that is special purposed for this scenario

**Comment by emilk** [comment]
This was recently implemented in https://github.com/emilk/egui/pull/1851 !
