### ISSUE TITLE
eframe window visiblity on Wayland is transparent if false

### ISSUE THREAD

**Issue by flukejones** [emilk/egui#1894]
I use the functionality added by https://github.com/emilk/egui/pull/1808. It works well on X11 but on wayland the window is shown as a transparent square.

Due to this I think I may begin using https://github.com/emilk/egui/pull/1889

**Comment by emilk** [comment]
Have you tested this behavior with just winit?

**Comment by flukejones** [comment]
@emilk sorry mate, I've got so much going on that I forgot I created this issue over on winit git https://github.com/rust-windowing/winit/issues/2388

It looks like winit needs to add support.

**Comment by emilk** [comment]
Thanks, I'll close this in favor of https://github.com/rust-windowing/winit/issues/2388
