### ISSUE TITLE
wgpu backend

### ISSUE THREAD

**Issue by IceSentry** [emilk/egui#19]
I was trying to create a plugin for https://github.com/bevyengine/bevy and that would require a wgpu backend I think. I'd be interested in working on this, but I have no idea where to start.

**Comment by emilk** [comment]
Hello!

A good place to start is probably to look at how the rendering is done for Glium: https://github.com/emilk/egui/blob/master/egui_glium/src/painter.rs

**Comment by Gonkalbell** [comment]
I just uploaded https://github.com/Gonkalbell/egui_wgpu, which is a pretty lazy port of the glium bindings. I haven't gotten around to uploading the documentation to docs.rs or publishing this to crates.io yet, but maybe you can find it useful.

**Comment by IceSentry** [comment]
Oh cool, thanks, I'll look at it. I kind of stopped working on this.

**Comment by emilk** [comment]
It seems like we have TWO wgpu backends for Egui now:

* https://github.com/hasenbanck/egui_wgpu_backend (https://crates.io/crates/egui_wgpu_backend)
* https://github.com/Gonkalbell/egui_winit_wgpu (unpublished)

So I will consider this issue closed!
