### ISSUE TITLE
documentation for video file + scrubber?

### ISSUE THREAD

**Issue by rustrust** [emilk/egui#1905]
I would like to be able to play back common video file formats (such as mpeg4 and preferably also av1) with a scrubber. Would it be possible to get a widget for this and some documentation? Thanks!

**Comment by Ryder17z** [comment]
hopefully it could make use of ffmpeg

**Comment by emilk** [comment]
A video player is outside the scope of `egui`, but it should be possible to make an egui library that implements it.

**Comment by n00kii** [comment]
In case you're still interested I made a video player library with ffmpeg 5 here[here](https://github.com/n00kii/egui-video)

**Comment by Ryder17z** [comment]
> In case you're still interested I made a video player library with ffmpeg 5 [here](https://github.com/n00kii/egui-video)

Very nice
