### ISSUE TITLE
[QUESTION] How to transfer information from one window to another?

### ISSUE THREAD

**Issue by Jerrody** [emilk/egui#1911]
I mean how do copy all of the content of the window and pass it to the window?
Labels, sliders and so on.

**Comment by emilk** [comment]
Please use https://github.com/emilk/egui/discussions to ask questions.

If you want to have identical contents of two windows, just call the same ui layout code. There is no way to "copy" a widget tree, because there is no widget tree. https://docs.rs/egui/latest/egui/#understanding-immediate-mode
