### ISSUE TITLE
Cannot cache (reuse) TextShape if pixels_per_point is set to other than 1.0.

### ISSUE THREAD

**Issue by ruimo** [emilk/egui#1915]
In the following example caches the TextShape object. https://github.com/ruimo/egui_text_shape_cache

If you change the following line to false, it can render properly.

    const CACHE_ENABLED: bool = true;

If you comment the following line, it can render properly even if cache is enabled.

    ctx.set_pixels_per_point(1.5);

    OK: Cache=On, pixels per point = 1.0(default)
    OK: Cache=Off, pixels per point != 1.0
    NG: Cache=On, pixels per point != 1.0
    OK: Cache = Off, pixels per point = 1.0(default)

**Comment by emilk** [comment]
Isn't the problem that you cannot cache `TextShape` when _changing_ the `pixels_per_point`?

**Comment by ruimo** [comment]
Sorry, I was not sure this behavior is as designed or not. So, do I need to create TextShapes every frame if I need to change pixels/point?

**Comment by emilk** [comment]
yeah, the idea is that you create new `Shape`:s every frame. The text layout is actually cached by `egui` though, so it shouldn't be very expensive.

**Comment by emilk** [comment]
That being said, it would be good if `TextShape` at least warned (during tessellation) if the `pixels_per_point` had changed.

**Comment by ruimo** [comment]
Agreed, it should be really helpful to detect wrong code. Should I close this thread? Or leave it for future reminder?
