### ISSUE TITLE
Online Demo "Painting" source code should include color picker, but it's missing (in demo source code, not the live demo)

### ISSUE THREAD

**Issue by Ryder17z** [emilk/egui#1928]
Go to https://www.egui.rs/#demo and activate "Painting window", click to view source and the color picker is nowhere to be found. (in source file)

**Comment by emilk** [comment]
I see it:

![Screen Shot 2022-08-18 at 09 40 30](https://user-images.githubusercontent.com/1148717/185338195-583ba748-7f41-442f-8fa4-0963e72a2e68.png)

Does it come back on a hard refresh?

egui stores Area positions, and perhaps your color picker is off-screen. We should probably fix that by e.g. clamping areas to the screen (which I thought we already did?) or by not storing positions for popups like color pickers.

**Comment by Ryder17z** [comment]
I'm not sure how your misreading this. CLICK "source code".

**Comment by emilk** [comment]
haha, I don't know how I misread it either 😆 

A new demo with a correct link will be published when I publish egui 0.19, which is hopefully today or tomorrow. I'll close this until then so I don't forget to do so later.

**Comment by Ryder17z** [comment]
@emilk i hope you didn't forget about this because i don't see it fixed.
