### ISSUE TITLE
Custom user textures for egui_glium

### ISSUE THREAD

**Issue by SparkyPotato** [emilk/egui#194]
Currently, egui_glium supports uploading custom user textures from the CPU side. However, if the user is doing any sort of OpenGL rendering on their own (like a viewport in a scene editor), there is no way to pass on the `glium` textures to the `Painter`.
Currently, the only way is to readback the texture onto the CPU, and then reload it every frame, which is terrible for performance.

What could be done is allowing the user to add an `SrgbTexture2d` to the `Painter`, and then get a reference to it. They can then use the reference to render to.

**Comment by emilk** [comment]
Sounds like a good idea! Feel free to open a PR for it

**Comment by t18b219k** [comment]
some backends support this feature e.g. egui_wgpu_backend , egui_ash_vk_mem

**Comment by t18b219k** [comment]
I wrote function and I'm writing sample

**Comment by SparkyPotato** [comment]
A simple way to make it work for the glium backend would be to just make the vector of textures public.

**Comment by t18b219k** [comment]
create rental function ?

**Comment by t18b219k** [comment]
I wrote sample and test it but rendered image was flipped

**Comment by t18b219k** [comment]
ok i fixed image flipping problem so i'm entering refining

**Comment by t18b219k** [comment]
ok i will make PR

**Comment by t18b219k** [comment]
#199 is that i implemented this issue

**Comment by emilk** [comment]
Closed by https://github.com/emilk/egui/pull/226
