### ISSUE TITLE
An error occurred during loading: RuntimeError: unreachable executed 

### ISSUE THREAD

**Issue by zohnannor** [emilk/egui#1944]
**To Reproduce**
1. Go to [egui.rs](https://www.egui.rs/)

**Screenshots**

<details>
<summary>Chrome</summary>

![image](https://user-images.githubusercontent.com/35764628/185755886-4f9bab33-92e8-491c-9488-2c1a3fcf32b1.png)

</details>

<details>
<summary>Firefox</summary>

![image](https://user-images.githubusercontent.com/35764628/185755891-d1816b17-0aec-4eb4-b64e-3d6dfc21ed5e.png)

</details>

**Desktop (please complete the following information):**
 - OS: `Windows 10`
 - Browsers: `Chrome 104.0.5112.102 (Official Build) (64-bit)`, `Firefox 103.0.2 (64-bit)`

**Additional context**

<details>
<summary>Chrome DevTools log</summary>

	  DEBUG crates/eframe/src/web/glow_wrapping.rs:127 WebGL1 selected.
	  egui_demo_app.js:425 DEBUG crates/egui_glow/src/shader_version.rs:20 Shader version: Es100 ("WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)").
	  egui_demo_app.js:425 DEBUG crates/egui_glow/src/painter.rs:118 Shader header: "#version 100\n".
	  egui_demo_app.js:425 DEBUG crates/egui_glow/src/painter.rs:126 WebGL with sRGB enabled. Turning on post processing for linear framebuffer blending.
	  egui_demo_app.js:425 DEBUG crates/egui_glow/src/vao.rs:116 GL version: "WebGL 1.0 (OpenGL ES 2.0 Chromium)".
	  egui_demo_app.js:425 DEBUG crates/egui_glow/src/vao.rs:127 Supported OpenGL extensions: {"WEBGL_color_buffer_float", "EXT_texture_filter_anisotropic", "WEBGL_compressed_texture_s3tc", "WEBGL_debug_shaders", "WEBGL_depth_texture", "OES_vertex_array_object", "WEBGL_draw_buffers", "EXT_sRGB", "ANGLE_instanced_arrays", "EXT_disjoint_timer_query", "WEBGL_lose_context", "WEBGL_multi_draw", "OES_texture_float_linear", "EXT_shader_texture_lod", "EXT_color_buffer_half_float", "OES_fbo_render_mipmap", "OES_standard_derivatives", "WEBGL_debug_renderer_info", "WEBGL_compressed_texture_s3tc_srgb", "EXT_frag_depth", "OES_texture_float", "OES_element_index_uint", "OES_texture_half_float_linear", "EXT_texture_compression_rgtc", "OES_texture_half_float", "EXT_blend_minmax", "KHR_parallel_shader_compile", "EXT_float_blend"}
	  egui_demo_app.js:425 DEBUG crates/egui_glow/src/vao.rs:116 GL version: "WebGL 1.0 (OpenGL ES 2.0 Chromium)".
	  egui_demo_app.js:425 DEBUG crates/egui_glow/src/vao.rs:127 Supported OpenGL extensions: {"WEBGL_color_buffer_float", "EXT_texture_filter_anisotropic", "WEBGL_compressed_texture_s3tc", "WEBGL_debug_shaders", "WEBGL_depth_texture", "OES_vertex_array_object", "WEBGL_draw_buffers", "EXT_sRGB", "ANGLE_instanced_arrays", "EXT_disjoint_timer_query", "WEBGL_lose_context", "WEBGL_multi_draw", "OES_texture_float_linear", "EXT_shader_texture_lod", "EXT_color_buffer_half_float", "OES_fbo_render_mipmap", "OES_standard_derivatives", "WEBGL_debug_renderer_info", "WEBGL_compressed_texture_s3tc_srgb", "EXT_frag_depth", "OES_texture_float", "OES_element_index_uint", "OES_texture_half_float_linear", "EXT_texture_compression_rgtc", "OES_texture_half_float", "EXT_blend_minmax", "KHR_parallel_shader_compile", "EXT_float_blend"}
	  egui_demo_app.js:454 panicked at 'ERROR: unsupported shader version

</details>

<details>
<summary>Firefox DevTools log</summary>

	  loading wasm… [www.egui.rs:127:17](https://www.egui.rs/)
	  wasm loaded. starting app… [www.egui.rs:133:21](https://www.egui.rs/)
	  Failed to create WebGL context: WebGL creation failed: 
	  * tryANGLE (FEATURE_FAILURE_EGL_NO_CONFIG)
	  * Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS) [egui_demo_app.js:1315:37](https://www.egui.rs/egui_demo_app.js)
	  DEBUG crates/eframe/src/web/glow_wrapping.rs:127 WebGL1 selected. [egui_demo_app.js:425:21](https://www.egui.rs/egui_demo_app.js)
	  WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. [egui_demo_app.js:1159:37](https://www.egui.rs/egui_demo_app.js)
	  DEBUG crates/egui_glow/src/shader_version.rs:20 Shader version: Es100 ("WebGL GLSL ES 1.0"). [egui_demo_app.js:425:21](https://www.egui.rs/egui_demo_app.js)
	  DEBUG crates/egui_glow/src/painter.rs:118 Shader header: "#version 100\n". [egui_demo_app.js:425:21](https://www.egui.rs/egui_demo_app.js)
	  DEBUG crates/egui_glow/src/painter.rs:126 WebGL with sRGB enabled. Turning on post processing for linear framebuffer blending. [egui_demo_app.js:425:21](https://www.egui.rs/egui_demo_app.js)
	  DEBUG crates/egui_glow/src/vao.rs:116 GL version: "WebGL 1.0". [egui_demo_app.js:425:21](https://www.egui.rs/egui_demo_app.js)
	  DEBUG crates/egui_glow/src/vao.rs:127 Supported OpenGL extensions: {"WEBGL_debug_shaders", "EXT_texture_filter_anisotropic", "WEBGL_compressed_texture_s3tc", "WEBGL_depth_texture", "OES_vertex_array_object", "WEBGL_draw_buffers", "EXT_sRGB", "ANGLE_instanced_arrays", "WEBGL_lose_context", "OES_texture_float_linear", "EXT_shader_texture_lod", "EXT_color_buffer_half_float", "OES_fbo_render_mipmap", "OES_standard_derivatives", "WEBGL_debug_renderer_info", "WEBGL_compressed_texture_s3tc_srgb", "EXT_frag_depth", "OES_texture_float", "OES_element_index_uint", "OES_texture_half_float_linear", "EXT_texture_compression_rgtc", "OES_texture_half_float", "EXT_blend_minmax", "WEBGL_color_buffer_float", "EXT_float_blend"} [egui_demo_app.js:425:21](https://www.egui.rs/egui_demo_app.js)
	  DEBUG crates/egui_glow/src/vao.rs:116 GL version: "WebGL 1.0". [egui_demo_app.js:425:21](https://www.egui.rs/egui_demo_app.js)
	  DEBUG crates/egui_glow/src/vao.rs:127 Supported OpenGL extensions: {"WEBGL_debug_shaders", "EXT_texture_filter_anisotropic", "WEBGL_compressed_texture_s3tc", "WEBGL_depth_texture", "OES_vertex_array_object", "WEBGL_draw_buffers", "EXT_sRGB", "ANGLE_instanced_arrays", "WEBGL_lose_context", "OES_texture_float_linear", "EXT_shader_texture_lod", "EXT_color_buffer_half_float", "OES_fbo_render_mipmap", "OES_standard_derivatives", "WEBGL_debug_renderer_info", "WEBGL_compressed_texture_s3tc_srgb", "EXT_frag_depth", "OES_texture_float", "OES_element_index_uint", "OES_texture_half_float_linear", "EXT_texture_compression_rgtc", "OES_texture_half_float", "EXT_blend_minmax", "WEBGL_color_buffer_float", "EXT_float_blend"} [egui_demo_app.js:425:21](https://www.egui.rs/egui_demo_app.js)
	  panicked at 'ERROR: unsupported shader version
	  ', crates/egui_demo_app/src/apps/custom3d_glow.rs:140:25
	  
	  Stack:
	  
	  getImports/imports.wbg.__wbg_new_693216e109162396@https://www.egui.rs/egui_demo_app.js:442:21
	  @https://www.egui.rs/egui_demo_app.js line 387 > WebAssembly.instantiate:wasm-function[3274]:0x277c85
	  @https://www.egui.rs/egui_demo_app.js line 387 > WebAssembly.instantiate:wasm-function[1786]:0x1d749b
	  @https://www.egui.rs/egui_demo_app.js line 387 > WebAssembly.instantiate:wasm-function[2590]:0x225562
	  @https://www.egui.rs/egui_demo_app.js line 387 > WebAssembly.instantiate:wasm-function[2423]:0x2110bc
	  @https://www.egui.rs/egui_demo_app.js line 387 > WebAssembly.instantiate:wasm-function[2406]:0x20a002
	  @https://www.egui.rs/egui_demo_app.js line 387 > WebAssembly.instantiate:wasm-function[1908]:0x1e177e
	  __exports.start@https://www.egui.rs/egui_demo_app.js:306:14
	  on_wasm_loaded@https://www.egui.rs/:136:41
	  promise callback*@https://www.egui.rs/:129:14
	  
	  
	  [egui_demo_app.js:454:21](https://www.egui.rs/egui_demo_app.js)
	      __wbg_error_09919627ac0992f5 https://www.egui.rs/egui_demo_app.js:454
	      <anonymous> https://www.egui.rs/egui_demo_app.js line 387 > WebAssembly.instantiate:2587990
	      <anonymous> https://www.egui.rs/egui_demo_app.js line 387 > WebAssembly.instantiate:1930395
	      <anonymous> https://www.egui.rs/egui_demo_app.js line 387 > WebAssembly.instantiate:2250082
	      <anonymous> https://www.egui.rs/egui_demo_app.js line 387 > WebAssembly.instantiate:2166972
	      <anonymous> https://www.egui.rs/egui_demo_app.js line 387 > WebAssembly.instantiate:2138114
	      <anonymous> https://www.egui.rs/egui_demo_app.js line 387 > WebAssembly.instantiate:1972094
	      start https://www.egui.rs/egui_demo_app.js:306
	      on_wasm_loaded https://www.egui.rs/:136
	      (Async: promise callback)
	      <anonymous> https://www.egui.rs/:129
	  Failed to start: RuntimeError: unreachable executed [www.egui.rs:147:21](https://www.egui.rs/)
	      on_wasm_error https://www.egui.rs/:147
	      (Async: promise callback)
	      <anonymous> https://www.egui.rs/:130

</details>

https://github.com/emilk/egui/blob/97ce10320980ea4e8f415b000b322881eb5ec51f/crates/egui_demo_app/src/apps/custom3d_glow.rs#L140

I must also say, I have a very old GPU (`GeForce 9500GT`).

**Comment by zohnannor** [comment]
Works on my phone, `Android 11`, `Crome 104.0.5112.97`, `Firefox 103.2.0`.
I build app locally, same error in the web.

**Comment by emilk** [comment]
Oh it's `custom3d_glow.rs` that is failing. Yeah, the shader there needs special casing for Es100 (WebGL GLSL ES 1.0). It should be a pretty easy fix. Thanks for the report!
