### ISSUE TITLE
How can I compile the android apk for example/hello_world?

### ISSUE THREAD

**Issue by sry948749099** [emilk/egui#1954]
I have tried two methods, first, i used FFI compile hello_world to a shared lib, then used MainActivity in android studio,  but, get a fatal problem.
![111](https://user-images.githubusercontent.com/56307410/185829479-d23c46c1-c338-428d-8db4-6124743447b5.png)

second, I change the method to use `cargo apk build...`, but the apk also cannot run in android devices. I also try to use the NativeActivity method in android studio, but error: 
 
![111](https://user-images.githubusercontent.com/56307410/185867029-f08ced6d-01ac-44a1-a596-dfdd0cff2b68.png)

**Comment by emilk** [comment]
Perhaps @rib or @Zoxc can help out - they have been doing [some recent Android work](https://github.com/emilk/egui/pull/1952).

**Comment by Zoxc** [comment]
I'd try to follow the [eframe example here](https://github.com/rib/android-activity/tree/eframe/examples/agdk-eframe).

**Comment by rib** [comment]
Yeah, mabe you can take a look at some of the Android examples we have here: https://github.com/rib/android-activity/tree/main/examples, including this [agdk-egui](https://github.com/rib/android-activity/tree/main/examples/agdk-egui) example. Those examples each have a README.md with some instructions for how they can be compiled.

We'll hopefully also be adding an eframe based example soon too: https://github.com/rib/android-activity/pull/14

**Comment by sry948749099** [comment]
I met this error:
https://github.com/rib/android-activity/issues/22#issue-1356565284

**Comment by rib** [comment]
> I met this error: [rib/android-activity#22 (comment)](https://github.com/rib/android-activity/issues/22#issue-1356565284)

This should hopefully be fixed by https://github.com/rib/android-activity/pull/23 

Btw @sry948749099 the egui/eframe based example was landed in `main` recently which you might find more convenient: https://github.com/rib/android-activity/tree/main/examples/agdk-eframe

**Comment by inferrna** [comment]
Who need a boilerplate, look at my https://github.com/inferrna/hello_world_android_egui - it compiles and works as just for now.
