### ISSUE TITLE
Can't access egui::Response::has_kb_focus anymore

### ISSUE THREAD

**Issue by 1danielcoelho** [emilk/egui#196]
Since [the change for multiple mouse button support in #135](https://github.com/emilk/egui/commit/247026149cc438b08e7457f2c56e792a51eeaf09#diff-dfc5c2cf1d97ad8b9cf4d70b057258f9e55f9a59df57b746425148a6321a3f12), `egui::Response::has_kb_focus` has `pub(crate)` visibility, but there is no public getter function to retrieve it, so it is now impossible to know if a widget has keyboard focus or not.

Is this intentional or just an oversight?

**Comment by emilk** [comment]
Just an oversight - thanks for noticing!
