### ISSUE TITLE
After upgrade to 0.19: error: failed to run custom build command for `expat-sys v2.1.6`

### ISSUE THREAD

**Issue by lukasz-sawicki** [emilk/egui#1963]
I get build error after updating cargo file to 
eframe = "0.19.0"

error: failed to run custom build command for `expat-sys v2.1.6`

$ cargo tree -i expat-sys
expat-sys v2.1.6
└── servo-fontconfig-sys v5.1.0
    └── servo-fontconfig v0.5.1
        └── crossfont v0.5.0
            └── sctk-adwaita v0.4.2
                └── winit v0.27.2
                    ├── eframe v0.19.0

I am on fedora 36
1. clone the repository
2. cargo build
4. see error..

**Comment by emilk** [comment]
You see the error, but I don't! Anyways, you should bring this up in the `winit` repo instead: https://github.com/rust-windowing/winit/issues
