### ISSUE TITLE
Opening a popup on right-click, but it doesn't show up (closes immediately)

### ISSUE THREAD

**Issue by vilcans** [emilk/egui#198]
**Describe the bug**

The docs for `egui::popup::popup_below_widget` show how to open a popup if the user clicks a widget. But if you want the popup to be displayed when you right-click instead of left-click the widget, the widget will not be visible. The popup closes immediately because a mouse button has been clicked. The code has a special case to make sure that the popup does not close when the user clicks the left mouse button, but that does not work for the right button.

The code that closes the popup directly after it's been opened is at the end of `popup_below_widget`. It checks for any clicks, but only ignores them if they are left-clicks.

```
        if ui.input().key_pressed(Key::Escape)
            || ui.input().pointer.any_click() && !widget_response.clicked()
        {
            ui.memory().close_popup();
        }
```

**To Reproduce**
Copy the code from the docs of `popup_below_widget`, but change `response.clicked()` to `response.secondary_clicked()` as follows:

```
let response = ui.button("Open popup");
let popup_id = ui.make_persistent_id("my_unique_id");
if response.secondary_clicked() {  // changed from response.clicked()
    ui.memory().toggle_popup(popup_id);
}
egui::popup::popup_below_widget(ui, popup_id, &response, |ui| {
    ui.label("Some more info, or things you can select:");
    ui.label("…");
});
```

**Expected behavior**
Right-clicking should open a popup.

**Comment by emilk** [comment]
Thanks for the bug report!
