### ISSUE TITLE
Dark-colored icons on Windows with Dark Theme are very blurry

### ISSUE THREAD

**Issue by njust** [emilk/egui#1989]
Hi, on Windows with Dark Theme, Dark-colored icons are very blurry:

![image](https://user-images.githubusercontent.com/2380253/187632678-804869c8-6ec6-4c70-a200-99c33c3bf089.png)
![image](https://user-images.githubusercontent.com/2380253/187625089-2f7a5da4-16da-47e1-92d2-9690a6f3c40a.png)
![image](https://user-images.githubusercontent.com/2380253/187630676-631216e8-8b20-49e8-8b73-a5d10ba89c42.png)

On Linux, everything is sharp:
![image](https://user-images.githubusercontent.com/2380253/187625848-5edc783e-242c-4c39-a538-f8aa2624a9b9.png)
![image](https://user-images.githubusercontent.com/2380253/187626055-33f3d713-03a3-4a50-81d9-583fbcdaf087.png)

Repository to reproduce
https://github.com/njust/egui_blurry_text

OS: Windows 10 Enterprise
Version: 10.0.19044 Build 19044
Processor: AMD Ryzen 5 1600X Six-Core Processor, 3600 Mhz, 6 Core(s), 12 Logical Processor(s)
Video: AMD Radeon R7 200 Series

**Comment by ciodc** [comment]
![7117BC9E-9AD6-49C6-80FA-BCF3A4C7B81C](https://user-images.githubusercontent.com/83868117/187698586-0486b6b9-b875-4b30-a94f-d6ff763a5a49.jpeg)
 Not exactly same with last one, here is a blurry widget title on Chrome 104.0.5112.99 MacOS

**Comment by TheAwesome98-Real** [comment]
> ![7117BC9E-9AD6-49C6-80FA-BCF3A4C7B81C](https://user-images.githubusercontent.com/83868117/187698586-0486b6b9-b875-4b30-a94f-d6ff763a5a49.jpeg) Not exactly same with last one, here is a blurry widget title on Chrome 104.0.5112.99 MacOS

also an issue on MobileSafari 14, maybe open a separate issue for this?

**Comment by njust** [comment]
Turns out, that this is an issue with the compression of the RDP client I'm using.
