### ISSUE TITLE
frame.info().window_info.position is None on linux

### ISSUE THREAD

**Issue by MrTanoshii** [emilk/egui#2004]
**Describe the bug**
The window position info is unavailable on linux.

**To Reproduce**

1. Add a `println!("{:?}", frame.info().window_info);` in the `update` loop
2. Run

**Expected behavior**

The position should be available.

**Screenshots**

![VirtualBoxVM_TAGVJkGV2u](https://user-images.githubusercontent.com/47116127/188452555-a6a02252-ee59-44b4-a916-15aa6451149d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 22.04

**Additional context**

It works fine on Windows
Source code also available at https://github.com/MrTanoshii/rusty-autoclicker/releases/tag/v2.0.0

**Comment by ar37-rs** [comment]
@MrTanoshii only happens on wayland, on x11 working fine. seems like winit issue.

**Comment by MrTanoshii** [comment]
> @MrTanoshii only happens on wayland, on x11 working fine. seems like winit issue. for xwayland based desktop (GNOME 41+) telling winit to use x11 seems to fix the position checking problem:
> 
> ```shell
> export WINIT_UNIX_BACKEND=x11
> ./launch_your_app
> ```

Thank you, that worked!
I'll close the issue as it isn't egui related after all.

Would you happen to know of a way to force x11 all the time?

**Comment by bdnugget** [comment]
With me it crashes under Wayland with Hyprland. Funny thing is that you do see coordinates, key presses and mouse clicks registered when hovering over floating windows, but nothing when over tiled windows. 
Setting WINIT_UNIX_BACKEND=x11 did not change any of this behavior.

```
RUST_BACKTRACE=full WINIT_UNIX_BACKEND=x11 rusty-autoclicker

thread 'main' panicked at src/app.rs:153:71:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x55d3aada9682 - <unknown>
   1:     0x55d3aa9ddb63 - <unknown>
   2:     0x55d3aada937f - <unknown>
   3:     0x55d3aada94e3 - <unknown>
   4:     0x55d3aada9043 - <unknown>
   5:     0x55d3aade2455 - <unknown>
   6:     0x55d3aade23e9 - <unknown>
   7:     0x55d3aade2bac - <unknown>
   8:     0x55d3aa802c0f - <unknown>
   9:     0x55d3aa802d4b - <unknown>
  10:     0x55d3aa802f68 - <unknown>
  11:     0x55d3aa862d94 - <unknown>
  12:     0x55d3aa873199 - <unknown>
  13:     0x55d3aa872b99 - <unknown>
  14:     0x55d3aa85bd28 - <unknown>
  15:     0x55d3aa86267c - <unknown>
  16:     0x55d3aa86ad19 - <unknown>
  17:     0x55d3aa87da5c - <unknown>
  18:     0x55d3aaa52829 - <unknown>
  19:     0x55d3aaa31437 - <unknown>
  20:     0x55d3aaa49ece - <unknown>
  21:     0x55d3aaa2de6b - <unknown>
  22:     0x55d3aa887c61 - <unknown>
  23:     0x55d3aa854f36 - <unknown>
  24:     0x55d3aa888fa3 - <unknown>
  25:     0x7f9cbd427675 - <unknown>
  26:     0x7f9cbd427729 - __libc_start_main
  27:     0x55d3aa854e35 - <unknown>
  28:                0x0 - <unknown>
```


Edit: sorry, this issue belongs to rusty-autoclicker
