### ISSUE TITLE
High CPU usage when window is focused

### ISSUE THREAD

**Issue by Sirius902** [emilk/egui#2008]
**Describe the bug**
When using eframe's native window, CPU usage will spike severely when the window is focused. This happens simply if the window is focused with an app that requests a repaint in update, or if you move the mouse quickly across the window.

**To Reproduce**
1. Clone egui.
2. Run the egui demo app using `cargo run --release -p egui_demo_app`.
3. Switch the rendering mode to Continuous in the Backend menu.
4. Unfocus the window (i.e. click onto another window) and observe that CPU usage is low for the app.
5. Focus the window and observe that CPU usage is spiking massively (maxing out a single core on my machine).
6. This behavior can also be observed on Reactive mode by quickly moving the mouse back and forth across the window while it is focused.

**Expected behavior**
Since the UI is rendering at the same framerate regardless of if the window is focused, I would expect the CPU usage to be similar when the window is focused and not focused.

**Screenshots**
Window is not focused (demo app is using ~0.7% CPU)
![Screenshot 2022-09-05 164337](https://user-images.githubusercontent.com/10891979/188521573-406fcb7e-5a03-4666-9ff5-5b68e4c935a0.png)

Window is focused (demo app is using ~9.6% CPU)
![Screenshot 2022-09-05 164426](https://user-images.githubusercontent.com/10891979/188521583-92983fe8-0cf7-4b97-859d-ad761f51d87a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Native desktop app (eframe)

**Additional context**
I noticed this when trying to develop an app using egui that also requests a repaint in update, so, I attempted to recreate the issue with the demo app and noticed the issue is present there as well.

**Comment by UE2020** [comment]
> When using eframe's native window, CPU usage will spike severely
This is true of basically any GUI, 9% CPU isn't even a lot. Try the same experiment on Discord or VSCode, from my testing Discord hits around 70% CPU utilization with any mouse movement.

**Comment by emilk** [comment]
yes - if the "bug" us that egui uses 10% CPU at peak usage, then that's not a bug. That's good performance.

**Comment by Sirius902** [comment]
Oh alright. I just wasn't sure if there might be a bug causing more utilization with the eframe event handling when focused, but if this CPU utilization is acceptable then that's fair. Thank you for this library by the way, it's pretty awesome.
