### ISSUE TITLE
A way to check if pointer is over a Window

### ISSUE THREAD

**Issue by mdenchev** [emilk/egui#203]
I have interactables behind UI widgets and would like a way to block interactions when the mouse is over a widget. I tried using `ui_contains_pointer()` but that does not seem to contain the title bar of a window. Is there a way to do the same thing as `ui_contains_pointer()` but for the whole window including title bar?

**Comment by emilk** [comment]
Check out:

https://docs.rs/egui/0.10.0/egui/struct.Context.html#method.is_using_pointer
https://docs.rs/egui/0.10.0/egui/struct.Context.html#method.is_pointer_over_area
https://docs.rs/egui/0.10.0/egui/struct.Context.html#method.layer_id_at
https://docs.rs/egui/0.10.0/egui/containers/struct.Area.html#method.layer
