### ISSUE TITLE
Demo App: custom3d_glows.rs - could not find `ShaderVersion` in `egui_demo_lib`

### ISSUE THREAD

**Issue by bidimensional** [emilk/egui#2034]
Hi, I am trying to build the demo app on my laptop and downloading all the dependencies using the Cargo.toml defined there. I amended the toml fille so that it downloads the dependencies from crates.io rather than referencing a local folder, by dropping the path parameter.

However, I get an error when compiling:

error[E0433]: failed to resolve: could not find `ShaderVersion` in `egui_glow`
  --> src\apps\custom3d_glow.rs:94:41
   |
94 |         let shader_version = egui_glow::ShaderVersion::get(gl);
   |                                         ^^^^^^^^^^^^^ could not find `ShaderVersion` in `egui_glow`

The method doesn't appear to be there.. but I was able to compile it in the past using the content of the crates folder from GitHub as a dependency, is there something wrong in the egui_glow version on crates.io?

**Comment by ar37-rs** [comment]
egui_glow 0.19.x doesn't expose ShaderVersion as public API (it's private API).

**Comment by emilk** [comment]
If you want to look at the code that is compatible with 0.19.0, you need to look at https://github.com/emilk/egui/blob/0.19.0/crates/egui_demo_app/src/apps/custom3d_glow.rs instead of https://github.com/emilk/egui/blob/master/crates/egui_demo_app/src/apps/custom3d_glow.rs
