### ISSUE TITLE
Web Mode Positioning Incorrect With EGUI Template

### ISSUE THREAD

**Issue by zicklag** [emilk/egui#204]
**Describe the bug**
The web render of the EGUI template library is stuck in the center of the screen with the update to EGUI 0.10. This is also happening on my project based on the template that I just migrated to 0.10.

**To Reproduce**
1. Clone the template repo
2. `./build_web.sh`
3. Serve the web example

**Expected behavior**
Rendered EGUI should fill the web page

**Screenshots**
![image](https://user-images.githubusercontent.com/25393315/110051534-ae7dc880-7d1b-11eb-91b8-c13c23aeedb6.png)

**Desktop (please complete the following information):**
 - Browser firefox/chromium

**Comment by emilk** [comment]
This is expected behavior. I added a limit because of some web browsers not handling huge WebGL canvases very well. You can control it with https://docs.rs/epi/0.10.0/epi/trait.App.html#method.max_size_points

**Comment by zicklag** [comment]
Awesome, thanks!
