### ISSUE TITLE
Caps Lock Key/Modifier

### ISSUE THREAD

**Issue by parker-codes** [emilk/egui#2041]
**Is your feature request related to a problem? Please describe.**

Provide more visual context to a user as they are typing when Caps Lock is on. One example might be password inputs where a warning message could prevent confusion from accidental caps.

**Describe the solution you'd like**

I'd like to either be able to check the modifier state or listen to an on/off event. Then the UI could style the hint however I want.

**Comment by njust** [comment]
You can already check the modifiers via the input state.
https://docs.rs/egui/0.19.0/egui/struct.InputState.html
https://docs.rs/egui/0.19.0/egui/struct.Modifiers.html

**Comment by parker-codes** [comment]
Thank you, @njust. What I'm specifically looking for though is the Caps Lock modifier, which is not yet available.

**Comment by emilk** [comment]
Closed in favor of https://github.com/emilk/egui/issues/3653
