### ISSUE TITLE
Macos memory consumption issue

### ISSUE THREAD

**Issue by qdwang** [emilk/egui#2044]
**Describe the bug**

When using the latest eframe, a very abnormal memory usage issue happens.
**Resizes the main window can affect the program memory consumption in macos**

When you maximize the window, it will take about 160MB.
When you shrink the size to 100 * 100, it will only take about 30-40MB.

**To Reproduce**
1. Create a hello world app by using only `eframe`
2. `cargo run -r`
3. Open **activity monitor** in macos
4. Resize your window to maximium
5. Check the hello world program in activity monitor, let's assume the memory usage is `A`.
6. Resize your window to about 100 * 100
7. Check the hello world program in activity monitor, let's assume the memory usage is `B`.
8. You will find out that `A` is way bigger than `B`.

**Desktop (please complete the following information):**
 - OS: MacOS 12.5.1 M2 chip

**Comment by adamierymenko** [comment]
Is this real memory consumption or perhaps some artifact of mmap() usage?

**Comment by qdwang** [comment]
@adamierymenko it seems to be a graphic memory usage, macos with integrated graphic card will count the cpu memory and gpu memory together in activity monitor.
