### ISSUE TITLE
combo box selection broken

### ISSUE THREAD

**Issue by the-drunk-coder** [emilk/egui#205]
**Describe the bug**
Clicking an item in a combo box doesn't trigger the selection (anymore)

**To Reproduce**
1.' click on combo box
2. select item

**Expected behavior**
The item selection is performed 

**Desktop (please complete the following information):**
 - OS: linux/xorg

**Additional context**
Seems like this was broken by commit 007f9f3cb99e3d2fd1b637c05e2bf1f2f6a0ba2a ...
Putting the old version of `popup.rs` back in place fixes the problem. 

Not sure what triggered the change in the first place ? The combo box worked as I expected, clicking anywhere outside or inside closed the popup ...

**Comment by emilk** [comment]
You are right, it's broken. Oops!

The motivation was this: https://github.com/emilk/egui/issues/198 (see link in commit description of 007f9f3 )
