### ISSUE TITLE
Is there a way to play video?

### ISSUE THREAD

**Issue by goldwind-ting** [emilk/egui#2060]

**Comment by ar37-rs** [comment]
Use 3rd party encoder, like ffmpeg or libvlc, that's it. don't ask here how, just google.

**Comment by goldwind-ting** [comment]
> Use 3rd party encoder, like ffmpeg or libvlc, that's it. don't ask here how, just google.

I mean how to develop a player use this library.

**Comment by ar37-rs** [comment]
@goldwind-ting make each of frames of the decoded video as image widget, that's the clue for that.
