### ISSUE TITLE
Get a handle to TemplateApp for eframe 0.19

### ISSUE THREAD

**Issue by saturn77** [emilk/egui#2065]
I am attempting to duplicate an existing project but upgrading from eframe 0.16 to 0.19, but having trouble getting a handle to the TemplateApp struct from main().  How is this done? 

The project I am referencing is here:
  
https://github.com/andy31415/rs-value-plotter

The basic approach in this design is to have a struct 

```rust 
struct TemplateApp {
    buffer : Arc<Mutex<VecDeque<egui::plot::Value>>>
}
```

and in a std::thread within main(), clone the handle to the TemplateApp and introduce values into the buffer. 

Now with eframe 0.19 I want to use a native GUI versus a wasm application. So the impl for as_any_mut for wasm32 is not helping in this case, as far as I can tell. 
![image](https://user-images.githubusercontent.com/5698048/191355262-7ecdc50d-482e-4dac-996f-70fcddf775dc.png)

**Comment by emilk** [comment]
You cannot get a handle to the app, but you can easily set up some shared state before calling `run_native` that you pass to your app. That is, create an `Arc<Mutex<…>>`, clone it, and pass the clone to your app, and modify the other handle.
