### ISSUE TITLE
Storage Issue when passing a Mutex to eframe 

### ISSUE THREAD

**Issue by saturn77** [emilk/egui#2074]
I am passing an Arc<Mutex\<T>\> as an argument to eframe as shown below, where T is a String. 

In the ui update() function, I lock the mutex and read the data, and then put it to a text edit window. This all works fine, except when I use persistence in the new () function. When I do that, I get nothing on the text edit screen. 

I am not sure if this is something that I did wrong a just a current limitation of the envisioned methodology with regards to passing an argument to eframe *and* wanting to having previous app state recall. 

```rust 
#[cfg(not(target_arch = "wasm32"))]
fn main() {
    tracing_subscriber::fmt::init(); 
    let mut tic : u32 = 0;
    let zz : Arc<Mutex<String>> = Arc::new(Mutex::new(String::new()));
    let xx = zz.clone();

    std::thread::spawn( move || loop { 
        let msg : String = format!("Main Tic =  {:?} \r", tic);
        println!("{:?}", msg);
        tic += 1;
        std::thread::sleep(std::time::Duration::from_millis(1000));
        *zz.lock().unwrap() = msg; 
        println!("alpha.lock = {:?}", zz.lock().unwrap());
    });

    let native_options = eframe::NativeOptions::default();

    eframe::run_native(
        "Plotter",
        native_options,
        Box::new(|cc| Box::new(TemplateApp::new(cc, xx)))
    );

}

```

The application struct looks like this, where the "buffer" is the member of the TemplateApp struct that I am passing into. 

```rust 
#[derive(serde::Deserialize, serde::Serialize)]
#[serde(default)] 
pub struct TemplateApp {
    p2        : Protection,
    p3        : Protection,
    mirror    : bool, 
    test_vcon : TestVCON,

    #[serde(skip)]
    logger_text    : String, 

    #[serde(skip)]
    pub buffer  : Arc<Mutex<String>>,
    #[serde(skip)]
    buffer_old : String,
    
    beta : u32,
    tic_index : u32,
}
```

The new() function "constructor" looks like this below. When I comment out the storage lines, everything works. When the storage is enable, the Arc<Mutex<String>> is never displayed . . . 

So it appears that on the initial call to new(), the storage is loaded and the function returns, never assigning the "tic_string" to the buffer. So if storage is to be used, how to avoid this situation? Thanks . . . 

```rust 

        pub fn new(
        cc: &eframe::CreationContext<'_>,
        tic_string : Arc<Mutex<String>>,
        ) -> Self {
            **if let Some(storage) = cc.storage {
                return eframe::get_value(storage, eframe::APP_KEY).unwrap_or_default();
            }**
            Self {
                p2 : Protection{max_volts : MAX_DC_VOLTS, debounce_sec : DEBOUNCE_SEC, timeout_min : TIMEOUT_MIN },
                p3 : Protection{max_volts : MAX_DC_VOLTS, debounce_sec : DEBOUNCE_SEC, timeout_min : TIMEOUT_MIN },
                mirror : false, 
                test_vcon : TestVCON{volts : 0.0, enable : false, relays : Relays{on : false, off : true,  p2 : false, p3 : false}},
                logger_text : "Parrot2VCON Graphical User Interface".to_string(),
                buffer : tic_string,
                buffer_old : "".to_string(),
                beta   : 0,
                tic_index : 0,
            }
        }   
    }
```

**Comment by ar37-rs** [comment]
```rust
 *zz.lock().unwrap() = msg; 
  println!("alpha.lock = {:?}", zz.lock().unwrap());
```

seems too fast.

**Comment by saturn77** [comment]
> ```rust
>  *zz.lock().unwrap() = msg; 
>   println!("alpha.lock = {:?}", zz.lock().unwrap());
> ```
> 
> seems too fast.

In testing the GUI for about 12 hours, it does work . . . I have code in the ui update() loop that looks for a *change* in the text string, and then updates the text window. As long as the persistence code is not in the new() function, everything works fine . . .
