### ISSUE TITLE
wgpu RenderPass with a depth/stencil attachment

### ISSUE THREAD

**Issue by kvark** [emilk/egui#2083]
Related to #2022

**Is your feature request related to a problem? Please describe.**
My main render pass has a depth/stencil attachment. I'm using `egui_wgpu_backend`, and [render pass creation](https://docs.rs/egui_wgpu_backend/0.19.0/egui_wgpu_backend/struct.RenderPass.html#method.new) assumes no depth/stencil involved.
That means, I can't render egui in my main render pass (it's incompatible with a render pipeline you create). That's unfortunate and wasteful on tiling GPU architectures.

**Describe the solution you'd like**
Have an `Option<wgpu::TextureFormat>` argument for the render pass creation, where the user would tell the format for depth/stencil, if any. It should involve minimal changes on egui wgpu side, could be done as another render pass constructor, e.g. `RenderPass::with_depth_stencil`.

**Describe alternatives you've considered**
None.

**Additional context**
Downstream work - https://github.com/kvark/vange-rs/pull/214
Egui looks great overall, thank you for amazing work!

**Comment by Wumpf** [comment]
with the egui-wgpu crate this can already be solved by using `render_onto_renderpass` - although I do agree with #2022 that this should be just always the case, i.e. call that `render` and remove `render_onto_renderpass` (with that `egui_wgpu::Renderer` also looses any knowledge of depth buffer)

Given that this ticket is kinda duplicate or belongs to egui_wgpu_backend, do you agree or am I missing something?

**Comment by kvark** [comment]
You mean https://github.com/emilk/egui/blob/c414af7aa2858703d2ff5d72b8dbf1a657da5991/crates/egui-wgpu/src/renderer.rs#L156 specifically. Glad to see this fixed!
