### ISSUE TITLE
Last commits with sRBG stuff crushes on Windows

### ISSUE THREAD

**Issue by enomado** [emilk/egui#2085]
I dig to last working commit is 12dc61ed0f1a23b45e336799005d62e0a6f47e4f
I cant dig more because of dual boot but recheck please.

I build egui_demo_app on linux

build command was 
`cargo build --target x86_64-pc-windows-gnu --release`

**Comment by enomado** [comment]
`D:\>egui_demo_app.exe
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', crates/eframe/src/native/run.rs:345:22`

**Comment by enomado** [comment]
There is some https://github.com/rust-windowing/glutin/issues/913

Which is also https://github.com/emilk/egui/issues/2018

and in my case, its caused only by turning srgb to false...  https://github.com/emilk/egui/blame/master/crates/eframe/src/native/run.rs#L341

**Comment by ar37-rs** [comment]
@enomado Try change `srgb_textures` on https://github.com/emilk/egui/blob/master/crates/egui_glow/src/painter.rs at line 119  to `false` like so:
```rust
// let srgb_textures = shader_version == ShaderVersion::Es300 // WebGL2 always support sRGB
let srgb_textures = false;
```
is that help?

**Comment by ar37-rs** [comment]
We need to know the log
```rust
set RUST_LOG=debug
egui_demo_app.exe
```

**Comment by enomado** [comment]
@ar37-rs it happens before code you listed. 

full log is something like

```D:\>hello_world.exe
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', crates/eframe/src/native/run.rs:345:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by enomado** [comment]
Everything just works with `srgb = true`

Is there something I can change here?

       pixel_format: PixelFormat {
                        hardware_accelerated: true,
                        color_bits: 24,
                        alpha_bits: 8,
                        depth_bits: 0,
                        stencil_bits: 0,
                        stereoscopy: false,
                        double_buffer: true,
                        multisampling: None,
                        srgb: true,
                    },
                    
Or can I just leave `srgb = true` ?

**Comment by ar37-rs** [comment]
@enomado i've added a fix on #2082 is that help?

**Comment by enomado** [comment]
I think so. Thanks!

**Comment by Ben-Lichtman** [comment]
It seems like this is not solved on the current master branch - I am still getting the original error
