### ISSUE TITLE
images are not listening to clicks

### ISSUE THREAD

**Issue by adsick** [emilk/egui#209]
I had a code like this:
```rust
            if let Some(mpos) = ui.image(texture_id, (dims.0 as f32, dims.1 as f32)).interact_pointer_pos(){ //does not work
                println!("{:?}", mpos);
            };

```
it compiles and shows the picture, but when I click on image - nothing happens;
then I wrote a similar code but with .hover() instead and this method appears to work.
then I tried to write this:
```rust
            if ui.image(texture_id, (dims.0 as f32, dims.1 as f32)).clicked(){
                println!("clicked");
            }
```
and when I click on image - nothing happens, therefore images are not reacting to clicks on them.

pc: Fedora 33, i5-3330, 8gigs of ram

**Comment by emilk** [comment]
If you want a clickable image use `ImageButton`: https://docs.rs/egui/0.10.0/egui/widgets/struct.ImageButton.html
