### ISSUE TITLE
Pointer released events do not trigger for drags

### ISSUE THREAD

**Issue by Baezon** [emilk/egui#2094]
I.e. the click was only held briefly. This seems to be by design? `PointerEvent` only has `Option<Click>` meaning that if the click is held too long and does not count as a click, the event merely has `None` and has no idea what button was released, and therefore cannot trigger `primary_released()`, `secondary_released()`, etc. 

Either way, very confusing that `button_released()` does not actually always trigger when the button releases.

**Comment by jiftoo** [comment]
+1

It seems that `PointerState::button_released()` check if a button was released only within a click, unlike `PointerState::any_released()`. This doesn't seem intentional.

```rust
/// Was any pointer button released (`down -> !down`) this frame?
pub fn any_released(&self) -> bool {
    self.pointer_events.iter().any(|event| event.is_release())
}
/// Was the button given released this frame?
pub fn button_released(&self, button: PointerButton) -> bool {
    self.pointer_events
        .iter()
        .any(|event| matches!(event, &PointerEvent::Released(Some(Click{button: b, ..})) if button == b))
}
```
