### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by 107295472** [emilk/egui#2118]
![image](https://user-images.githubusercontent.com/6436116/194482331-b4570354-67f8-44e1-a13d-2051a335f63e.png)

**Comment by emilk** [comment]
You need to install a font that supports Chinese characters: https://docs.rs/egui/latest/egui/struct.Context.html#method.set_fonts

**Comment by RSS1102** [comment]
It seems that not all Chinese characters can be supported.
i used some fonts in Chinese are not supported。Try a few more Chinese fonts.
