### ISSUE TITLE
DatePickerButton: run closure on save

### ISSUE THREAD

**Issue by cdhf** [emilk/egui#2134]
I am using a DatePickerButton to show dates I get from a server. When I change a date, I want to upload the new date to the server. This would be easier if I could run some code when the save button is pressed.

So in addition to DatePickerButton::new, it would be great to have something looking like this:

DatePickerButton::on_save(initial_date, |new_date| println!("do something with the date"))

**Comment by emilk** [comment]
The way it is _supposed_ to work is:

``` rust
let response = ui.add(DatePickerButton::new(…));
if response.changed() {
    println!("The date changed!");
}
```

if that doesn't work, then `DatePickerButton` is forgetting to set the `changed` flag, but that should be an easy fix.

**Comment by cdhf** [comment]
I didn't realize I could use the change method. Unfortunately it doesn't work with the datepicker widget.
