### ISSUE TITLE
Keys not turned into characters in native egui when input methods are deactivated

### ISSUE THREAD

**Issue by ksqsf** [emilk/egui#2141]
**Describe the bug**

When input methods are deactivated, or in "English" mode, it is expected that keys are directly turned into characters in a text field.

In the following screencast, after typing two Chinese characters, switch to English mode by pressing Shift. Then type random letters, but only the first key press `j` successfully appeared, and other input didn't. Switch again to Chinese mode, it now works again.

https://user-images.githubusercontent.com/23358293/195254695-0ba9edd1-1553-47d4-b957-6f0570dbb9e0.mov

**To Reproduce**
1. Switch to a non-English input method. In my case, [RIME](https://rime.im/), [Qingg](https://qingg.im/), and [Luoge](https://im.logcg.com/).
2. Switch to English mode.
3. Press any key to type letters.

**Expected behavior**
Letters should be input when input methods are in English mode.

**Screenshots**
See the description above.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser n.a.
 - Version 12.6

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**
AFAIK this problem happens to macOS native egui, but not to Web egui. I haven't tested it on Windows and Linux.

**Comment by emilk** [comment]
A lot of IME fixes lately - does this work for you now?

**Comment by ksqsf** [comment]
Thanks for the heads up. Just tried the master branch. Although there are still some problems wrt preedit etc., but this issue _per se_ doesn't happen. So I'm going to close this issue.
