### ISSUE TITLE
RGB color values are not correct

### ISSUE THREAD

**Issue by josuigoa** [emilk/egui#2161]
**Describe the bug**
When I add a `egui::widgets::color_picker::color_edit_button_rgb(ui, rgb)` and select a color I see some values in the widget itself and get different ones in the rgb variable when I print them

**To Reproduce**
Clone an run the [this](https://github.com/josuigoa/egui_color_bug) example and watch the console output

**Expected behavior**
I was expecting to see the value of the widget (in 0...255 range) as value in 0...1 range. But they are not equivalent.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/3088505/196358389-ce80df96-2d72-4627-91f9-b4110aac2508.png)

When I select the red value 255 in the widget, the console output of 1 is correct. But the green value in widget being 106, the console output should be 106/255=0.41568 but is 0.142857.

**Desktop (please complete the following information):**
 - Windows 10 native

**Comment by emilk** [comment]
> I was expecting to see the value of the widget (in 0...255 range) as value in 0...1 range. But they are not equivalent.

You're expectations are wrong - the 0-255 values are in sRGB gamma space: https://en.wikipedia.org/wiki/SRGB

Use [`egui::Rgba`](https://docs.rs/epaint/latest/epaint/color/struct.Rgba.html) if you want linear space colors
