### ISSUE TITLE
"Hover to zoom" no longer working in Settings UI

### ISSUE THREAD

**Issue by parasyte** [emilk/egui#220]
**Describe the bug**

An empty popup appears in the Settings UI when the pointer is hovered over the font texture.

**To Reproduce**

1. Open the Settings UI in the demo app, e.g. https://emilk.github.io/egui/index.html will do fine for testing.
2. Expand the "Fonts" collapsing header.
3. Hover your pointer over the font texture.
4. I see an empty popup.

**Expected behavior**

This is a regression introduced in version 0.10.0. Older versions would show a magnified view of the font texture.

**Screenshots**

<img width="413" alt="Screen Shot 2021-03-09 at 3 29 35 PM" src="https://user-images.githubusercontent.com/456942/110552486-4862be00-80ec-11eb-938c-82d6b010307f.png">

The empty box at the bottom should not be empty. See below for the expected result as shown in version 0.9.0:

<img width="369" alt="Screen Shot 2021-03-09 at 4 00 17 PM" src="https://user-images.githubusercontent.com/456942/110554992-ab565400-80f0-11eb-8c57-62a00a1f87a3.png">

**Comment by emilk** [comment]
Thanks!
