### ISSUE TITLE
Being able to customise check mark in button to only have colours

### ISSUE THREAD

**Issue by Dominik1999** [emilk/egui#2215]
**Is your feature request related to a problem? Please describe.**

I want to create a Game of Life. So I need a grid of n x n buttons or checkboxes. When activated, I want the button or checkbox to change colour instead of showing the check mark. Maybe this is already possible (using radio buttons is too ugly). 

**Describe the solution you'd like**

A n x n grid where every cell is black and when "activated", the cell has a different colour, e.g. green. 

**Describe alternatives you've considered**

**Additional context**

**Comment by ItsEthra** [comment]
You can change checkbox color or radio button's dot by changing `visuals.widgets.inactive.fg_stroke.color`. Additionally you can wrap it into `ui.scope` so those changes won't affect the rest of the application. https://imgur.com/fPg4kZ3
```rust
ui.scope(|ui| {
    ui.style_mut().visuals.widgets.inactive.fg_stroke.color = Color32::RED;
    // If you want the same color when hovered
    ui.style_mut().visuals.widgets.hovered.fg_stroke.color = Color32::RED;

    ui.checkbox(&mut self.check, "Checkbox");
    ui.radio(self.check, "Radio");
});
```

**Comment by Dominik1999** [comment]
Thanks a lot for the quick response. 

The code works. However, now my check mark is red instead of green. I want no check mark but the whole box to be red (if inactive) and green (if active / checked). Does that make sense?

**Comment by ItsEthra** [comment]
You can use https://docs.rs/egui/latest/egui/struct.Painter.html#method.rect_filled for that.

**Comment by Dominik1999** [comment]
Thanks a lot. I am quite new here, but do you mean changing the `Painter` in `button.rs`? Can I somehow override the default `Painter`?

**Comment by ItsEthra** [comment]
To get a `Painter` instance you probably would want to use one of the `ui.allocate_*` functions. You can take a look at the example with custom checkbox to see how it is used. Then through various methods you can fill allocated space with small squares(`rect_filled` method I mentioned above).

**Comment by Dominik1999** [comment]
Man, sorry to bother again, I am sure you have other stuff to do as well. But somehow I don't get it. 

I have the following code working at the moment: 

```
                egui::Grid::new("some_unique_id").show(ui, |ui| {
                    for i in 0..=*(sqrt_number_of_cells) as usize  - 1 { 
                        for j in 0..=*(sqrt_number_of_cells) as usize - 1 { 
                                ui.checkbox(&mut self.front_end_grid[i][j], "");
                        }
                        ui.end_row();
                    }
                });
```

It creates a grid of checkboxes for a given number of cells `sqrt_number_of_cells`.

I understand, that I can now put the grid inside a 

```
ui.scope(|ui| { 
... grid ...
});
```

Within the `ui.scope` I can use `ui.allocate_*`. But somehow I don't get my `checkbox` red (inactive) and green (active).

**Comment by david072** [comment]
You can use this to create a rectangle, whose background color can be toggled:
```rs
fn custom_checkbox(ui: &mut Ui, width: f32, height: f32, checked: &mut bool) -> Response {
    // create a `Rect` with given size
    let (rect, response) = ui.allocate_exact_size(
        vec2(width, height), Sense::click(),
    );

    // if the rect is visible
    if ui.is_rect_visible(rect) {
        // paint with a background color, depending on whether we're checked
        let color = if *checked { Color32::GREEN } else { Color32::RED };
        ui.painter().rect_filled(rect, 0.0, color);

        // if we're clicked, update the checked state
        if response.clicked() {
            *checked = !*checked;
        }
    }

    response
}
```

The `response` also has other useful functions, such as `hovered()`.
For a larger example, see https://github.com/emilk/egui/blob/master/crates/egui_demo_lib/src/demo/toggle_switch.rs.

**Comment by ItsEthra** [comment]
```rust
const SPACING: f32 = 4.;
const WIDTH: f32 = 18.;
const N: usize = 10;

let (r, p) = ui.allocate_painter(Vec2::splat(N as f32 * WIDTH + SPACING * (N - 1) as f32), Sense::click());
let input = ui.input().pointer.clone();

for i in 0..N {
    for j in 0..N {
        let min = r.rect.min
            + vec2(
                i as f32 * WIDTH + i as f32 * SPACING,
                j as f32 * WIDTH + j as f32 * SPACING,
            );

        let rect = Rect {
            min,
            max: min + Vec2::splat(WIDTH),
        };

        let color = if input.hover_pos().map(|p| rect.contains(p)).unwrap_or(false) {
            // Hovered

            if r.clicked() {
                // Clicked
                println!("Clicked {i} {j}");
            }

            Color32::WHITE
        }

        p.rect_filled(rect, Rounding::none(), color)
    }
}
```

**Comment by Dominik1999** [comment]
Amazing, exactly what I wanted. Thanks
