### ISSUE TITLE
Ui::vertical_centered is not centered

### ISSUE THREAD

**Issue by RazrFalcon** [emilk/egui#222]
`Ui::vertical_centered` not always place the widget in the center.

In the demo app, it can be reproduced by resizing the _Windows Options_ dialog.

**To Reproduce**
1. Create a widget using `Ui::vertical_centered`
2. Resize the parent layout

**Expected behavior**

The layout content should be centered.

**Screenshots**

![1615376113](https://user-images.githubusercontent.com/725494/110623591-b61ef080-81a5-11eb-8d75-4ff38947a3d4.png)

**Desktop (please complete the following information):**
 - OS: Linux

egui version: https://github.com/emilk/egui/commit/07a17dc6cf3841a94f5d93821255cf8a7ed87a5d

**Comment by RazrFalcon** [comment]
Looks like this is the same as #179

**Comment by emilk** [comment]
thanks for the report!
