### ISSUE TITLE
egui::SidePanel::show_animated exists in the 0.19 source code and demo, but not in the public crate

### ISSUE THREAD

**Issue by xudesheng** [emilk/egui#2229]
If you are asking a question, use [the egui discussions forum](https://github.com/emilk/egui/discussions/categories/q-a) instead!

The `show_animated` api doesn't exist in the https://docs.rs/egui/latest/egui/containers/panel/struct.SidePanel.html#method.show

However, it's accessible in line 235 in the [wrap_app.rs](https://github.com/emilk/egui/blob/master/crates/egui_demo_app/src/wrap_app.rs)

and it's a `pub` method in the source.

have I missed in enabling any feature?

**Comment by ItsEthra** [comment]
It does not exists in 0.19 source code as you can see [here](https://docs.rs/crate/egui/latest/source/src/containers/panel.rs). It was added to master branch after 0.19 was released.

**Comment by xudesheng** [comment]
@ItsEthra Thank you, you are right.
