### ISSUE TITLE
Enable custom font file for egui_glium or egui_web?

### ISSUE THREAD

**Issue by n2n2** [emilk/egui#227]
There is a feature "default_font" in epaint, which controls wether to use default font file, or leave font file to user. The problem is, that feature is in epaint's default_feature group, and can not get disabled from outer crates, such like egui_glium or egui_web, which make executable or wasm large.
Maybe it is better to replace "default_font" to something like "no_default_font"(not in default-feature group), following the logic like:
```
#[cfg(not(feature = "no_default_fonts"))]
 {
    // Load default fonts
    ......
}
#[cfg(feature = "no_default_fonts")]
 {
    // Use empty FontDefinitions, leaving it to user
    ......
}
```
and expose "no_default_font" to egui, and hence to egui_glium and egui_web.
By doing so, the users can choose font file freely without wasting wasm size.

**Comment by t18b219k** [comment]
Default font is not part of  egui_glium or egui_web it is part of epaint .

**Comment by emilk** [comment]
Hi!

I tried working on this a bit in https://github.com/emilk/egui/pull/266 but I find cargo dependencies very confusing. I feel this is the right approach, if we can get it working.

`no_default_font` may work, but it seems a bit weird to me to turn on a feature to get less features. I don't know of any library that does this.
