### ISSUE TITLE
Incomplete advice for action on pressing enter in a text field

### ISSUE THREAD

**Issue by crumblingstatue** [emilk/egui#229]
The documentation of Reponse::lost_focus says:
```Rust
/// The widget had keyboard focus and lost it,
/// perhaps because the user pressed enter.
/// If you want to do an action when a user presses enter in a text field,
/// use this.
///
/// ```
/// # let mut ui = egui::Ui::__test();
/// # let mut my_text = String::new();
/// # fn do_request(_: &str) {}
/// if ui.text_edit_singleline(&mut my_text).lost_focus() {
///     do_request(&my_text);
/// }
/// ```
```
However, this approach has one big problem: It can trigger even if the user didn't press enter. It can trigger for example if the window that the text input is in is getting dragged, etc.

A correct approach for detecting pressing enter should be documented here.

**Comment by crumblingstatue** [comment]
I believe the correct approach is `re.lost_kb_focus() && re.ctx.input().key_down(egui::Key::Enter)`, but I'm not sure.

**Comment by emilk** [comment]
Good point. There are several things you may want to check for:

* `re.changed()` - text was changed this frame
* `re.lost_focus()` - user stopped editing the text
* `re.lost_focus()  && re.ctx.input().key_pressed(egui::Key::Enter)` - user finished editing with the `Enter` key

We could add all those examples to the docstring

**Comment by carcigenicate** [comment]
@emilk 

Is that last point supposed to be

```rust
re.lost_focus() && re.ctx.input(|i| i.key_pressed(egui::Key::Enter))
```
?

**Comment by crumblingstatue** [comment]
@carcigenicate The API has changed over time. It used to be different in 2021 (when that comment was made)

**Comment by carcigenicate** [comment]
> [@carcigenicate](https://github.com/carcigenicate) The API has changed over time. It used to be different in 2021 (when that comment was made)

Ah, thank you. I missed the date of that comment.
