### ISSUE TITLE
examples/custom_3d_three-d project, I wasn't able to get to compile for wasm

### ISSUE THREAD

**Issue by IwateKyle** [emilk/egui#2290]
This doesn't seem to be a bug - just a compilation error
In the examples/custom_3d_three-d project, I wasn't able to get to compile for wasm using the prescribed 

> wasm-pack build examples/custom_3d_three-d --target web

instruction because it complained of missing 
).await?

Once I added it, it worked.  If appropriate, I can make the PR with the modified code.

**Comment by emilk** [comment]
This example is no longer there
