### ISSUE TITLE
Improve color picker

### ISSUE THREAD

**Issue by bel8z** [emilk/egui#230]
In the color picker widget, the "Hue" slider is affected by the currently selected "Saturation" and "Value": this makes impossible to see the hue scale at low saturation and/or value.
This is a minor usability issue, but one that can make users frustrated since every other color picker keep the hue scale always visible.

The fix seems too small to be worth a pull request: in color_picker.rs,  `color_slider_1d(ui, h, |h| HsvaGamma { h, ..opaque }.into());` becomes `color_slider_1d(ui, h, |h| HsvaGamma { h, s: 1.0, v:1.0, ..opaque }.into());`.

Let me know what do you think about it, and keep up with the great job!

**Comment by emilk** [comment]
Yeah, makes sense! 👍
