### ISSUE TITLE
Plot bounds broken when all y values are the same

### ISSUE THREAD

**Issue by nknotts** [emilk/egui#2307]
**Describe the bug**
When all y values are identically the same, the calculated y bounds will be considered invalid and the default y-range of [0, 1] will be used instead. The same bug applies to x as well.

**To Reproduce**
I've created an example application here:

https://github.com/nknotts/egui/blob/added-plot-bounds-example/examples/plot_bounds/src/main.rs

The gist is

```
            let x_range = 0..1000;
            let single2: PlotPoints = x_range
                .clone()
                .map(|i| {
                    let x = i as f64 * 0.01;
                    [x, 2.0]
                })
                .collect();

            ui.label("All values == 2, completely missing");
            Plot::new("plot3")
                .allow_drag(false)
                .allow_zoom(false)
                .allow_scroll(false)
                .height(row_height)
                .show(ui, |plot_ui| plot_ui.line(Line::new(single2)));
```

Where determining the bounds, there is

https://github.com/emilk/egui/blob/a1f6f6821366c95b36b43e83ba67bc7e8645e14a/crates/egui/src/widgets/plot/mod.rs#L831

```
        let auto_x = !bounds_modified.x && (!min_auto_bounds.is_valid_x() || auto_bounds.x);
        let auto_y = !bounds_modified.y && (!min_auto_bounds.is_valid_y() || auto_bounds.y);
```

Ultimately there is a call to

https://github.com/emilk/egui/blob/a1f6f6821366c95b36b43e83ba67bc7e8645e14a/crates/egui/src/widgets/plot/transform.rs#L52

```
    pub fn is_valid(&self) -> bool {
        self.is_finite() && self.width() > 0.0 && self.height() > 0.0
    }
```

where, in this case, the height will be `== 0.0` since all values are the same. Since the y bounds are not valid, the default bounds of `[0, 1]` are used.

**Expected behavior**
An appropriate bound to be calculated for this case.

**Screenshots**
<img width="868" alt="Screen Shot 2022-11-14 at 1 33 45 PM" src="https://user-images.githubusercontent.com/5288782/201741817-8a7cb56f-a7b8-4785-ba07-80dbee7c7630.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.6

**Additional context**

**Comment by JumpyLionnn** [comment]
I have this issue as well, any updates?

**Comment by emilk** [comment]
The bounds will be zero-height, which probably leads to a divide by zero somewhere. Basically it is hard to pick a zoom on an axis if it is infinitely narrow. No zoom will make it fill the available width.

The same problem should happen if all X values are the same, or if there is just a single point in a plot (all X and all Y values are all the same).

It should be fairly easy to fix if someone wants to take a stab at it.

**Comment by bonsairobo** [comment]
@emilk Would an acceptable solution be to scale the `item_bounds` by `1.1` when doing this calculation?

```rust
            for item in &items {
                let item_bounds = item.bounds();
                if auto_x {
                    bounds.merge_x(&item_bounds);
                }
                if auto_y {
                    bounds.merge_y(&item_bounds);
                }
            }
```

Maybe the scaling value could be configurable.

**Comment by bonsairobo** [comment]
@emilk Maybe instead of this block in `Plot::new`:

```rust
        // Make sure they are not empty.
        if !bounds.is_valid_x() {
            bounds.set_x(&PlotBounds::new_symmetrical(1.0));
        }
        if !bounds.is_valid_y() {
            bounds.set_y(&PlotBounds::new_symmetrical(1.0));
        }
```

it could be:

```rust
        // Make sure they are not empty.
        if !bounds.is_valid_x() {
            bounds.expand_x(0.001);
        }
        if !bounds.is_valid_y() {
            bounds.expand_y(0.001);
        }
```
