### ISSUE TITLE
Open link in new tab

### ISSUE THREAD

**Issue by optozorax** [emilk/egui#231]
**Is your feature request related to a problem? Please describe.**
When browsing `egui` demos, I want to click to button `source code`, but after clicking, URL is opened in the same tab, but I want it to open in a new tab, so I can see the demo live.

**Describe the solution you'd like**
Add parameter to `egui::Output::open_url`, where specified is URL should be opened in a new tab, or in the same tab. Also, a URL should be opened in the same tab if clicked by the Left Mouse Button and should be opened in the new tab if clicked by Middle Mouse Button.

**Describe alternatives you've considered**
Another alternative — to always open links in a new tab.

**Comment by emilk** [comment]
Already added in https://github.com/emilk/egui/commit/1c06622dbcaefceec2e1cad32cad93eb54e6626b - will be coming in egui 0.11
