### ISSUE TITLE
[Eframe] Allow relative position canvas

### ISSUE THREAD

**Issue by lsh** [emilk/egui#2331]
I'm using Eframe in a notebook/widget context and have noticed that the styling from [the text agent](https://github.com/emilk/egui/blob/8671aa26e1f65340c41f6b2c6f3ef2d6d80a6567/crates/eframe/src/web/text_agent.rs#L166) forces a canvas to use the style `position: absolute`. Is there any information on why the styling is there and would it be possible to have an option that allowed other positioning?

**Comment by jprochazk** [comment]
This was fixed in https://github.com/emilk/egui/pull/4561 - note that setting width/height through CSS is now _required_ (otherwise you may run into #4699), but you should also be able to set `position: relative` on the canvas.
