### ISSUE TITLE
cargo deny fails due to problem with ndk-sys

### ISSUE THREAD

**Issue by mwcampbell** [emilk/egui#2336]
My PR no longer passes CI because cargo deny fails with this error:

failed to verify the checksum of `ndk-sys v0.4.0`

I think the solution is to update to ndk-sys 0.4.1, which was published about 12 hours ago.

**Comment by foresterre** [comment]
This is a crates.io / cargo issue which is being discussed here: https://github.com/rust-lang/cargo/issues/7180. 

In the same issue thread, a reply by the `ndk-sys` author can be found, who [explains](https://github.com/rust-lang/cargo/issues/7180#issuecomment-1325636251) what went wrong for `ndk-sys`.

**Comment by emilk** [comment]
Thanks both of you!
