### ISSUE TITLE
Need help with this unbelievable web bug. How does storage exists on a brand new browser?

### ISSUE THREAD

**Issue by robertpauson** [emilk/egui#2348]
I've added save state functionality to my App, it worked on native so I deployed to Web.. I couldn't pinpoint the bug for a while because the console output was not saying much but then I noticed a panic that has to do with some piece of data that is not present later in the program. I figured - maybe it detects storage I've had from previous when it used to run? 

And so I just used 2 panics!() as a way of finding out:

```
impl MyApp{
    pub fn new(cc: &eframe::CreationContext<'_>, blacklist_preload:HashSet<H160>, op_vec_reload:Vec<(H160,DisplayPart)>, storage_:HashMap<String, ColorImage>) -> Self {
        if let Some(storage) = cc.storage {
            panic!("se");
            return eframe::get_value(storage, eframe::APP_KEY).unwrap_or_default();
        }
        panic!("sde");
        let mut ma = MyApp::default();
        ma.BLACKLIST = blacklist_preload;
        ma.operational_vec_db = op_vec_reload;
        ma.storage_ = storage_;
        ma
    }
}
```

[`storage_` is my own addition to storage, hence the `_`]

And to eliminate all doubt, I've installed a new browser - Opera, and ran it first thing and this was the console output:

```
panicked at 'se', src/main.rs:913:13
```

But how...? How can that even happen?

stack question for points =) 
https://stackoverflow.com/questions/74581216/wasm-app-egui-storage-exists-on-a-new-clean-browser

**Comment by emilk** [comment]
`eframe::Storage uses [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) on web, so that's what you get. The storage is likely empty though.
