### ISSUE TITLE
Release new egui version

### ISSUE THREAD

**Issue by TimonPost** [emilk/egui#2357]
Hi! The unreleased github code contains some changes that are important to us (Embark) regarding `ahash` and `getrandom` dependencies which at the moment prevent us from upgrading to egui 0.19.  Also the wayland feature flag is great to have. Any estimation or plans to release a new version of egui/epaint and the rest? Would be lovely if you can do a release sometime soon.

Related issue: https://github.com/emilk/egui/issues/2009

**Comment by emilk** [comment]
Yeah, it's high time. I'll try to get to it this week or the next!

**Comment by TimonPost** [comment]
You are awesome!

**Comment by qihaiyan** [comment]
You are handsome!

**Comment by coderedart** [comment]
reminder to fix all clippy lints right after making a new release https://github.com/emilk/egui/blob/master/Cranky.toml#L115

**Comment by emilk** [comment]
0.20.0 released!
