### ISSUE TITLE
Synergies with https://github.com/Immediate-Mode-UI/

### ISSUE THREAD

**Issue by dumblob** [emilk/egui#236]
Just a small heads up - our organization [Immediate Mode UI](https://github.com/Immediate-Mode-UI/ ) is always looking for projects who would want to join us. It's nothing formal, but rather growing our community through having the repo under this organization. As a side effect, it helps to deal with [bus factor](https://en.wikipedia.org/wiki/Bus_factor ) :wink:.

Feel free to move this repo under the org any time. Cheers!

**Comment by emilk** [comment]
No thanks
