### ISSUE TITLE
Newlines get removed from a string pasted into a multiline text editor when targetting wasm32

### ISSUE THREAD

**Issue by samoylovfp** [emilk/egui#2377]
**Describe the bug**

When pasting a string into a `TextEdit` widget, on a webpage, all the newlines get replaced with a space character.
I have uploaded a minimal example [here](https://github.com/samoylovfp/broken_paste/blob/master/src/main.rs)
Which is deployed [here](https://samoylovfp.github.io/broken_paste/)
Built [using trunk](https://github.com/samoylovfp/broken_paste/blob/master/.github/workflows/trunk_build_and_deploy.yml)

This does not happen on `egui.rs` even though I don't see any significant changes in the source code.

**Expected behavior**
I expect the newline characters from the pasted string to be preserved.

**Video**
I type several numbers, separated with newlines into an instance of the widget on egui.rs and then tried to paste that into previously mentioned version. I also noticed that in the version built by trunk, copying does not work and keys do not repeat when I hold them.

https://user-images.githubusercontent.com/17025459/205495792-58783f47-4071-46f6-b7bf-98170c262b33.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chromium 100.0.4896.88, Firefox 107.0.1

**Additional context**
The problem might be not in the egui itself, but in one of the wasm <-> dom events libraries,  I would appreciate any help debugging this.

**Comment by samoylovfp** [comment]
Ah this was the fix
https://github.com/emilk/egui/blob/master/sh/build_demo_web.sh#LL47C8-L47C45

**Comment by coderedart** [comment]
you can have a `.cargo/config.toml` too.
template repo explains this -> https://github.com/emilk/eframe_template/blob/master/.cargo/config.toml
