### ISSUE TITLE
README should be updated to reflect current accessibility status

### ISSUE THREAD

**Issue by mwcampbell** [emilk/egui#2391]
@emilk I can open a PR for this if you want, but I also understand if you want to write things like this in the README yourself.

An accurate summary would be something like this:

egui includes optional support for [AccessKit](https://accesskit.dev/), which currently implements the native accessibility APIs on Windows and macOS. For platforms that AccessKit doesn't yet support, including web, there is an experimental built-in screen reader; in [the web demo](https://www.egui.rs/#demo) you can enable it in the "Backend" tab.

**Comment by emilk** [comment]
That sounds perfect to me - open a PR please!
