### ISSUE TITLE
DragValue not support unicode format or prefix

### ISSUE THREAD

**Issue by tkkcc** [emilk/egui#2405]
master branch egui eframe, browser
font: https://github.com/SolidZORO/zpix-pixel-font
**To Reproduce**
```rust
ui.label("账号");
ui.add(DragValue::new(&mut index).prefix("账号"));
ui.add(DragValue::new(&mut index).custom_formatter(|n,_|format!("账号{n}")));
```

**Screenshots**
![image](https://user-images.githubusercontent.com/17373509/206193006-e9a31145-170e-4961-b902-f57d4806f74b.png)

**Comment by emilk** [comment]
I’m guessing you’ve only installed your font in the Proportional family, not the Monospaced one. Yes, it’s a bit confusing

**Comment by tkkcc** [comment]
Thanks!
