### ISSUE TITLE
egui-wgpu panics if device is not found

### ISSUE THREAD

**Issue by lunixbochs** [emilk/egui#2427]
If the device_descriptor doesn't match a device, egui-wgpu will panic here:
https://github.com/emilk/egui/blob/f4d8ab9/crates/egui-wgpu/src/winit.rs#L72-L73

This means there's no good way for the caller to fall back to a different egui backend, their app just panics.

In Parallels, on an M1 Mac, running Ubuntu 22.04 in the VM, the GPU driver is limited enough that a default wgpu instantiation by egui fails to match a driver:

```rust
egui_wgpu::winit::Painter::new(Default::default(), 1, 0);
```

I worked around this by relaxing the device target, but I know there are also machines with no OpenGL at all, and I'd like to be able to provide a software fallback for those. It might be good to make these code paths return a Result somehow.

**Comment by emilk** [comment]
yup, we should indeed be avoiding any panics and `unwrap`:s, so returning a `Result` makes sense. Do you want to make a PR?
