### ISSUE TITLE
Table does not take the full height of CenterPanel

### ISSUE THREAD

**Issue by njust** [emilk/egui#2446]
Hi,

with egui 0.20.0 and current master it looks like this:

![image](https://user-images.githubusercontent.com/2380253/207369789-b0832240-ffc7-4a72-a940-dcddef3fa9c9.png)

with egui 0.19.0 the table took the full height of the CenterPanel:
![image](https://user-images.githubusercontent.com/2380253/207369985-4c63337b-1316-4a17-a1c3-c1381187dabe.png)

Repo with code to reproduce:
https://github.com/njust/table_grow_issue

![image](https://user-images.githubusercontent.com/2380253/207369380-8b72bb12-3a96-4b26-99d1-409ea60bd641.png)

**Comment by emilk** [comment]
You can fix this with [`max_scroll_height`](https://docs.rs/egui_extras/latest/egui_extras/struct.TableBuilder.html#method.max_scroll_height)

**Comment by njust** [comment]
Thanks!
