### ISSUE TITLE
AccessKit updates: macOS text editing, critical fixes for Windows 11 with Narrator

### ISSUE THREAD

**Issue by mwcampbell** [emilk/egui#2473]
We just need to bump egui-winit's dependency on accesskit_winit to 0.7.2. What's the standard procedure for such a dependency update?

**Comment by mwcampbell** [comment]
@emilk I mean, should I just open a PR with the dependency bump and the updated Cargo.lock, or would you rather batch this update with others, as you have before? I'd personally prefer to do this one right away, because AccessKit has momentum and I want to keep it going, with egui reflecting the latest improvements. But of course, this is your project.

**Comment by parasyte** [comment]
Given that the `accesskit_winit` semver spec is 0.7.1 with no other qualifiers, [Cargo treats it as a range](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio). There is technically no need to do anything more. Dependents will naturally pull in 0.7.2 for their first build (without a lockfile) or after running `cargo update`.

But IMHO, a PR just to bump a dependency is a reasonable thing to do.
