### ISSUE TITLE
glow: Failed to create glutin display

### ISSUE THREAD

**Issue by auroraanna** [emilk/egui#2486]
**Describe the bug**

I can't get the eframe_template app to start. When the rendering engine is set to `glow` it does the following error
```console
> cargo run
   Compiling freetype-sys v0.13.1
   …
   Compiling eframe v0.20.0
   Compiling eframe_template v0.1.0 (/home/annaaurora/projects/Finnarr)
    Finished dev [unoptimized + debuginfo] target(s) in 58.73s
     Running `target/debug/eframe_template`
2022-12-20T02:07:02.675585Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1.0833333333333333    
thread 'main' panicked at 'failed to create glutin display: Error { raw_code: None, raw_os_message: None, kind: NotFound }', /home/annaaurora/.cargo/registry/src/github.com-1ecc6299db9ec823/eframe-0.20.0/src/native/run.rs:355:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
and with `wgpu` there's errors too. I can't get it to work,

**To Reproduce**
1. `cargo run`

**Expected behavior**
A window of the app opens.

**Desktop (please complete the following information):**
 - OS: NixOS 23.05.20221203.61a8a98
 - Browser: Brave Browser
 - Version 105.1.43.89

**Comment by IvarWithoutBones** [comment]
I had the same problem on my NixOS machine, it occurs when `$LD_LIBRARY_PATH` does not contain the right packages. I was able to fix this with the following `flake.nix`:

```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    { self
    , nixpkgs
    , flake-utils
    }:
    flake-utils.lib.eachDefaultSystem (system:
    let
      pkgs = import nixpkgs { inherit system; };
    in
    {
      devShells.default = pkgs.mkShell rec {
        nativeBuildInputs = with pkgs; [
          cmake
          pkg-config
        ];

        buildInputs = with pkgs; [
          xorg.libX11
          xorg.libXrandr
          xorg.libXcursor
          xorg.libXi
          libxkbcommon
          libGL
          fontconfig
          wayland
        ];

        LD_LIBRARY_PATH = nixpkgs.lib.makeLibraryPath buildInputs;
      };
    });
}
```
With that you can enter a development shell using `nix develop` or automatically with `nix-direnv`, from which the binaries should start just fine. The error message is a bit unfortunate, hopefully that can be improved in the future.

**Comment by coderedart** [comment]
nix + egui had this problem in the past too. https://github.com/emilk/egui/discussions/1587

**Comment by auroraanna** [comment]
Thanks, 't works now.
