### ISSUE TITLE
cannot change widget background color

### ISSUE THREAD

**Issue by archsolar** [emilk/egui#2496]
This code is supposed to change the background color of a window widget to TRANSPARENT but it does not work.
```rs
fn ui(world: &mut World, _cx: EditorWindowContext, ui: &mut egui::Ui) {
        ...
        ui.visuals_mut().override_text_color = Some(egui::Color32::GREEN);
        ui.visuals_mut().window_fill = egui::Color32::TRANSPARENT;
        ui.visuals_mut().panel_fill = egui::Color32::TRANSPARENT;
        ...
    }
```

**Comment by archsolar** [comment]
finally found it had to tweak the window itself

``window.frame(egui::Frame{fill:egui::Color32::TRANSPARENT, ..Default::default()});``

**Comment by DavidZemon** [comment]
Where did you get the `window` object? I'm running an eframe app and not seeing that passed into any of the functions that I'm working with.
