### ISSUE TITLE
example programs doesn't run, None of them works.

### ISSUE THREAD

**Issue by SujithChristopher** [emilk/egui#2497]
I'm currently using rust 1.66

While compiling example programs from this repo

all folder shows the same error, as given below.

C:\Users\Sujith\Documents\Projects\rust_projects\egui\egui\examples\retained_image>cargo run
warning: C:\Users\Sujith\Documents\Projects\rust_projects\egui\egui\crates\eframe\Cargo.toml: unused manifest key: target.cfg(not(target_arch = "wasm32")).dependencies.glutin.es
   Compiling proc-macro2 v1.0.47
   Compiling unicode-ident v1.0.5
   Compiling quote v1.0.21
   Compiling cfg-if v1.0.0
error: `-Csplit-debuginfo=unpacked` is unstable on this platform

error: could not compile `proc-macro2` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `unicode-ident` due to previous error
error: could not compile `quote` due to previous error
error: could not compile `cfg-if` due to previous error

I'm new to rust, so please tell me if I have made any mistake or something I've to follow to get the example programs running.

**Comment by Mingun** [comment]
Try to run `cargo clean` in your working copy or just remove the `target` folder. I've also encountered some strange errors in my project when I upgraded to Rust 1.66, probably because the format of the incremental compilation cache was changed.

**Comment by SujithChristopher** [comment]
Sorry for the delayed reply @Mingun , I have tried that, the results remain the same. Maybe I should try with other versions of Rust, and see if that helps.

**Comment by kkoski** [comment]
you might try commenting out line 30 in the top level Cargo.toml file. see https://github.com/rust-lang/rust/issues/103976.

**Comment by SujithChristopher** [comment]
Thanks @kkoski, It works after commenting line 30.

**Comment by kkoski** [comment]
i missed this existing issue yesterday: https://github.com/emilk/egui/issues/2368
