### ISSUE TITLE
`epi` module is private

### ISSUE THREAD

**Issue by robertpauson** [emilk/egui#2500]
The example way failed at importing `epi`:
(https://github.com/emilk/egui/blob/0.17.0/eframe/examples/custom_font.rs`)
```
error[E0603]: module `epi` is private
  --> src/main.rs:28:5
   |
28 |     epi,
   |     ^^^ private module
   |
```
Latest epi version is `0.17.0` which is quite behind egui and eframe: https://docs.rs/epi/latest/epi/
Upon clicking the "Repository" from dropdown menu, I encountered 404 error.

How can we load custom fonts?

**Comment by metkm** [comment]
It looks like you already got your answer [here](https://www.reddit.com/r/rust/comments/zslfoe/comment/j18htwx/?utm_source=share&utm_medium=web2x&context=3). 
You can close this issue
