### ISSUE TITLE
The main window is not centered correctly when the scale factor is not 1.

### ISSUE THREAD

**Issue by zhatuokun** [emilk/egui#2513]
**Describe the bug**
The main window is not centered correctly when the scale factor is not 1(my default 1.25).

**To Reproduce**
1. `cargo new example`
2. add `eframe = "0.20.0"`
3. run the following code

```rs
fn main() {
    eframe::run_native(
        "app_name",
        eframe::NativeOptions {
            centered: true,
            initial_window_size: Some(eframe::egui::vec2(960.0, 670.0)),
            ..Default::default()
        },
        Box::new(|_| Box::new(Application::default())),
    );
}

#[derive(Default)]
struct Application;

impl eframe::App for Application {
    fn update(&mut self, ctx: &eframe::egui::Context, _frame: &mut eframe::Frame) {
        eframe::egui::CentralPanel::default().show(ctx, |ui| {
            ui.heading("Hello World");
        });
    }
}
```

**Expected behavior**
The window is centered correctly.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version: 21H2

**Comment by emilk** [comment]
Did https://github.com/emilk/egui/pull/2651 solve this?

**Comment by zhatuokun** [comment]
> Did #2651 solve this?

No, same issue. The position difference is even greater.

One solution is to use `winit::dpi::PhysicalPosition`, but multiply `inner_size` by `monitor.scale_factor ()` in the calculation of X and Y position.

I'm not sure if there is a better way.

**Comment by zhatuokun** [comment]
This issue has been fixed on the latest branch.
