### ISSUE TITLE
egui_demo_app doesn't compile to WASM without modification.

### ISSUE THREAD

**Issue by danec020** [emilk/egui#2522]
I was trying to build the demo app as a WASM module but due to the lack of documentation I was unable to build the wasm module. I can run the wasm module you provided but I can not rebuild it from scratch.

I have tried several things from searching the comments but in the end I can not find the magic combination to get it to work. I think this project would benefit from an example that shows how you built your web demo. I realize the main function is for native compilation, but when using the target wasm32-unknown-unknown there is no override function for the build process, so it errors on main.rs. 

I've tried to make sure I have researched through your documents but I am at a loss. I have some experience with WASM but not with rust. Maybe this is my fault and there is some entry point I need to set?

**Comment by kkoski** [comment]
does `sh/build_demo_web.sh` not work for you?

**Comment by danec020** [comment]
If I delete the "egui_demo_app_bg.wasm",  it doesn't get rebuilt with the script. I have been able to make it build by creating my own main function for the wasm build target but when loaded to the server it throws an error. I am how ever able to build a wasm eframe project quite easily. But I was hoping to build the entire demo scene for better learning but I have spent several hours to no success despite compiling a wasm module. All the hooks seem correct but maybe I am missing something.

**Comment by danec020** [comment]
Well I was finally able to get the demo version compiling to wasm and loading it properly. It definitely took some time to understand the process but it was a good learning experience.

**Comment by danec020** [comment]
So it was bothering me why the script didn't work and I can not see where the problem was.

```
# Get the output directory (in the workspace it is in another location)
TARGET=`cargo metadata --format-version=1 | jq --raw-output .target_directory`
```
This line fails to get the target and because of this the WASM_PATH is not set correctly and the wasm-bindgen command doesn't get executed. Do you want me to leave this open so you can try to figure out why it failed or would you like me to close this?

**Comment by kkoski** [comment]
what's the output of that command if you execute it in a terminal? it's `/Users/kkoski/git/egui/target` for me.

**Comment by danec020** [comment]
I am on a windows machine so the error I get is for the "jq"

```
jq : The term 'jq' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:37
+ cargo metadata --format-version=1 | jq --raw-output .target_directory
+                                     ~~
    + CategoryInfo          : ObjectNotFound: (jq:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by kkoski** [comment]
ah, there is a Windows version: https://stedolan.github.io/jq/download/

**Comment by danec020** [comment]
Ok, yeah I never heard of jq so didn't realize it was something to install. I will close the issue as it seems like mostly this was due to my lack of experience. I apologize for creating the issue.

**Comment by coderedart** [comment]
is jq necessary to build egui demo app? then, we might want to keep this issue open until it is documented somewhere.

**Comment by kkoski** [comment]
yep, see https://github.com/emilk/egui/blob/master/crates/egui_demo_app/README.md?plain=1#L12 and https://github.com/emilk/egui/blob/master/sh/build_demo_web.sh#L65
