### ISSUE TITLE
File uploading widget

### ISSUE THREAD

**Issue by kirkylesich** [emilk/egui#254]
**Is your feature request related to a problem? Please describe.**

We need file uploading widget

**Comment by emilk** [comment]
Is this for `egui_web`, i.e. "select a file to upload" (like in https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_fileupload_files)?

**Comment by kirkylesich** [comment]
> Is this for `egui_web`, i.e. "select a file to upload" (like in https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_fileupload_files)?

Yes

**Comment by emilk** [comment]
I'm closing this in favor of the broader issue https://github.com/emilk/egui/issues/270
