### ISSUE TITLE
Clamped integer DragValue with the range 0.0..=1.0 can not be dragged to 1 with the mouse

### ISSUE THREAD

**Issue by sphereflow** [emilk/egui#256]
**Describe the bug**

An integer `DragValue` which is clamped to ` 0.0..=1.0` can not be dragged to `1` with the mouse.
However manually entering `1` with the keyboard does set the `DragValue` to `1`.

**To Reproduce**
1. Add a variable `unsigned_int: u64,` to the `WidgetGallery` struct in the demo app.
2. Set it to `0` on struct initialization.
3. Add the following code to the `gallery_grid_contents` function:
```rust
ui.add(doc_link_label("DragValue u64", "DragValue"));
        ui.add(
            egui::DragValue::u64(unsigned_int)
                .clamp_range(0.0..=1.0)
                .speed(1.0),
        );
ui.end_row();
```
4. Try to drag the value with the mouse.

**Expected behavior**

I should be able to drag the value with the mouse to `1`.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10 with Gnome on Wayland

**Additional context**

I have only tested this with usize and u64.
I can observe this behavior on master and egui 0.10. 
Debugging this yields the following:
In drag_value.rs on line 271 `emath::smart_aim::best_in_range_f64` is called with a `rounded_new_value` of `1.0`
and an `aim_value` of `1.0` and as a result sets `rounded_new_value` to `0.0`.
I think this is the source of the bug.
Currently as a workaround i set the `clamp_range` to `0.0..=(max + 0.1)` for integer values.

**Comment by emilk** [comment]
Thanks for the bug report!
