### ISSUE TITLE
Filterable/Seachable ComboBox

### ISSUE THREAD

**Issue by 7sDream** [emilk/egui#2575]
**Is your feature request related to a problem? Please describe.**

https://user-images.githubusercontent.com/7822577/211762157-bfb06c96-1296-4fa6-83c1-55aadb008e1b.mov

I try to add a text edit in combobox's popup ui to make it filterable, but the popup will be closed when I click the text edit, make it very hard to input any filter word. I can drag the mouse in text edit to make it not close, but I think this is not ideal.

**Describe the solution you'd like**

Maybe only when user select a value(SelectableLabel) in combo box will make it close?

**Describe alternatives you've considered**

Any workaround I can make a filterable combobox is good enough.

**Additional context**

<details>
<summary>My test code, if it helps: </summary>

```rust
#[derive(Debug, Default)]
struct App {
    filter: String,
    selected: String,
}

impl eframe::App for App {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {
            egui::ComboBox::from_id_source("id").selected_text(&self.selected).show_ui(ui, |ui| {
                ui.text_edit_singleline(&mut self.filter);
                for s in ["one", "two", "three", "fore", "five"]
                    .into_iter()
                    .filter(|s| s.contains(&self.filter))
                {
                    ui.selectable_value(&mut self.selected, s.to_string(), s);
                }
            });
        });
    }
}

fn main() {
    env_logger::init();

    let opt = eframe::NativeOptions {
        initial_window_size: Some([720.0, 480.0].into()),
        resizable: false,
        ..Default::default()
    };
    eframe::run_native("egui combo box filter test", opt, Box::new(|_cc| Box::<App>::default()));
}
```
</details>

**Comment by ItsEthra** [comment]
You can take a look at how I implemented it in [egui-dropdown](https://github.com/ItsEthra/egui-dropdown). Basically what you need is a `TextEdit` as main widget and draw popup with variants manually.

**Comment by 7sDream** [comment]
@ItsEthra `egui::popup_below_widget` is something I didn't know before, turns out it is exact what I need and works very well. Thank you for the great help!
