### ISSUE TITLE
epi::App name() string suppressing app popup & stuck in infinite loop

### ISSUE THREAD

**Issue by bayswaterpc** [emilk/egui#259]
**Describe the bug**
Egui window is suppressed due to the string used in the epi::App name() function on the original dev machine.  It was working on that machine for a while unitl the app was suppressed, I had to roll back 4 commits' of previously working code to figure out it was the app name change that was causing the issue.

```Rust    
impl epi::App for WarbossWaaghitApp {
fn name(&self) -> &str {
        //"Generals Chest" //causes the window to be suppressed on original dev machine
        "Generals Chesst" //any other string name is fine
    }
```

From my debugging it get's caught in an infite loop in glium event_loop.rs run_return()
- Stuck in 'main: loop {}
- line 220 runner.reset_runner() & repeat
```rust
if let Err(payload) = runner.take_panic_error() {
    runner.reset_runner();
    panic::resume_unwind(payload);
}
```

![image](https://user-images.githubusercontent.com/78702667/112763677-6cbb0780-8fd3-11eb-8e18-f3b4a2c4d5a7.png)

**Callstack**
```
winit::platform_impl::platform::event_loop::EventLoop<egui_glium::backend::RequestRepaintEvent>::run_return<egui_glium::backend::RequestRepaintEvent,closure-0>(closure-0) event_loop.rs:225
winit::platform_impl::platform::event_loop::EventLoop<egui_glium::backend::RequestRepaintEvent>::run<egui_glium::backend::RequestRepaintEvent,closure-0>(EventLoop<egui_glium::backend::RequestRepaintEvent>,closure-0) event_loop.rs:188
winit::event_loop::EventLoop<egui_glium::backend::RequestRepaintEvent>::run<egui_glium::backend::RequestRepaintEvent,closure-0>(EventLoop<egui_glium::backend::RequestRepaintEvent>,closure-0) event_loop.rs:154
egui_glium::backend::run(Box<App, alloc::alloc::Global>) backend.rs:214
eframe::run_native(Box<App, alloc::alloc::Global>) lib.rs:57
warboss_waaghit::main() main.rs:9
core::ops::function::FnOnce::call_once<fn(),tuple<>>(void (*)()) function.rs:227
std::sys_common::backtrace::__rust_begin_short_backtrace<fn(),tuple<>>(void (*)()) backtrace.rs:125
std::rt::lang_start::{{closure}}<tuple<>>(std::rt::lang_start::closure-0 *) rt.rs:66
std::rt::lang_start_internal() 0x00007ff79756e897
std::rt::lang_start<tuple<>>(void (*)(),long long,unsigned char **) rt.rs:65
main 0x00007ff7970b11a0
__scrt_common_main_seh() 0x00007ff797585e80
BaseThreadInitThunk 0x00007ffb3e067034
RtlUserThreadStart 0x00007ffb3e1a2651
```
**To Reproduce**
I can't reproduce the bug on my 2nd laptop, it appears to be associated with some local env state.
Source code for project can be found at [https://github.com/bayswaterpc/WarbossWaaghit](url)

**Expected behavior**
A working popup
![image](https://user-images.githubusercontent.com/78702667/112763710-9116e400-8fd3-11eb-8f2a-24e881a93515.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10

**Additional context**
- Issue occurs on single machine on rust nightly & rust stable
- I've tried deleting the target folder and rebuilding, 
- tried  deleting appdata 'warboss_waaghit' folder, 

**Request**
If anyone has any intution on what kind of state on this machine could be causing this would love to know, otherwise a heads up for others, be flexible on app name changes 🖌️

**Comment by emilk** [comment]
`eframe` uses the name of the app to persist the state at:

* Linux:   `/home/UserName/.config/appname`
* macOS:   `/Users/UserName/Library/Application Support/appname`
* Windows: `C:\Users\UserName\AppData\Roaming\appname`

If you clear that directory it should be fine.

Sorry for the inconvenience, I know this is a bit of a hidden "feature". There are some docs at https://docs.rs/epi/0.10.0/epi/trait.App.html#method.save

**Comment by bayswaterpc** [comment]
Oh, I was so close, just deleted an older named "C:\Users\UserName\AppData\Roaming\appname" because it had the name of the exe.  But that folder will be the App name and I'll be deleting that in the future with any goofy state related issues.  Thanks!
