### ISSUE TITLE
Is there any way force to disable ui animation transition?

### ISSUE THREAD

**Issue by lencil** [emilk/egui#2601]
I'm working on a cpu based soft render backend of egui, is there any way to disable ui animation to improve ui operation experience for 
the soft render low fps.

**Comment by parasyte** [comment]
Does setting `animation_time` to 0.0 on `Style` work? https://docs.rs/egui/latest/egui/style/struct.Style.html#structfield.animation_time

**Comment by lencil** [comment]
setting animation_time to 0.0 works fine.

**Comment by MrBeanCpp** [comment]
@lencil I have the same question, can you tell me how to do it specifically? I have tried the following solution, but it's not work:
```rust
ctx.clear_animations();
ctx.all_styles_mut(|s| s.animation_time = 0.0);
```

**Comment by parasyte** [comment]
I don't know what doesn't work about it. Does it panic? Do animations continue playing regardless? Does it steal your lunch money? Perhaps more specific details about what "doesn't work" would be helpful.

FWIW, it looks like 78a93f81f07f2a893d86449f408276db96c02b59 broke `animation_time == 0.0` for bools. This change causes a divide-by-zero to occur.

**Comment by MrBeanCpp** [comment]
@parasyte Sorry, I found that windows created through the following way have transition animations (scaling) when displayed and hidden. I hope to remove it (show in one frame), but after setting `animation_time`, there is no change.

```rust
ctx.show_viewport_immediate(
                egui::ViewportId::from_hash_of("screenshot_viewport"),
                viewport,
                |ctx, class| {
                    egui::CentralPanel::default()
                        .frame(egui::Frame::none())
                        .show(ctx, |ui| {
                        ...
```

**Comment by parasyte** [comment]
I dug around a bit. `show_viewport_immediate` just directly uses `winit` to create the window. It doesn't do anything fancy. Any window opening animations are the responsibility of your window manager.

On Windows 11, there is a notable positional animation when opening the child window. Meanwhile on macOS there is no animation at all.

You can turn it off in your Windows settings under Accessibility -> Visual Effects. Then it behaves the same way as on macOS. There might be a way to disable it per-application with the [`windows` crate](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/Animation/struct.IUIAnimationManager.html#method.SetAnimationMode), but it's `unsafe` and I honestly have no idea how to use it...

**Comment by MrBeanCpp** [comment]
Thank you for your patience. I also tried `winit` and it was indeed as you said.🥲
