### ISSUE TITLE
How to sort a column in a table

### ISSUE THREAD

**Issue by 247gzs** [emilk/egui#2640]
@emilk 
I created a table that needs to sort the data according to different columns. Is there any available method to implement it?

**Comment by 247gzs** [comment]
I have solved this problem and share it with you

```rust
for header_name in ctx::OrderField::VALUES.iter() {
    header.col(|ui| {
        // when the text content is clicked, record the clicked fields and sort them later
        if ui.add(Label::new(set_font_style(format!("{}", header_name), 18f32, Color32::LIGHT_BLUE)).sense(Sense::click())).clicked() {
            order_field.lock().unwrap().replace(header_name.clone());
            {
                let v = *sequence.lock().unwrap();
                let mut s = sequence.lock().unwrap();
                *s = !v;
            }
        }
    });
}
```

**Comment by qqke** [comment]
> ```rust
> for header_name in ctx::OrderField::VALUES.iter() {
>     header.col(|ui| {
>         // when the text content is clicked, record the clicked fields and sort them later
>         if ui.add(Label::new(set_font_style(format!("{}", header_name), 18f32, Color32::LIGHT_BLUE)).sense(Sense::click())).clicked() {
>             order_field.lock().unwrap().replace(header_name.clone());
>             {
>                 let v = *sequence.lock().unwrap();
>                 let mut s = sequence.lock().unwrap();
>                 *s = !v;
>             }
>         }
>     });
> }
> ```
Can you shou the full source,except function of set_font_style?

**Comment by 247gzs** [comment]
@qqke that‘s all,I hope it can help you!

```rust
pub fn set_font_style(text: String, size: f32, color: Color32) -> RichText {
    RichText::from(text).size(size).color(color)
}
```

```rust
#[derive(serde::Deserialize, serde::Serialize, Debug, Clone)]
pub enum OrderField {
	A,
	B,
	C,
	D
}

impl OrderField {
    pub const VALUES: [Self; 7] = [Self::A, Self::B, Self::C, Self::D];
}
```

```rust
// record the fields used for sorting
order_field: Arc<Mutex<Option<ctx::OrderField>>>

// record ascending or descending order
sequence: Arc<Mutex<bool>>
```
