### ISSUE TITLE
is there a current example for using egui-wgpu + winit?

### ISSUE THREAD

**Issue by 0xDEADFED5** [emilk/egui#2646]
just wondering if there's a current example showing best practices for using egui-wgpu + winit?

https://github.com/hasenbanck/egui_example is pretty different

**Comment by Tomobodo** [comment]
Would be cool to update it with updated dependencies, i'm trying to make it work but I'm getting stuck with the renderer replacing the renderpass, I don't know how to get the texture ID it asks in the update_texture function.

**Comment by emilk** [comment]
No, there is not. PRs welcome!
