### ISSUE TITLE
Default multisampling value causes performance issues on M1 Macs.

### ISSUE THREAD

**Issue by JosephCatrambone** [emilk/egui#2658]
Quick disclosure: credit to finding the root cause of this issue is deserved by Perl#0420 on Discord.

When running some basic copy/pasted examples, it looks like egui struggles to break 3FPS in release mode.  This comes down to the value of 'multisampling' in the NativeOptions setup.  This does not apply to web examples.

This code has an average FPS of 3 on my 2021 M1 Max:

```
	eframe::NativeOptions {
		initial_window_size: Some(egui::vec2(1280.0, 720.0)),
		multisampling: 8,
		renderer: eframe::Renderer::Glow,
		depth_buffer: 24,
		..Default::default()
	}
```

While this can easily break 90FPS:
```
	eframe::NativeOptions {
		initial_window_size: Some(egui::vec2(1280.0, 720.0)),
		multisampling: 4,
		renderer: eframe::Renderer::Glow,
		depth_buffer: 24,
		..Default::default()
	}
```

It might make sense to change multisampling to 2 or 4 for the default examples.

**Comment by emilk** [comment]
Good catch!
