### ISSUE TITLE
Context::request_repaint_after doesn't repaint unless the mouse is moving

### ISSUE THREAD

**Issue by ShayBox** [emilk/egui#2674]
I need to display constantly changing information, I tried `Context::request_repaint_after` but the labels only update when the mouse is moving, inside or outside the window, focused or unfocused.

**Comment by emilk** [comment]
Using `eframe`? On what OS?

**Comment by ShayBox** [comment]
I'm using eframe, the eframe template, on the desktop (windows)

**Comment by ShayBox** [comment]
Here's a video of the problem, this is a big problem for my program, it displays constantly changing information but if the screen doesn't change when the mouse isn't moving or the mouse isn't over the window when it's unfocused, the program will be useless.

https://user-images.githubusercontent.com/9505196/221392892-33febdfc-6253-40bb-ae61-4e77d94d6600.mp4
