### ISSUE TITLE
Color picker is not standard

### ISSUE THREAD

**Issue by oredaze** [emilk/egui#2681]
In most graphics software like Photoshop you will see the color picker be like the right side. When you flip the colors like this it gets confusing for me and probably for a lot of other people. Please consider changing it.
Also the color selection circle is very huge. I don't know about that...

![picker](https://user-images.githubusercontent.com/51076873/216842936-3b8ba459-1caf-4171-abf4-df8d235015c9.png)

**Comment by robertpauson** [comment]
it opens right bottom and so on mobile it won't be accessible if the button is let's say also near the bottom. 

parts of the widget are inaccessible and the picker can't be moved. 

to fix that I had to modify repo with the line that defaults and kinda anchors it, so that it opened elsewhere and was movable

**Comment by oredaze** [comment]
Perhaps I am misunderstanding what you are saying, or it's the other way around, but I am talking about the colors inside the picker, not it's position. Notice how the white corner is bottom-right, but the standard is top-left.

**Comment by Mingun** [comment]
Not sure that this is the rule. [Shutter](https://github.com/shutter-project/shutter) uses egui layout:
![Shutter color selection](https://user-images.githubusercontent.com/450131/216908381-57b92802-b6a5-44d7-86ab-6838429eebeb.png)

**Comment by oredaze** [comment]
It's not a rule of course, it's just the most common way of doing it. Things that use my suggestion include: Photoshop; Krita; plugins for the aforementioned; Blender; Procreate; Artstudio pro; Rebelle; Painttool Sai; Clip Studio Paint; google search color picker; etc...

**Comment by emilk** [comment]
I'm for going with the majority here - should be an easy PR if anyone wants to tackle it!

**Comment by IVAN-MK7** [comment]
Accomplished by [swapping hsva's saturation and value](/emilk/egui/compare/master...IVAN-MK7:egui:hsva_color_slider_2d_orientation) in the color_slider_2d in my [fork's hsva_color_slider_2d_orientation branch](/IVAN-MK7/egui/tree/hsva_color_slider_2d_orientation)

![image](https://user-images.githubusercontent.com/68190772/218322895-c373cee8-1874-4b34-9c0c-a6afe5d766c3.png)
