### ISSUE TITLE
Some widgets keep expanding due to non-integral pixels_per_point

### ISSUE THREAD

**Issue by hasenbanck** [emilk/egui#27]
Hi,

While testing the WGPU render backend and Winit platform crates I created, I get following odd error:

![grafik](https://user-images.githubusercontent.com/12084860/95740987-c29e2c00-0c8d-11eb-957b-b1901ce025be.png)

Some elments keep expanding once they are visible. In the screenshot you can see that the drawing area of the painting widget expands and keeps expanding. If you scroll down until the end of the drawing area is visible, the expanding will stop.

Anothe example:
![grafik](https://user-images.githubusercontent.com/12084860/95741107-fbd69c00-0c8d-11eb-9027-530df96df706.png)

Do you maybe know where I could start debugging this? I have a hard time figuring out how the backend or the windowing integration could cause this behavior.

The code for reproducing this problem can be found here can be found in [this example project](https://github.com/hasenbanck/egui_example).

**Comment by emilk** [comment]
I've had those bugs before, but fixed them, so weird seeing them pop up again! Interestingly, when I run your code it all works as expected.

What is the `pixels_per_point` (`window.scale_factor()`) on your system when you run your example? Maybe Egui has a rounding error for when `pixels_per_point` is non-integral.

Does `demo_glium` work as expected? How about https://emilk.github.io/egui/ ?

**Comment by hasenbanck** [comment]
I have run my desktop in 4k with 150% scale. So `pixels_per_point` is 1.5.

I can reproduce the same error with the glium backend, but it only triggers when I move the mouse, since the application doesn't run unlimited (ControlFlow::Poll) and waits for events (ControlFlow::Wait).

**Comment by emilk** [comment]
Then it is probably a bug for me to fix in Egui. I'll try to get to it some time this week (or more likely: weekend)
