### ISSUE TITLE
Custom fonts have vertical offset with unicode symbols

### ISSUE THREAD

**Issue by woelper** [emilk/egui#2700]
Egui default font with `0.21`:

![image](https://user-images.githubusercontent.com/3613791/217669500-baa5e755-65ab-4836-bd0b-6679905a45cf.png)

Noto sans with `0.19`:
![image](https://user-images.githubusercontent.com/3613791/217669720-bb3e6962-f501-4662-94fa-3a20402bc3b8.png)

Noto sans with `0.21`:
![image](https://user-images.githubusercontent.com/3613791/217669933-c791da0d-a4a9-4e6a-a287-e8dbad22eee5.png)

Although a bit hard to see, all symbols are offset in the y direction. I tried different fonts such as IBM plex, and they show this as well.

**Describe the bug**
Symbols are not vertically aligned with text if using a custom font.

**To Reproduce**
```rust
pub fn new(cc: &eframe::CreationContext<'_>) -> Self {
    let mut fonts = FontDefinitions::default();
    fonts.font_data.insert(
        "my_font".to_owned(),
        FontData::from_static(include_bytes!("../res/fonts/NotoSans-Regular.ttf")),
        // FontData::from_static(include_bytes!("../res/fonts/IBMPlexSans-Regular.ttf")),
    );
    fonts
        .families
        .get_mut(&FontFamily::Proportional)
        .unwrap()
        .insert(0, "my_font".to_owned());
    cc.egui_ctx.set_fonts(fonts);
    Default::default()
}
```

**Comment by woelper** [comment]
Actually after reading [your post](https://twitter.com/ernerfeldt/status/1621216119955619841) and trying `Inter` (which worked and is vertically aligned with symbols) I am not so sure any more if I just picked the wrong fonts. Noto and Plex are pretty common though and I wonder what they do differently.

**Comment by emilk** [comment]
There may be a "vertical offset" font attribute that egui ignores, and shouldn't. In any case, you can tweak the y-offset when you load your fonts using https://docs.rs/egui/latest/egui/struct.FontData.html#method.tweak

**Comment by aevyrie** [comment]
I've run into this using `Roboto`, and had to add a manual y offset in the font tweaks. Issue found when upgrading to `v0.20`.
