### ISSUE TITLE
Sub Context menu hover disappears

### ISSUE THREAD

**Issue by lampsitter** [emilk/egui#2704]
**Describe the bug**
When hovering over a sub context menu the highlighting appears for one frame and then disappears.

**Expected behavior**
Hovered over button remains highlighted for more than the first frame.

**Screenshots**
Old behaviour:
![egui_bug_old](https://user-images.githubusercontent.com/96946613/217887057-f1d4c301-b5f3-41a7-b674-ac5fc92b879d.png)

Current:
![egui_bug_new](https://user-images.githubusercontent.com/96946613/217887048-d8d3621d-505a-411d-ad9d-550d22fae61a.png)

**Additional context**
Seems like it was introduced in: #2621. Notably this line: 
https://github.com/emilk/egui/blob/ce67d7345e8c2177068e75875e1ddaecdbbefdfa/crates/egui/src/menu.rs#L446

**Comment by xyning** [comment]
its a dark style issue, works fine under light mode..

dark `open` style is wrongly set to be same as `noninteractive`, and should use `hovered` values instead
https://github.com/emilk/egui/blob/1581f0229ec3d7946b2a1f680defc28880e5ce9e/crates/egui/src/style.rs#L869-L870

**Comment by lampsitter** [comment]
Looks like this behaves properly again in 0.25
