### ISSUE TITLE
Proposed DragValue improvement

### ISSUE THREAD

**Issue by DrOptix** [emilk/egui#273]
**Is your feature request related to a problem? Please describe.**
At the moment drag values are good, but I believe we can make them better. I'm ready to work on this one.
@emilk if you give me the go ahead I can start working on it or part of it depending on what you think will be good for **egui**.

**Describe the solution you'd like**
I would like to propose an implementation similar with the ones from Blender.

You can see more in the GIF below, but the key improvements are in order of priority:

- [x] On hover display ResizeHorizontal cursor
- [x] When `shift` is pressed and we drag we add or subtract `DragValue::speed()` / 10
- [x] While dragging display ResizeHorizontal.
- [ ] ~Add arrows to increase or decrease value, maybe display them only on hover~
- [ ] ~When arrows are clicked we add or subtract the amount equal to the value set by `DragValue::speed()`~
- [ ] ~When `shift` is pressed and we click on the arrows we add or subtract `DragValue::speed()` / 10~
- [ ] ~When we start dragging save cursor position, hide the cursor while dragging, when dragging is done display the cursor at the saved location~

**Describe alternatives you've considered**
Nothing here as my focus is to do my best to help improve **egui**

**Additional context**
How Blender does it.
![blender_drag_value](https://user-images.githubusercontent.com/512152/113479484-113bbe80-9498-11eb-940e-9e963d93d746.gif)

**Comment by emilk** [comment]
I think this all sounds great! I would like to keep the compactness of the current values, but maybe adding room for thin arrows is fine. I definitely thing they should be hidden until hovered, like in your gif.

**Comment by DrOptix** [comment]
Great. I will will start working on this then.

**Comment by DrOptix** [comment]
This one:
> When we start dragging save cursor position, hide the cursor while dragging, when dragging is done display the cursor at the saved location

I think I will skip it. I mean for desktop it is easy, but to support it on web I think it will be an ugly hack. From my research the mouse API for web gives us, mouse movement, clicks, wheel and mouse locking, but no positioning ability. Also from my brief examination of `web_sys` it seems that pointer lock API is not exposed, but again I might be wrong. I will move this as the last potential item to implement.

**Comment by DrOptix** [comment]
Bummer. I can't figure out how to add the arrows only on hover. I tried a few things, but both the UI and the code were ugly. I'll keep a bit at it.

**Comment by DrOptix** [comment]
@emilk For the moment I need to stop on this, but rather than giving up everything I propose those 3 implemented features.

- On hover display ResizeHorizontal cursor
- When shift is pressed and we drag we add or subtract DragValue::speed() / 10
- While dragging display ResizeHorizontal.

Link to PR: https://github.com/emilk/egui/pull/274
