### ISSUE TITLE
Rive animation support

### ISSUE THREAD

**Issue by soundprojects** [emilk/egui#2736]
So this is probably a bit ‘out there’ or at least very long term but would you be interested if Egui would support the viewing of Rive animations?

[Rive Website](https://rive.app/) 

particularly because of the State Machine structure this might be nice as an animation backend within Egui? They have a great online editor which would detach the design part of the code.

they already have a WASM library but that seems to interface with SKIA

**Comment by coderedart** [comment]
doesn't seem to have rust support. https://help.rive.app/runtimes/overview

**Comment by emilk** [comment]
This seems like something that should be built on top of egui, not deeply integrated into it
