### ISSUE TITLE
Add support for custom `line_height` and `letter_spacing`

### ISSUE THREAD

**Issue by mikedilger** [emilk/egui#2738]
I'm considering working on a PR and want feedback first.

I'd like to be able to follow the "visual design rules" on this site https://anthonyhobday.com/sideprojects/saferules/
specifically this PR would allow users to "lower letter spacing and line height with larger text. Raise them with smaller text" as shown in this image https://anthonyhobday.com/sideprojects/saferules/images/6.png

For this I'm suggesting `row_height` and `character_spacing` fields within epaint::TextFormat.

`row_height` would be a multiplier on `glyph.size.y` within `text_layout.rs` and `character_spacing` a multiplier on `advance_width`.

Users would have to manually set these; I'm not suggesting we automatically do anything differently from now.

**Comment by abey79** [comment]
Piggy-backing on this existing issue, I suggest following as closely CSS naming/behaviour as possible.

- `line_height`: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height
- `letter_spacing`: https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing

cc @martenbjork
