### ISSUE TITLE
Demo keyboard input "p" not working

### ISSUE THREAD

**Issue by jiricodes** [emilk/egui#2739]
# Short Description
In the deployed [egui demo](https://www.egui.rs/) the character `p` is being ignored in some TextEdit fields.

# Expected behaviour
Press `P` on keyboard and a `p` character appears in selected editable field.
Press `Shift + P` on keyboard and a `P` character appears in selected editable field.

# Observed behaviour
The keyboard input `P` is ignored in following fields:

- Demos
    - [Code Editor](https://github.com/emilk/egui/blob/38849fe3816d24538e200c4dc62854e38cb47a09/crates/egui_demo_lib/src/demo/code_editor.rs#L87)
    - [Code Example](https://github.com/emilk/egui/blob/38849fe3816d24538e200c4dc62854e38cb47a09/crates/egui_demo_lib/src/demo/code_example.rs#L34)
    - [Font Book](https://github.com/emilk/egui/blob/38849fe3816d24538e200c4dc62854e38cb47a09/crates/egui_demo_lib/src/demo/font_book.rs#L62)
    -  Misc Demos - [password](https://github.com/emilk/egui/blob/38849fe3816d24538e200c4dc62854e38cb47a09/crates/egui_demo_lib/src/demo/password.rs#L41)
        - [ Desktop ] works as expected until visibility is toggled on or off
            - gets fixed by selecting all the text and deleting it
            - one by one character deletion doesn't fix
    - [TextEdit](https://github.com/emilk/egui/blob/38849fe3816d24538e200c4dc62854e38cb47a09/crates/egui_demo_lib/src/demo/text_edit.rs#L44)
        - [ Desktop ] - buttons [*start*](https://github.com/emilk/egui/blob/38849fe3816d24538e200c4dc62854e38cb47a09/crates/egui_demo_lib/src/demo/text_edit.rs#L87) and [*end*](https://github.com/emilk/egui/blob/38849fe3816d24538e200c4dc62854e38cb47a09/crates/egui_demo_lib/src/demo/text_edit.rs#L97) seems to fix things, making the 'P' key being registered as expected. Until the cursor is moved manually. (maybe a hint towards the root cause?)
    - [Window Options](https://github.com/emilk/egui/blob/38849fe3816d24538e200c4dc62854e38cb47a09/crates/egui_demo_lib/src/demo/window_options.rs#L92)
- [EasyMark](https://github.com/emilk/egui/blob/38849fe3816d24538e200c4dc62854e38cb47a09/crates/egui_demo_lib/src/easy_mark/easy_mark_editor.rs#L94)

These fields work as expected:
- [HTTP](https://github.com/emilk/egui/blob/38849fe3816d24538e200c4dc62854e38cb47a09/crates/egui_demo_app/src/apps/http_app.rs#L117)

Note of inconsistency - when testing, spamming key `p` while changing TextEdit field selection resulted in registering the character occasionally in either of the fields (sometimes in the just selected and sometime in the just deselected)

Native build of `egui_demo_app` (master branch) locally works fine.

# Tested Platforms

- Desktop: Ubuntu 22.04.1 LTS
    - Chrome (Version 110.0.5481.77 (Official Build) (64-bit))
    - Firefox (109.0.1 (64-bit))ppp
- Mobile: iOS 16.2
    -  Safari
    - Chrome

**Comment by YgorSouza** [comment]
Apparently the reason is this:

https://github.com/emilk/egui/blob/38849fe3816d24538e200c4dc62854e38cb47a09/crates/eframe/src/web/events.rs#L92-L97

This code should probably check for modifiers. For Windows and Linux it's Ctrl, and for macOS I guess it's Command? But I am not sure.

**Comment by emilk** [comment]
Oh wow, this is embarrassing 🤦 

Yes, should be a very easy fix to check for modifers when we ignore keys.

**Comment by emilk** [comment]
eframe 0.21.3 released with fix
