### ISSUE TITLE
Add hook to tap into window creation similar to EventLoopBuilder hook in eframe

### ISSUE THREAD

**Issue by twop** [emilk/egui#2747]
### Problem
I would love to customize appearance beyond what is available in `eframe::NativeOptions` (example below is on macOS).

Specifically I would love to achieve this look (top window, code snippet is taken from `winit`):
<img width="703" alt="image" src="https://user-images.githubusercontent.com/6633216/219827978-6fcd0bce-7721-41c1-a242-fc18ec56560f.png">

It is a combination of these `winit` settings:
```rs
    let event_loop = EventLoop::new();

    let window_1 = WindowBuilder::new()
        .with_titlebar_buttons_hidden(true)
        .with_title_hidden(true)
        .with_titlebar_transparent(true)
        .build(&event_loop);
```

Note that these methods are specific to macOS (defined in `WindowBuilderExtMacOS`).
The closest that `eframe` provides today is 
```rs
 eframe::NativeOptions {
        fullsize_content: true,
        decorated: false
}
```
But it removes the ability to resize and "roundness" of the window.

### Desired solution
I would love to to tap into `WindowBuilder` with a hook similar to `EventLoopBuilder`.
Something like that
```rs
let options = eframe::NativeOptions {
    // proposed API for window builder
    window_builder: Some(Box::new(|builder| {
        #[cfg(target_os = "macos")]
        {
            use winit::platform::macos::WindowBuilderExtMacOS;
            builder
                .with_titlebar_buttons_hidden(true)
                .with_title_hidden(true)
                .with_titlebar_transparent(true)
        }
    })),

    // existing hook for event loop
    event_loop_builder: Some(Box::new(|builder| {
        #[cfg(target_os = "macos")]
        {
            use winit::platform::macos::{ActivationPolicy, EventLoopBuilderExtMacOS};
            builder.with_activation_policy(ActivationPolicy::Accessory);
        }
    })),

    ..Default::default()
};
```

### Alternative
Mimic `winit` window builder API in `eframe::NativeOptions`. It feels less desirable to me because
1. There is already a precedent for `EventLoop` hook
2. It seems that `eframe::NativeOptions` is mostly 1:1 to `winit` options, thus it feels repetitive.
3. With little code in `eframe` this provides access to a lot of features, AND it is future proof, e.g. when `winit` adds features `eframe` gets these features for "free".

---
Happy to contribute the code

**Comment by twop** [comment]
I have a fork when it is implemented https://github.com/twop/egui/tree/focus-and-window-builder
Here is the gist:

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/6633216/235208541-3c556d7c-ac8b-43c4-9204-22d8bf8f90b0.png">
and here is the usage of it
<img width="819" alt="image" src="https://user-images.githubusercontent.com/6633216/235208631-b42a4cf9-35c1-4bed-a3f5-baa007e5e244.png">

Should I submit a PR?

**Comment by nanaian** [comment]
> Should I submit a PR?

Placing my hat in the ring for this - yes! Support would be greatly appreciated!

This would be a breaking change because `NativeOptions` isn't [marked exhaustive](https://rust-lang.github.io/rfcs/2008-non-exhaustive.html), the PR should probably mark it as such to make it non-breaking to add new options in the future.

**Comment by twop** [comment]
created a PR just in case https://github.com/emilk/egui/pull/3390
