### ISSUE TITLE
Add ability to focus window on native platforms in `eframe::Frame`

### ISSUE THREAD

**Issue by twop** [emilk/egui#2748]
**Is your feature request related to a problem? Please describe.**
I'm building a utility app that is shown/hidden from tray icon or by a global hotkey (to quickly capture notes). The intent is to show the window quickly with the focus already set on TextEdit, capture some text information (like pasting a link), and then go back.

The problem is that the window can be show by `Frame::set_visible(true)`, but not focused, thus requiring an extra click.

See the video, note the click to focus around 0:20 sec.
https://user-images.githubusercontent.com/6633216/219838554-4a0de3a9-fcda-4c6c-bdf1-8bb1472c20b6.mov

**Describe the solution you'd like**
I would love to have an API to ask for focus, the underlying API support already exists in `winit`
```rs
frame.focus_window(); // the same method exists in winit
```
snippet from window.rs in `winit`
<img width="821" alt="image" src="https://user-images.githubusercontent.com/6633216/219839524-ae401689-74e5-4f74-b139-770dbae4ae53.png">

Note that the api probably makes the most sense on desktop platforms, but in theory it can be supported on the web (focusing on canvas element).

**Describe alternatives you've considered**

I'm not sure if there is a way to achieve that any other way.
--- 
Happy to contribute the code

**Comment by emilk** [comment]
Closed by https://github.com/emilk/egui/pull/2900
