### ISSUE TITLE
Touch gesture support

### ISSUE THREAD

**Issue by emilk** [emilk/egui#279]
It would be great if `egui` could support pinch-to-zoom, multi-finger swipes and other touch gestures. For a start, the most important place to support it is the web (i.e. in `egui_web`).

(NOTE: full multi-touch support, e.g. dragging two sliders at once, is a separate issue).

I suggest we start by adding touch events to [`egui::Event`](https://docs.rs/egui/0.11.0/egui/enum.Event.html). Let's do something similar to `winit`:

``` rust
enum Event {
    …
    Touch(TouchEvent),
}

pub struct TouchId(pub u64);

struct TouchEvent {
    id: TouchId,
    pos: Pos2,
    phase: TouchPhase,
}

pub enum TouchPhase {
    Started,
    Moved,
    Ended,
    Cancelled,
}
```

`egui::InputState` can then keep track of the touches in a `HashMap<TouchId, Pos2>` and detect gestures. For instance, if there is exactly two touches then it could measure zoom, translation and rotation to support manipulating 2D surfaces. An egui application would then just do something like `self.zoom *= ui.input().zoom();` to update its zoom-state each frame.

**Comment by quadruple-output** [comment]
I plan to spend some time on it on the weekend 🚧
