### ISSUE TITLE
change egui canvas resize behavior to play nicer with other html content

### ISSUE THREAD

**Issue by samitbasu** [emilk/egui#2805]
**Is your feature request related to a problem? Please describe.**

When running the web target with `egui`, the `resize_canvas_to_screen_size` function
attempts to make the canvas a full screen.  In instances where you want HTML content
around the `egui` canvas, you can mostly work around this with some `css` and an
enclosing `<div>`.  However, the `resize` function uses the `parent` element's scroll height
and width.  This means that if you resize your window to make it smaller, the canvas
no longer tracks the size of the parent element.  And that means the `egui` canvas overpaints
the rest of the web page.

**Describe the solution you'd like**

I put on PR a simple replacement of `scroll_height` with `client_height` that seems to leave
the main demo (`egui_demo`) unaffected, but enables better behavior of the canvas when
the page is resized and the canvas does not take up the entire screen.

**Describe alternatives you've considered**

It might be better to add a flag to the `WebOption` struct so you can select the behavior
you want.  I could implement that instead if you think that's better.

**Additional context**

<img width="809" alt="Screenshot_20230312_225439" src="https://user-images.githubusercontent.com/5354222/224619037-5d475a8e-9182-4a0a-b752-f84ca90ed459.png">

In this screenshot you can see the header, body (rendered by egui) and the footer.   Now, I have made the window smaller, and the footer is now under the canvas.  This is because the scroll height of the containing `div` has not changed, while the `client height` has.

<img width="809" alt="Screenshot_20230312_225617" src="https://user-images.githubusercontent.com/5354222/224619270-d0284a96-45a1-4f5c-ac05-f6c1c55f5afc.png">

**Comment by Deadalusmask** [comment]
I'm having a similar issue when trying to integrate egui as part of a web page like this:
```ts
import('../../pkg')
  .then(m => {
    const canvas = document.createElement('canvas')
    canvas.width = 960
    canvas.height = 540
    canvas.id = 'app'
    document.body.appendChild(canvas)
    m.start('app')
  })
  .catch(console.error)
```
It appears that eframe is listening to `window.resize` event and automatically resizing the canvas during the render loop. It will be good if there is a way to stop this behavior and set canvas size manually.

**Comment by samitbasu** [comment]
@Deadalusmask - you may want to check out this [post](https://webgl2fundamentals.org/webgl/lessons/webgl-resizing-the-canvas.html).  I didn't appreciate how difficult canvas size issues were.  You can definitely put the `egui` app into an `iframe`, but that makes interaction with the rest of your webpage a larger issue.  I'll keep investigating.

**Comment by jsalort** [comment]
@samitbasu can you share which solution you eventually chose ? In particular, how do you set up the enclosing div and the css? I have tried to enclose the egui canvas in a div, and it initially shows up fine, but after interacting with the canvas (clicking on a button), the canvas moves to the top left corner instead...
