### ISSUE TITLE
`DragValue` edit is discarded when clicked off

### ISSUE THREAD

**Issue by Barugon** [emilk/egui#2818]
**Describe the bug**
If I click a `DragValue` and type in a new value then that new value is discarded if I click on another `DragValue` or `TextEdit`.

Video: https://youtube.com/shorts/_wxqB0XjkIY

**Comment by paul-hansen** [comment]
This is really annoying when you want to edit a list of values with the keyboard by tabbing through them. The only way to make the changes save is to hit the return key, which resets the tabbing state so you have to tab back to where you were from the start.

For example, I have this Ui:
![image](https://user-images.githubusercontent.com/7019130/227364697-ad4cbb3a-8919-4289-9884-a7317cbe03a4.png)

I would like to be able to select the first value, translation.x, type the new value, hit tab, type the next value, hit tab, etc. Currently that's not possible as it doesn't save the values you typed when you hit tab.

**Comment by Barugon** [comment]
I'm using the return key to mean "Ok" when displaying a dialog (standard OS behavior) so using it to enter a single value is not good.

**Comment by paul-hansen** [comment]
Looks like it was introduced in this commit: https://github.com/emilk/egui/commit/b40dba18c642fa959c4bad59fea99416a31f0825

Used git bisect and tested with the hello_world example to find the first commit where it wasn't working. The drag value created by the Slider in the example is affected so it made a good test since DragValue isn't used in the examples directly.

**Comment by Barugon** [comment]
The problem here seems to be that `Memory` doesn't see that the `TextEdit` has lost focus.

**Comment by Barugon** [comment]
Okay, I found the culprit. If you click on another `DragValue` or `TextEdit` then `Memory::stop_text_input` gets called, which sets the focus ID to `None`. This happens before [this check](https://github.com/emilk/egui/blob/eb0812a9530f77712bf77aad0956f932a3a8f23d/crates/egui/src/widgets/drag_value.rs#L382), so `is_kb_editing` is false, which essentially kills the edit session.

Clicking on other widgets (e.g. `Label`) does not call `TextEdit` then `Memory::stop_text_input`, which allows `Memory::surrender_focus` to be executed correctly, resulting in the correct behavior.

Simply commenting out [this line](https://github.com/emilk/egui/blob/eb0812a9530f77712bf77aad0956f932a3a8f23d/crates/egui/src/memory.rs#L456) fixes the issue but I don't know if there would be any other issues because of it.
@emilk

**Comment by Barugon** [comment]
Tabbing between `DragValue`s also disregards any edit.

**Comment by Barugon** [comment]
I honestly feel that #2688 is just too problematic and should be reverted.
