### ISSUE TITLE
Change `eframe::start_web` to take canvas name as owned string?

### ISSUE THREAD

**Issue by samitbasu** [emilk/egui#2822]
**Is your feature request related to a problem? Please describe.**

The current signature for `start_web` takes the name of the canvas element as a borrowed string.  Because that function call needs to be run on a `spawn_local`,
I think that means the name of the canvas element has to have a static lifetime.  This 
means you cannot (as far as I can tell) have two of the same GUIs running on the same
page but with different canvas targets.  

**Describe the solution you'd like**

The ideal situation would be to change `start_web` to take the name of the canvas as an
owned `String`.  However, this would be a breaking change.  An alternative would be
to make it generic and take the name of the canvas as an `AsRef<str>`, which would probably work with both cases?

**Describe alternatives you've considered**

The only workaround I came up with was to leak the canvas ID name, using something like:
```rust
#[wasm_bindgen]
pub fn start_my_gui(the_canvas_id: &str) {
   let the_canvas_id = Box::leak(Box::new(String::from(the_canvas_id)));
   // call spawn_local on eframe::start_web here...
}
```
This has the side effect of leaking the string, which is unfortunate.

**Additional context**

I am happy to make the change and put it on PR, but am not sure if there is a better/different way to solve this, and if there is a preference for how to deal with backward compatibility.

**Comment by emilk** [comment]
This has been implemented, and an example can be found in https://github.com/emilk/egui/blob/master/web_demo/multiple_apps.html
