### ISSUE TITLE
Egui almost certainly shouldn't be depending on android-activity

### ISSUE THREAD

**Issue by rib** [emilk/egui#2829]
This dependency on the "native-activity" feature for `android-activity` means that applications can't use Egui with the game-activity backend and it also locks Egui applications to a specific version of android-activity which is probably not necessary.

https://github.com/emilk/egui/blob/59c2c4c70d9e23b673b4cf6fcdfc030a91074d7e/crates/egui-winit/Cargo.toml#L76

Unlike most crates it's strictly never possible to have more than one version of android-activity linked into an application and so ideally very few crates should be directly depending on a specific version (increasing the chance of conflicts).

The android-activity crate is re-exported from Winit so that most crates can avoid needing to specify a direct dependency.

E.g. see:
https://github.com/rust-mobile/rust-android-examples/blob/41e72ca9de45e2add4776ec004f916ad979cf781/agdk-egui/src/lib.rs#L4

I can't see anything depending on the android_activity API though, so hopefully this can be removed.

**Comment by ardocrat** [comment]
I made PR to use android-activity as optional dependency cause their CI is requiring it: https://github.com/emilk/egui/pull/2834
