### ISSUE TITLE
eframe: Request window focus

### ISSUE THREAD

**Issue by philpax** [emilk/egui#2843]
**Is your feature request related to a problem? Please describe.**
I'm building an overlay that pops up (using `frame.set_visible`) on a hotkey with `eframe` and `egui`, and I'd like it to consistently focus the input widget. However, `Response::request_focus` does not appear to focus the widget the first time around.

I believe this is because the overlay window itself is not focused.

**Describe the solution you'd like**
`eframe::Frame::request_focus`, which requests the frame to be focused on platforms where it's supported.

I believe this would be relatively simple for the `winit` backend of `epi`: it should just be a call to [winit::Window::focus_window](https://docs.rs/winit/latest/winit/window/struct.Window.html#method.focus_window).

**Describe alternatives you've considered**
`Response::request_focus` could implicitly focus the window, but that may be unexpected behaviour (especially as it would likely break existing workflows)

**Additional context**
I'm happy to implement this myself and submit a PR, but I wanted to check that this would fit within the purview of `eframe` first.

**Comment by TicClick** [comment]
this has been added in https://github.com/emilk/egui/pull/2900, but not yet released under any tag
