### ISSUE TITLE
Docs still refer to custom_3d_three-d example

### ISSUE THREAD

**Issue by erooke** [emilk/egui#2844]
Two places in the docs/examples refer to the example `custom_3d_three-d` however this example was removed in 636a39cbe122ce91ea554920ee7aa4475d8f2de7.

https://github.com/emilk/egui/blob/089c7b46f37d76381eddf258de220cba08b8f126/examples/custom_3d_glow/README.md?plain=1#L5

https://github.com/emilk/egui/blob/089c7b46f37d76381eddf258de220cba08b8f126/README.md?plain=1#L348-L349
(the 3d_glow link happens to be dead too)

**Comment by emilk** [comment]
Closed by d7dcfe4dae8b734c9398ddceed83cf56ac6ef53c
