### ISSUE TITLE
TextEdit won't lost focus on mobile when user click elsewhere

### ISSUE THREAD

**Issue by n2** [emilk/egui#288]
**Describe the bug**
On mobile devices, TextEdit will not lose focus when the user clicks elsewhere.

**Smartphone (please complete the following information):**
safari@iOS14 && chrome@Android9

**Additional context**
This bug may be introduced from [this commit](https://github.com/emilk/egui/commit/def09c245513f3f1c9b848dca6244ba206ac291a), and [the previous commit](https://github.com/emilk/egui/commit/6fbb59de1f0097bfa973357354223383b1b456e7) just work fine.

**Comment by emilk** [comment]
Thanks for the report!
