### ISSUE TITLE
Wrong texture is bound when rendering

### ISSUE THREAD

**Issue by 1danielcoelho** [emilk/egui#29]
Hi!

I'm trying to integrate egui into a wasm-bindgen app that also needs to draw some other geometry. Basically my app tries to do the job of your `AppRunner` class also using `egui_web`, but also rendering other things, and doing other things with the input events, etc.

For some reason all my widgets end up looking like this though: 

![demo](https://user-images.githubusercontent.com/8158763/96760936-6931ad80-13af-11eb-8e79-ebda9117bd85.png)

If I use something like SpectorJS I can debug the draw call and see that drawElements is called with the font atlas texture bound to sampler 0, which is why the lines look strange: I think it's drawing them with the texture atlas bound? It is also likely the same thing that is preventing the actual text from showing. I wonder if you know what could be wrong, of if there's anything I'm missing?

Here is how I first setup the egui state:
```
let mut backend = egui_web::WebBackend::new("mycanvas").expect("Failed to make a web backend for egui");
let mut web_input: WebInput = Default::default();
```
And here is how I draw every frame:
```
ctx.clear_color(0.1, 0.1, 0.2, 1.0);
ctx.clear(GL::COLOR_BUFFER_BIT | GL::DEPTH_BUFFER_BIT);

let raw_input = web_input.new_frame();
let ui = backend.begin_frame(raw_input);

let mut s = String::from("test");
let mut value = 0.0;
egui::Window::new("Debug").show(&ui.ctx(), |ui| {
    ui.label(format!("Hello, world {}", 123));
    if ui.button("Save").clicked {
        log::info!("Save!");
    }
    ui.text_edit(&mut s);
    ui.add(egui::Slider::f32(&mut value, 0.0..=1.0).text("float"));
});

let (output, paint_jobs) = backend.end_frame().unwrap();
backend.paint(paint_jobs).expect("Failed to paint!");

ctx.viewport(
    0,
    0,
    canvas_width_on_screen as i32,
    canvas_height_on_screen as i32,
);

cube.render(
    &context,
    (js_sys::Date::now() - start_millis) as f32,
    curr_state.canvas_width,
    curr_state.canvas_height,
);
```

This should be working right? Or is there some magical step that `AppRunner` does that I overlooked?

Thanks!

**Comment by 1danielcoelho** [comment]
Check it out, if I provide a much higher `pixels_per_point` to web_input, we can get a better look at what it's trying to draw. 
![texture](https://user-images.githubusercontent.com/8158763/96770505-e6145580-13b6-11eb-8b7e-e1933900e90b.png)
I'm not quite sure what's going on here... it looks like it's only drawing half the triangles and with transparency? Or maybe it's actually using the texture atlas its just that it's very small and so only sampled a couple of times, and it looks like that?

**Comment by emilk** [comment]
Hello!

I don't think this is a texture issue. Egui only uses the texture for text, for all other primitives it sets the texture coordinates to zero (the Egui texture has a white pixel in the top left corner).

That all your primitives come out like this looks like backface culling. Try calling `gl.disable(Gl::CULL_FACE);` and see if that helps!

**Comment by 1danielcoelho** [comment]
Thanks, it really was culling! Once I disable it everything rendered perfectly. 

Since it relies on culling being disabled maybe you could add a call to disable it inside `paint_jobs`?

**Comment by emilk** [comment]
Good catch; thanks for the report!
