### ISSUE TITLE
Memory leak in egui

### ISSUE THREAD

**Issue by Wicpar** [emilk/egui#2909]
**Describe the bug**

A memory leak seems to keep the painter shapes in memory on native and wasm. Both wgpu and glow are affected. Latest version and Master.
It is not the Memory class. It is not other state. It likely is the renderer that does not consume the primitives properly and never drops them.
I even tested it in a previous project and it's there with only the demo windows, it uses egui-vulkano, so the issue is likely in egui itself.
I don't remember a memory leak last time i compiled that project...

**To Reproduce**
1. Create a new project with the eframe template
2. Add the demo windows
3. Request redraw every frame
4. Memory grows without bounds

**Expected behavior**
No memory leak

**Comment by Wicpar** [comment]
I checked the demo app and it doesn't leak...

**Comment by Wicpar** [comment]
i have a demo repo with a 100MB/s leak with a few elements. https://github.com/Wicpar/test_leak

**Comment by YgorSouza** [comment]
This demo has a lot of code, so it's hard to tell where the leak is coming from, or even if it is egui's fault at all. Maybe you could use something like [dhat](https://crates.io/crates/dhat) to narrow it down?

**Comment by Wicpar** [comment]
Good catch, with dhat i saw that the accrete library was setting weealloc as the global allocator, which does leak in that scenario, probably because it is unable to handle all the vec allocations. I am frankly shocked that a library can set the global allocator...

**Comment by Wicpar** [comment]
however i should note that using dhat that demo repo does still leak, even if at a slower rate.
