### ISSUE TITLE
`.clicked()` broken for labels in 0.11

### ISSUE THREAD

**Issue by jakobhellermann** [emilk/egui#292]
It seems like `ui.label("Label").clicked()` doesn't work since 0.11, it always returns `false`.

**Comment by emilk** [comment]
This has always been the case - labels does not sense clicks (and they do not light up when you hover them with your mouse). If you want to click labels, use [`Response::interact`](https://docs.rs/egui/0.11.0/egui/struct.Response.html#method.interact).

That being said, this is a such a common question that I just added an option to sense clicks on Labels directly (with hover-effects etc) using `Label::sense`.
