### ISSUE TITLE
Demo doesn't load due to egui_memory_ron incompatibility

### ISSUE THREAD

**Issue by alexkazik** [emilk/egui#2953]
**Describe the bug**
When opening https://www.egui.rs there was only a loading screen and an error in the console (see below).

When I removed egui_memory_ron from the local storage it worked after a reload.

My guess is that due to an earlier visit (I think at the time of egui 0.18/0.19) the storage is not compatible.

**Desktop:**
 - OS: macOs 13
 - Browser Chrome

```
frame::web::storage] eframe/src/web/storage.rs:21: Failed to parse memory RON: 1:14410: Unexpected missing field `pivot_pos` in `State`
```

**Comment by emilk** [comment]
This has been fixed
