### ISSUE TITLE
Feature 'resolver' is required

### ISSUE THREAD

**Issue by cbeust** [emilk/egui#297]
Trying to build a simple app with:

```
[dependencies]
egui = { version = "0.11.0" }
```

and getting:

```
Execution failed (exit code 101).
cargo.exe metadata --verbose --format-version 1 --all-features
stdout : error: failed to download `egui v0.11.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `C:\Users\cedri\.cargo\registry\src\github.com-1ecc6299db9ec823\egui-0.11.0\Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature
```

Not sure where to specify this `cargo-features` line...

**Comment by quadruple-output** [comment]
What is your `cargo --version`?
For me it shows 
`cargo 1.51.0 (43b129a20 2021-03-16)`
and I do not get the error message you are reporting.

**Comment by cbeust** [comment]
Yes, that was the problem, I was still on 1.50. Thanks!

**Comment by ujjwalbajaj** [comment]
I am havung cargo version : cargo 1.54.0 (5ae8d74b3 2021-06-22)
still getting the same error

**Comment by AndonMitev** [comment]
I have same issue for cargo 1.52.0 (69767412a 2021-04-21)

**Comment by emilk** [comment]
Does removing the `resolver = "2"` line in `Cargo.toml` fix it for you all?
