### ISSUE TITLE
Upgrade Cargo.lock image-rs to version 0.24.6

### ISSUE THREAD

**Issue by bu5hm4nn** [emilk/egui#2973]
Many users of image-rs are experiencing a panic on webp images. https://github.com/image-rs/image/issues/1856

I just found out this has been fixed in image-rs version 0.24.6 but egui's lockfile is stuck at 0.24.5, resulting in projects not getting the newest version if they just specify "0.24" as the version (at least my example did this).

Please update the Lockfile.

**Comment by emilk** [comment]
The `Cargo.lock` files in this repository only affects the `egui_demo_app` and other examples in this repository. The lock files does not affect anyone depending on `egui`
