### ISSUE TITLE
Better example

### ISSUE THREAD

**Issue by cbeust** [emilk/egui#300]
It would be nice if the code under **Example** was fully self contained, including imports and code that I can copy/paste to get a working example.

Right now, I still haven't been able to extract the relevant information from the examples in the distribution to find out, for example, what the variable `ui` is.

**Comment by emilk** [comment]
I have https://github.com/emilk/egui_template set up for this purpose!

**Comment by cbeust** [comment]
Thanks! Sorry if I missed this link from the main documentation (and if that link is not there, it should :-))
