### ISSUE TITLE
Program is compiling for wasm but do not show anything

### ISSUE THREAD

**Issue by gravit22** [emilk/egui#301]
**Describe the bug**
When I compile my app for OS it works fine, but when I try to export it to web assembly it compiles but do not show anything at all.
![image](https://user-images.githubusercontent.com/33228017/114439873-23bda280-9bd2-11eb-8aa0-355ad710fd0d.png)
![image](https://user-images.githubusercontent.com/33228017/114440014-5071ba00-9bd2-11eb-91c6-6f678c110476.png)

**To Reproduce**
This is repository: https://github.com/gravit22/ithkuil_learning
to check if program runs: cargo run
to check if it runs in wasm - ordinary steps:
./setup_web.sh
./build_web.sh
./start_server.sh
open http://127.0.0.1:8080/

**Expected behavior**
It should be the same, or at least working.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser chrome
 - Version 89.0.4389.114 (Official Build) (64-bit)

**Comment by emilk** [comment]
Does https://github.com/emilk/egui_template work for you?

**Comment by gravit22** [comment]
> Does https://github.com/emilk/egui_template work for you?
Yeah, untouched egui_template works completely fine.
![image](https://user-images.githubusercontent.com/33228017/114492599-8d18d200-9c21-11eb-8831-9b540460ceb1.png)

P. S. I did make this project based on that template.

**Comment by optozorax** [comment]
@gravit22 are there some errors in the browser console?

**Comment by gravit22** [comment]
> @gravit22 are there some errors in the browser console?

Thank you for asking, because I completely forgot about that.
Here what I get: 
![image](https://user-images.githubusercontent.com/33228017/114494582-4927cc00-9c25-11eb-8e23-47f2f3668a89.png)

![image](https://user-images.githubusercontent.com/33228017/114494713-7e341e80-9c25-11eb-96f9-b180c38aedfc.png)

**Comment by optozorax** [comment]
@gravit22 I believe now you can find a source of your problem. Maybe this happened because you renamed your project, therefore the `.wasm` file name is changed.

**Comment by gravit22** [comment]
Yeah, you are right. Thank you for help. I thought that index.html as all the other files is generated on its own, so when I made changes in it, it works.
Thank you a lot.
