### ISSUE TITLE
TextEdit is not editable and not selectable

### ISSUE THREAD

**Issue by 12089897411** [emilk/egui#3010]
Hello actor!

I'm creating an editor using TextEdit from egui! I need to make the editor non-editable at a certain moment, and I found the method provided (interactive(false)). This method sets the editor as non-editable and non-selectable. However, as an editor, I think that even when it is not editable, copy and other operations that do not change the text content should be selected

**Comment by emilk** [comment]
This is explained by the last section of the top-level docs for `TextEdit`: https://docs.rs/egui/latest/egui/widgets/struct.TextEdit.html

**Comment by 12089897411** [comment]
This is not the best way! When I use the solution you gave `ui.add(TextEdit::multiline(&mut text))`, I cannot get the gallery or response of TextEdit! I hope you can give other methods!
