### ISSUE TITLE
Is there any way to stop repaint when mouse move?

### ISSUE THREAD

**Issue by rustytsuki** [emilk/egui#3017]
I've turn off all of the animations of the egui in my apps. So I think I don't need the mouse move feedback. Is there any way to stop repaint when mouse move? I want to minimize CPU usage as much as possible.

**Comment by emilk** [comment]
Usually you want to repaint on mouse move to enable highlighting of buttons when they are hovered.

The request to repaint is done by the integrations. For `eframe` it is done by the `WindowEvent::CursorMoved` handler in `crates/egui-winit/src/lib.rs`. As you can see, there is no way to turn if off at the moment, but feel free to open a PR

**Comment by rustytsuki** [comment]
Thank you, I'm going to do some research about the eframe code.
