### ISSUE TITLE
Table Demo and Strip Demo window height grow when mouse cursor moves

### ISSUE THREAD

**Issue by rustrust** [emilk/egui#3029]
Even if I refresh my browser, the egui.rs demo page windows for the Table Demo and Strip Demo grow on their own when the mouse cursor moves. Using Latest Firefox 113.0.2 64-bit on an M1 running MacOS Ventura 13.4.

**Comment by vvv** [comment]
Watch the bug in action: https://youtu.be/ES4Mj6taq00

[![Watch the bug in action](https://img.youtube.com/vi/ES4Mj6taq00/maxresdefault.jpg)](https://youtu.be/ES4Mj6taq00)

**Comment by vvv** [comment]
The same bug applies to the [Strip Demo](https://github.com/emilk/egui/blob/860dac69dac6f1378e8556ccd7d39afb98a572e9/crates/egui_demo_lib/src/demo/strip_demo.rs) — the window grows on any interaction.

**Comment by jccampagne** [comment]
With the help of git-bisect, this behaviour first shows up in commit 94f8b02286d141147fa0f7177487091cbdca4c45.
Previous good commit: 089c7b46f37d76381eddf258de220cba08b8f126.

Tested locally using `egui/crates/egui_demo_app` on a Mac M1 (MacOS 13.4)

**Comment by jccampagne** [comment]
One can see this behaviour even without moving the mouse: if egui is set to "continuous" mode, "Table demo" and "Strip demo" frames will continuously grow vertically.

**Comment by vvv** [comment]
‘Table Demo’ window doesn't grow if any of these statements is commented out.

1)

https://github.com/emilk/egui/blob/9478e50d012c5138551c38cbee16b07bc1fcf283/crates/egui_demo_lib/src/demo/table_demo.rs#L112-L116

2)

https://github.com/emilk/egui/blob/9478e50d012c5138551c38cbee16b07bc1fcf283/crates/egui_demo_lib/src/demo/table_demo.rs#L107-L111

### Demos

<details>
<summary>Both statements are present (9478e50d012c5138551c38cbee16b07bc1fcf283)</summary>

https://github.com/emilk/egui/assets/17462/8a7cd847-ae6c-456c-8993-e58c53802333

</details>

<details>
<summary>Statement 1 is commented out</summary>

https://github.com/emilk/egui/assets/17462/3d474513-5555-4f8e-bcce-90f556e7ab08

</details>

<details>
<summary>Statement 2 is commented out</summary>

https://github.com/emilk/egui/assets/17462/cc020b93-034b-401d-8f38-e847ca931a2c

</details>

<details>
<summary>Both statements are commented out</summary>

https://github.com/emilk/egui/assets/17462/50954202-4bec-4d63-a814-245e4f8f127b

</details>

**Comment by rustrust** [comment]
I am unclear from the description, was this an issue only with the demo itself or was there an underlying problem with the egui library itself? I see that area.rs and rect.rs were modified.

**Comment by vvv** [comment]
@rustrust I [have replied](https://github.com/emilk/egui/pull/3122#issuecomment-1616087355) in the PR.

**Comment by rustrust** [comment]
the egui.rs demo page is still doing this,... are we waiting for this to be rolled out to the demo page or is it expected to be fixed now?

**Comment by olanti-p** [comment]
I still get this issue with `egui_demo_app` compiled for linux from latest master (627e1b3d5054df9961b5a467ac7c7b866a04d913).
