### ISSUE TITLE
Uncaught RuntimeError: unreachable

### ISSUE THREAD

**Issue by gravit22** [emilk/egui#303]
Sorry to bother so often, but I have another problem.
**Describe the bug**
When I compile for OS everything works as intended but when I compile for wasm I got this in browser console:
![image](https://user-images.githubusercontent.com/33228017/114500361-8b0a3f80-9c30-11eb-8a2f-d2d056674e24.png)
![image](https://user-images.githubusercontent.com/33228017/114500384-98272e80-9c30-11eb-9304-8eb70a270951.png)
![image](https://user-images.githubusercontent.com/33228017/114500450-b1c87600-9c30-11eb-8557-d41395e28a40.png)
![image](https://user-images.githubusercontent.com/33228017/114500485-c278ec00-9c30-11eb-80c5-8d6b57e74524.png)

**To Reproduce**
Source code: https://github.com/gravit22/ithkuil_learning
1. compile for web as usual: 
./setup_web.sh
./build_web.sh
./start_server.sh
open http://127.0.0.1:8080/
2. Click "Writing practice"
3. Click "Slot2
4. Everything freezes. Open console and there is an error I showed above.
![image](https://user-images.githubusercontent.com/33228017/114500794-767a7700-9c31-11eb-8550-e069c2d4a1ba.png)

**Expected behavior**
It should work as when it is runs on OS.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 89.0.4389.114 (Official Build) (64-bit)

**Comment by emilk** [comment]
Diagnosing crashes in wasm is difficult.

Try reducing the problem by removing code and find what is causing the crash. Since `egui_template` works fine for you, it should be fairly easy to find the minimal change that causes the crash.
