### ISSUE TITLE
Need more examples

### ISSUE THREAD

**Issue by cbeust** [emilk/egui#304]
I am trying to find out how to

- Display an image, and/or make that image the background of an existing widget
- Understand how events such as hovering can lead to changes in appearance

So far, I haven't been able to find examples or documentation showing how to do this

**Comment by emilk** [comment]
Have you seen https://emilk.github.io/egui/index.html ?

The Widget Gallery shows how to display an image. Showing an image behind an existing widget (e.g. a slider) is not currently possible; please open a feature request issue if that is something you need!

The toggle switch demo (also shown in the widget gallery) shows how you get hover-effects: https://github.com/emilk/egui/blob/master/egui_demo_lib/src/apps/demo/toggle_switch.rs

**Comment by cbeust** [comment]
I studied the source of the example yes but this code doesn't show how to load an arbitrary png/jpg. Could this be added? (and even better: can you show how to do this here?)

Thanks!

**Comment by emilk** [comment]
Loading images can be done with https://crates.io/crates/image as shown in https://github.com/emilk/egui/blob/master/egui_demo_lib/src/apps/http_app.rs

**Comment by cbeust** [comment]
I am familiar with that crate but egui requires to specify a `TextureId` in all its widgets, how do I convert an `Image` to a `TextureId`?

**Comment by emilk** [comment]
A better image loading example would be good though. When egui gets a logo, I can add an example for loading it.

**Comment by cbeust** [comment]
Yes. I was able to make it work by copy/pasting a sizeable portion of `http_app.rs` but it would be helpful if egui could hide as much of the `TextureId` concept as possible. Most people building GUI's just want to know how to load an image either externally or from an internal bundle, and don't care much about the intermediate steps to get there.

On a related note, I noticed that an image can never be `clicked()`, is this by design? Should I file a separate bug?

**Comment by emilk** [comment]
> On a related note, I noticed that an image can never be `clicked()`, is this by design?

Yes, that's why there is a separate `ImageButton`. Please look at the demo and read the docs.

**Comment by emilk** [comment]
I added a task to make a demo to load/show an image to https://github.com/emilk/egui/issues/186

**Comment by umberto-fontanazza** [comment]
@emilk the links you posted seem outdated/unreachable. It would be much better to have an example of creation of ImageButton directly in the [docs](https://docs.rs/egui/latest/egui/widgets/struct.ImageButton.html)
