### ISSUE TITLE
eframe: acrylic/mica/blur background vibrancy

### ISSUE THREAD

**Issue by AZProductions** [emilk/egui#3050]
**Is your feature request related to a problem? Please describe.**

Is there a method to apply window vibrancy effects to an eframe window? [Tauri](https://github.com/tauri-apps/window-vibrancy/blob/dev/src/windows.rs#L64) has an external implementation using the windows-sys crate and by setting the hwnd of the window you want to apply the effect on. 

Has this been done before, and is there then a way to get the eframe hwnd at runtime?

**Comment by AZProductions** [comment]
![image](https://github.com/emilk/egui/assets/66299945/b794a63c-e5a9-4060-8d36-86a0392debec)
I made a small demo with egui_glow, and the only requirement is the rawwindowhandle/hwnd which I can't seem to get from eframe.

**Comment by AZProductions** [comment]
Is there a way to access the raw window handle from egui? Perhaps it should be added since it allows alot of flexibility to embed effects etc.

**Comment by AZProductions** [comment]
Any winit based project will work with the window-vibrancy crate

**Comment by OmegaJak** [comment]
Though I don't need to set the window vibrancy for my application, I do need the hwnd/raw window handle for a different purpose - calling the Windows API to be notified when the user locks their session ([WTSRegisterSessionNotification](https://learn.microsoft.com/en-us/windows/win32/api/wtsapi32/nf-wtsapi32-wtsregistersessionnotification)). All it needs, to be called through the [windows](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/RemoteDesktop/fn.WTSRegisterSessionNotification.html) crate, is the hwnd.

Exposing the raw_window_handle would provide a lot of flexibility for implementing platform-specific behaviors that eframe itself doesn't support.

I'll be opening a PR that does this shortly.

**Comment by OmegaJak** [comment]
Actually, the raw_window_handle was already exposed in #3073 and is available on master, it just hasn't been released yet.

That could resolve this issue @AZProductions, unless you were hoping for a more integrated solution within egui itself.

**Comment by AZProductions** [comment]
Yes that would definitely make it work, perhaps I'll make a guide for that. Hope that the new version releases soon

**Comment by seradotflac** [comment]
Could you provide the code example you used in the image you provided?

**Comment by AZProductions** [comment]
> Could you provide the code example you used in the image you provided?

You just need the HWND from the window (you can get it via any of the egui render backends, or directly if you’re using eframe). Once you have that, you can apply vibrancy using something like the [window-vibrancy](https://github.com/tauri-apps/window-vibrancy) crate.

One important detail is that you also need to set the window background to transparent, otherwise the effect won’t show through.
