### ISSUE TITLE
Different logic for glow and wgpu integration in eframe

### ISSUE THREAD

**Issue by tkkcc** [emilk/egui#3079]
in `eframe/src/native/run.rs`

wgpu integration
```rust
        fn run_ui_and_paint(&mut self) -> EventResult {
            if let (Some(running), Some(window)) = (&mut self.running, &self.window) {
```
glow integration
```rust
        fn run_ui_and_paint(&mut self) -> EventResult {
            if let Some(running) = &mut self.running {
```
the glow interation does not check is `window` is valid. android app will panic on resume if using glow backend but is fine using wgpu: https://github.com/rust-mobile/rust-android-examples/issues/6.

This because winit `window` is taken on `Suspend` event and would be recreated on `Resumed`, but `run_ui_and_paint` can be called just before `Resumed`, and it needs a valid `window`.

Fot a quick solve, just add extra check for `window`, as the wgpu integration does.
```rust
        fn run_ui_and_paint(&mut self) -> EventResult {
            if let Some(running) = &self.running {
                if running.gl_window.window.is_none() {
                    return EventResult::Wait;
                }
            }
            if let Some(running) = &mut self.running {

```

But I wish for a more uniform code organization for these integrations, to avoid such problem. Currently, winit `window` is hold by `WgpuWinitApp` or `GlowWinitApp->GlowWinitRunning->GlutinWindowContext`, it's also strange.

**Comment by emilk** [comment]
Yeah, it would be nice to refactor this to unify the code a bit
