### ISSUE TITLE
Implement Clone for Window

### ISSUE THREAD

**Issue by coderedart** [emilk/egui#3083]
Window is the most commonly used container. But the struct not implementing Clone/Copy, and being generic over a lifetime (`'open`), makes it really hard to store or to create bindings for it. 

I am trying to add `Luau` bindings for egui at https://github.com/coderedart/luaegui

The problem is simple. Builder patterns are cool in rust because it is all inlined/optimized away by compiler, but they seem to create a lot of transient garbage in scripting languages. Every new builder fn will throw away the old object which will need to be collected by gc, and to make things worse, egui is immediate mode -> lots of garbage every frame. To avoid this issue, i just made the functions on containers like `Area` self mutating. eg: take the `Area::enabled` method. In rust, it uses builder pattern by consuming the current `Area` struct and returning a new struct. I bind it to mlua using

```rust
// add a method to `Area` type in lua called "enabled"
// It takes a "this"( mut ref to self) as the first argument  and another argument bool
area.add_method_mut("enabled", |_, this, enabled: bool| {
	// as you can see, the enabled method copies/clones the struct and returns a new one.
	// we will simply assign it to the same object, and avoiding creation of a lua gc-able object. 
	*this = this.enabled(enabled);
    Ok(())
});
```

But this method is not possible for `Window` struct. 
1. The method `enabled` takes `self`, but as `Window` is not Copy/Clone AND we can't move it out of `this`.
2. Even if it was possible, the lifetimes would definitely create some other problem. You cannot ask for a `&mut bool` in any scripting apis (lua/rhai etc..), as most primitive types like bools/numbers are passed by value. Instead, we have to take some kind of object (table in lua), and set the bool value just before returning from the show fn. User can check the object to see if the window is open/close.

To solve this with minimal breaking changes 
1. Make Window Copy/Clone just like Area. This will allow easier bindings.
2. Remove the `'open` lifetime, by not storing a `mut ref bool` inside `Window`. Instead, change the `show` fn to take a `&mut bool` along with ctx and ui closure. This is a breaking change.

### Alternative
It is possible to workaround this problem:
1. Change the `Window` binding of mlua to `Option<Window>`, which would allow moving it out of the mut ref ("this"). But, it still means creating a new window struct every frame, instead of just creating one and using a clone of it every frame. The struct can then be modified whenever necessary.
2. use some unsafe to transmute the `Window` struct to `'static` lifetime. And just skip the `open` fn and get/set the bool with the `show` fn binding.

Anyway, this is a niche use case, so nothing urgent.

EDIT: It seems, the same problem affects other containers like topbottompanel or centralpanel etc..

**Comment by emilk** [comment]
Are you having the same problem with `Slider` and `DragValue`?

**Comment by coderedart** [comment]
yes. But `Window` is used by everyone and was the main pain point. 

Lua passes numbers/strings/bools by value and tables (objects) / custom rust structs by reference. 

This causes two different kinds of problems
1. functions like `text_edit_singleline` or `checkbox` which want a `&mut T` are hard. And the clumsy workarounds are 
	1. given them a lua table like `{ value: "my text edit string" }` or `{ value: false }`, which the lua fn will take by reference, get the value out of object, validate argument before calling the checkbox or text_edit_* functions, and then setting the new value to that table's value field. 
	2. return a copy of the new value along with response. feels functional-ish. 
		```lua
			local my_bool, response = ui:checkbox(true);
			if my_bool then 
				print("value didn't change");
			else 
				print("value changed to false");
			end
		```
2. We can't use rust structs with functions which take a struct by value. Best example is `Window` and its `show` fn. When you create a `Window` struct, lua gc will handle that struct. And you can use functions which take `&self` or `&mut self`. But you can't call a fn that wants `self`, because lua's GC gets to decide when the object is destroyed, as the script might have other variables holding reference to this `Window` struct. So, any such struct which uses builder pattern taking in `self` is changed into `Option<Self>`. So, that we can call the `take` fn to take the Window out of the lua mutable reference of Option<Self> and pass it to any builder fn, take the returning new struct and put it back into `Option<Self>` using the same mutable reference. Finally, when we call a consuming fn like `show`, we don't have anything to put in the `Option<Self>`, and if user still uses that object, we just throw a exception. 
 
This code shows the problems and how i am working around them.
```lua
-- we can't pass mut ref to string in lua
-- so we store the string in an object and pass ref of this object to `text_edit_singleline` fn
my_data = {
    text = "my text"
}
-- a function to run inside the window
function window_ui(ui)
	-- label is fine, as it takes a readonly ref
    ui:label(my_data.text);
    -- working around the mut ref string by passing a table reference, and the fn will set the new value to the `text` field of the table
    ui:text_edit_singleline(my_data);
end
-- will be called every frame with egui Context as arg
_G.gui_run = function (ctx)
	-- we make the window static, so that we can store it in variable. 
	-- and we can't clone it , so we need to build this window object every single frame
	-- because calling show consumes the object
	-- that's why `new_window` below is not just a static window, but a static Option<Window>
	-- If it was cloneable (and show only took it by reference), we could keep reusing this every frame.
    local new_window = egui.window.new("my lua window");
	-- set default pos or whatever here..
	-- these builder fn wrappers basically take the window struct out of option, call the builder fn, and put the new value back into the option.
    new_window:show(ctx, window_ui);
	-- using new_window here will throw an error, because show already consumed the value out of option
end
```

The main reason to have clone  is performance. Builder pattern works for compiled/inlined languages like rust that optimize everything away. But for scripting, it is a lot of redundant work and unidiomatic. 

Something like this is much easier for scripting (subjective opinion):
```lua
-- create Window struct once at program startup and validate all args/config
local window_object = egui.window.create_window_object(
	{
		title = "my window",
		open = false,
		default_pos: -- and so on
	}
)

_G.gui_run = function (ctx)

	-- use the window_object every frame
	window_object.show(ctx,
		function (ui) 
			ui:label("hello");
		end
	)
	// window object owns its values like "open" boolean, so we can just check to see if it is open
	if window_object:open then 
		print("window is open");
	end
end
```
