### ISSUE TITLE
I want to create a new egui window

### ISSUE THREAD

**Issue by yunfengwangluo** [emilk/egui#3085]
If you are asking a question, use [the egui discussions forum](https://github.com/emilk/egui/discussions/categories/q-a) instead!

First of all, thank you for taking the precious time to read this information from me. Thank you here!

I want to create a new EGUI window that needs to be completely independent of the original window. I tried using multithreading, but I failed.

If you have time, please provide an idea or a simple code example. Thank you very much!

**Comment by n00kii** [comment]
open issue https://github.com/emilk/egui/issues/1044
