### ISSUE TITLE
Omitted keys prevent implementation of macOS standard shortcuts 

### ISSUE THREAD

**Issue by DoctorWhoof** [emilk/egui#3099]
**Describe the bug**
I understand why some non-standard keys are omitted from the "Key" enum, however there are a few omissions that should be reconsidered since they are required to satisfy all the standard macOS shortcuts:
(notice that most of those are handled by the OS and don't need to be implemented by the app).
https://support.apple.com/en-us/HT201236

The main omissions are:
**Comma** - used in "Command + ," (Settings, or preferences as it was named in older OS versions).
**Left** and **Right curly brackets,** **Vertical** Bar - Used  for alignment.
**Question Mark** - Used in "Shift+Command+?" to open the help menu.
**Colon** and **Semi-Colon** are used in spelling commands.
**Comma**, **Period** and **Grave Accent** are also used for several accessibility shortcuts.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.4

Aside from that, these are REALLY useful for complex desktop apps ()like music sequencers and 3D editors) and should be at least optional, maybe clearly labeled as non-standard.

Thanks!

**Comment by coderedart** [comment]
There is also https://github.com/pyfisch/keyboard-types which winit is looking to integrate. Maybe it would be useful to just reuse the types from that crate, which follow the UIEvents web spec.

**Comment by emilk** [comment]
Yeah, maybe it's time to add some of these keys. Feel free to make a PR. Make sure it works on web too! 🙏

**Comment by DoctorWhoof** [comment]
> Make sure it works on web too! 

Ooof, that's outside my tiny box... maybe I should just make the PR and someone else chimes in with Web standards?
Thanks!

**Comment by emilk** [comment]
Closed in favor of https://github.com/emilk/egui/issues/3653
