### ISSUE TITLE
Is there a way to make this work in a tiling window manage / compositor

### ISSUE THREAD

**Issue by yassinebenarbia** [emilk/egui#3104]
**I'm using :**
Os: Manjaro Linux x86_64
Kernel: 6.1.31-2-MANJARO 
Compositor: sway (default)

**Is your feature request related to a problem? Please describe.**

I've compiled the first example on this repo, it compiles just fine but I'm unable to interact with it.

**Additional context**

![swappy-20230622_155209](https://github.com/emilk/egui/assets/104306099/bb88ccde-f8c6-4924-a7ac-dafdd3c4190f)
![swappy-20230622_155317](https://github.com/emilk/egui/assets/104306099/bb064da6-59ee-41cb-a0a6-c4e4271b6f11)

**Comment by dvoytik** [comment]
I see the same regression on wayland/sway after updating egui from 0.21 to 0.22

**Comment by Janik-Haag** [comment]
@emilk csn you tell me what comments to run? seems like I'm facing a similar issue

**Comment by Tomaz-Vieira** [comment]
I just tried this on Fedora with sway `1.8.1` and egui at `401de056306d632b1082247e152c93479d88aa20`. I had to [fix the build script](https://github.com/emilk/egui/pull/3795) but otherwise it seems to work just fine.
