### ISSUE TITLE
Inline type to replace string test

### ISSUE THREAD

**Issue by OvermindDL1** [emilk/egui#312]
**Is your feature request related to a problem? Please describe.**

Currently text is stored in, for example, in `Label`'s or `Windows` or so, as just a `String`.  Occasionally it will also have associated style information, such as in `Label` that is adjacent to the String that stores the text.  This prevents mixing styles in a single string.  This prevents mixing other possible renderables inline in text, such as small images or a small widget or so.

As a real-life example of how this is useful think of a rich-text label, even a rich-text editor, allowing users to be able to specify styles themselves, for example like in Factorio you are able to do something like `This is some text, and [item=iron] is a tiny image of iron` or so and it will render it as the text but with `[item=iron]` replaced with a tiny text-sized image of iron, and this works near ubiquitously in its UI, can put it in chat (some are even clickable like `[pos=...]` as well), in draggable window headers, in-world, everywhere.  Factorio also has other abilities with text like making shortcode for URL's that are clickable, able to open windows via text links, can add inputs, sliders, toggles, etc... as well.  Being able to support all of this would be doable via the below `Inline` style api.

**Describe the solution you'd like**

What would be preferred is that in every location that a text can be displayed then it should not be a `String` but rather something like an `Inline` type, which I'd imagine would be a list of some form that accepts string, styled strings (string and associated style data, font, etc...), or widgets.

With this it would be possible to, for example, have `Label` disable stylized text, inline images, inline input boxes, whatever.

The API I was considering was:

`Inline` type that handles the rendering of such inline text, used like:

```rust
Inline::show(ui, |i| {
  i.text("Basic unstyled text, rendered as the parent widget wishes");

  // Perhaps text and styled_text calls would both just be text, normal text
  // would just by styled_text with nothing styled about it.
  i.styled_text("StylizedText").size_em(2.0).color(Color::Blue).font(SomeOtherFont).italic(true);

  // Can add other widgets, can even override the size to make sure it fits
  // if you don't want it to blow up in line size.
  i.add(Image::new(tex_id, (16.0, 16.0).uv(atlas_id.uv())).height_em(2.0);

  // Perhaps even helpers for common cases:
  i.image(tex_id).uv(atlas_id.uv()).height_em(2.0);

  // Any widget, notice that the button takes an Inline itself since it takes
  // text, using a simple `text` helper for a single simple unstyled string.
  if i.add(Button::new(Inline::text("Do Something")).clicked() { do_something(); }
});
```

A varieties of helpers for the simple cases like `Inline::text("Simple unstyled string")` and so forth would be useful.  Perhaps an implementation for `From<Into>` on `String`/`str` to allow a String to be passed to something that takes an `impl Into<Inline>` would allow the textual api to remain as it does now while allowing greater inline formatting when necessary.  Everything that takes a string to display as text now would be updated to this.

**Describe alternatives you've considered**

Tried just starting to manually make my own `InlineLabel` widget that renders such a list via function calls on it, but this doesn't allow its use in a variety of areas without rewriting a large variety of other widgets.  I'd essentially have to rewrite many/most widgets in all of egui as it stands anyway, and this feature would be greatly generically useful for others as well, while keeping the basic/current user api unchanged.

**Comment by emilk** [comment]
You can do this already: https://github.com/emilk/egui/blob/master/egui_demo_lib/src/apps/demo/widgets.rs#L48

<img width="414" alt="Screenshot 2021-04-16 at 23 19 09" src="https://user-images.githubusercontent.com/1148717/115085114-373a7780-9f0a-11eb-8116-dc3ab7edc4ee.png">

**Comment by OvermindDL1** [comment]
I wasn't referencing where each part are generic widgets, but rather where all things that take text would support it, including, for example, even a `Window` title, where you cannot currently do so, among other areas.

**Comment by emilk** [comment]
Oh, I see! Sorry for the misunderstanding.

Still, the thing you are describing is basically a `trait Widget` or `impl FnOnce(&mut Ui)`. It would perhaps be possible to make `Window` take a `Widget` for its title, but there is no need for any new `Inline` object afaict.

**Comment by OvermindDL1** [comment]
> It would perhaps be possible to make Window take a Widget for its title

That would be perfectly wonderful generic!
