### ISSUE TITLE
"Hello World" application starts with a black box and errors are logged in the console

### ISSUE THREAD

**Issue by josephkerkhof** [emilk/egui#3131]
**Describe the bug**
Trying to run "hello world" from the `master` branch.

**To Reproduce**
1. Clone master and `cd` to hello world in the examples folder.
2. `cargo run`
3. The application starts with a black box.
4. Several of the following errors are logged in the console:
```
[2023-07-02T04:01:00Z ERROR egui_glow] GL error, at crates/egui_glow/src/painter.rs:284 (FRAMEBUFFER_SRGB): GL_INVALID_ENUM (0x500)
```

**Expected behavior**
The hello world program works as expected.

**Screenshots**
None. It's just a black screen.

**Desktop (please complete the following information):**
 - OS: Parabola
 - Browser: N/A
 - Version: N/A

**Additional context**
My window manager is DWM as my window manager with X as my display server on a Thinkpad T400.

**Comment by josephkerkhof** [comment]
I've tried this in Rust 1.70 and the bug still persists. I cannot run `hello_world`. It just gives me a black screen.

**Comment by josephkerkhof** [comment]
I am no longer having this issue after installing the proper driver for my Arch linux computer, `mesa-amber`. Sorry for the confusion which was on my end.

**Comment by philip-lamb** [comment]
See also https://github.com/servo/servo/issues/30782
