### ISSUE TITLE
Mint Integration!

### ISSUE THREAD

**Issue by edwinwalda** [emilk/egui#314]
**Is your feature request related to a problem? Please describe.**
`egui` has been an awesome solution to getting ui up and running for for my game. For all of my coordinate systems, I'm currently using `glam` and would love an easy way to translate some of my vectors easily into egui's format without having to unpack them every time.

**Describe the solution you'd like**
Fortunately, that's why Mint exists: https://github.com/kvark/mint

Mint is a data / representation only linear algebra library meant to be used as a unified intermediate step when converting between linear algebra representations. All each library has to do is implement `from<mint::types>` for their own representations, and users can easily convert between them.

Here's a short list of libs that implement mint conversions:
- `cgmath`
- `euclid`
- `nalgebra`
- `glam`
- `kurbo`
- `vek`

The library itself is fairly lightweight, (7.5kb), has a single (optional) dependency on `serde` and could be enabled / disabled with a feature easily.

**Describe alternatives you've considered**
To my knowledge `mint` is the best supported interoperability lib for math-related types. If `egui` had consumes another library's types, I would suggest to just re-export them. But `egui` wrote them from scratch, so the next best solution would be to implement conversions for `mint`

This would be a pretty lightweight feature, and would be happy to contribute it, I just wanted to raise the idea first, and gauge how open y'all are to the idea. 

In general, I would just like to thank y'all for the work on this lib. It's been a pleasure to use, and I hope to improve it even more.

**Comment by emilk** [comment]
Haven't heard about `mint` before - very cool idea!

I definitely think we should add this to `emath::Vec2` and `emath::Pos2` behind an feature-gate.
