### ISSUE TITLE
Text is unreadable in "Light Mode"

### ISSUE THREAD

**Issue by billyswong** [emilk/egui#315]
**Describe the bug**
Text, especially hyperlink and placeholder text, is very hard to read in "light mode" in the demo page.

**To Reproduce**
1. Go to https://emilk.github.io/egui/index.html
2. Click on "Switch to light mode" button in the top left corner
3. Some problem happen to edge handling between text and background, rendering normal text extremely thin while text in other colour totally unreadable

**Expected behavior**
Proper text rendering. If alpha-blending handling of text is too hard to maintain well, don't use anti-alias in text rendering, as the monospace font is unaffected in the demo.

**Screenshots**
![image](https://user-images.githubusercontent.com/33863356/115135986-45de7700-a04f-11eb-9b8d-3785fe8e6685.png)
![image](https://user-images.githubusercontent.com/33863356/115136103-05cbc400-a050-11eb-9834-899dc531381d.png)
![image](https://user-images.githubusercontent.com/33863356/115136342-bbe3dd80-a051-11eb-8674-292a76266f71.png)

**Desktop:**
 - OS: Linux Mint 20.1
 - Browser: Firefox 87

**Smartphone:**
 - OS: Android 8.0
 - Browser: Chrome 89

**Additional context**
Because smartphone is running a hidpi screen (200%dpi in my phone browser), the bug is less prominent there. But the italic-grey text is still horrible and practically unreadable as shown in screenshot 3.

**Comment by parasyte** [comment]
@emilk This is fixed by effd3c7440d9f70c0eff677871a60be539cf1113
