### ISSUE TITLE
TextEdit calls `TextBuffer::delete_char_range` on inserting text

### ISSUE THREAD

**Issue by ales-tsurko** [emilk/egui#3154]
In my app I have undo/redo implementation for the state. And to handle undo/redo for the multiline text edit widget, I implement `TextBuffer` for the state. When `insert_text` is called, the action for inserting is recorded in the history, for the `delete_char_range` another action is recorded. But I've found that when I insert the text, first `delete_char_range` is called, and then `insert_text`. This leads to a bug in my case, because the history of actions is wrong and undo/redo always works on the second call. 

I found in the code that deleting text (and triggering `TextBuffer::delete_char_range`) is done before inserting intentionally (event handling in `widgets/text_edit/builder.rs::events` function). Are there any workarounds? Can I process text edit's insert/delete events without having side effects?

**Comment by emilk** [comment]
The natural workaround is to ignore calls to `delete_char_range` if the range is empty?
