### ISSUE TITLE
Infinitely growing top panel

### ISSUE THREAD

**Issue by feelingnothing** [emilk/egui#3155]
**Describe the bug**
Tested on master.
Code to reproduce
```rust
TopBottomPanel::new(TopBottomSide::Top, "titlebar").show(ctx, |ui| {
    ui.with_layout(Layout::left_to_right(Align::Center), |ui| {
        ui.label("");
    });
    ui.with_layout(Layout::right_to_left(Align::Center), |ui| {
    });
});
```

**Screenshots**
![default](https://github.com/emilk/egui/assets/47575622/8ca6916a-40e2-4665-870f-ef64b9841c33)

**Desktop (please complete the following information):**
OS: Windows 11 22H2

**Comment by timvw01** [comment]
Ive had the same when compiling to wasm. There the issue was a growing canvas size, which was fixed by changing the eframe-> web->mod.rs

<pre>
<code>
pub fn resize_canvas_to_screen_size(canvas_id: &str, max_size_points: egui::Vec2) -> Option<()> {
    let canvas = canvas_element(canvas_id)?;
    let parent = canvas.parent_element()?;

    let width = parent.scroll_width();
    <del>let height = parent.scroll_height();</del>
    let height = parent.client_height();
</code>
</pre>

**Comment by emilk** [comment]
The reason for this is documented here: https://docs.rs/egui/latest/egui/struct.Ui.html#method.with_layout

**Comment by feelingnothing** [comment]
> The reason for this is documented here: https://docs.rs/egui/latest/egui/struct.Ui.html#method.with_layout

It says that all available space would be used, why does it expand the window?

**Comment by emilk** [comment]
The first call to `with_layout` uses up all available space, then you ask for more space using `with_layout`. The second call should give you a zero-sized `ui` (there's nothing left), but first there will be spacing added between the two ui:s (`item_spacing.y`). There is no room for that spacing, so the panel expands to fit it.

**Comment by blueforesticarus** [comment]
does egui have something for constructing the items first, and then computing the layout?
