### ISSUE TITLE
Painter's `CallbackFn` redesign

### ISSUE THREAD

**Issue by MatrixDev** [emilk/egui#3163]
**Is your feature request related to a problem? Please describe.**
It is a little hard to describe but I'll try my best. It is based on wgpu backend but glow could has similar points.

First of all example for using glow/wgpu directly is way too simple. It covers at max one control and stores all data in `paint_callback_resources` which is not always possible when using multiple controls. For example it is not possible to have custom UVs per-control because there is only a single vertex buffer stored `globally` in context.

Currently it is somewhat hard to implement custom controls that require its own retainable data (for ex. uniform/vertex buffers). We can register our 'global' context in the `paint_callback_resources` during App initialization and use it as storage for uniforms/vertex/shaders/etc.

Ideally we could have a big buffer for all controls and just update it in `CallbackFn::prepare` (while storing offset) and than just bind it in `CallbackFn::paint` with stored offset. Unfortunately unlike in egui itself we don't know how big the buffer must because we don't know how many controls we have. This can be worked around by using per-control uniform/vertex buffer instead of single huge one.

So possible solution is to:
- register global object in `paint_callback_resources`
- write all the data to global object's intermediate Vec<u8> in `CallbackFn::prepare`, and store offsets in per-control shared data
- between `CallbackFn::prepare` and `CallbackFn::paint` reallocate uniform/vertes buffers (if needed) and upload data (similar to what egui does)
- simply schedule draw calls in `CallbackFn::paint` with all of the offsets above

There are few problems:
1. we don't have a callback between of `prepare`/`paint` to update all buffers. we can instead use a boolean flag which will be reset in `CallbackFn::prepare` and perform buffer updates in the first call to `CallbackFn::paint` but `paint_callback_resources` are readonly there.
2. the only way to pass per-control data from `CallbackFn::prepare` to `CallbackFn::paint` is to use shared arc-ed struct. so all offsets need to be stored atomically.
3. if we had a single trait instead of two callbacks, we could store said offsets in the object implementing it. but because  `CallbackFn` itself is stored in an Arc, mutable access to this object is not possible (so again... atomics).

**Describe the solution you'd like**
Ideally:
1. store `CallbackFn` in `PaintCallback` as Box<dyn Any> instead of Arc<dyn Any>
2. combine `CallbackFn::prepare` and `CallbackFn::paint` into a single trait (also reduces number of allocations)
3. add additional `&mut self` callback between `CallbackFn::prepare` and `CallbackFn::paint` to know when we can upload intermediate buffers to final buffers.

Realistically:
I guess 1 is very painfull to implement. so we can at the very try to least implement 2 & 3. those are much less painfull:
```rust
// old
#[derive(Clone)]
pub struct CallbackFn {
    prepare: Box<PrepareCallback>,
    paint: Box<PaintCallback>,
}

// new
// ideally wouldn't need it but `dyn Any` can't be case to `dyn Trait` in Rust, `CallbackFn` is used just as a wrapper:
pub struct CallbackFn {
    implementation: Box<dyn CallbackFnTrait>
}

pub trait CallbackFnTrait : Send + Sync {
    fn prepare(
        &self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        encoder: &mut wgpu::CommandEncoder,
        resources: &mut TypeMap,
    ) -> Vec<wgpu::CommandBuffer>;

    fn finish_prepare(
        &self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        encoder: &mut wgpu::CommandEncoder,
        resources: &mut TypeMap,
    ) -> Vec<wgpu::CommandBuffer>;

    fn paint<'a>(
        &self,
        info: PaintCallbackInfo,
        render_pass: &mut wgpu::RenderPass<'a>,
        resources: &'a TypeMap,
    );
}
```

Drawbacks:
- a breaking change
- requires GATs, so MSRV must be increased to 1.65

**Describe alternatives you've considered**
Just allocate shared state and callbacks separately, per-control unified/vertex buffers.

**Additional context**
This is only a potential improvement that fits my use case, it might not be worth overall but lets see.

**Comment by Wumpf** [comment]
Great writeup, liking the proposal quite a bit, having a stab at it. I'll play around a bit and try to get rid of the TypeMap, not very fond of having that there since typeid is such an odd limitation for accessing global resources 🤔 
This might also help to to tackle the issue with`fragile-send-sync-non-atomic-wasm` https://github.com/emilk/egui/pull/3170#issuecomment-1671001996
