### ISSUE TITLE
eframe window position incorrectly restored when saved on a secondary screen

### ISSUE THREAD

**Issue by abey79** [emilk/egui#3176]
**Describe the bug**

The eframe window position is not correctly restored after successive launches when moved to a secondary screen.

**To Reproduce**
Steps to reproduce the behavior (I'm using eframe_template as a basic project *with* state persistance):
1. run `eframe_template` (`cargo run`)
2. move the window to the secondary screen
3. close the window
4. run again (`cargo run`) --> the window is restored on the primary screen instead of the secondary screen as expected

**Screenshots**

https://github.com/emilk/egui/assets/49431240/2bce4f38-8356-473f-ae59-7e76c73228ac

**Desktop:**
 - OS: macOS Ventura 13.4.1
- Display layout:
<img width="586" alt="image" src="https://github.com/emilk/egui/assets/49431240/8e8ff1f0-2dba-4145-802c-4cd4b1116fb7">

**Comment by emilk** [comment]
It seems `WindowBuilder::with_position` doesn't work with negative values on Mac (secondary monitors often has negative coordinates). `Window::set_outer_position` seems to maybe work though, at least slightly better.
