### ISSUE TITLE
z-index is wrong

### ISSUE THREAD

**Issue by octavz** [emilk/egui#3177]
Hey,

I was browsing the example on browser (chromium based, Vivaldi) and this happened when dragging around and overlapping 2 panels.

I am  not a Rust/egui user yet, I can't say if it reproduce with master.

![image](https://github.com/emilk/egui/assets/23629302/ee874603-c87a-48be-a0d8-ae64386dd89b)

I couldn't easily find if is a duplicate, please close if it is.

Thank you.

**Comment by liquidhelium** [comment]
>Widgets that store state require unique and persisting identifiers so we can track their state between frames.
>For instance, collapsible headers needs to store whether or not they are open. 
>Their Id:s are derived from their names. 
>If you fail to give them unique names then clicking one will open both. 
>To help you debug this, an error message is printed on screen:

As quoted above, ID clashing is a bug when it appears in your program. So this error message needs to be easy to see.
