### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by tomassedovic** [emilk/egui#32]
Egui currently ships with built-in fonts and (as far as I could see) there's no way for the library user to switch those out.

Font customisation is done via `ctx.set_fonts` which accepts a `FontDefinitions`. But that requires a `FontFamily` which is an enum containing the hardcoded fonts and a no way to change them.

Would bringing your own font be within Egui's scope? The built-in fonts are great for e.g. debugging, level editor etc. UIs, but for a user-facing one (e.g. in-game menu, windows) the fonts often need to match the look & feel of the game.

If this is welcome, I'll be happy to work on it (albeit slowly) and follow any design considerations you might have.

My initial thought is adding a third variant `FontFamily::Custom(u32)` and provide a way to register a new font e.g.: `impl Context { pub add_custom_font(font: &[u8]) -> u8; }`

Where the function and the enum variant would both use a font ID (or maybe a hashed name) to support multiple fonts at the same time.

For reference, this is a commit I'm maintaining in my Egui fork to be able to use a (single) custom font:

https://github.com/tomassedovic/emigui/commit/47c7942725267856d2ad32fe29ce1274d617bff2

And it's used like this in my game:

```rust
let font_definitions = {
    use egui::paint::fonts::{FontFamily, TextStyle};
    let family = FontFamily::Mononoki;

    let mut def = egui::paint::FontDefinitions::default();
    def.fonts.insert(TextStyle::Body, (family, font_size_px));
    def.fonts.insert(TextStyle::Button, (family, font_size_px));
    def.fonts.insert(TextStyle::Heading, (family, font_size_px));
    def.fonts
        .insert(TextStyle::Monospace, (family, font_size_px));
    def
};
ctx.set_fonts(font_definitions);
```

**Comment by emilk** [comment]
Hello!

There are (at least) two separate issues here:

A) Being able to override the default fonts used by Egui
B) Being able to add additional user fonts

Egui should definetly support both! I think A) is probably the first priority. In this case, maybe what you really wanted to do is to change `TextStyle::Monospace` to use `Mononoki`, so A) would have indeed solved it.

There is some design work to be done here before we start coding.

Let's start with thinking about A). We could start by having `FontDefinitions` contain a map from `FontFamily` to the TTF font data (e.g. as a `ttf: HashMap<FontFamily, Vec<u8>>` member). `FontDefinitions::default()` could use the default fonts, but you could then override it as such:

``` rust
let mut fonts = egui::paint::FontDefinitions::default();
fonts.ttfs[FontFamily::Monospace] = include_bytes!("mononoki.ttf").to_vec();
ctx.set_fonts(fonts);
```

What do you think, is something like that a good start?

**Comment by tomassedovic** [comment]
Greetings!

What you proposed looks perfect! It would cover my needs completely.

I agree there's multiple things "custom font support" could mean and focussing on being able to swap the default fonts for user-specified ones is a great start.

**Comment by emilk** [comment]
Let me know if you start working on this, otherwise I'll get to it... some time? :)

**Comment by tomassedovic** [comment]
It would probably be some time here too. I'll post here if/when I pick it up! Thanks for the great suggestion!

**Comment by tomassedovic** [comment]
This is awesome, thank you so much!

**Comment by Eskerepvp** [comment]
> 

This doesn't work...


```   |
77 |         fonts.ttfs[FontFamily::Monospace] = include_bytes!("../assets/fonts/NotoEmoji-Regular.ttf").to_vec();
   |               ^^^^ unknown field
   |
   = note: available fields are: `font_data`, `families````

**Comment by emilk** [comment]
@Eskerepvp it's because you are reading a two year old issue instead of [the latest documentation](https://docs.rs/epaint/latest/epaint/text/struct.FontDefinitions.html).
