### ISSUE TITLE
Egui-winit/egui-wgpu samples

### ISSUE THREAD

**Issue by tech0tron** [emilk/egui#3201]
Working on a renderer and looking to add a debug/diagnostic UI for it. Would be nice to have some to the point examples of using egui-winit/egui-wgpu being used.

**Comment by Wumpf** [comment]
There's an example here, but it sure could be expanded a bit
https://github.com/emilk/egui/blob/master/crates/egui_demo_app/src/apps/custom3d_wgpu.rs

**Comment by fralonra** [comment]
https://github.com/fralonra/wgshadertoy/ is a working example.

Hope it helps.
