### ISSUE TITLE
Labels with tabs-only text don't allocate space

### ISSUE THREAD

**Issue by tvanderstad** [emilk/egui#3203]
**Describe the bug**
Labels with only tabs in their text don't allocate space e.g. don't affect the layout of subsequent labels. This is confusing because empty labels do affect the layout.

**To Reproduce**
Run the following app:
```
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use eframe::egui;

struct MyApp {}

impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        let long_text = "long text\n".repeat(50);

        egui::CentralPanel::default().show(ctx, |ui| {
            ui.label("-----");
            ui.label(""); // rendered
            ui.label("-----");
            ui.label(" "); // rendered
            ui.label("-----");
            ui.label("\t "); // rendered
            ui.label("-----");
            ui.label("\t"); // NOT rendered
            ui.label("-----");
            ui.label("\t\t"); // NOT rendered
            ui.label("-----");
        });
    }
}

fn main() {
    eframe::run_native(
        "test",
        eframe::NativeOptions {
            drag_and_drop_support: true,
            initial_window_size: Some(egui::vec2(900.0, 600.0)),
            ..Default::default()
        },
        Box::new(|_cc: &eframe::CreationContext| Box::new(MyApp {})),
    )
    .unwrap();
}
```

**Expected behavior**
A series of labels with text "-----" spaced equally apart.

**Screenshots**
<img width="912" alt="Screenshot 2023-08-04 at 12 02 00 PM" src="https://github.com/emilk/egui/assets/6198756/cfc54726-c630-40f8-9655-18d6cb398a60">

**Desktop:**
 - OS: MacOS Ventura 13.3.1

**Additional context**
Building a markdown editor for github.com/lockbook/lockbook and not sure how I'm supposed to render tab characters

**Comment by StripedMonkey** [comment]
This appears to have been fixed in git by #3302
![image](https://github.com/emilk/egui/assets/8009284/3444dead-8b50-4393-a988-72f5a72bc336)

**Comment by emilk** [comment]
Trailing tab characters also messes up the text layout

**Comment by mfrench1989** [comment]
Leading tabs on a label that wraps do not get rendered, this is in version 0.29.1 though so might be fixed in current version.
