### ISSUE TITLE
[egui-winit] Move to `wl-clipboard-rs`

### ISSUE THREAD

**Issue by daxpedda** [emilk/egui#3215]
`egui-winit` currently uses [`smithay-clipboard`](https://crates.io/crates/smithay-clipboard), which isn't being maintained anymore: see https://github.com/Smithay/smithay-clipboard/issues/44.

[`wl-clipboard-rs`](https://crates.io/crates/wl-clipboard-rs) is a still maintained alternative, e.g. used by [`arboard`](https://crates.io/crates/arboard).

**Comment by daxpedda** [comment]
I just saw that `egui-winit` actually uses `arboard`, but because `arboard` doesn't support Wayland except in terminals, `smithay-clipboard` was used instead: https://github.com/emilk/egui/pull/1613.

**Comment by kchibisov** [comment]
this is just non-sense, if you can see it has a working release with all the bugs fixed. It won't get updates to support images, but that's about it.

The wl-clibpoard-rs is not the crate that should be used for windowing apps, it's for clipboard managers and uses priv protocols, which egui is clearly not.

If you want more on clipboard, I'd suggest researching a winit based solution.

**Comment by kchibisov** [comment]
>Kinda implies that the crate won't be updated and it wasn't for a long time.

it's just on a bug fix mode.
