### ISSUE TITLE
`on_hover_text` does not work on disabled items

### ISSUE THREAD

**Issue by HalfVoxel** [emilk/egui#323]
**Describe the bug**
I expected that `on_hover_text` should still work for disabled items (`ui.set_enabled(false)`) so that one can for example explain why it is disabled. However it does not seem to work.

**To Reproduce**
1. https://emilk.github.io/egui/index.html
2. Click the `Interactive` toggle
3. Hover over anything in the window
4. Observe that hover texts do not show up

**Expected behavior**
Hover texts do show up

```
let mut some_bool = false;
ui.wrap(|ui| {
    ui.set_enabled(false);
    ui.selectable_value(&mut some_bool, true, "Some label")
        .on_hover_text("Some hover text");
});
```

Is this by design or is it a bug?
If it is by design, it would be nice with a mode that disables things while still allowing hover texts to be shown.

**Comment by emilk** [comment]
I think it is a bug. I think it makes sense to allow tooltips for disabled items too.

**Comment by emilk** [comment]
I've looked at this a bit closer, and have changed my mind. I think `on_hover_*` should only show something on a proper hover, and that we should have a second `on_disabled_hover_*` for the disabled behavior.

Motivation: visit [the widget gallery](https://emilk.github.io/egui/index.html) and uncheck the "interactive" checkbox. It would be quite weird if a bunch of tooltips appeared when hovering e.g. the hyperlinks. So I think in most cases tooltips shouldn't show when disabled, and when they do it is probably to explain to the user why the e.g. a button isn't clickable.

``` rust
ui.button("Submit")
    .on_hover_text("Submit form")
    .on_disabled_hover_text("You must complete the form first");
```

**Comment by HalfVoxel** [comment]
I think that's a very good solution! It fits exactly with the use case I had in mind too.
