### ISSUE TITLE
egui_demo_app with glium integration using lots of cpu when in continuous mode and minimized on mac

### ISSUE THREAD

**Issue by jnises** [emilk/egui#325]
**Describe the bug**
The native version of the egui_demo_app seems to ignore vsync when running minimized in continuous mode on a mac.
It uses much more cpu when the window is minimized than when it is visible.

**To Reproduce**
1. on a mac. running big sur in my case.
2. clone egui 0.11.0
3. `cd egui_demo_app`
4. `cargo run --release`
5. select continuous mode in the backend section
6. check cpu usage in activity monitor
7. minimize the egui_demo_app window
8. check activity monitor again

**Expected behavior**
That the demo app would use less or the same amount of cpu when minimized.

**Screenshots**
When visible:
![image](https://user-images.githubusercontent.com/1059884/115273795-49056000-a140-11eb-9dfa-6e6518e5932d.png)

When minimized:
![image](https://user-images.githubusercontent.com/1059884/115273843-56bae580-a140-11eb-87e2-aa2b535058d1.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.3.2

**Comment by emilk** [comment]
Good find!

A perfect solution is hard because there is no way to know if a window is minimized: https://github.com/rust-windowing/winit/issues/208

But I'll add a sleep when the window is in the background. That should at least help.
