### ISSUE TITLE
TextEdit does not allocate properly according to the aspect ratio

### ISSUE THREAD

**Issue by VitoKingg** [emilk/egui#3269]
**Describe the bug**

`TextEdit`'s width is set default to `280`, which is defined in `text_edit_width`. My screen aspect ratio is `150%`. When I add a `TextEdit` widget, the actual render width of this widget is 420. When I set `desired_width` to `200`, the actual render width is `300`.

I found this `pixels_per_point` field in other ui widgets. Should there be a `pixels_per_point` field in `TextEdit` too?

**Comment by emilk** [comment]
`pixels_per_point` is global to egui. All of `egui` uses "points" as its unit. You set the `TextEdit` with to 280 points, and on screen it becomes 420 pixels, because you have set `pixels_per_point = 1.5`.

You can change `pixels_per_point` using `Context::set_ pixels_per_point`
