### ISSUE TITLE
`Plot` `Polygon`s ignore stroke color, stroke instead with fill color

### ISSUE THREAD

**Issue by tgross35** [emilk/egui#3276]
**Describe the bug**

Setting stroke and fill colors different should result different stroke and fill, but this is not the case. Setting stroke to red and fill to blue, this is the result:

<img width="425" alt="image" src="https://github.com/emilk/egui/assets/13724985/742564e1-3553-4c1e-bd8c-8d6065ed9325">

**To Reproduce**

Run this sample:

```rust
use egui::plot::{Plot, Polygon};
use egui::{Color32, Stroke};

fn main() -> eframe::Result<()> {
    eframe::run_native(
        "demo",
        eframe::NativeOptions::default(),
        Box::new(|_cc| Box::new(App)),
    )
}

struct App;

impl eframe::App for App {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::CentralPanel::default().show(&ctx, |ui| {
            let poly = Polygon::new(vec![
                [0.0, 0.0],
                [0.0, 10.0],
                [10.0, 10.0],
                [10.0, 0.0],
                [0.0, 0.0],
            ])
            .stroke(Stroke::new(3.0, Color32::RED))
            .color(Color32::BLUE);
            Plot::new("my_plot").view_aspect(1.0).show(ui, |plot_ui| {
                plot_ui.polygon(poly);
            });
        });
    }
}
```

**Expected behavior**

The stroke should be red and not blue

**Screenshots**

See above for main screenshow.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 12.6.8

**Additional context**

Verified on both Windows and Mac

**Comment by s-nie** [comment]
Should be fixed by https://github.com/emilk/egui/pull/3182
