### ISSUE TITLE
Negative clipping zone values

### ISSUE THREAD

**Issue by mvlabat** [emilk/egui#328]
**Describe the bug**

I was able to reproduce a case when `DrawCommand`'s `clipping_zone` has a negative height.

**To Reproduce**
1. You can run the `ui` example of [`bevy_egui`](https://github.com/mvlabat/bevy_egui)
2. Quickly click the minimize button
3. I'll eventually crash with the following error:

```
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(1, 1375, Vulkan)>`
    In a set_scissor_rect command
    Invalid ScissorRect parameters
```

Printing the clipping zone with `dbg!` reveals this:

```
[src\egui_node.rs:313] (draw_command.clipping_zone.min.x, draw_command.clipping_zone.min.y,
 draw_command.clipping_zone.width(), draw_command.clipping_zone.height()) = (
    291.0,
    72.0,
    346.0,
    -2.6479187,
)
```

**Expected behavior**

I believe that Egui should not pass a command if any clipping zone parameter is equal to or less than 0.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro (10.0.19041 Build 19041)

**Additional context**
https://github.com/mvlabat/bevy_egui/pull/16

**Comment by mvlabat** [comment]
@emilk thanks for fixing it so fast! I also wanted to suggest ignoring 0 clipping zones (or even the ones, that are lesser than 1). Some graphic backends treat 0 scissors height as an error. And practically it probably doesn't make sense to push a command that wouldn't actually draw anything that would fit on a pixel

**Comment by emilk** [comment]
My commit ignores zero-sized clip-rects too

**Comment by mvlabat** [comment]
@emilk I saw you used this function to filter them out:

```
    pub fn is_non_negative(&self) -> bool {
        self.min.x <= self.max.x && self.min.y <= self.max.y
    }
```

But it seems to be that it allows min to equal to max, which means that 0 values are not filtered out. Am I missing something?

**Comment by emilk** [comment]
You are right - I was to quick :) Thanks for pointing out my mistake!

**Comment by mvlabat** [comment]
Looks good now! Thanks a lot :)
