### ISSUE TITLE
`eframe` does not appear to expose ability to set window transparency and mouse passthrough

### ISSUE THREAD

**Issue by jquesada2016** [emilk/egui#3287]
**Is your feature request related to a problem? Please describe.**

`egui::NativeOptions` exposes a couple fields that don't seem to have a way to change during runtime, such as `transparency` and `mouse_passthrough`.

**Describe the solution you'd like**

Add additional setters to `egui::Frame` to control these settings.
**Describe alternatives you've considered**

A workaround for `transparency` is to set the `App::clear_color` to return an opque background, but I believe this is not the same thing, performance wise, when disabling transparency on the window, since the window compositor needs to do more work.

**Additional context**

N/A

**Comment by emilk** [comment]
Sounds good to add it to `Frame`

**Comment by danielnehrig** [comment]
this was one of the reasons why i didn't use eframe i have a use cases where this is required
now i had to do all of this myself 😭 window creation, wgpu setup egui setup, event loop ...

**Comment by emilk** [comment]
This is now possible with https://docs.rs/egui/latest/egui/struct.Context.html#method.send_viewport_cmd

**Comment by jquesada2016** [comment]
Lol,  I thought I had made a PR for this...but I actually made it for iced, because I needed it there too, and forgot to contribute back here. Sorry about that!
