### ISSUE TITLE
Separator in menu has wrong length

### ISSUE THREAD

**Issue by optozorax** [emilk/egui#329]
**Describe the bug**
When using a separator in `menu::menu`, it didn't fill full space.

**To Reproduce**
Add this code to `menu::bar` and run:
```rust
menu::menu(ui, "Test", |ui| {
    drop(ui.button("Test"));
    ui.separator();
    drop(ui.button("Now long text"));
    ui.separator();
    drop(ui.button("Now much much much longer text"));
});
```

**Expected behavior**
A separator should fill full space like it did in regular windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/18114381/115564633-d7194c00-a2e2-11eb-90d2-7d040bd937ba.png)

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by emilk** [comment]
This is a result of immediate mode - a separator fills the current width, but it can't know that there later will be a much wider label.

The same problem exists for all ui:s and windows. There really isn't a way around this as far as I can tell. Storing the width from the previous frame and using that as the width the next frame will prevent the menu from shrinking. There are immediate mode versions where the layout code is run twice - first to collect sizes, and then to draw - but egui doesn't do that, and switching to such a mode is not only a huge undertaking, but also has other downsides (~twice as slow).

The workaround is to call `ui.set_width` before the first label in the menu.

**Comment by optozorax** [comment]
Hm, but this works for regular windows in `egui`.

> prevent the menu from shrinking

Now I understand. We can shrink the regular window by hand, but the menu window isn't resizable, so the approach from regular windows doesn't fit here.

However, there is another way: remember only the size of non-filling widgets and use it for the next frame. This sounds like this can fix this issue and https://github.com/emilk/egui/issues/94. Also, this sounds like huge refactoring and a huge change of API.

**Comment by felipetesc** [comment]
Feedback: Using a state wrapper, defining inside it a min_width and then passing ui.set_width(min_width ) as the first line for each egui::menu::menu
fixed ui.separator's width and all button selection's width color for me.
