### ISSUE TITLE
Drag & Drop files into Egui Glium window

### ISSUE THREAD

**Issue by Tilix4** [emilk/egui#33]
It'd be very nice to be able to run an action when something is dropped in the area, is that possible?

**Comment by emilk** [comment]
Not currently, but it definitely on the road map. Please describe your use case in detail and I can prioritize!

**Comment by Tilix4** [comment]
I'd like to drop a file (or several) in the UI and to be able to get the file(s) path(s) of the dropped file(s). This will be a good start to analyse these files and determine the appropriate behaviour.

**Comment by emilk** [comment]
So dropping a file from outside of Egui? That is outside the scope of the `egui` library.

With `egui_glium` (or egui_winit) you can already look for file drop events (https://docs.rs/winit/0.23.0/winit/event/enum.WindowEvent.html#variant.DroppedFile) and then use things like [`ui.hovered()`](https://docs.rs/egui/0.2.0/egui/struct.Ui.html#method.hovered) so see if the mouse is above an Egui `Ui`. Would that work for you?

**Comment by Tilix4** [comment]
I believe yes!

**Comment by emilk** [comment]
Replaced by: https://github.com/emilk/egui/issues/270
