### ISSUE TITLE
Should `egui::Button`s change the cursor to PointingHand on hover?

### ISSUE THREAD

**Issue by zkldi** [emilk/egui#3311]
At the moment, mousing over an egui::Button does nothing, but I think it should change to `PointingHand` to be consistent with most other UIs.

For example, mousing over any button on this page, or in vscode, etc. will turn the cursor into `PointingHand`.

This could be achieved with `ctx.output_mut(|out| { out.cursor_icon = CursorIcon::PointingHand })` inside the `.hovered()` call for a button.

It would be painful to implement this everywhere yourself, so maybe it should just be part of the component itself?

**Comment by LoganDark** [comment]
this is a web browser thing that absolutely does not belong on native controls! leave this up to the user please and do NOT use the pointing hand cursor by default
