### ISSUE TITLE
Support floating scrollbars

### ISSUE THREAD

**Issue by martenbjork** [emilk/egui#3316]
When a view starts to overflow, scrollbars appear. These scrollbars take up physical space in the view, and pushes the content to the left. This causes a visual jump by a few pixels.

IMO, it would be better if the scrollbars floated on top of the content, like the default scrollbars on MacOS and iOS (and Window now as well, I believe?). That way, you avoid the jumpiness altogether.

https://github.com/emilk/egui/assets/875708/e0e54563-646a-4a5e-8a64-d6bb73096d20

**Comment by emilk** [comment]
The default scrollbars on MacOS and iOS are invisible until you start scrolling, which can be very confusing since it doesn't tell the user there is anything to scroll. Do you have a suggestion on how to resolve that?

If they are always visible, then they will always cover the content, which is not great. Of course, we can reserve some space for them, but then we are back to them not being floating anymore.

**Comment by YgorSouza** [comment]
In the Gnome desktop environment, the scrollbar disappears completely when the mouse is not moving, appears very thin when the mouse is moving far from it, and becomes wide when the mouse is close to it. 

[Screencast from 2023-09-18 20-53-18.webm](https://github.com/emilk/egui/assets/43298013/d7c9cd30-014d-4ffe-824a-e6287176e97c)

It can still block part of the UI if you don't put any margin, but I guess that's up to the UI designer to decide if that's a problem or not for their particular app.

![image](https://github.com/emilk/egui/assets/43298013/12941c40-b713-4172-995f-73c798b4e5ff)

**Comment by emilk** [comment]
Thats pretty neat - thanks @YgorSouza!

It doesn't quite solve it for touch screens though :/  Perhaps always showing the thin scroll bar makes sense for touch screens.

**Comment by martenbjork** [comment]
which can be very confusing since it doesn't tell the user there is anything to scroll. Do you have a suggestion on how to resolve that?

**Comment by martenbjork** [comment]
(accidental PR close — never mind)

> ...which can be very confusing since it doesn't tell the user there is anything to scroll. Do you have a suggestion on how to resolve that?

(Not trying to be salty! 👉 ) I'd argue that it's not the role of individual apps to correct the operating system's default affordances. IMO, if Apple and Microsoft thinks invisible scrollbars is the best solution for scrollable areas, I think we should follow their lead.

I think there are some exceptions:

- The scrollable content is unusual, so users might not recognize it as scrollable.
- The scrollbars provide useful info for the type of content you're working with (In code, they tell me how big my file is and where I am in it. It helps me find my way in the code.)

In the example of Rerun, the scrollable areas contain lists. My assumption as a user would be that they are scrollable. Not seeing the scrollbars by default wouldn't make me disoriented. `</assumtion>`

If we want to bump the affordance, I like the show-floating-scrollbars-on-hover approach. It's close to the OS default, but with a little extra affordance.
