### ISSUE TITLE
Merge of "change focused widgets with arrow keys" broke l/r keys use while editing single line text fields

### ISSUE THREAD

**Issue by apessino** [emilk/egui#3324]
Since https://github.com/emilk/egui/pull/3272 was merged in, the left/right arrow keys switch focus even while a *single line* text editing box is focused and text is being edited. This makes it impossible to move within the text being edited without using the mouse, which is of course not expected behavior.

To verify: run `egui_demo_app`, click to edit a single line text field, hit the left or right arrow keys and the text edit loses focus.

I only took a quick look at the code, but it seems that single line text fields don't "focus lock" because the tab key has always been used to end their editing, but now the arrow keys follow through and also cause the focus to move away.

**Comment by emilk** [comment]
Good catch - I'll make sure it is fixed before the next release
