### ISSUE TITLE
egui_extras feature http does not compile without the log feature being enabled too

### ISSUE THREAD

**Issue by lampsitter** [emilk/egui#3334]
**Describe the bug**
egui_extras does not compile with the http feature

**To Reproduce**
`cd crates/egui_extras && cargo c --features http` Compile error
`cd crates/egui_extras && cargo c --features http,log` Compiles

I seems to work fine with all the other image loading features.

**Expected behavior**
It compiles

**Comment by emilk** [comment]
I'll just make `log` a non-optional feature of `egui_extras`
