### ISSUE TITLE
Unicode Control Characters displaying incorrectly

### ISSUE THREAD

**Issue by OvermindDL1** [emilk/egui#336]
**Describe the bug**

Unicode control characters, such as in my case where I'm using Unicode Isolate marks (2068 and 2069), they are appearing as boxes in the text instead of not being displayed at all.  In the case of Unicode Isolate marks the text between 2068 and 2069 is directionality independent of the surrounding text, but this seems to happen with at least the part of the unicode control character range that I've run across so far.

**To Reproduce**
Render text anywhere in egui, such as in label, that including Unicode control characters, such as right-to-left encoding, or isolate characters.

**Expected behavior**
The control characters should be correcting how text is displayed, it should not be displaying boxes (they should not display anything at their location at all).

**Screenshots**

Here's an example where the string is `"Loading ⁨0.0199⁩"` (note there are isolate marks around the 0.00199 here, can copy/paste it from your browser, can be represented in rust inline via `"Loading \u{2068}0.0199\u{2069}"`):
![image](https://user-images.githubusercontent.com/401605/116148180-d0e9ed80-a69d-11eb-88f6-7950132eabd8.png)

**Desktop (please complete the following information):**
 - OS: Debian
 - Version 20.10

**Additional context**
Translating text via the `fluent` library and some languages aren't rendering right in text form in egui, this is the current big issue.  Disabling isolate marks in fluent for now but hitting other issues like right-to-left encoding in other languages.

**Comment by emilk** [comment]
`egui` doesn't at all support right-to-left languages yet, just FYI.

I guess for now the proper solution is to just ignore those characters. It would be easy to add a special case to `glyph_info` in `epaint/src/text/font.rs`, e.g. 

``` rust
if is_bidi_control(c) {
    GlyphInfo {
        id: glyph.id(),
        advance_width: 0.0,
        uv_rect: None,
    }   
}
```

If you have knowledge of exactly which marks needs ignoring it should be easy enough. There seems to be quite a few: https://www.w3.org/International/questions/qa-bidi-unicode-controls

**Comment by OvermindDL1** [comment]
All of the unicode control characters should not be rendered, can easily test out that entire range efficiently and just not render them at all.  In fact it's so common to do that Rust has a built in method for that as [`char::is_control`](https://doc.rust-lang.org/std/primitive.char.html#method.is_control) to test if a given character is a control character.  :-)

**Comment by OvermindDL1** [comment]
Hmm, sadly it doesn't catch `'\u{2068}'`as a control character..., interesting...  Might need a `unicode` crate for rust instead, or just manually test out the entire range, it is crafted in the spec to be really simple to test such a range.

Hmm, looks like rust's `is_control` just tests if it's a C0 rather than the full range, how mislabeled...

**Comment by OvermindDL1** [comment]
Ah, need to ignore the unicode Cf range as well, that looks like most of it?  `Cc`, `Cf`, and `Cn` should get it all.
