### ISSUE TITLE
`ImageSource::Bytes` docs should mention URIs are used for format detection

### ISSUE THREAD

**Issue by xTibor** [emilk/egui#3363]
**Describe the bug**
The new `ImageSource::Bytes` docs does not mention providing URIs are mandatory and used for format detection. This is kinda a significant detail.

Based on the [current docs](https://github.com/emilk/egui/blob/c07394b5766053fcdb5cb506e369f60a535a4800/crates/egui/src/widgets/image.rs#L498) one might think these URIs are there just for error reporting and egui is using some kind of format probing on the provided data instead. At least that's what I first thought trying out the new API.

**Comment by emilk** [comment]
Good point - will fix momentarily
