### ISSUE TITLE
memory is not cleared when using egui::Button (possible bug)

### ISSUE THREAD

**Issue by UnknownSuperficialNight** [emilk/egui#3365]
Here is my code as a example
```Rust
egui::ScrollArea::vertical().show(ui, |ui| {
                                    for (column_index, button_label) in
                                        self.merged_array[1].iter().enumerate()
                                    {
                                        if button_label.to_string() == self.selected.clone() {
                                            if ui
                                                .add(
                                                    egui::Button::new(button_label.to_string())
                                                        .fill(egui::Color32::from_rgb(153, 0, 153)),
                                                )
                                                .clicked()
                                            {
                                                if env::args().any(|arg| arg == "-d") {
                                                println!(
                                                    "Clicked item is in column: {}",
                                                    column_index
                                                );}
                                            }
                                        } else {
                                            if ui
                                                .add(
                                                    egui::Button::new(button_label.to_string())
                                                        .fill(egui::Color32::from_rgb(102, 0, 102)),
                                                )
                                                .clicked()
                                            {
                                            }
                                        }
                                    }
                                });
```

Merged_array[1] has around 10,000 elements in it, only adding around 10 MB to my total memory usage.

While the code above, when I run it against those 10,000 elements, it goes up to around 400 MB. I'm fine with that, but the problem is that when I overwrite the array with, let's say, 10 items, it stays the same allocation because of the buttons. It does not seem to clear the allocation when I loop over new items.

(Just to clarify, I add 10,000 items to the array. I loop over them with the code above. Then, I change the array to fewer items. Then, I loop over those items using the code block above. It should, in theory, since the old array is gone with all of its buttons, shrink to size, so to speak, and lower the memory allocation.)

**Comment by emilk** [comment]
You mean memory isn't being freed? Are you sure? Have you hooked up the allocator and counted (e.g. with [`re_memory`](https://crates.io/crates/re_memory)? You cannot trust what the OS tells you!

Also: you should be using https://docs.rs/egui/latest/egui/containers/scroll_area/struct.ScrollArea.html#method.show_rows

**Comment by UnknownSuperficialNight** [comment]
> Also: you should be using https://docs.rs/egui/latest/egui/containers/scroll_area/struct.ScrollArea.html#method.show_rows

Thank you i didn't see that it really helps :)

> You mean memory isn't being freed? Are you sure? Have you hooked up the allocator and counted (e.g. with [re_memory](https://crates.io/crates/re_memory)? You cannot trust what the OS tells you!

I used [heaptrack](https://milianw.de/blog/heaptrack-a-heap-memory-profiler-for-linux) to try and get the memory usage. Ill try using [re_memory](https://crates.io/crates/re_memory) and see what the results is

**Comment by emilk** [comment]
`re_memory` should be able to point you to the exact callstack of what is eating up your RAM

**Comment by UnknownSuperficialNight** [comment]
> `re_memory` should be able to point you to the exact callstack of what is eating up your RAM

haven't used re_memory yet but switching to [.show_rows](https://docs.rs/egui/latest/egui/containers/scroll_area/struct.ScrollArea.html#method.show_rows) did fix it 200 MB lower now and i did nothing but implement .show_rows

im going to close this for now since it's technically solved for me (if i had to guess id assume using the normal .show to render that many buttons without culling was the reason for the high memory )
