### ISSUE TITLE
Feature: tiny-skia as renderer

### ISSUE THREAD

**Issue by rawhuul** [emilk/egui#3367]
Currently, `egui` supports `glow` and `wgpu` as renderer, [tiny-skia](https://github.com/RazrFalcon/tiny-skia) which is also utilised by [iced](https://github.com/iced-rs/iced) could be a nice feature to have as it is very minimal and tiny like `egui` itself.

**Comment by emilk** [comment]
There already is one: https://github.com/lucasmerlin/egui_skia

You can find all 3rd party integrations (that I know of) here: https://github.com/emilk/egui#3rd-party-integrations

**Comment by rawhuul** [comment]
Thanks, but the following link uses `skia` not `tiny-skia` which I linked above

**Comment by emilk** [comment]
Oh, sorry!

Well, adding additional backends is outside of the scope of this repository - create a new repository and I'll add it to the list in https://github.com/emilk/egui#3rd-party-integrations !

**Comment by rawhuul** [comment]
okay, i will look into it
