### ISSUE TITLE
New memory not implementing `Send + Sync`

### ISSUE THREAD

**Issue by optozorax** [emilk/egui#337]
@mvlabat reported that new memory based on `Box<dyn Any + 'static>` didn't implement `Send` and `Sync`, and he can't send `CtxRef` to different places (maybe he use different threads for GUI and for other things).

This is possible to implement because `typemap` [has](https://docs.rs/typemap/0.3.3/typemap/type.ShareMap.html) this type of map.

But, do we want to restrict a user to only `Send + Sync` types in custom memory? Is it possible to have `!Send` and `!Sync` type that also implements `De-`/`Serialize`? (Sorry, I don't know much about this area of Rust)

If it's ok to require `Send + Sync` types in custom memory, then I will try to implement PR to fix this.

**Comment by emilk** [comment]
Good catch! Requiring `Send + Sync` for the values sounds like a fair requirement to me.

**Comment by mvlabat** [comment]
Can we also make sure that we won't break it in any other way in future? Whether somehow force it statically, or at least write an "integration" test that checks that `CtxRef` can be passed to a function that requires `Send + Sync`.

> maybe he use different threads for GUI and for other things

My actual use-case is passing `CtxRef` to a Bevy resource.

Thanks!

**Comment by emilk** [comment]
Adding a static regression check sounds very sensible
