### ISSUE TITLE
how can program icon flashes in the taskbar?

### ISSUE THREAD

**Issue by coolstudio1678** [emilk/egui#3370]
Can NativeOptions::icon_data be changed while the program is running? Sometimes, when the program is reduced to the taskbar, I want the program icon to flash, or are there other ways to make the icon flash?

**Comment by dscso** [comment]
I have the same problem, as I want to adjust the icon depending on the state of the application (If application is online or not)

**Comment by emilk** [comment]
If your goal is to get the users attention, you can use
https://docs.rs/egui/latest/egui/viewport/enum.ViewportCommand.html#variant.RequestUserAttention

**Comment by dscso** [comment]
For me I'd like to implement something similar to this:
<img width="80" alt="image" src="https://github.com/emilk/egui/assets/6866008/208d09c5-2b25-4049-8750-4dc71a0fa088">
I want to change the icon depending on the state of the program. Is there a way to access `NativeOptions` or `ViewportBuilder` from inside the `fn update(&mut self, ctx: &egui::Context, frame: &mut eframe::Frame)` method?

**Comment by emilk** [comment]
You can change the icon by sending a `ViewportCommand::Icon` with `ctx.send_viewport_cmd`
