### ISSUE TITLE
Allow creation of large window that can exceed the monitor size

### ISSUE THREAD

**Issue by EvinceMoi** [emilk/egui#3389]
**Is your feature request related to a problem? Please describe.**
When I set `initial_window_size` in `eframe::NativeOptions` with large value (bigger than the logical size of the monitor), the size is chop by [largest_monitor_point_size](https://github.com/emilk/egui/blob/master/crates/eframe/src/native/epi_integration.rs#L203C14-L217), this blocks some cases like displaying a workspace screenshot on multiple monitors, like #3185, or display high resolution pic/videos in actical size. I'm curious about the reason behind it.

**Describe the solution you'd like**
maybe add a option like `unbounded_size: bool` the disable the max window restriction?

**Describe alternatives you've considered**
N/A

**Additional context**
An simple example(all values are logical)
| monitor | x | y | width | height |mode|
|-|-|-|-|-|-|
|m1|0|0|1080|1920|portrait|
|m2|1080|840|1920|1080|landscape|

with this setup, a window across all screen should have the size of `3000x1920`. Setting `initial_window_size` to `3000x1920` , `initial_window_pos` to `0, 0`, a window at `0, 0` with size `1920x1080` wat created in my case.

**Comment by lopo12123** [comment]
Hello @emilk , is there any progress on this issue? I would like to know what the motivation is for using largest_monitor_point_size, and whether it is possible to provide a bool value for users to choose whether to apply this option.

**Comment by emilk** [comment]
The motivation can be found here:

https://github.com/emilk/egui/blob/2342788973120552c012f028bfda576fea87738b/crates/egui-winit/src/window_settings.rs#L97-L99

And yes, we can make that a `bool`, though I suggest we avoid negations in names and go with `clamp_size_to_monitor_size` or something like that, and default it to `true` only on Linux? 🤷 

PRs welcome!

**Comment by lopo12123** [comment]
Thanks for the answer🙇‍

If the situation on linux is the only thing to consider, then I would try adding this field and then pr.

It may take me four or five days (I have three days off next and I have to go to the company to have multiple monitors for testing)
