### ISSUE TITLE
 getting and mutating translation/zoom state for a pane?

### ISSUE THREAD

**Issue by briteroses** [emilk/egui#3414]
Hi, I'm building an app on top of egui where I have multiple panes with displaying similar plots / 2d maps. Currently I can use mouse drag or the mouse wheel scroll to zoom in/out or translate the viewing area to a different part of the plot. I'm hoping to build a functionality where the translation/zoom of the current viewing is applied identically to all of my panes. As far as I've explored, egui does not expose these viewing state parameters to the user. Would it be possible for the viewing states to be exposed? Or is this functionality already possible and I just didn't realize it?

**Comment by YgorSouza** [comment]
If you just want to have identical bounds on multiple plots, there is [link_axis](https://docs.rs/egui_plot/0.23.0/egui_plot/struct.Plot.html#method.link_axis). If you want to do something custom like making one bound have the same center as the other but be twice as big, you can read the bounds with [plot_bounds](https://docs.rs/egui_plot/0.23.0/egui_plot/struct.PlotUi.html#method.plot_bounds) and set with [set_plot_bounds](https://docs.rs/egui_plot/0.23.0/egui_plot/struct.PlotUi.html#method.set_plot_bounds).
