### ISSUE TITLE
Vertical Sliders are upside down as of egui 0.23

### ISSUE THREAD

**Issue by zkldi** [emilk/egui#3422]
**Describe the bug**

As of egui 0.23, vertical sliders are upside down -- the largest value is at the bottom and the smallest value is at the top.

**To Reproduce**
1. https://www.egui.rs/
2. Click on Sliders
3. Make them vertical

**Expected behavior**

The largest values should be at the top of the slider.

**Screenshots**

![image](https://github.com/emilk/egui/assets/20380519/5ff01444-fc68-4b7f-9963-d66693ed38e5)

**Comment by YgorSouza** [comment]
It seems that this was caused by 8cdffc4e2d66d54f3059b3a31fac924f630dce8b.
