### ISSUE TITLE
eframe w/ wgpu breaks after latest Xcode update

### ISSUE THREAD

**Issue by segfault87** [emilk/egui#3433]
**Describe the bug**
After upgrading to Xcode 15, running `egui_demo_app` with wgpu looks like the screenshot below.

When adding `multisampling: 4` to `eframe::NativeOptions`, initialization fails with following error message.
```
❯ cargo run --release --features wgpu
   Compiling egui_demo_app v0.23.0 (/Users/segfault/Projects/egui/crates/egui_demo_app)
    Finished release [optimized] target(s) in 0.40s
     Running `/Users/segfault/Projects/egui/target/release/egui_demo_app`
[2023-10-03T02:38:27Z WARN  wgpu_core::device::global] Requested size 4294967295x4294967295 is outside of the supported range: Extent3d { width: 4, height: 4, depth_or_array_layers: 1 }..=Extent3d { width: 16384, height: 16384, depth_or_array_layers: 1 }
2023-10-03 11:38:27.988 egui_demo_app[64740:2678202] CAMetalLayer ignoring invalid setDrawableSize width=4294967295.000000 height=4294967295.000000
[2023-10-03T02:38:27Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_texture
      note: label = `egui_msaa_texture`
    Dimension X value 4294967295 exceeds the limit of 8192

', /Users/segfault/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:3056:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**

1. Upgrade to Xcode 15 and run egui_demo_app with `wgpu` feature flag
2. Broken screen shows up
3. Add `multisampling: 4` to `eframe::NativeOptions` at `egui_demo_app/src/main.rs`
4. Build and run

**Expected behavior**
App runs without any problems

**Screenshots**
<img width="1450" alt="image" src="https://github.com/emilk/egui/assets/424089/1c530e02-5ad3-4b64-997a-ffab6a9ef43d">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Sonoma

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by segfault87** [comment]
Using latest egui from git fixed the problem. Closing this issue.

**Comment by lucasmerlin** [comment]
I'm also having the same problem after updating MacOS to Sonoma. Neither checking out the latest master or the wgpu-0.18 branch fixes this for me. 
Can you share which commit hash and which branch you switched to to make things work again @segfault87?

For me after resizing the window things look normal again. 

I'm running the demo app with `cargo run --bin egui_demo_app --features wgpu --no-default-features`

**Comment by zhouhang95** [comment]
I use to delete Cargo.lock to resolve it.
