### ISSUE TITLE
Add redo to Undoer

### ISSUE THREAD

**Issue by YgorSouza** [emilk/egui#3447]
**Is your feature request related to a problem? Please describe.**

The `Undoer` does not have a redo functionality, and thus neither does the `TextEdit`. most text boxes that have undo also have redo, and there is a TODO for it in the source code.

https://github.com/emilk/egui/blob/38b4234c3282a7c044c18b77234ee8c204efe171/crates/egui/src/widgets/text_edit/builder.rs#L987-L988

**Describe the solution you'd like**

The `Undoer` should push undone states to a redo stack, and have a `redo()` method that can be called to revert the `undo()` call, as well as a `has_redo()` method to help set the enabled/disable state for the corresponding UI button.

**Describe alternatives you've considered**

It might be possible to check the state of `has_undo()` before and after calling `feed_state()` or `add_undo()`, and push a state to a redo stack stored separately, but that seems complicated and error-prone, and this feature is needed for the `TextEdit` anyway, so it may as well be provided by the `Undoer`.

**Additional context**

I am willing to try to implement this feature myself, but I would like to know if there are any pitfalls I should consider, that might have prevented it from being implemented until now.

**Comment by LoganDark** [comment]
> any pitfalls I should consider, that might have prevented it from being implemented until now

Seems like just laziness :)

I'm the author of the PR that just landed to close this.
