### ISSUE TITLE
 Sogou Input Method window cannot be located near the text box

### ISSUE THREAD

**Issue by 12089897411** [emilk/egui#3463]
When using Sogou Input Method in China, the input method window cannot be located near the text box and always appears at the bottom of the screen.
Sogou Input Method has 530 million users in China, and we hope to make it compatible with this input method.

The default setting for Sogou Input Method is for the input window position to follow the location of the input cursor. Maybe this input cursor is a concept in Windows, but I am not entirely sure.

Test in egui example: use chinese to in put ‘你好’
Testing environment: Windows 11. egui 0.23.0

Sogou Input Method download:

**Comment by kapaseker** [comment]
老哥，放个截图

**Comment by 12089897411** [comment]
https://github.com/emilk/egui/assets/108512675/1affded3-1eec-4742-a3d5-73a042090e08

**Comment by suzp1984** [comment]
<img width="415" alt="Screenshot 2023-10-13 at 9 52 28 PM" src="https://github.com/emilk/egui/assets/2757043/74087b52-cf02-4480-96da-5ad38aacafa5">

Can not reproduced on my mac os 14.0.

**Comment by zhoujun681** [comment]
The same porblem on xunfei input,but  Microsoft input method is normal!

**Comment by tingfeng-key** [comment]
解决了吗？
