### ISSUE TITLE
Need expose the `PlotItem` trait.

### ISSUE THREAD

**Issue by griffenliu** [emilk/egui#3464]
I wish to expose the PlotItem trait so that I can define my own PlotItem.
`pub(super) trait PlotItem` to `pub trait PlotItem`.

**Comment by dwuertz** [comment]
While `PlotItem` has recently been exposed to the public API, there is one missing piece left which is to also make `egui_plot::items::values::PlotGeometry` public on which `PlotItem` depends. Since everything else is already there, this seems like an oversight?
