### ISSUE TITLE
Allow egui-wgpu on Wasm Atomics

### ISSUE THREAD

**Issue by cwfitzgerald** [emilk/egui#3467]
**Describe the bug**

I have a use case where we use wgpu with wasm atomics and currently egui-wgpu doesn't work with wasm atomics enabled. This is blocking us from bumping wgpu versions. I thought initially that 0.18 would remove lifetimes from renderpasses, causing this issue to magically fix itself too, but that's actually more difficult than it seems and won't happen for the next couple versions.

**Comment by cwfitzgerald** [comment]
Totally missed https://github.com/emilk/egui/commit/b896d641c578c04603adf07a9350b8bfc3c7ed9f which fixes the issue

**Comment by bezdomniy** [comment]
@cwfitzgerald - can you please tell me how that PR fixed the issue? I am having the same problem as you I think.

I tried building the egui_demo_app with target-feature=+atomics and it still failed.
