### ISSUE TITLE
ImageButton with rotated Image - Button doesn't match Image

### ISSUE THREAD

**Issue by Ya-hwon** [emilk/egui#3471]
**Describe the bug**

If the contained image of an ImageButton is rotated, the button rect remains unchanged, causing a mismatch.

**To Reproduce**
[repro repo](https://github.com/Ya-hwon/rotated_image_repro)
```rust
use std::f32::consts::FRAC_PI_2;
use eframe::{
    egui::{self, Image, ImageButton},
    epaint::Vec2,
};

fn main() {
    let mut rotation_angle = 0f32;

    eframe::run_simple_native(
        "rotated image button test",
        eframe::NativeOptions::default(),
        move |ctx, _frame| {
            egui_extras::install_image_loaders(&ctx);
            egui::CentralPanel::default().show(ctx, |ui| {
                let image = {
                    let mut image = Image::new(egui::include_image!("../img.jpeg"));
                    if rotation_angle != 0f32 {
                        image = image.rotate(rotation_angle, Vec2::splat(0.5));
                    }
                    image
                };
                let img_btn = ui.add(ImageButton::new(image));
                if img_btn.clicked() {
                    rotation_angle += FRAC_PI_2;
                }
                if img_btn.secondary_clicked() {
                    rotation_angle -= FRAC_PI_2;
                }
            });
        },
    )
    .unwrap();
}
```
- Run and click the image.

**Expected behavior**
The Button rect changes to match the Image - with a 90° rotation width becomes height and height becomes width.

**Screenshots**

![image](https://github.com/emilk/egui/assets/37835539/d4378007-db88-4cb3-ac53-d177b05335bf)

**Desktop (please complete the following information):**
 - OS: Windows 10 10.0.19045 Build 19045

**Additional context**

/

**Comment by YgorSouza** [comment]
Probably the same issue as #3341.

**Comment by Ya-hwon** [comment]
> Probably the same issue as #3341.

Yes, looks like it
Sorry - I thought this was about the ImageButton so I always included 'button' in my searches so didn't see the other one.

Closing as duplicate.
