### ISSUE TITLE
Plot documentation not found

### ISSUE THREAD

**Issue by PrethamMuthappa** [emilk/egui#3472]
In the official documentation of egui , there is not plot section available 
 <a href="https://docs.rs/egui/latest/egui/?search=plot" >Docs link</a>, as you can see in this link , we have no information on how we can plot graphs in egui , its the same even for the eframe docs

**what can be done**

Add new documentation section for plotting graphs and maps too

**Comment by YgorSouza** [comment]
The plot functionality has been moved to its own crate. <https://docs.rs/egui_plot/latest/egui_plot/>. See also  #3282 and #3441.
