### ISSUE TITLE
Slider unable to produce range of odd values

### ISSUE THREAD

**Issue by ExpertOfNil** [emilk/egui#3483]
**Description**

When defining the `egui::Slider` bounds with a range having odd bounds (e.g. `3..=31`) and step size of `2_f64`, instead of having selectable values {3, 5, 7, ..., 29, 31}, values {4, 6, 8, ..., 30, 31} are provided.  This is not remedied with `.clamp_to_range(true)`.  Similarly, providing a range `3..=501` and a step size of `2_f64` produces values {4, 10, 20, 30, ..., 490, 500, 501}.  _NOTE_ this scenario is also not remedied by using ranges starting at 1.0, either.

**To Reproduce**

```rust
egui::Grid::new("CameraConfigGroup")
    .num_columns(2)
    .spacing([40.0, 4.0])
    .striped(true)
    .show(ui, |ui| {
        ui.add(egui::Label::new("Value 1:"));
        ui.add(
            egui::Slider::new(&mut self.slider_value1, 3.0..=31.0)
                .step_by(2_f64)
                .fixed_decimals(1),
        );
        ui.end_row();
        ui.add(egui::Label::new("Value 2:"));
        ui.add(
            egui::Slider::new(&mut self.canny_edges.threshold2, 3.0..=501.0)
                .step_by(2_f64)
                .fixed_decimals(1),
        );
    });
```

**Expected Behavior**

* Value 1: Selectable values {3.0, 5.0, 7.0, ..., 29.0, 31.0}
* Value 2: Selectable values {3.0, 5.0, 7.0, ..., 499.0, 501.0}

**Actual Behavior**

* Value 1: Slider _may_ start at 3.0, but once moved, it will only provide values {4.0, 6.0, 8.0, ..., 30.0, 31.0}, even when manually editing the text value
* Value 2: Slider _may_ start at 3.0, but once moved, it will only provide values {4.0, 10.0, 20.0, ..., 490.0, 500.0, 501.0}.  Manually editing the text will only allow even numbers, with the exception of 501.0.

**Screenshots**

![image](https://github.com/emilk/egui/assets/97487335/57224350-3d41-403d-9f4e-7d8631fef605)
![image](https://github.com/emilk/egui/assets/97487335/11f19f6d-cdce-4092-b282-7956a484cd5e)
![image](https://github.com/emilk/egui/assets/97487335/73b6125b-7602-4d36-9b4d-e0f347c30373)
![image](https://github.com/emilk/egui/assets/97487335/eff9d07b-b514-4a1a-81af-6d6a5648b4f0)

**Hypothesis**

I believe this may be the cause of the issue [(slider.rs, lines 501-514)](https://github.com/emilk/egui/blob/fd75adb3a0e5f8ca373ac7e5e03f750e690ae87b/crates/egui/src/widgets/slider.rs#L501C6-L501C6):
```rust
fn set_value(&mut self, mut value: f64) {
    if self.clamp_to_range {
        let start = *self.range.start();
        let end = *self.range.end();
        value = value.clamp(start.min(end), start.max(end));
    }
    if let Some(max_decimals) = self.max_decimals {
        value = emath::round_to_decimals(value, max_decimals);
    }
    if let Some(step) = self.step {
        value = (value / step).round() * step;
        // should be: value = (value + step).round()?
    }
    set(&mut self.get_set_value, value);
}
```
**Desktop**
 - OS: Ubuntu 20.04
 - Eframe: v0.23.0
   - Also tried using `eframe = { git = "https://github.com/emilk/egui", branch = "master", features = ["persistence"] }`

**Comment by YgorSouza** [comment]
The solution is probably to take the start of the range into account when rounding.

```rs
if let Some(step) = self.step {
    let start = self.range.start();
    value = start + ((value - start) / step).round() * step;
}

```

**Comment by ExpertOfNil** [comment]
If I'm understanding what's going on in `Slider::set_value` correctly, it can be mocked up using `Slider::from_get_set`:
```rust
let range = 3.0..=31.0;
let start = *range.start();
ui.add(egui::Slider::from_get_set(
    range,
    |v: Option<f64>| -> f64 {
        if let Some(v) = v {
            self.slider_value = start + ((v - start) / 2_f64).round() * 2_f64;
        }
        return self.slider_value;
    },
));
```
Using @YgorSouza suggestion, I get the desired behavior.

**Comment by emilk** [comment]
Yeah, I agree that the step should start at the start value, and @YgorSouza's solution seems sounds - please make a PR 🙏
