### ISSUE TITLE
ImageButton ignoring input Image rounding

### ISSUE THREAD

**Issue by v-kat** [emilk/egui#3486]
```Rust
ui.add(ImageButton::new(
    egui::Image::new(SizedTexture::new(
        *a_texture_id,
        egui::Vec2::new(1.0, 1.0)
    )).rounding(50.0)
));
```
https://github.com/emilk/egui/blob/master/crates/egui/src/widgets/button.rs#L620 is the problem line I believe

**Expected behavior**
The image button should respect the input image's rounding. There should also maybe be an exposed `.rounding` method on the `ImageButton`. I might try to fix this later myself....

**Comment by chriscate** [comment]
@v-kat did you end up working on this? I'm looking for ways to get comfortable with contributing to egui and the code base in general. Thinking this bug may be a nice intro if you didn't already take it on.

**Comment by v-kat** [comment]
I haven't thanks for asking. You can go ahead with it. I also wanted to checked on keyboard support for `ImageButton` and `menu_image_button` too. https://github.com/emilk/egui/pull/3288 is an example small PR

**Comment by chriscate** [comment]
great thanks!

**Comment by chriscate** [comment]
@v-kat I opened draft PR for this last night. If you get a moment just let me know if there's anything you would change and if not I'll mark it ready for review. I did mention in the PR too that a new `rounding()` method on the `ImageButton` itself could be a separate issue/enhancement. Let me know if you disagree though.
