### ISSUE TITLE
Integration testing/event injection

### ISSUE THREAD

**Issue by svenstaro** [emilk/egui#3491]
I didn't find _anything_ about this in this whole project which is odd so I think the following should be considered a feature request.

There's currently no documented (or even possible?) way to do integration testing/event injection/instrumentation for the purposes of integration testing. It's probably possible to abuse the [new accessibility features](#167) for that like in other frameworks but it would still be good to have an official way for doing this for people that want to test their UIs.

**Comment by YgorSouza** [comment]
Wouldn't that be the same as any other integration? In which case you could follow the instructions in <https://docs.rs/egui/0.23.0/egui/index.html#integrating-with-egui>.

**Comment by svenstaro** [comment]
It might be, but this issue is about documenting the flow for integration testing in an obvious manner. I'll give it a shot and maybe make a MR.

**Comment by drewmiller** [comment]
> It might be, but this issue is about documenting the flow for integration testing in an obvious manner. I'll give it a shot and maybe make a PR.

Consider the Imgui test engine here: https://github.com/ocornut/imgui_test_engine. It seems like something similar should be on the roadmap.

**Comment by xiyuzhai** [comment]
I'm also confused about what to do for continuous integration.

**Comment by emilk** [comment]
Some automated testing of an egui app would be great, and I think the best approach might be to interface with `accesskit`, both for reading the location of widgets and for automating interaction with them. That way the same code can be reusable across GUI toolkits (i.e. not be egui specific)
