### ISSUE TITLE
egui-wgpu docs failed to build on docs.rs

### ISSUE THREAD

**Issue by abey79** [emilk/egui#3492]
See https://docs.rs/crate/egui-wgpu/0.23.0

**Comment by abey79** [comment]
I believe this is related to https://github.com/emilk/egui/pull/3228. I got that error on my CI when updating to egui 0.23 (https://github.com/abey79/vsvg/pull/54). Without the x11 or wayland feature, winit isn't able to detect the platform on linux (https://github.com/rust-windowing/winit/blob/772b21ce095b655f0fe50b89253910cd2ff9fa78/build.rs#L13). My workaround was to run that part on a mac runner, which is probably not an option for docs.rs.

**Comment by abey79** [comment]
winit issue: https://github.com/rust-windowing/winit/issues/3173

**Comment by tgross35** [comment]
This is still an issue at 0.24.0 https://docs.rs/crate/egui-wgpu/0.24.0

**Comment by tgross35** [comment]
But they seem to build fine on my local, weird...
