### ISSUE TITLE
ctx.request_repaint_after makes app repaint constantly and not after set duration

### ISSUE THREAD

**Issue by trsh** [emilk/egui#3507]
```
[dependencies]
eframe = "0.23.0"
egui = "0.23.0"
rfd = "0.12.1"
```

**Describe the bug**
`ctx.request_repaint_after` makes app repaint constantly and not after set duration

**To Reproduce**
1. Take https://pastebin.com/raw/6kMba2X5
2. Run, see button getting wider, despite there is no mouse or keyboard input and large (but valid) `request_repaint_after` duration
3. Comment `ctx.request_repaint_after(dur);` and run again
4. Button gets wider only on input

**Expected behavior**
`request_repaint_after` should request repaint after set duration, not act as instant repaint request

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Rust: rustc 1.73.0 (cc66ad468 2023-10-03)

**Comment by YgorSouza** [comment]
Same as #3109. It only affects Windows, due to a workaround for winit introduced in egui 0.22, as discussed there.

**Comment by trsh** [comment]
Closing because dupe of https://github.com/emilk/egui/issues/3109
