### ISSUE TITLE
 eframe should persist pixels_per_point

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [emilk/egui#3519]
It would be nice if the "persistence" feature saved the current `pixels_per_point`.

**Is your feature request related to a problem? Please describe.**
Currently eframe forgets the app's zoom-level every time it closes, 
and the next time the app opens the user needs to zoom in again to their desired zoom-level.

**Describe the solution you'd like**
I'd like for eframe to store the current `pixels_per_point` alongside the other window size & position data.

This obviously can not apply to web pages, which have their own scaling/zooming tools.

**Additional context**
This is a minor feature and it seems like it should be simple to implement.
Here is my solution:
```
impl eframe::App for MyApp {
    fn save(&mut self, storage: &mut dyn eframe::Storage) {
        storage.set_string("zoom_level", format!("{}", self.ctx.pixels_per_point()));
    }
}
```
```
impl MyApp {
    fn new(cc: &eframe::CreationContext<'_>) -> Self {
        if let Some(storage) = cc.storage {
            if let Some(zoom_level) = storage.get_string("zoom_level") {
                cc.egui_ctx.set_pixels_per_point(zoom_level.parse().unwrap());
            }
        }
    }
}
```

**Comment by stonerfish** [comment]
How do you set the pixels_per_point.  Are you calling set_pixels_per_point()?
Make an item in your App struct that contains  value that you want to set the pixels_per_point to.  Then on you first update() call set_pixels_per_point().  The values in your App struct should be saved automagic.

**Comment by emilk** [comment]
Replaced with https://github.com/emilk/egui/issues/3602
