### ISSUE TITLE
Better `changed` union UX

### ISSUE THREAD

**Issue by ckiee** [emilk/egui#3522]
**Is your feature request related to a problem? Please describe.**
~~I'd like `?`-like (maybe) bubbling for `.changed()`.~~ Currently I have to bubble `InnerResponse<bool>`s and OR them until I get to the root of the form which makes for very ugly code:

- I have this form that requires manual re-submission once it's all done: https://github.com/ckiee/desk-fcobs/blob/1487181fde7d3c23cac169be74b09d60c2134c28/ledc/src/ui.rs#L147-L181
- This strip controls "component" which has two controls that need to be bubbled in order to trigger an update on my I/O thread: https://github.com/ckiee/desk-fcobs/blob/1487181fde7d3c23cac169be74b09d60c2134c28/ledc/src/ui.rs#L52-L76; [**This one is trickier**](https://github.com/emilk/egui/issues/3522#issuecomment-1817553724).

**Describe the solution you'd like**
~~Maybe add a `change` field to `egui::Sense`?~~ No longer sure.

~~Describe alternatives you've considered~~

**Additional context**

You can run `ledc` from the `desk-fcobs` repository pretty easily if you want to try this. But it won't do anything since it won't be able to connect to the serial port.

**Comment by YgorSouza** [comment]
I think what you are looking for is the [union](https://docs.rs/egui/0.23.0/egui/struct.Response.html#method.union) method.

For example, here is the hello_world example modified to count changes made to the form:

```rs
impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {
            ui.heading("My egui Application");
            let mut form_response = ui
                .horizontal(|ui| {
                    let name_label = ui.label("Your name: ");
                    ui.text_edit_singleline(&mut self.name)
                        .labelled_by(name_label.id)
                })
                .inner;
            form_response = ui
                .add(egui::Slider::new(&mut self.age, 0..=120).text("age"))
                .union(form_response);
            if ui.button("Click each year").clicked() {
                form_response.mark_changed();
                self.age += 1;
            }
            if form_response.changed() {
                self.total_changes += 1;
            }
            ui.label(format!("Hello '{}', age {}", self.name, self.age));
            ui.label(format!("Total changes: {}", self.total_changes));
        });
    }
}
```

For your first example, you could create a function/closure `schedule_grid_ui(ui: &mut Ui) -> Response`, and return a response that is the union of all the responses from the editable widgets (or the widgets you care about), then do `if schedule_grid_ui(ui).changed() {...}`.

**Comment by ckiee** [comment]
Oh, that's quite good (:  I suppose the `Sense` idea was wrong since that seems to be the _input_ to the widget/`Ui`?

But it is still lacking, I'd have to manually reduce over an array of `Ui`s and that seems very messy.

**Comment by YgorSouza** [comment]
Yes, `Sense` is for the widget to tell the Ui what input events it's interested in, while the `changed` flag is set by the widget's own logic. So I think you do have to write the logic for how to combine the responses of the individual widgets in your form. The alternative would be for the Ui to intercept the responses somehow and combine them, but I don't know where that would even happen.

Consider the `toggle_switch` sample:

<https://github.com/emilk/egui/blob/3a8ed37f491e2bf63395632bb9e98c6ed198ae67/crates/egui_demo_lib/src/demo/toggle_switch.rs#L73-L96>

It initially gets a response from the Ui, to see if the area has been clicked. Then, the logic for this particular widget dictates that it changes when it is clicked, so it calls `mark_changed` as appropriate. But at this point the Ui no longer has access to the `Response`, it is returned to the caller. So it is up to the caller who is using the widget as part of an Ui to decide what to do with its response.

Actually, I just looked at the docs again and there is a trait implementation meant specifically for that, that I hadn't noticed before: <https://docs.rs/egui/0.23.0/egui/struct.Response.html#impl-BitOr-for-Response>

So you can just do:

```rs
ui.add(Slider::new(&mut strip.0, 0..=65535).text("cold"))
| ui.add(Slider::new(&mut strip.1, 0..=65535).text("warm"))
```

Then I guess it's a matter of breaking the UI code down into small functions that return `Response`, so this is easier to write and keep track of.
