### ISSUE TITLE
Update to winit 0.29

### ISSUE THREAD

**Issue by cybersoulK** [emilk/egui#3542]
It brings a lot of fixes, specially to the wasm backend.
So it's a priority bump for web apps that use egui.

A few that i am aware are:
resize fixes
firefox pointers/mouse scroll issues
fixes to window animation loop

**Comment by dbalsom** [comment]
Winit 0.29 also fixes some major issues with international keyboards. There are entire characters you can't send to egui like ':' on Italian layouts.
