### ISSUE TITLE
Feature request: Slider without the slider

### ISSUE THREAD

**Issue by wareya** [emilk/egui#3563]
**Is your feature request related to a problem? Please describe.**

I'm making an image editor and just got around to adding a New File popup window. I need to add height and width fields. To support this I need numeric text entry. The slider widget already has this, and is fully-featured, supporting logarithmic scrubbing, range limits, etc, so hacking a number entry out of TextEdit would be worse than using a Slider. 

**Describe the solution you'd like**

In this popup window, for setting the height and width of the new image, I don't want the actual slider part, just the number part.

**Describe alternatives you've considered**

I could use the slider with the slider part, but it would make my interface look and feel tacky/hacked together.

**Additional context**

N/A

**Comment by RuboGubo** [comment]
maybe just fix the documentation then

**Comment by wareya** [comment]
DragValue doesn't have all the functionality that Slider has.

**Comment by emilk** [comment]
This is just `DragValue`

**Comment by wareya** [comment]
Should I open an issue asking to add the missing functionality from Slider to DragValue, then? (i.e. `step_by` and logarithmic/exponential support)

**Comment by emilk** [comment]
`step_by` is missing true, but exponential drag-value is really just a drag-value with a `.speed` that is proportional to the magnitude of the current value

**Comment by nixpulvis** [comment]
Is there a way I can change the underlying speed value of a slider? I need to change the base of the logarithm for scaling somehow.
