### ISSUE TITLE
Feature request: eframe demo with continuous delivery workflow

### ISSUE THREAD

**Issue by sdasda7777** [emilk/egui#3569]
Hi, I've been trying to set up continuous delivery workflow for my eframe project using [rust-build.action](https://github.com/rust-build/rust-build.action), but the Linux builds don't seem to work. I tried to debug it ([bit more details](https://github.com/rust-build/rust-build.action/issues/85 )), but I just don't seem to have the knowledge of both projects to make it work, or even tell where exactly the issue is. Would it be possible for you to set up a demo with continuous delivery workflow, so that it's clear it's not an issue with egui/eframe?

**Comment by emilk** [comment]
This repository deploys a new web demo each merge to main using https://github.com/emilk/egui/blob/master/.github/workflows/deploy_web_demo.yml

`eframe_template` too, `trunk`: https://github.com/emilk/eframe_template

**Comment by sdasda7777** [comment]
Hi, thanks for the reply, but I'm personally not really interested in web version, rather the executables. I know in theory everyone should be able to build it the project with `cargo run`, but in practice I don't think I should expect everyone to know how to do it.
