### ISSUE TITLE
Introduce a persistent `zoom_factor`

### ISSUE THREAD

**Issue by emilk** [emilk/egui#3602]
Currently we have `pixels_per_point` which the user can change with `ctx.set_pixels_per_point`. However, it is confusing how that works when e.g. dragging an eframe window from one monitor to another with a different pixel density.

I suggest we introducer a `zoom_factor: f32` (default 1.0) which would be a multiplier on top of the native pixels_per_point. This means dragging a window from one monitor to another would keep the same `zoom_factor` (e.g. 120%), even though the monitors might have different pixel densities.

I'd also like to build-in the cmd+/- gui scaling to egui, which would then operator on `zoom_factor`.

`zoom_factor` would thus replace a settable `pixels_per_point`. `Context` would instead computer `pixels_per_point` as `zoom_factor * native_pixels_per_point`, where `zoom_factor` is read/write, and `pixels_per_point` is read-only.

We would then persist `zoom_factor` in `egui::Memory`.

This is essentially what we do manually at Rerun: https://github.com/rerun-io/rerun/pull/1448/files

----

One wrinkle is: what unit to use for input/output? Currently we use UI "points" everywhere, e.g. when describing mouse coordinates and output triangle vertices.

This means integrations would need to ask for `Context::pixels_per_point()` to calculate it.
We could also change the input/output interface to use native pixels for everything, but that's a pretty big change, and can lead to many subtle bugs.

**Comment by Resonanz** [comment]
Suggestion: allow setting limits on the zoom factor. 

Useful, for example, for limiting the end user's ability to change scaling outside of the limiting bounds of say 1.0  and 1.5.

**Comment by Resonanz** [comment]
Pressing Ctrl + plus or minus changes the zoom factor.

However, in the code below, pressing and holding this key combination results in the scaling jumping back and forth.

Why would the scaling jump around if the zoom factor is applied at the beginning of each redraw cycle?  Doesn't this code lock the zoom factor to 1.0?

```
impl eframe::App for TemplateApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        ctx.set_zoom_factor(1.0);
```
