### ISSUE TITLE
Plotting: Add line markers

### ISSUE THREAD

**Issue by EmbersArc** [emilk/egui#362]
It would be great to have line markers for curves in the plotting library. It's mostly done but there are still some open questions that I'll have to figure out when it comes to user friendliness. I'll open a draft PR soon.

![image](https://user-images.githubusercontent.com/1352472/117565381-27e5be80-b0b1-11eb-9674-b21c1dc99afe.png)

**Comment by emilk** [comment]
Can I ask what this is for?

I thought line markers were used mostly when printing plots in black-and-white. Is there really a need for it in a full-color interactive plot? And if there is a need for something like this, isn't dashed and dotted lines more readable?

**Comment by EmbersArc** [comment]
The initial idea was to add scatter plots (no lines, only points). But those share all the functionality with the `Curve` datatype we currently have, and only really differ in appearance. So I did not want to create a separate datatype just for that. This is an attempt to unify those so that curves can also be used as scatter plots. I'm also making the markers very configurable, so something like this is possible as well:
![image](https://user-images.githubusercontent.com/1352472/117571438-dba97700-b0ce-11eb-9677-8d307c06d3b6.png) 
This is important when working with real data and you want to show where the actual datapoints are.

I hope this makes sense, you can have a look at the draft PR to see how it's implemented right now. Maybe you even have a better idea.

**Comment by EmbersArc** [comment]
Based on experience, I can confirm that it's sometimes very useful to have a small selection of marker shapes to choose from. They may have different meanings in the plot and then it could be confusing to only have dfiferent colored dots. But I understand your concerns @emilk so I took some time to figure out how to keep functionality simple while still making different marker shapes available. Now, you can add a default marker to the plot like this:

```rust
        Curve::from_parametric_callback(
            move |t| ((2.0 * t + time).sin(), (3.0 * t).sin()),
            0.0..=TAU,
            100,
        )
        .color(Color32::from_rgb(100, 150, 250))
        .marker(Marker::default())
        .name("x = sin(2t), y = sin(3t)")
```
This will add filled dots to the datapoints with the same color as the line, as suggested by @skairunner as well. But they can be customized further (within reason) like this:
```rust
curve.marker(marker.filled(false).radius(5.0).color(Color32::GRAY))
```

I extended the plot demo a bit so that we can showcase this:

https://user-images.githubusercontent.com/1352472/117843780-6b8e2300-b27f-11eb-9534-485d3d34920b.mp4
