### ISSUE TITLE
egui v0.24.0 Bug Report : custom_window_frame, multiple_viewports

### ISSUE THREAD

**Issue by rustbasic** [emilk/egui#3635]
Subject: egui v0.24.0 Bug Report

Dear Emilk,

1. After running "examples\custom_window_frame", 
when double-clicking on the title bar, the window does not maximize.
The dragging functionality works well when the title bar is clicked and held.

2. After running "examples\multiple_viewports",
selecting "Show immediate child viewport" and moving the generated child viewport to another screen
causes all text in the main window to change to like Arabic characters ( broken characters ). 
"Deferred child viewport" does not exhibit any issues.

Thanks, Emilk.

Library: egui v0.24.0
OS: Windows 10 (Korean version)
Monitors: 2 in use, extended screen mode, left monitor scaled at 1.5x, right monitor scaled at 1.25x

**Comment by emilk** [comment]
Thanks for the report, but please create one report per issue!

**Comment by emilk** [comment]
On Mac when I double-click on the title-bar of `custom_window_frame`, it maximizes just fine, so I suspect this is a Windows-only problem.

**Comment by emilk** [comment]
Is the first problem solved by https://github.com/emilk/egui/pull/3643 ?

**Comment by rustbasic** [comment]
> 1. "examples\custom_window_frame"
It is unrelated to that issue. I will explain in the comment below.

**Comment by rustbasic** [comment]
1.
In "examples\custom_window_frame," checking only for double_clicked() as follows is fine:

```
    if title_bar_response.double_clicked() {
        let is_maximized = ui.input(|i| i.viewport().maximized.unwrap_or(false));
        ui.ctx()
            .send_viewport_cmd(ViewportCommand::Maximized(!is_maximized));
    }
/*
    else if title_bar_response.is_pointer_button_down_on() {
        ui.ctx().send_viewport_cmd(ViewportCommand::StartDrag);
    }
*/
```

Note that even when checking both clicked() and double_clicked(), both will be executed. (Common to all versions of egui)

**Comment by rustbasic** [comment]
2. "examples\multiple_viewports"
When two monitors have different scaling factors, text is distorted.
However, when both monitors have the same scaling factor, there is no issue.

have a good day.
thanks emilk.

**Comment by emilk** [comment]
Closed in favor of https://github.com/emilk/egui/issues/3664
