### ISSUE TITLE
egui_demo_app color test lines

### ISSUE THREAD

**Issue by Letronix624** [emilk/egui#3667]
The color test in the `egui_demo_app` crate got weird lines between the gradients since version 0.23.

Here in this screenshot you can see them clearly.
![image](https://github.com/emilk/egui/assets/94926994/1834fe5c-879e-4f98-ae1e-ac81259c6e09)

they are also seen in the official [demo app color test web page](https://www.egui.rs/#Colors) when you start scrolling.
I don't think that started happening intentionally.

**Comment by alufers** [comment]
Is  maybe your browser zoomed in? I observed similar behavior when being 125% zoomed in. For me it happens for every non-integer zoom amount (e. g. not 100%, 200% etc.).

**Comment by Letronix624** [comment]
This screenshot is not from the browser version. The browser version also contains those lines and it is not zoomed in.

**Comment by emilk** [comment]
I wonder if this can be solved by:
* https://github.com/emilk/egui/issues/5164
