### ISSUE TITLE
Problems interacting with `examples\custom_window_frame`

### ISSUE THREAD

**Issue by rustbasic** [emilk/egui#3669]
Subject: "examples\custom_window_frame" issue

Dear emilk,

I'm re-raising the issue regarding the "examples\custom_window_frame" that I posted earlier,
as it has not been addressed in v0.24.1.
Even if double_clicked() is not working, clicked() should still function.

After running "examples\custom_window_frame",
when double-clicking on the title bar, the window does not maximize.
The dragging functionality works well when the title bar is clicked and held.

```
    if title_bar_response.double_clicked() {
        let is_maximized = ui.input(|i| i.viewport().maximized.unwrap_or(false));
        ui.ctx()
            .send_viewport_cmd(ViewportCommand::Maximized(!is_maximized));
    }
    else if title_bar_response.is_pointer_button_down_on() {
        ui.ctx().send_viewport_cmd(ViewportCommand::StartDrag);
    }
```

In "examples\custom_window_frame," checking only for double_clicked() as follows is fine (no problem) :

```
    if title_bar_response.double_clicked() {
        let is_maximized = ui.input(|i| i.viewport().maximized.unwrap_or(false));
        ui.ctx()
            .send_viewport_cmd(ViewportCommand::Maximized(!is_maximized));
    }
/*
    else if title_bar_response.is_pointer_button_down_on() {
        ui.ctx().send_viewport_cmd(ViewportCommand::StartDrag);
    }
*/
```

In "examples\custom_window_frame," even when double_clicked() is changed to clicked(),
if there is `else if title_bar_response.is_pointer_button_down_on()`, clicked() does not work.

```
    if title_bar_response.clicked() {
        let is_maximized = ui.input(|i| i.viewport().maximized.unwrap_or(false));
        ui.ctx()
            .send_viewport_cmd(ViewportCommand::Maximized(!is_maximized));
    }
    else if title_bar_response.is_pointer_button_down_on() {
        ui.ctx().send_viewport_cmd(ViewportCommand::StartDrag);
    }
```

Thanks, emilk.

Library: egui v0.24.0, egui v0.24.1
OS: Windows 10

**Comment by dbuch** [comment]
I tested abit here. StartDrag takes precedence for sure. The caveat is that I'm able to get a `is_double_clicked() = true` with touch event. I'm digging deeper.
