### ISSUE TITLE
Running the example doesn't work

### ISSUE THREAD

**Issue by hello350** [emilk/egui#367]
# Bug
When I paste the code at https://github.com/emilk/egui#example it does not work, but rather comes with these error

error: expected one of `!` or `::`, found `.`
 --> src\main.rs:1:3
  |
1 | ui.heading("My egui Application");
  |   ^ expected one of `!` or `::`

error: aborting due to previous error

error: could not compile `my_gui`

To learn more, run the command again with --verbose.

This should be fixed as I wish to run this

**Comment by follower** [comment]
It would be helpful if you could show the entire contents of the file `src\main.rs`...

Ah, after looking at https://github.com/emilk/egui#example I see it's possibly not clear that the example isn't complete as is--it needs other code around it to work.

For a more complete example (using `eframe`) see: https://github.com/emilk/egui/blob/0.11.0/eframe/examples/hello_world.rs

**Comment by hello350** [comment]
Yep, that seems to work!
