### ISSUE TITLE
WebGPU build broken

### ISSUE THREAD

**Issue by emilk** [emilk/egui#3675]
`./scripts/build_demo_web.sh --webgpu --release`
`./scripts/start_server.sh`

> panicked at 'canvas context is not a GPUCanvasContext: Object { obj: JsValue(GPUCanvasContext) }', /Users/emilk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.18.0/src/backend/web.rs:975:14

**Comment by Wumpf** [comment]
struggling with this one. It seems to fail a cast that should just work. Suspected some kind of web_sys/wasm-bindgen version issue but updating those didn't help so far. Hoping for responses on wgpu matrix chat right now

**Comment by emilk** [comment]
According to @Wumpf the wgpu web build works again with [this wgpu pr](https://github.com/gfx-rs/wgpu/pull/5044)), so this will likely solve itself when we update wgpu

**Comment by rakurtz** [comment]
Hey emilk, i am not sure if the error message i get when i try to compile the eframe template with wgpu instead of glow is related to the above described issue:

```
error: failed to select a version for `web-sys`.
    ... required by package `wgpu v0.18.0`
    ... which satisfies dependency `wgpu = "^0.18.0"` of package `eframe v0.25.0`
    ... which satisfies dependency `eframe = "^0.25.0"` (locked to 0.25.0) of package `msg-extractor v0.1.0 (/Users/xxxxxx/VisualStudioCodeProjects/Rust/HELPER/msg-extractor)`
versions that meet the requirements `^0.3.64` (locked to 0.3.67) are: 0.3.67

the package `wgpu` depends on `web-sys`, with features: `GpuComputePassTimestampWrite` but `web-sys` does not have these features.
```

Maybe that helps ?

**Comment by emilk** [comment]
no, that's a compilation issue. Looks like you're using an old web-sys

**Comment by emilk** [comment]
A fix is coming in https://github.com/emilk/egui/pull/3824

**Comment by rakurtz** [comment]
> no, that's a compilation issue. Looks like you're using an old web-sys

mmh, i am using the current version of web-sys 0.3.67. I just took the `eframe-template` and switched to `wgpu` in `Cargo.toml` though. Shall i file another issue dedicated to the above error messages?
