### ISSUE TITLE
Cannot run program with wgpu backend on Windows 10 22H2 "STATUS_ACCESS_VIOLATION", exit code: 0xc0000005

### ISSUE THREAD

**Issue by sakura6264** [emilk/egui#3686]
Cannot run program with wgpu backend on Windows 10 22H2 due to "STATUS_ACCESS_VIOLATION", exit code: 0xc0000005.

**To Reproduce**
1. Run the program use 'cargo run'.
2. The program cannot run because of "STATUS_ACCESS_VIOLATION".

**Screenshots**
![Snipaste_2023-12-06_09-18-20](https://github.com/emilk/egui/assets/65833536/9b003a08-7e78-43ee-8ad2-273c37aaaf0e)
0x00007FFAA4BCABB1 Instruction reference to memory 0xFFFFFFFFF...F, this memory cannot be read.

**Desktop**
 - OS: Windows 10
 - Version 22H2

**Additional context**
I've tried both version 0.24.1, version 0.24.0, and master branch, all of them could not work.

**Comment by valaphee** [comment]
Can you run your program with a debugger and send the stack trace? Or if possible send a minidump, as this would help identifing the cause for the access violation.

This error also looks untypical to me, as most Rust applications don't use message boxes to report errors.

**Comment by sakura6264** [comment]
I tried again this morning and found it worked...
Maybe something happened to my computer three weeks ago.
Anyway, thank you very much.
