### ISSUE TITLE
Other DragValue widgets are responding at the same time

### ISSUE THREAD

**Issue by 1danielcoelho** [emilk/egui#37]
Hello,

I'm trying to display a sort of table/spreadsheet with a label and a dragvalue next to it per row, by doing this:
``` Rust
ui.columns(2, |cols| {
    cols[0].label("var_a: ");
    cols[1].add(egui::DragValue::f32(&mut var_a));
});

ui.columns(2, |cols| {
    cols[0].label("var_b: ");
    cols[1].add(egui::DragValue::f32(&mut var_b));
});
```
The problem is that when I drag the `var_a` DragValue, the `var_b` DragValue also simultaneously responds, and both change at the same time. Am I doing something wrong?

Thanks!

**Comment by emilk** [comment]
You are not doing something wrong!

Egui generates `Id`s for each widget, and these are used to figure out "what is being dragged?".

There seems to be a bug here where the columns `Ui`s (and, by extension, their `DragValue`:s) don't get unique `Id`s generated. I'll take a look at it as soon as a I can (the `Id` generator system needs a refactor anyway).
