### ISSUE TITLE
strange buttom panel design

### ISSUE THREAD

**Issue by zhouhang95** [emilk/egui#3701]
bottom panel should be more width than center panel.
Almost software need bottom panel as status bar.

![Snipaste_2023-12-13_13-31-07](https://github.com/emilk/egui/assets/15245678/554edcfe-76db-4df4-bcfa-35414ce9f2f1)

![Snipaste_2023-12-13_13-27-52](https://github.com/emilk/egui/assets/15245678/23adbd2c-4a29-44e9-99fe-09989445f93b)
![Snipaste_2023-12-13_13-26-28](https://github.com/emilk/egui/assets/15245678/a71d2fd9-3f24-449f-917f-fd3723e95c92)
![Snipaste_2023-12-13_13-25-46](https://github.com/emilk/egui/assets/15245678/1e623330-0595-4f0e-93db-da60aea9c28d)

**Comment by YgorSouza** [comment]
That's just the example. You can arrange the panels in any way you like in your application.

Here is the source for this demo: 

https://github.com/emilk/egui/blob/c8dd3dd01a7ea40b95925b8de11ecfa981eaa738/crates/egui_demo_lib/src/demo/window_with_panels.rs#L22-L81

If you rearrange it so the bottom panel comes before the side panels, it will fill the whole space horizontally.

```diff
@@ -34,6 +34,15 @@ impl super::View for WindowWithPanels {
                 });
             });
 
+        egui::TopBottomPanel::bottom("bottom_panel")
+            .resizable(false)
+            .min_height(0.0)
+            .show_inside(ui, |ui| {
+                ui.vertical_centered(|ui| {
+                    ui.heading("Bottom Panel");
+                });
+            });
+
         egui::SidePanel::left("left_panel")
             .resizable(true)
             .default_width(150.0)
@@ -60,15 +69,6 @@ impl super::View for WindowWithPanels {
                 });
             });
 
-        egui::TopBottomPanel::bottom("bottom_panel")
-            .resizable(false)
-            .min_height(0.0)
-            .show_inside(ui, |ui| {
-                ui.vertical_centered(|ui| {
-                    ui.heading("Bottom Panel");
-                });
-            });
-
         egui::CentralPanel::default().show_inside(ui, |ui| {
             ui.vertical_centered(|ui| {
                 ui.heading("Central Panel");
```

![image](https://github.com/emilk/egui/assets/43298013/f4fd7fcb-8a2b-46b1-aa0e-24bca94080f0)

**Comment by zhouhang95** [comment]
Amazing, it depends function call order.
