### ISSUE TITLE
Can't compile standart template project (https://github.com/benwis/eframe_template) to WASM using trunk

### ISSUE THREAD

**Issue by GulGanis** [emilk/egui#3703]
The project's contents are 1:1. I didn't make any changes.

> error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
>    --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:126:27
>     |
> 126 |             0x4F54544F => Some(Magic::OpenType),
>     |                           ^^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
>    --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:127:27
>     |
> 127 |             0x74746366 => Some(Magic::FontCollection),
>     |                           ^^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
>    --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:378:9
>     |
> 378 |         Some(Rect {
>     |         ^^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
>    --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:476:9
>     |
> 476 |         Some(TableRecord {
>     |         ^^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Err` in this scope
>    --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:599:24
>     |
> 599 |                 return Err(FaceParsingError::UnknownMagic);
>     |                        ^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Ok` in this scope
>    --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:608:9
>     |
> 608 |         Ok(RawFace {
>     |         ^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Ok` in this scope
>    --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:785:9
>     |
> 785 |         Ok(face)
>     |         ^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Ok` in this scope
>    --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:874:9
>     |
> 874 |         Ok(face)
>     |         ^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Ok` in this scope
>    --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:910:9
>     |
> 910 |         Ok(FaceTables {
>     |         ^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
>     --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:1228:9
>      |
> 1228 |         Some(self.vertical_ascender()? - self.vertical_descender()?)
>      |         ^^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
>     --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:1284:9
>      |
> 1284 |         Some(metrics)
>      |         ^^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
>     --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:1301:9
>      |
> 1301 |         Some(metrics)
>      |         ^^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
>     --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:1320:9
>      |
> 1320 |         Some(metrics)
>      |         ^^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
>     --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:1339:9
>      |
> 1339 |         Some(metrics)
>      |         ^^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
>     --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:1367:24
>      |
> 1367 |                 return Some(id);
>      |                        ^^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
>     --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:1386:61
>      |
> 1386 |                     cmap::GlyphVariationResult::Found(v) => Some(v),
>      |                                                             ^^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
>     --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:1514:20
>      |
> 1514 |             return Some(name);
>      |                    ^^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
>     --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:1518:20
>      |
> 1518 |             return Some(name);
>      |                    ^^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
>     --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:1723:9
>      |
> 1723 |         Some(())
>      |         ^^^^ not found in this scope
> 
> error[E0425]: cannot find function, tuple struct or tuple variant `Ok` in this scope
>     --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ttf-parser-0.15.2\src\lib.rs:1788:13
>      |
> 1788 |             Ok((table.table_tag, {
>      |             ^^ not found in this scope
> 
> error: could not compile `ttf-parser` (lib) due to 1985 previous errors
> 2023-12-13T13:18:45.522125Z ERROR error
> error from build pipeline
> 
> Caused by:
>     0: error from asset pipeline
>     1: error during cargo build execution
>     2: cargo call to executable 'cargo' with args: '["build", "--target=wasm32-unknown-unknown", "--manifest-path", "C:\\Users\\User\\RustroverProjects\\eframe_template-master\\Cargo.toml"]' returned a bad status: exit code: 101

I tried to compile another project some time before and faced the same situation. I didn't payed much attention to it because I wasn't sure that I did everything correct. But It starts worrying me because today and right now I've just cloned a repo with a template and didn't make any changes to it. It's very strange and I tried to google but didn't find any fixes.

How can I solve this situation?

**Comment by stonerfish** [comment]
The benwis fork you link, compiles for me.  Maybe try cargo update?
Or better yet, use the "official" template at  http://github.com/emilk/eframe_template

**Comment by GulGanis** [comment]
> The benwis fork you link, compiles for me. Maybe try cargo update? Or better yet, use the "official" template at [http://github.com/emilk/eframe_template](https://github.com/emilk/eframe_template)

What OS do you use? I'm on Windows 11, maybe should check it on Mac.

**Comment by emilk** [comment]
This is not the right place to discuss problems compiling `ttf-parser`
