### ISSUE TITLE
Paste in textbox on web demo duplicates text

### ISSUE THREAD

**Issue by zacps** [emilk/egui#371]
**Describe the bug**
Pasting text into a textbox duplicates the text.

**To Reproduce**
1. Copy 'abc' to the clipboard
1. Go to https://emilk.github.io/egui/
3. Paste into the textbox
4. The textbox contains 'abcabc'

**Expected behavior**
The textbox contains 'abc'

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser Chrome
 - Version 90.0.4430.93

**Comment by follower** [comment]
Thanks for your report. :)

Looks like this got fixed yesterday: https://github.com/emilk/egui/commit/934bb7f5e988ae3b1cac4162f33dc3318bd4fd58

**Comment by emilk** [comment]
yup, already fixed! (new web demo will be published on next release)
