### ISSUE TITLE
Unrenderable Characters in Specific Code Range

### ISSUE THREAD

**Issue by rustbasic** [emilk/egui#3729]
Title: Unrenderable Characters in Specific Code Range

Dear emilk,

Several characters within the ranges 0x2100 to 0x21FF, 0x2504 to 0x250B, and 0xE0A0 to 0xE0B3 are displayed as a square box when the characters cannot be rendered.

To verify this issue, navigate to FontBook in the egui_demo_app, locate the character with the problematic code, copy it, and paste it into the single-line search in FontBook. If the character appears as a square box, the issue is confirmed.

These characters seem to exhibit inconsistent behavior, appearing as squares in some ui.button() or ui.label() instances while displaying correctly in others.

Thanks,
emilk.

egui Version: v0.24.1
OS : Windows 10

**Comment by emilk** [comment]
Only the characters in the font book are supported in egui.rs

If you want to support more characters, you need to tell egui to use a fonts that support them.

See https://docs.rs/egui/latest/egui/struct.Context.html#method.set_fonts
