### ISSUE TITLE
IME: Currently typed characters get copied when switching TextEdit fields

### ISSUE THREAD

**Issue by rustbasic** [emilk/egui#3730]
Title: Copying Characters While Typing UTF-8 (Non-English) Characters

Dear emilk,

In multiline() or singleline():

When typing UTF-8 characters (non-English characters), during the typing process, the character is treated as selected in a block, which is normal behavior.

However, if you click elsewhere while the character is still selected in a block, there is a bug where the currently typed character remains in the input, and the clicked location also receives a copy of the character. The expected behavior is that the character should not be copied to the clicked location.

Thanks,
emilk.

egui Version: v0.24.1 & All version
OS : `Windows 10`

**Comment by emilk** [comment]
I assume you are talking about IME input of e.g. asian characters (as opposed to e.g. typing a `Å` on a Swedish keyboard)?

**Comment by rustbasic** [comment]
I am currently using the Korean keyboard.
I expect that the characters that are selected in blocks when entering characters will have the same symptoms.

**Comment by rustbasic** [comment]
@varphone

Dear varphone

I recently planned to find a solution to symptom #3730.

#3730 Do you have any symptoms?
