### ISSUE TITLE
Disabled button text color appears green by default

### ISSUE THREAD

**Issue by CerulanLumina** [emilk/egui#3732]
**Describe the bug**
The text color of disabled widgets is green when the regular color is not.

**To Reproduce**
The issue can be seen in the demo at https://www.egui.rs/#demo. Just uncheck "Interactive" in the widget gallery.

Alternatively,

1. Create a disabled button with text supplied as `&str` (or `RichText` with no color supplied)
2. It is green.

**Expected behavior**
The text is a faded out color of the normal text color.

**Screenshots**
*Enabled*
![image](https://github.com/emilk/egui/assets/1103450/eb713bdd-414a-4964-bc5e-ff85181dda9f)

*Disabled*
![image](https://github.com/emilk/egui/assets/1103450/623d193c-ee00-466f-b008-ebd8198a2c21)

**Additional context**
As of #3727 (tested by rolling back to git rev e36b9811180476fadd5b67c3e311ac9ce5a82302), the button text appears green. It seems like it is not replacing the new `PLACEHOLDER` color with the appropriate color when disabled (it is graying out the PLACEHOLDER rather than the intended default color). Using `RichText` with a color does not display this issue.

**Comment by YgorSouza** [comment]
The text also turns white in the light theme

![image](https://github.com/emilk/egui/assets/43298013/ca71b67b-5421-4e1f-a2e4-0f4a54de54ba)

**Comment by emilk** [comment]
Thanks for the report!
