### ISSUE TITLE
Assertion Failure in egui_extras

### ISSUE THREAD

**Issue by rustbasic** [emilk/egui#3747]
Subject: Assertion Failure in egui_extras

Dear Emilk,

I've been experiencing occasional assertion failures, approximately every few hours,
when using egui_extras. The error message displayed is as follows:

```
thread 'ehttp' panicked at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui_extras
-0.24.2\src\loaders\ehttp_loader.rs:99:21:
assertion failed: matches!(prev, Some(Poll :: Pending))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I haven't noticed any specific issues with the program's functionality,
and it seems to be operating normally.

Thanks,
Emilk.

egui version : v0.24.1, v0.24.0, v0.23.0
OS : windows10

**Comment by emilk** [comment]
Sounds like a bug in `EhttpLoader`!

I think that `assert` may be wrong. In any case, it should have been a `debug_assert`
