### ISSUE TITLE
Add a resizeable SplitView panel

### ISSUE THREAD

**Issue by edko99** [emilk/egui#375]
Would it please be possible to add a resizeable split-view container, that allows either a vertical or horizontal split, to the standard set of widgets?

**Comment by OfficialURL** [comment]
I'm not sure if this falls within the scope of this issue, but a resizable `SidePanel` would be nice too. The only way to achieve this currently is by embedding a `Resize` within the `SidePanel`, but this can only be resized from the bottom corner, which is quite inconvenient.

**Comment by emilk** [comment]
@OfficialURL no, but that happens to be something I'm working on: https://github.com/emilk/egui/issues/425
