### ISSUE TITLE
custom_font example not support chinese

### ISSUE THREAD

**Issue by dtdyq** [emilk/egui#3765]
**Describe the bug**
custom_font example can not support chinese input

**To Reproduce**
just use example code of custom_font

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser use eframe native
 - Version 0.24.2

**Comment by emilk** [comment]
The font installed by `examples/custom_font/src/main.rs` has no Chinese characters in it. If you replace the `.ttf` file it includes with a font that supports Chinese characters, it should work.

Try e.g. Noto: https://github.com/notofonts/noto-cjk/tree/main/Sans#downloading-noto-sans-cjk
