### ISSUE TITLE
Custom widget runs 10x slower on Windows machines

### ISSUE THREAD

**Issue by rafaga** [emilk/egui#3782]
**Describe the bug**
Running a simple application with the same code results in 10x slower performance on windows environment I append puffin profiles and repository with the testing code. 

I wasn't aware of this difference on performance because I was developing on MacBook Air 2019 13" Retina. I percieved this difference when such machine died and run the appliction on Windows 11 Enterprise with MS VC '22 compiler. both machine has similar specs and I would say that windows machine has better specs than the intel mac but the difference on performance was huge

just clone the repository https://github.com/rafaga/bugtest/ 
compile with `cargo build` and run with `cargo run`

if want to use puffin to check execution times use `--features=puffin` on run

**Expected behavior**
I wait that the same code executes on different platforms with similar performance

**Profiling**
[macos.profile.puffin.zip](https://github.com/emilk/egui/files/13855136/macos.profile.puffin.zip) run o a mac studio 
[profile.windows.zip](https://github.com/emilk/egui/files/13855151/profile.windows.zip) run o intel core i5 10th gen

**Desktop (please complete the following information):**
 Computer 1
 - OS: Sonoma 14.2.1
 - Browser Not Appplicable
 - Version Not available

Computer 2
 - OS: Windows 11 22H2
 - Browser Not Appplicable
 - Version Not available

**Additional context**
I'm not 100% sure that it is a bug from egui or not but reporting here because apparently it has somewhat relation with graphical functions

**Comment by emilk** [comment]
I don't think this is related to `egui`. The puffin profiles shows that _everything_ is pretty uniformly slower:

![image](https://github.com/emilk/egui/assets/1148717/5b86e015-2b5d-46d0-98f6-69e2c8da202c)

![image](https://github.com/emilk/egui/assets/1148717/e2cfc131-16cf-47cf-b535-7d66302753f0)

It looks like your compiling the windows code without `--release`, or running it in an emulator or something

**Comment by rafaga** [comment]
the slowdown it is present with or without --release flag, use it just make it marginally faster.

**Comment by RossSmyth** [comment]
@emilk This is not an issue where the application was not run in release mode. There is something strange going on with optimization or cfg or something. The process that I followed was the following:

Single CGU application:

1. `git clone git@github.com:rafaga/bugtest.git`
2. `cd bugtest`
1. Run `puffin_viewer --url 127.0.0.1:8585`
3. Run `cargo run --release --features=as_file,puffin`
4. See the the "as_file" version runs mostly fine. The puffin profile looks fine.


![image](https://github.com/rust-lang/rust/assets/18294397/0b76e322-1560-4a5f-99c9-caeac971923d)

This is using Rust 1.75.0 on Windows 10 Version 10.0.19045 Build 19045 with an AMD 1700X & Nvidia 2060 Super.
[profile.zip](https://github.com/rust-lang/rust/files/13944241/profile.zip)

Library application:

1. Run `puffin_viewer --url 127.0.0.1:8585`
1. `cargo run --release --features=as_lib,puffin`

Definitely a regression. I have different hardware so the result are not quite the same, but still a significant regression.

![image](https://github.com/rust-lang/rust/assets/18294397/7b6ccfa4-5a18-4955-8af5-fd96d1a38120)
[lib_profile.zip](https://github.com/rust-lang/rust/files/13944342/lib_profile.zip)

One thing that I notice is that there are many [WindowEvent::CursorMoved](https://docs.rs/winit/latest/winit/event/enum.WindowEvent.html#variant.CursorMoved) winit events. While in the local version there are not. The local version uses [DeviceEvent::Motion](https://docs.rs/winit/latest/winit/event/enum.DeviceEvent.html#variant.MouseMotion)

Local:
![image](https://github.com/rust-lang/rust/assets/18294397/d0f2136a-ce7e-429f-9a77-d29ed7f27137)

lib:
![image](https://github.com/rust-lang/rust/assets/18294397/03085a8d-fd11-41ad-998b-e1e54c141319)

I don't know enough about winit & the rest of the egui stack to say what this is or what it means.

**Comment by RossSmyth** [comment]
Just for kicks tried running with a profile

```toml
[profile.rel-lto]
inherits = "release"
lto = true
```
And no difference. Same thing with adding `codegen-units = 1` and because I just love watching rustc compile forever I also tried LTO-at-home (`-Zcross-crate-inline-threshold=yes`) just for fun and it made it much worse. But you can ignore the latter profile as it was just something I was curious about

**Comment by RossSmyth** [comment]
@workingjubilee

**Comment by workingjubilee** [comment]
I dunno then!
