### ISSUE TITLE
Error: lacking either libGL or libEGL so could not fallback to other

### ISSUE THREAD

**Issue by ClementNerma** [emilk/egui#380]
**Describe the bug**
Getting the following error message when cloning the starter template (https://github.com/emilk/egui_template/) and compiling it with `cargo run`:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/egui_template`
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(CreationErrors([NotSupported("lacking either libGL or libEGL so could not fallback to other"), NoAvailablePixelFormat]))', /home/XXXXXX/.cargo/registry/src/github.com-1ecc6299db9ec823/egui_glium-0.11.0/src/backend.rs:88:85
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm running it on WSL 2 on Windows 10.

I followed the installation instructions and run `apt install` for all the required packages.

**To Reproduce**
1. Clone the `https://github.com/emilk/egui_template/` repository
2. Run `cargo run` (same result with `cargo run --release`)

**Expected behavior**
The example should work fine.

**Desktop (please complete the following information):**
 - OS: Debian 10 on WSL 2 on Windows 10 20H2

**Comment by emilk** [comment]
Does the examples at https://github.com/rust-windowing/glutin run?

**Comment by ClementNerma** [comment]
> Does the examples at https://github.com/rust-windowing/glutin run?

No, I get the exact same error message.

**Comment by parasyte** [comment]
I haven't tried this myself, but it seems you will need to install a WSLg driver for your GPU: https://devblogs.microsoft.com/commandline/wslg-architecture/#hardware-accelerated-opengl

**Comment by ClementNerma** [comment]
> I haven't tried this myself, but it seems you will need to install a WSLg driver for your GPU: https://devblogs.microsoft.com/commandline/wslg-architecture/#hardware-accelerated-opengl

Unfortunately WSLg isn't available in the stable channel for now. Besides, I think this should work correctly without it as many heavy GUI-based applications work fine with as long as there is an X server running.

**Comment by parasyte** [comment]
Are you sure it's supposed to work on WSL2 stable? The [GUI tutorial](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps) says this can _only_ work on Windows 10 Insider Preview build 21362+ as of 2021-04-27.

**Comment by ClementNerma** [comment]
> Are you sure it's supposed to work on WSL2 stable? The [GUI tutorial](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps) says this can _only_ work on Windows 10 Insider Preview build 21362+ as of 2021-04-27.

As I said, it isn't available as stable for now.

But it's been possible to run GUI applications for a very long time already, by using a third-party X server like Xming.

WSLg is the next step in that direction, allowing to run applications natively on WSL with first-class support without using a third-party server, but it's not available in stable yet.

**Comment by parasyte** [comment]
There might be some confusion.

An X server on Windows (like Xming or VcXsrv) is a remote X server. This works for the X11 protocol, but not for OpenGL. You will need either a hardware or software rasterizer for OpenGL support in WSL. If you cannot use WSLg (especially its hardware rasterizer), then you might be able to use a software rasterizer like `libgl1-mesa-swx11`.

**Comment by ClementNerma** [comment]
I see, so in that case it will probably require to wait for WSLg in order for `egui` to be compatible with WSL at all.

**Comment by parasyte** [comment]
It depends on the backend you want to use. If you are required to use the `egui-glium` backend, then yes, you will need OpenGL support. But hypothetically even a TUI backend could be written that will render `egui` into the terminal. 😉 Or a backend that uses X11; your remote X11 server should work with that.

The trouble is, to my knowledge, none of these backends currently exist.

**Comment by ClementNerma** [comment]
> It depends on the backend you want to use. If you are required to use the `egui-glium` backend, then yes, you will need OpenGL support. But hypothetically even a TUI backend could be written that will render `egui` into the terminal. 😉 Or a backend that uses X11; your remote X11 server should work with that.
> 
> The trouble is, to my knowledge, none of these backends currently exist.

Ok I understand, so it's more like we'll need WSLg to use the OpenGL backend provided in the examples.

**Comment by emilk** [comment]
The `egui_glium` backend has been moved out to a separate repo (https://github.com/fayalalebrun/egui_glium), so I'm gonna close this issue
