### ISSUE TITLE
Window title bar border disappears                                           

### ISSUE THREAD

**Issue by rustbasic** [emilk/egui#3806]
Subject: Window title bar border disappears                                           
                                                                                      
Dear emilk,                                                                           
                                                                                      
When I select a window in my program,                                                 
the color of the selected window's title bar changes,                                 
but the border of the title bar disappears.                                           
                                                                                      
Thank you, emilk.                                                                                
                                                                                      
egui version: egui v0.25.0

**Comment by emilk** [comment]
The native os window, or `egui::Window`?

Do you have a screenshot?

**Comment by rustbasic** [comment]
It mean egui::window

![winchoice1](https://github.com/emilk/egui/assets/127506429/bd33a8c5-0c5c-4951-bdf0-2697c9225b7b)
![winchoice2](https://github.com/emilk/egui/assets/127506429/3f448106-fa02-4203-ad36-a32eebc9afc3)
