### ISSUE TITLE
epi::http not showing up in the docs

### ISSUE THREAD

**Issue by emilk** [emilk/egui#381]
I just noticed that `epi::http` is not showing up in the docs at <https://docs.rs/epi/0.12.0/epi/>.

How do we configure cargo doc to generate docs with all feature enabled?

**Comment by memoryruins** [comment]
docs.rs will read `[package.metadata.docs.rs]` metadata in `Cargo.toml` https://docs.rs/about/metadata

**Comment by emilk** [comment]
Thanks, I didn't know about that!
