### ISSUE TITLE
Master branch currently does not build on Windows

### ISSUE THREAD

**Issue by mcclure** [emilk/egui#3813]
I check out this git repo. I run `cargo.exe run --example hello_world`. It chugs for a bit then prints

```
    Updating crates.io index
error: failed to select a version for `wgpu`.
    ... required by package `eframe v0.25.0 (C:\Users\Andi\work\r\other\egui\crates\eframe)`
    ... which satisfies path dependency `eframe` (locked to 0.25.0) of package `egui_demo_app v0.25.0 (C:\Users\Andi\work\r\other\egui\crates\egui_demo_app)`
versions that meet the requirements `*` are: 0.16.2

the package `eframe` depends on `wgpu`, with features: `fragile-send-sync-non-atomic-wasm` but `wgpu` does not have these features.
```

I then check out tag 0.25.0. `cargo.exe run --example hello_world` says that example is not found, but if I `cd examples/hello_world && cargo.exe run`, it builds and runs successfully.

I am running Rust 1.72.0 for Windows, but I think you override my Rust version with Cargo settings. Complicating factors: I did not check out with git, I checked out with hg-git, but this should not matter. I am running the Windows version (Windows 10) but I am invoking the Windows exe from within WSL (WSL1). This also should not matter.

I have not yet tried building on other platforms and I since I have now switched to the 0.25.0 branch (IOW: I am not blocked) I have not yet tried a plain `cargo.exe build` on master.

**Comment by emilk** [comment]
You may need to do a cargo clean or something. `main` is currently on wgpu 0.18: https://github.com/emilk/egui/blob/301c72ba22da8f29596d65757cf3dacdf5309985/Cargo.toml#L58

**Comment by emilk** [comment]
Also, it is `cargo run -p hello_world`, not `--example`

**Comment by mcclure** [comment]
Thanks. I now believe this was a local tools issue.
