### ISSUE TITLE
Proposal: A "form" widget

### ISSUE THREAD

**Issue by juancampa** [emilk/egui#3829]
HTML has nice 

**Is your feature request related to a problem? Please describe.**

HTML has the concept of forms which group together fields. More importantly, when enter is pressed and any of those fields were focused, the form's "submit" action is executed. [Try it out here](https://brick-13-rock-152-matter-1013-pit.hook.membrane.io/).

It's not hard to implement this in egui by combining all `Response::has_focus` for the relevant widgets and then checking `consume_key` but as forms get more complex, it gets harder to ensure that you've covered all the fields.

For example, in this video, I show a rich "form" with multiple kinds of fields, each of which has multiple widgets in them (e.g. notice the `X` buttons on the right) and some widgets change depending if you're actively editing the value or not. Some fields have drag-and-drop wrappers so that you can drop values onto them and so on.

https://github.com/emilk/egui/assets/1410520/4648ab21-c9b8-4100-ae43-eac8fc9b407e

I would like to only trigger the submit logic if the "Invoke" button is pressed or if any widget in the form is focused, (as opposed to any of the popups that can appear on top) and enter or (cmd+enter) is pressed.

**Describe the solution you'd like**

Maybe something similar to `ui.menu` but for forms:

```rust
let on_submit = || {
  println!("Form was submitted");
}

// This handles the submission logic and calls `on_submit` as needed
ui.form(id_source, on_submit, |ui| {

  // Submit via enter key (not shown) or via button
  if ui.button("submit").clicked() {
    ui.submit_form();
  }
})
```
I believe some additional state would need to be tracked, perhaps the submission via `enter` or `cmd+enter` could be handled in `Focus::begin_frame`. 

**Describe alternatives you've considered**
Many `form_has_focus |= response.has_focus()` spread out everywhere.

**Additional context**

[Play with the HTML form behavior](https://brick-13-rock-152-matter-1013-pit.hook.membrane.io/).

**Comment by juancampa** [comment]
@emilk let me know what you think about this proposal. Happy to work on it.

**Comment by enomado** [comment]
I don't think this solution is generic enough. 

We should care about tons of stuff, like controlling next focus by pressing TAB, composition,  tabindex, event bubbling, meta-focus, nesting, stacking, etc, etc. how all this stuff compares with other elements like GAME itself(if egui is embed) ?

I think can simulate this stuff by accessing to memory/focused and remember all your text inputs ids, and traverse it in key-event handler.

Similar concept exists. egui-dock has "meta-focus". when you click on area - tab becomes active.

BTW, what technology on your video? dnd to the field is awesome.

**Comment by juancampa** [comment]
Good points, I thought about it a bit more and I think it's better to leave this to "userspace". I'll close this.


> BTW, what technology on your video? dnd to the field is awesome.

Thanks! It's the client of https://membrane.io which is all egui.
