### ISSUE TITLE
No item selection and proper keyboard navigation in the web demo

### ISSUE THREAD

**Issue by vi** [emilk/egui#383]
**Describe the bug**

List items should typically be selectable and keyboard actions should affect that selection.

**To Reproduce**

1. Open the web demo: https://emilk.github.io/egui/#demo
2. Activate "Drag and drop" and "Scrolling" windows
3. Click onto some list item in one of the visible lists
4. Press "down" keyboard button

**Expected behavior**

Selected item is highlighted somehow.
Pressing down key moves makes lower item highlighted instead. 

---

It is in general tricky to access all features of the web demo using keyboard only. A lot of Tab / Shift+Tab and other bugs (i.e. uncloseable combobox) gets encountered this way.

**Comment by emilk** [comment]
What is needed in order to accomplish keyboard navigation has been discussed in more detail in https://github.com/emilk/egui/issues/1250, so I'll close that in favor of https://github.com/emilk/egui/issues/1250
