### ISSUE TITLE
Some examples with native file dialogs will not build on cross-compile Linux -> x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by John-Nagle** [emilk/egui#3836]
**Describe the bug**

```
cargo build --target x86_64-pc-windows-gnu
   Compiling file_dialog v0.1.0 (/home/john/projects/egui/examples/file_dialog)
   Compiling save_plot v0.1.0 (/home/john/projects/egui/examples/save_plot)
error: linking with `x86_64-w64-mingw32-gcc` failed: exit status: 1
```
Full details: 
[egui_bad_linking.txt](https://github.com/emilk/egui/files/13971168/egui_bad_linking.txt)

This seems to be associated only with examples that use native file dialogs. The main egui library will work cross-compiled. This is just a problem with the build setup for some of the examples. So it's not critical once that's figured out.

**To Reproduce**
1. Run on Linux machine.
2. Set up Rust with target x86_64-pc-windows-gnu
3. Load egui crate from github
4. cargo build --target x86_64-pc-windows-gnu 

**Expected behavior**

Successful build and link.

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Smartphone (please complete the following information):**
 - Device: x86-64
 - OS: Linux 22.04 LTS  
 
**Additional context**

Discussion on Rust forums here: https://users.rust-lang.org/t/cross-compiling-crate-egui-linux-win-cant-find-core/105427/1

**Comment by emilk** [comment]
The native file dialogs is using [rfd](https://github.com/PolyMeilex/rfd) - have you tried cross-compiling the rfd examples? Perhaps the issue belongs in that repository?
