### ISSUE TITLE
Demo app crashes in webassembly

### ISSUE THREAD

**Issue by WojciechMula** [emilk/egui#3844]
Steps to reproduce:

- Open demo at https://www.egui.rs/
- Open widget "Window option"
- Click a few times somewhere on label "This windows is on"
- This triggers panic: `Parking not supported on this platform', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parking_lot_core-0.9.8/src/thread_parker/wasm.rs:26:9`

I tried also openning differernt demo windows and sometimes this panic is triggered on random clicks. But the steps above gives me 100% crash rate.

**Comment by rustbasic** [comment]
The `ui.label()` function has been updated now, so the bug doesn't seem to be occurring, but it would be good if you could check again and write the results.

**Comment by WojciechMula** [comment]
Thanks! It works correctly now.
