### ISSUE TITLE
About Widget's Memory Usage

### ISSUE THREAD

**Issue by Orchiliszt** [emilk/egui#3851]
I found a problem, when I use ui.label() or TextEdit, the same character content (about 300kib of text), multiple drawing is more memory intensive than one drawing. 
Is this normal?

**Comment by emilk** [comment]
It depends. If the label is on-screen and visible then yes, it will generate more triangles = more memory.

If the label is off-screen (e.g. deep down in a ScrollArea) it should not use up any extra memory

**Comment by Orchiliszt** [comment]
> It depends. If the label is on-screen and visible then yes, it will generate more triangles = more memory.
> 
> If the label is off-screen (e.g. deep down in a ScrollArea) it should not use up any extra memory

Thank you for your reply;

But what I encountered was the second situation. As the text changes, each drawing will become more sluggish.
Perhaps I shouldn't pass the entire String to it?
