### ISSUE TITLE
egui_plot: Images inside of plots are not clipped during folding animations

### ISSUE THREAD

**Issue by alufers** [emilk/egui#3865]
**Describe the bug**
When a Plot with an Image from `egui_plot` is put inside of a window, or collapsing header the image is not clipped during the folding or unfolding animations, even though the rest of the plot elements are properly clipped.

See the attached movie:

https://github.com/emilk/egui/assets/5400940/3d20ae8c-4d1c-4e66-809c-3bcace872e09

(I have set the animation duration to 3.0s to exaggerate the effect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the project from the reproducer repo: https://github.com/alufers/egui-plot-error-reproducer/blob/master/src/main.rs
2. Click the arrow near the window header to collapse it.
3. Observe the image in the plot

**Expected behavior**

The image is clipped along with the rest of the plot.

**Screenshots**

<img width="481" alt="image" src="https://github.com/emilk/egui/assets/5400940/e6b3e78a-02e7-4a88-850c-de2e44b664d4">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.1.2 (23B92), as well as Arch linux both on wayland and X11
 - Browser n/a
 - Version Both the `master` branch and the `0.25.0` release

**Smartphone (please complete the following information):**

Not tested, but probably appears too.

**Additional context**

This behaviour also occurs in my more complex app, where `egui_dock` is used, and the plot image somehow overdraws under another panel and ends up on the window margin. I believe this is caused by the same problem, but it is harder to create a minimal reproducer.

![image](https://github.com/emilk/egui/assets/5400940/9ddd86ab-d487-44ca-9772-c8a50f7b26cb)

**Comment by YgorSouza** [comment]
This is reproducible with the demo app as well, just to make it easier to test the eventual fix.

https://github.com/emilk/egui/assets/43298013/5859243f-09f0-40a4-8669-14965df5e09a
