### ISSUE TITLE
Improvements to make drag-and-drop easier

### ISSUE THREAD

**Issue by abey79** [emilk/egui#3882]
- #3876 added `men.dragged_id()`, but there is no way to get the value of to an `egui::Id` (which could then be converted to an internal Id).
- It would be nice to have `ctx().anything_being_decidedly_dragged()` (equivalent to ` ui.memory(|mem| mem.is_anything_being_dragged()) && ui.input(|i| i.pointer.is_decidedly_dragging())`
- It would be nice to have `ctx().drag_stopped()`

**Comment by emilk** [comment]
We should take a look at the ImGui API for drag-and-drop

**Comment by crumblingstatue** [comment]
I want to mention [egui_dnd](https://docs.rs/egui_dnd/latest/egui_dnd/) just as a baseline to compare an egui-builtin solution against.

It only seems to support fairly simple layouts.

I would like something that supports drag and drop between different uis for maximum flexibility.

An example use case of mine would be to drag tree nodes in a tree.

For example move `a-1` to `b` in this tree ui made out of `CollapsingHeader`s.
![image](https://github.com/emilk/egui/assets/1521976/bd5e3159-e4c3-424d-a14a-6e8749cde22b)

**Comment by abey79** [comment]
@crumblingstatue I think a proper high-level drag-and-drop API in egui is still a little far off due to the difficulty to properly address the general case(s). This issue is more about the little things that would make lower-level implementation easier.

As for the tree drag-and-drop, I just built a demo of that in the rerun repository: https://github.com/rerun-io/rerun/pull/4879. I plan on making a proper egui example out of it.

**Comment by abey79** [comment]
@crumblingstatue https://github.com/emilk/egui/pull/3903
