### ISSUE TITLE
WASM multithreading?

### ISSUE THREAD

**Issue by serzhiio** [emilk/egui#39]
Is it possible to run webworkers in egui?

**Comment by emilk** [comment]
Hi!

 You don't really run anything "in egui" - Egui is a library you call into. The online Egui demo is done with [`egui_web`](https://github.com/emilk/egui/tree/master/egui_web), which is a pretty simple library that just hooks up to some callbacks for input and paint events using [`js-sys`](https://crates.io/crates/js-sys) and [`wasm-bindgen`](https://github.com/rustwasm/wasm-bindgen).

If you want to spawn a web worker I think you can do so from either JS or in Rust with `js-sys / wasm-bindgen`. If you want to call Egui code from that worker, that should be no problem.

I hope that helps!

**Comment by serzhiio** [comment]
... but if i want webworker to render some parts on canvas? ideally i should transfer that canvas to worker.

**Comment by emilk** [comment]
`egui_web` paints to a canvas using WebGL. So are you asking if you can call WebGL functions from a web worker? I don't know the answer to that, but a quick googling seems to suggest that it should be no problem. Try it 🤷 :)

I don't know much web stuff, so I don't think I can be of much more help here (except maybe to guide you are in the `egui_web` code base). My guess is that you know much more than me :) `egui_web` would maybe need some refactoring or cleanup to make it easier to run in a web worker, but I have no idea.

**Comment by serzhiio** [comment]
my idea is to delegate part of canvas to dedicated webworkers with specific work, but i dont know is it possible or not so far

**Comment by emilk** [comment]
I'm gonna close this because it is more related to `wasm-bindgen`/`js-sys` than to Egui.
