### ISSUE TITLE
Support horizontal scrolling in ScrollArea

### ISSUE THREAD

**Issue by parasyte** [emilk/egui#391]
`ScrollArea` currently only supports scrolling vertically. We need a way to allow scrolling horizontally for wide content.

**Describe the solution you'd like**

"Wide content" is a broad definition, so I'll propose that we define the term to mean, roughly, that the content width _needs_ to be wider than the `ScrollArea` width. This is usually because the content area contains UI elements that cannot be made thinner. A very obvious example is an `Image` which has a static width and height.

Draw a horizontal scroll bar at the bottom of the `ScrollArea`, and allow it to be scrolled with <kbd>Shift + Scroll Wheel</kbd>. Otherwise it should support the same interactions as the existing vertical scroll bar, including touch inputs.

**Comment by emilk** [comment]
Having horizontal scrolling as an opt-in part of `ScrollArea` is the right approach. Users should have the choice between vertical, horizontal or both.
