### ISSUE TITLE
Labels are focusable when they shouldn't be

### ISSUE THREAD

**Issue by mwcampbell** [emilk/egui#3910]
As of the current revision in egui master, labels are focusable when they shouldn't be. I'm seeing this in the hello_world example app. Labels should only be focusable if the old primitive screen reader is enabled. Notably, merely enabling AccessKit shouldn't trigger this, because users of real screen readers have other ways of reading labels.

**Comment by mwcampbell** [comment]
It appears that #3814 had the side effect of adding labels to the tab order. This might make sense for specific labels if the implementation of text selection in labels supported selecting text with the keyboard. But since #3814 also made labels selectable by default (if I'm understanding that code correctly), it has the unwanted side effect of putting _all_ labels in the tab order. I think we can solve this problem one of two ways:

* amke labels non-selectable by default, and require applications to opt into text selection for specific labels
* Or, modify the code for setting up the label's `Sense` such that it doesn't make the label focusable, even though clicking and possibly dragging are enabled

**Comment by emilk** [comment]
Good catch! Your diagnosis is spot on, and I think the solution makes sense too: labels should sense clicks and drags, but not be focusable.
