### ISSUE TITLE
Customize eframe persistence file path

### ISSUE THREAD

**Issue by C0D3-M4513R** [emilk/egui#3927]
**Is your feature request related to a problem? Please describe.**

When making an app, where you want to allow saving to a custom location (e.g. because you want your users to be able to work on multiple projects at once), you basically have to create a custom `eframe::Storage` implementation, which for me boils down to just copying the file that `eframe::native::FileStorage` resides in, removing the profiler macros and making the `eframe::native::FileStorage::from_ron_filepath` public.

 
**Describe the solution you'd like**

just make `eframe::native::FileStorage::from_ron_filepath` public

**Describe alternatives you've considered**

just copy the existing implementation

**Additional context**

**Comment by emilk** [comment]
Sure - you wanna make a PR? 🙏

**Comment by YgorSouza** [comment]
Did #4423 resolve this?

**Comment by emilk** [comment]
I'll mark this as closed by https://github.com/emilk/egui/pull/4423 
If you have further requests, please open a new issue
