### ISSUE TITLE
no `http` in `epi`

### ISSUE THREAD

**Issue by scrubjay55** [emilk/egui#394]
I use the template from https://github.com/emilk/egui_template/ so http feature is enabled but when i try to:
```
use eframe::{egui, epi};
use epi::http;
```

I get this error: `no http in epi`

I can't really tell what's wrong here.. I have been going through examples and I have seen the demo app using this in the http part.

**Comment by emilk** [comment]
https://github.com/emilk/egui_template/blob/master/Cargo.toml does not enable the `http` feature by default. Are you sure you are enabling it?

You should have something like `eframe = { version = "0.12.0", features = ["http"] }`

**Comment by scrubjay55** [comment]
All good now. Sorry my bad.
