### ISSUE TITLE
egui.rs appears to be broken

### ISSUE THREAD

**Issue by jleibs** [emilk/egui#3941]
**Describe the bug**
Very few elements render. Specifically missing all text.

**To Reproduce**
Go to: https://www.egui.rs/

**Expected behavior**
Page should render.

**Screenshots**
![image](https://github.com/emilk/egui/assets/3312232/aeab8710-e8de-4cca-8b8e-814962f3957c)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome, Firefox
 - Version 22.10

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOs
 - Browser Safari
 - Version 

**Additional context**

**Comment by Wumpf** [comment]
Repros on Firefox @ Mac as well.
egui.rs is on glow, haven't tried wgpu yet

**Comment by YgorSouza** [comment]
It's not loading the default font, it seems. The same happens on desktop linux and with wgpu. It was caused by https://github.com/emilk/egui/commit/00cd671ad8db895438f66b8995ea05199a9333ed, the previous commit is working fine.
