### ISSUE TITLE
UI resizes infinitly

### ISSUE THREAD

**Issue by xNxExOx** [emilk/egui#3952]
Under some circumstances the UI starts to resize in one direction, even though there is no obvious reason for it.
It happen to me multiple times, but because of non public dependencies I did not have any example.
I still do not have a small example, but placing breakpoint at the [linked line](https://gitlab.com/xxxkubikx/map_editor/-/blob/211f638fb5b8f604d5c86d79cea121c17f0b52df/src/app/map/generator/empty/height_map/modifiers.rs#L591) gives relatively small scope to start with investigating.

**To Reproduce**
1. Build and run https://gitlab.com/xxxkubikx/map_editor/-/blob/211f638fb5b8f604d5c86d79cea121c17f0b52df/src/app/map/generator/empty/height_map/modifiers.rs#L585
2. Click on `❗ WIP ❗ Generate random map` (as shown in the video: https://discord.com/channels/900275882684477440/904461220592119849/1202992360179368007)
3. Watch it expand

**Expected behavior**
`ui.vertical(|ui|{/*nothing*/})` does not cause any resizing.

**Screenshots**
When trying to debug it I noticed `min_rect.min` being  bigger, than `max_rect.min`?
![obrazek 1](https://github.com/emilk/egui/assets/1893229/ec684bd5-2a22-474d-8ebb-63f82c915f36)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.25

**Comment by emilk** [comment]
Without a minimal reproduce, this isn't actionable.

Try using https://docs.rs/egui/latest/egui/style/struct.DebugOptions.html#structfield.show_expand_width, or come up with a simple repro

**Comment by xNxExOx** [comment]
I finally got a very simple example that reproduces the issue:
```rs
egui_extras::TableBuilder::new(ui)
.stick_to_bottom(true)
.column(egui_extras::Column::remainder())
.body(|body|{
    body.rows(20., 100, |mut row|{
        let i = row.index();
        row.col(|ui|{
            ui.label(format!("{i}"));
        });
    });
});
let mut b = true;
ui.checkbox(&mut b, "test");
```
Without the checkbox under the table everything is OK, after adding the checkbox it resized to some maximum size (bigger than the OS window, and it is impossible to make it smaller.

**Comment by xNxExOx** [comment]
@emilk should I create a second issue about exactly the same? Or is the example I found enough?
