### ISSUE TITLE
Windows: High CPU Usage when minimized

### ISSUE THREAD

**Issue by SitiSchu** [emilk/egui#3982]
**Describe the bug**
When minimized a simple egui application will use up to 17% CPU on my CPU while using 0% when not minimized

**To Reproduce**
1. Take a very simple egui application:
```rust
use eframe::egui;

fn main() -> Result<(), eframe::Error> {
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default().with_inner_size([320.0, 240.0]),
        ..Default::default()
    };

    eframe::run_simple_native("My egui App", options, move |ctx, _frame| {
        egui::CentralPanel::default().show(ctx, |ui| {
            ui.heading("My egui Application");
        });
    })
}
```
2. Run it
3. Observe CPU usage while open, if the mouse cursor is not in the window it will drop to 0
4. Minimize window
5. CPU Usage will go up a lot

**Expected behavior**
CPU Usage should stay low or at least close to the same CPU Usage when not minized

**Screenshots**
When idle and not minimized:
![image](https://github.com/emilk/egui/assets/18517178/43841c03-6941-48a3-a2e3-ed486ff4af88)
After being minimized:
![image](https://github.com/emilk/egui/assets/18517178/c161b565-68a7-40a8-b781-bcbc040de621)

**Desktop:**
 - OS: Windows 10 21H2 (19044.3086)
 - Version: latest master (56bf8b7)

**Additional context**
This does not happen with 0.25

**Comment by rustbasic** [comment]
@SitiSchu 
Please refer to patch #3985 to fix it.

**Comment by SitiSchu** [comment]
That fixed the issue, thanks!

**Comment by yakrider** [comment]
This issue seems to still exist when the window is hidden (or set invisible) instead of just minimized .. (in win-11)
