### ISSUE TITLE
Custom frames for windows not applied correctly

### ISSUE THREAD

**Issue by Tearth** [emilk/egui#4002]
**Describe the bug**
Since version 0.25 there is a visual bug when we set a custom window frame. In 0.24 the code below was making the window all green (as expected) with little margin.

```rust
let frame = egui::containers::Frame::none()
    .fill(egui::Color32::from_rgb(180, 220, 160))
    .inner_margin(egui::Margin::symmetric(20.0, 20.0));
```

In 0.25 and 0.26 the same code makes it only partially green with title bar area still with its original color, which is also not properly adjusted to the title.

![image](https://github.com/emilk/egui/assets/26147774/7beda39f-da3f-432b-bdef-052bdb93e51c)

**To Reproduce**
1. Go to egui_demo_lib -> window_options.rs
2. Find creation of "demo_window_options" window
3. Make it as below:

```rust
use super::View as _;
let frame = egui::containers::Frame::none() // <-- new
	.fill(egui::Color32::from_rgb(180, 220, 160)) // <-- new
	.inner_margin(egui::Margin::symmetric(20.0, 20.0)); // <-- new
let mut window = egui::Window::new(title)
	.id(egui::Id::new("demo_window_options"))
	.frame(frame) // <-- new
	.resizable(resizable)
	.constrain(constrain)
	.collapsible(collapsible)
	.title_bar(title_bar)
	.scroll2(scroll2)
	.enabled(enabled);
```

**Expected behavior**
Just as in 0.24 and earlier, the whole window area should be colored green with no exception for title bar.

**Comment by emilk** [comment]
Was this solved by https://github.com/emilk/egui/pull/3995 ?

**Comment by Tearth** [comment]
Sadly no, I was testing it on the most recent master which already includes fix from #3995.

**Comment by rustbasic** [comment]
@Tearth
Is it similar to #3806 ?

**Comment by Tearth** [comment]
> @Tearth Is the color-related thing similar to #3806 ?

Seems like yes, and turns out adding `context.style_mut(|p| p.visuals.window_highlight_topmost = false);` similarly as you did in your issue fixed the thing - the window is now displayed as I was used to before 0.25. Thanks for the link!
