### ISSUE TITLE
Zooming with ctrl + MouseWheel does not work as expected on a Mac

### ISSUE THREAD

**Issue by quadruple-output** [emilk/egui#401]
**Describe the bug**

Holding `CTRL` while turning the mouse wheel is translated to a Zoom event. This is correct on Windows, but on a Mac the correct modifier key would be `Command` rather than `CTRL`.

(On a Mac, the combination `CTRL`+Wheel is captured by the OS and triggers a full-screen zoom.)

**To Reproduce**
1. On a Mac: `cargo run -p egui_demo_app`
2. Open the "Plot" demo
3. try zooming with `Command`+MouseWheel (only moves but does not zoom) or `CTRL`+MouseWheel (triggers hardware full-screen zoom which is not desired)

**Comment by emilk** [comment]
I picked ctrl-scroll because that's how I zoom in Firefox, but I notice cmd-scroll also works. Perhaps egui_glium should treat both as a zoom event?

**Comment by quadruple-output** [comment]
Oh, ok… I am glad you tested this on your machine.

Keybindings on the Mac often surprise me. I think I found the setting that makes the difference for me: System Preferences → Accessibility → Zoom → [/] Use scroll gesture with modifier keys to zoom (can be configured as "Control", "Option", or "Command")
