### ISSUE TITLE
Update Issue : #4006 

### ISSUE THREAD

**Issue by rustbasic** [emilk/egui#4015]
@emilk 

Update Issue : #4006 

After update 4006, you will no longer be able to click any button on an image (in fact any button) that is not visible on screen when the image is enlarged.

If you read this post, please mark it with an eye emoji.

----------------------
Reference :

May be,
Should we save the results of all events first?

egui/crates/egui/src/widgets/image.rs : fn ui(self, ui: &mut Ui)
337 line
let (rect, response) = ui.allocate_exact_size(ui_size, self.sense);
to
let (rect, response) = ui.allocate_exact_size(ui_size, egui::Sense::click_and_drag());

it's a good result.
But, One problem found in this case is that the Image in the ScrollArea cannot be dragged with the mouse after being enlarged.
then,

    `let (rect, response) = ui.allocate_exact_size(ui_size, egui::Sense::click_and_drag());`
    to
    `let (rect, response) = ui.allocate_exact_size(ui_size, egui::Sense::click());`
it's a good result.

Or, Should it be this way?

First, save all information with click_and_drag().
Then, information is removed according to the Sense settings.
May be, Remove it from the interact() function
Please refer to the contents so far.

----------------------

**Comment by emilk** [comment]
#4006 will not be merged, so I'll close this
