### ISSUE TITLE
Difference between Label height and Button height

### ISSUE THREAD

**Issue by rustbasic** [emilk/egui#4023]
@emilk 

Difference between Label height and Button height

Because the height of the Button and Label are different,
When displayed together, the Button is in the center,
The Label appears to be attached to the top.

The height of the Button and Label are the same, or
It would be good to have a Label function with the same height as the Button.
(Of course, SelectedLabel is the same height as Button.)

egui version : ALL

**Comment by YgorSouza** [comment]
For what it's worth, you can center the label using a `Grid` (or a `Layout` with the alignment set to center).

```rs
        egui::CentralPanel::default().show(ctx, |ui| {
            ui.style_mut().spacing.button_padding.y = 10.0;
            Grid::new("my grid").num_columns(2).show(ui, |ui| {
                ui.label("Some text");
                ui.button("Button");
            });
        });
```

![image](https://github.com/emilk/egui/assets/43298013/e7e1b23f-1463-44dc-8bff-e9bd0190a1e9)

**Comment by rustbasic** [comment]
@YgorSouza 

Yes, that's good advice.

Instead of using 'Grid', I would like to have a `Label` function with the same height as the `Button`.

**Comment by rustbasic** [comment]
@YgorSouza

Yes, thank you. that's good advice, too.

Additionally, I would like to have a Label function with the same height as the Button.
It is intended for anyone to use easily.
( What I make, I think will have bad results. )
