### ISSUE TITLE
Width of the window title bar with custom frame

### ISSUE THREAD

**Issue by Tearth** [emilk/egui#4024]
**Describe the bug**
While testing #4002 (thanks for the fast fix!) on 0.26.1, I found another issue, or at least I think it was not desired. When setting the inner margin and stroke, the title bar is wider than the window's content as can be seen below. I've put some ridiculous values to show it clearly, but it's visible even when the stroke is just a few pixels wide.

![image](https://github.com/emilk/egui/assets/26147774/0d5424d6-7227-432d-83b4-a6dfd64dde8e)

**To Reproduce**
1. Go to egui_demo_lib -> window_options.rs
2. Find creation of "demo_window_options" window
3. Make it as below:

```rust
use super::View as _;
let frame = egui::containers::Frame::none() // <-- new
	.fill(egui::Color32::from_rgb(180, 220, 160)) // <-- new
	.stroke(egui::Stroke::new(20.0, egui::Color32::from_rgb(40, 100, 30))) // <-- new
	.inner_margin(egui::Margin::symmetric(20.0, 20.0)); // <-- new
let mut window = egui::Window::new(title)
	.id(egui::Id::new("demo_window_options"))
	.frame(frame) // <-- new
	.resizable(resizable)
	.constrain(constrain)
	.collapsible(collapsible)
	.title_bar(title_bar)
	.scroll2(scroll2)
	.enabled(enabled);
```

**Expected behavior**
The title bar should respect margin/stroke settings and have the same width as the rest of the window.

**Comment by rustbasic** [comment]
Related Issue: #3806

The egui::Window active.
This causes TitleBar to be activated and paint the backgound to display the TitleBar as active.
This occurs because the width (thickness) of the Stroke used in the frame is not excluded when the TitleBar is activated and displayed.

Until the bug is fixed,
You may temporarily disable a title.

```rust
             let mut visuals = ui.visuals_mut().clone();
             visuals.window_highlight_topmost = false;
             ui.ctx().set_visuals(visuals);
```

**Comment by rustbasic** [comment]
I'm editing this issue for Pull Request, and I think I'll have it done soon.

**Comment by Tearth** [comment]
Thank you!
