### ISSUE TITLE
egui::Response::interact() does not sense click on 0.26.0

### ISSUE THREAD

**Issue by jjtuffreau-haven** [emilk/egui#4034]
**Describe the bug**

This snippet used to work in 0.25 and isn't working anymore in 0.26.
```
// Draw a hoverable custom widget
let (rect, response) = ui.allocate_exact_size(egui::vec2(20.0, 20.0), Sense::hover());
if ui.is_rect_visible(response.rect) {
    ui.painter().add(RectShape::new(
        rect,
        0.5,
        egui::Color32::GREEN,
        egui::Stroke::NONE,
    ));
}
// Make it clickable
let response = response.interact(Sense::click());
// Detect click
if response.clicked() {
    println!("SUCCESS");
}
```

This is a simplified version of a use case where I need to make a widget clickable while it is not initially clickable...

**To Reproduce**
See snippet above.

**Expected behavior**
Print "SUCCESS" on click on 0.25.0, doesn't print on 0.26.0

**Desktop (please complete the following information):**
 - OS: windows (using eframe 0.26)

**Comment by YgorSouza** [comment]
Did you try on 0.26.1? Normally this was hotfixed by #4013.

**Comment by jjtuffreau-haven** [comment]
you're right!
