### ISSUE TITLE
Clamping a `DragValue` clears invalid value visually but not internally

### ISSUE THREAD

**Issue by OfficialURL** [emilk/egui#404]
**Describe the bug**
When a `DragValue`'s clamp range is changed, if its previous value ends outside of the new limits, the value that is shown is updated to be on the correct range. However, the internal value remains unchanged, which leads to a discrepancy between the shown and the internal value.

**To Reproduce**
1. Make two `DragValue`s and have the first control the clamping range of the second. 
2. Set the maximum value for the second `DragValue`.
3. Use the first `DragValue` to clamp the second one into a range that makes the previous value invalid.
4. The value shown on the second `DragValue` will be within the desired range, but if we print out its value, we'll see that the internal value isn't.

**Expected behavior**
The internal and shown value should always coincide.

**Additional context**
My guess is that the shown value has a check in place to clamp the value, but the internal value doesn't. So perhaps this check should simply be moved within the code?

**Comment by OfficialURL** [comment]
By the way, by "internal value", I mean the `&mut f64` that is passed into the method. I understand that a `DragValue` doesn't really own the value it holds.

**Comment by OfficialURL** [comment]
Wait, it seems like my fix now causes the opposite effect. When a `DragValue` is reclamped, it changes by **twice** of what it should, even though the shown value is correct. Any idea of what might be causing this discrepancy?

**Comment by emilk** [comment]
I don't understand. Can you give a short code example of what you are trying to do and what goes wrong?

This is what I tried:

``` rust
            let mut value = 11.0;
            ui.add(egui::DragValue::new(&mut value).clamp_range(0.0..=10.0));
            ui.label(value.to_string());
```

and the value is shown as 10 (both by the `DragValue` and the label), as it should.

**Comment by OfficialURL** [comment]
Nevermind, I wasn't using the latest version of `egui`. Tested this twice, and it seems to have worked. Thanks for the help!
