### ISSUE TITLE
TextAgent assumes canvas is aligned to the top

### ISSUE THREAD

**Issue by canselcik** [emilk/egui#4060]
https://github.com/emilk/egui/blob/f7fc3b0154bfef4f7f787f0eab21c48fe497b583/crates/eframe/src/web/text_agent.rs#L153-L154

There seems to be no way to disable this. Any input to the canvas makes the canvas get a `position: absolute, top: 0%`, breaking layout.

Maybe `mouseup` shouldn't result in `text_agent::update_text_agent(runner)` getting called.

Maybe eframe should save some of the original style attributes of the canvas and then restore them instead of making this assumption.

**Comment by emilk** [comment]
Web stuff is not really my skill set, so any help here would be appreciated.

**Comment by canselcik** [comment]
> Web stuff is not really my skill set, so any help here would be appreciated.

Would be happy to help. Am I understanding correctly that this is for IME support? Was this behind a feature flag in the past?

If this was for IME support, what's the intention behind changing the position of the canvas element at all? At a quick glance, it appears the intention would be to slide it up and down to accommodate the keyboard that would slide in on a mobile device but my assumption would be that the keyboard appearing would already have that effect.

**Comment by canselcik** [comment]
https://github.com/canselcik/egui/commit/be66734dd1ec4cbabe316de25e3642661b8644b2
How about something like this?

Since it is non-trivial accessing some configuration in that closure, I figured this would be a compromise-free option.

If the canvas isn't flush to the upper left corner of the page, pushing it up like it is currently done will result in potentially broken page layout. So if the canvas is flush to the upper left corner, we do what is currently done and then set an attribute on the canvas. We prefix it with `data-` as custom attributes doing that is allowed by the HTML5 spec. When the on screen keyboard is gone, we check for that custom attribute, if it is set, we unset it and "restore" the canvas back to the upper left corner of the page.

**Comment by jprochazk** [comment]
The current workaround is to add some CSS to the canvas:
```css
canvas {
  position: initial !important;
  top: unset !important;
}
```

Ideally, egui would never set the style of the canvas element for any reason.
