### ISSUE TITLE
[eframe native-windows] Entire program crashes when eframe viewport is resized from a corner

### ISSUE THREAD

**Issue by khyerdev** [emilk/egui#4061]
**Describe the bug**

I am using `eframe` version `0.26.2` on Windows 11. Whenever I resize the eframe window from the corner, the entire program crashes with the exit code `0xc0000005` which is `STATUS_ACCESS_VIOLATION`. No panic message is printed to the console. This is the same bug I found in an earlier project of mine that used version `0.25.0`.

**Video showcasing the bug**
https://github.com/emilk/egui/assets/82794982/258ef1e8-fdd6-4739-8540-2b4fe33552a1

**To Reproduce**
1. Create a new `NativeOptions` variable, with a resizable viewport
2. Open up a new `eframe` window using `eframe::run_native()` using the same `NativeOptions`
3. Use your mouse to drag any of the four corners of the `eframe` window in any way

**Expected behavior**

When I resize the window from the corner, I am expecting it to successfully resize as I drag my mouse, without any program crashes.

**Screenshots**

Here are the screenshots of the exit codes `cargo run` gave me
![image](https://github.com/emilk/egui/assets/82794982/f27a723a-f6f0-4811-b64c-681413c0e110)
![image](https://github.com/emilk/egui/assets/82794982/a5d21384-6e60-4070-be9e-a09412d26e4b)

**Desktop:**
 - OS: Windows 11 
 - Version: 23H2 build 22631.3085
 - CPU: Core i9 10900k

**Additional context**

This bug is forcing me to make a UI with a fixed viewport size.

This is not an issue about debug or release build profiles, as it happens in both of them.

This is also not an issue about the terminal in VSCode or compiling without `#![windows_subsystem = "windows"]`, since the issue remains in the VSCode terminal, in the native windows terminal, compiling with the "windows" windows subsystem, and compiling without said attribute. I testes the issue with all of these.

This issue does not affect fullscreening the window. That is safe.

I don't know if I am doing something wrong or if my OS configuration is messed up, or if this is an actual issue not fixed, because this seems like a large issue for eframe, yet I see no issue opened or closed about it. I am pretty sure resizing a window is not supposed to crash its entire program with a memory related status code.

This issue is coming from a personal project of mine to help me learn more about what I can do in Rust.

**Comment by emilk** [comment]
Have you tried the `wgpu` backend?

**Comment by OSCH2008** [comment]
How would I use it natively?

**Comment by emilk** [comment]
Just enable the `wgpu` feature of `eframe`

**Comment by OSCH2008** [comment]
Thank you!

Adding the `wgpu` feature does prevent the crashing, but it does also make the viewport look slightly stretched while I resize it, as well as doubling the file size of the output binary. Both of these I don't really like.

Not much of an issue though, and I can use it for now, but I would prefer if the default backend worked properly (no crashing when resizing from a corner)

**Comment by rustbasic** [comment]
@OSCH2008 

If you could make a simple example with one file (panic occurs when resizing), it would be helpful to check.

**Comment by YgorSouza** [comment]
I tried running the hello_world example on Windows 11 with the default features, and it didn't crash when resizing. Have you tried that? You have another dependency called screen-info that has a lot of unsafe code. Does it crash without that dependency as well? If you're only using it to center the window on the screen at startup, you can do that by passing `centered: true` to `NativeOptions`.

**Comment by OSCH2008** [comment]
I did use `screen-info` to calculate the center of my screen for the window, because I didn't like the inaccuracy of `centered = true` in one of my previous projects. But removing that dependency and using `centered = true` instead still did not stop the crashes.

**Comment by OSCH2008** [comment]
@rustbasic 
```rust
struct MainWindow;
impl MainWindow {
    fn create(_cc: &eframe::CreationContext<'_>) -> Self {
        Self
    }
}
impl eframe::App for MainWindow {
    fn update(&mut self, ctx: &eframe::egui::Context, _frame: &mut eframe::Frame) {
        eframe::egui::CentralPanel::default().show(ctx, |_ui| {
            // empty app
        });
    }
}

fn main() -> eframe::Result<()> {
    let options = eframe::NativeOptions::default();
    eframe::run_native("vscode", options, Box::new(|cc| Box::new(MainWindow::create(cc))))
}
```
using `eframe v0.26.2`

**Comment by rustbasic** [comment]
@OSCH2008 

With the above source code, I tested it with egui v0.26.2 on Windows 10.
There is nothing wrong.

I added one Viewport as follows and tested it all, and there was no problem.

```
struct MainWindow;
impl MainWindow {
    fn create(_cc: &eframe::CreationContext<'_>) -> Self {
        Self
    }
}
impl eframe::App for MainWindow {
    fn update(&mut self, ctx: &eframe::egui::Context, _frame: &mut eframe::Frame) {
        eframe::egui::CentralPanel::default().show(ctx, |ui| {
            ui.label("Main : Corner resize TEST");
            dev_viewport_immediate(ui);
        });
    }
}

fn main() -> eframe::Result<()> {
    let options = eframe::NativeOptions::default();
    eframe::run_native("vscode", options, Box::new(|cc| {
        Box::new(MainWindow::create(cc))
    }))
}

pub fn dev_viewport_immediate(ui: &mut egui::Ui) {

    let title = "Immediate Viewport";
    ui.ctx().show_viewport_immediate(
        egui::ViewportId::from_hash_of(title.clone()),
        egui::ViewportBuilder::default()
            .with_title(title.clone())
            .with_inner_size([800.0, 600.0]),
        |ctx, class| {
            assert!(
                class == egui::ViewportClass::Immediate,
                "This egui backend doesn't support multiple viewports"
            );

            egui::CentralPanel::default().show(ctx, |ui| {
                ui.label("Viewport : Corner resize TEST");
            });

            if ctx.input(|i| i.viewport().close_requested()) {
                // Tell parent viewport that we should not show next frame:
            }
        },
    );
}
```

**Comment by OSCH2008** [comment]
I copied the code and ran it on my machine, and I still had the same problem with both viewports. It might be an issue with Windows 11 or just my machine.

**Comment by rustbasic** [comment]
> I copied the code and ran it on my machine, and I still had the same problem with both viewports. It might be an issue with Windows 11 or just my machine.

`cargo update`
After trying once, try compiling again.

**Comment by OSCH2008** [comment]
@rustbasic 
![image](https://github.com/emilk/egui/assets/82794982/5ea87dde-40c4-4213-82e6-8d020b19145e)
still the same issue

**Comment by pm100** [comment]
@khyerdev I am trying to repro on windows 11. I used the 20 line source that was posted above. Can you post your cargo.toml file. I have a bare minimum

```
[dependencies]
eframe = {version="=0.26.2", default-features=false, features=["glow"]}
egui = {version="=0.26.2", default-features=false}
```

program runs for me, also works if I allow all defaults.

Can you run it in vscode debugger. You can see the failing stack trace. I edited the code to force a 0xc00005, this is what vscode shows

![image](https://github.com/user-attachments/assets/ebd7dd2d-e81e-4be5-a979-124068ca3e6d)

could you post a similar screenshot, it would be very helpful.

**Comment by khyerdev** [comment]
@pm100 hi
i stopped using vscode a long time ago and havent even used windows much, so i probably wont be able to give my stacktrace
but i can link the repo i was working on when i encountered this bug
https://github.com/khyerdev/whisperer
i only made this for my ap csp test so dont judge it too much

**Comment by pm100** [comment]
@khyerdev I am sure you are fed up with this by now but nobody else can repro. But Can I ask one more effort from you.

Its fairly  easy to tell windows to generate a mini dump when an app crashes 

Use procdump from the sysinternals tools set - https://learn.microsoft.com/en-us/sysinternals/downloads/procdump

You can run it without installing it via `\\live.sysinternals.com\tools\procdump`

Start your app, suppose its called crasher then run

`\\live.sysinternals.com\tools\procdump -e crasher.exe
`

 in a different console window. procdump is now watching the app and waiting for it to crash. Note . you must start the app first otherwise procdump will say it cant find the app.

Now crash the program by resizing the window , procdump will tell you it created a mindump file - about 5-10mb and where it is.

Then upload that dump somewhere (github, google drive, dropbox....) and let me know

Tx

**Comment by khyerdev** [comment]
well if nobody else can repro its probably an issue with just my machine
im sorry

**Comment by RogueMacro** [comment]
I am also struggling with this issue. I did not use egui when this problem arose, but I stumbled upon this issue and using the example from @rustbasic I ran into the same problem. Both causing a crash with the same exit code. Originally I was using [vello](https://github.com/linebender/vello), but figured out the problem was with wgpu. When resizing the window and making lots of redraws, I found the crashes to happen during `wgpu::SurfaceTexture::present()`. I have been getting both exit code `0xc0000005` and `0xc000041d`. This does not happen when using Vulkan as backend, but does when using OpenGL or DX12. I don't know more about what is causing this. @khyerdev if you have some more knowledge I would love to hear :)

**Comment by AvinashPrajapati** [comment]
```

use eframe::{self};
use eframe::egui::{self, CentralPanel, Sense, UiBuilder, ViewportCommand, RichText};

struct MyApp {
    window_size: egui::Vec2,
}

impl Default for MyApp {
    fn default() -> Self {
        MyApp {
            window_size: egui::vec2(400.0, 300.0),
        }
    }
}

impl eframe::App for MyApp {
    fn clear_color(&self, _visuals: &egui::Visuals) -> [f32; 4] {
        egui::Rgba::TRANSPARENT.to_array() // Make sure we don't paint anything behind the rounded corners
    }

    fn update(&mut self, ctx: &egui::Context, frame: &mut eframe::Frame) {
        custom_window_frame(ctx, frame, "Custom Window", &mut self.window_size, |ui| {
            ui.label(RichText::new("This is bold").strong());
        });
    }
}

fn custom_window_frame(
    ctx: &egui::Context,
    frame: &mut eframe::Frame,
    title: &str,
    window_size: &mut egui::Vec2,
    add_contents: impl FnOnce(&mut egui::Ui),
) {
    let panel_frame = egui::Frame {
        fill: ctx.style().visuals.window_fill(),
        rounding: 5.0.into(),
        stroke: ctx.style().visuals.widgets.noninteractive.fg_stroke,
        outer_margin: 0.5.into(), // so the stroke is within the bounds
        ..Default::default()
    };
    // panel_frame.

    CentralPanel::default().frame(panel_frame).show(ctx, |ui| {
        let mut app_rect = ui.max_rect();

        let title_bar_height = 25.0;
        let title_bar_rect = {
            let mut rect = app_rect;
            rect.max.y = rect.min.y + title_bar_height;
            rect
        };

        title_bar_ui(ui, title_bar_rect, title);

        // Add the contents:
        let content_rect = {
            let mut rect = app_rect;
            rect.min.y = title_bar_rect.max.y;
            rect
        }
        .shrink(4.0);
        let mut content_ui = ui.new_child(UiBuilder::new().max_rect(content_rect));
        add_contents(&mut content_ui);

        // Visual indicator for resizing
        // Resize interaction on bottom-right corner
        let resize_area_size = 10.0;
        let resize_rect = egui::Rect {
            min: app_rect.right_bottom() - egui::vec2(resize_area_size, resize_area_size),
            max: app_rect.right_bottom(),
        };

        let resize_response =
            ui.interact(resize_rect, egui::Id::new("resize_handle"), Sense::drag());
        if resize_response.dragged() {
            if let Some(pointer_pos) = resize_response.hover_pos() {
                let delta = pointer_pos - app_rect.right_bottom();

                // Update window size
                window_size.x = (window_size.x + delta.x).max(200.0); // Min width
                window_size.y = (window_size.y + delta.y).max(150.0); // Min height

                // Update the application rectangle

                // Update the app rectangle based on the new window size
                ctx.send_viewport_cmd(egui::ViewportCommand::InnerSize(*window_size));
                


                // ui.ctx().request_repaint();
            }
        }

        if resize_response.hovered() {
            ui.painter()
                .rect_filled(resize_rect, 1.0, egui::Color32::from_white_alpha(128));
        }
    });
}

fn title_bar_ui(ui: &mut egui::Ui, title_bar_rect: eframe::epaint::Rect, title: &str) {
    use egui::{vec2, Align2, FontId, Id, PointerButton, Sense, UiBuilder};

    let painter = ui.painter();

    let title_bar_response = ui.interact(
        title_bar_rect,
        Id::new("title_bar"),
        Sense::click_and_drag(),
    );

    // Paint the title:
    painter.text(
        title_bar_rect.center() - egui::vec2(title_bar_rect.width() / 3.0, 0.0),
        Align2::CENTER_CENTER,
        title,
        FontId::proportional(15.0),
        ui.style().visuals.text_color(),
    );

    // Paint the line under the title:
    painter.line_segment(
        [
            title_bar_rect.left_bottom() + vec2(1.0, 0.0),
            title_bar_rect.right_bottom() + vec2(-1.0, 0.0),
        ],
        ui.visuals().widgets.noninteractive.bg_stroke,
    );

    // Interact with the title bar (drag to move window):
    if title_bar_response.double_clicked() {
        let is_maximized = ui.input(|i| i.viewport().maximized.unwrap_or(false));
        ui.ctx()
            .send_viewport_cmd(ViewportCommand::Maximized(!is_maximized));
    }

    if title_bar_response.drag_started_by(PointerButton::Primary) {
        ui.ctx().send_viewport_cmd(ViewportCommand::StartDrag);
    }

    // Close button for the window
    ui.allocate_new_ui(
        UiBuilder::new()
            .max_rect(title_bar_rect)
            .layout(egui::Layout::right_to_left(egui::Align::Center)),
        |ui| {
            ui.spacing_mut().item_spacing.x = 0.0;
            ui.visuals_mut().button_frame = false;
            ui.add_space(8.0);
            close_button(ui);
        },
    );
}

fn close_button(ui: &mut egui::Ui) {
    use egui::{Button, RichText};

    let button_height = 12.0;

    let close_response = ui
        .add(Button::new(RichText::new("❌").size(button_height)))
        .on_hover_text("Close the window");
    if close_response.clicked() {
        ui.ctx().send_viewport_cmd(egui::ViewportCommand::Close);
    }
}

fn main() -> eframe::Result {
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_decorations(false) // Hide the OS-specific "chrome" around the window
            .with_inner_size([400.0, 600.0]) // Set the initial size
            .with_min_inner_size([200.0, 300.0]) // Minimum size for the window
            .with_transparent(true), // To have rounded corners we need transparency
        ..Default::default()
    };

    eframe::run_native(
        "Custom Window with Close Button",
        options,
        Box::new(|_cc| Ok(Box::<MyApp>::default())),
    )
}

```

** i got the same issue here**
- My toml file code
```
[package]
name = "egui-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"

```

When i resize it very fast then the application just crashes.

**Any solution??**

**Comment by AvinashPrajapati** [comment]
I am guessing sending the command to resize the viewport on fast resize(each change in dimensional unit sends the command to viewport to resize)  the application can not process and get crashes.
```
// Update the app rectangle based on the new window size
                ctx.send_viewport_cmd(egui::ViewportCommand::InnerSize(*window_size));
```
