### ISSUE TITLE
error: no such command: `cranky`

### ISSUE THREAD

**Issue by FreePhoenix888** [emilk/egui#4067]
**Describe the bug**

In pull request template you have told us 

> * Remember to run \cargo fmt and `cargo cranky`.

 but there is no `cranky` command:
```
PS C:\Users\FreePhoenix\Documents\Programming\egui> cargo cranky
error: no such command: `cranky`

        Did you mean `yank`?

        View all installed commands with `cargo --list`
 ```
 
**To Reproduce**
1. `git clone https://github.com/emilk/egui.git`
2. `cd egui`
3. `cargo build`
4. `cargo cranky`

**Expected behavior**

cranky script to be executed
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by YgorSouza** [comment]
You have to install [cargo-cranky](https://crates.io/crates/cargo-cranky). Or run the check script (`scripts/check.sh`) and let it install everything for you.

**Comment by FreePhoenix888** [comment]
> You have to install [cargo-cranky](https://crates.io/crates/cargo-cranky). Or run the check script (`scripts/check.sh`) and let it install everything for you.

Why is not it dev dependency that will be installed when we `cargo build`?
