### ISSUE TITLE
The program screen flickers (shakes) when resizing.

### ISSUE THREAD

**Issue by rustbasic** [emilk/egui#4070]
The program screen flickers (shakes) when resizing.

OS: Windows 10
egui Version : ALL, master

**Comment by jk-gan** [comment]
Hi, I saw you create a PR to fix this, may I know what is the status of this? I still getting this with an empty `eframe_template` project. This is the latest 0.28 version.


https://github.com/emilk/egui/assets/7545747/dda19013-e035-458f-838d-cd7c64083380

**Comment by jk-gan** [comment]
Got it.

**Comment by jk-gan** [comment]
Btw, I notice the screen no longer flicker when using `wgpu` 🤔

**Comment by rustbasic** [comment]
When using `wgpu`, it flickers.
When using `glow`, it doesn't flickers.

After checking, `wgpu` itself enlarges/reduces the contents when resizing, so you need to provide a function in `wgpu` to make it not flickers.
Currently, it seems that `wgpu` doesn't have a function to not enlarge/reduce the contents when resizing the window.

**Comment by d3bgger** [comment]
Seeing that this issue was closed https://github.com/gfx-rs/wgpu/issues/6158 and not being addressed from wgpu side, is there any update to this from egui side?

**Comment by rustbasic** [comment]
> Seeing that this issue was closed [gfx-rs/wgpu#6158](https://github.com/gfx-rs/wgpu/issues/6158) and not being addressed from wgpu side, is there any update to this from egui side?

I briefly checked if this issue could be easily resolved, but it seems like it's not a simple one. 
I mainly use `glow`, so I don't have time to fix the `wgpu` issue. 
It seems like no one has a plan to solve this yet. 

Using `glow` in egui works without any problems.

**Comment by rustbasic** [comment]
I mainly use `glow`, so I don't have time to fix the `wgpu` issue.

It would be great if someone could fix this. I'm going to close it for now.

**Comment by d3bgger** [comment]
Thanks for the update. But why close it and not keep it open until fixed? Maybe someone wants to pick it up (maybe I can try when I am more familiar).

**Comment by rustbasic** [comment]
> Thanks for the update. But why close it and not keep it open until fixed? Maybe someone wants to pick it up (maybe I can try when I am more familiar).

This has been open for a long time.
I closed it because if I leave it open, you might think I'm working on solving it.
It's okay if you open it again with the same issue.
