### ISSUE TITLE
error: implementation of `Deserialize` is not general enough

### ISSUE THREAD

**Issue by suprohub** [emilk/egui#4087]
**Describe the bug**
`error: implementation of `Deserialize` is not general enough
  --> src/app.rs:33:20
   |
33 |             return eframe::get_value(storage, eframe::APP_KEY).unwrap_or_default();
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ implementation of `Deserialize` is not general enough
   |
   = note: `Game<'_>` must implement `Deserialize<'0>`, for any lifetime `'0`...
   = note: ...but `Game<'_>` actually implements `Deserialize<'1>`, for some specific lifetime `'1`
`

**To Reproduce**
`#[derive(serde::Deserialize, serde::Serialize)]
#[serde(default)] // if we add new fields, give them default values when deserializing old state
pub struct Game<'a> {
    #[serde(borrow)]
    pub name: &'a str,

    pub game_data_unparsed: String,

    #[serde(borrow)]
    pub game_data: HashMap<&'a str, (&'a str, u32)>,

    #[serde(skip)]
    pub main_layout: LayoutType
}

impl<'a> Game<'a> {
    /// Called once before the first frame.
    pub fn new(cc: &eframe::CreationContext<'_>) -> Self {
        // This is also where you can customize the look and feel of egui using
        // `cc.egui_ctx.set_visuals` and `cc.egui_ctx.set_fonts`.

        // Load previous app state (if any).
        // Note that you must enable the `persistence` feature for this to work.
        if let Some(storage) = cc.storage {
            return eframe::get_value(storage, eframe::APP_KEY).unwrap_or_default();
        }

        Default::default()
    }
}
`
**Expected behavior**
no eror

**Desktop (please complete the following information):**
 - OS: linus mint latest

**Comment by emilk** [comment]
please format your code properly.

But it seems like you are trying to deserialize borrowed data and yeah, eframe doesn't support that. I'm not sure it can. If that is the problem, please open a new and better written issue
