### ISSUE TITLE
android persistence feature

### ISSUE THREAD

**Issue by sbechet** [emilk/egui#4098]
Hello,

It seems `eframe` [directories-next](https://crates.io/crates/directories-next) dependencies can't handle android.

Any idea how we can implement persistence on systems other than Linux, macOS, Redox and Windows?

Thank you.

**Comment by sbechet** [comment]
logcat: 

```
1708977138.478 10288  7286  7315 I eframe  : Both the glow and wgpu renderers are available. Using wgpu.
1708977138.481 10288  7286  7315 W winit::platform_impl:..: TODO: forward onStart notification to application
1708977138.502 10288  7286  7315 W eframe::native::file_..: Saving disabled: Failed to find path to data_dir.
```

- see [eframe file_storage](https://github.com/emilk/egui/blob/master/crates/eframe/src/native/file_storage.rs) from_app_id() fn
- see [eframe file_storage](https://github.com/emilk/egui/blob/master/crates/eframe/src/native/file_storage.rs) storage_dir() fn
- see [directories-next](https://crates.io/crates/directories-next)

How to get the path to the default shared folder in all androids around the world?

**Comment by sbechet** [comment]
see [dodometer](https://codeberg.org/sbechet/dodometer) as an example.

**Comment by YgorSouza** [comment]
There is a discussion in the directories repo: <https://github.com/dirs-dev/directories-rs/issues/83>.
