### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by efendioglukdz** [emilk/egui#4102]
Is there any known issues with drag and drop functionality. Because in the newer versions of egui >24 this functionality doesnt work anymore. I cant drag and drop files from outside into my window.

**Comment by emilk** [comment]
Drag-dropping files works great for `egui_demo_app` both on my Mac and on egui.rs

Please check out this repository and run `cargo run -p egui_demo_app`. If drag-dropping files into the app does not work, open a new issue with details about your system!
