### ISSUE TITLE
Layout is Broken in BottomUp Mode

### ISSUE THREAD

**Issue by fallaciousreasoning** [emilk/egui#411]
**Describe the bug**
`egui::Layout` doesn't layout content when the `egui::Direction` is `BottomUp`.

**To Reproduce**
1. Create a new layout with direction `BottomUp`
2. Add Content to the layout

This behavior is visible on the [Demo Site](https://emilk.github.io/egui/index.html) in the LayoutDemo. Layout works as expected in all modes except `BottomUp`.

**Expected behavior**
Expected the content to layout the same as in TopDown, but with the order reversed.

**Screenshots**

Broken `BottomUp` Layout
![image](https://user-images.githubusercontent.com/7678024/118652615-e2588c80-b83a-11eb-98df-81e7d656d6ae.png)

Not Broken `TopDown` Layout
![image](https://user-images.githubusercontent.com/7678024/118653177-5bf07a80-b83b-11eb-96b0-d488c6c9b1b7.png)

**Desktop (please complete the following information):**
Tested on the following devices:
- Windows Desktop
- Android Phone (Firefox)
- Android Phone (Chrome)
- Desktop Firefox

**Additional Details**
I came across this while trying to create a reversed column while trying out `egui`. I assumed I was doing something wrong but the issue reproduces in the demo app.

**Comment by emilk** [comment]
Thanks for the report! This was already fixed: https://github.com/emilk/egui/pull/386

**Comment by fallaciousreasoning** [comment]
Awesome, cheers!
