### ISSUE TITLE
`SidePanel::right`s with an `exact_width`  have incorrect padding

### ISSUE THREAD

**Issue by sobaq** [emilk/egui#4126]
**Describe the bug**

`SidePanel::right` incorrectly pads the right side of the panel when it has an `exact_width` set.

**To Reproduce**

The following `update` function roughly implements the screenshot below:

```rust
fn update(&mut self, ctx: &egui::Context, _: &mut eframe::Frame) {
    egui::SidePanel::right("right").exact_width(100.).show(ctx, |ui| {
        ui.label("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    });
    egui::SidePanel::left("left").exact_width(100.).show(ctx, |ui| {
        ui.label("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    });
    egui::CentralPanel::default().show(ctx, |ui| { });
}

```

**Screenshots**

<img width=500 src="https://github.com/emilk/egui/assets/109554668/82bdab2b-5c8c-49b6-8289-46cbf583ffaf">

**Desktop (please complete the following information):**
- OS: Linux.

**Additional Information**

As implied, the padding is correct when an `exact_width` is not given.

**Comment by sobaq** [comment]
Closely related to #3006, I wouldn't call it a duplicate but I'd be happy to close this if need be.

**Comment by RylanYancey** [comment]
I am also experiencing this problem! Here is what I'm seeing: 

![Screenshot from 2024-03-10 18-42-53](https://github.com/emilk/egui/assets/76256852/0edb7a83-851a-4d32-be68-3c454947fa1a)

The 'saved moves' panel is being rendered on top of 'Nxf6' and the multiline text widget. Heres' my src:

![Screenshot from 2024-03-10 18-44-39](https://github.com/emilk/egui/assets/76256852/95cc99be-167d-408e-a309-7781d9602f60)

(screenshot cuz my editor is being weird about copying)

I'm calculating what I want the width to be (40% of the screen space for the notes panel, and 10% for the moves panel), then assigning it by using `exact_width()`. However, this results in the aforementioned issue.

Thanks!
    - Rylan Yancey
