### ISSUE TITLE
`Ui::scroll_to_me` cannot be called for two separate ScrollArea during the same frame

### ISSUE THREAD

**Issue by abey79** [emilk/egui#4167]
`Ui::scroll_to_me` appears to use a single, global state to store the scroll target (`FrameState::scroll_target`). This means that it's not possible to change the scroll position of two separate scroll areas during the same frame. This is a problem e.g. for https://github.com/rerun-io/rerun/issues/5232, where two scroll area should scroll to focused item at the same time.

**Comment by emilk** [comment]
Having two calls to `scroll_to_me` in two separate `ScrollArea`:s _should_ already work

**Comment by abey79** [comment]
The situation was way more complicated than that and a couple of bugs were eventually found:
- https://github.com/emilk/egui/pull/4174
