### ISSUE TITLE
How to make a tree with selectable lines?

### ISSUE THREAD

**Issue by msklywenn** [emilk/egui#417]
**Is your feature request related to a problem? Please describe.**
I'd like to display a tree structure like the one made up of `CollapsibleHeaders` in the example, but I want to be able to select a line in the tree instead of opening/closing on every click. For that I would expect only the arrow icon to handle opening/closing and be able to detect clicks on the rest of the header, maybe even had more stuff in there.

**Describe the solution you'd like**
A solution I think would be to have a `CollapsingHeader::show_with_custom_header` with a lambda that handles the UI in the rectangle on the right of the arrow.

**Describe alternatives you've considered**
I don't have much ideas beside the above proposed solution.

**Additional context**
A screenshot from a customized hierarchy done with Unity:
![image](https://user-images.githubusercontent.com/1546678/118832675-1d050800-b8c1-11eb-89b5-0316edb54001.png)

I could implement the above solution if deemed appropriate.

**Comment by msklywenn** [comment]
I managed to hack something by modifying CollapsingHeader like proposed. I probably broke stuff but for my purpose it works. Let me know if you'd be interested in a PR: https://github.com/msklywenn/egui/commit/afb665adf7fe67af05cc1a94ccd074563996e498 (there's also another commit that makes the rectangle of the original CollapsingHeader optional)

https://user-images.githubusercontent.com/1546678/119153066-3046dd80-ba51-11eb-9426-70df4e79b16c.mp4

**Comment by tgolsson** [comment]
I combined the default non-callback header from CollapsingHeader with @msklywenn's implementation for icon as an expander widget here: https://github.com/tgolsson/egui/commit/25e88ef2b4a34383c4dce608afc8a8d34a75ef1d. I'm hoping to clean it up a bit more, but after that I might PR it back if you'd be OK with that @emilk. It's unfortunately a lot of duplicated code at the moment, but I think that these widgets fill different roles and double-dutying will make it bad for both.

**Comment by msklywenn** [comment]
@tgolsson have you checked the subsequent commit? I made it so the header closure returns the content closure so that if both manipulate the same variable, we don't end up with multiple moves of mutable values. https://github.com/msklywenn/egui/commit/bc0c00cdc9c8c5ff168037b3e37fc84b2daa3769

**Comment by tgolsson** [comment]
I didn't, no! I'll take a peek later today. What is the use-case where a label isn't enough and you need to mutate things in the closure? Renaming things in the hierarchy?

**Comment by msklywenn** [comment]
If I recall correctly, the thing that I was trying to mutate was the currently selected entry in the hierarchy. I don't exactly remember why I didn't just return the new value... Maybe it's due to how ui.toggle consumes a &mut. It was a few weeks back...

**Comment by gents83** [comment]
Is this something that was stopped or is there any chance to get it further?
I would have same exact need - so I would be interested either in developing it or iterate on yours 👍
