### ISSUE TITLE
There is on very rare occasions a case where a panic occurred at line 152 of layers.rs

### ISSUE THREAD

**Issue by rustbasic** [emilk/egui#4179]
There is on very rare occasions a case where a panic occurred at line 152 of layers.rs when a Viewport exit.
( At this time, self.0.len() == 0 )

( On screens with different pixels_per_point. )

thread 'main' panicked at C:\prog\egui\crates\egui\src\layers.rs:152:15:
index out of bounds: the len is 0 but the index is 0

**Comment by emilk** [comment]
Please run with `RUST_BACKTRACE=1` so we get a stack trace to the error

**Comment by rustbasic** [comment]
> Please run with `RUST_BACKTRACE=1` so we get a stack trace to the error

On monitors with different pixels_per_point, this symptom sometimes appears when request_repaint() is continuously called and the Viewport is continuously moved, so it does not appear easily.
I will post the report when I get it.
