### ISSUE TITLE
Using PathShape::line to draw an arc results in jagged edges at larger radii

### ISSUE THREAD

**Issue by murl-digital** [emilk/egui#4188]
**Describe the bug**
This could also serve as a feature request, but currently I have a usecase where I need to draw arcs of circles. I have an implementation that works for smaller radii (sub 25 pixels), but it rapidly gets more jaggy and aliased as the radius increase.

**To Reproduce**
This is the code I'm using, you get the same results if you just iterate over a range of integer degrees.
```
  let circle_radius = 100.0;
  let mut circle_points = Vec::new();
  let visual_angle = 180.0 + correcting_angle;
  let angle_range = 180.0_f32.max(visual_angle)..180.0_f32.min(visual_angle);
  for i in 1..=512 {
      let (sin, cos) = (i as f32).map_range(1.0_f32..512.0_f32, angle_range.clone()).to_radians().sin_cos();
  
      circle_points.push(painter.clip_rect().center() + Vec2::new(circle_radius * sin, circle_radius * cos));
  }
  painter.add(PathShape::line(circle_points, Stroke::new(2.0, Color32::GREEN)));
```

**Screenshots**
![image](https://github.com/emilk/egui/assets/8054329/526ff98a-703f-4b8e-b3d1-5c7f824b76eb)
A side by side example of arcs at 2 different radii

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Baseview backend
 - Version 0.26

**Comment by dataphract** [comment]
The typical way to render circular arcs is to approximate them using cubic Bezier curves of up to π/2 radians, using multiple curves to construct larger arcs. The computation for a single curve looks like

```rust
    // Center of the circle
    let xc = center.x;
    let yc = center.y;

    // First control point
    let p1 = center + radius * Vec2::new(start_angle.cos(), -start_angle.sin());

    // Last control point
    let p4 = center + radius * Vec2::new(end_angle.cos(), -end_angle.sin());

    let a = p1 - center;
    let b = p4 - center;
    let q1 = a.length_sq();
    let q2 = q1 + a.dot(b);
    let k2 = (4.0 / 3.0) * ((2.0 * q1 * q2).sqrt() - q2) / (a.x * b.y - a.y * b.x);

    let p2 = Pos2::new(xc + a.x - k2 * a.y, yc + a.y + k2 * a.x);
    let p3 = Pos2::new(xc + b.x + k2 * b.y, yc + b.y - k2 * b.x);
```

(see [this paper](https://www.researchgate.net/publication/265893293_Approximation_of_a_cubic_bezier_curve_by_circular_arcs_and_vice_versa) by Aleksas Riškus)

Here's a dial drawn using these approximate arcs:

![Screenshot from 2024-04-17 00-29-56](https://github.com/emilk/egui/assets/86984145/3451c900-45f0-4d9e-a49f-7d9ec25b3f19)

Would definitely be nice to have these in egui proper -- if it's a desired feature I'd be happy to write a PR!

**Comment by murl-digital** [comment]
please do! it'd make my life a lot easier

**Comment by murl-digital** [comment]
I implemented it myself for my [own widget library](https://vcs.cozydsp.space/cozy-dsp/cozy-ui/src/commit/d4706ec9f4592137307ce8acafb56b881ea54e35/src/util.rs#L49), I could easily PR this in if everyone's happy with my approach. However, it's still not being anti-aliased.

**Comment by murl-digital** [comment]
I'm fairly sure this bug isn't actually a real issue, the root cause on my end was accidentally drawing the same path 1000 times.
