### ISSUE TITLE
On wayland `ViewportCommand::InnerSize` doesn't update the content size

### ISSUE THREAD

**Issue by ColinKinloch** [emilk/egui#4196]
**Describe the bug**

On wayland (mutter) when the window is resized using `ViewportCommand::InnerSize` the viewport size doesn't match the window.

| Drag Resize Handle | Press "Phone Size" | Drag Resize Handle | Press "Desktop Size" |
| - | - | - | - |
| ![Screenshot from 2024-03-20 11-30-33](https://github.com/emilk/egui/assets/334272/19a6d819-4c9b-4f9d-b175-cf3cf8026a33) | ![Screenshot from 2024-03-20 11-28-20](https://github.com/emilk/egui/assets/334272/7ec5b50a-1dfa-4755-aa37-2f220a596c3c) | ![Screenshot from 2024-03-20 11-30-54](https://github.com/emilk/egui/assets/334272/ff5ad227-e962-4796-99e7-61c01279d5e8) | ![Screenshot from 2024-03-20 11-28-35](https://github.com/emilk/egui/assets/334272/01ebb808-df47-4dc5-887e-341732408ea5) |

I suspect this is because winit doesn't send `Resized` events after the resize, the correct way to handle this is applying the value returned from `request_inner_size` to the viewport here:

https://github.com/emilk/egui/blob/d449cb1d488cbc10915a3c720a232c01c1901561/crates/egui-winit/src/lib.rs#L1313-L1322

**To Reproduce**
1. On gnome shell press the Phone Size button, note the window contents are stretched
2. Resize the window, note the window contents are not stretched
3. Repeat

**Expected behavior**
Contents are not stretched

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 39

https://github.com/emilk/egui/pull/4197 makes it easier to test.

**Comment by zeta0134** [comment]
I just ran into this bug today. Same behavior, this time on Arch+KDE. Only occurs in Wayland, the same device with an x11 session computes the dimensions correctly, even with DPI scaling applied.

**Comment by ColinKinloch** [comment]
The behaviour is documented here:
https://docs.rs/winit/latest/winit/window/struct.Window.html#method.request_inner_size
