### ISSUE TITLE
Text can't be copied using Ctrl+C on WASM

### ISSUE THREAD

**Issue by sdasda7777** [emilk/egui#4213]
**Describe the bug**
For some reason, it seems the text can't be copied in the web version using Ctrl+C (on standard latin keyboard), when it can be copied without problem in the native version.

E.g.: https://sdasda7777.github.io/minesweeper6d/ , Help > About.

**Expected behavior**
Text to be able to be copied exactly the same in both versions.

**Desktop (please complete the following information):**
 - OS: Native builds seemingly not affected
 - Browser: Tested with both Chromium and Firefox.
 - Version: 26, but detected earlier

**Comment by rustbasic** [comment]
It seems to work normally in the web demo.

https://www.egui.rs/#demo

**Comment by sdasda7777** [comment]
You're absolutely right, but any idea why? I believe I create the labels in the same exact way [here](https://github.com/sdasda7777/minesweeper6d/blob/47d8b747f5d4cf79160b07cbf8951f731a2782f0/src/main.rs#L613 ) as he does [here](https://github.com/emilk/egui/blob/20b0637d42892b87fb8411b39c5c256fd32d7ee3/crates/egui_demo_lib/src/demo/about.rs#L29 ), and as I said, I can copy text just fine on the native version. Is there maybe some way you have to explicitly enable the copying in the WebOptions or something?

**Comment by sdasda7777** [comment]
I don't see any egui version or build date information in the Demo. Is is possible the demo was built before some sort of regression was made?

**Comment by rustbasic** [comment]
> I don't see any egui version or build date information in the Demo. Is is possible the demo was built before some sort of regression was made?

The web demo may be newer than v0.26.2.

**Comment by YgorSouza** [comment]
You can build the web demo locally with the command provided in the [readme](https://github.com/emilk/egui/blob/20b0637d42892b87fb8411b39c5c256fd32d7ee3/crates/egui_demo_app/README.md), and see if it is working in the current master and in the latest release, or do a bisect to see when it was broken/fixed.

**Comment by sdasda7777** [comment]
> You can build the web demo locally with the command provided in the [readme](https://github.com/emilk/egui/blob/20b0637d42892b87fb8411b39c5c256fd32d7ee3/crates/egui_demo_app/README.md), and see if it is working in the current master and in the latest release, or do a bisect to see when it was broken/fixed.

Seems like it's not that simple. I just did that on a Linux VM, and it all worked there. However when I tried the https://sdasda7777.github.io/minesweeper6d/, it all worked as well, while still not working outside the VM. Since nobody seems to know what version is actually running at https://www.egui.rs/#demo and I can't run Linux script on my real machine, I'm kind of out of ideas.

**Comment by YgorSouza** [comment]
You can run the scripts on Windows with Git Bash.

**Comment by sdasda7777** [comment]
Hmm, nevermind, I forwarded ports to the VM, and it did in fact work on the real machine. Guess this will be fixed in 0.26.3, then? 🤔

**Comment by YgorSouza** [comment]
The script does mention this:

https://github.com/emilk/egui/blob/20b0637d42892b87fb8411b39c5c256fd32d7ee3/scripts/build_demo_web.sh#L8-L11

But I tried running the script without this line and the clipboard still works, both on master and on 0.26.2, so 🤷

**Comment by sdasda7777** [comment]
Hmm, actually the demo works for me on 0.26.2 as well. Now I'm just confused 😕

**Comment by YgorSouza** [comment]
> The script does mention this:
> 
> https://github.com/emilk/egui/blob/20b0637d42892b87fb8411b39c5c256fd32d7ee3/scripts/build_demo_web.sh#L8-L11
> 
> But I tried running the script without this line and the clipboard still works, both on master and on 0.26.2, so 🤷

Ok, it is this, actually. It's just that the env var is also defined in the cargo config:

https://github.com/emilk/egui/blob/20b0637d42892b87fb8411b39c5c256fd32d7ee3/.cargo/config.toml#L1-L6

If I remove both and build the web demo, the clipboard doesn't work. So just add this to your repo and it should work fine.

**Comment by sdasda7777** [comment]
You're right, that works! Thanks 😁
