### ISSUE TITLE
Please adopt HTML/Mustache syntax

### ISSUE THREAD

**Issue by ceremcem** [emilk/egui#4237]
I took a look at the syntax in your examples and I found it a little bit complex. Would you consider using an intermediate template syntax, such as [Kivi](https://kivy.org/doc/stable/gettingstarted/rules.html)'s or [Ractive](https://ractive.js.org/api/)'s?

**Comment by emilk** [comment]
No - this is an immediate mode GUI, and is fundamentally different.

https://docs.rs/egui/latest/egui/#understanding-immediate-mode
