### ISSUE TITLE
Ui.collapsing does not work with multiple Ui.collapsing of the same name after version 0.27.0

### ISSUE THREAD

**Issue by UnknownSuperficialNight** [emilk/egui#4265]
**Describe the bug**

using ui.collapsing in a scrollarea with multiple ui.collapsing in with the same name causes issues with clicking on them aswell as closing them it seems the only the bottom one can be clicked on i have videos below 

**Expected behavior**

Here is a video using egui version '0.26.2'

Synopsis: I can click on all the elements with no problem, and clicking on any of them will trigger the rest to open and close without any issues.

https://github.com/emilk/egui/assets/88142731/3a8796d4-79d6-4efc-8849-4edb099e59db

**Here is a video of egui version 0.27.1 and 0.27.0 does the same thing as 0.27.1**

Synopsis: After version 0.27.0, I can't click on all the elements, only the very bottom one. And when I do, sometimes it opens; other times, it opens then closes as well. When it opens, it seems to glitch while scrolling down, going up, then back down a little. All this stops happening if you have one ui.collapse with a different name. In the video below, I called it "hi," and you can see that the element works with no problems.

https://github.com/emilk/egui/assets/88142731/9203837c-8d7d-4dee-b8cc-c03758c735b1

Desktop information):**
 - OS: Gnu/Linux 
 - Arch: x86_64 
 - Desktop: KDE Plasma v: 5.27.11 
 - Distro: Gentoo Base System release 2.14

**Comment by emilk** [comment]
The collapsing header needs a unique Id to store its state ('am i collapsed or not'). When using `ui.collapsing` the title is used as its Id, causing an Id clash. This was and still is a bug, it is just that the bug manifests differently now.

Use `CollapsingHader::id_source` to give each header its own unique `Id`.

If you compile with `debug_assertions` (or set `Options::warn_on_id_clash`) you should see a warning printed on screen when you have `Id` clashes

**Comment by YgorSouza** [comment]
> Is it possible to retain the functionality to purposefully share the same `Id` in order to be able to click on one of the matching `Id` and all with the same match open?

Here is an example that does what you are asking for:

```rs
        egui::CentralPanel::default().show(ctx, |ui| {
            (1..=5).for_each(|i| {
                let header = format!("header {}", i % 2);
                let open_id = egui::Id::new(&header);
                let open = ui
                    .data_mut(|data| data.get_persisted(open_id))
                    .unwrap_or(false);
                let toggle = CollapsingHeader::new(header)
                    .id_source(("different id", i))
                    .open(Some(open))
                    .show(ui, |ui| ui.label(format!("Body {i}")))
                    .header_response
                    .clicked();
                if toggle {
                    ui.data_mut(|data| data.insert_persisted(open_id, !open));
                }
            });
        });
```

[Screencast from 2024-03-29 19-28-45.webm](https://github.com/emilk/egui/assets/43298013/a10a6ef7-97c8-4cbe-a773-4f313b7abdff)



(If you don't want the open state to be persisted to the disk, use `get_temp`/`insert_temp` instead of persisted.

**Comment by UnknownSuperficialNight** [comment]
> > Is it possible to retain the functionality to purposefully share the same `Id` in order to be able to click on one of the matching `Id` and all with the same match open?
> 
> Here is an example that does what you are asking for:
> 
> ```rust
>         egui::CentralPanel::default().show(ctx, |ui| {
>             (1..=5).for_each(|i| {
>                 let header = format!("header {}", i % 2);
>                 let open_id = egui::Id::new(&header);
>                 let open = ui
>                     .data_mut(|data| data.get_persisted(open_id))
>                     .unwrap_or(false);
>                 let toggle = CollapsingHeader::new(header)
>                     .id_source(("different id", i))
>                     .open(Some(open))
>                     .show(ui, |ui| ui.label(format!("Body {i}")))
>                     .header_response
>                     .clicked();
>                 if toggle {
>                     ui.data_mut(|data| data.insert_persisted(open_id, !open));
>                 }
>             });
>         });
> ```
> 
> Screencast.from.2024-03-29.19-28-45.webm
> 
> (If you don't want the open state to be persisted to the disk, use `get_temp`/`insert_temp` instead of persisted.

You're a legend thanks a bunch
