### ISSUE TITLE
Text rotation

### ISSUE THREAD

**Issue by philipc** [emilk/egui#428]
I would like to be able to rotate text.

https://github.com/emilk/egui/issues/155#issuecomment-773472371 suggested adding a `Rot2` field to `Shape::Text`. I assume we then transform the vertices in `tessellate_text`, similar to the italic handling.

I think I'll also need to add a `Pos2` in order to rotate around the anchor, since the existing `pos` is already the top left. Is this the correct way to proceed? Alternatively I could change the existing `pos` to be the anchor and store the `Align2` in `Shape::Text`.

**Comment by philipc** [comment]
The other question is how to expose this in `Painter`. I assume we don't want to add a new parameter to all of `Painter::text/galley/galley_with_italics`, and #173 is adding more methods too. I think it might be better if `Shape::Text` used a real struct, so that it can be constructed and modified before putting it in the `Shape` enum.

**Comment by emilk** [comment]
This will be fairly easy to implement once https://github.com/emilk/egui/pull/682 is merged by just adding as `angle: f32` parameter to `Shape::Text` and using that in the tessellator.
