### ISSUE TITLE
Hover only interactions no longer work

### ISSUE THREAD

**Issue by AnotherNathan** [emilk/egui#4286]
**Describe the bug**
It seems that any hover only interaction is broken.

**To Reproduce**
Non of the following examples work any more.

```rust
Label::new("my label")
        .selectable(false)
        .ui(ui)
        .on_hover_text("tooltip");

let response = Label::new("my label").selectable(false).ui(ui);
response.interact(Sense::hover()).on_hover_text("tooltip");

let response = Label::new("my label").selectable(false).ui(ui);
ui.interact(response.rect, ui.next_auto_id(), Sense::hover())
        .on_hover_text("tooltip");
```
The tooltip is never shown.

**Expected behavior**
Tooltip should be shown when hovering with the cursor on the labels.

**Platform:**
 - OS: Windows 10
 - Version 22H2

**Additional context**
I tried 0.27 and master.
Note that this was working fine on 0.26.

**Comment by YgorSouza** [comment]
Reproducible in the demo app as well. If you open the settings and tick off "Selectable text in labels", you can no longer see the tooltips for the settings just above it. Also the progress bar in the widget gallery no longer displays an animation when you hover it.

**Comment by rustbasic** [comment]
Temporarily until corrected,
Useable `Sense::click()` or `Sense::click_and_drag()`.

**Comment by AnotherNathan** [comment]
Yes, this works as long as you do not have a widget, with a clickable area and a hoverable area inside of that clickable area (which is what I have unfortunately).
