### ISSUE TITLE
Question: why does `EguiGlium::on_event` take control of the app's control flow?

### ISSUE THREAD

**Issue by InnocentusLime** [emilk/egui#434]
I have noticed, that in `egui-glium`, `EguiGlium::on_event` takes a mutable reference to the control flow of the window's event loop. Upon further investigation it turned out that [here](https://github.com/emilk/egui/blob/master/egui_glium/src/lib.rs#L72) `egui-glium` handles the close requests **for the user**, essentially closing the app before the user gets a chance to do it themselves.

What's the reason behind that? No docs or comments inside code seem to suggest why the implementation should be doing that... And It doesn't seem to be too convenient either. Neither it seems to be something that a gui library should be doing...

**Comment by emilk** [comment]
You are right, this should be moved out to `egui_glium::run` instead
