### ISSUE TITLE
Place elements horizontally with a given direction

### ISSUE THREAD

**Issue by vihdzp** [emilk/egui#435]
There's a convenience method for building horizontal layouts: `Ui::horizontal`. This method places elements either from left to right or right to left according to the "preferred" direction of the layout. However, it seems like we aren't able to set our preferred direction. So to make a layout that goes the other way, we have to use a quite nontrivial workaround:
```rs
ui.allocate_ui_with_layout(ui.min_size(), Layout::right_to_left(), |ui| { ... });
```
I propose that there be a method similar to `Ui::horizontal` (and perhaps another for `Ui::vertical`) that allows us to easily specify the order of direction in which the elements are placed. Something similar to
```rs
ui.horizontal_with_direction(Direction::Rtl, |ui| { ... });
```
The `Ui::horizontal` method could simply call this more general method with the preferred orientation.

**Comment by quietvoid** [comment]
This seems possible in 0.17.0 now.
```rust
ui.with_layout(egui::Layout::right_to_left(), |ui| { ... })
```
