### ISSUE TITLE
i can't input chinese words into singleline properly

### ISSUE THREAD

**Issue by 799189288** [emilk/egui#4354]
[patch.crates-io]
`eframe = { features = [
    "default",
    "__screenshot", # __screenshot is so we can dump a screenshot using EFRAME_SCREENSHOT_TO
] }`
**Describe the bug**

When using the chinese input method, you can only successfully input once until the single line content is cleared.

**To Reproduce**
1. use chinese input method editor.
2. type some chinese words in the textEdit singleline
3. repeat step 2

**Screenshots**

https://github.com/emilk/egui/assets/73056742/39da1a88-b220-4bf0-9f32-e80756dbd02a

**Desktop (please complete the following information):**
 - OS: windows 11

**Comment by rustbasic** [comment]
What egui version did you use?

**Comment by rustbasic** [comment]
Is there anything wrong with multiline()?

**Comment by rustbasic** [comment]
Could you try Pull Request #4358, and let me know the results?

* #4358

**Comment by 799189288** [comment]
@rustbasic 
i have pulled your patch41 branch and try singleline and multiline, there is no change the problem still exist


https://github.com/emilk/egui/assets/73056742/47db15c2-42ef-4769-a06c-ead9829775c2

**Comment by rustbasic** [comment]
@799189288 

Again, could you please try Pull Request #4358 and let me know the results?

* #4358

**Comment by 799189288** [comment]
@rustbasic 
winit::event::Ime::Preedit this arm seems like unreachable, when i press the spacebar ,type into singline. there are some infomations: 
1.Ime Enabled
2.Ime Commit "测试"
3.Ime Disabled

**Comment by rustbasic** [comment]
@799189288 

Again, could you please try Pull Request #4358 and let me know the results?


* #4358

**Comment by 799189288** [comment]
@rustbasic great! it works now.

https://github.com/emilk/egui/assets/73056742/013097a8-c224-4403-a4b7-0c8220b65d4c

**Comment by xuerenlin** [comment]
@799189288 你好，看作者意思已经合入了master分支，我pull了master分支，测试其中examples中的hello_world，问题还是存在。你那边下载master分支也一起测试看看？


> @rustbasic great! it works now.
> 
>  2024414-1362.mp4

**Comment by 799189288** [comment]
@xuerenlin  我试了试 patch41 分支还是好的， master 我拉下来 报错 
2024-04-29T15:58:44.806058Z ERROR rust_analyzer::main_loop: FetchWorkspaceError:
rust-analyzer failed to load workspace: Failed to load the project at C:\Users\79918\Desktop\myproject\egui-master\egui\Cargo.toml: Failed to query rust toolchain version at C:\Users\79918\Desktop\myproject\egui-master\egui, is your toolchain setup correctly?: "C:\\Users\\79918\\.cargo\\bin\\cargo.exe" "--version" failed, exit code: 1
stderr:
error: 'cargo.exe' is not installed for the toolchain '1.76.0-x86_64-pc-windows-msvc'.
To install, run `rustup component add  --toolchain {toolchain}cargo`

**Comment by xuerenlin** [comment]
@799189288 
我继续测试了下，在windows下是好的，在ubuntu下有问题，具体情况如下：
https://github.com/emilk/egui/issues/4430
