### ISSUE TITLE
Change position of `Checkbox` label

### ISSUE THREAD

**Issue by vihdzp** [emilk/egui#436]
Currently it seems like there's no way to make a checkbox (or radiobox) whose text precedes its button. This would be a useful layout option, as having labels before controls and text after checkboxes clashes a lot.

**Comment by emilk** [comment]
Are we sure this is the right solution?

> having labels before controls and text after checkboxes clashes a lot

The other solution is to move others labels to be after the control.

The problem with moving them to the right is that it aligns badly:

```
Accept EULA: [ ]
Sign up to newsletter: [ ] 
```

vs 


```
[ ] Accept EULA
[ ] Sign up to newsletter
```

The nicer way to have checkboxes to the right is to align them using a `Grid` (which is already possible):


```
Accept EULA:           [ ]
Sign up to newsletter: [ ] 
```

**Comment by OfficialURL** [comment]
I wasn't aware about `Grid`s. That does seems like a better solution to the problem I had.
