### ISSUE TITLE
scripts/cargo_deny.sh fails to install cargo-deny because of an MSRV error

### ISSUE THREAD

**Issue by dataphract** [emilk/egui#4373]
**Describe the bug**
While running `scripts/cargo_deny.sh`, if `cargo-deny` is not already installed, the step that attempts to install it fails because the latest `cargo-deny` has an MSRV of 1.74, while the `rust-toolchain` file sets the toolchain to 1.72, and this affects `cargo install`.

```
$ cargo install cargo-deny
    Updating crates.io index
  Installing cargo-deny v0.14.21
    Updating crates.io index

error: failed to compile `cargo-deny v0.14.21`, intermediate artifacts can be found at `/tmp/cargo-installv5Hzhx`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  package `clap_builder v4.5.2` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.72.0
  Try re-running cargo install with `--locked`

```

**To Reproduce**
1. Uninstall `cargo-deny` if it is already installed.
2. From the repository root, run `cargo install cargo-deny`.

**Expected behavior**
`cargo-deny` should install without error.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: N/A
 - Version: N/A

**Comment by YgorSouza** [comment]
I tried to fix that in #4293 by adding the `+stable` argument. I'll try to finish that PR and open it up for review.
