### ISSUE TITLE
Update `rustls` to remove RUSTSEC warning

### ISSUE THREAD

**Issue by rustbasic** [emilk/egui#4382]
@emilk 

master version
`Cargo.lock` seems to be causing the problem, is it just me?

After master update, problems occurred in all Pull Requests.

Shouldn't we add Cargo.lock to `.gitignore`?

```
# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
# More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
Cargo.lock
```

BELOW : Pull Request Error

info: default toolchain set to '1.72.0-x86_64-unknown-linux-musl'

  1.72.0-x86_64-unknown-linux-musl installed - rustc 1.72.0 (5680fa18f 2023-08-23)

info: note that the toolchain '1.72.0-x86_64-unknown-linux-musl' is currently in use (overridden by '/github/workspace/rust-toolchain')
error[vulnerability]: `rustls::ConnectionCommon::complete_io` could fall into an infinite loop based on network input
    ┌─ /github/workspace/Cargo.lock:156:1
    │
156 │ rustls 0.21.7 registry+https://github.com/rust-lang/crates.io-index
    │ ------------------------------------------------------------------- security vulnerability detected
    │
    = ID: RUSTSEC-2024-0336
    = Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0336
    = If a `close_notify` alert is received during a handshake, `complete_io`
      does not terminate.

      Callers which do not call `complete_io` are not affected.
      
      `rustls-tokio` and `rustls-ffi` do not call `complete_io`
      and are not affected.

      `rustls::Stream` and `rustls::StreamOwned` types use
      `complete_io` and are affected.
    = Announcement: https://github.com/rustls/rustls/security/advisories/GHSA-6g7w-8wpp-frhj
    = Solution: Upgrade to >=0.23.5 OR >=0.[22](https://github.com/emilk/egui/actions/runs/8757443820/job/24036059287?pr=4374#step:4:23).4, <0.[23](https://github.com/emilk/egui/actions/runs/8757443820/job/24036059287?pr=4374#step:4:24).0 OR >=0.21.11, <0.22.0 (try `cargo update -p rustls`)
    = rustls v0.21.7
      └── ureq v2.8.0
          └── ehttp v0.5.0
              └── egui_extras v0.27.2
                  ├── custom_keypad v0.1.0
                  ├── egui_demo_app v0.27.2
                  ├── egui_demo_lib v0.27.2
                  │   └── egui_demo_app v0.[27](https://github.com/emilk/egui/actions/runs/8757443820/job/24036059287?pr=4374#step:4:28).2 (*)
                  ├── hello_world v0.1.0
                  └── images v0.1.0

advisories FAILED, bans ok, licenses ok, sources ok

**Comment by YgorSouza** [comment]
The guidelines regarding lockfiles have changed. <https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html>

And this error is just saying that the Rust security team published a vulnerability in the rustls crate today. It does not seem to be problematic for egui, but I guess the dependency will be updated in the next PR that gets merged to fix that.
