### ISSUE TITLE
Limit ordered-float to version 2.4

### ISSUE THREAD

**Issue by baysmith** [emilk/egui#439]
ordered-float has released version 2.5 which adds a dependency on getrandom which doesn't compile for wasm32.

Perhaps the ordered-float dependency should specify version 2.4? Or maybe certain feature settings would work?

I have used `cargo update -p ordered-float --precise 2.4.0` as a workaround.

**Comment by emilk** [comment]
Please verify that this was indeed fixed by https://github.com/emilk/egui/pull/440 or I will probably remove `ordered-float` as a dependency
