### ISSUE TITLE
Close Window or Frame

### ISSUE THREAD

**Issue by cyberpunkbln** [emilk/egui#4397]
Hello,

simple question:). How can i close an windows on eFrame::App::update{}? As an example with if btn_quit.clicked() {????};?

thx

**Comment by thmxv** [comment]
Not really experienced enough to be sure. But have you tried using [`Context::send_viewport_cmd()`](https://docs.rs/egui/0.27.2/egui/struct.Context.html#method.send_viewport_cmd) to send a [`ViewportCommand::Close`](https://docs.rs/egui/0.27.2/egui/viewport/enum.ViewportCommand.html) command?

Maybe using the Discussions github tab to ask for help before sending a bug report would also be better for this kind of questions.

**Comment by cyberpunkbln** [comment]
thats is it,thx
