### ISSUE TITLE
Smooth scrolling introduced latency

### ISSUE THREAD

**Issue by emilk** [emilk/egui#4401]
A recent egui release introduced smoothed scrolling (`InputState::smooth_scroll_delta`) which is used by `ScrollArea` and other things.

For mice with discreet scroll steps this is a big win, making scrolling smooth and nice.

For platforms with smooth scroll input (e.g. Mac trackpads) however, it only adds latency for no win.

It would be nice if we could somehow get the best of two worlds, i.e. only apply the smoothing in case the input it sharp/discreet.

**Comment by rustbasic** [comment]
It seems that `unprocessed_scroll_delta` should be stored and processed for each `ScrollArea`.

Currently, `unprocessed_scroll_delta` is stored in one place, `InputState`, so fine processing for each ScrollArea is difficult.
