### ISSUE TITLE
Rendering an <iframe> in egui?

### ISSUE THREAD

**Issue by theSherwood** [emilk/egui#441]
I realize this may be something of a long shot, but would there be any way to render and `<iframe>` within egui? Something like https://pub.dev/packages/webview_flutter ? In any case, I'm following the development of this library with keen interest! Thanks for all your hard work!

**Comment by emilk** [comment]
That is indeed a long shot :) egui is not a browser :P

**Comment by theSherwood** [comment]
Ha. There are some use-cases for webviews outside of full-blown browsers. Flutter and SwiftUI allow for including webviews. I figure I can fake it within egui in the browser (basically, absolutely positioning and clipping an iframe), but I'm not sure how to make it work with a native app. Embedding web content in the app would be a pretty important part of the app I have in mind.

But I understand if it's out of scope!

**Comment by pythoneer** [comment]
https://github.com/webview/webview is a good way to start https://github.com/fltk-rs/fltk-webview uses it to render a webview. Idk how exactly the rendering pipeline for egui is working but if you can deliver a window handle to webview it can render itself into it, but this could be a problem.
