### ISSUE TITLE
Chinese can be entered in the first position of text_editor, but not in other positions

### ISSUE THREAD

**Issue by xuerenlin** [emilk/egui#4430]
**Describe the bug**

Chinese can be entered in the first position of text_editor, but not in other positions

**To Reproduce**
1. git clone eframe_template
2. setup custom fonts:
fn setup_custom_fonts(ctx: &egui::Context) {
    // Start with the default fonts (we will be adding to them rather than replacing them).
    let mut fonts = egui::FontDefinitions::default();

    // Install my own font (maybe supporting non-latin characters).
    // .ttf and .otf files supported.
    fonts.font_data.insert(
        "my_font".to_owned(),
        egui::FontData::from_static(include_bytes!(
            "msyh.ttc"
        )),
    );

    // Put my font first (highest priority) for proportional text:
    fonts
        .families
        .entry(egui::FontFamily::Proportional)
        .or_default()
        .insert(0, "my_font".to_owned());

    // Put my font as last fallback for monospace:
    fonts
        .families
        .entry(egui::FontFamily::Monospace)
        .or_default()
        .push("my_font".to_owned());

    // Tell egui to use these fonts:
    ctx.set_fonts(fonts);
}

4. cargo run 

**Expected behavior**

check this scrennshorts，“你好” can be entered in the first position， but can not entered after "test" 

**Screenshots**

<img width="300" alt="image" src="https://github.com/emilk/egui/assets/168352862/9a9d5dd1-da47-466c-8f41-1afc6ae991b0">

**Desktop (please complete the following information):**
 - OS:  I check windows 11 and unbuntu，has the same behavior.
 - Browser   
 - Version

**Comment by rustbasic** [comment]
Check if it works by applying egui Master Version.

It is expected that there will be no problems with the Master Version,
and it will be corrected in the next egui Version (0.27.3 ?) update.

**Comment by xuerenlin** [comment]
> Check if it works by applying egui Master Version.
> 
> It is expected that there will be no problems with the Master Version, and it will be corrected in the next egui Version (0.27.3 ?) update.
> 
> * Related [i can't input chinese words into singleline properly #4354](https://github.com/emilk/egui/issues/4354)
> * Related [Improve IME support with new `Event::Ime` #4358](https://github.com/emilk/egui/pull/4358)

Thank you for your reply.

I test the master branch examples/hello_world:
**1. In my window 11, it works good !!**
**2. But I test in ubuntu, the problem has not been resolved.**

I modify crates/egui/src/widgets/text_edit/builder.rs like this, and it works.

                ImeEvent::Commit(prediction) => {
                    println!("ImeEvent::Commit( {}", prediction);
                    if prediction == "\n" || prediction == "\r" {
                        None
                    } else {
                        state.ime_enabled = false;

                        if !prediction.is_empty()
                        //&& cursor_range.secondary.ccursor.index
                        //    == state.ime_cursor_range.secondary.ccursor.index
                        {
                            println!(
                                "cursor_range.secondary.ccursor.index:{}",
                                cursor_range.secondary.ccursor.index
                            );
                            println!(
                                "state.ime_cursor_range.secondary.ccursor.index:{}",
                                state.ime_cursor_range.secondary.ccursor.index
                            );

                            let mut ccursor = text.delete_selected(&cursor_range);
                            text.insert_text_at(&mut ccursor, prediction, char_limit);
                            Some(CCursorRange::one(ccursor))
                        } else {
                            let ccursor = cursor_range.primary.ccursor;
                            Some(CCursorRange::one(ccursor))
                        }
                    }
                }

Then run this test, got the print below:

    ImeEvent::Commit( 中国
    cursor_range.secondary.ccursor.index:6
    **state.ime_cursor_range.secondary.ccursor.index:0**
    ImeEvent::Commit( 你好
    cursor_range.secondary.ccursor.index:8
    **state.ime_cursor_range.secondary.ccursor.index:0**

But I don't know why state.ime_cursor_range.secondary.ccursor.index is allway 0

**Comment by rustbasic** [comment]
@xuerenlin 

Please check if the following Pull Request has a problem in Ubuntu. If not, check if there is a problem in Windows as well and let us know the results.

* #4436

**Comment by xuerenlin** [comment]
@rustbasic 

I test #4436 in Ubuntu. 
The first time I entered "你好", it was not displayed in the text_edit box.
When I enter "你好" again, it's normal. Then every input is normal.
It looks like it's the first time that the control status is abnormal.

In text_edit/builder.rs  **fn events()**

The First enter，get bellow ImeEvent:
  ImeEvent::Commit: prediction=你好
  ImeEvent::Disabled

The Second enter，get bellow ImeEvent:
  ImeEvent::Enabled
  ImeEvent::Commit: prediction=你好
  ImeEvent::Disabled

**The First enter, do not trigger ImeEvent::Enabled event.**

**Comment by xuerenlin** [comment]
@rustbasic

Test in Windows it works good，In text_edit/builder.rs **fn events()** 
Every input get bellow ImeEvent:
```
  ImeEvent::Enabled
  ImeEvent::Enabled
  ImeEvent::Commit prediction=你好
  ImeEvent::Disabled
  ImeEvent::Disabled
```

The above tests used SougoPinyin（a popular IME in China）.


Then I use MicrosoftPinyin(Windows default chinese IME) Test，get bellow ImeEvent:
```
  ImeEvent::Enabled
  ImeEvent::Preedit text_mark=n
  ImeEvent::Preedit text_mark=ni
  ImeEvent::Preedit text_mark=ni'h
  ImeEvent::Preedit text_mark=ni'ha
  ImeEvent::Preedit text_mark=ni'hao
  ImeEvent::Enabled
  ImeEvent::Commit prediction=你好
  ImeEvent::Disabled
  ImeEvent::Disabled
```

**This result may be due to SougoPinyin not following the IME rules well?**
**And In Ubuntu system, I test GooglePinyin again, it has the same problem like SougoPinyin.**

**Comment by rustbasic** [comment]
@xuerenlin 

Please print the `winit::event::Ime::` event details at the following location and let us know.
I'll check tomorrow.                                                                  
                                                                                      
crates/egui-winit/src/lib.rs                                                          
330 line                                                                              
            WindowEvent::Ime(ime) => {

**Comment by rustbasic** [comment]
Because it is difficult to apply to all languages, there are no exact rules.
However, it is true that `SougoPinyin` has a unique behavior.

**Comment by rustbasic** [comment]
This is the problem

When app run, print:
ime event is: Enabled

**Comment by rustbasic** [comment]
@xuerenlin 

Since this is a problem with `SougoPinyin`, I think you should do something like this:
Please check if it is possible as follows.

1. Apply #4436.

2. Call `send_ime_disable()` in `egui-winit/src/lib.rs` only once when the program starts. 
(Alternatively, it is expected to operate normally even if you call `send_ime_disable()` every time before inputting.)

**Comment by rustbasic** [comment]
@xuerenlin

Please check if it is possible as follows.
let me know result, please.

1. Apply new #4436.

2. Call `ime_event_disable()` in `egui-winit/src/lib.rs` only once when the program starts.
(Alternatively, it is expected to operate normally even if you call `send_ime_disable()` every time before inputting.)

OR

2. Find a way to prevent `winit::event::Ime::Enabled` from occurring when the program starts.

**Comment by xuerenlin** [comment]
@rustbasic 
I call ime_event_disable() once time, and it works.
Here is my test code:
![image](https://github.com/emilk/egui/assets/168352862/edf0f6c8-ee8b-4a26-8172-88dc56872f90)

**Comment by rustbasic** [comment]
@xuerenlin 
 
Is it okay to call `ime_event_disable()` from your program without changing `egui-winit/src/lib.rs`?

Or is there anything I need to change in `egui-winit/src/lib.rs` to use `ime_event_disable()`?

**Comment by xuerenlin** [comment]
@rustbasic 

Yes, I change egui-winit/src/lib.rs,  add call ime_event_disable() as follows:
```
                match ime {
                    winit::event::Ime::Enabled | winit::event::Ime::Preedit(_, None) => {
                        self.ime_event_enable();
                    }
                    winit::event::Ime::Preedit(text, Some(_cursor)) => {
                        self.ime_event_enable();
                        self.egui_input
                            .events
                            .push(egui::Event::Ime(egui::ImeEvent::Preedit(text.clone())));
                    }
                    winit::event::Ime::Commit(text) => {
                        self.egui_input
                            .events
                            .push(egui::Event::Ime(egui::ImeEvent::Commit(text.clone())));
                        self.ime_event_disable();
                    }
                    winit::event::Ime::Disabled => {
                        self.ime_event_disable();
                    }
                };
                ///////////////////////////////////////////////////////////////
                //following is my test code:
                static DISABLE_IME_ENABLE_AT_START: OnceLock<i32> = OnceLock::new();
                DISABLE_IME_ENABLE_AT_START.get_or_init(|| {
                    self.ime_event_disable();
                    println!("ime_event_disable");
                    return 0;
                });
```

You need to consider the specific solution. I'm just testing whether calling ime_event_disable() once when the program starts  can solve the problem.

**Comment by rustbasic** [comment]
@xuerenlin 

Do not modify `egui-winit/src/lib.rs`,
Make sure your program can call `ime_event_disable()`.

Let's work together to get it in a usable condition.
Ultimately, approval from 'emilk' is required.

**Comment by xuerenlin** [comment]
@rustbasic 
Sorry, I have just been using egui for a few days and I am still not familiar with it. So I don't understand how to call ime_event_disable() in my program. 
Is something can do in raw_input_hook() function ?

**Comment by rustbasic** [comment]
@xuerenlin 

Again,
Please check if the following Pull Request has a problem in Ubuntu and Windows. let us know the results.

* #4436

**Comment by xuerenlin** [comment]
@rustbasic 
I tested the following scenarios and all of them worked properly !
1. Windows + MicrosoftPinyin
2. Windows + SougouPinyin
3. Ubuntu + MicrosoftPinyin
4. Ubuntu + GooglePinyin

**Comment by rustbasic** [comment]
@emilk @xuerenlin 

I expect this to work, and we've been told it will work, so we hope this gets approved.

* #4436

**Comment by konceptosociala** [comment]
The same issue with Russian/Ukrainian/Esperanto keyboard (all non-ASCII, maybe)
The first character is printed, other do not print (but Ctrl-C + Ctrl-V some text with these characters works)

**Prerequisites:**
OS: Ubuntu 24.04.2
egui/eframe: 0.32.1

**Minimal example**
```rust
use eframe::egui;

fn main() {
    let native_options = eframe::NativeOptions::default();
    let _ = eframe::run_native("My egui App", native_options, Box::new(|cc| Ok(Box::new(MyEguiApp::new(cc)))));
}

#[derive(Default)]
struct MyEguiApp { buffer: String }

impl MyEguiApp {
    fn new(_cc: &eframe::CreationContext<'_>) -> Self { Self::default() }
}

impl eframe::App for MyEguiApp {
   fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
       egui::CentralPanel::default().show(ctx, |ui| {
           ui.text_edit_multiline(&mut self.buffer);
       });
   }
}
```

**Steps to reproduce:**
Print any russian/esperanto character in the text edit
