### ISSUE TITLE
Pan Zoom and Strip Demo overlap bug

### ISSUE THREAD

**Issue by markusdd** [emilk/egui#4448]
Hi, I have not dug deeper into this, in case this is a known bug feel free to close:

![grafik](https://github.com/emilk/egui/assets/25175069/529e39c6-a674-44c8-9216-5fb3a5cf60d7)

In the current official demo there is this very visible overlap bug. (might be the coding of the Demo or a framework issue, idk).

happens in briught+dark mode, tried it in latest Firefox and Edge, same behavior.

**Comment by YgorSouza** [comment]
This was reported before in #4128.

**Comment by markusdd** [comment]
thx
