### ISSUE TITLE
Missing example with image.

### ISSUE THREAD

**Issue by Kesanov** [emilk/egui#447]
The documentation should show a self-contained example on how to draw an image. 

It is not clear how to convert URL or filepath like `./this/is/my/image.png` into TextureID.

**Comment by parasyte** [comment]
You have to create a texture with the backend/graphics stack you are using. Here's a function that can load a png image with `egui_glium`. This was tested by modifying the ["pure" example](https://github.com/emilk/egui/blob/master/egui_glium/examples/pure.rs).

```rust
fn upload_png<P: AsRef<Path>>(
    egui: &mut egui_glium::EguiGlium,
    path: P,
) -> anyhow::Result<(egui::TextureId, emath::Vec2)> {
    // Read and decode the image.
    let decoder = png::Decoder::new(std::fs::File::open(path)?);
    let (info, mut reader) = decoder.read_info()?;
    let mut buf = vec![0; info.buffer_size()];
    reader.next_frame(&mut buf).unwrap();

    // Convert the data to an array of epaint colors.
    let mut pixels = Vec::with_capacity(info.buffer_size() / 4);
    for rgba in buf.chunks_exact(4) {
        match rgba {
            &[r, g, b, a] => pixels.push(Color32::from_rgba_unmultiplied(r, g, b, a)),
            _ => (),
        }
    }

    // Create a new texture and upload the pixels to it.
    let (_, painter) = egui.ctx_and_painter_mut();
    let id = painter.alloc_user_texture();
    painter.set_user_texture(id, (info.width as usize, info.height as usize), &pixels);

    let size = emath::Vec2::new(info.width as f32, info.height as f32);
    Ok((id, size))
}
```

Upload the texture after creating the `EguiGlium` instance. You only have to do this once.

```rust
let (image_id, image_size) = upload_png(&mut egui, "./this/is/my/image.png")?;
```

Then draw your `image_id` as part of the rest of the GUI.

```rust
egui::CentralPanel::default().show(egui.ctx(), |ui| {
    ui.image(image_id, image_size);
});
```

Doing this with `egui_web` is similar, but you will have to jump through hoops to get the image data and upload it as a WebGL texture. It would be nice to see the backend-specific stuff abstracted away a bit.

**Comment by emilk** [comment]
> Doing this with `egui_web` is similar, but you will have to jump through hoops to get the image data and upload it as a WebGL texture. It would be nice to see the backend-specific stuff abstracted away a bit.

There already is an abstraction for this: https://docs.rs/epi/0.12.0/epi/struct.Frame.html#method.tex_allocator

**Comment by Kesanov** [comment]
Seems like a lot of work, for something so basic. Additionally:
- Why does `TexAllocator` have a `free` method, when rust doesn't use manual memory management?
- Does each scaling of an image require new allocation?
- Does Egui support background images?

**Comment by parasyte** [comment]
Here is what I know:

- `TexAllocator` is just a collection, like `Vec<T>` or `HashMap<K, V>`. It owns all textures that are allocated with it. The only way to free an item from a collection is to call a method on it like `Vec::remove(i)` or `HashMap::remove(k)`. Think of `TextAllocator::free(id)` as analogous.
- No, you can use a single texture and scale it with whatever scaling methods are provided by the backend, including filtering modes and mipmapping.
    - Depends entirely on what is supported by the backend. If you need mip levels and your backend doesn't currently support it, submit a PR!
- To my knowledge, the current state of layering within egui widgets is limited to windows (which can overlap), drop-down menus, and context menus (WIP).
    - You will very likely have to do rect allocations for your widgets "by hand" instead of letting the `Ui` do layout for you automatically so you can layer widgets on top of one another. Similar to this answer: https://github.com/emilk/egui/discussions/469#discussioncomment-836880 E.g. putting an image background on a button would require first allocating space for the button, then drawing the image with the right clipping shape, followed by drawing the button on top of it with a transparent fill color.

**Comment by Kesanov** [comment]
> No, you can use a single texture and scale it with whatever scaling methods are provided by the backend, including filtering modes and mipmapping.
Can you share an example of how can you rescale texture, without calling `free` and `alloc`?

**Comment by Kesanov** [comment]
Also, it isn't possible to allocate texture in `App::load`, as you don't have access to `Frame`.

**Comment by emilk** [comment]
> Also, it isn't possible to allocate texture in `App::setup`, as you don't have access to `Frame`.

[Yes you do](https://docs.rs/epi/0.14.0/epi/trait.App.html#method.setup)

**Comment by emilk** [comment]
There is a demo of how to load and show an image at https://github.com/emilk/egui/blob/master/eframe/examples/image.rs

**Comment by emilk** [comment]
@omarandlorraine I fixed the link; thanks for noticing
