### ISSUE TITLE
Error: WinitEventLoop(NotSupported(NotSupportedError))

### ISSUE THREAD

**Issue by kengknyaz** [emilk/egui#4472]
I have tried to compile and run any of the code examples in examples/ directory but after compiling at the time of running I get this error:
Error: WinitEventLoop(NotSupported(NotSupportedError))

cargo --version
cargo 1.77.2 (e52e36006 2024-03-26)

rustc --version
rustc 1.77.2 (25ef9e3d8 2024-04-09)

**Comment by eloraiby** [comment]
I have the same issue after switching from wayland to x11 on ubuntu 22.04. This doesn't happen on kubuntu 22.04 (x11).

**Comment by eloraiby** [comment]
If you are using ubuntu, it seems to be missing the `DISPLAY` env variable. First you need to figure out which display is your server using.

```
$ ls /tmp/.X11-unix
/X1
```
in my case, it is `X1` so the display is 1. if you see `X0` then it's 0.

The following should fix it:
```
export DISPLAY=:1
```
or
```
export DISPLAY=:0
```
and then it'll run.
