### ISSUE TITLE
`Style` feature to have label truncate by default

### ISSUE THREAD

**Issue by abey79** [emilk/egui#4473]
In some context, it would be useful to have `ui.label(txt)` defaults to truncate, such as we don't have to change them all for `ui.add(egui::Label::new(txt).truncate(true))`. Likewise, it would be nice to have a `ui.label_truncated()` helper (though each might be suited for different situations).

As per:
- https://github.com/rerun-io/rerun/issues/4161#issuecomment-2089947539

**Comment by rustbasic** [comment]
Please also refer to #3900 and #4045 when working.

* Related 3900
* Related 4045

**Comment by emilk** [comment]
Would `ui.style().truncate = Some(true);` solve most of the problems @abey79, or do you still want `label_trunc` and `label_wrap`?

**Comment by abey79** [comment]
I think `ui.style().truncate = Some(true);` would actually solve this more elegantly than dedicated `ui.label_trunc`. It's also more in-line with the bigger CSS-like styling story.
