### ISSUE TITLE
How to avoid the CMD window pop up when running on Windows?

### ISSUE THREAD

**Issue by qq253498229** [emilk/egui#4477]
I'm beginner to EGui and I'm trying to build my first application and run it on Windows operating system.
I noticed that it also opens a CMD window. 
I'm not sure how to avoid this. 
I want my application to run without any side effects.

Also, is there any documentation for EGui other than examples or demos?

**Comment by YgorSouza** [comment]
Add this line that is in all the examples:

https://github.com/emilk/egui/blob/ded8dbd45bc8616475c364878f6b8e2f7293d12c/examples/hello_world/src/main.rs#L1

All crates have documentation on docs.rs, also linked from the crate page on crates.io. Here is the one for egui:

https://docs.rs/egui/0.27.2/egui/

**Comment by qq253498229** [comment]
@YgorSouza 

I might not have described my idea clearly. 

I need a documentation website similar to https://ng.ant.design/docs/introduce/en, so I can easily find how to get started, locate the components I need, and understand the detailed configurations of each component. 

Currently, on docs.rs, I don't even know how to run my first application.
