### ISSUE TITLE
How to get the current settings of a window

### ISSUE THREAD

**Issue by Tilix4** [emilk/egui#45]
I cannot find a way to access the x, y, width and height of a window. I derived my `Node` struct from `Window` and I'd like to be able to put things inside relatively to these current parameters.

(sorry I'm a bit learning rust with this project, then it might be a dumb question)

**Comment by emilk** [comment]
If you want the inner size of the Window you can use the `Ui` it wraps and call `ui.min_rect()`: https://docs.rs/egui/0.3.0/egui/struct.Ui.html#sizes-etc

If you want the outer size, then `Window::show` returns an optional `Response`:

``` rust
let response = egui::Window::new("my window").show(ctx, |ui|{
    // ..add a bunch of widgets to ui
    let inner_rect = ui.min_rect();
});
if let Some(response) = response {
    let outer_rect = response.rect;
} else {
    // window was closed (will only happen if you use [`open`](https://docs.rs/egui/0.3.0/egui/containers/struct.Window.html#method.open))
}
```

I hope that helps!

If you have more questions, there is an Egui discord channel at https://discord.gg/vY8ZGS292W

**Comment by Tilix4** [comment]
Yes, I think it's what I was looking for. I have to get used to the whole concept. Thank you!
