### ISSUE TITLE
Phantom key presses when focusing an egui/winit window

### ISSUE THREAD

**Issue by hut** [emilk/egui#4513]
Currently, when running egui in X11 on Linux with the winit backend, phantom key presses are registered when the window gains focus. Examples:

1. If you press Alt+TAB to select the window, a key press of "TAB" is erroneously registered.
2. My window manager has the key binding Alt+w to change workspaces. Assuming the egui window has a text box selected, if I change the workspace to the one with the egui window with the key binding Alt+w, it will erroneously type a "w" into the text box.

In either example, I would expect no key to be registered. After all, no other (non-broken) application will register/type keys simply by changing focus into the application window.

This error happens because winit [sends "fake" KeyboardInput events with a field "is_synthetic"](https://docs.rs/winit/latest/winit/event/enum.WindowEvent.html#variant.KeyboardInput) when the window focus is gained. Key presses with "`is_synthetic == true`" should [not be interpreted as real key presses and should be filtered out, according to the maintainers of winit.](https://github.com/rust-windowing/winit/issues/3691#issuecomment-2102561152)

egui currently does not do special handling of KeyboardInput events with "is_synthetic == true", see https://github.com/emilk/egui/blob/8321f64f6e68c5b8a433517e535e22087573f8a4/crates/egui-winit/src/lib.rs#L371

The proper handling would be to discard the event if "`keyboardinput.event.state == ElementState::Pressed && keyboardinput.is_synthetic`" is true.

See also:

- Relevant winit bug report: https://github.com/rust-windowing/winit/issues/3691
- Relevant winit discussion: https://github.com/rust-windowing/winit/issues/3543
- An analogous fix in another UI framework: https://github.com/lapce/floem/pull/387
    - They discard all events with "`is_synthetic == true`", which is another way to handle this.

Thanks for looking into this. It probably causes a lot of confusion/frustration for X11 users that heavily customize their window manager key bindings.

**Comment by emilk** [comment]
Sounds like an easy fix then! Wanna make a PR?

**Comment by hut** [comment]
Sure, will do.

**Comment by hut** [comment]
Thanks so much for resolving this.

It's such a subtle bug, but so annoying. I'm using a tiling window manager with lots of alt+letter keys for focus switching, and all those unintended key presses are driving me crazy. Very relieved, thanks. <3
