### ISSUE TITLE
Configurable plot cursor "snap" radius

### ISSUE THREAD

**Issue by bellwether-softworks** [emilk/egui#4519]
First, apologies if this has been asked already; I looked but didn't managed to identify an existing issue to track this need.

When viewing the plot, the cursor often jumps a considerable distance to snap to the nearest available point.  Being able to modify this distance (including disabling it altogether, perhaps by zeroing it out) would be helpful for some scenarios where hovering near a point is important.

Currently, the radius appears to be [hard-coded](https://github.com/emilk/egui/blob/8321f64f6e68c5b8a433517e535e22087573f8a4/crates/egui_plot/src/lib.rs#L1669); I'd request a property at the struct level to override.

**Comment by haricot** [comment]
If you don't want any information about the specified item, you can use for example:
`plot_ui.line(line.name("Line with fill")).allow_hover(false)`  

Otherwise @YgorSouza PR might well come in handy.
