### ISSUE TITLE
Multiple issues with font texture.

### ISSUE THREAD

**Issue by nikitablack** [emilk/egui#454]
Hello. I believe there're problems with font rendering, partly because of the texture.

1. [srgba_pixels](https://docs.rs/egui/0.12.0/egui/struct.Texture.html#method.srgba_pixels) says:
   >  Returns the textures as sRGBA premultiplied pixels, row by row, top to bottom.
   
I looked at the data returned by calling `texture.srgba_pixels()` and found lots of strange values, for example `Color32([131, 131, 131, 58])`. Notice how components are greater than the alpha, which is not possible if the color is premultiplied by that alpha.

2. Font rendering looks wrong in the demo app - a bright outline appears around glyphs. This can be clearly seen if make a background color bright and font color other than white:
![egui](https://user-images.githubusercontent.com/6390092/120618087-0206cc00-c45b-11eb-9b5c-9b46d05ce9d6.png)
I don't know how it rendered in a web demo, but looking at the [egui_wgpu_backend](https://github.com/hasenbanck/egui_wgpu_backend/blob/master/src/shader/egui.frag) source code I see how that happened - the color from the _bad_ texture is multiplied with the vertex color and after the blending, the resulting color becomes brighter.

3. I saw the recommendation to use the `LINEAR` filtering mode. But I believe this can't work - when rendering a non-font UI (a button body/border, for example) the out fragment color should be equal to the vertex color. And since there's a multiplication in a fragment shader with a result of a texture sampling, the former should be equal to `[1, 1, 1, 1]`. True, the `uv` for these vertices are `[0, 0]` and the top-left pixel of the texture is fully opaque white. But with the `LINEAR` filtering that value will be mixed with the adjacent pixels. Indeed, in RenderDoc I see the value `[0.25, 0.25, 0.25, 0.25]` for the sampled `[0, 0]` uv coords.

This is the image I get when I _"fixed"_ the listed issues:
![egui2](https://user-images.githubusercontent.com/6390092/120620676-7e021380-c45d-11eb-9ade-0e38d92ed5b4.png)

**Comment by emilk** [comment]
1. 
> I looked at the data returned by calling `texture.srgba_pixels()` and found lots of strange values, for example `Color32([131, 131, 131, 58])`. Notice how components are greater than the alpha, which is not possible if the color is premultiplied by that alpha.

That is expected - the RGB values are gamma encoded but the alpha is linear. The premultiplication is done in linear-space.

So `131` decodes to `((131 + 14.025) / 269.025) ^ 2.4` ≈ `0.227` and `58` decodes to `58 / 255` ≈ `0.227`. So it is correct

2. 
> Font rendering looks wrong in the demo app - a bright outline appears around glyphs. This can be clearly seen if make a background color bright and font color other than white:

This looks good in `egui_glium` on my machine:

![Screen Shot 2021-06-03 at 17 43 00](https://user-images.githubusercontent.com/1148717/120673128-3302f300-c493-11eb-86e7-f95b54f64f06.png)

> looking at the `egui_wgpu_backend` source code I see how that happened - the color from the bad texture is multiplied with the vertex color and after the blending, the resulting color becomes brighter.

Sounds like an issue you should file in https://github.com/hasenbanck/egui_wgpu_backend and not here

3.

> True, the uv for these vertices are [0, 0] and the top-left pixel of the texture is fully opaque white. But with the LINEAR filtering that value will be mixed with the adjacent pixels.

Not if you use [clamping sampling](https://github.com/emilk/egui#my-windows-are-too-transparent-or-too-dark)

**Comment by parasyte** [comment]
I see good results with `egui_glium` but bad results with `egui_web`.

![egui_web-fonts](https://user-images.githubusercontent.com/456942/120684520-a38a1f80-c453-11eb-9aa6-57de56a66c94.png)

**Comment by emilk** [comment]
The blending on egui_web is broken because WebGL doesn't support linear alpha blending, which is a shame. It may be possible to get alpha blending with render-to-texture, but I haven't investigated that yet.

**Comment by nikitablack** [comment]
> The blending on egui_web is broken because WebGL doesn't support linear alpha blending, which is a shame. It may be possible to get alpha blending with render-to-texture, but I haven't investigated that yet.

What do you mean under the `linear alpha blending`? This is the first I see this term.

**Comment by emilk** [comment]
> The blending on egui_web is broken because WebGL doesn't support linear alpha blending, which is a shame. It may be possible to get alpha blending with render-to-texture, but I haven't investigated that yet.

Writing this comment actually got me thinking about the problem again for the N:th time, and this time [I found a solution!](https://github.com/emilk/egui/commit/effd3c7440d9f70c0eff677871a60be539cf1113). Starting with the next release, text will look much nicer in egui_web, especially in light mode. Yay!

**Comment by emilk** [comment]
> What do you mean under the `linear alpha blending`? This is the first I see this term.

I mean that alpha blending is done in linear space instead of gamma space. See e.g. https://www.realtimerendering.com/blog/tag/srgb/

**Comment by emilk** [comment]
@nikitablack where is image 2 from? `egui_web` or `
egui_wgpu_backend` ?

**Comment by nikitablack** [comment]
> @nikitablack where is image 2 from? `egui_web` or ` egui_wgpu_backend` ?

1st Image is a screenshot of the web demo.
2nd image is my Vulkan application.

**Comment by parasyte** [comment]
`egui_wgpu_backend` doesn't have this problem. Check with the example app that uses `egui_demo_lib`: https://github.com/hasenbanck/egui_example

![egui-wgpu](https://user-images.githubusercontent.com/456942/120885002-5b761480-c59b-11eb-883d-7c4c1ec79ee7.png)
