### ISSUE TITLE
Getting the size of a widget without adding it to the UI

### ISSUE THREAD

**Issue by edko99** [emilk/egui#460]
In some cases, I would like to skip drawing a widget but consume its space anyways, but I haven't found a way to determine the size of the widget without adding it to the UI first.

Looking at the way widgets are implemented, since the calculation of the size and its allocation are in the same function that paints it, I imagine the solution would involve somehow temporarily hacking the Ui object to ignore any painting, and recovering the allocated space once the size is determined. Is there a way of doing this?

**Comment by emilk** [comment]
There is no way to get the size of a widget without adding it to a `Ui`, but I added a `ui.set_visible(false);` to make further widgets invisible yet still allocate the space they take up.
