### ISSUE TITLE
Make some widgets modules public so it is easier to create custom widgets

### ISSUE THREAD

**Issue by khanghugo** [emilk/egui#4609]
I want to make a crossover between SelectableLabel and ImageButton. Basically borderless ImageButton. But right now, `image` module in `widgets` is not public. That means simply copy pasting all of the codes making up ImageButton would not just work and require some changes in egui. 

It is totally possible on my side to have my own modified egui but I just think it is nicer if this is upstream.

![image](https://github.com/emilk/egui/assets/29143195/0486194e-8243-4066-920b-1804d9475ca7)

**Comment by YgorSouza** [comment]
See #4181 for discussion.

But for that, you can probably just use [ImageButton::frame](https://docs.rs/egui/0.27.2/egui/widgets/struct.ImageButton.html#method.frame).

**Comment by khanghugo** [comment]
Oh nice. Thanks.
