### ISSUE TITLE
Why layouts dont stack

### ISSUE THREAD

**Issue by suprohub** [emilk/egui#4624]
![image](https://github.com/emilk/egui/assets/125716028/e4e3cd1f-8f9c-445d-9b62-6351af9ba910)
![image](https://github.com/emilk/egui/assets/125716028/738c12b5-ae13-4383-ada1-39802dd72e16)
I want these widgets to be in the center

**Comment by suprohub** [comment]
and i want these widgets to be expanded

**Comment by suprohub** [comment]
anyone help?

**Comment by suprohub** [comment]
horizontal centered breaks everything

**Comment by suprohub** [comment]
![image](https://github.com/emilk/egui/assets/125716028/e95a3d78-30ad-4d46-8254-fe03886c1d6d)
![image](https://github.com/emilk/egui/assets/125716028/6ca6002c-043d-4a71-a094-61c77f0b240b)

**Comment by suprohub** [comment]
![image](https://github.com/emilk/egui/assets/125716028/9962157d-aa07-4148-a584-cd5175b85335)
![image](https://github.com/emilk/egui/assets/125716028/233f6738-d393-446b-a278-8c98e403c9a6)

**Comment by emilk** [comment]
This is because of shortcomings inherent in immediate mode: https://github.com/emilk/egui?tab=readme-ov-file#disadvantages-of-immediate-mode
 
That said, there is some work towards making this better. You can track that here: https://github.com/emilk/egui/issues/4378

**Comment by suprohub** [comment]
> This is because of shortcomings inherent in immediate mode: https://github.com/emilk/egui?tab=readme-ov-file#disadvantages-of-immediate-mode
> 
> That said, there is some work towards making this better. You can track that here: #4378
Ok and how a i can made "horizontal centered" now not breaking all ui?

**Comment by suprohub** [comment]
> This is because of shortcomings inherent in immediate mode: https://github.com/emilk/egui?tab=readme-ov-file#disadvantages-of-immediate-mode
> 
> That said, there is some work towards making this better. You can track that here: #4378

Ok and how a i can made "horizontal centered" now not breaking all ui?
