### ISSUE TITLE
eframe: Switch to winit `ApplicationManager` api

### ISSUE THREAD

**Issue by expenses** [emilk/egui#4709]
The next version of winit will remove the `run` APIs: https://github.com/rust-windowing/winit/pull/3683. This pretty extensively breaks code like https://github.com/emilk/egui/blob/93d458bb68a5c6e1fd05cbebfd64701463e7ab61/crates/eframe/src/native/run.rs#L73-L208. I'm not sure how much effort it will be to fix, but it might make sense to do that sooner-rather-than-later.

**Comment by emilk** [comment]
* Blocked by https://github.com/emilk/egui/issues/4437
