### ISSUE TITLE
TextEdit loses focus as soon as the cursor moves away (web only)

### ISSUE THREAD

**Issue by lucasmerlin** [emilk/egui#4743]
**Describe the bug**

The textedit loses focus as soon as the cursor stops hovering it. This is observable on https://egui.rs: 

https://github.com/emilk/egui/assets/8009393/28f69e14-734d-4108-afd0-0300c7cff8b0

Interestingly the textedit regains focus even when we hover a different textedit.

This makes using the mobile keyboard impossible, only showing the ime for a split-second. 

This only happens when building egui for wasm, running the example natively I didn't experience this.

**To Reproduce**
Try using the textedit on egui.rs

**Expected behavior**
The textedit should stay focused no matter where the cursor is moved.

**Desktop (please complete the following information):**
 Current chrome on macos

**Comment by YgorSouza** [comment]
Confirmed that the same happens on Firefox on Linux (and does not happen on native Linux).

**Comment by emilk** [comment]
Thanks for reporting this!
