### ISSUE TITLE
`WebRunner::start` should accept canvas object

### ISSUE THREAD

**Issue by jprochazk** [emilk/egui#4746]
It would be nice if it was possible to initialize `eframe` on web without giving the canvas an `id` and appending it to the DOM. It should be possible if the `WebRunner::start` accepted an `HTMLCanvasElement`, and passed it along directly:

https://github.com/emilk/egui/blob/d2717180656d640e606a46932718dbef59fd5ef7/crates/eframe/src/web/web_runner.rs#L58-L63

Right now for apps using `eframe` with multiple canvases on the same page, each one needs to be given a unique ID. The painter already holds onto the canvas element directly rather than its ID, so this feels like an obvious and easy change.

**Comment by emilk** [comment]
Context: https://github.com/rerun-io/rerun/pull/6680#discussion_r1659408887
