### ISSUE TITLE
touchend listener on document prevents listening for clicks on dom elements (web)

### ISSUE THREAD

**Issue by lucasmerlin** [emilk/egui#4752]
**Describe the bug**
Egui is registering a `touchend` event listener on the document and is calling preventdefault on the event. This prevents any touch interactions with dom elements shown on top of the canvas.

**To Reproduce**

Paste the following in the console on egui.rs (to create a simple html dialog):

```js
let dialog = document.createElement("dialog");
let button = document.createElement("button");
button.innerHTML = "Hello";
dialog.appendChild(button);
button.onclick = () => alert("button click!!");
document.body.appendChild(dialog);
dialog.show()
```
Clicking the button now does nothing. (Make sure you enabled the device toolbar and set it to e.g. iPhone SE)

If we forcefully remove the egui touchend listener from document via
```js
document.removeEventListener("touchend", getEventListeners(document).touchend[0].listener)
```
the button will become clickable.

**Expected behavior**
Egui shouldn't interfere with other dom elements. Maybe the touchend listener doesn't need preventDefault or it could be made configurable.

**Additional context**

The listener is added here: https://github.com/emilk/egui/blob/af404fec635ddd6390e2caeb3313cb9003b54835/crates/eframe/src/web/events.rs#L92

* Related issue: https://github.com/emilk/egui/issues/3157

**Comment by emilk** [comment]
This should only be a problem if the button overlaps the canvas, due to 

https://github.com/emilk/egui/blob/770c82a3f38d5910d5ab9ce616b38e7cbb1361ae/crates/eframe/src/web/events.rs#L529-L532

https://github.com/emilk/egui/blob/770c82a3f38d5910d5ab9ce616b38e7cbb1361ae/crates/eframe/src/web/events.rs#L425-L427

**Comment by lucasmerlin** [comment]
@emilk Makes sense! I'll try to implement this
