### ISSUE TITLE
egui-wgpu is at 0.27.2 on both Github trunk and crates.io, but they are different.

### ISSUE THREAD

**Issue by John-Nagle** [emilk/egui#4753]
Both Github trunk and crates.io show egui-wgpu at version 0.27.2. 

Github trunk is using wgpu 0.20.0, but crates.io is using wgpu 0.19.1

There were some problems with wgpu 0.20.0 vs. egui, as I recall, and wgpu is now up to 0.20.1 on crates.io. 

Are things just out of sync, or stuck on a bug in a dependency? Thanks.

_Originally posted by @John-Nagle in https://github.com/emilk/egui/discussions/4736_

**Comment by emilk** [comment]
The egui version in egui trunk is always the version of the last published crate. This is so that users can easily patch their egui crates to trunk if they want to. I added a clarification in fcec84ca744db61e42ec568c2443f5e53e68b3d0 now
