### ISSUE TITLE
egui_plot panic on when using mouse to zoom to rectangle

### ISSUE THREAD

**Issue by FabianLippold** [emilk/egui#4768]
When using the mouse on a plot to zoom to a dragged rectangle this panics:

https://github.com/emilk/egui/blob/47accb0eebcc4771c6a289cb650078761bd9cf07/crates/egui_plot/src/lib.rs?plain=1#L1827-L1840

It happens because (min, max) is (f64::max, f64::min)
**notice its the wrong way around** so the assertion fails

**To Reproduce**
1. Draw a plot
2. Drag with the mouse to create a rectangle
3. Let go to zoom to the dragged area
4. kaboom

**Expected behavior**
not crash

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
The commit that broke this is https://github.com/emilk/egui/commit/1036e184404ce65b867b5ebebdfd0519108f6344

When adjusting the clamp_to_finite function to take into account +-inf not just NaN it works, but since I have no clue how infinities end up there I'm not opening a pull request.
```rust
#[inline]
fn clamp_to_finite(&mut self) {
    for d in 0..2 {
        if !self.min[d].is_finite() {
            self.min[d] = 0.0;
        } else {
            self.min[d] = self.min[d].clamp(f64::MIN, f64::MAX);
        }

        if !self.max[d].is_finite() {
            self.max[d] = 0.0;
        } else {
            self.max[d] = self.max[d].clamp(f64::MIN, f64::MAX);
        }
    }
}
```

**Comment by emilk** [comment]
I fail to reproduce on egui.rs

**Comment by FabianLippold** [comment]
Actually this is already fixed by https://github.com/emilk/egui/pull/4741, because this was just 3 days ago my fork was still behind. Sorry 😗
