### ISSUE TITLE
Ctrl + scroll wheel zoom no longer works (v0.28)

### ISSUE THREAD

**Issue by Barugon** [emilk/egui#4777]
**Describe the bug**
`Event::Zoom` is now never sent via `Context::input` for ctrl + scroll wheel.

**To Reproduce**
1. Implement `Context:input` and specifically look for `Event::Zoom`
2. Execute the app, hold the control key and spin the mouse-wheel 
3. Note that `Event::Zoom` is never received

**Desktop (please complete the following information):**
 - OS: Fedora 
 - Version: 40

**Comment by emilk** [comment]
I forgot to add this to the 0.28 migration guide (will fix!) but this is actually expected behavior.

In https://github.com/emilk/egui/pull/4530 I changed the behavior of ctrl-scroll to no longer emit `Zoom` events in the integration. Instead zooming is handled in `egui`:

https://github.com/emilk/egui/blob/8bf498d2bf849892ec0c3fa49fea4c3c504a06fe/crates/egui/src/input_state.rs#L264

As a user, you should use `InputState::smooth_scroll_delta` or `InputState::raw_scroll_delta`.

**Comment by Omustardo** [comment]
It took me a bit of trial and error to figure out how to implement ctrl+scroll zooming even with the pointer to `smooth_scroll_delta` in the prior comment, so here my implementation in case anyone finds it useful.

```
impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        self.handle_mouse_zoom(ctx);

        // your UI code goes here
    }
}

impl MyApp {
    /// Handle zooming in and out using while holding ctrl and scrolling.
    fn handle_mouse_zoom(&mut self, ctx: &egui::Context) {
        let zoom_delta = ctx.input_mut(|input| {
            // `input.smooth_scroll_delta.y` didn't work in my experience and I'm not sure why.
            // Raw seems fine since we only care about it being negative or positive, not the value.
            let scroll_delta = input.raw_scroll_delta.y;
            if input.modifiers.ctrl && scroll_delta != 0.0 {
                // Consume the scroll event to prevent other handlers from using it.
                input.smooth_scroll_delta.y = 0.0;

                // Use steps rather than using scroll delta directly since the units are different.
                const ZOOM_STEP: f32 = 0.1;
                if scroll_delta > 0.0 { ZOOM_STEP } else { -ZOOM_STEP }
            } else {
                0.0
            }
        });
        if zoom_delta != 0.0 {
            let new_zoom_factor = ctx.zoom_factor() + zoom_delta;
            const MIN_ZOOM: f32 = 0.5;
            const MAX_ZOOM: f32 = 3.0;
            ctx.set_zoom_factor(new_zoom_factor.clamp(MIN_ZOOM, MAX_ZOOM));
        }
    }
}
```

I suspect there will be some trickiness for the hard-coded step size that causes it to not work consistently between platforms, but perhaps not. It works for me on Debian 12, and when compiled to wasm and running in Firefox.
