### ISSUE TITLE
Add Embedded File Explorer Into Egui Window

### ISSUE THREAD

**Issue by dorkydanny** [emilk/egui#4801]
**Is your feature request related to a problem? Please describe.**
I find it odd how you have to open a new windows to select a file.

**Describe the solution you'd like**
Have a function such as egui::emedded_fs() that is like a ui.embedded_fs() that returns currently selected path in the fs or returns the path on the user pressing selects. Just not open a new window.

such as
![image](https://github.com/emilk/egui/assets/83188206/06aa54b3-dcd4-4fb0-ba51-dedd3f3dcc39)

**Comment by emilk** [comment]
You can use https://crates.io/crates/egui-file-dialog instead

**Comment by dorkydanny** [comment]
So does this crate have the embedded file explorer or not? Sorry I cannot understand
