### ISSUE TITLE
keyboard input ignored by single line text edit fields on egui 0.28.1

### ISSUE THREAD

**Issue by rustingcode** [emilk/egui#4806]
After updating from egui / eframe 0.27.2 to 0.28.1, I have noticed that egui::TextEdit::singleline input fields will stop ignoring keyboard input after initially working.

This is only happening on native desktop build. WASM build does not have the problem.

To reproduce the problem, hold down the enter key for several seconds on a single line edit field then release the key. Perform this a few times and the field will no longer recognize any further key presses.

Anyone else ran into this? If so, any suggestions on how to resolve it?

**Comment by emilk** [comment]
Holding down enter makes the singleline text edit loose focus, so it is expected that you have to click it again to enter more text.

**Comment by rustingcode** [comment]
Thanks, the issue seems to be related to the application programmatically setting focus on the text field multiple times, then at some point the field stops working entirely (can no longer focus or enter text). Doesn't happen on 0.27.

I'll close this and open a new issue if I can come up with a minimum example to duplicate the problem outside a full application.
