### ISSUE TITLE
panic calling allocate_space on egui 0.28.1

### ISSUE THREAD

**Issue by rustingcode** [emilk/egui#4807]
After updating from egui / eframe 0.27.2 to 0.28.1, calls to the allocate_space() function of egui::Ui panic with the following backtrace:

`
thread 'main' panicked at /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/placer.rs:109:9:
assertion failed: child_size.is_finite() && child_size.x >= 0.0 && child_size.y >= 0.0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
   3: egui::placer::Placer::next_space
             at /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/placer.rs:109:9
   4: egui::ui::Ui::allocate_space_impl
             at /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/ui.rs:1037:26
   5: egui::ui::Ui::allocate_space
             at /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/ui.rs:992:20
 `
The application checks the sizes of UI controls and then uses allocate_space to manually implement a layout that is otherwise not possible.

No issues with this on 0.27.2, but after updating to 0.28.1, the app started crashing due to this issue. Any suggestions would be appreciated.

**Comment by YgorSouza** [comment]
This panic is just telling you that you are trying to allocate negative or non-finite space, which makes no sense. Previously these checks were opt-in, and now they are enabled by default on debug builds.

https://github.com/emilk/egui/commit/f19f99180e6571a780aaa9ce6286e6fd712a4eab#diff-33e10ef5a20311b2d624b96d40ac62139a08d4716fe99059cc574f5c76e6d9dbR109

These assertions are off by default in release. If you want to turn them off in debug as well, you can add this to your Cargo.toml:

```toml
[profile.dev.package.egui]
debug-assertions = false
```

**Comment by emilk** [comment]
I really wish Rust would print debug assertions as "debug assertion failed" instead

**Comment by rustingcode** [comment]
Thank you very much for the information. Somehow my app layout calculations changed after upgrading from 0.27 to 0.28, triggering this panic, so I'll look into that. Thanks.

**Comment by frankvgompel** [comment]
I get something related in debug mode since 0.28.1:
`thread 'main' panicked at /.../.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/placer.rs:143:9:
You cannot advance the cursor when in a grid layout`

I can't find anything obviously wrong in my code related to the grid.
