### ISSUE TITLE
popup reports available_height as zero which seems to break ScrollArea taking up as much vertical space as it needs

### ISSUE THREAD

**Issue by SUPERCILEX** [emilk/egui#4852]
![image](https://github.com/user-attachments/assets/27cbd0e4-f396-42d1-8927-3dc9b65dd17d)

Notice the scrollbar in the popup and the space available below the popup. A separate (but probably related bug) is that once popups have their available_width grow (through window resizing), it does not shrink leading the popup to be cut off when the window width is shrunk again.

This is all I'm doing for the scrollable part:
```rust
      ScrollArea::vertical()
                                .auto_shrink([false, true])
                                .show(ui, |ui| {
                                    ui.label(full);
                                });
```

**Comment by emilk** [comment]
This needs more details, ideally a simple reproduce

**Comment by SUPERCILEX** [comment]
Doesn't reproduce on master anymore, so something fixed it recently. Any idea when the next release will be?
