### ISSUE TITLE
mullvad browser cursor error

### ISSUE THREAD

**Issue by rust-ferrum** [emilk/egui#4858]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by rust-ferrum** [comment]
https://github.com/emilk/egui/issues/4108 
identical problem

**Comment by oscargus** [comment]
Quite hard to do any sort of debugging without more context. Are you sure that whatever you are running in the browser is built with egui 0.27.1 or newer? If it is not, it is most likely fixed.
