### ISSUE TITLE
Allow custom headers for HTTP Request

### ISSUE THREAD

**Issue by trickster** [emilk/egui#487]
https://github.com/emilk/egui/blob/ebb08f87f1adb0b96c6c854bc3a0ed1b7e5cb392/egui_web/src/http.rs#L32

- Create new field in `epi::Request`, which should be passed along with http_fetch

**Comment by skuzins** [comment]
I've been working on a PR for this. 

<https://github.com/emilk/egui/pull/488>

- allow bytes as request body 
- expose request and response headers in API

The core of the changes is switching the `Request::body` field type to `vec<u8>` and adding `Request::headers` and `Response::headers` fields.

The `Response::text` field is replaced by a `text()` helper method and `Response::header_content_type` is replaced by a `content_type()` helper method.

Updated demo app:

<img width="461" alt=" post" src="https://user-images.githubusercontent.com/20017950/121902630-7f50fd00-ccf5-11eb-91e9-4e36221f4fec.png">
