### ISSUE TITLE
mobile/ios textarea focus not working 

### ISSUE THREAD

**Issue by frederik-uni** [emilk/egui#4879]
I cloned the latest version from the eframe template and it failed to focus the textarea. i tried to focus the input field manually with this code
```rs
if resp.clicked(){
#[cfg(target_arch = "wasm32")]
                let document = web_sys::window().unwrap().document().unwrap();
                #[cfg(target_arch = "wasm32")]
                let input = document.query_selector("input").unwrap().unwrap();
                #[cfg(target_arch = "wasm32")]
                let input_element = input.dyn_into::<web_sys::HtmlInputElement>().unwrap();
                #[cfg(target_arch = "wasm32")]
                input_element.focus().unwrap();
```

Which focused the textarea, but the virtual keyboard wasnt opening. I noticed that the egui.rs site does open the keyboard, but only on the second click

**Comment by micmonay** [comment]
Hi

I tried to fix the bug on my applications and I proposed this fix here #4855.
I don't know if it's the best solution, but it gives at least a hint for the final fix.

Best regards
