### ISSUE TITLE
Replace `directories` dependency

### ISSUE THREAD

**Issue by valadaptive** [emilk/egui#4884]
**Describe the bug**

The maintainer of the `directories` crate has [intentionally added an MPL-licensed dependency](https://github.com/dirs-dev/dirs-sys-rs/issues/21) and refuses to remove it. While the MPL isn't technically a viral license, it would still be nice to remove it to avoid any potential legal trouble.

A potential candidate is [etcetera](https://github.com/lunacookies/etcetera), but it appears to have different behavior on macOS with regards to the bundle identifier.

**Comment by YgorSouza** [comment]
I wonder if eframe shouldn't just copy the part of the code it needs from one of these crates. It's just one folder anyway. Might contribute towards #4481.
