### ISSUE TITLE
ui.horizontal ignores layout

### ISSUE THREAD

**Issue by ToasterUwU** [emilk/egui#489]
Hello,

im very new to Rust, so maybe i just misunderstood something.

My problem is that the ui.horizontal method, that I placed within a layout, ignores the layout.
Meaning I got the following code, that results in the following picture:
```rust
egui::CentralPanel::default().show(ctx, |ui| {
  // The central panel the region left after adding TopPanel's and SidePanel's
  let mut buttons: Vec<(String, String)> = vec!();
  for (filename, path) in &self.executables{
      buttons.push((filename.to_string(), path.to_string()));
  }
  
  ui.with_layout(egui::Layout::top_down(egui::Align::Center), |ui| {
      ui.heading("Wählen sie ein Programm");
      ui.label(""); //Spacer
  
      for chunk in buttons.chunks(3){
          if ui.button("Test").clicked(){
              println!("Test");
          }
          ui.horizontal(|ui|{
              for (filename, path) in chunk{
                  if ui.button(filename).clicked(){
                      println!("{}", path);
                  }
              }
          });
      }
  });
  
  egui::warn_if_debug_build(UI);
});
```

![image](https://user-images.githubusercontent.com/43654377/121914288-6a468f00-cd32-11eb-8f74-7f65a5b8203b.png)

Like you can see, the widgets placed in the ui.horizontal method are aligned to the left, but the "Test" button, that I make before that, gets aligned to the center, as I specify with the ui.with_layout method.

Did I find a bug or is that intentional and I somehow need to specify it again? 
(I tried doing the ui.with_layout again within the ui.horizontal, but that just broke the layout completely by throwing the buttons all together at the right end of the frame with all the text wrapping char by char)

I first tried to use the Grid layout, since that's basically what I want, but it also ignored the layout. Possibly cause it also uses the horizontal method?

So if I can, I would like to use the grid again, but with each row vertically centered.

I hope I provided everything needed to give me an answer.
Thanks for reading!

**Comment by emilk** [comment]
You can't center a whole layout - this is a fundamental shortcoming with immediate mode.

See https://github.com/emilk/egui#why-immediate-mode and https://docs.rs/egui/0.12.0/egui/#understanding-immediate-mode

(there is actually a way to do it with immediate, but it involves calling the code twice - once to collect sizes and once again to do actual placement, and egui doesn't currently support that)

**Comment by ToasterUwU** [comment]
Ohh ok...

Is there a way I still can achieve my goal of centering all buttons?
Or maybe alternatively make them wrap on the end, if the screen border comes?

I just want to decently layout the buttons I have, Centering is not a requirement to me.

Thanks for the help!

**Comment by ToasterUwU** [comment]
OK, I will use something else then. Thanks anyways.

**Comment by tkkcc** [comment]
Same issue here. In order to "survive" screen rotation, a fix sized block can be used. The block is centered to parent, while the content is left aligned. 

```rust
let control = |ui: &mut egui::Ui| {
    ui.vertical(|ui| {
        ui.centered(|ui| {
            ui.label("...");
        });
        ui.horizontal(|ui| {
           // ...
        });
        ui.horizontal(|ui| {
           // ...
        });

    })
    .response
};

egui::CentralPanel::default().show(ctx, |ui| {
    ui.vertical_centered(|ui| ui.add_sized(egui::vec2(300.0, 0.0), control));
});
```


https://user-images.githubusercontent.com/17373509/205952482-8cdf7a84-86ed-4777-9c65-24ecc5633a89.mp4
