### ISSUE TITLE
Advance wgpu version to 22.1, please.

### ISSUE THREAD

**Issue by John-Nagle** [emilk/egui#4905]
Current **wgpu** version is now 22.1. (Yes, 22, not 0.22.)

**egui-wgpu** in crates.io depends upon **wgpu 0.20.1.**

So, crates out of sync, again, and because everybody passes low level types around, compiles fail.

**Comment by YgorSouza** [comment]
That is already done on master. It just hasn't been released yet.

**Comment by John-Nagle** [comment]
Is it? See

https://github.com/emilk/egui/blob/master/Cargo.toml

```
wgpu = { version = "22.0.0", default-features = false, features = [
    # Make the renderer `Sync` even on wasm32, because it makes the code simpler:
    "fragile-send-sync-non-atomic-wasm",
] }

```
[WGPU is at 22.1.0 now.](https://crates.io/crates/wgpu) WGPU got a quick update because something was broken in 22.0.0.

**Comment by YgorSouza** [comment]
22.1 is semver compatible with 22.0, so that is not a problem.

**Comment by John-Nagle** [comment]
OK. But it still needs to be pushed to crates.io so that other crates which depend upon it can be updated.

**Comment by emilk** [comment]
Fixed on master, will be released in next egui release
