### ISSUE TITLE
backspace fail after ime input

### ISSUE THREAD

**Issue by tkkcc** [emilk/egui#4908]
**Describe the bug**
![Peek 2024-08-03 18-25](https://github.com/user-attachments/assets/2a5e8fc9-89fe-4b47-855c-f35a8609e989)

**To Reproduce**
run master(d856f7b3a58fc65a81ff9657f5c6e1ab462b7bb6) egui_demo_app, use fcitx5 ime to input unicode words in text_edit, press backspace won't delete char, but typing, ime input and del key still work.

**Expected behavior**
backspace delete char

**Desktop (please complete the following information):**
 - OS: archlinux, fcitx5 5.1.10

**Additional context**
web version work
use chinese font not help

**Comment by rustbasic** [comment]
I think it will be fine if you apply #4896.

* #4896

**Comment by rustbasic** [comment]
I think it will be fine if you apply #4910

* #4910

**Comment by YgorSouza** [comment]
It seems that after fcd02bd7d1dde123a1b2dce11ae86cea17029ace, the backspace and arrow keys no longer work in the TextEdit in native linux. I guess it thinks IME is always enabled? Even if I disable the compose key and use only the physical keys, it still doesn't work.

**Comment by rustbasic** [comment]
> It seems that after [fcd02bd](https://github.com/emilk/egui/commit/fcd02bd7d1dde123a1b2dce11ae86cea17029ace), the backspace and arrow keys no longer work in the TextEdit in native linux. I guess it thinks IME is always enabled? Even if I disable the compose key and use only the physical keys, it still doesn't work.

Yes. I am currently preparing to commit. Do you use IME? or Will it be recognized as IME enabled even in English?

**Comment by YgorSouza** [comment]
I don't have IME, just a regular US English keyboard. I use the compose key from the Gnome desktop environment, which allows me to enter special characters, e.g., `RCtrl + " + E` enters the Ë character. I don't know if that counts as IME, but the arrow keys and backspace still don't work if I turn that off in the system settings. The `TextEdit` gets the IME enabled event as soon as I click on it. It is disabled when I move the window, and the enabled again. If I enter a special character with the compose key, it gets the commit, disabled, and enabled events. So basically it is always enabled while the `TextEdit` has focus.

![image](https://github.com/user-attachments/assets/8596b934-6f5f-436f-91c7-2873c9db134a)


Also, when I press the compose key, it adds a · character to the string until I press the other keys, and if I click away the character just stays there.

https://github.com/user-attachments/assets/20b01379-7a99-4506-83c1-f31427f23d0e

**Comment by rustbasic** [comment]
Yes, that special character input is considered IME.

Please check if there are any problems when applying #4912.

**Comment by YgorSouza** [comment]
> Yes, that special character input is considered IME.
> 
> Please check if there are any problems when applying #4912.

This does fix the problem with the backspace and the arrow keys for me, and the compose key is still working like before.

**Comment by rustbasic** [comment]
> This does fix the problem with the backspace and the arrow keys for me, and the compose key is still working like before.

thank you.

I hope it will work well in Chinese too.

**Comment by tkkcc** [comment]
thank you, it's fix for me too
