### ISSUE TITLE
Debug tool to highlight unaligned cursor coordinates

### ISSUE THREAD

**Issue by abey79** [emilk/egui#4927]
When `ui.cursor()` is set to fractional coordinates that are not aligned to physical pixels, all sorts of visual issues ensue. For example, `ui.button()` and `ui.selectable_*()` have their text oddly vertically aligned on the background (causing [this](https://github.com/rerun-io/rerun/pull/7064#issuecomment-2270865953)).

It would be very useful to have a tool that displays a big fat point whenever the cursor is unaligned, so we can easily spot the thing that created that misalignment in the first place.

**Comment by emilk** [comment]
See my comment on https://github.com/emilk/egui/issues/4928#issuecomment-2353528354 about the need to decide what we want to align to (ui points of physical pixels)
