### ISSUE TITLE
Improve vertical centering of text (e.g. in buttons)

### ISSUE THREAD

**Issue by abey79** [emilk/egui#4929]
The optical vertical alignment of text is not perfect with button and selectable label, especially with the Inter font we use at rerun. The text here should be ~1-2px lower compared to the background. Unfortunately, we dont have separate control on the top/bottom padding there.

<img width="456" alt="image" src="https://github.com/user-attachments/assets/92602347-802f-4adf-94a3-8032c4babfca">

I'm not sure if there is something in the font metadata that could be used to adjust alignment.

An escape hatch would be provided by making `button_padding` a `Margin` instead of a `Vec2`.

**Comment by emilk** [comment]
You can manually tweak this when you set a font: https://docs.rs/epaint/latest/epaint/text/struct.FontTweak.html

…but we should be able to do better by default too
