### ISSUE TITLE
`TextEdit` requires double touch to focus on Android

### ISSUE THREAD

**Issue by Zoxc** [emilk/egui#4941]
`TextEdit` requires double touch now to focus on Android in 0.28.1. Other however elements still correctly work with a single touch however.

This still occurs on `1f6ae49a5f6bf43a869c215dea0d3028be8d742a`.

**Comment by Zoxc** [comment]
It looks like this is because `TextEdit` does not request focus when clicking. Clicking with a mouse counts as a drag which does request focus, but a touch doesn't count as a drag.

**Comment by emilk** [comment]
This should now be fixed on egui.rs
