### ISSUE TITLE
`egui_extras::TableBuilder`: add a `ensure_row_visible()` method

### ISSUE THREAD

**Issue by abey79** [emilk/egui#4951]
Currently, there are two ways to scroll to a specific part of a table:

- `TableBuilder::scroll_to_row()`: this _always_ scrolls, even if the row is already visible. which is annoying if the scrolling event comes from the row being double clicked as for Rerun's focus mechanism. In that case, you want to avoid scrolling as to not move the item from beneath the mouse cursor.
- ~~`Response::scroll_to_me()`: this works, but then one has to make a decision on which column to scroll to and may or may not incur horizontal scrolling (depending on the ScrollArea layout). Also, it's slightly unergonomic to use.~~ (this actually doesn't work using the `rows()` api, as the row to focus one is never drawn, so it isn't given a chance to call `scroll_to_me()`. 

Ideally, we would have a `TableBuilder::ensure_row_visible(align: Option<Align>)` that would vertically scroll only if the row is not already visible.

**Comment by emilk** [comment]
I did this in the new [`egui_table`](https://github.com/rerun-io/egui_table) instead
