### ISSUE TITLE
What is the method to build the egui app to .exe in Windows ?

### ISSUE THREAD

**Issue by Shrav108** [emilk/egui#4957]
What is the right way to build an app into a executable in Windows ? What attributes need to be mentioned in the main.rs file ? What are the other details necessary for the same ?

**Comment by rustbasic** [comment]
See examples in the `\examples` directory.

When writing a program, put the following in `Cargo.toml`.

```
[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
egui_glow = "0.28.1"
egui_plot = "0.28.1"
egui_extras = { version = "0.28.1", features = ["all_loaders"] }
egui_demo_lib = { version = "0.28.1", features = [ "chrono", ] }
```

**Comment by Shrav108** [comment]
Thank you for your response. I followed what was given in the examples directory.

Method : 

1. Put this in top of your app's main file -
```#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")] // hide console window on Windows in release```

2. Run with ```cargo run -p crate_name```
      -> You will find an executable in ```crate_name\target\debug```. It will come with a console.

3. You can also make an executable with ```cargo build --release```
     -> You find the executable in  ```crate_name\target\release```. A console will not show up.
