### ISSUE TITLE
web-sys 0.70 issue

### ISSUE THREAD

**Issue by taiyoungjang** [emilk/egui#4958]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

fn set_clipboard_text(s: &str) {
    if let Some(window) = web_sys::window() {
        if let Some(clipboard) = window.navigator().clipboard() {

changed function return type:
window.navigator().clipboard() -> Clipboard

**Comment by bircni** [comment]
Please fill out the description - this doesn't help

**Comment by taiyoungjang** [comment]
sorry! i try this. raise error
crates use web-sys 0.70

trunk build


error[E0308]: mismatched types                                                                                                                                                                     
   --> C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\eframe-0.28.1\src\web\mod.rs:187:16
    |
187 |         if let Some(clipboard) = window.navigator().clipboard() {
    |                ^^^^^^^^^^^^^^^   ------------------------------ this expression has type `Clipboard`
    |                |
    |                expected `Clipboard`, found `Option<_>`
    |
    = note: expected struct `Clipboard`
                 found enum `std::option::Option<_>`

**Comment by bircni** [comment]
This was also raised in #4961 and already fixed in a PullRequest #4954
