### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Resonanz** [emilk/egui#4959]
The egui demo has a plot widget. The link to the source code is broken.

```
https://github.com/emilk/egui/blob/master/crates/egui_demo_lib/src/demo/plot_demo.rs
```

404 Page not found.  The link should point to here.

```
https://github.com/emilk/egui_plot/blob/main/demo/src/plot_demo.rs
```

**Comment by emilk** [comment]
`egui_plot` demo now lives at https://emilk.github.io/egui_plot/

**Comment by Resonanz** [comment]
Thanks, but not sure that I understand your resolution "not planned". The link inside the compiled egui demo is pointing to the wrong URL.

**Comment by emilk** [comment]
Where is this broken link? I cannot find it on `master`, nor on https://www.egui.rs/

**Comment by Resonanz** [comment]
Hi @emilk, I cannot see the incorrect link now. The only questionable links I can see would be on here [https://docs.rs/egui_plot/latest/egui_plot/struct.Plot.html](https://docs.rs/egui_plot/latest/egui_plot/struct.Plot.html). The repository and homepage links in the dropdown are pointing at https://github.com/emilk/egui.

Great work on this project btw !
