### ISSUE TITLE
Progress bars

### ISSUE THREAD

**Issue by Bauxitedev** [emilk/egui#496]
Quick question, does egui contain any kind of functionality to draw a progress bar? I haven't been able to find any.

Ideally it would be kinda similar to this imgui progress bar: https://github.com/ocornut/imgui/issues/1901

![](https://user-images.githubusercontent.com/623790/41831953-e5a624ee-7817-11e8-964a-4212766cb4e7.gif)

**Comment by EmbersArc** [comment]
@emilk If you agree that this would be a good feature to have, I could implement one. Let me know if you have any ideas how to style it.

**Comment by sourcebox** [comment]
A progress bar would be really nice to have, I was recently looking for one in the demo app to include it in my latest project.

**Comment by Bauxitedev** [comment]
Here's my temporary workaround if you want a progress bar right now. Replace `progress` with your own progress value from 0 to 1, and `progress_bar_len` with the width of the progress bar in characters.
```rust
let progress_bar_len = 18;
let progress = 0.5;
ui.label(format!(
    "{}",
    (0..progress_bar_len)
        .map(|i| {
            let percent = i as f32 / progress_bar_len as f32;
            if percent < progress {
                '◼'
            } else {
                '◻'
            }
        })
        .collect::<String>()
));
```


![egui_progress](https://user-images.githubusercontent.com/31383123/122912632-d0e23300-d358-11eb-8290-c9a3d4877845.gif)

**Comment by sourcebox** [comment]
@Bauxitedev Thanks, that look good already. I don't need it right now, maybe in about 2 weeks.

**Comment by emilk** [comment]
A progress bar would be nice yes, ideally with an optional text attached to it!

**Comment by EmbersArc** [comment]
I've opened a PR: #519
Let me know if you have suggestions on how to improve it.
