### ISSUE TITLE
unstable clipboard logic on web is incompatible with web_sys 0.3.70

### ISSUE THREAD

**Issue by simon-wh** [emilk/egui#4961]
I'm trying to use `web_sys_unstable_apis` in my project, but it started failing due to an error coming from some special clipboard logic in eframe.

The error:
```error[E0308]: mismatched types
   --> /Users/syte-laptop/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/web/mod.rs:187:16
    |
187 |         if let Some(clipboard) = window.navigator().clipboard() {
    |                ^^^^^^^^^^^^^^^   ------------------------------ this expression has type `Clipboard`
    |                |
    |                expected `Clipboard`, found `Option<_>`
    |
    = note: expected struct `Clipboard`
                 found enum `Option<_>`
```
 
The source:
https://github.com/emilk/egui/blob/master/crates/eframe/src/web/mod.rs#L171-L192

In v0.3.69 and before of web_sys, the return of [`.clipboard()` is `Option<Clipboard>`](https://docs.rs/web-sys/0.3.69/web_sys/struct.Navigator.html#method.clipboard). In [v0.3.70, it is now just `Clipboard`](https://docs.rs/web-sys/0.3.70/web_sys/struct.Navigator.html#method.clipboard)

Thankfully, I'm able to just pin my web_sys dependency to `=0.3.69` and I'm able to compile again

**Comment by simon-wh** [comment]
> @simon-wh Could you test if the branch from PR #4954 works for you?

Looks to be working 👍

**Comment by bioinformatist** [comment]
I also met this problem. When will the #4954 be merged? 😄

**Comment by bircni** [comment]
@bioinformatist please have a look at #4980
