### ISSUE TITLE
`egui_extras::TableBuilder`: allow setting an `Id` source

### ISSUE THREAD

**Issue by abey79** [emilk/egui#4982]
The entire state of the `egui_extras::Table` is stored against an id that is currently hardcoded by `TableBuilder`. This isn't ideal as different table with different content may end up sharing state. Currently, we must use `ui.push_id()` with is unergonomic.

**Comment by canselcik** [comment]
This made me realize `Id::value(&self) -> u64` finally became `pub` instead of `pub(crate)` as of 7 months ago. I used to have this abomination:
```rust
#[serde_as]
#[derive(Clone, Copy, Hash, Eq, PartialEq, serde::Deserialize, serde::Serialize)]
pub struct AggroPubId(#[serde_as(as = "DisplayFromStr")] pub u64);

impl From<Id> for AggroPubId {
    fn from(value: Id) -> Self {
        unsafe { std::mem::transmute(value) }
    }
}
```
