### ISSUE TITLE
Windows .exe file not compiling in other windows PC

### ISSUE THREAD

**Issue by Shrav108** [emilk/egui#4985]
I have made an .exe file using egui framework.  The app is working on my PC.
![image](https://github.com/user-attachments/assets/4b545c32-0697-41ea-a3ef-ef2cd8111fc3)

I seem to be running into a problem when I run it on other windows PCs. The app opens on other PC. But when I press compute, the app crashes / vanishes. What could be the issue ?

I built the .exe using 
```
cargo build --release
```

These are my dependencies

```
[package]
name    = "Hydro"
version = "0.1.0"
edition = "2021"
build   = ".../src/build.rs"

[dependencies]
eframe        = "0.28.1"
egui          = "0.28.1"
egui_glow     = "0.28.1"
egui_plot     = "0.28.1"
egui_extras   = { version = "0.28.1", features = ["all_loaders"] }
egui_demo_lib = { version = "0.28.1", features = [ "chrono", ] }

image  = { version = "0.25", features = ["jpeg", "png"] }
plotly = { version = "0.9.0", features = ["kaleido"] }
genpdf = { version = "0.2.0",  features = ["images"] }
chrono      = "0.4.38"
rfd         = "0.14.1"
imageproc   = "0.25.0"
ab_glyph    = "0.2.28"

[build-dependencies]
winresource = "0.1.17"
```

The compute button calculates some values and creates a graph for plotting (plotly)

```
compute ->  1. calculates some values (no crate used)
             2. uses plotly crate for plotting ( saves a .png file internally in a folder and shows on the gui screen )
```

**Comment by Shrav108** [comment]
I think I got the source of my error. It is as follows :

1. With every COMPUTE clicked, I am generating a new image file in a particular folder.
2. But images which do not change are being displayed ( NO PROBLEM )
3. But I am unable to save new image after COMPUTE and this is the reason for crashing.

Is there a way to handle this problem ? 

How can I save new images and display it without crashing ?

**Comment by bircni** [comment]
the image crate has nothing todo with egui how are you saving the image?
it seems like you cannot overwrite the image

**Comment by YgorSouza** [comment]
If the app is panicking, you should launch it from a command prompt so you can see what the panic message is. Maybe it's just unwrapping an error or something like that. If it is crashing for some other reason (e.g., access violation), it's probably undefined behavior in one of your dependencies (or in unsafe code you wrote yourself). That is way harder to diagnose, but you can check the Windows Event Viewer to see if any error is logged when it crashes.

**Comment by Shrav108** [comment]
I tried to do the following : 

1. Delete the image file before saving the image (to solve overwriting). But it still crashes.
2. I unwrapped all errors. But it still crashes.

I ran the app with console mode in other pc. It exits with some message when it crashes. How to get that message ?

**Comment by YgorSouza** [comment]
Run the app from the command prompt instead of double-clicking on it, so the console stays open when it crashes.

**Comment by Shrav108** [comment]
I got the error from log file. I do not no if it is appropriate to post it here ( The error is from plotly crates kaleido), but here is the message : 

```
thread 'main' panicked at C:\.......\.cargo\registry\src\index.crates.io-6f17d22bba15001f\plotly_kaleido-0.9.0\src\lib.rs:83:25:
could not find kaleido executable in path
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
