### ISSUE TITLE
`egui_extras::Table`: support for hierarchical, multi-row headers

### ISSUE THREAD

**Issue by abey79** [emilk/egui#5002]
We need hierarchical, multi-row headers to efficiently present a large number of column. See this design for example:

<img width="1433" alt="image" src="https://github.com/user-attachments/assets/14b92516-8f41-4af0-810b-46c8679ecb20">

We may need up to 3 levels (entity path -> archetype -> component name).

Related:
- https://github.com/emilk/egui/issues/5003

**Comment by emilk** [comment]
Done in https://github.com/rerun-io/egui_table
