### ISSUE TITLE
eframe Linux: Backspace & arrow keys are completely broken

### ISSUE THREAD

**Issue by StarStarJ** [emilk/egui#5008]
I use the latest master from egui (a9a6e0c2f223419d52a90cb3d40e211810caf1ee), and run the egui_demo_app on x11 linux (no IME). I can't use arrows or backspace in a text edit

Maybe it is related to this issue:
* #4908

**To Reproduce**
Simply start the demo app (native) and the keys wont work

**Desktop (please complete the following information):**
 - OS: debian sid x11 using KDE

**Comment by rustbasic** [comment]
Could you check if applying #4896 fixes the issue?

* #4896

**Comment by StarStarJ** [comment]
I tried 6ef2ef55c4e662762d47ca6639fed5a522cc1159,
which does **not** fix the issue.

**Comment by rustbasic** [comment]
> I tried your branch on rev [6ef2ef5](https://github.com/emilk/egui/commit/6ef2ef55c4e662762d47ca6639fed5a522cc1159), which does **not** fix the issue.

It's strange. The issue only happens when `state.ime_enabled` is `true`. So applying #4896 to set `state.ime_enabled` to `false` when gaining or losing focus should fix the issue, but it's not working, which is strange.

**Comment by rustbasic** [comment]
Dear `emilk`.
#4896 should be applied separately from the resolution of this issue.

**Comment by StarStarJ** [comment]
You are right, it's most likely not related to your merge request

`[crates/egui/src/widgets/text_edit/builder.rs:750:9] state.ime_enabled = true`
ime_enabled is true, seems like winit sends that event. 

maybe a regression there:
https://github.com/rust-windowing/winit/issues/3092

Sadly it affects egui too

**Comment by rustbasic** [comment]
> You are right, it's most likely not related to your merge request
> 
> `[crates/egui/src/widgets/text_edit/builder.rs:750:9] state.ime_enabled = true` ime_enabled is true, seems like winit sends that event.
> 
> maybe a regression there: [rust-windowing/winit#3092](https://github.com/rust-windowing/winit/issues/3092)
> 
> Sadly it affects egui too

Yes. There seem to be a lot of bug reports related to IME in `winit` + `LINUX`. I created a separate option related to `ime_enable`, but it was not approved. When I have time, I will commit a separate option again.

**Comment by rustbasic** [comment]
@StarStarJ 
#4896 has been applied to `egui Master version`, is it still in a weird state?

**Comment by StarStarJ** [comment]
Yes, still buggy.
For now I disabled all IME events on Linux inside the winit handler.

**Comment by rustbasic** [comment]
Could you please check if this can be solved with #5085?

`Settings` window -> Visuals -> Text Edit -> `OFF` IME Support

**Comment by StarStarJ** [comment]
Yes that fixes it as well

**Comment by crumblingstatue** [comment]
Just as a future note: This should have been labeled regression, and blocked the 0.29 release.
This breaks all Linux X11 users.

**Comment by crumblingstatue** [comment]
In the meantime, I made a small patch that just ignores IME events in egui-winit

```toml
# Fix text input being broken on Linux X11
[patch.crates-io.egui-winit]
git = "https://github.com/crumblingstatue/egui.git"
branch = "ime-ignore"
[patch.crates-io.egui]
git = "https://github.com/crumblingstatue/egui.git"
branch = "ime-ignore"
```

**Comment by AlexanderSchuetz97** [comment]
@crumblingstatue 
Thank you, I was about to go insane because of this.
Does your fix have any impact on non linux targets? I compile my app for wasm, linux, windows. (well they all have to work.)

**Comment by crumblingstatue** [comment]
@AlexanderSchuetz97 
> Does your fix have any impact on non linux targets? I compile my app for wasm, linux, windows. (well they all have to work.)

Yes, it disables IME events completely. So IME support is removed on all targets.

**Comment by AlexanderSchuetz97** [comment]
> @AlexanderSchuetz97
> 
> > Does your fix have any impact on non linux targets? I compile my app for wasm, linux, windows. (well they all have to work.)
> 
> Yes, it disables IME events completely. So IME support is removed on all targets.

Ive had to lookup what IME is and yeah... Not relevant for me. Thank you for explaining.
