### ISSUE TITLE
EGUI on crates.io out of sync with EGUI on github, although EGUI version numbers are the same

### ISSUE THREAD

**Issue by John-Nagle** [emilk/egui#5009]
Compare

https://crates.io/crates/egui-wgpu/0.28.1/dependencies

`Version 0.28.1
Depends on wgpu ^0.20.0 `

with 

https://github.com/emilk/egui/blob/master/Cargo.toml

```
version = "0.28.1"
...
wgpu = { version = "22.1.0", default-features = false, features = [
    # Make the renderer `Sync` even on wasm32, because it makes the code simpler:
    "fragile-send-sync-non-atomic-wasm",
] }
```

**Comment by bircni** [comment]
The egui versions are the same as here a new version is still in development. 
You can find the release of `0.28.1`, which is also on crates.io in the tags section:  https://github.com/emilk/egui/releases/tag/0.28.1

Whenever a new egui version will be published the wgpu crate will have the newest version on crates.io

If you really need the newer wgpu version, you can get the egui version with wgpu on `22.1.0` by pulling it from github

```toml
egui ={ git = "https://github.com/emilk/egui.git"}
```

**Comment by John-Nagle** [comment]
That means I can't publish a crate that uses egui on crates.io. Can't have an outside dependency in production.

**Comment by bircni** [comment]
For sure you can! Just use wgpu 20.0 and update it when egui gets updated, too

**Comment by emilk** [comment]
The motivation behind the version on `master` can be found at https://github.com/emilk/egui/blob/master/RELEASES.md#versioning
