### ISSUE TITLE
`egui_extras::Table`: add support for right aligned icons/button in column header

### ISSUE THREAD

**Issue by abey79** [emilk/egui#5015]
This can be used to e.g. indicate/change the sort column/direction:

<img width="204" alt="image" src="https://github.com/user-attachments/assets/fd2aefe8-a64a-428b-ba64-c30a05b465ef">

Using a combination of `right_to_left` and `left_to_right` layout can partially achieve this, but has the side-effect of maxing the column width, which is not desirable.

**Comment by abey79** [comment]
Actually, this could be useful in any cell, not just headers. For example, a button next to a component batch reading `100 items` to expend and see these instances.

**Comment by emilk** [comment]
I think this could be solved as a separate helper. Not sure exactly of the API yet, but something like:

```rs
egui::left_and_right(
    ui,
    |ui| {
        // left-to-right layout, starting at left edge
        ui.label("Left label");
    },
    |ui| {
        // right-to-left layout, starting at right edge
        ui.button("Right button");
    }
);
```

It would need to be aware of it being a sizing pass and do some smart stuff in that case… I'll try to whip something up.
