### ISSUE TITLE
How to use Context::include_bytes for Images ?

### ISSUE THREAD

**Issue by Shrav108** [emilk/egui#5019]
I have an application where the GUI updates new plots on to the screen when a button is pressed. The plot gets saves a .jpeg internally and displays it on the app. I have the following code

```
ui.add(egui::Image::new("D:/XYZ/hydrostatic/Pics/gap_load_stiff_equal.jpeg")
                                    .max_height(340.0)
                                    .max_width(560.0)
                                    .maintain_aspect_ratio(true)
                                    .rounding(10.0));
```

In cargo.toml : 

```
egui_extras   = { version = "0.28.1", features = ["all_loaders"] }
```

When I run the app,  I get this message

![image](https://github.com/user-attachments/assets/5ab2dd87-c0fb-4904-bf2b-63010eb74815)

I also tried with : 
```
ui.add(egui::Image::from_uri("D:/XYZ/hydrostatic/Pics/gap_load_stiff_equal.jpeg"))
```
but still the same message.

How to include Context::include_byte or add more byte loaders ?

**Comment by emilk** [comment]
You need to use [`egui_extras::install_image_loaders`](https://docs.rs/egui_extras/latest/egui_extras/fn.install_image_loaders.html)

**Comment by Shrav108** [comment]
I have already put this function in my main code. I have a code below that shows the plot image when I press the button 
```
ui.add(egui::Image::new(egui::include_image!("D:/XYZ/hydrostatic/Pics/gap_load_stiff_equal.jpeg"))
                                .max_height(330.0)
                                .max_width(560.0)
                                .maintain_aspect_ratio(true)
                                .rounding(10.0));
```
The problem here is that : 
1. First time I press the button with some inputs, it shows the plotted image.
2. But when I press the button with different inputs
        -> _it saves the new plotted image internally but does not update on the app (the older plot is shown)._

The updated image has the same name i.e. overwriting
