### ISSUE TITLE
Rename `id_source` to `id_salt` or similar

### ISSUE THREAD

**Issue by emilk** [emilk/egui#5020]
A lot of widgets take an `id_source` which is mixed in with the id of the parent Ui. This is a misleading name - this is not the source of the id, just a salt added to an existing hash. So `id_salt` would be a better name. Perhaps we can find an even better one?

**Comment by rustbasic** [comment]
`id_salt`, `id_modifier`, `id_suffix`, `id_hash_suffix`

`id_salt` seems easy to use.
`id_modifier` seems easy to understand.

**Comment by emilk** [comment]
* Closed by #5025
