### ISSUE TITLE
TextureHandle.set_partial( ) panics in wgpu

### ISSUE THREAD

**Issue by tsinjue** [emilk/egui#5026]
Can anyone help for this issue? Many thanks.

**Describe the bug**
`TextureHandle.set_partil` panics in wgpu. here is detailed info:
size: [
    3248,
    2432,
]thread 'main' panicked at wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

`Caused by:
  In Queue::write_texture
    Copy of X 100..3348 would end up overrunning the bounds of the Destination texture of X size 3248`

**To Reproduce**

```rust
if let Some(handle) = self.texture_handle.as_mut() {
        let image_data = self.image_data.clone().unwrap();
        handle.set_partial([100usize, 200], image_data, self.texture_options);
        ui.image(SizedTexture::from_handle(&handle));
```

**Comment by emilk** [comment]
You are writing outside the bounds of the texture. The first argument is a position, not a size.
