### ISSUE TITLE
Crashes when resizing window really small, makes the widget size negative

### ISSUE THREAD

**Issue by sigaloid** [emilk/egui#507]
`thread 'main' panicked at 'assertion failed: child_size.x >= 0.0 && child_size.y >= 0.0', /home/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/egui-0.12.0/src/layout.rs:553:9`

On KDE I can resize the window to be basically non-existent, here's a demo with my discord window:

https://user-images.githubusercontent.com/69441971/123142539-1120de80-d449-11eb-8007-24a1ddc3de56.mp4

Seems that resizing the window layout to be that small it somehow sets the child_size to negative? 

Full backtrace: https://pastebin.com/raw/GALPyZ6Q

**Comment by emilk** [comment]
In the next release this is now an opt-in assert
