### ISSUE TITLE
optimize Color32::from_rgba_unmultiplied

### ISSUE THREAD

**Issue by veyh** [emilk/egui#5086]
I noticed displaying images with alpha channels was a bit slower than I expected so I attached a profiler and saw that a considerable amount of time was spent in `Color32::from_rgba_unmultiplied` (though it shows up as `ColorImage::from_rgba_unmultiplied` because it's inlined).

![image](https://i.imgur.com/mgqlM5e.png)

So I looked at the code and basically the [else branch](https://github.com/emilk/egui/blob/master/crates/ecolor/src/color32.rs#L97) is the problem. But since were working with a limited number of values, couldn't we just compute them in advance and use a lookup table instead?

I tried this out and saw a massive performance boost as a result. So I was just wondering if you see anything wrong with it and whether you'd like me to submit a PR (or you can just take these changes and apply them yourself).

This is basically what I did

```rust
use once_cell::sync::Lazy;

static GAMMA_U8_FROM_LINEAR_F32_LUT: Lazy<[u8; 256 * 256]> = Lazy::new(|| {
    let mut values: [u8; 256 * 256] = [0; 256 * 256];

    for color in 0..=255 {
        for alpha in 0..=255 {
            values[(color * 256) + alpha] = gamma_u8_from_linear_f32(
                linear_f32_from_gamma_u8(color as u8) *
                linear_f32_from_linear_u8(alpha as u8)
            );
        }
    }

    values
});

impl Color32 {
    pub fn from_rgba_unmultiplied(r: u8, g: u8, b: u8, a: u8) -> Self {
        let r = unsafe {
            *GAMMA_U8_FROM_LINEAR_F32_LUT.get_unchecked(((r as usize) * 256) + (a as usize))
        };

        let g = unsafe {
            *GAMMA_U8_FROM_LINEAR_F32_LUT.get_unchecked(((g as usize) * 256) + (a as usize))
        };

        let b = unsafe {
            *GAMMA_U8_FROM_LINEAR_F32_LUT.get_unchecked(((b as usize) * 256) + (a as usize))
        };

        Self::from_rgba_premultiplied(r, g, b, a)
    }
}
```

**Comment by YgorSouza** [comment]
I made a version that pulls the lookup table from a file at compile time instead, and uses just regular indexing without unsafe, to see how it goes. It seems to be as fast as the `0` and `255` cases from the current version.

**Comment by veyh** [comment]
Looks good!
