### ISSUE TITLE
Very high latency / judder on egui_wgpu + Vulkan + X11

### ISSUE THREAD

**Issue by valadaptive** [emilk/egui#5089]
**Describe the bug**

On X11, with `egui_wgpu` and Vulkan, with `present_mode` set to the default of `PresentMode::AutoVsync` (which resolves to `PresentMode::Fifo`, there is far more latency than the 3 frames' worth that wgpu claims, and there seem to be occasional "blips" where the framerate tries to catch up:

https://github.com/user-attachments/assets/d46cccb8-0e31-4038-82e0-990ce0eb20be

**To Reproduce**
1. Run the egui demo app with wgpu, on Linux, within an X11 session
2. Try dragging a slider, or a similar "mouse-following" widget
3. Observe the latency and hitches

**Expected behavior**

There should be a reasonably low amount of latency

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Fedora 40 on Xfce, w/ NVIDIA

**More Information**

The examples within the wgpu repository seem to run without any judder, which makes me suspect something in egui_wgpu.

**Comment by valadaptive** [comment]
With the CPU graph in the demo app, you can see a bit more of the weird frame pacing I'm talking about. There are these weird gaps in the graph:

https://github.com/user-attachments/assets/230f9d5c-e221-4a97-9a4f-6f715535ab98

**Comment by valadaptive** [comment]
I think what's going on here is that the frame pacing is slightly too *fast* (notice how it seems to be around 62 FPS in the above recording). This means that frames are submitted to the queue more quickly than they are popped from it, causing ever-increasing latency since the later frames take longer to reach the front of the queue. The judders/gaps are caused by it "catching up" and not submitting any more frames to the queue until all the current ones are processed.

**Comment by valadaptive** [comment]
It seems this goes a bit deeper. With compositing *disabled*, the issue appears only on eframe. With compositing *enabled*, it is reproducible in the wgpu demos as well. I'm using XFCE (with xfwm4), for reference.

**Comment by emilk** [comment]
Is this a duplicate of https://github.com/emilk/egui/issues/5037 ?

**Comment by valadaptive** [comment]
Looking at the actual frame times, this actually happens in the wgpu demos always. Disabling compositing somehow hides it.
