### ISSUE TITLE
How to package as app bundles for macOS

### ISSUE THREAD

**Issue by rustbomber** [emilk/egui#514]

**Comment by sourcebox** [comment]
At the moment there is no really good solution for that. I use [cargo-bundle](https://github.com/burtonageo/cargo-bundle) for that in another project, but it has some issues that may affect you or not.

**Comment by rustbomber** [comment]
[cargo-bundle](https://github.com/burtonageo/cargo-bundle) is many issues, I want egui to run directly on macos, not through the terminal，Can you give some guidance, thanks

**Comment by emilk** [comment]
This issue is more general than just about `egui`

**Comment by geniousli** [comment]
> [cargo-bundle](https://github.com/burtonageo/cargo-bundle) is many issues, I want egui to run directly on macos, not through the terminal，Can you give some guidance, thanks

had you find a solution?
