### ISSUE TITLE
Layout Issue with `CollapsingState`

### ISSUE THREAD

**Issue by nixpulvis** [emilk/egui#5148]
Given:
```rust
let id = ui.make_persistent_id("spyglass");
egui::collapsing_header::CollapsingState::load_with_default_open(ui.ctx(), id, true)
.show_header(ui, |ui| {
    ui.add(
        egui::Slider::new(&mut spyglass.radius, 10.0..=25000.0)
            .logarithmic(true)
            .drag_value_speed(0.1)
            .text("Radius"),
    );
    ui.add_space(2.);
    ui.checkbox(&mut spyglass.disabled, "Override Spyglass");
})
.body(|ui| ui.label("Spyglass"));

```

I get:
![screenshot-2024-09-23T00:29:43Z](https://github.com/user-attachments/assets/f67de2a2-dfba-4aca-8ac7-145be1dec408)

I expect it to look like normal, just inside the new collapsible header:
![screenshot-2024-09-23T00:30:26Z](https://github.com/user-attachments/assets/ed35960a-eba1-43f7-8fa7-a643ac851a61)

Am I doing something wrong?

**Comment by emilk** [comment]
It looks like you're getting exactly what you ask for - a header with a slider and a checkbox, and a body with just a label.

**Comment by nixpulvis** [comment]
Oh my… I got the body and header backward >.< please forgive me I’d been staring at code all weekend
