### ISSUE TITLE
 parent and child windows communicate

### ISSUE THREAD

**Issue by rustbomb** [emilk/egui#515]
How to communicate between parent and child windows and pass parameters？

**Comment by parasyte** [comment]
It is probably easiest to just use channels. Either the [standard library `mpsc`](https://doc.rust-lang.org/nightly/std/sync/mpsc/index.html) or [`crossbeam-channel`](https://docs.rs/crossbeam-channel/) will work. You don't want to block on send or receive, so keep that in mind; `try_send()` paired with `try_recv()` might be the way to go. For `wasm`, various async channel implementations also exist.
