### ISSUE TITLE
Memory, size and exit errors with dynamic library rendering

### ISSUE THREAD

**Issue by CrazyboyQCD** [emilk/egui#5170]
Seperate from https://github.com/emilk/egui/issues/5152
Commits in ascending order:
After https://github.com/emilk/egui/pull/4849 (https://github.com/emilk/egui/pull/4849/commits/46238635494f7a100fe5c8e93559f4d716eab5d8 ~~related with upstream ``winit``, hard to find out the root cause~~ same thing like https://github.com/emilk/egui/issues/5152#issuecomment-2403688921 but only different in error code)
The ``exit`` error:
```bash
error: process didn't exit successfully: `target\debug\e_test.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```
After https://github.com/emilk/egui/pull/4305 (https://github.com/emilk/egui/pull/4305/commits/65b0676ae8f0a6ab6fc329a7bee8feb8e3efe908)
The running error:
```bash
Called `available_rect()` before `Context::run()`
```
[stacktrace.txt](https://github.com/user-attachments/files/17141981/stacktrace.txt)

After https://github.com/emilk/egui/pull/5056 (https://github.com/emilk/egui/pull/4942/commits/97eaf832c7ade31bc83f31c15aad5b05c4454a20)
The running error:
```bash
unsafe precondition(s) violated: ptr::copy_nonoverlapping requires that both pointer arguments are aligned and non-null and the specified memory ranges do not overlap
```
[stacktrace.txt](https://github.com/user-attachments/files/17141865/stacktrace.txt)

After https://github.com/emilk/egui/pull/4744 (https://github.com/emilk/egui/pull/4744/commits/0faab82ec97ddf442bc215a2bfea2b910207333c)
The running error:
```bash
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
```
[stacktrace.txt](https://github.com/user-attachments/files/17141877/stacktrace.txt)

**Comment by CrazyboyQCD** [comment]
Above issues except first one are disappeared in 0.29.1.

**Comment by 0thElement** [comment]
Hello, the second issue still persist even in 0.29.1. 

I encountered this after trying to get [hot-lib-reloader-rs](https://github.com/rksm/hot-lib-reloader-rs) working with the latest egui version. After updating the dependency of `eframe` in the example `examples/hot-egui` from 0.19.0 to 0.29.1, the issue appeared.

**Comment by RockyGitHub** [comment]
I am also encountering the 2nd issue, but in bevy

**Comment by noprobelm** [comment]
I am also encountering this in my bevy app as of 0.31. Not sure how to work around it yet.
