### ISSUE TITLE
Regression: Bottom panel nested inside a window keeps expanding the window

### ISSUE THREAD

**Issue by crumblingstatue** [emilk/egui#5173]
If we put a `TopBottomPanel::bottom` inside a window, some widgets inside it, like `TextEdit::singleline` will cause the window to keep expanding vertically indefinitely.

## Demo video

https://github.com/user-attachments/assets/59bf5d1a-ddff-4dba-b1d4-8a7d8e6961a4

## Bisect

This is a regression caused by #4943.

The offending code is here:
https://github.com/emilk/egui/pull/4943/files#diff-1b1b7f67a664568e1201e4336ca926fa687c506ffaaf2f237a21a1fa4619fab7R824-R825

```Rust
// Keep this rect snapped so that panel content can be pixel-perfect
let rect = ui.painter().round_rect_to_pixels(rect);
```

If we comment this line out, the window stops expanding.

## Minimal reproducing code
```Rust
        egui::Window::new("Bottom panel inside window").show(ctx, |ui| {
            egui::TopBottomPanel::bottom("bottom panel").show_inside(ui, |ui| {
                let mut s = String::new();
                ui.text_edit_singleline(&mut s);
            });
        });
```

**Comment by emilk** [comment]
Thanks for reporting and bisecting!

This seems very related to:
* https://github.com/emilk/egui/issues/5163

Basically: we should round visual shapes to physical pixels, and widgets/Uis to logical points, and not confuse the two

**Comment by rustbasic** [comment]
OS: Windows10
egui: master ( = 0.29.0 )
Renderer: glow, wgpu

If you run the example below under the above conditions, it will be normal.
Can you show the entire example that is problematic?

```
use eframe::egui::*;

fn main() -> eframe::Result {
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default().with_inner_size([320.0, 240.0]),
        // vsync: false,
        ..Default::default()
    };
    eframe::run_native(
        "My egui App",
        options,
        Box::new(|_cc| Ok(Box::<MyApp>::default())),
    )
}

#[derive(Default)]
struct MyApp {
    input: String,
    _text: String,
}

impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        CentralPanel::default().show(ctx, |ui| {
            ScrollArea::vertical()
                .id_salt("editor")
                .max_height(200.0)
                .show(ui, |ui| {
                    ui.text_edit_multiline(&mut self.input);
                });
            ScrollArea::vertical().id_salt("list").show(ui, |ui| {
                for i in 0..100 {
                    ui.label(format!("test{}", i));
                }
            });
        });

        egui::Window::new("Bottom panel inside window").show(ctx, |ui| {
            egui::TopBottomPanel::bottom("bottom panel").show_inside(ui, |ui| {
                let mut s = String::new();
                ui.text_edit_singleline(&mut s);
            });
        });
    }
}
```

**Comment by emilk** [comment]
I suspect this is dependent on `pixels_per_point` being non-integer

**Comment by rustbasic** [comment]
OS: Windows10
native_pixels_per_point : 2.0, 1.25

Yes, it seems to be fine under the above conditions.

**Comment by fluxxcode** [comment]
I can confirm that the same error occurs on Linux with Wayland.
But I couldn't actually reproduce it on Windows either.
