### ISSUE TITLE
Color test shows spurious lines

### ISSUE THREAD

**Issue by 01mf02** [emilk/egui#5177]
The color test on <https://www.egui.rs/#Rendering> shows lines when scrolling. At the beginning, there are no such lines. Sometimes, they disappear once the scrolling is done, sometimes they rest. I have the impression that when using the scroll bar rather than the mouse wheel, the lines have a greater tendency to stay.

**To Reproduce**

1. Go to <https://www.egui.rs/#Rendering>
2. Click on "Color test"
3. Scroll around, preferably with scroll wheel
4. Observe strange lines appearing

**Expected behavior**
No spurious lines should appear.

**Screenshots**
![Screenshot_2024-09-27_16-07-41](https://github.com/user-attachments/assets/a5a9fb4a-7f15-4eb5-9314-90920f9d621a)

**Desktop**
 - OS: Ubuntu 22.04
 - Browser: Firefox 130.0

**Comment by emilk** [comment]
I think the solution is:
* https://github.com/emilk/egui/issues/5164

**Comment by emilk** [comment]
* Duplicare of https://github.com/emilk/egui/issues/3667
