### ISSUE TITLE
[regression] [eframe] Backspace and arrow keys don't work in `TextEdit`

### ISSUE THREAD

**Issue by crumblingstatue** [emilk/egui#5181]
On Linux, X11, pressing backspace or using the arrow keys to move the cursor have no effect.
This is a regression, because it used to work in 0.28.

**Desktop:**
 - OS: Linux, X11

**Additional context**
#4912 is the pull request that introduces the regression.

**Comment by crumblingstatue** [comment]
Ah, this looks like it might be a duplicate of #5008.
I'm surprised egui 0.28 was released with such a serious regression.

**Comment by emilk** [comment]
Closed as duplicate of https://github.com/emilk/egui/issues/5008
