### ISSUE TITLE
Allow easier setting of background color for TextEdit

### ISSUE THREAD

**Issue by AlexanderSchuetz97** [emilk/egui#5183]
**Is your feature request related to a problem? Please describe.**
Setting background color on TextEdit is pain. 
I require a few text edits to have different background colors on a single GUI.
for example one currently has to do something like this to set the background color of a single text edit:
```rust
  let old_color = ui.visuals_mut().extreme_bg_color;
  ui.visuals_mut().extreme_bg_color = RED;
  ui.add(egui::TextEdit::singleline(&mut self.my_awesome_string));
  ui.visuals_mut().extreme_bg_color = old_color;
```

**Describe the solution you'd like**
```rust
  ui.add(egui::TextEdit::singleline(&mut self.my_awesome_string).background_color(RED));
```

**Describe alternatives you've considered**
Workaround as described in Feature Request is what I currently use.

**Additional context**
RED is a constant Color32 in the examples.

After looking at the TextEdit's show implementation I think I would be capable of implementing this myself and make a PR if you do not have the time to implement it yourself. However I would only make this effort if you actually want this "feature". Please let me know what you think

**Comment by YgorSouza** [comment]
For the record, you can also use [Ui::scope](https://docs.rs/egui/0.29.0/egui/struct.Ui.html#method.scope) for that.

```rs
ui.scope(|ui| {
    ui.visuals_mut().extreme_bg_color = Color32::RED;
    ui.text_edit_singleline(&mut self.name);
});
```
