### ISSUE TITLE
Latest egui file_dialog compiles with warning

### ISSUE THREAD

**Issue by Resonanz** [emilk/egui#5207]
Ubuntu 24.04, running Wayland, rustc 1.81, latest egui 29.1.

After solving https://github.com/emilk/egui/issues/5205#issuecomment-2387694303 ```sudo apt install libgtk-3-dev```, egui's example file_dialog compiled with the following warning...

(Unfortunately file_dialog's drag-and-drop capability does not work with Ubuntu 24.04 Wayland.)

```
cargo run --release -p file_dialog
warning: struct `DummyStorage` is never constructed
   --> crates/eframe/src/epi.rs:803:19
    |
803 | pub(crate) struct DummyStorage {}
    |                   ^^^^^^^^^^^^
    |
    = note: `DummyStorage` has a derived impl for the trait `Default`, but this is intentionally ignored during dead code analysis
    = note: `#[warn(dead_code)]` on by default

warning: `eframe` (lib) generated 1 warning
    Finished `release` profile [optimized] target(s) in 0.50s
     Running `target/release/file_dialog`
```

**Comment by emilk** [comment]
This is just a warning in newer `rustc`
