### ISSUE TITLE
EXC_BAD_ACCESS in `Color32::from_rgba_unmultiplied` on iOS

### ISSUE THREAD

**Issue by lucasmerlin** [emilk/egui#5210]
When I'm running my app for iOS with a debug build I'm now getting a EXC_BAD_ACCESS (Maybe this is a stackoverflow?). I guess this came with https://github.com/emilk/egui/pull/5088, it seems like [u8; 65536] crosses some limit? When running a release build, everything works as expected. 

<img width="739" alt="image" src="https://github.com/user-attachments/assets/7f093993-29c1-4258-9601-ca4daac2b82c">

**Comment by emilk** [comment]
Maybe we just need to put it on the heap, i.e. use a `Vec` or `Box<[u8; 256 * 256]>` instead in the `OnceLock`
