### ISSUE TITLE
HLines and VLines cannot have custom stroke colors

### ISSUE THREAD

**Issue by Arc-blroth** [emilk/egui#524]
With egui 0.13.0, it is impossible to set a custom `Stroke` for the `HLine` and `VLine` plot items, since there is no setter method on either of those. (`Line` _does_ however have setter methods for the stroke, stroke width, and stroke color.)

I'm not sure if this was an oversight as part of the plot widget overhaul or an intended API change - if it was unintentional, I'd be happy to PR the missing setters!

**Comment by EmbersArc** [comment]
Good catch, that was an oversight, I'll fix it in #482.

**Comment by emilk** [comment]
Already fixed in https://github.com/emilk/egui/pull/526 :)
