### ISSUE TITLE
Painter method for line is missing

### ISSUE THREAD

**Issue by Resonanz** [emilk/egui#5273]
```
Error[E0599] no method named `line` found for reference `&egui::Painter` in the current scope
```
https://docs.rs/egui/latest/egui/enum.Shape.html#method.line

```
/// A line through many points.
pub fn line(points: Vec<Pos2>, stroke: impl Into<PathStroke>) -> Self
```

**To Reproduce**

```
let mut vec = Vec::new();
vec.push(Pos2 {x: 0., y: 0.});
vec.push(Pos2 {x: 10., y: 50.});

ui.painter().line(vec, (3., Color32::YELLOW));

```
There are no problem using ```line_segment``` rather than ```line'''. 

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 24.04

**Comment by lucasmerlin** [comment]
The method you linked is on the `Shape` struct, not the `Painter`. You should be able to do `painter.add(Shape::line(...))`. But it would make sense to add a `Painter::line` function as well 👍🏻

**Comment by Resonanz** [comment]
Thanks, you are right, that worked:

```
let mut v = Vec::new();
v.push(Pos2 {
    x: locx + 0.,
    y: locy + 0.,
});
v.push(Pos2 {
    x: locx + 70.,
    y: locy + 0.,
});
v.push(Pos2 {
    x: locx + 70.,
    y: locy + 70.,
});
v.push(Pos2 {
    x: locx + 0.,
    y: locy + 70.,
});
v.push(Pos2 {
    x: locx + 0.,
    y: locy + 0.,
});

ui.painter().add(Shape::line(v, (1., Color32::LIGHT_BLUE)));
```

This is also how it is done in the Spinner widget.
