### ISSUE TITLE
[eframe] Serde feature is broken

### ISSUE THREAD

**Issue by MeGaGiGaGon** [emilk/egui#5278]
**Describe the bug**
When using `eframe`, the `"serde"` feature doesn't work to enable serde derives on egui types, while `"persistence"` does work.
This only happens when importing through `eframe`, this doesn't happen when using `egui` directly.

**To Reproduce**
1. Create a new crate, in my case `cargo new egui_serde_test`
2. Make the contents of `cargo.toml` 
```toml
[package]
name = "egui_serde_test"
version = "0.1.0"
edition = "2021"

[patch.crates-io]
egui = { git = "https://github.com/emilk/egui", branch = "master" }
eframe = { git = "https://github.com/emilk/egui", branch = "master" }

[dependencies]
eframe = { version = "0.29.1", features = [ "serde" ] }
serde = { version = "1.0", features = [ "derive" ] }
```
3. Make the contents of `main.rs` 
```rust
#[derive(serde::Serialize)]
struct IdSerdeTest(eframe::egui::Id);

fn main() {
    println!("Hello, world!");
}
```
4. Run `cargo check`
5. Observe the "the trait bound `Id: Serialize` is not satisfied" error
<details>
<summary> full error message</summary>

```rust
error[E0277]: the trait bound `Id: Serialize` is not satisfied
   --> src/main.rs:1:10
    |
1   | #[derive(serde::Serialize)]
    |          ^^^^^^^^^^^^^^^^ the trait `Serialize` is not implemented for `Id`
2   | struct IdSerdeTest(eframe::egui::Id);
    |                    ------ required by a bound introduced by this call
    |
    = note: for local types consider adding `#[derive(serde::Serialize)]` to your `Id` type
    = note: for types from other crates check whether the crate offers a `serde` feature flag
    = help: the following other types implement trait `Serialize`:
              &'a T
              &'a mut T
              ()
              (T,)
              (T0, T1)
              (T0, T1, T2)
              (T0, T1, T2, T3)
              (T0, T1, T2, T3, T4)
            and 131 others
note: required by a bound in `serialize_newtype_struct`
   --> C:\Users\gigagon\.cargo\registry\src\index.crates.io-6f17d22bba15001f\serde-1.0.210\src\ser\mod.rs:907:21
    |
901 |     fn serialize_newtype_struct<T>(
    |        ------------------------ required by a bound in this associated function
...
907 |         T: ?Sized + Serialize;
    |                     ^^^^^^^^^ required by this bound in `Serializer::serialize_newtype_struct`
    = note: this error originates in the derive macro `serde::Serialize` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `egui_serde_test` (bin "egui_serde_test") due to 1 previous error
```

</details>

6. Switch `"serde"` to `"persistence"` in `cargo.toml`
7. Run `cargo check`
8. Observe no errors

**Expected behavior**
The `"serde"` feature enables serde trait derives on `egui` though `eframe`

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by YgorSouza** [comment]
Should crates propagate `serde` to their re-exports when they don't need to? The API guidelines don't seem to make any recommendation on that. On the one hand it's practical, but on the other hand it takes some control away from the user. What if someone actually just wants to serialize `WebGlContextOption` and doesn't want to pay the price of compiling serde traits for all of egui's types?

**Comment by bircni** [comment]
please just import egui as own crate and then it works

**Comment by MeGaGiGaGon** [comment]
Yep, that does make sense. The main annoying thing is that by having both eframe and egui as dependencies, you can get the annoying situation where you have two different versions of egui, and then get fun errors like `got egui::ui::Ui, expected egui::ui::Ui`, but that's not worth the cost of extra serialization. Sorry for the churn!
