### ISSUE TITLE
Show `Slider` buttons only when the mouse hovers.

### ISSUE THREAD

**Issue by zhatuokun** [emilk/egui#5280]
**Is your feature request related to a problem? Please describe.**

In the progress bar of some music players, the `Slider` button will only be displayed when the mouse hovers. At present, egui has no built-in option to do this.

**Describe the solution you'd like**

Add an option to control whether the `Slider` button is displayed only when the mouse hovers.

**Describe alternatives you've considered**

I try to use this hack method, although it can achieve similar results, but it will slightly affect the layout.

```rs
// a code fragment
{
  set_slider_handle_shape_size(ui, 0.0);

  if is_pointer_in_rect(ui.ctx(), ui.max_rect()) {
    set_slider_handle_shape_size(ui, 10.0);
  }

  ui.add(Slider::new(xx, yy));
}

fn is_pointer_in_rect(egui_ctx: &egui::Context, rect: egui::Rect) -> bool {
    egui_ctx
        .input(|i| i.pointer.hover_pos())
        .map_or(false, |p| rect.contains(p))
}

fn set_slider_handle_shape_size(ui: &mut egui::Ui, size: f32) {
    ui.spacing_mut().interact_size.y = size;
    if let Some(s) = ui.style_mut().text_styles.get_mut(&egui::TextStyle::Body) {
        s.size = size;
    }
}
```

**Additional context**

**Comment by rustbasic** [comment]
Note:
It may be better to pop up a `Window` or a `Popup` rather than supporting the functionality in a `Slider`.

**Comment by zhatuokun** [comment]
@rustbasic Hey, bro, maybe I didn't express myself clearly enough, sorry for my bad English.

![exp1](https://github.com/user-attachments/assets/0d334d71-ae69-4170-a1cc-e0239893c7a6)
![exp2](https://github.com/user-attachments/assets/fb086830-f6a4-411d-87f7-1134e90511a6)

When your mouse is not hovering, it is just like a progress bar, so it would be nice if the slider could do this.

**Comment by YgorSouza** [comment]
If you're not using the number part, you can use this hack:

```rs
ui.scope(|ui| {
    ui.visuals_mut().widgets.inactive.expansion = -100.0;
    ui.add(egui::Slider::new(&mut self.age, 0..=120).show_value(false));
});
```

**Comment by zhatuokun** [comment]
> If you're not using the number part, you can use this hack:
> 
> ```rust
> ui.scope(|ui| {
>     ui.visuals_mut().widgets.inactive.expansion = -100.0;
>     ui.add(egui::Slider::new(&mut self.age, 0..=120).show_value(false));
> });
> ```

Oh, bro, thanks! This solved my problem.

It's a little hack, but it's much better, so I think this can be closed.
