### ISSUE TITLE
ScrollArea is not properly clipping items near the bottom edge

### ISSUE THREAD

**Issue by DrOptix** [emilk/egui#529]
The repro steps are in the gif bellow:
![egui_scroll_area_wrong_clipping](https://user-images.githubusercontent.com/512152/123682527-c42b7680-d853-11eb-8f1d-6617f374dc6c.gif)

I'm trying to figure out how to fix it and propose a PR, but if anyone knows where we need to apply a patch let us know.
This is a rendering from egui integrated in my game engine, but the same can be reproduced with the latest `main`.

**Comment by parasyte** [comment]
I've done a lot of testing with the ScrollArea and haven't seen that behavior, except when [`debug_ignore_clip_rects`](https://docs.rs/epaint/0.13.0/epaint/tessellator/struct.TessellationOptions.html#structfield.debug_ignore_clip_rects) is enabled.

You can check and mutate the value with something like this:

```rust
let mut tessellation_options = ctx.memory().options.tessellation_options;
dbg!(tessellation_options);
tessellation_options.debug_ignore_clip_rects = false;
ctx.memory().options.tessellation_options = tessellation_options;
```

You can also enable `debug_paint_clip_rects` the same way, or even use `ctx.settings_ui()` to make these kinds of changes at runtime like the demo app does.

**Comment by DrOptix** [comment]
I forgot to do a crucial test case, to get the egui code I have in my engine and plug it into egui_demo_app.

I did that and indeed the clipping problem goes away. When I said is there with the latest `main` I actually meant that I plugged egui as a dependency to the cloned repo from my disk that was at the latest commit on `main`.

Now I'm investigating your suggestion. Thank you!

**Comment by DrOptix** [comment]
I'm closing this issue.

Using the settings window to debug the clip rectangles I concluded that it is related to the fact that the tessellator is doing just a coarse test. I need to use the clip rect of the ClippedMesh to do the true clipping when I render.
