### ISSUE TITLE
Copy (CTRL+C and ui.output_mut) crash if HTTP

### ISSUE THREAD

**Issue by itsNiccoloSabatini** [emilk/egui#5293]
## What happened
After the update for egui 0.29.1 i noticed that whenever i try to copy something in HTTP the WASM compiled version has a fatal crash at runtime. This does not happen when i use HTTPS.

## When does it happen 
**No matter if the OS is Windows or Linux it crashes in both.**
whenever i try to copy some text from the WASM page but in HTTP protocol, in 0.27.2 it just wouldn't have copied anything but since when the web-sys-unstable-apis aren't needed anymore, and something changed about how the copy to clipboard works, the copy in a HTTP page makes everything crash.

this happens in every time if i press CTRL+C or i use the code macro in HTTP:
```rust
ui.output_mut(|o| {
    debug!("Copying API key to clipboard: {:?}", key);
    o.copied_text.clone_from(&key.to_string());
});
```

## Image of the error in Chromium
![Schermata del 2024-10-21 16-02-02](https://github.com/user-attachments/assets/ca438af3-efdd-4316-904c-6590edd9703b)

## Image of the error in Firefox
![immagine](https://github.com/user-attachments/assets/c3382372-e384-40e6-aed8-39a086346e95)

**Comment by lucasmerlin** [comment]
The clipboard api (which I guess is used now) only works in secure contexts ([explained here](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#security_considerations)). So when accessing an egui app over http on an address other than localhost this will fail. But of course egui shouldn't crash but return some kind of error result so the failure can be caught gracefully.

**Comment by emilk** [comment]
I don't have this problem on https://www.egui.rs/ - do you? If not, I would suspect this is a wasm-bindgen mismatch on your end, or something similar

**Comment by lucasmerlin** [comment]
> I don't have this problem on [egui.rs](https://www.egui.rs/) - do you? If not, I would suspect this is a wasm-bindgen mismatch on your end, or something similar

It should only happen when accessing an egui app via http (not https) on domains other than localhost, since the clipboard api is not available there. So this is a bit of an edge case, but we should still try to handle this without crashing

**Comment by YgorSouza** [comment]
I was able to reproduce the issue locally with the demo by navigating to my machine's LAN IP ( `192.168...` as returned by e.g. `ifconfig` on Linux) instead of `127.0.0.1`. Then it considers that it is not a secure context and copying text panics. My PR changes it to just log an error and return instead, as it was before.

![image](https://github.com/user-attachments/assets/135b0f25-91b7-4110-8c4d-76535b646a05)
