### ISSUE TITLE
Display needs to be magnifiable

### ISSUE THREAD

**Issue by BartMassey** [emilk/egui#53]
Either ctl-scrollwheel or ctl-shift-+ needs to work to magnify the UI as a whole. This is pretty much a necessity both for accessibility (my vision is terrible) and for hi-DPI screens (I'm using a 4K monitor). If I understand correctly, the decision to work in screen coordinates may make this hard: however, it's a must-have for any application that is intended for widespread web deployment.

**Comment by emilk** [comment]
This is a great point, and actually should not be too hard to implement. I already have a slider for scaling up the UI, so hooking it up to the appropriate events shouldn't be too much work.

**Comment by BartMassey** [comment]
Sweet!

**Comment by actionless** [comment]
any chance to get dpi configurable also for desktop backends? (for example via optional env var)

**Comment by emilk** [comment]
@actionless It is already configurable with https://docs.rs/egui/latest/egui/struct.Context.html#method.set_pixels_per_point

**Comment by actionless** [comment]
@emilk  my point was what in case of browser backend user can change the scale themselves by using Ctrl+Scroll or such

while on desktop scale could be changed only if the developer will add some custom code for that
