### ISSUE TITLE
Set initial window size with epi.

### ISSUE THREAD

**Issue by etrombly** [emilk/egui#534]
Calling frame.set_window_size works in the update function, but not from setup. I just want to set the initial size, not lock the window to one size:

    fn setup(
        &mut self, 
        _ctx: &CtxRef, 
        frame: &mut epi::Frame<'_>, 
        _storage: Option<&dyn Storage>
    ) {
        frame.set_window_size(egui::Vec2{x:1200.0,y:600.0});
    }

    /// Called each time the UI needs repainting, which may be many times per second.
    /// Put your widgets into a `SidePanel`, `TopPanel`, `CentralPanel`, `Window` or `Area`.
    fn update(&mut self, ctx: &egui::CtxRef, frame: &mut epi::Frame<'_>) {
        frame.set_window_size(egui::Vec2{x:1200.0,y:600.0});

**Comment by emilk** [comment]
https://docs.rs/epi/0.13.0/epi/struct.NativeOptions.html#structfield.initial_window_size
