### ISSUE TITLE
Git lfs out of storage. 

### ISSUE THREAD

**Issue by Muzz** [emilk/egui#5348]
Looks like the LFS is out of quota, so i can't clone properly. 

Downloading crates/egui/assets/ferris.png (46 KB)
Error downloading object: crates/egui/assets/ferris.png (
5724e4e): Smudge error: Error downloading crates/egui/ass
ets/ferris.png (5724e4e1afa6091434e599c767c1d8b3c2646c26d
3cc84c9bea70a5cdddbc8a5): batch response: This repository
 is over its data quota. Account responsible for LFS band
width should purchase more data packs to restore access.

**Comment by emilk** [comment]
Oops - thanks for reporting! I upgraded to 50GB/month; hopefully that should be enough for a while 🤞

**Comment by Muzz** [comment]
Np thanks for fixing!
