### ISSUE TITLE
bad window decorations without sudo

### ISSUE THREAD

**Issue by avitran0** [emilk/egui#5354]
**Describe the bug**
when starting any egui application on my system the window decorations are borked. when running the program with sudo, the decorations are fine.

**To Reproduce**
1. build egui_demo_project on fedora
2. without sudo, decorations are broken
3. with sudo, they are fine

**Expected behavior**
window decorations should work without sudo

**Screenshots**
without sudo:
![without_sudo](https://github.com/user-attachments/assets/93fe05a4-5858-4ff1-8d70-befa7a71d3a7)
with sudo:
![with_sudo](https://github.com/user-attachments/assets/9264d866-044c-4cb6-a727-e5463ceeb0d6)

**Desktop (please complete the following information):**
 - OS: Fedora 40
 - Browser: n/a
 - Version: 40

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**
running default fedora install with gnome, wayland and a nvidia gpu. all other applications have working window decorations.

**Comment by lucasmerlin** [comment]
My guess would be that this is a winit issue, can you try running one of the winit examples to see if the same thing happens there?

**Comment by avitran0** [comment]
just tried that, it indeed seems to be a winit issue. thank you.

**Comment by avitran0** [comment]
i opened one [here](https://github.com/rust-windowing/winit/issues/3988). this seems to be wayland-specific, because the wayland server does not provide window decorations, the client has to do it themselves. winit draws the decorations itself with the sctk crate, and not with libdecor or gtk, which is why it does not look like other system decorations. when running with sudo, it runs under x11, whose server _does_ provide decorations.

**Comment by avitran0** [comment]
to force winit to run under x11, you can use `std::env::remove_var("WAYLAND_DISPLAY");` before the egui/eframe initialization. this will also make options like hiding the maximize button work.

**Comment by avitran0** [comment]
on winit versions before 0.29.2, you would have to use `std::env::set_var("WINIT_UNIX_BACKEND", "x11");`.

**Comment by TuTiuTe** [comment]
Then how come running the same code on KDE wayland and GNOME wayland yields different decoration results?
Who provides window decorations for KDE windows?

<img width="462" height="418" alt="Image" src="https://github.com/user-attachments/assets/04f1be6d-fdcf-474d-be62-908633e6a58a" />

On KDE 6.4

<img width="436" height="366" alt="Image" src="https://github.com/user-attachments/assets/2685ade2-f694-469e-8875-c1a01e0970a2" />

On gnome 48

Also tested with hyprland, it hides the decorations altogether and adds its gradient border properly, though I don't know if removing decorations is tied to styling them
