### ISSUE TITLE
Merge Pos2 and Vec2? Or use linear algebra library?

### ISSUE THREAD

**Issue by mankinskin** [emilk/egui#536]
Is there a difference between Pos2 and Vec2? It seems like they are basically interchangable.

Also what about using a linear algebra library like nalgebra or cgmath for vector math? This would also give us matrices and all the related implementations immediately.

**Comment by emilk** [comment]
Points and vectors are different things (https://docs.rs/emath/0.13.0/emath/struct.Vec2.html). Some libraries chose to represent them using the same primitive, but `emath` does not. This helps catch some bugs, like the mixing up the parameters to `Rect::from_min_max` and `Rect::from_min_size`.

egui doesn't really need matrices, so right now I'm opting for a more minimalistic and custom approach. `emath` is opinionated and custom made for a GUI library (i.e. calling the max Y edge of a rect "bottom", which nalgebra or cgmath would not, and should not, do)

**Comment by mankinskin** [comment]
Understandable. In this case what do you think about `From` conversion implementations between them? `Pos2` has `.to_vec2()` but `Vec2` does not have the reverse. I think `.to_pos2()` would be consistent and useful, aswell as `From` implementations. It should be a small addition so I can quickly open a PR.
