### ISSUE TITLE
Visuals wont apply correclty when building for Windows

### ISSUE THREAD

**Issue by MercuryHgO** [emilk/egui#5368]
**Describe the bug**

When building my app for x86_64-unknown-linux-gnu on host of NixOS 24.05, my app correctly applies configures style, but when building for x86_64-pc-windows-msvc on host of Windows, these styles wont apply correctly.

This is how visuals definition looks like in my code:
```rust
cc.egui_ctx.set_visuals(egui::Visuals {
    dark_mode: false,
    widgets: egui::style::Widgets {
        inactive: egui::style::WidgetVisuals {
            weak_bg_fill: Color32::from_hex("#67ba80").unwrap(),
            bg_fill: Color32::from_gray(230),
            bg_stroke: Default::default(), // separators, indentation lines
            fg_stroke: Stroke::new(1.0, Color32::from_gray(60)), // normal text color
            rounding: Rounding::same(2.0),
            expansion: 0.0,
        },
        hovered: egui::style::WidgetVisuals {
            weak_bg_fill: Color32::DARK_GREEN,
            bg_fill: Color32::DARK_GREEN,
            bg_stroke: Stroke::new(1.0, Color32::from_gray(105)), // e.g. hover over window edge or button
            fg_stroke: Stroke::new(1.5, Color32::from_gray(240)),
            rounding: Rounding::same(3.0),
            expansion: 1.0,
        },
        ..egui::style::Widgets::light()
    },
    ..egui::Visuals::light()
});
```
**To Reproduce**
As described, build the app for the Windows platform to see the problem.

**Expected behavior**
Correct rendering of applied visuals

**Screenshots**
Linux:
![image](https://github.com/user-attachments/assets/d038b19c-d9bb-4671-b7e5-8a5151285657)
Windows:
![image](https://github.com/user-attachments/assets/57fa9ac2-83f2-4850-a2b3-9bf24a1b6bda)

**Desktop (please complete the following information):**
 - OS: NixOS 25.05, Windows 10

**Comment by lucasmerlin** [comment]
I can't imagine that this is related to the platform. `Context::set_visuals` sets the visuals for the current theme, you could instead use set_visuals_of with Theme::Light and then set the theme to always be light (via set_theme).

**Comment by MercuryHgO** [comment]
> I can't imagine that this is related to the platform. `Context::set_visuals` sets the visuals for the current theme, you could instead use set_visuals_of with ThemePreference::Light and then set the theme to always be light (via set_theme).

Did the job, many thanks!
