### ISSUE TITLE
Clipboard access on non https site breaks app

### ISSUE THREAD

**Issue by e00E** [emilk/egui#5388]
This issue is out of egui's control. I'm creating it to help other people running into it when they search for the error message.

## Description

When you try to use the clipboard in egui web app for example by selecting text and pressing ctrl-c to copy it, then you get an error in the console and the whole app freezes forever. This only happens if you access the site over http instead of https. On localhost like through `trunk serve` it does not happen either.

In Firefox the error starts with this line:

> Uncaught TypeError: getObject(...) is undefined

In Chrome the error starts with this line:

> Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')

## Explanation

Egui since version.0.29.0 supports clipboard access on the web. In egui code this happens through [`window.navigator().clipboard()`](https://docs.rs/web-sys/0.3.72/web_sys/struct.Navigator.html#method.clipboard). As the [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard) warns:

> Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard#browser_compatibility).

This is not reflected in this web-sys API, which causes a panic when the API is not available like in this case.  The issue has been reported here https://github.com/rustwasm/wasm-bindgen/issues/4085 .

**Comment by lucasmerlin** [comment]
There already is https://github.com/emilk/egui/issues/5293 and a PR https://github.com/emilk/egui/pull/5326 for this, so I'm closing this as a duplicate. This should be "fixed" in the next egui release (we will log a helpful error message and added a note to the docs).
