### ISSUE TITLE
Can't run eframe program on wayland.

### ISSUE THREAD

**Issue by vol8** [emilk/egui#5401]
**Describe the bug**
I am on NixOS using Wayland. I am trying to run a simple eframe demo. It builds but when I run the program, I get this error:
`Error: WinitEventLoop(Os(OsError { line: 81, file: "/home/vol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoWaylandLib)) }))`

**To Reproduce**
Run this code: 
```rust
use eframe::{egui, NativeOptions};

fn main() -> eframe::Result {
    eframe::run_native(
        "My egui App",
        NativeOptions::default(),
        Box::new(|cc| {
            Ok(Box::<MyApp>::default())
        }),
    )
}

#[derive(Default)]
struct MyApp {
}

impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {
            ui.heading("My egui Application");
        });
    }
}
```

There was a guy that had a similar problem but his fix didn't help either. 
https://github.com/emilk/egui/issues/4528

**Comment by AvinashPrajapati** [comment]
it is not the problem of the EGUI, it is problem of the WSL
issues #3413

**Comment by vol8** [comment]
> it is not the problem of the EGUI, it is problem of the WSL issues #3413

How is that a WSL issue when I am not on Windows? I cannot be using WSL on NixOS.

**Comment by AvinashPrajapati** [comment]
> > it is not the problem of the EGUI, it is problem of the WSL issues #3413
> 
> How is that a WSL issue when I am not on Windows? I cannot be using WSL on NixOS.

you can enable Ozone Wayland support in [Chromium](https://nixos.wiki/wiki/Chromium) and [Electron] based applications by setting the environment variable NIXOS_OZONE_WL=1. For example, in a configuration.nix 

That is why i am saying.... there is problem with the support backup from the OS

**Comment by vol8** [comment]
> > > it is not the problem of the EGUI, it is problem of the WSL issues #3413
> > 
> > 
> > How is that a WSL issue when I am not on Windows? I cannot be using WSL on NixOS.
> 
> you can enable Ozone Wayland support in [Chromium](https://nixos.wiki/wiki/Chromium) and [Electron] based applications by setting the environment variable NIXOS_OZONE_WL=1. For example, in a configuration.nix
> 
> That is why i am saying.... there is problem with the support backup from the OS

First of all, sry I misunderstood you, I thought you were meaning the windows subsystem for linux lol

I have reported this issue to the `winit` repo and they said that I need to have `libwayland` installed. 
With this I will close the issue because thats just what needs to be installed. 
I'll just need a way to somehow link the `libwayland` into the Rust binary with something called `rpath`?
If anyone figures out how to use that, comment pls

**Comment by yassinebenarbia** [comment]
> > > > it is not the problem of the EGUI, it is problem of the WSL issues #3413
> > > 
> > > 
> > > How is that a WSL issue when I am not on Windows? I cannot be using WSL on NixOS.
> > 
> > 
> > you can enable Ozone Wayland support in [Chromium](https://nixos.wiki/wiki/Chromium) and [Electron] based applications by setting the environment variable NIXOS_OZONE_WL=1. For example, in a configuration.nix
> > That is why i am saying.... there is problem with the support backup from the OS
> 
> First of all, sry I misunderstood you, I thought you were meaning the windows subsystem for linux lol
> 
> I have reported this issue to the `winit` repo and they said that I need to have `libwayland` installed. With this I will close the issue because thats just what needs to be installed. I'll just need a way to somehow link the `libwayland` into the Rust binary with something called `rpath`? If anyone figures out how to use that, comment pls

I was able to get an `eframe` application to work on my `NixOS` machine by linking `wayland`, `libxkbcommon` and `vulkane-loader` to the compiled binary, via something like this on `.cargo/config.toml`
```toml
[build]
rustflags = ["-C", "link-arg=-Wl,-rpath,/nix/store/84839y8j0d4l4d3q048v00h20jdk9lh0-wayland-1.23.1/lib:/nix/store/pxww3rra041yadg758ii500kagr5l090-vulkan-loader-1.3.296.0/lib:/nix/store/i0d0ws5xwix1dvmwp8w1fr4kz61k11x4-libxkbcommon-1.7.0/lib:/nix/store/ymhcg6x5jrw3hx8ik1cji6awiybgp9f7-libglvnd-1.7.0/lib"]
```
for those "magic" paths, I got them by installing those packages and then `nix eval nixpkgs#<package-name>.outPath` (add `/lib` at the end), this is the code for the app that I've tested
```rust
fn main() {
    eframe::run_simple_native("hello", Default::default(), |ctx, _frame| {
        eframe::egui::CentralPanel::default().show(ctx, |ui| {
            ui.label("hello world");
        });
    })
    .unwrap();
}
```
[and here's where I got my "inspiration" from](https://github.com/NixOS/nixpkgs/blob/0abc80da7fccfe6104ec9657c343ac4229ace612/pkgs/by-name/co/coppwr/package.nix#L65-L74)

**Comment by vol8** [comment]
Ayyy nice. I will try this out and see if it works for me too!

**Comment by kronberger-droid** [comment]
Here is a the nix flake which fixed the issue for me.
Essentially just the libPath part...

```
{
  description = "Nix development shell for egui";

  inputs = {
    nixpkgs.url      = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url  = "github:numtide/flake-utils";
    fenix.url        = "github:nix-community/fenix";
    rust-overlay.url = "github:oxalica/rust-overlay";
  };

  outputs = { self, nixpkgs, flake-utils, fenix, rust-overlay, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ fenix.overlays.default rust-overlay.overlays.default ];
        };
        lib = pkgs.lib;

        stableToolchain = fenix.packages.${system}.complete.toolchain;
        rustAnalyzer    = fenix.packages.${system}.latest.rust-analyzer;
        libPath = with pkgs; lib.makeLibraryPath [
          wayland-protocols
          wayland
          libxkbcommon
          libGL
        ];
      in {
        devShells.default = pkgs.mkShell {
          name = "rust-dev-shell";

          buildInputs = with pkgs; lib.flatten [
            stableToolchain
            rustAnalyzer
            cargo-expand
            nushell

            u-config
            wayland
            wayland-protocols
          ];

          shellHook = ''
            echo "Using Rust toolchain: $(rustc --version)"

            export CARGO_HOME="$HOME/.cargo"
            export RUSTUP_HOME="$HOME/.rustup"
            export LD_LIBRARY_PATH="${libPath}"
            mkdir -p "$CARGO_HOME" "$RUSTUP_HOME"

            # Launch nushell as login shell
            exec nu --login
          '';
        };
      }
    );
}
```
