### ISSUE TITLE
Android overlay app

### ISSUE THREAD

**Issue by suprohub** [emilk/egui#5409]
How i can create overlay app? WindowLevel not works on android

**Comment by lucasmerlin** [comment]
I'm not sure what you mean, I think you have to be a bit more specific.

**Comment by suprohub** [comment]
> I'm not sure what you mean, I think you have to be a bit more specific.
 Just type android overlay on google

**Comment by lucasmerlin** [comment]
I don't think this is something we can add to egui/eframe. You'll need to write kotlin code for that. It should probably be possible to render the ui in a floating activity with egui, but it's nothing we can support out of the box.

**Comment by suprohub** [comment]
I think its issue for winit

**Comment by suprohub** [comment]
> I don't think this is something we can add to egui/eframe. You'll need to write kotlin code for that. It should probably be possible to render the ui in a floating activity with egui, but it's nothing we can support out of the box.
We can use jni, but as i say, its more like issue of winit, because window level not works
