### ISSUE TITLE
App icon not showing up on KDE endeavor OS (Arch based) distro.

### ISSUE THREAD

**Issue by CodeCanna** [emilk/egui#5445]
**Describe the bug**
The app logo should appear in the app drawer when the application opens.

**To Reproduce**
1. Run [this](https://github.com/CodeCanna/spacepix) application with `cargo run` on a KDE based system
2. You should see the app logo in the bottom menu bar, but its not showing up for me

**Expected behavior**
The app logo should appear in the app drawer/menubar

**Screenshots**
![sp_screenshot](https://github.com/user-attachments/assets/1cdd5209-a90d-46ed-b482-a6a51b2fbe00)

**Desktop (please complete the following information):**
 - OS: EndeavorOS
 - Browser N/A
 - Version Latest

**Additional context**
This works on Linux Mint, Windows, and FreeBSD, the logo shows up on all of these.

**The code for loading the logo**
```
fn load_icon(path: &str) -> egui::IconData {
  let (icon_rgba, icon_width, icon_height) = {
      let image = image::open(path)
          .expect("Failed to open icon path")
          .into_rgba8();
      let (width, height) = image.dimensions();
      let rgba = image.into_raw();
      (rgba, width, height)
  };

  egui::IconData {
      rgba: icon_rgba,
      width: icon_width,
      height: icon_height,
  }
}
```

**Comment by smoe** [comment]
Likely related to https://github.com/emilk/egui/issues/3992 ?

**Comment by CodeCanna** [comment]
> Likely related to #3992 ?

Yes it is indeed, I confirmed by logging into an X11 session and testing my program, and the Icon is visible.  It does seem to be a Weyland problem.  Closing since this is a known problem.
