### ISSUE TITLE
apt install dependencies

### ISSUE THREAD

**Issue by MarkSwanson** [emilk/egui#545]
Just a fyi to save someone some time:
sudo apt install libxcb-render-util0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev

**Comment by EmbersArc** [comment]
This line is in the readme https://github.com/emilk/egui#demo

**Comment by MarkSwanson** [comment]
Thanks!

**Comment by MarkSwanson** [comment]
fyi I tested the documented apt install instructions on a fresh machine (raspberry pi 4) and it didn't work unless I included libxkbcommon-dev
