### ISSUE TITLE
Bump current release wgpu's version with `wgpu = "23"`

### ISSUE THREAD

**Issue by Chu-4hun** [emilk/egui#5476]
# Current release 0.29.1 is on fe368bacc4a15697e347607e73a56c0299b3d42d `wgpu` is on `22.1.0`

Current commit, have it on  ```version = "23.0.0"``` (latest version is ```23.0.1```)

**please update version on crates**

**Comment by Chu-4hun** [comment]
im here from https://github.com/EmbarkStudios/puffin/pull/234#issuecomment-2543362177 MR

It would be awesome if `puffin_egui` will be updated also

**Comment by emilk** [comment]
just run `cargo update -p wgpu` in your own project
