### ISSUE TITLE
Q: Multiple top-level windows?

### ISSUE THREAD

**Issue by jgarvin** [emilk/egui#552]
I'm not sure if the APIs needed to do this exist for the web backend, but for native is multiple top-level window support a goal? It's something that non-game apps would probably use, since without it multi-monitor use of the same app is pretty inconvenient (you need one big native window to stretch over all your screens). Even for games might be nice for egui to be able to 'pop out' to be in a separate window from the game instead of always being an overlay.

**Comment by mitchmindtree** [comment]
I'm considering starting to use `egui` alongside  [`nannou`](https://nannou.cc) for some of our audiovisual installation work. These often involve multi-screen or multi-projector setups with content split across each, separating the control window from the visualisation window, etc.

Even if there's no real "multi-window" support in `egui`, I'd be satisfied knowing that I could have a unique `Ui` per window without messing up any global state or anything like that. Does that sound feasible with `egui` in its current state?

Great work on the lib btw! I just came across the web demo and was blown away by the list of features :)

**Comment by parasyte** [comment]
AFAIK, supporting multiple windows is mostly the responsibility of the platform implementation. For most users this is `egui_glium`, but it's also true of alternatives like `egui_winit_platform`.

`egui_glium` takes over handling of the windowing subsystem and the main event loop, so it is going to need some work to handle multiple windows.

`egui_winit_platform` puts all those responsibilities into the caller's hands, so it's up to the user to define how they want their windows created and managed. It should be trivial to have as many `Platform` instances as you like with a single event loop using this architecture. Each `platform` gives you its own `CtxRef` when you are ready to render the UI. You just have to be careful in your event loop to update the `platform` using events from the correct window reference.

**Comment by emilk** [comment]
@parasyte is right - adding multi-window support to `egui_glium` is maybe possible, but I don't know. If you have an integration with multiple windows already, then having one `egui::Context` per window is the way to go, and should not produce any problems.

**Comment by parasyte** [comment]
See also #1044

**Comment by emilk** [comment]
`eframe` now support multiple viewports/windows.

The `egui_glium` backend has been moved out to a separate repo (https://github.com/fayalalebrun/egui_glium).
