### ISSUE TITLE
IME input does not working on Linux since v0.29.0

### ISSUE THREAD

**Issue by rew150** [emilk/egui#5544]
**Describe the bug**

Since `v0.29.0` , nothing in the text box will be displayed when typed with IME in Linux and even if I have chosen the word from IME, nothing happened. I tested with both Chinese and Japanese and it's the same

**To Reproduce**
1. create minimal eframe app, insert new font data (for CJK display), and using `egui::ui::Ui::text_edit_singleline()` to create text box.
2. compile for native and run app
3. input `先生` in Japanese (sensei) or Chinese (xiansheng)

**Expected behavior**
The typed word (先生) or intermediate, waiting to be finalized via IME, should be displayed in the textbox. Also, when the word is chosen in IME, that word should appear in the text box.

**Screenshots**

***Before v0.29***
*IME (Japanese)*
![image](https://github.com/user-attachments/assets/5ecdc649-818c-4d5d-88eb-c2923b3a7661)

*IME (Chinese)*
![image](https://github.com/user-attachments/assets/636a15ab-4ddf-438f-8e29-915b516c1366)

*Chosen word*
![image](https://github.com/user-attachments/assets/29379b11-4216-4381-80db-f90b40b35bfe)

***Since v0.29***

![image](https://github.com/user-attachments/assets/46afb6fe-0641-4b51-a8bd-1ad2b8d0ab2b)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 40 (Workstation Edition) x86_64
 - Browser: - (Native)

**Additional context**

 I use mozc in Fedora 40

**Comment by iamazy** [comment]
@rew150 IME is disabled in Linux, you can refer to https://github.com/emilk/egui/pull/5198
