### ISSUE TITLE
`TextEdit::singleline`: `lost_focus` not triggered on enter key

### ISSUE THREAD

**Issue by d4h0** [emilk/egui#565]
Hi,

For some reason, the following code doesn't panic when the enter key is pressed while the text field is focused:

```rust
let mut my_string = String::new();
let response = ui.add(egui::TextEdit::singleline(&mut my_string));
if response.lost_focus() && ui.input().key_pressed(egui::Key::Enter) {
    panic!()
}
```

If I remove `response.lost_focus() &&`, `panic` is executed (but also if the text field isn't focused).

When I press enter, the cursor flashes one time, so something seems to happening, but `lost_focus` isn't triggered.

I'm using `egui_miniquad` (in case this could be relevant).

**Comment by Hirtol** [comment]
To add on to this, for now `response.has_focus()` seems like a suitable alternative, and then subsequently calling `response.surrender_focus()` if you rely on the loss of focus.


For some reason, however, the `response.clicked()` event also triggers when you press Enter, which seems like incorrect behaviour.

**Comment by emilk** [comment]
Good find! The problem is that `Enter` is treated as a click (so you can click selected buttons with enter), and so the TextEdit widget incorrectly thinks it was clicked and should gain focus (even though it just lost it).
