### ISSUE TITLE
Egui will be blocked after adding custom fonts

### ISSUE THREAD

**Issue by Itsusinn** [emilk/egui#571]
When using egui 0.13, I get a black output after adding custom fonts.
The whole program will block at CtxRef::begin_frame.

To be precise, it will block at this line https://github.com/emilk/egui/blob/7c5a2d60c5d000f193bc7b16c5a53c059fee8259/egui/src/context.rs#L578

In egui 0.12, there is no problem with [this approach](https://github.com/emilk/egui/discussions/373)

Here is the minimized project to reproduce the error
https://github.com/Itsusinn/custom-font-bug

**Comment by zu1k** [comment]
I found that no deadlocks occurred, just that when the font file was large (including too many characters) it was very slow.

Very slow processing here:

https://github.com/emilk/egui/blob/94937a33e8b8f1f21165854ec5426e84849131f9/epaint/src/text/font.rs#L205-L207

**Comment by zu1k** [comment]
> https://github.com/emilk/egui/blob/94937a33e8b8f1f21165854ec5426e84849131f9/epaint/src/text/font.rs#L206

I'm not sure if it's the `iterator` or the BTreeSet that's causing the problem, perhaps a combination of both factors ?

**Comment by zu1k** [comment]
I have created a PR to fix it, maybe you could have a try.  @Itsusinn
