### ISSUE TITLE
Don't drag with secondary pointer button by default

### ISSUE THREAD

**Issue by mankinskin** [emilk/egui#578]
For a Context Menu #543 it is natural to use the second mouse button to open it by a click. Currently, when this happens on a draggable element, the right click is registered as a drag (same for left clicks). This is a problem for this feature, because context menus can't be opened on draggable elements. 

In general, I think it is more common to use the left mouse button for initiating drags, anyways, not the right mouse button. Maybe the right mouse button should not register drags at all, by default?

In any case, #547 would still fix this, just wanted to put this up for discussion.

**Comment by emilk** [comment]
I agree that it makes sens to limit dragging windows using the primary mouse button.

**Comment by coderedart** [comment]
just wanted to ask if this would affect future features like selecting multiple items (maybe in a list view sorta widget) by dragging with primary button, where we can choose secondary button to drag windows or such.

**Comment by emilk** [comment]
@coderedart if a widget listens for drags (with `Sense::Drag`) then that wins over the window being moved. So when dragging a slider, you don't drag the window.
