### ISSUE TITLE
TemplateApp freezing after opening a weblink (firefox)

### ISSUE THREAD

**Issue by nyvs** [emilk/egui#580]
I compiled the TemplateApp, clicked on a link in the app.
Firefox opens. I get these errors in the terminal:

```
(firefox:41218): Gtk-WARNING **: 23:18:27.764: Locale not supported by C library.
        Using the fallback 'C' locale.

(/usr/lib/firefox/firefox:41302): Gtk-WARNING **: 23:18:28.305: Locale not supported by C library.
        Using the fallback 'C' locale.

(/usr/lib/firefox/firefox:41359): Gtk-WARNING **: 23:18:28.651: Locale not supported by C library.
        Using the fallback 'C' locale.

(firefox:41218): GLib-GIO-WARNING **: 23:18:28.679: /etc/xdg/kde-mimeapps.list contains a [Added Associations] group, but it is not permitted here.  Only the non-desktop-specific mimeapps.list file may add or remove associations.

(/usr/lib/firefox/firefox:41415): Gtk-WARNING **: 23:18:28.926: Locale not supported by C library.
        Using the fallback 'C' locale.

(/usr/lib/firefox/firefox:41472): Gtk-WARNING **: 23:18:29.309: Locale not supported by C library.
        Using the fallback 'C' locale.
```
(Though I suspect it doesn't have anything to do with the freezing problem)

The window has now become unresponsive.
Trying to interact with the TemplateApp yields a freezing window. 
(Manjaro KDE Plasma)

When I close firefox before interacting with the app, everything works fine.

I guess I need to provide more info, what do you need?

**Comment by emilk** [comment]
`egui_glium` uses the `webbrowser` crate to open links, so maybe try it on its own and/or start a discussion at https://github.com/amodm/webbrowser-rs

**Comment by nyvs** [comment]
I switched to another distro, problem doesn't persist anymore - closing
