### ISSUE TITLE
TopBottomPanel resizing doesn't seem to work

### ISSUE THREAD

**Issue by UditDey** [emilk/egui#581]
I'm new to this library and was experimenting by modifying the template application. If my understanding is right the following code should create a bottom bar that can be resized by dragging:
```
fn update(&mut self, ctx: &egui::CtxRef, frame: &mut epi::Frame<'_>) {
        egui::TopBottomPanel::bottom("bottom_panel")
        .default_height(200.0)
        .resizable(true)
        .show(ctx, |ui| {
            ui.label("Some Text");
        });
}
```
It doesn't seem to work though. The attached video shows what happens:

https://user-images.githubusercontent.com/44467986/126878450-3dd0099c-2a60-420b-8f88-1fe4d012fed9.mp4

The bottom bar stays shrunk to the label's size and when dragged it moves up instead of resizing, and immediately goes back when you release it. Is this a bug or am I using it incorrectly? The online demo has functional resizable panels so I thought I was using it incorrectly. I'm running it via `eframe` like the template application

EDIT:
I added a `CentralPanel` and that had no effect
```
egui::TopBottomPanel::bottom("bottom_panel")
        .resizable(true)
        .show(ctx, |ui| {
            ui.label("Some Text");
        });

        egui::CentralPanel::default().show(ctx, |ui| {
            ui.label("Some Other Text");
        });
```
The bottom panel still doesn't get resized. It drags along with the mouse and immediately returns to its original state when you let go

**Comment by gents83** [comment]
I noticed the same today - the issue is with all widgets that do not "expand" to full available height

**Comment by UditDey** [comment]
So do all the layouts normally shrink down to the size of the child components?

**Comment by gents83** [comment]
> So do all the layouts normally shrink down to the size of the child components?

Not for all of them, but that's what TopBottomPanel does right now :)

**Comment by UditDey** [comment]
Alright thanks, I'm gonna look into creating a custom layout for my use case instead
