### ISSUE TITLE
Theming/styling demo

### ISSUE THREAD

**Issue by Dimev** [emilk/egui#590]
The demo has some examples for theming/styling built in, but it would be nice to have a seperate demo for styling the gui and changing fonts

**Comment by tami5** [comment]
Found this issue while searching for a way to setup text styles and fonts. due to api changes, I no longer know how to setup TextStyle::Heading font size. Anyways, yes a demo would be awesome

**Comment by coderedart** [comment]
There's egui stylist where we can take some inspiration from. It's still on 0.15 if I remember correctly

**Comment by emilk** [comment]
There is a demo for using custom fonts at https://github.com/emilk/egui/blob/master/eframe/examples/custom_font.rs

Making a similar demo calling `ctx.set_style` should be very easy if someone wants to take a stab at tit

**Comment by emilk** [comment]
@tami5 you use https://docs.rs/egui/latest/egui/style/struct.Style.html#structfield.text_styles + `Context::set_style`. If you have some ideas for how to improve the visibility/documentation of this let me know.

**Comment by tami5** [comment]
> @tami5 you use https://docs.rs/egui/latest/egui/style/struct.Style.html#structfield.text_styles + `Context::set_style`. If you have some ideas for how to improve the visibility/documentation of this let me know.

Yah sure, assign it to me. I will drop a pr in few days
