### ISSUE TITLE
Document min versions of rustc/cargo

### ISSUE THREAD

**Issue by icefoxen** [emilk/egui#607]
Namely, Ubuntu 18.04 ships with rustc 1.47 and Debian 11 ships with rustc 1.48, which seem to be too old to build `eframe`.  I get this build error when trying to build `egui_template`:

```
  Downloaded eframe v0.13.1
error: failed to parse manifest at `/home/NEA.com/simon.heath/.cargo/registry/src/github.com-1ecc6299db9ec823/eframe-0.1
3.1/Cargo.toml`

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest
```

This is annoying 'cause I'm trying to build Debian packages out of programs that use `egui`.  :cry:

**Comment by sourcebox** [comment]
Honestly, relying on a rust toolchain that is installed by the distribution's packet manager is not a good idea. At least if you're not runnng a rolling release distribution that is updated quite often. Rust has a 6-week release cycle, so there is a good chance that some crate used in the project will use a new language feature. This is not only valid for egui, but any larger project with a good amount of dependencies.

**Comment by icefoxen** [comment]
Yes, but that sucks and it would be nice to make "document minimum rustc version" normal among crates so that people could at least easily reject things that won't work without spending 20 minutes reading the docs and trying to get examples to work.

**Comment by emilk** [comment]
The minimal rustc version is documented in the first paragraph of https://docs.rs/egui/0.13.1/egui/

I don't know a better place for it.

It would be great to have it as part of `Cargo.toml` so that rustc/cargo could give better error messages.
