### ISSUE TITLE
TextView/TextBox widget

### ISSUE THREAD

**Issue by kotx** [emilk/egui#609]
Basically a TextEdit, but without a mutable reference (so no editing). The main use case for this would be logs or consoles that should be copyable. The `enabled` field of TextEdit does not allow selection (so no copy-paste, etc). Should support scroll as well

**Comment by kotx** [comment]
Possibly related: #319

**Comment by kotx** [comment]
Related: #322

**Comment by emilk** [comment]
This was added just a few days ago in https://github.com/emilk/egui/commit/8d854391df39ebf10ad611edbc432889fc1d1d78
