### ISSUE TITLE
Slider snaps back when text field was focused first

### ISSUE THREAD

**Issue by mk12** [emilk/egui#618]
On the demo page https://emilk.github.io/egui/index.html:

1. Click in the "42º" text field to focus.
2. Click or drag the slider to its left.

Expected outcome: the slider value stays where I moved it.

Actual outcome: it snaps back to its original value. If I try again it works (now that the text field is no longer in focus).

**Comment by Bromeon** [comment]
Short video to illustrate the issue:
https://user-images.githubusercontent.com/708488/135751078-dd6335c2-5377-4a4b-9e17-a97d36f1553f.mp4

**Comment by emilk** [comment]
Thank you for that video @Bromeon, that helped me understand the problem immediately!
