### ISSUE TITLE
dont work in windows 10 arm 

### ISSUE THREAD

**Issue by OElabs-official** [emilk/egui#628]
tested with snapdragon 850 && 810 CPU (galaxy book 2 / Lumia 950 XL) 
gui force closed.

**Comment by emilk** [comment]
@OElabs-official does the [glium](https://github.com/glium/glium) examples work? does the [glow](https://github.com/grovesNL/glow) examples work?

**Comment by OElabs-official** [comment]
> 
> 
> @OElabs-official please check out latest `master` of egui and then go to `egui_demo_app/Cargo.toml` and change lines 13-14 to read:
> 
> ```toml
> # eframe = { version = "0.14.0", path = "../eframe" }
> eframe = { version = "0.14.0", path = "../eframe", default-features = false, features = ["default_fonts", "egui_glow"] }
> ```
> 
> (flip which line is commented)
> 
> Then run `(cd egui_demo_app && cargo run --release)` - does that work for you?




err while >> --release
error: unused import: `glutin::platform::windows::WindowBuilderExtWindows`
 --> egui_glow\src\epi_backend.rs:4:5
  |
4 | use glutin::platform::windows::WindowBuilderExtWindows;

so i deleted this line;
works fine on host <x86-64,win 10>;
 
but same problem;

Err >> NoAvailablePixelFormat

egui_glow\src\epi_backend.rs:48:14

**Comment by AlexApps99** [comment]
What is `glow-main/examples/howto`?
None of the examples we provide link to SDL2, are you sure that even has egui in it?

**Comment by emilk** [comment]
The glium backend is gone, and egui no longer use an sRGB framebuffer, so I'm closing this
