### ISSUE TITLE
(Single line) TextEdit does not lose focus on pressing enter

### ISSUE THREAD

**Issue by sdleffler** [emilk/egui#632]
I tested this on the web demo on my machine, running Firefox on Windows, as well as natively. Makes it difficult to do significant stuff when hitting enter on it, cuz `lost_focus` doesn't fire. :(

**Comment by emilk** [comment]
Duplicate of #565 closed in https://github.com/emilk/egui/commit/2f46b0eb068017df727bc05b42111b8f0dad38de

Please search for similar issues before opening new ones!
