### ISSUE TITLE
UI scales on window resize

### ISSUE THREAD

**Issue by woelper** [emilk/egui#653]
Since https://github.com/emilk/egui/commit/04b3921923df340c2ac5ad884c4b9165a78ada58 resizing a window scales it's contents until the resize operation is complete, causing the contents to look very stretched.
This happens on OSX, I will try to reproduce/test this on other operating systems, too.

**Comment by woelper** [comment]
Thank you for getting back so quickly on this (and for this awesome library by the way). I guess there is sound reasoning behind using `run_return` - do you think it's realistic that this is going to change again in the future, or is this at the mercy of winit?

The reason I ask is that I am currently building tools that might get resized a lot and I am thinking of pinning them to an older commit to be more user friendly, which of course in no good idea in the long run :)

**Comment by emilk** [comment]
@woelper you can try helping @PolyMeilex fix this in winit: https://github.com/emilk/egui/issues/270#issuecomment-907392402

If we manage to fix winit:s `run` vs dialog issue, then we can revert https://github.com/emilk/egui/pull/631, but until then I prioritize supporting file dialogs over nice resize behavior.

We could of course add some feature-flag to `egui_glium/eframe` for switching which event pump to use, but I'd rather avoid that if possible.

**Comment by PolyMeilex** [comment]
Just for reference, here is my winit fork that fixes this: https://github.com/PolyMeilex/winit/commit/e4a0a15fc42496a03b76a633ea9d123209751f39

Here is also a little better approach proposed in an issue: 
https://github.com/rust-windowing/winit/issues/1779#issuecomment-842619910
(Currently not implemented by anyone)

**Comment by woelper** [comment]
@emilk Thank you for the explanation. After reading #631, this makes more sense, I was never expecting an immediate mode UI to work with a file dialog out of the box, so I was using `nfd` and later `rfd` with a channel, which worked very well with imgui-rs and egui. It seems like I can even stop doing that now!

@PolyMeilex Let me know if I can help you somehow! I lack plenty of experience with winit, but I have at least some hardware to test on should that help.

**Comment by emilk** [comment]
We no longer use `run_return`, so this issue is no more

**Comment by woelper** [comment]
Thank you so much @emilk !
