### ISSUE TITLE
Support for Docking

### ISSUE THREAD

**Issue by gbrls** [emilk/egui#655]
Imgui has a docking branch and it's great ([link](https://github.com/ocornut/imgui/issues/2109)). I think it opens up many more applications for the library such as an editor for a small engine or a full desktop app. This is the only reason that I stil use imgui-rs for [my project](https://github.com/gbrls/gdb-FunEnd) and I'd love to make the switch.

**Comment by Ragarnoy** [comment]
I'd really get behind this!

**Comment by coderedart** [comment]
https://github.com/emilk/egui/discussions/424

relevant discussion

**Comment by cirrusone** [comment]
This looks excellent -> https://github.com/lain-dono/egui_docking

**Comment by emilk** [comment]
Wow, that does look neat @cirrusone !

![egui_docking](https://user-images.githubusercontent.com/1148717/180406506-53b9134e-fe50-48b4-8988-60bd4865cd54.gif)

**Comment by Adanos020** [comment]
With the author's consent I forked [egui_docking](https://github.com/lain-dono/egui_docking), added some documentation, and published it on crates.io. https://crates.io/crates/egui_dock

I encountered a few bugs which I'm going to work on when I find time. I'll also appreciate all contributions.

**Comment by boonkerz** [comment]
> With the author's consent I forked [egui_docking](https://github.com/lain-dono/egui_docking), added some documentation, and published it on crates.io. https://crates.io/crates/egui_dock
> 
> I encountered a few bugs which I'm going to work on when I find time. I'll also appreciate all contributions.

it would be nice to add padding in tab body but it's not possible to create issues on fork

**Comment by Adanos020** [comment]
@boonkerz I just enabled issues, thanks for spotting that. Feel free to open one for this.

**Comment by emilk** [comment]
There are two good libraries for docking within a single egui viewport:

* https://github.com/Adanos020/egui_dock
* https://github.com/rerun-io/egui_tiles

For proper support of docking using multiple viewports (e.g. like how tabs in a browser can be detached into its own window, then dragged back in again), I've created this issue:
* https://github.com/rerun-io/egui_tiles/issues/30
