### ISSUE TITLE
How can I get the input event (mouse event) outside of the egui area?

### ISSUE THREAD

**Issue by zu1k** [emilk/egui#656]
I'm trying to create a translator, we can select a sentence then the translator show the result.

I notice that egui provides the ability to get the mouse events, I tested it and found It can only get events occured inside the egui area. I need to get the global mouse events, which means every events including those outsiding egui area.

So I found a crates that provides global mouse events, however I need to process all the event manualy to analysis whether the mouse is moving, which is a little complex. 

I wonder if there is an easier way to modify egui itself or some configuration to allow it return global events, or how to simply reuse egui's code related to mouse event handling to detect movement.

Thanks!

**Comment by iamazy** [comment]
This feature is quite necessary and useful. Hope egui implement this feature. cc @emilk
