### ISSUE TITLE
Support for fullscreen windowing

### ISSUE THREAD

**Issue by jeremymeadows** [emilk/egui#662]
It doesn't appear that egui has support for fullscreen windowing. You can remove window decorations and set the size to fill the whole screen, but that isn't a great solution.
I added a `fullscreen` field to `NativeOptions` which gets passed through to glutin at compile time, but that isn't as useful as being able to change the mode at runtime. If anybody knows a way to get a reference to the `glutin::window::Window` from the egui context, I'd be happy to try to implement it and make a PR.

**Comment by emilk** [comment]
Closed by https://github.com/emilk/egui/pull/1782
