### ISSUE TITLE
Consider using different monospace font for demos

### ISSUE THREAD

**Issue by athre0z** [emilk/egui#664]
Hey there & thanks for creating egui! I've played around with it quite a bit now and came to love it already. 

Recently, I created a small split view application for a toy programming language: half of the screen an editor, the other half an AST view & built it as a wasm application. I then linked it a to a bunch of friends and a common complaint that I got back was about the "terrible monospace font rendering". It appears that, from the (by design) blocky font, people incorrectly inferred that egui simply sucks at rendering monospace. I'm aware of the font-rendering issues in pre-0.14 versions on web, but when asked, people explicitly pointed out that it was the monospace stuff in particular that they disliked. I also remember that this was my first thought when first looking at the markdown editor in the egui demo app.

<img width="1645" alt="Screen Shot 2021-08-28 at 01 48 17" src="https://user-images.githubusercontent.com/6553158/131198761-726b57d1-182d-4255-b91d-9fe9ba632961.png">

While I realize that this is probably a bit controversial and against your personal preferences, I'd suggest changing the default font to a more "standard" looking monospace font.

**Comment by emilk** [comment]
I think this is a good idea - let's collect some suggestions!

The font must have a liberal license (e.g. Open Font License), and the font file should be small (a few hundred kB max).

Nominate some suggestions, ideally with a screenshot, a link and a summary of the license and file size, and then we can pick one!

**Comment by athre0z** [comment]
That's good to hear!vMy personal favorites are these two:

### JetBrains Mono

**License:** SIL Open Font License 1.1
**File size:** 144 KiB (`JetBrainsMonoNL-Regular.ttf`, NL = no ligatures)
**Website:** https://www.jetbrains.com/lp/mono/

<img width="330" alt="Screen Shot 2021-08-28 at 16 44 58" src="https://user-images.githubusercontent.com/6553158/131221816-6695b609-4ae9-44f2-9136-890c4b139b08.png">

### Fira Code

**License:** SIL Open Font License 1.1
**File size:** 299 KiB (`FiraCode-Regular.ttf`)
**Website:** https://github.com/tonsky/FiraCode

<img width="330" alt="Screen Shot 2021-08-28 at 16 47 07" src="https://user-images.githubusercontent.com/6553158/131221870-d33b5fcc-2515-44cf-9129-5d5da0ebda47.png">

Note that this one doesn't have a no-ligatures version, so we're probably wasting a bit of space here (unless you intend to support ligatures). I haven't done that before, but we can prooobably somehow remove these unused characters ourselves (if the license permits it, we'd have to check).

As a general note, I noticed that these fonts compress rather well, e.g. JB Mono goes down to half the size when compressed with LZ4, which is lightning-fast and can have a decoder implemented in <100 lines of Rust. I wonder if creating a proc-macro for compressing these resources & decompressing them at runtime might be worth considering.

**Comment by emilk** [comment]
> As a general note, I noticed that these fonts compress rather well, e.g. JB Mono goes down to half the size when compressed with LZ4, which is lightning-fast and can have a decoder implemented in <100 lines of Rust. I wonder if creating a proc-macro for compressing these resources & decompressing them at runtime might be worth considering.

I'm not sure it's worth it - space is mostly an issue for web, but the .wasm file will already be compressed by the server:

```
❯ curl https://emilk.github.io/egui/egui_demo_app_bg.wasm --silent --write-out "%{size_download}\n" --output /dev/null
3654628

❯ curl https://emilk.github.io/egui/egui_demo_app_bg.wasm --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null
1556882
```

Compressing the font data will make the first number smaller, but likely not the second one.

**Comment by athre0z** [comment]
Yeah good point, I didn't think of transport compression!

**Comment by DrOptix** [comment]
Indeed JetBrains Mono kicks ass I have it set as coding font everywhere

**Comment by emilk** [comment]
I tested a few, and I really like this one: https://github.com/source-foundry/Hack

<img width="196" alt="Screen Shot 2021-10-16 at 15 56 43" src="https://user-images.githubusercontent.com/1148717/137590229-cc9fed4b-7192-4193-a30d-752e748182a9.png">
<img width="645" alt="Screen Shot 2021-10-16 at 15 56 21" src="https://user-images.githubusercontent.com/1148717/137590231-d443b817-ce31-4221-91ea-2643eb623a90.png">

309 kB (compressed to 148 kB), and MIT license.

**Comment by athre0z** [comment]
Looks very decent as well! Reminds me of Microsoft's Consolas.
