### ISSUE TITLE
Firefox CPU usage skyrockets unlike non-WebGL web pages

### ISSUE THREAD

**Issue by meglio** [emilk/egui#67]
I have been exploring the Immediate Mode GUI concept, and I found a few demos for web applications, including emilk/egui.

One thing I noticed is that the CPU usage by Firefox skyrockets when I play with those demos, unliked with any other pages written with using HTML/CSS/JavaScript.

Q1. Why it happens and is this expected?
Q2. What happens if most of the websites I open in 50+ tabs use the Immediate Mode GUI - will Firefox and OS struggle?

Any input appreciated.

Many thanks,
Anton

**Comment by emilk** [comment]
Hi!

No, this is quite unexpected! I have no problems in my version of Firefox running on my Mac.

What platform are you on? Laptop/desktop? What graphics card?

Does it still happen if you scale down the browser window?

What does the `ms / frame` read (left hand side on https://emilk.github.io/egui/)?

**Comment by meglio** [comment]
* Mac OS Big Sur latest update.
* Firefox latest
* MacBook Pro late 2015
* CPU goes quiet ~30 seconds after I switch to another tab.
* ms / frame is always smaller than `5ms`
* looks like sizing the window down helps a bit, but it's difficult to measure

**Comment by emilk** [comment]
Sounds like a GPU-side problem then. My WebGL skills are not great, and I don't really have the time to investigate this right now. There should theoretically be no problem at all with the GPU rendering, but WebGL is weird and maybe there is some subtlety when using large canvases.

If anyone is good at web tools and diving into why large canvases + WebGL is sometimes so slow, that would be greatly appreciated.

**Comment by mrXCray** [comment]
Well, at least confirm, please, that there is no bitcoin miner in your code :)

**Comment by meglio** [comment]
Re WebGL, I'm not that experienced to dig into it, but for sure desktop games run just fine on this Desktop, like e.g. Witness.

**Comment by emilk** [comment]
@meglio you can also clone this repo and run `cargo run --release -p demo_glium` and verify that the exact same Egui demo runs fast when native (as I and epxect it will).

**Comment by meglio** [comment]
Same issue with the Hobogo game at https://emilk.github.io/hobogo/index.html

**Comment by dneumair** [comment]
Hi @meglio,
be sure, that you have hardware acceleration in firefox enabled... At least on windows it is possible to turn it off

**Comment by emilk** [comment]
I've implemented a max-width in `egui_web` now: https://emilk.github.io/egui - does that help @meglio ?

**Comment by emilk** [comment]
Thanks to @not-fl3 I now know this is a bug in Firefox: https://twitter.com/fedor_games/status/1342838418343141381 https://bugzilla.mozilla.org/show_bug.cgi?id=1010527#c0

**Comment by meglio** [comment]
So, let's look at it this way: there is a bug in Firefox that has been there for years, and is still making it impossible to use egui in the browser (one of the major browsers). Kind of being unfortunately ala vendor-locked.

**Comment by emilk** [comment]
I definitely wouldn’t say it is impossible to use egui in Firefox. It just hurts the FPS and adds cpu usage, but it still works pretty well

**Comment by meglio** [comment]
When I tested it, it did not work pretty well, unfortunately :( Adding CPU usage that much just makes it not a viable option.
