### ISSUE TITLE
[bug] window will not be closed after `run_native` returned

### ISSUE THREAD

**Issue by zu1k** [emilk/egui#677]
It looks like the window will not be closed after `run_native` returned.

On windows, I use [this method](https://github.com/bayswaterpc/egui_glium_pure_window_not_closing) to destroy window, however on linux, I don't know how to destroy the window.

_Originally posted by @zu1k in https://github.com/emilk/egui/issues/427#issuecomment-907723675_

**Comment by zu1k** [comment]
the case is: after returning, the program does not exit, and the window will be reopened sometime in the future

**Comment by bayswaterpc** [comment]
I updated my mini example [here ](https://github.com/bayswaterpc/visual_studio_cpp_egui_demo) and can confirm that the window is lingering.

Can I confirm  @zu1k  that you placed that method in the backend.rs run() function?

I had initially identifed this issue on glutin issue [1360](https://github.com/rust-windowing/glutin/issues/1360)

**Comment by zu1k** [comment]
> Can I confirm @zu1k that you placed that method in the backend.rs run() function?

Yes. https://github.com/zu1k/egui/commit/2c8e7871b4680f317b7b3ab7f44254ef68d439b8

**Comment by emilk** [comment]
We no longer use `run_return`, so I think we can close this.
