### ISSUE TITLE
API's for accessing underlying implementation?

### ISSUE THREAD

**Issue by sdfgeoff** [emilk/egui#688]
This is a weird one, but it represents several hours of frustration.

I have two libraries: egui, and one that I wrote. The library that I wrote requires an openGL handle at initialisation and outputs to an openGL texture. 
I created an interface in egui using the template at https://github.com/emilk/egui_template/ as a model. Now I want to run my library and output the texture to the interface of egui. 

As far as I can tell there is no way to get a reference to the underlying draw implementation from an egui app, and there is no way to coerce a GL texture into an egui texture. This is all for a good reason! Egui is intended to be backend agnostic, so it shouldn't matter if you're running in GL or not!
But it leaves me at a loss to know how to proceed. 
> I did manage to get it running by using the egui_glow port mentioned https://github.com/emilk/egui/issues/93#issuecomment-907607337 and modifying the app.setup() and app.render() functions to include the gl reference. However I then got stuck on how to pass a texture back :) 

So this is a request for documentation that answers questions like:
- How do you display a texture in EGUI where the texture resides on the graphics card? (aka is not an array of pixels in RAM)
- How do you create an application that interacts with the GPU without requiring you to write your own backend for EGUI?

--------------------------------------------------

If the answer to either of those is "you don't" then perhaps it would be worth investigating alternate interfaces to eframe/egui_glium/egui_web that allows you to. As far as I can tell the root of the problem is that the TemplateApp's method of:
```
eframe::run_native(Box::new(app), native_options);
```
does not allow your app to have any reference to the implementation behind egui. Ideally I'd like to avoid vendoring exact clones of these crates just to change a handful of function definitions!

**Comment by emilk** [comment]
The short answer is: don’t use eframe. I suggest using egui_miniquad or waiting for egui_glow. egui_glium should also work well, if you follow https://github.com/emilk/egui/blob/master/egui_glium/examples/pure.rs though an example of user textures is missing there.


If all you need is to allocate a texture, then eframe got you covered: https://docs.rs/epi/0.14.0/epi/struct.Frame.html#method.tex_allocator

**Comment by t18b219k** [comment]
you can register glium texture as egui texture using egui_glium eframe doesn't support offscreen rendering
use egui_glium's register_glium_texture()->egui::TextureId 
and give  this Id to egui::Image initalization
