### ISSUE TITLE
High GPU

### ISSUE THREAD

**Issue by kevinxxq** [emilk/egui#689]
Hi All,
I am just running the demo through https://emilk.github.io/egui/index.html#demo
The GPU runs at a high level usage.

![image](https://user-images.githubusercontent.com/55800697/131779100-85b1ab9c-ed34-40f8-b034-95081f42fec7.png)

Did I miss some options or drivers?

The laptop is with Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz   2.11 GHz, with Intel(R) UHD Graphics 620.

Thanks.

**Comment by emilk** [comment]
It seems you have opened every demo window at once, AND turned on continuous mode, so I guess stress testing like that is just a bit too much for a UHD Graphics 620 (or rather not too much, since it does handle it).

Normally you would use the Reactive mode and have only a few things open at once.

**Comment by correabuscar** [comment]
Just want to make a note here for Firefox users that the following two `about:config` settings have to be like this, for the above to work:
 `webgl.disabled`=`false` 
`webgl.enable-webgl2`=`true`.
Otherwise you can see in F12 key (console) these errors:
>  Failed to create WebGL context: WebGL creation failed: 
> *  ()

> Uncaught (in promise) WebGL isn't supported

and

> Failed to create WebGL context: WebGL is currently disabled.
>  Uncaught (in promise) WebGL isn't supported
