### ISSUE TITLE
ComboBox select dialog goes offscreen whenever it is opened too low

### ISSUE THREAD

**Issue by TheSylex** [emilk/egui#693]
Whenever you position a combobox too low on the screen, its select window goes out of the window, like this:
![unknown](https://user-images.githubusercontent.com/69397882/131880129-8928341e-9e33-4c68-9b00-12bd341515f4.png)
Instead it should move upwards to fit.

**Comment by DrOptix** [comment]
For this one I think me need that layout size pre-process mentioned here in #606.

I'm facing the same issue while trying to use `popup::popup_below_widget` to show a popup when I click a button.
Seeing that `ComboBox` uses `popup` internally I tried to fix it.

The idea that I have is to compare `ui.input().screen_rect()` to the rect generated by the `Area` from here:
https://github.com/emilk/egui/blob/5539dbe620f3a184490010a706104de36ba80c3e/egui/src/containers/popup.rs#L275-L310

**Comment by bonsairobo** [comment]
This seems possible without #606. One option is to choose the popup direction based on the y coordinates of box. Upper half of the window means open downwards, lower half means open upwards.
