### ISSUE TITLE
Odd behavior when resizing right side panel

### ISSUE THREAD

**Issue by Ratysz** [emilk/egui#696]
Happens with both `egui` version 0.14.* and latest main. Putting a scroll area into the panel makes it behave as expected; I don't know enough about `egui` to know if this is intended, but it does prevent utilizing panels made up entirely from e.g. labels and buttons.

![XhzSTcdGMs](https://user-images.githubusercontent.com/2969204/132044622-a59eae7f-299e-416e-a489-5d208c0ada72.gif)

```rust
use eframe::epi::Frame;
use egui::CtxRef;

struct App {
    disable_weirdness: bool,
}

impl eframe::epi::App for App {
    fn update(&mut self, ctx: &CtxRef, frame: &mut Frame) {
        egui::SidePanel::right("panel").show(ctx, |ui| {
            let text = if self.disable_weirdness {
                "enable weirdness"
            } else {
                "disable weirdness"
            };
            if ui.button(text).clicked() {
                self.disable_weirdness = !self.disable_weirdness;
            }
            if self.disable_weirdness {
                let scroll_area = egui::ScrollArea::vertical();
                scroll_area.show(ui, |ui| {});
            }
        });
    }

    fn name(&self) -> &str {
        "right side panel bug repro"
    }
}

fn main() {
    let options = eframe::NativeOptions::default();
    eframe::run_native(
        Box::new(App {
            disable_weirdness: false,
        }),
        options,
    );
}
```

**Comment by emilk** [comment]
In egui, `Panels` and Windows auto-shrink. What do you want to happen when you drag that line?

Do you want buttons to become wider? Then use a justified layout:

``` rust
ui.with_layout(Layout::top_down_justified(Align::Center), |ui| {
    ui.button("Look at me, I am becoming so wide!");
});
```

Do you want button to stay the same size, but add some empty space? Then add some empty space at the end of the panel:

``` rust
ui.allocate_space(ui.available_size());
```

Do you want to prevent the panel from being resizable? Then use https://docs.rs/egui/0.14.2/egui/containers/panel/struct.SidePanel.html#method.resizable

---

Yes it looks weird that you can pull out the button and then see them snap back as you release, but this is an artifact of using immediate mode that is very hard to escape.
