### ISSUE TITLE
deprecated for "egui_winit_ash_vk_mem" and publish "egui-winit-ash-integration"

### ISSUE THREAD

**Issue by MatchaChoco010** [emilk/egui#707]
Hi!

I am deprecating the crate "egui_winit_ash_vk_mem" that I maintain, because vk_mem appears to be abandoned for maintenance.

Instead, I have created a crate called [egui-winit-ash-integration](https://github.com/MatchaChoco010/egui-winit-ash-integration).
I would like you to remove egui_winit_ash_vk_mem from the README.md and add egui-winit-ash-integration.

Thank you very much.

**Comment by emilk** [comment]
Thanks for letting me know!
