### ISSUE TITLE
Values marked as `#[serde(skip)]` still overwritten when loading app state.

### ISSUE THREAD

**Issue by the-drunk-coder** [emilk/egui#72]
Hi,

I'm working on an app that has a callback field which should be ignored during saving/loading the app state:

```
#[derive(serde::Deserialize, serde::Serialize)]
pub struct MyApp {
    content: String,
    #[serde(skip)]
    callback: Option<Arc<Mutex<dyn FnMut(&String)>>>,
}
```
Nonetheless, when I configure the app with the callback before calling `egui_glium::run()`, the callback is overwritten when "load" is called.

This happened after the latest update ... before that, the app state was re-loaded manually before calling `run()`. Not sure if there's a good way to handle this ...

**Comment by emilk** [comment]
Hi!

I am still designing how the `trait App` should work in "framework mode" (where egui_glium calls your code), so it's great with feedback like this!

Eventually `egui_glium` should probably call some sort of `fn App::init(...)` after deserializing.

In the meantime, here is one way to solve it:

``` rust
#[derive(serde::Deserialize, serde::Serialize)]
#[serde(default)]
pub struct MyApp {
    content: String,
    #[serde(skip)]
    callback: Arc<Mutex<dyn FnMut(&String)>>,
}

impl Default for MyApp {
    fn default() -> Self {
        Self {
            content: ...,
            callback: ..., // <- set it up here
        }
    }
}
```

Here is another solution:

``` rust
impl egui::app::App for MyApp {
    fn load(&mut self, storage: &dyn egui::app::Storage) {
        let callback = self.callback.take();
        *self = egui::app::get_value(storage, egui::app::APP_KEY).unwrap_or_default();
        self.callback = callback;
    }

    ...
}
```

This is assuming you are using latest `master` of Egui... which is a big assumption, but also a recommendation  :)

(you can take a look at [`egui_template`](https://github.com/emilk/egui_template) to see how to update to the very latest Egui)

**Comment by the-drunk-coder** [comment]
Thanks for the quick answer :) 

Yes, I'm using the latest master, and opted for the second solution. Works great !

**Comment by emilk** [comment]
I'm gonna close this as I think the work-around is good enough for now.
