### ISSUE TITLE
Custom Fragment Shader & Sampler for User Texture

### ISSUE THREAD

**Issue by bpostlethwaite** [emilk/egui#729]
Apologies, this may be more of a naive "help needed" issue. I'm not very familiar with OpenGL or Glium. If I can end up using EGUI I'd definitely Github sponsor ❤️ you and this project if sponsorship is set this up.

I'm trying to build a real-time Spectrograph with egui. I noticed recently there is an example and helper `register_native_texture` which is great as the actual spectrograph is a wrapping texture (glium::uniforms::SamplerWrapFunction::Repeat) with a custom fragment shader for coloring.

I am drawing the texture with a custom SamplerWrapFunction to shift the texture incrementally and only writing one new array of data to the texture as the data streams in real time. I'm using a Fragment Shader to color the texture based on a user selected colormap.

I have not found a great way to integrate these custom glium calls with egui. The best I have now is creating a blank space within the egui interface and passing the coordinates into my glium routines to draw on top of egui in that space.

It looks something like this (code abbreviated)
_event_loop:_
```rust
{
 egui::CentralPanel::default().show(ctx, |ui| {
            egui::Frame::dark_canvas(ui.style()).show(ui, |ui| {

                // creating free space workaround
                let avail_size = ui.available_size();
                let spec_height = avail_size.y * 0.7;
                let (_, place_rect) = ui.allocate_space(egui::Vec2 {
                    x: avail_size.x,
                    y: spec_height,
                });
                
                // fix vertices into  egui free space
                spectrograph.set_vertex_position(place_rect, app_rect);
            });
        });
       
       // new data written into part of texture, offsets used to scroll texture in view
       spectograph.offset = new_offset;
       spectograph.data_texture.write(some_rect, new_data);
}
{
  use glium::Surface as _;
  let mut target = display.draw();

  egui.paint(&display, &mut target, shapes);

  // draw on top of egui within free space
  spectrograph.draw(&mut target);
  target.finish().unwrap();
}
```

_spectrograph.rs:_
```rust

   // incoming egui Coords defining place to draw texture
   pub fn set_vertex_position(&mut self, place_rect: egui::Rect, screen_rect: egui::Rect) {
        let left = -1.0 + place_rect.min.x / screen_rect.max.x * 2.0;
        ...
        self.vertex_position = egui::Rect {min: egui::Pos2 { x: left, y: top }, ...};
   }

   pub fn draw(&mut self, target: &mut glium::Frame) {
        ...
            use glium::Surface as _;
            target
                .draw(
                    &self.rect_vertices, // updated vertices to draw into egui blank space
                    &self.rect_indices,   // these don't change
                    &self.rect_program,  // custom Vertex and Fragment Shaders
                    &uniforms,  // glium MagnifySampler::Nearest & Repeat Samplers to get scrolling behaviour with minimal computational overhead
                    &Default::default(),
                )
                .unwrap();
        }    
}
```
            
Is there a more integrated/elegant way to write into an egui interface with custom graphics?

**Comment by emilk** [comment]
The recommended way is to render to a texture, and display that in egui: https://github.com/emilk/egui#how-do-i-render-3d-stuff-in-an-egui-area

**Comment by bpostlethwaite** [comment]
Thanks. The example linked from that section is static Rust logo. The section, and my problem, is how this looks when you are rendering a scene at 60fps. I've attempted to render into a framebuffer with a texture presented to egui however that hasn't been successful yet.
Perhaps instead of a static Rust logo the example could show what this would look like if the rust logo was generated from a texture, then run through some shaders driven by some incrementor, such that the logo will spin.
It's the combination of the two render pipelines that I'm fighting, not simply displaying an image.

**Comment by emilk** [comment]
I agree it would be great with a full example of this! Hopefully there is some glium example code for render-to-texture you can use.

https://github.com/emilk/egui/blob/master/egui_glium/examples/native_texture.rs is an example of how to use a native glium texture with egui using `register_native_texture`.

If you manage to make it all work, please consider making a PR to add an example!

----

PS: glium is not actively maintained, so you may also consider alternatives, such as [miniquad](https://github.com/not-fl3/miniquad) + [egui-miniquad](https://github.com/not-fl3/egui-miniquad)

**Comment by bpostlethwaite** [comment]
Great thanks, I'll definitely open a PR once I have it working.

**Comment by bpostlethwaite** [comment]
Here is a working example with egui-miniquad: https://github.com/not-fl3/egui-miniquad/pull/29

Thanks for the assistance!
