### ISSUE TITLE
Feature request: File picker

### ISSUE THREAD

**Issue by Walther** [emilk/egui#731]
Thank you for creating such a useful library - it was really quick to get started!

Having a file picker utility widget could be nice to have. Both native platforms and web browsers should have APIs available for opening the appropriate native file select window, that `egui` could probably utilize.

**Comment by Walther** [comment]
Oops, probably a duplicate of https://github.com/emilk/egui/issues/270 - feel free to close if appropriate 🙇‍♂️

**Comment by emilk** [comment]
I think for most people https://github.com/PolyMeilex/rfd should be the default choice. However, if someone wants a file picker widget written in egui, I suggest making that a separate library!

File select on web is more difficult to implement, but drag-and-dropping files onto an egui browser window is already implemented, so hopefully that should satisfy most use cases for now.
