### ISSUE TITLE
Separate serde derives from persistence feature

### ISSUE THREAD

**Issue by jparoz** [emilk/egui#733]
I'm currently working on a small pet project and trying out egui (using eframe) while doing so. I'm making a `Widget` which has a user-configurable `Color32` value, which is working great. I need to serialise this widget, and I am able to do this easily by enabling the `persistence` feature in the dependencies of my `Cargo.toml`.

However, I don't really want all the built-in persistence features. I don't want the window to move to its last recorded place, I don't need my side panel to resize to the previous state, all I want is to turn on the `#[derive(Serialize, Deserialize)]` for `Color32` (and other types). It seems to me that it's currently not possible. I could manually implement `Serialize` and `Deserialize` for my own structs containing an egui type, but this would be inconvenient and ugly compared to deriving.

What I would suggest is to have a new feature named `serde` (or similar), which enables the serde derives for each egui type. Then the existing `persistence` feature can enable the `serde` feature, as well as providing the existing automatic serialisation features.

Alternatively it would be fine to have some sort of eframe configuration to cause egui to not recall different parts of its state. This way I can enable `persistence`, and manually disable the things I don't want to persist.

**Comment by emilk** [comment]
The feature `persistance` exists on both `egui` and `eframe`.

On `egui` it adds `#[derive(Serialize, Deserialize)]` on a bunch of types.
On `eframe` it does the actual persistence (and adds the feature flag to `egui`).

So if your `Cargo.toml` reads:

``` toml
egui = { version = "0.14", features = ["persistence"] }
eframe = { version = "0.14" }
```

It should work as you want it to work.

Reusing the same feature name for the two crates was convenient, but perhaps a bit confusing.

**Comment by TimonPost** [comment]
If I understand the author accurately, he has no difficulties that it does not work just more that the 'persistence' feature flag is used for multiple purposes. 

1. The auto-saving of application state.
2. Implementing serde serialize functionality.

While I understand the initial choice, namely auto-save and persistence functionality occurs with a serialization process, I think it would be better to split the feature flag up. Something like this:

```toml
[features]
persitance = ["serde"]
serialize = []
```

With this, if you want to use serde only with `serialize`, not all persistence logic is immediately activated.

**Comment by jparoz** [comment]
This makes sense. I agree that the naming is confusing, but I now see that the behaviour I wanted is basically already there, just using the one feature name under the two separate crates. I can work with this as a solution, thank you for the help @emilk. This could be closed, although I would be +1 to rename the features to be less confusing.

I will say that using the `Cargo.toml` setup suggested by @emilk causes the `save` method from the `App` trait to not be called on exit. I think I'll move to manually serialising the data I want in the `on_exit` method instead, but it might be nice in some cases to still have access to the `Storage` as provided in `save`. As much as it seems like saving is linked to 'persistence', and so should be linked to the `persistence` feature, in this case I would prefer more fine-grained control.

**Comment by jparoz** [comment]
As I reflect, I think the real issue/misunderstanding that I'm having is which of these `persistence` represents:
1. Turn-key save-everything program state saving, so that all the built-in UI elements just remember what they need to between program runs
2. The ability to manually serialise and recall program state, possibly including some built-in UI state
3. `Serialize` and `Deserialize` impls

I am looking for option 2. It always seemed clear to me that `persistence` was at least in part to enable option 1, and the above workaround gives me option 3. This is fine, I can work my way from there back up to option 2; but if it's possible to enable more fine-grained control of which built-in data is recalled, I think all 3 would be possible.

**Comment by coderedart** [comment]
https://docs.rs/egui/0.14.2/egui/struct.Memory.html
this is what i use for storing my egui state into a egui_cache.json every few seconds.
