### ISSUE TITLE
Plot: Get mouse position

### ISSUE THREAD

**Issue by EmbersArc** [emilk/egui#734]
To use plots interactively, we need to have a way of retrieving the mouse position in plot coordinates.

I'm not sure yet how to do this but can think of two ways that could work.

**1.)** Store the mouse position from the last frame in memory and use a specialized function to retrieve it before drawing the plot again.
```rust
let mut position = Pos2::ZERO;
let plot = Plot::new("plot_name")
    .get_mouse_position(ui, &mut position)
    .text(Text::new(position, "mouse was here"));
ui.add(plot)
```
Pro: Simple
Con: The mouse position always lags behind by one frame.

**2.)** Completely rework how plots are created, using a closure to add the contents.
This idea is based on how [implot-rs](https://github.com/4bb4/implot-rs) works.
```rust
Plot::new("plot_name")
    .build(ui, |plot_ui| {
        let position = plot_ui.mouse_position();
        plot_ui.text(Text::new(position, "mouse IS here"))
    });
```
Pro: Mouse position is available the frame it is needed.
Con: Requires many changes. Not sure if it's going to work.

If anyone has another idea, please let me know.

**Comment by emilk** [comment]
Here is another solution:

``` rust
pub struct PlotResponse {
    /// Interactions etc
    pub response: Response,
    
    /// How to convert to/from screen space coordinates and
    /// the plot (data) coordinate system.
    pub transform: ScreenTransform,

    /// The position of the mouse/touch in the same coordinate system
    /// as the data you are plotting.
    pub pointer_in_plot_coords: Option<Pos2>,

    …
}

impl Plot {
    fn show(self, ui: &mut Ui) -> PlotResponse {
        …
    } 
}

impl Widget for Plot {
    fn ui(self, ui: &mut Ui) -> Response {
        self.show(ui).response
    }
}
```


Usage:

``` rust
let plot = Plot::new(…);
let plot_response = plot.show(ui);
// ui.add(plot); // also works, but doesn't give us as much info back
```

**Comment by jbuckmccready** [comment]
There currently isn't any manual work around to get the bounds/perform the transform now correct? Looking through the code for plot it looks like the `PlotMemory` type stores the bounds and is private.

**Comment by EmbersArc** [comment]
Thanks for the suggestion @emilk! I considered doing it this way but decided against it because it requires the user to store the interaction info between frames. I went with option 2 instead which I think is the most flexible solution and offers room for more complex interaction methods.

**Comment by EmbersArc** [comment]
> Can you perhaps add a motivating example for what kind of interaction you are interested in doing?

With the current PR, you're probably right that just querying the mouse position is not worth the large change. But I was thinking about at some point having more sophisticated interaction methods i.e. not only interact with the plot itself, but also with its items (see https://github.com/emilk/egui/issues/759).

So that within the `plot_ui` callback, each item that is added will have its own response. Might look like this:
```rust
Plot::new("MyPlot").build(ui, |plot_ui| {
    let response = plot_ui.line(self.circle());
    // Just some suggestions:
    let line_hovered = response.hovered();
    // In plot coordinates:
    let line_hover_pos = response.hover_pos();
    let line_drag_delta = response.drag_delta();
})
```

Concerning your suggestion:

> ```rust
> let pointer_coordinate = Plot::State::read_id_source(ui, "My Plot")
>     .and_then(|state| state.pointer_coordinate());
> 
> let mut plot = Plot::new("My Plot");
> ```

Besides being somewhat verbose, this requires the user to specify the name "My Plot" twice (at least I'd mess that up sooner or later), or store it in a variable. Hence suggestion 1 in the first comment. The same would apply for each plot item for which we would like to query the response.

In addition to those points, avoiding the 1-frame delay would be nice. More importantly however, I don't want the user to have to save the interaction between frames. In my experience, just getting the mouse position in plot coordinates is very important and used often, so this should be as simple as possible.

**Comment by crimsondamask** [comment]
@emilk, I think getting the hovered and clicked pointer position in plot coordinates would be very helpful.

**Comment by emilk** [comment]
@EmbersArc thanks, that makes a lot of sense! Basically we need the scope as a context for the coordinate system.

If we want users interacting with items (e.g. clicking them), then we should also think about having the plot be able to add hover-effects to them. We will likely end up in a similar place as with `Ui`: supply a `Sense` with each item, and get a `PlotResponse` for each. But let's not get too ahead of ourselves :)

I'll give https://github.com/emilk/egui/pull/766 a proper review in the coming days, but now I understand and like the shape of it 👍
