### ISSUE TITLE
Suggestion: make the API for basic drawing more prominent/discoverable

### ISSUE THREAD

**Issue by drewm1980** [emilk/egui#740]
Thanks so much for a great UI library!

I just wanted to share an actionable bit of my new user experience. While looking up how to do basic drawing (lines, circles, etc...), I initially went down the wrong path and started using the Plot API. I forget the exact sequence of what I looked at, but I think I searched the issue tracker for geometry related keywords and your recent work on Plot swamped the results. I eventually got back on (what I think is) the right track, i.e. using ui.allocate_painter, the Painter API, egui::Shape, etc... starting from code deep in the drawing demo code, but maybe that can made more discoverable somehow. Maybe just some additional text in the docs, or maybe a simpler "basic drawing" pane in the demo. If you have an idea how you'd want it done, I can take a crack at a MR.

**Comment by emilk** [comment]
Good feedback!

I think adding a section with examples to the crate level docs would be a good idea.

There are already a few demos using the painter functionality, including the demo called "Painting". I'm not sure how to make it much more prominent than that :)

**Comment by drewm1980** [comment]
Yeah... nevermind; the demos are ample. Painter was in fact the demo that got me back on the right direction. Fractal clock in the demo is also doing a lot of line drawing.
