### ISSUE TITLE
File drag and drop with eframe + epi seems broken

### ISSUE THREAD

**Issue by Ell** [emilk/egui#747]
### Discussed in https://github.com/emilk/egui/discussions/744

I'm trying to get file drag and drop working (desktop file -> app window) and none of the events seem to be firing off. I copied the example from https://github.com/emilk/egui/blob/a256ca115bd052a87d1b6c7f83f8a9bcccf088ef/egui_demo_lib/src/wrap_app.rs#L152

My current test:
https://gist.github.com/Ell/09d2a3875375a2c4dc9cba919f382541  

Quick winit test to confirm this works in windows fine https://gist.github.com/Ell/b5f66e74820e8cb86450d7c2b10c8838  

Also set breakpoints on a few events -- all of them BUT the drag and drop events fire off fine. I think something in the way egui renders is blocking drag and drop events from propagating down to winit (wild guess).  

Would love to help debug this more but I'm not really sure where to start, any pointers would be great!

**Comment by Ell** [comment]
Ok turns out `create_display` never gets the "enable drag and drop" bit enabled on windows, passed that in explicitly when running my app and now it works. Not sure if this is intentional so I'll leave this ticket open, but this does seem like an easy fix

**Comment by emilk** [comment]
It's not intentional, so if you have a fix please make a PR for it!
