### ISSUE TITLE
Reactive RunMode broken on Windows 10

### ISSUE THREAD

**Issue by parasyte** [emilk/egui#755]
This was reported in https://github.com/emilk/egui/pull/21#issuecomment-929901028

`git bisect` shows that 04b3921923df340c2ac5ad884c4b9165a78ada58 caused the regression. (Looks like my guess was right!)

**To Reproduce**
1. Run `egui_demo_app` on Windows 10
2. Open the `Backend` panel.
3. Set "Mode" to `Reactive`

**Expected behavior**
With the `Backend` panel open, the "Total frames painted" counter should _not_ be updated until an event is produced. E.g. by moving the mouse.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: `master`

**Comment by parasyte** [comment]
FWIW, [`rfd`](https://docs.rs/rfd) has async file dialogs that work correctly with the current `winit` event loop. This has been discussed in multiple places, including https://github.com/rust-windowing/winit/issues/1779 and https://github.com/EmbarkStudios/nfd2/issues/11

**Comment by emilk** [comment]
Yeah, it is looking more and more like we should revert https://github.com/emilk/egui/commit/04b3921923df340c2ac5ad884c4b9165a78ada58

I'd still love for non-async dialogs to work as well.

I'll take a look at the winit fix provided by @PolyMeilex at https://github.com/PolyMeilex/winit (and ported to winit 0.25 by @vihdzp at https://github.com/OfficialURL/winit)
