### ISSUE TITLE
Scroll "Stick To End": PR Proposal

### ISSUE THREAD

**Issue by bpostlethwaite** [emilk/egui#757]
**Is your feature request related to a problem? Please describe.**
I want to be able to set the scroll direction as _up_ for UIs where content enters from the bottom such as log scrollers, terminals and spectographs etc.

**Describe the solution you'd like**
I will attempt a PR that allows the `ScrollArea` to have a `scroll_direction` attribute. This will basically inverse a few assumption in ScrollArea (maybe more I haven't investigated the blast area)

**Describe alternatives you've considered**
Reframing my problem to have a different UI or ditching Egui (which I don't want to do)

**Additional context**
I can write code so how hard can it be (haha)

@emilk anything I may need to know before diving in and giving this a whirl?

**Comment by emilk** [comment]
Sounds to me like what you want is a feature where if the scroll area is scrolled all the way to the bottom, it should stay scrolled to the very bottom the next frame too, even if there is more content there now (e.g. more log lines has arrived).

If the scroll is not at the bottom, it should stay (the user has scrolled up in the log to read something old).

Does that cover it?

If so I would suggest adding something like a `stick_to_bottom` boolean for this setting. "Reverse scroll direction" sounds like something completely different to my ears.

**Comment by bpostlethwaite** [comment]
Ok maybe `stick_to_bottom_right: [bool; 2]` to cover the horizontal scroll case too. I'll try this route thanks!

**Comment by bpostlethwaite** [comment]
PR here https://github.com/emilk/egui/pull/765

**Comment by AlexApps99** [comment]
I need something like this for my egui `log` backend that I started hacking together today
![image](https://user-images.githubusercontent.com/30854646/135992102-b8fcd63d-3c8b-4176-bdd4-141967be8b50.png)
:+1:
