### ISSUE TITLE
Sliders width doesn't seem to include the input box

### ISSUE THREAD

**Issue by AlexEne** [emilk/egui#76]
I am trying to add a slider and I just noticed they have an input box where the value is displayed.
However, this doesn't seem to always show.

Using this code it is visible:
```rust
craft_to_columns[1].add(
    egui::Slider::u32(&mut workbench_data.craft_to_count, 1..=20)
        .text("Craft to"),
    );
```
And it appears:
![image](https://user-images.githubusercontent.com/5849037/102991788-d4b00c80-4511-11eb-915e-4955c0377ab9.png)

Setting the text to `""` makes it dissapear:
![image](https://user-images.githubusercontent.com/5849037/102991820-e85b7300-4511-11eb-9e3e-332f6bd0c581.png)

It's also worth noting that the first example, the `"Craft to"` doesn't expand the column width either (you can see just the `C`).

**Comment by AlexEne** [comment]
This may just also be because I'm using the columns api, I remember you mentioned it's not quite ready and I will try the proposed alternative to do:
```rust
ui.horizontal(|ui|{
    ui.vertical(|ui| first_column(ui));
    ui.separator();
    ui.vertical(|ui| second_column(ui));
    ...
});
```

**Comment by emilk** [comment]
This is definitely because of `ui.columns`, since that function does not allow the containing UI to properly expand to fit the contents of the columns. I will deprecate it in the next version of Egui.

As for the overlap in your second example code. Try setting some min/max widths of the columns:


``` rust
ui.horizontal(|ui| {
    ui.vertical(|ui| {
        ui.set_max_width(300.0);
        first_column(ui);
    });
    ui.serparator();
    ui.vertical(|ui| {
        ui.set_min_width(200.0);
        first_column(ui);
    });
    ...
});
```
