### ISSUE TITLE
Additional Linux dependencies now required?

### ISSUE THREAD

**Issue by sourcebox** [emilk/egui#760]
When building via GitHub CI using the ubuntu-18.04 image, I had to install 3 additional packages to make it work:
- libpango1.0-dev 
- libatk1.0-dev 
- libgtk-3-dev

If this is a requirement from now on, it should be mentioned somewhere in the docs.

**Comment by sourcebox** [comment]
Ok, after having a look at the output of `cargo tree` I think, I'm wrong. These dependencies seems to be related to the `rfd` crate I use. It's only a little bit strange that the build failed on compiling `egui-winit`, that was a little bit misleading.

**Comment by emilk** [comment]
those are required to build the `file_dialog` example
