### ISSUE TITLE
Resizing window changes some widgets size whereas it shouldn't

### ISSUE THREAD

**Issue by GuillaumeGomez** [emilk/egui#773]
A small video of the bug:

https://user-images.githubusercontent.com/3050060/136276719-671ba2e4-45ad-4eba-aff5-657a714248ea.mp4

The code I used:

```rust
egui::Window::new("Character").collapsible(false).show(&egui_ctx, |ui| {
    let player = &players[0];

    ui.label("Character imperio");
    ui.separator();

    egui::Grid::new("chracter_infos").show(ui, |ui| {
        ui.label("Level");
        ui.label(&player.level.to_string());
        ui.end_row();

        ui.label("Experience");
        ui.label(&format!("{} / {}", player.xp, player.xp_to_next_level));
        ui.end_row();

        ui.label("Health");
        ui.label(&player.health.to_string());
        ui.end_row();

        ui.label("Stamina");
        ui.label(&player.stamina.to_string());
        ui.end_row();

        ui.label("Mana");
        ui.label(&player.mana.to_string());
        ui.end_row();
    });
});
```

Thanks a lot for this crate, it's really great!

**Comment by Bromeon** [comment]
Also happens in the Table Test demo in latest `master` (commit e4aa1e6e1ac000c83c3bec66f2b260e5b8881f0e).
What's interesting is that it resizes one, but not all separators:

https://user-images.githubusercontent.com/708488/150124462-2a1c4236-a1a9-4dd0-acfd-a1c84622899a.mp4

<br>
A similar, but maybe not the same issue: #762

**Comment by emilk** [comment]
This is a consequence of immediate mode. You make the window narrower, so all contained widgets try to fit within this smaller size. The first few widgets can fit, but the later can't, so the window expands to fit the wider widgets.

I see no obvious way of fixing this except for [multipass layout](https://github.com/emilk/egui/issues/843).

**Comment by emilk** [comment]
Closed in favor of

* https://github.com/emilk/egui/issues/843
