### ISSUE TITLE
eframe apps crash on arch linux

### ISSUE THREAD

**Issue by XakepSDK** [emilk/egui#798]
Please make sure there is not already a similar bug report!

**Describe the bug**
ehttp example crashes on Arch Linux https://github.com/emilk/ehttp/issues/3
egui_demo_app crashes on Arch Linux
I tried nightly and stable compiler.

```
cargo run --release -p egui_demo_app
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/egui_demo_app`
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
egui_demo_app: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

**To Reproduce**
1. `git clone https://github.com/emilk/egui.git`
2. `cd egui`
3. `cargo run --release -p egui_demo_app`

**Expected behavior**
App does not crash

**Desktop (please complete the following information):**
Operating System: Arch Linux
Kernel Version: 5.14.12-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-4790K CPU @ 4.00GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4600

**Additional context**
Sometimes app does not crash. Probably race condition.

**Comment by darthdeus** [comment]
I'm not sure how helpful this is, but I'm running Arch Linux and it doesn't crash for me. I've also been using egui on desktop for a couple of weeks and haven't had a single crash.

Kernel: 5.10.73-1-lts
CPU: Amd Ryzen 9 3900X
Memory: 64GB RAM
GPU: Nvidia GTX 1080ti

**Comment by XakepSDK** [comment]
https://github.com/rust-windowing/glutin/issues/1034
Fix: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/12006
