### ISSUE TITLE
ScrollAreas interact strangely with ui.horizontal()

### ISSUE THREAD

**Issue by bjoern-j** [emilk/egui#809]
Using more than one `ScrollArea` inside of a `horizontal` container doesn't work correctly - only the contents of the first scroll area are rendered, and the scroll bar shown never moves even when scrolling.

If using only one scroll area inside the `horizontal`, various things go wrong depending on whether it is the first or the second element that's wrapped in the `ScrollArea`, but it's never as expected either.

**To Reproduce**
Compile and execute the following code: 

```rust
use eframe::{ epi, egui };
use egui::{ ScrollArea };

fn main() {
    eframe::run_native(Box::new(App::new()), eframe::NativeOptions::default());
}

struct App {
}

impl App {
    pub fn new() -> Self {
        App {  
        }
    }
}

impl epi::App for App {
    fn update(&mut self, ctx: &egui::CtxRef, frame: &mut epi::Frame<'_>) {
        egui::CentralPanel::default().show(ctx, |ui| {
            ui.horizontal_top(|ui| {
                ScrollArea::auto_sized().id_source(1).show(ui, |ui| {
                    ui.label("a\nb\nc\nd\ne\nf\ng\nh\ni\nj\nk\nl\nm\nn\no\np\nq\nr\ns\nt\nu\nv\nw\nx\ny\nz");
                });
                ScrollArea::auto_sized().id_source(2).show(ui, |ui| {
                    ui.label("a\nb\nc\nd\ne\nf\ng\nh\ni\nj\nk\nl\nm\nn\no\np\nq\nr\ns\nt\nu\nv\nw\nx\ny\nz\nSecond");
                })                
            });
        });
    }

    fn name(&self) -> &str {
        "Test"
    }
}
```
Then shrink the window enough that the labels (should) become scrollable.

**Expected behavior**
I expected the text in both labels to be visible and independently scrollable, with two scrollbars visible - one between the two labels, one at the right edge.

**Screenshots**
![image](https://user-images.githubusercontent.com/43930632/137640930-e727903b-8947-4a47-9864-eb3749b49b5a.png)
As you can see, only the first of the two labels is shown, and the scroll bar looks like the scroll area is at its top, but the label is scrolled all the way to its bottom. Screenshot is from compiling and executing on Windows 10 with current stable Rust.
![image](https://user-images.githubusercontent.com/43930632/137641026-cdc08e99-c995-4e31-a6eb-15a6ef076eea.png)
And this happens if we comment out the first `ScrollArea`: Both labels are shown and the second one can be scrolled, but we can't scroll all the way down - this is as far as scrolling down will go (and this is the full size of the window, I didn't clip it).

It seems the `ScrollArea`s aren't really respecting that they're inside a `ui.horizontal` call?

**Comment by emilk** [comment]
I tried your code on latest `main`, and the good news is it seems to work as it should! The `ScrollArea` has been worked on a lot since the last egui release.
