### ISSUE TITLE
glow wasm backend

### ISSUE THREAD

**Issue by leviska** [emilk/egui#837]
I've seen your recent PR with glow backend, and it looks very nice! 

But I really hoped that with glow there will be (at least some basic) support for glow wasm (web-sys) target also, but it seems, that glutin is required for glow. 

I would really appreciate it if you'd made some basic support for wasm with glow.

As far as I understand, rendering side should be easily done, because glow is (kinda) similar on web and native sides.

Input is the harder problem, and I will be satisfied at least with just an ability to pass inputs yourself (and rendering done with glow). As I understand, I can't do it right now(?)

**Comment by AlexApps99** [comment]
Have a look at #852, it seems to be an early work in progress, but it would certainly close this issue.

**Comment by leviska** [comment]
Thanks
I'm not in a hurry, so I'll wait for some unified solution, 852 looks very promising

**Comment by t18b219k** [comment]
Let's try #852 
Current test status
* OpenGL 2.1 + (same as glium and glow)(on Ryzen 5 5500U iGPU)
* WebGL1 (same as web) (on servo)
* WebGL1+sRGB (same as web)(on webgl2 disabled firefox with angle and native GL)
* WebGL2 (same as web)(on firefox , edge,firefox android)

and report bugs.
https://github.com/t18b219k/egui.git

**Comment by t18b219k** [comment]
let's close this issue

**Comment by emilk** [comment]
Closed by https://github.com/emilk/egui/pull/868
