### ISSUE TITLE
`drag_window` scuffed even on Windows

### ISSUE THREAD

**Issue by CAD97** [emilk/egui#846]
**Describe the bug**

https://user-images.githubusercontent.com/5992217/138809615-738f3334-7306-4fab-81c7-1bbabcdddedd.mp4

**Expected behavior**

Either:

- A clean drag, or
- The documentation to note that it's awkward on Windows as well as macOS and impossible on the web

**Desktop (please complete the following information):**
 - OS: Microsoft Windows (10 Education) Version 21H1 (OS Build 19043.1288)

**Additional context**

My original code

```rust
impl epi::App for _ {
    fn update(&mut self, ctx: &egui::CtxRef, frame: &mut epi::Frame<'_>) {
        let InnerResponse { response, .. } =
            egui::TopBottomPanel::top("top_toolbar").show(ctx, |ui| {
                egui::warn_if_debug_build(ui);
            });

        if response.hovered() {
            frame.drag_window();
        }

        egui::CentralPanel::default().show(ctx, |ui| {
            ui.label("Hello, world");
        });
    }
```

was even more scuffed, never leaving the jitter phase. Funnily enough, it's jittery enough that it triggers Windows's "wiggle a window around to minimize all other windows" feature, even if I'm moving my cursor smoothly.

**Comment by AlexxxRu** [comment]
@CAD97 Hi, I have the same trouble on my Windows. 
I've created PR with the fix. Can you check it for your case?

More info here:
https://github.com/emilk/egui/issues/943
