### ISSUE TITLE
eframe size from elements in ScrollArea

### ISSUE THREAD

**Issue by Stefan2409** [emilk/egui#851]
Hello! I'm having the following problem in regard of sizing in an ScrollArea Widget from eframe:

If I create a ScrollArea with items painted using a for loop like so:

```rust
ScrollArea::vertical().auto_shrink(false; 2).show(ui, |ui | {
  for a in &items {
    ui.add_space(5.);
    ui.colored_label(white, a.title);
    ui.add_space(5.);
    ui.colored_label(cyan, a.desc);
    ui.add_space(5.);
    ui.add(Separator::default());
  }
});
```
the first element will always render the whole ScrollArea size. 
![error](https://user-images.githubusercontent.com/17899913/139278890-d004de0c-21c4-44ff-8c9b-1eefe9ecf000.jpg)

it should look like this:
![right](https://user-images.githubusercontent.com/17899913/139278986-3030ea97-ad81-4577-9a99-e56e471ff8bf.jpg)

**Comment by emilk** [comment]
Can you please post a minimal reproduce of the problem?

I just tried putting this inside of a `CentralPanel` and it worked as expected:

``` rust

            egui::ScrollArea::vertical()
                .auto_shrink([false; 2])
                .show(ui, |ui| {
                    for i in 0..3 {
                        ui.add_space(5.);
                        ui.label("First");
                        ui.add_space(5.);
                        ui.label("Second");
                        ui.add_space(5.);
                        ui.add(egui::Separator::default());
                    }
                });
```
