### ISSUE TITLE
Allow specifying font index when loading a font file

### ISSUE THREAD

**Issue by 7sDream** [emilk/egui#853]
I try to let my egui app to use system font.

I can use some font query/loading library to find the font location and read it as binary data, however, it's a ttc file(for example, Microsoft YaHei), so egui report the data a invalid when parsing.

It seems ab_glyph do support collection, by using [FontRef::try_from_slice_and_index](https://docs.rs/ab_glyph/0.2.11/ab_glyph/struct.FontRef.html#method.try_from_slice_and_index), so any idea how can I use ttc/otc ffont file as custom font in egui?

## update

Maybe there is some bug in the font loading library I used.

I changed from [font-loader](https://github.com/matprec/rust-font-loader) to [fontdb](https://github.com/RazrFalcon/fontdb), and now it's working, no `invalid font` report.

But, IIRC,  font loading library gives whole file content, and because I can't pass the font face index to egui, current it will always using the font face at index 0, which means when using ttc/otf, the render result may not be as expected.

<details>
<summary>For example, Helvetica Neue(Normal style) is in index 10</summary>
<img width="1301" src="https://user-images.githubusercontent.com/7822577/139451426-57271b62-a023-4d4c-b8ef-124861eb63bc.png">
</details>

**Comment by emilk** [comment]
If you could specify the face index in `epaint::FontDefinitions` (together with the `FontData`), would that solve the problem for you?

**Comment by 7sDream** [comment]
Yes, I think add a `font_face_index: HashMap<String, usize>` field in `FontDefinitions` (with the same key in `font_data`, values is the index) is a feasible solution.

Considering compatibility, a default value of 0 can be used when the index cannot be found in this field.

**Comment by emilk** [comment]
It seems `ab_glyph::FontArc` lacks the convenience of `try_from_vec_and_index` and `try_from_slice_and_index`. If you make a PR to `ab_glyph` to add those I can hook them up in egui later!

**Comment by parasyte** [comment]
`FontArc` does implement `From<FontRef>` though. That should be enough?

**Comment by emilk** [comment]
Good point @parasyte - I made a PR; please try it out @7sDream !

**Comment by 7sDream** [comment]
Thank you! I can try this pr tonight, after work
