### ISSUE TITLE
Does CtxRef need to exist?

### ISSUE THREAD

**Issue by aloucks** [emilk/egui#861]
Have you considered taking `&Arc<Context>` as the self receiver? 

e.g:
```rust
impl Context {
    fn begin_frame(self: &Arc<Context>, new_input: RawInput) {
        // ..
    }
}
```

**Comment by emilk** [comment]
I did use `Arc<Context>` early on but it has two downsides:

* everyone needs to have `use std::sync::Arc;` in there file, or use the very verbose `std::sync::Arc<Context>`
* it prevents us from changing `Arc` to something else. For instance, with the `single_threaded` feature flag to egui, we should probably change it to `Rc` for performance reasons.
