### ISSUE TITLE
Secondary click on mobile

### ISSUE THREAD

**Issue by mankinskin** [emilk/egui#865]
Recently, context menus got added, but they can't be used on mobile because there is no way to perform a secondary click. For a live example try [my graph_app project](https://mankinskin.github.io/graph_app) on mobile (context menu should be available on background panel).

Usually, a long tap is interpreted as a secondary click. The default context menu may not be suitable for mobile, because it is too small, but being able to trigger it with the same code as on desktop is a first step for bringing this feature.

**Comment by mankinskin** [comment]
This may collide with the long tap from #501 .. This is also a problem on desktop web, where the native context menu is overridden because egui catches the mouse events. But I am unsure if this is really circumventable, because not all platforms have a native context menu, so I guess the best egui can do is try to create a native context menu when asked to and if one exists. This could allow us to use native context menus on mobile.

**Comment by emilk** [comment]
It's unclear how to best implement this.

Should `egui_web` interpret any long-press touch as a secondary mouse click? Or should egui do so, using the touch events it receives? What happens when one wants to drag something?

Anyone wants to try experimenting with this?

**Comment by mankinskin** [comment]
I wanted to try to implement this some time, but I can't say when I want to start yet.. most probably a drag event will only be created when the pointer moves out of a fixed radius or something similar. Might do some research about how this is usually implemented.

Another thing is that the distinction between mouse click and touch screen touch seems to sometimes disappear in egui.. I am not sure but we might need to make that more clear to prevent secondary clicks being triggered when holding the left mouse button down. In other words, the long tap should not apply for left mouse button clicks.
