### ISSUE TITLE
Don't handle alt-f4

### ISSUE THREAD

**Issue by Kyuuhachi** [emilk/egui#877]
On both Windows and Linux (not sure about Mac), alt-f4 is translated into window close events by the window manager, and thus need not be handled by individual applications. Also, many Linux environments can be configured to not use alt-f4 at all (I use win-X for example). In those cases, handling alt-f4 inside applications is directly detrimental to the user experience, as it is different from just about every other application on the system.

**Comment by emilk** [comment]
Good to know! Yeah, let's remove it then.

On mac one has to manually opt-in to Cmd-Q (surprisingly enough), that's why I assumed it was the same on Windows/Linux.

**Comment by emilk** [comment]
Oh, checking for `Cmd-Q` is no longer needed on mac either. This must have changed when I upgraded winit!
