### ISSUE TITLE
RGB color chooser resets hue to red when set to gray

### ISSUE THREAD

**Issue by Kyuuhachi** [emilk/egui#884]
When a RGB color chooser (for example via `color_edit_button_rgb`) is set to a gray shade (the left or bottom edges), the hue is changed to red. Presumably this is because the color is stored in the user-provided variable, which is RGB and thus cannot store the hue in that case. The best solution I can think of is having the widget store the hue separately (only used if the color is grayscale).

**Comment by emilk** [comment]
This is already implemented for `color_edit_button_rgba_&`, just not for `color_edit_button_rgb` (yet) due to laziness.
