### ISSUE TITLE
Axis legends for Plots

### ISSUE THREAD

**Issue by jossriLDR** [emilk/egui#889]
I think there is no 'native' way to add x and y axis legends.
This is one of the most basic features of plotting and should be added (and also be demonstrated in the web demo).

Any suggestions how to achieve this (maybe even workarounds)?

Other than this, I can't figure out how to rotate labels. #428 refers to this but the mentioned commit 
a0f5d7e is in another fork of this repo.

**Comment by JohannesProgrammiert** [comment]
## Question to the maintainers @emilk @nknotts 

I am currently working on the plot library. Labels and ticks generally work as expected. One remaining challenge is calculating the y-axis label width for the widget layout (marked blue in the picture):

![egui_legend](https://user-images.githubusercontent.com/80203331/201482904-af617cef-5a51-4e5a-adf8-71cfa0f420d2.png)

Part of the solution is that the x-axis label height is constant

### Idea

1. Layout the widget in y-direction
2. Make the plot grid in y-direction (needs screen-to-plot and plot-to-screen transformation in 1D)
3. Initialize the galleys for y-ticks and calculate maximum width
4. Do the remaining layout

However, I noticed transformation between plot space and screen space are rather limited and non-standard/'manual' in the current state. I know that [`euclid`](https://docs.rs/euclid/latest/euclid/) makes such transformations easy and has an intuitive API. On a quick glance, it even might be suitable to replace the `emath` library completely.

Implementing basic linear algebra myself is cumbersome and and is not the task I want to focus on now.

### My questions:

* why don't you use that or another widely known crate that provides the required functionality?
* may I add `euclid` as dependency to `egui` and refactor the plot-to-screen transformations in `eplot`?

**Comment by nknotts** [comment]
@JohannesProgrammiert I am not a maintainer, but this is exactly what I am looking for! Great work.

**Comment by Pardoxa** [comment]
I would really love to have this functionality as labeling your axis is kind of essential. So I'd like to +1 this feature request

**Comment by jakkosdev** [comment]
@JohannesProgrammiert that looks great!

I'd love to have this functionality, so +1 too

**Comment by wolro** [comment]
Thank you for your efforts! I am currently slowly introducing Rust / egui for easy-to-deploy data acquisition and monitoring tools at my workplace, and the lack of axis labels and (to a lesser degree) axis ticks outside the plot are giving me a hard time convincing my fellow Pythonistas :-)

Otherwise, egui + plot is just wonderful.

**Comment by JohannesProgrammiert** [comment]
I am glad you like it. Since I didn't receive a response regarding the calculation of the y-label width (see above) I simply use a constant width now. It can be set manually via API else a default width is used and I think it is ok for now.

The PR is ready for review.
