### ISSUE TITLE
Invalid clip rect for the multiline text widget

### ISSUE THREAD

**Issue by Vlad2001MFS** [emilk/egui#89]
The left edge of the multiline text widget is always invisible if I enable the glScissor with a clip rect from the egui.
`clip_rect.min.x` is always +2 from the valid value. The valid value is calculated from vertices for the rendering of a job.

![image](https://user-images.githubusercontent.com/11822153/103431218-dfd3fe00-4bdd-11eb-9eac-65dc8e5f7530.png)

My code to rendering the UI is very similar to egui_glium's painter.

It is really a bug or I am stupid?

OS: Win10 x64
Rust: 1.49

**Comment by emilk** [comment]
Can you try out the code using an existing backend, such as `egui_glium` (or the brand new `eframe`)? If the bug disappears then the bug is likely in your integration, but if it persists it is definitely a bug in `egui`.

**Comment by Vlad2001MFS** [comment]
I tried it. The bug does not disappear.
I cloned the egui repository and build a changed eframe's HelloWorld:
```Rust
use eframe::{egui, epi};

struct MyApp {
    name: String,
    age: u32,
}

impl Default for MyApp {
    fn default() -> Self {
        Self {
            name: "Arthur".to_owned(),
            age: 42,
        }
    }
}

impl epi::App for MyApp {
    fn name(&self) -> &str {
        "My Egui App"
    }

    fn update(&mut self, ctx: &egui::CtxRef, frame: &mut epi::Frame<'_>) {
        let Self { name, age } = self;
        
        egui::Window::new("TestWindow").auto_sized().show(ctx, |ui| {
            ui.text_edit_multiline(name);
            if ui.button("TestButton").clicked {
                println!("TestButton is clicked! ### {}", name);
            }

        });

        // Resize the native window to be just the size we need it to be:
        frame.set_window_size(ctx.used_size());
    }
}

fn main() {
    eframe::run_native(Box::new(MyApp::default()));
}
```

The resulting image is wrong:
![image](https://user-images.githubusercontent.com/11822153/103477158-dbba0300-4dcc-11eb-9f94-27a4600ff458.png)

I tested on the AMD Vega 8 and GTX 1050.

**Comment by emilk** [comment]
Thanks @Vlad2001MFS - I've located the problem and working on a solution
