### ISSUE TITLE
Showing multiple tooltips at different locations

### ISSUE THREAD

**Issue by zylkowski** [emilk/egui#890]
**Is your feature request related to a problem? Please describe.**
When trying to render multiple tooltips at once they all have to be in the same location.

**Describe the solution you'd like**
Allow rendering multiple tooltips at different locations.

**Describe alternatives you've considered**
Hacky solution would be to render multiple windows instead of tooltips.

**Comment by Friz64** [comment]
I am affected by this and want to try working on a fix.

Are there any advantages to tooltip stacking? Should tooltip stacking be removed entirely? And if not, how should the API look for it? - Should you be able to only stack certain tooltips but not others?

**Comment by Friz64** [comment]
Disregard my last comment, i realized my problem was that i was abusing tooltips, not using them for their intended use case. I solved my problem with custom `Area`s together with `Frame::popup`.
