### ISSUE TITLE
Improved plot interaction methods

### ISSUE THREAD

**Issue by EmbersArc** [emilk/egui#891]
#766 has just been merged and is usable, I'd like to add the following features next:

* Access to `Ui` (or the context?) inside the closure as well. Either through the `plot_ui` struct or as a second argument.
* A `plot_to_screen` conversion, to enable custom drawing in screen coordinates based on items in the plot.
* A way to get the current plot bounds.
* Fix the `plot_from_screen` function. Pretty sure I messed up hard when writing it and it likely does not work as expected right now.

**Comment by emilk** [comment]
Access to `Ui` (at least to a `&mut Ui`) seems like a dangerous footgun to me, as that will invariable lead to users doing stuff like

``` rust
Plot::new(…).show(|ui, plot_ui| {
    ui.label("Where will this end up?");
});
```

I think a `plot_ui.ctx()` accessor to get a `&CtxRef` makes sense though.
