### ISSUE TITLE
Click-dragging with the mouse on label in the Sliders-demo page gives strange results

### ISSUE THREAD

**Issue by Goffen** [emilk/egui#895]
**Describe the bug**
Clicking-holding down the mouse button on the label while going left or right with the mouse gives very wierd results.

**To Reproduce**
1. Got to [demo page](https://emilk.github.io/egui/index.html#demo)
2. Click on "Sliders"
3. Click-hold and move mouse on the field next to "right"

**Expected behavior**
The slider to slide and not jump around.

**Screenshots**

![slider_problems](https://user-images.githubusercontent.com/1148718/141765306-889d00cf-2ed1-4ed0-ac80-551cf22040ca.gif)

**Desktop (please complete the following information):**
 - Browser  Chrome
 - Version  95

**Comment by emilk** [comment]
This is a feature, not a bug. You can drag the slider, or the value. Dragging the value (or clicking it) can let you enter values outside the slider range (if this has been enabled with `clamp_to_range(false)`)
