### ISSUE TITLE
Spooky "Code example" window creeping up when moving the mouse

### ISSUE THREAD

**Issue by Goffen** [emilk/egui#897]
**Describe the bug**
If you resize a window and put in the bottom of the screen. Moving the mouse makes it creep up.

**To Reproduce**
1. Got to demo page
2. Open "Code example"
3. Resize it, reduce the height
4. Move mouse

**Expected behavior**
It to stay the way I put it?

**Screenshots**
![spooky_popout](https://user-images.githubusercontent.com/1148718/141771325-0e715015-c991-4381-aee7-7eb4eb38d1b9.gif)

### Desktop

Browser: Chrome
Version: 95

**Comment by YgorSouza** [comment]
I think this has been fixed.
