### ISSUE TITLE
Non-interactable Area shouldn't capture pointer

### ISSUE THREAD

**Issue by JMS55** [emilk/egui#898]
**Is your feature request related to a problem? Please describe.**
Using an area with `interactable(false)` captures the pointer when clicked on.

**Describe the solution you'd like**
Using an area with `interactable(false)` should not capture the pointer when clicked on.

**Additional context**
I'm trying to replace imgui with egui for my game's UI https://github.com/JMS55/sandbox#sandbox.

**Comment by emilk** [comment]
What do you mean by "capture"? That `wants_pointer_input` returns `true`?

**Comment by JMS55** [comment]
Sorry for the late response, I missed this earlier.

Yes, `wants_pointer_input()` returns true, when I want it to be false when clicking on that area.

**Comment by coderedart** [comment]
https://github.com/emilk/egui/pull/1240 is done, so this could be closed i think

**Comment by emilk** [comment]
Closed by https://github.com/emilk/egui/pull/1240

(thanks for the reminder @coderedart)
