### ISSUE TITLE
Horizontal layout does not take into account padding

### ISSUE THREAD

**Issue by JMS55** [emilk/egui#900]
Widgets with padding are not properly centered on the Y-axis when using a horizontal layout. Removing the padding fixes this.

![image](https://user-images.githubusercontent.com/47158642/142127077-fc268e79-87c6-4d74-a61c-d1a743b1ba60.png)

```rust
Area::new("ui_area")
    .anchor(Align2::LEFT_TOP, [16.0, 16.0])
    .show(&self.egui_ctx, |ui| {
        ui.horizontal(|ui| {
            ui.checkbox(should_display_ui, "Toggle UI");

            ui.scope(|ui| {
                ui.spacing_mut().button_padding = Vec2::new(18.0, 14.0);

                if ui.button("foo").clicked() {
                    // ...
                }
            }
        });
    });
```

**Comment by JMS55** [comment]
Not sure if this actually a bug, or a limitation of immediate mode layout.

**Comment by emilk** [comment]
This is a limitation - egui can't know how tall future widgets will be when adding the first widget. You can call `ui.set_min_height(expected_height);` before adding the first widget to work around this.
