### ISSUE TITLE
Flickering / glow backend not clearing buffer

### ISSUE THREAD

**Issue by Hperigo** [emilk/egui#904]
**Describe the bug**
seems that egui frame doesn't clear properly using glow backend on a mac

**To Reproduce**
1. go to default example for the glow backend
2. add a global clear color variable
3. create a  `ui.color_edit_button_rgb(&mut clear_color);`
4. move the color panel

**Expected behavior**
everything should be clear

**Screenshots**
https://user-images.githubusercontent.com/3333460/142732354-014755b9-9241-4ded-a673-138c8bb5622c.mov

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser 
 - Version 

**Additional context**
Only tested with glow backend in a Mac, so I'm not sure if this happens in other platforms

**Comment by 20iahazban** [comment]
Im also experiencing flickering in Windows 10.
i used (unchanged): https://github.com/emilk/eframe_template

![egui](https://user-images.githubusercontent.com/30409619/142834176-5089abd8-5a37-4b5e-9706-3d13614b6733.gif)
/

**Comment by 20iahazban** [comment]
after digging deeper, i understand my comment does not belongs here but instead of delete my comment you could reference #838
