### ISSUE TITLE
libEGL warning: DRI2: failed to authenticate

### ISSUE THREAD

**Issue by tazz4843** [emilk/egui#911]
**Describe the bug**
Trying to build the example egui template results in an error after packing into an AppImage and trying to run on either 32-bit or 64-bit. 

**To Reproduce**
This can be reproduced with some build scripts:
[Setup](https://github.com/FerrisChat/Client/blob/master/setup_appimage.sh)
[Build](https://github.com/FerrisChat/Client/blob/master/build_appimage.sh)

After building this and trying to run the executable, a window appears for a moment and then closes, with `libEGL warning: DRI2: failed to authenticate` printed in terminal.

**Expected behavior**
For there to be no warning and for the app to run without errors.

* OS: Debian 11
* Desktop env: Xfwm4 Xfce 4.16
* Host: virtual machine on fresh Debian install

**Other info**
Trying to run that same AppImage on the actual host machine (Mint 20.2 with Cinnamon) throws another different error: ` error while loading shared libraries: __vdso_gettimeofday: invalid mode for dlopen(): Invalid argument` and never even flashes a window.

**Comment by tazz4843** [comment]
Quick update: I switched backends from default in `eframe` whatever it is to `egui_glow` and now it loads for a moment, I see the GUI, but then it closes instantly again.

**Comment by imxood** [comment]
I also encountered this problem on Raspberry Pi 3b+
system is raspios-buster-armhf, based on linux debian

**Comment by AlexApps99** [comment]
If it happens on both backends, then it's likely to be an upstream problem with `glutin` or `winit`.
Can you provide any more information, like a backtrace?

**Comment by tazz4843** [comment]
There is no panic/backtrace, just the error followed by process exit. I'm not sure what extra info I could add, but let me know what you need and I can try and find it.

**Comment by AlexApps99** [comment]
Does this virtual machine have hardware acceleration?
It's possible that might be the reason why it doesn't work

**Comment by tazz4843** [comment]
Hardware acceleration was indeed the issue on both 32 and 64 bit systems. 
The other issue however (when copying the created AppImage to the host, `error while loading shared libraries: __vdso_gettimeofday: invalid mode for dlopen(): Invalid argument`) still remains.

 That should perhaps be its own issue tho. Thanks for the help!

**Comment by felipetesc** [comment]
Same on Ubuntu 22.04 - not vm (now it uses wayland as default):

```bash
XXXX@XXXX-XXXX:/mnt/HD1T/Projects/Rust/my_project$ cargo run -- --backtrace
   Compiling my_project v0.1.0 (/mnt/HD1T/Projects/Rust/my_project)
    Finished dev [unoptimized + debuginfo] target(s) in 6.64s
     Running `target/debug/my_project --backtrace`
/mnt/HD1T/Projects/Rust/my_project
libEGL warning: DRI2: failed to authenticateXXXX@XXXX-XXXX:/mnt/HD1T/Projects/Rust/my_project
```
I cloned:
Winit 0.26.1: compiles and examples are ok
glutin 0.28.0: compiles and examples are ok

Than, I build egui_demo_app, 0.18.0. It compiles, but  when I ran the example I got:

```bash
fte@ftx-2022:/mnt/HD1T/Repositories/egui/target/release$ ./egui_demo_app
2022-05-01T01:51:12.561028Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
libEGL warning: DRI2: failed to authenticate
2022-05-01T01:51:12.572625Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1 
```
I googled and I found this similar issue on Bevy: https://github.com/bevyengine/bevy/issues/3753
