### ISSUE TITLE
Storage options: selecting where to save app

### ISSUE THREAD

**Issue by saona-raimundo** [emilk/egui#914]
The current way to have a persistent app is to implement [`epi::App`](https://docs.rs/epi/0.15.0/epi/trait.App.html) and use the feature `persistence`.
In particular, one must implement the method [`save`](https://docs.rs/epi/0.15.0/epi/trait.App.html#method.save).

`save` uses a default location given by:
- `Local Storage` on the web
- [`directories_next::ProjectDirs::data_dir`](https://docs.rs/directories-next/2.0.0/directories_next/struct.ProjectDirs.html#method.data_dir) on native.

But there is no way (as far as I can see) to change the default location.

**Describe the solution you'd like**

I would like to be able to choose where the data is stored. 

**Describe alternatives you've considered**

I propose to exhibit the call to create a [dyn `epi::Storage`](https://docs.rs/epi/0.15.0/epi/trait.Storage.html), so people could change it. 

We could add a method to the [`epi::App`](https://docs.rs/epi/0.15.0/epi/trait.App.html) trait
```rust
fn storage(&self) -> dyn Storage { ... }
```
A default implementation is given by the current behaviour.

**Additional context**

A very simple use case is that I would like to store the app data in a Google drive folder, so I get "persistence" across devices too.

**Comment by wmte** [comment]
> Perhaps the path could be an option in `NativeSettings` ?

I worry this does not address user-selectable paths (ie, a typical File->Save action) which I am trying to unify with the current persistence mechanism.

By [exposing FileStorage](https://github.com/emilk/egui/commit/194507cebd225af587574fa7075739f2de4f15d9) I was able to save to a chosen path on user interaction. In my application I use the default storage behavior as a kind of 'session-resume', but would like to also have manual save and load as I expect users to generate multiple application states.

**Comment by emilk** [comment]
Closed by https://github.com/emilk/egui/pull/4423
