### ISSUE TITLE
Is egui_glium broken?

### ISSUE THREAD

**Issue by zfxstd** [emilk/egui#921]
Hi. Im new to the Rust and im trying to use egui_glium.
I created new rust project (cargo init) , added dependencies and took this example: (Just ctr+c -> ctrl+v): 
https://github.com/emilk/egui/blob/master/egui_glium/examples/pure_glium.rs

I also tried to copy Cargo.toml from example, there is my Cargo.toml https://pastebin.com/az8rzDR7

If im trying to build project, i get following error:
```
λ cargo build
   Compiling rust_test v0.1.0 (M:\dev\rust_test)
error[E0599]: no method named `run` found for struct `EguiGlium` in the current scope
  --> src\main.rs:32:54
   |
32 |             let (needs_repaint, shapes) = egui_glium.run(&display, |egui_ctx| {
   |                                                      ^^^ method not found in `EguiGlium`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rust_test`

To learn more, run the command again with --verbose.

```

So my question is, is it my misstake or not? Thanks!

Windows 10 19043.928, 
i tried rustc 1.53.0 (53cb7b09b 2021-06-17) and rustc 1.56.1 (59eed8a2a 2021-11-01)

i tried this too, but then i get other compilation errors.
```
[patch.crates-io]
egui = { git = "https://github.com/emilk/egui", branch = "master" }
```

**Comment by parasyte** [comment]
If you are using a released version of `egui`, you _cannot_ copy-paste examples out of the main branch and expect them to work. Use the appropriate branch instead: https://github.com/emilk/egui/blob/0.15.0/egui_glium/examples/pure_glium.rs
