### ISSUE TITLE
How to build with latest Rust edition?

### ISSUE THREAD

**Issue by kitepad** [emilk/egui#922]
I installed rust 1.56.1 with toolchain, and I can run cargo build with other rust projects.
But when I build egui (eframe sample, egui_demo) with cargo, prompt me 1.54 will be used and download it, even  I changed cargo.toml to update rust edition as "2021".

**Comment by TENX-S** [comment]
Delete the file `rust-toolchain` under the project root

**Comment by kitepad** [comment]
Got it. Thanks.
