### ISSUE TITLE
Place one widget in one direction and other one in other?

### ISSUE THREAD

**Issue by feelingnothing** [emilk/egui#931]
**Describe the bug**
It doesn't sound like a bug, but there isn't a way (without some hackary with previous values for avaliable width on previous frame) to actually place two widgets on one row with layouts facing different directions (maybe someone familiar with DockPanel in WPF, this basicaly what functionality layout system misses)

**Comment by emilk** [comment]
Without a clear picture of what you are talking about (and what code you tried) it is very difficult to classify this as a bug. Sounds more like [a limitation of immediate mode](https://github.com/emilk/egui#disadvantages-of-immediate-mode) that will be solved if/when we add [multipass support](https://github.com/emilk/egui/issues/843).
