### ISSUE TITLE
Hide title bar of the main eframe in egui app

### ISSUE THREAD

**Issue by arnabanimesh** [emilk/egui#932]
**Is your feature request related to a problem? Please describe.**

Modern apps are run with no title bar. I could not find a way to do such a thing with this egui

**Describe the solution you'd like**

Provide a native option to hide the title bar from the main window

**Comment by creativcoder** [comment]
You can do so using [decorated](https://docs.rs/eframe/latest/eframe/struct.NativeOptions.html#structfield.decorated) field when initializing an eframe window using `NativeOptions`

**Comment by feelingnothing** [comment]
While https://docs.rs/eframe/latest/eframe/struct.NativeOptions.html#structfield.decorated would resolve your issue, but it would make your program basically unmovable on screen, and afaik there's no built-in way to move titlebar moving area to user drawn space (this could be possible with `winapi` on windows, but i'm not sure)

**Comment by arnabanimesh** [comment]
There are many windows apps which includes buttons in the title bar with its own custom colours. Ms office, discord, vscode, any modern web browser.

Check out custom window frame using desktop window manager api. It provides some amazing insights.

In the meantime, can I make the entire frame draggable?

**Comment by feelingnothing** [comment]
> There are many windows apps which includes buttons in the title bar with its own custom colours. Ms office, discord, vscode, any modern web browser.
> 
> Check out custom window frame using desktop window manager api. It provides some amazing insights.
> 
> In the meantime, can I make the entire frame draggable?

I would recommend to open new discussion, I tried to implement it with `epi::Frame#drag_window` but without any luck, strange behaviour bugs with window always slowly snapping back, maybe I will open issue about it

**Comment by arnabanimesh** [comment]
Closing this issue.

**Comment by JiveyGuy** [comment]
@arnabanimesh Did you open a new issue for dragging the entire window?

**Comment by JiveyGuy** [comment]
> You can do so using [decorated](https://docs.rs/eframe/latest/eframe/struct.NativeOptions.html#structfield.decorated) field when initializing an eframe window using `NativeOptions`

I followed the link and it seems structfield.decorated is not there currently.

**Comment by arnabanimesh** [comment]
@JiveyGuy Have you tried [with_decorations](https://docs.rs/eframe/0.26.2/eframe/struct.WindowBuilder.html#method.with_decorations)?
