### ISSUE TITLE
Sense only on button?

### ISSUE THREAD

**Issue by feelingnothing** [emilk/egui#942]
I'm trying to implement my own titlebar, I set `TopBottomPanel` on top and tried to hook `.dragged()` to it and got nothing, looked in the source of the `Input Test` in the showcase app, and found `Button#sense`, after that I tried to add it to panel and then `Frame` and they didn't have this function implemented, how I can sense drag on `Frame` or panel?

**Comment by emilk** [comment]
Did you read https://docs.rs/egui/latest/egui/struct.Response.html#method.dragged ? It links to https://docs.rs/egui/latest/egui/struct.Response.html#method.interact which should be the answer to your question.
