### ISSUE TITLE
Question on request frame integration

### ISSUE THREAD

**Issue by BillyDM** [emilk/egui#95]
I'm creating an `egui` backend on `baseview`, which is a cross-platform windowing library for audio plugins (which have a very different structure to normal windows). The `epi` interface does not fit the way you interact with `baseview`, so I'm not using it.

https://github.com/BillyDM/egui-baseview

Anyway, I've got it working with `baseview`'s API, but I wondered how I'm suppose to detect when I need to redraw the frame?
I see some reference to a "request_frame" callback, but I can't figure out how `egui` actually uses it and how I can detect it. Right now I'm just redrawing every single frame.

**Comment by emilk** [comment]
[`Context::end_frame`](https://docs.rs/egui/0.7.0/egui/struct.Context.html#method.end_frame) returns [`Output`](https://docs.rs/egui/0.7.0/egui/struct.Output.html) which has a [`needs_repaint: bool`](https://docs.rs/egui/0.7.0/egui/struct.Output.html#structfield.needs_repaint). You should paint Egui again the next frame if this is set, or if there is some novel input to Egui (mouse movement, keyboard presses, etc).

**Comment by BillyDM** [comment]
Ah, thank you!
