### ISSUE TITLE
Add multiple mouse button support.

### ISSUE THREAD

**Issue by BillyDM** [emilk/egui#96]
I was a bit surprised to find out there isn't support for right-click. I want to use this for desktop audio applications with my baseview backend. I just find it a bit weird that a GUI library inspired by desktop design doesn't have this.

https://github.com/BillyDM/egui-baseview

I also want to be able to disable the inertia touch scrolling on desktop platforms.

**Comment by emilk** [comment]
I will hopefully be able to get to this in the next couple of week.

**Comment by BillyDM** [comment]
Cool, thank you!
