### ISSUE TITLE
Rendering of Chinese characters is very slow

### ISSUE THREAD

**Issue by lionelfung7** [emilk/egui#962]
**Describe the bug**

To be able to display Chinese in the UI, I added a Chinese TTF file to the fonts.rs file using the font_data.insert() method. This file contains thousands of Chinese characters and some nerd characters. I then recompiled egui_demo_app in debug mode, ran it again, and found that it was very slow to open. After opening it, I tried to enter Chinese characters in an input box and the Chinese characters displayed normally, but they also appear to be slow and sluggish.

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Browser 
 - Version 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by coderedart** [comment]
Did you try release mode? How's the CPU or GPU usage looking when you are running the app?

**Comment by emilk** [comment]
Do you insert the TTF once or every frame? (I've seen people do the latter before)

**Comment by lionelfung7** [comment]
> Did you try release mode? How's the CPU or GPU usage looking when you are running the app?
![egui](https://user-images.githubusercontent.com/50703745/146644624-b39fff55-9570-4097-b914-c5cdb19f9438.png)

After adding Chinese TTF, it took about 10 seconds to open egui_demo_app. Attached is CPU usage. If compiled in Release mode, the opening speed increases by about 5 seconds

**Comment by lionelfung7** [comment]
> 
![add_code](https://user-images.githubusercontent.com/50703745/146644945-fc8e2103-a2e8-4088-8b59-b13ceea4890b.png)
[sarasa-mono-sc-nerd-regular.zip](https://github.com/emilk/egui/files/7739412/sarasa-mono-sc-nerd-regular.zip)
Please refer to the attachment. I have added codes in these two places. I have also attached the TTF file

**Comment by emilk** [comment]
I tried it locally and had no problems with performance. Make sure you compile with `--release`!

**Comment by blueberrynotblue** [comment]
> > 
> 
> ![add_code](https://user-images.githubusercontent.com/50703745/146644945-fc8e2103-a2e8-4088-8b59-b13ceea4890b.png) [sarasa-mono-sc-nerd-regular.zip](https://github.com/emilk/egui/files/7739412/sarasa-mono-sc-nerd-regular.zip) Please refer to the attachment. I have added codes in these two places. I have also attached the TTF file

你好，请问的中文会出现乱码吗？

**Comment by emilk** [comment]
Is this really an issue? If you take https://github.com/emilk/egui/blob/master/examples/custom_font/src/main.rs and modify it with your own font, does it lag? On native, web, or both? Are you using `--release`? Is it the IME that is lagging? Can you use a profiler (e.g. [puffin](https://github.com/emilk/egui/pull/1483)) to track down the problem?

**Comment by blueberrynotblue** [comment]
mine works fine. maybe he didn't context.request_repaint?

**Comment by rdrpenguin04** [comment]
Can this be closed?
