### ISSUE TITLE
Horizontal scroll reversed in Windows native builds

### ISSUE THREAD

**Issue by aevyrie** [emilk/egui#965]
**Describe the bug**
Horizontal scrolling does not respect Windows preferences.

**To Reproduce**
1. Build a native demo on windows
2. Open the plot demo
3. Scroll horizontally and vertically
4. Do the same on the web to compare

**Expected behavior**
Horizontal scrolling, like vertical scrolling, should respect the "native scroll" default behavior.

**Desktop (please complete the following information):**
 - OS: Windows 10/11

**Comment by emilk** [comment]
Duplicate: https://github.com/emilk/egui/issues/356

**Comment by emilk** [comment]
Can you please open a winit issue on this?

**Comment by aevyrie** [comment]
> Can you please open a winit issue on this?

Yes, I forgot to link these issues/PRs, my bad. I filed an issue and submitted a PR upstream: https://github.com/rust-windowing/winit/pull/2101

This egui issue and PR (#966) are only useful as workarounds if the winit issue is not merged for some reason.
