### ISSUE TITLE
[Feature request] Fixed TextEdit width

### ISSUE THREAD

**Issue by lucaspoffo** [emilk/egui#97]
https://user-images.githubusercontent.com/35241085/103775789-51141680-500d-11eb-9005-660db51083ab.mp4

I want to set the text input to a fixed width so it does not change the `SidePanel` width.

**Comment by emilk** [comment]
That's a reasonable feature request, but there is one more piece of imformation needed:

What should happen when the text is too long for the fixed width? Some alternatives:

* Show only portion of the text (scroll to cursor)
* Wrap onto a new line (even if it is a `singeline` `TextEdit`?) (related to https://github.com/emilk/egui/issues/55)
* Truncate text to fit (i.e. forbid adding more characters than fit)

**Comment by lucaspoffo** [comment]
I think the default browser <input />  behavior would be the ideal.

https://user-images.githubusercontent.com/35241085/103950766-3d0b0a80-511c-11eb-8bf5-73721d3511cb.mp4

Show only portion of the text and move the cursor when typing to the end of the typed letter.
When losing focus move the cursor to the start of the input.

**Comment by DGriffin91** [comment]
Is there a way to do this yet by any chance? I tried using max_width, and desired_width but it appears the text box can still grow indefinitely.
