### ISSUE TITLE
Applicaiton hangs when zooming all the way out on a plot

### ISSUE THREAD

**Issue by aevyrie** [emilk/egui#970]
**Describe the bug**
Zooming out on a plot eventually causes the application to hang.

**To Reproduce**
Zoom out on a plot.
Keep zooming out.

**Expected behavior**
Plot should have some maximum limit before an overflow occurs.

**Desktop (please complete the following information):**
 - OS: Windows 10/11
 - Browser Chrome
 - Version 96

**Comment by emilk** [comment]
I can confirm this still happens

**Comment by emilk** [comment]
I think this is fixed actually
