### ISSUE TITLE
eframe: rfd file dialog causes app to freeze on MacOS.

### ISSUE THREAD

**Issue by cessen** [emilk/egui#977]
With the latest version of eframe, attempting to open an rfd dialog will freeze the application.

This appears to be the same as this bug in winit:
https://github.com/rust-windowing/winit/pull/2027

A fix was made, but was only merged recently.  The first release with the fix is 0.26.0, which was also released recently.  However, currently eframe (indirectly through egui-glium/egui-winit) is still using 0.25.0:
https://github.com/emilk/egui/blob/214d2b5d4f10d58c65593fec93fce305e5d7c4fc/egui-winit/Cargo.toml#L25

(This is currently affecting a suite of software tools I'm writing that is pending release, so getting addressed soon would be very appreciated!  Although, of course, I realize this is a volunteer open source project, so I don't mean to be pushy.)

**Comment by emilk** [comment]
Closed by https://github.com/emilk/egui/pull/930

**Comment by cessen** [comment]
Thanks so much!

**Comment by cessen** [comment]
Sorry to re-open, but it looks like the full dependency chain hasn't been updated yet, so eframe still has the bug:

https://github.com/emilk/egui/blob/c69fe941afdea5ef6f3f84ed063554500b6262e8/eframe/Cargo.toml#L31

I'm also not totally sure how specify a dependency on an updated eframe that hasn't been published to crates.io--the syntax in Cargo.toml for specifying a git repository as a dependency doesn't seem to allow sub-paths.  (I'm not looking for help trouble-shooting that, btw, it's just to say that a patch release would be very appreciated if you have the time!)

**Comment by cessen** [comment]
Ah, so upon further investigation it looks like if I specify my eframe dependency as this github repo, Cargo automatically crawls the entire contents and will use this repo for all dependencies with matching crate names.  Sorry for the noise!  (Although I patch release would still be appreciated if you have the time.)
