### ISSUE TITLE
App icon not visible in windows file explorer

### ISSUE THREAD

**Issue by arnabanimesh** [emilk/egui#986]
**Describe the bug**

The icon is not visible in the windows file explorer even though it is visible in the taskbar and title bar of the app.

The icon looks like this:
![image](https://user-images.githubusercontent.com/6032584/147153655-a55ee964-362b-49cb-88ef-ae2f697de441.png)
 whereas it should look like this:
![newspaper](https://user-images.githubusercontent.com/6032584/147153967-694b9535-4704-460d-ae5c-31fa98e70ef7.png)

I have also tried using multi sized icon file (`.ico`) format, but to no avail.

**To Reproduce**
1.  Download [arnabanimesh/headlines](https://github.com/arnabanimesh/headlines)
2.  Compile using `cargo build --release`
3. Go to `target/release` inside the repo
4.  Check the icon of `headlines.exe`

**Expected behavior**

The file icon shown in the file explorer should match with the one shown in the taskbar/title bar

**Screenshots**

Already provided above.

**Desktop (please complete the following information):**
 - OS:  Windows 10 x64 latest
 - Browser  NA
 - Version  NA

**Smartphone (please complete the following information):**
 - Device:  NA
 - OS:  NA
 - Browser  NA
 - Version  NA

**Additional context**

NA

**Comment by t18b219k** [comment]
This is not egui or winit problem.
let see https://stackoverflow.com/questions/30291757/attaching-an-icon-resource-to-a-rust-application
