### ISSUE TITLE
Template app crashes

### ISSUE THREAD

**Issue by NChechulin** [emilk/egui#99]
The [Template app](https://github.com/emilk/egui_template) crashes when the text inside textbox is too long:
```
thread 'main' panicked at 'Mismatching panels. You must not create a panel from within another panel.'
```
[Video](https://youtu.be/nNUvv8MUMd8)
Not sure, whether the issue is in the crate itself or something is wrong with the template app only.

**Comment by emilk** [comment]
Related: https://github.com/emilk/egui/issues/55

**Comment by emilk** [comment]
Thanks for the detailed bug report!
